### PR TITLE
ICDS Dashboard: Web & mobile common nav menu (work in progress)

### PR DESCRIPTION
**Pull request by saiprakash-v**
https://trello.com/c/0OOsD1Pt
##### SUMMARY

Work in progress for using common datastructure for web and mobile navigation menu

### CODE REVIEW

**Comment by czue** [comment]
thanks @saiprakash-v . Looks like a good start. 

Can you highlight the specific issues you ran into with this approach? I think you were mentioning it has to do with preview features and the menus changing under certain conditions?

**Comment by saiprakash-v** [comment]
> thanks @saiprakash-v . Looks like a good start.
> 
> Can you highlight the specific issues you ran into with this approach? I think you were mentioning it has to do with preview features and the menus changing under certain conditions?

certain menu items are displayed only when specific date conditions are met along with feature access

**Comment by czue** [comment]
> certain menu items are displayed only when specific date conditions are met along with feature access

@saiprakash-v can you link me to an example in the code?

**Comment by saiprakash-v** [comment]
> > certain menu items are displayed only when specific date conditions are met along with feature access
> 
> @saiprakash-v can you link me to an example in the code?

https://github.com/dimagi/commcare-hq/pull/26293/files/d9d82f4dfd16908aafd071faaf2cb7caa4e742e9#diff-b7cc134730cae3b8cc67454f140fedce

**Pull request closed without merging**
