### PR TITLE
Style DimagiSphere map based on CommCare color palette

### PR DESCRIPTION
**Pull request by rickypchen**
@esoergel @czue 

Color scheme of DimagiSphere map should be based on CommCare color palette

### CODE REVIEW

**Comment by orangejenny** [comment]
hooray

**Comment by orangejenny** [comment]
screenshot?

**Comment by rickypchen** [comment]
@orangejenny

screen shot 2016-08-11 at 4 27 17 pm

**Comment by orangejenny** [comment]
pretty :)

**Comment by benrudolph** [comment]
😮 😮 😮

**Comment by czue** [comment]
fancy

**Pull request merged**
