### PR TITLE
fix management command

### PR DESCRIPTION
**Pull request by nickpell**
@emord cc: @esoergel @biyeun

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Review by esoergel — APPROVED** [review]

**Comment by esoergel** [comment]
Just a thought - do you need tests running on all of these?

**Comment by emord** [comment]
@esoergel for what it's worth this managment command is actually tested https://github.com/dimagi/commcare-hq/blob/80d6885dd9885adac05c7b265d19f7f9d39e4efd/corehq/apps/cleanup/tests/test_fix_forms_and_apps_with_missing_xmlns.py#L167

but agreed most of these probably won't catch anything

**Comment by nickpell** [comment]
This one has test coverage, and since it's fixing a bug (in django 1.10) I'd like to run tests on just this one.  But after this batch there isn't test coverage for the rest of the management commands, so I'll submit those changes in larger groups.

**Comment by nickpell** [comment]
The reason I suspect most of the remaining management commands don't have coverage is that optparse didn't cause them to fail during tests on django 1.10

**Pull request merged**
