### PR TITLE
Cmitfb migrate by domain

### PR DESCRIPTION
**Pull request by orangejenny**
@emord 

cc @benrudolph

### CODE REVIEW

**Comment by emord** [comment]
Would be nice if this were a command line option, but I don't think that's necessary.

:+1: on :white_check_mark:

**Comment by benrudolph** [comment]
yeah agree `--domain <my_domain>` and `--app-id <app_id>` would be a bit nicer, but not blocking. mergin'

**Comment by orangejenny** [comment]
Curious what y'all see as the downside of the script figuring out whether the given id is an app or a domain - I tend to think that the less user input required, the better.

**Comment by emord** [comment]
@orangejenny I usually think with scary migrations like this the more error checking the better.

**Comment by emord** [comment]
For instance if someone had a domain name that was the same as an app id, then it would be impossible to migrate that domain because it would grab the app first. I don't think that's very likely though

**Comment by benrudolph** [comment]
also just some clarity in the code, i don't think it's very obvious from reading that mgmt command that that arg can be domain or the app_id, but my feelings aren't super strong

**Pull request merged**
