### PR TITLE
B3 care pathways

### PR DESCRIPTION
**Pull request by biyeun**
builds on https://github.com/dimagi/commcare-hq/pull/10763

@lwyszomi @czue for sanity check
cc @emord

### CODE REVIEW

**Comment by czue** [comment]
@lwyszomi are you able to test these reports locally? :+1: from me

**Comment by biyeun** [comment]
@czue can you merge this little guy in? https://github.com/dimagi/commcare-hq/pull/10763 :pray:

**Comment by lwyszomi** [comment]
@czue @biyeun Yes I can test this. I will do this today and I let you know.

**Comment by lwyszomi** [comment]
@czue @biyeun 
I found some issues:
In two reports (Adoption Disaggregated and Table Report Card) when I click apply button, the reports don't have data. I only see information  
```
Why can't I see any data?
Please choose your filters above and click Apply to see report data.
```

In Filters section:
 - popovers doesn't work in Gander, Group Leadership and CBT Name filters
 - very small selects for Gander, Group Leadership and CBT Name filters
 - all filters has different indentation.
filters

**Comment by czue** [comment]
(put a don't merge on until B has a chance to review feedback)

**Comment by biyeun** [comment]
Thanks, will have a look this coming wednesday/thursday. I'm slowing waking up from vacation :)

**Comment by biyeun** [comment]
@kkrampa will be taking this on to wrap it up

**Pull request closed without merging**
