### PR TITLE
Delete enikshay tests

### PR DESCRIPTION
**Pull request by proteusvacuum**
I think these tests take an inordinate amount of time to run, so we should just remove them to speed up everyone's builds

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]
💀 💀 💀 
This is just everything in `enikshay/tests` ? Awesome

**Review by esoergel — APPROVED** [review]

**Review by nickpell — APPROVED** [review]
I have never before APPROVED so strongly a pull request.

**Comment by orangejenny** [comment]
Much appreciated.

**Review by esoergel — APPROVED** [review]

**Comment by mkangia** [comment]
Thanks @proteusvacuum .. 
thinking about all the time spent writing those out.. 😢

**Review by mkangia — APPROVED** [review]

**Comment by proteusvacuum** [comment]
:skull:

**Pull request merged**
