### PR TITLE
Add more detailed assurance steps to PR template

### PR DESCRIPTION
**Pull request by dannyroberts**
## Summary
This PR puts some further boilerplate and checklist items in place to guide PR authors into following a conservative path when it comes to proof that a PR is regression-free. I have also separately installed the https://github.com/marketplace/task-list-completed plugin which will make PRs stay as pending until all boxes are checked.

## Feature Flag
None

## Product Description
None

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] QA labels are set correctly
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

None

### QA Plan

None

### Safety story

This is a change that affects only the PR template, which is not tested, but could not introduce a product defect.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by ctsims — APPROVED** [review]
this looks like a good start to me, although I think there's still not quite an obvious place to say "how did I personally test this" for things that aren't a QA request or automated test coverage, which might be appropriate for some PR's.

**Review by orangejenny — APPROVED** [review]

**Review by millerdev — APPROVED** [review]
I'm not wild about adding this much verbosity to the template, but I understand the motivations. If this reduces regressions it will probably be worth it.

**Review by snopoke — APPROVED** [review]

**Comment by dannyroberts** [comment]
Alright, let's start here and see how it goes

**Comment by orangejenny** [comment]
Having just filled this template out for the first time, I don't think the checkbox for certainty is adding value.

Although I did briefly muse over whether I am ever truly certain of anything.

**Comment by dannyroberts** [comment]
I'm thinking of it as a way of (1) just making people ask themselves whether their plan reaches some threshold of certainty and (2) saying whether they consider their testing plan final and ready for review, or still something they're working on. I think I want there to be some kind of checkbox/lightweight gate that serves those purposes, but I'm open to other options, and definitely to rearranging the placement of checkboxes and wording

**Comment by orangejenny** [comment]
@dannyroberts That makes sense, I'll try it out a few more times and also see what other feedback comes in. I also don't want to immediately start adding churn.

**Pull request merged**
