### PR TITLE
Make sure inline edits of App Name, Form Name, and Module Name update doc Title

### PR DESCRIPTION
**Pull request by biyeun**
Builds off of https://github.com/dimagi/commcare-hq/pull/16741
@orangejenny // @benrudolph 

taking into account suggestion from @proteusvacuum 
- "{form name} - Form Settings - CommCare HQ"
- "{form name} - Edit Form - CommCareHQ"
- "{module name} - Module Settings - CommcareHQ"

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Looks good, though I'm not a fan of `_p` as a variable name.

**Comment by biyeun** [comment]
@orangejenny I use it as a shorthand for `_private`...would you prefer I use that instead?

**Comment by orangejenny** [comment]
yeah - it makes sense when you explain it, but I don't think `_p` alone is a convention in our codebase

**Comment by biyeun** [comment]
@orangejenny resolved conflicts and responded to request

**Review by orangejenny — APPROVED** [review]

**Comment by biyeun** [comment]
@proteusvacuum I just like having some sort of concrete signal that the variable is intended for use throughout the module rather than variables inside a smaller scope. I always did like that distinction between public / private ...

**Pull request merged**
