### PR TITLE
Cs/sc 3385 remove redundant code

### PR DESCRIPTION
**Pull request by Charl1996**
Basing the PR on https://github.com/dimagi/commcare-hq/pull/34695 until it's merged, then I'll rebase on master.

## Technical Summary
[Ticket](https://dimagi.atlassian.net/browse/SC-3385)

This PR simply removes code that is not used currently [nor will likely be used](https://dimagi.atlassian.net/browse/SC-3385?focusedCommentId=329567). 

## Feature Flag
Geospatial

### Safety story
Tested affected areas locally

### QA Plan
QA not planned.

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
Always love it when code gets reduced. :medal_sports:

**Review by ajeety4 — APPROVED** [review]
This is great. Thanks.
(Maybe push these changes for QA planned for the [ticket](https://github.com/dimagi/commcare-hq/pull/34695) , ignore if already planned)

**Comment by Charl1996** [comment]
> This is great. Thanks. (Maybe push these changes for QA planned for the [ticket](https://github.com/dimagi/commcare-hq/pull/34695) , ignore if already planned)

That's a great idea.

**Comment by Charl1996** [comment]
Please note that I force pushed to this PR. I added [this commit](https://github.com/dimagi/commcare-hq/pull/34696/commits/07f6c0237af31ef83b171c656bf8b015dbcb0641) after I rebased on the base branch to solve merge conflicts.

**Review by mkangia — APPROVED** [review]

**Pull request merged**
