### PR TITLE
rename sync_couchdb to sync_couch_views

### PR DESCRIPTION
**Pull request by dannyroberts**
because it was competing with a couchdbkit mgmt cmd of the same name

This was apparently never doing what I thought it was doing—with the result that sync_couchdb wasn't syncing and of the design docs handled by the preindex plugins (couchapps, fluff, apps that have their design docs synced to multiple dbs).

### CODE REVIEW

**Comment by dannyroberts** [comment]
This will fix @katembu's problem.

**Comment by dannyroberts** [comment]
@proteusvacuum @orangejenny (cc @czue)

**Comment by orangejenny** [comment]
should https://github.com/dimagi/commcare-hq/blob/master/docs/management_commands.rst be updated?

**Comment by dannyroberts** [comment]
Hmm, that doc needs to be updated in a couple of respects. I think the full list is quite out of date, and maybe doesn't belong there at all, since you can get the full list by running `./manage.py` with no arguments. I'll make a note of it and clean that page up once this PR's merged

**Comment by orangejenny** [comment]
yeah, having a manual list of mgmt commands might be more annoying to update than it is useful.

will merge this once tests pass.

**Comment by czue** [comment]
ha, definitely never knew about that page

**Pull request merged**
