### PR TITLE
fix reindex queries

### PR DESCRIPTION
**Pull request by snopoke**
@czue 

I discovered a serious issue with these queries. Because the inner queries don't sort each query returns a somewhat arbitrary set of rows so the more pages you have the more rows you are likely to miss.

These queries should do index only scans: https://wiki.postgresql.org/images/3/35/Pagination_Done_the_PostgreSQL_Way.pdf

### CODE REVIEW

**Review by czue — APPROVED** [review]
looks good. just for my own education what was the original purpose of the inner queries (sorry, didn't read the presentation closely - feel free to tell me to look there)?

**Comment by czue** [comment]
kicked build

**Comment by czue** [comment]
do we need to do a reindex?

**Comment by snopoke** [comment]
Yes, this requires a reindex which I'll run.

**Comment by snopoke** [comment]
To answer your question about the purpose of the inner queries - I wrote those before knowing about index only scans. I was trying to write an efficient query that didn't rely of 'OFFSET' (which is slow).

**Comment by czue** [comment]
:+1: thanks

**Pull request merged**
