### PR TITLE
Restrict edits for read only reports

### PR DESCRIPTION
**Pull request by mkangia**
http://manage.dimagi.com/default.asp?237648

Once done we need to remove the copies of Static Reports created. Aware of icds-cas for now.

### CODE REVIEW

**Comment by mkangia** [comment]
@sheelio @czue @NoahCarnahan Review please.

**Comment by czue** [comment]
> Once done we need to remove the copies of Static Reports created.

are you going to follow up on this? should we make a mgmt command or something?

**Comment by mkangia** [comment]
@czue i will follow up on this. Not making a management command. Need to do it carefully so would delete them one at a time.

**Comment by czue** [comment]
> Need to do it carefully 

I actually would have thought this might be an argument for a scripted approach. can we not just delete anything that has a conflicting ID with a static report?

**Comment by mkangia** [comment]
We can. Still want to do it one at a time. Making sure at every step. Also may be trying to avoid writing a management command.

**Pull request merged**
