### PR TITLE
add datespan_filters and has_ucr_datespan as properties in report config json

### PR DESCRIPTION
**Pull request by nickpell**
fixes http://manage.dimagi.com/default.asp?168942

@TylerSheffels

### CODE REVIEW

**Comment by nickpell** [comment]
I'm ok merging this before tests pass and taking care of a hotfix deploy if necessary (trying to enable some time-sensitive workflows)

**Comment by TylerSheffels** [comment]
Tests are going to be delayed a while, and want to get this in before the deploy.  I am going to merge, but someone with more context should take a look. @NoahCarnahan @czue

**Comment by czue** [comment]
I don't really have much context on these saved report filters either but code looks ok to me too. Maybe @NoahCarnahan should also do a pass

**Comment by NoahCarnahan** [comment]
Looks good to me too, thanks Nick.

**Pull request merged**
