### PR TITLE
Migrate Domain.granted_messaging_access to SQL (2 of 3)

### PR DESCRIPTION
**Pull request by orangejenny**
## Technical Summary
Next phase of https://github.com/dimagi/commcare-hq/pull/31370: step 2 of the [vanilla process](https://github.com/dimagi/commcare-hq/blob/master/docs/couch_to_sql_models.rst#conceptual-steps).

First new commit is https://github.com/dimagi/commcare-hq/commit/d04140ec6a3628666cd757d4e13111fc803cce54

### Safety story
This is a fairly small footprint, as it's only touching one attribute.

### Automated test coverage

There are tests of the attribute in the PR.

### QA Plan

Leaning toward requesting QA for this, although it's pretty small as migrations go.

### Migrations
- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by snopoke** [comment]
Closing old PRs, reopen if needed.

**Comment by snopoke** [comment]
Closing old PRs, reopen if needed.

**Comment by millerdev** [comment]
@orangejenny was QA ever requested on this? Should it be reopened?

**Comment by orangejenny** [comment]
@millerdev I don't have time to move this forward, unfortunately, it's reasonable to close this set of PRs.

**Pull request closed without merging**
