### PR TITLE
Remove useless columns

### PR DESCRIPTION
**Pull request by emord**
@calellowitz this should speed up the awc aggregation. Removes 5 full table updates and removes the dependency on two tables. I'm pretty sure this won't conflict with any work you're doing, but if it is I can close it.

Doesn't actually remove the columns, and the tests will fail because I haven't changed the output CSV files yet. I'll finish it before monday's deploy

### CODE REVIEW

**Review by czue — COMMENTED** [review]
code and numbers look good, though guessing @calellowitz should sign off since i have no context

**Review by calellowitz — APPROVED** [review]
I don't really have enough context to know which of these are necessary but seems fine. Should not conflict with any work I did, but a past PR of mine deleted a lot of columns from the django models for the views, and I would be curious to see if we found the same ones.

**Comment by emord** [comment]
I rebased this on latest master because there was a nasty conflict with the test files. realizing now that I didn't need to rebase, but it seemed like the best option at the time

**Comment by emord** [comment]
This should be good to go on approval

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
