### PR TITLE
Make upgrade-requirements

### PR DESCRIPTION
**Pull request by emord**

### CODE REVIEW

**Comment by mkangia** [comment]
Some of those look like big jumps? how do we test this?

**Comment by emord** [comment]
what do you consider a big jump? are you talking about `certifi`? Its because it uses a time based versioning system 2018's last release vs 2019's first release.

scandir is just changing python versions supported https://github.com/benhoyt/scandir/releases

the others are patch level

**Comment by mkangia** [comment]
Ya mainly those two.
certifi would me a `major` version change considering `major.minor.point` version system. It's fine if they use the year, but just that there would be some feature changes in that and not just fixes or minor improvements.

I was just curious though about testing these that how and if we do test these.

**Comment by emord** [comment]
certifi is a downstream dependency of requests. we use requests for every couch call, so its pretty heavily auto tested.

scandir is downstream of ipython, so it doesn't get run live on production.

I think the point of `make upgrade-requirements` is to upgrade the requirements that we are confident can be handled in automated tests https://confluence.dimagi.com/pages/viewpage.action?spaceKey=commcarehq&title=Python+Dependency+Versioning

**Review by mkangia — APPROVED** [review]

**Comment by mkangia** [comment]
Thanks.

**Comment by emord** [comment]
Closing this because there are lots of conflicts due to celery upgrade. moved to https://github.com/dimagi/commcare-hq/pull/23720

**Pull request closed without merging**
