### PR TITLE
No random urls in bower

### PR DESCRIPTION
**Pull request by emord**
noticed this when looking through the IPs list

@benrudolph is there any upside to using the urls that I'm missing

buddy @czue

### CODE REVIEW

**Comment by benrudolph** [comment]
not exactly sure how the internals work, but would this mean that our `cchq` would need a public key on github?

**Comment by emord** [comment]
@benrudolph I don't think so. we're already using similar notation https://github.com/dimagi/commcare-hq/blob/master/bower.json#L48

**Comment by benrudolph** [comment]
cool, sounds good then

**Review by benrudolph — APPROVED** [review]

**Comment by emord** [comment]
Closing this for now. Looks like sinon uses require which would have to be setup

**Pull request closed without merging**
