### PR TITLE
Use addtoblock tag to put inline js in one place

### PR DESCRIPTION
**Pull request by dannyroberts**
This lets inline js code appear in the place it's most logical to write it, but still end up at the end of the document body where inline js belongs. The pattern is

```
{% addtoblock js-inline %}
<script>
...
</script>
{% endaddtoblock %}
```

This code adds that tag and modifies the built-in `{% block %}` tag to include the combined contents of these additions.

Since this PR does move a lot of inline js to the end of the document, that could technically change the behavior on some page or another, so I'll put it up on staging for a bit. We could use this same pattern to put other snippets in their right place including `<script type="html/text">"-style knockout templates, modals, inline css, etc. each in their own place. Curious what others think.

### CODE REVIEW

**Comment by dannyroberts** [comment]
@dimagi/js-team @gcapalbo buddy

**Comment by dannyroberts** [comment]
Ah, this is real

```
======================================================================
ERROR: test_compress_offline (corehq.apps.style.tests.test_compress_command.TestDjangoCompressOffline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/style/tests/test_compress_command.py", line 69, in test_compress_offline
    call_command('compress', force=True)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/vendor/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/vendor/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/vendor/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 302, in handle_noargs
    self.compress(sys.stdout, **options)
  File "/vendor/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 249, in compress
    rendered = parser.render_nodelist(template, context, node)
  File "/vendor/lib/python2.7/site-packages/compressor/offline/django.py", line 125, in render_nodelist
    return node.nodelist.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/mnt/commcare-hq-ro/corehq/apps/hqwebapp/templatetags/hq_shared_tags.py", line 470, in render
    request_blocks = AddToBlockNode.get_request_blocks(context)
  File "/mnt/commcare-hq-ro/corehq/apps/hqwebapp/templatetags/hq_shared_tags.py", line 460, in get_request_blocks
    request_blocks = context['request']._addblock_contents
  File "/vendor/lib/python2.7/site-packages/django/template/context.py", line 70, in __getitem__
    raise KeyError(key)
KeyError: 'request'
```
I'll take this off staging and find a smarter way to store this data.

**Comment by gcapalbo** [comment]
looks ok to me, would be good for someone on @dimagi/js-team to take a pass too

does this need any qa at all, or putting it on staging is enough? (seems like there are a few specific templates that were also updated)

**Comment by dannyroberts** [comment]
All the templates I touched are partials imported directly onto `base.html`. There are tons of places in all our templates where we can use this, but I thought I'd just start with the things in the base template.

I'm largely concerned with things like it breaking the way `{% compress %}` and static files work, which is harder to test locally, and also just clicking around and making sure there are no JS errors due to the change in order. While there could be harder-to-find bugs too, my sense is that full QA is a big lift that's still likely not to find a hidden-but-unlikely bug. So I'd initially say it's not worth it, but happy to be talked down.

**Comment by gcapalbo** [comment]
ok, just wanted to make sure we thought it through

**Comment by dannyroberts** [comment]
Been on staging for a while without any apparent issue, so I'm calling this good to go!

**Pull request merged**
