### PR TITLE
add rebuild_care_pathways_fluff mgmt cmd

### PR DESCRIPTION
**Pull request by dannyroberts**
to rebuild pillows on all care_pathways domains

http://manage.dimagi.com/default.asp?230124

### CODE REVIEW

**Comment by dannyroberts** [comment]
would like to get this in to deploy today for @kkrampa. FYI @czue buddy @calellowitz

**Comment by dannyroberts** [comment]
(I can run this after deploy today)

**Comment by czue** [comment]
nice use of coding to save you mindless work.

**Comment by dannyroberts** [comment]
Yeah I was also pretty sure I'd f 💣 it up if I had to run 8 commands

**Comment by dannyroberts** [comment]
thanks!

**Pull request merged**
