### PR TITLE
Externalize js: Management Commands

### PR DESCRIPTION
**Pull request by orangejenny**
Low-hanging fruit. Review commit by commit.

@mkangia

### CODE REVIEW

**Comment by orangejenny** [comment]
tests pass

**Comment by snopoke** [comment]
Is this page useful? Could we just kill it?

**Comment by orangejenny** [comment]
@snopoke Yeah, good point. Analytics say it's accessed occasionally, but I suspect those aren't real usages and are people semi-randomly clicking because it's an item in the top menu dropdown. Checked with A team and didn't find anyone who uses it. Will kill.

**Comment by snopoke** [comment]
👍☠

**Pull request closed without merging**
