### PR TITLE
B3 Chat over SMS page

### PR DESCRIPTION
**Pull request by biyeun**
@gcapalbo 

Is there a good domain on staging I can test the data with? It should just be g2g. If it's not too much of a hassle, could you do a quick QA locally?

Thanks!

screen shot 2016-02-22 at 5 30 20 pm

### CODE REVIEW

**Comment by gcapalbo** [comment]
sure, i'll do a pass on it locally

**Comment by biyeun** [comment]
@gcapalbo wondering if you were able to get to taking a closer look at this one

**Comment by gcapalbo** [comment]
sorry, this fell off my radar, i'll test this locally

**Comment by gcapalbo** [comment]
@biyeun looks good, i just had to make one update for the upgrade to datatables 1.10

**Pull request merged**
