### PR TITLE
add new users

### PR DESCRIPTION
**Pull request by mkangia**
updates new users added for another round of aks audit

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Review by snopoke — COMMENTED** [review]
should these not be in localsettings?

**Comment by mkangia** [comment]
they can be. Are you saying from configuration perspective or security?

**Comment by snopoke** [comment]
from the perspective of trying to decouple icds code from commcare-hq

**Comment by mkangia** [comment]
@snopoke this got delayed. I guess this is already resolved by the code movement you have done, please let me know if otherwise.

**Comment by snopoke** [comment]
I have not touched this app in the code move

**Pull request merged**
