### PR TITLE
update submission metrics

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Review by czue — APPROVED** [review]
kicked build

**Comment by dannyroberts** [comment]
Hey I merged in https://github.com/dimagi/commcare-hq/pull/24866 as the quickest fix to the pervasive 500s, which is what's causing the conflict. Feel free to undo it and solved differently if you have a better way to fix the issue

**Review by millerdev — APPROVED** [review]

**Comment by emord** [comment]
would it be better to have this sort of non-critical reporting moved to a pillow?

**Comment by snopoke** [comment]
> would it be better to have this sort of non-critical reporting moved to a pillow?

I think it's better to have it here. If pillows get behind then the metrics would also get skewed.

**Pull request merged**
