### PR TITLE
Remove phone number views

### PR DESCRIPTION
**Pull request by gcapalbo**
Removes 4 couch views
@dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by gcapalbo** [comment]
closing this, once https://github.com/dimagi/commcare-hq/pull/11934 is merged and i delete the old docs, we can merge

**Comment by dannyroberts** [comment]
https://github.com/dimagi/commcare-hq/pull/11934 merged, does this mean we can reopen this?

**Comment by gcapalbo** [comment]
not yet, i'll run the script and then we can reopen

**Comment by orangejenny** [comment]
@dannyroberts Do you remember anything about this? Looks like those 4 views are still around and there are still `VerifiedNumber` docs on couch, although all code references to `VerifiedNumber` are gone other than in the deletion script. I'm wondering if this would be low-hanging fruit to kill.

**Comment by dannyroberts** [comment]
Agree! From the context in this PR and the one Giovanni referenced, I think we just need to run `cchq proudction django-manage delete_messaging_couch_phone_numbers` (and maybe on other environments?) to delete the docs from couch, and then we can reopen this PR. I checked and those views still have data in them, so it appears that Giovanni never did end up running the script.

**Comment by orangejenny** [comment]
@dannyroberts Sounds good. Checking other environments, india has `VerifiedNumber` documents, but swiss, pna, and icds are all clear. I'll run the deletion script on prod and india, probably later today, and then reopen this.

**Comment by orangejenny** [comment]
Replacing this with https://github.com/dimagi/commcare-hq/pull/26192

**Pull request closed without merging**
