### PR TITLE
remove tornado

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by czue** [comment]
@snopoke

**Comment by snopoke** [comment]
:+1:

**Comment by snopoke** [comment]
Pretty sure build will pass

**Comment by czue** [comment]
(killed)

**Comment by nickpell** [comment]
should ```tornado``` be added to ```requirements/uninstall-requirements.txt```?

**Comment by czue** [comment]
i was wondering that too - i think it can't hurt!

**Comment by czue** [comment]
https://github.com/dimagi/commcare-hq/pull/8788

**Pull request merged**
