### PR TITLE
fix circular import

### PR DESCRIPTION
**Pull request by dannyroberts**
tests were passing but you could't actually run runserver

introduced in commit 21a74f6888a98a7629c1e5298f77ac90f70a723e

### CODE REVIEW

**Comment by benrudolph** [comment]
good find, will wait for tests

**Comment by benrudolph** [comment]
test failure looks real

**Comment by dannyroberts** [comment]
:poo:

**Comment by dannyroberts** [comment]
I need to either change how the mock's working or fix the circular import in a different way

**Comment by dannyroberts** [comment]
last commit makes dhis2 tests pass locally

**Comment by czue** [comment]
weird about tests not catching that. thanks, and sorry!

**Pull request merged**
