### PR TITLE
Make app-level test dependencies for locations

### PR DESCRIPTION
**Pull request by esoergel**
The dependencies in the test class were out of date.  I've confirmed that the full locations test suite passes locally.

### CODE REVIEW

**Comment by esoergel** [comment]
@czue @benrudolph

**Comment by czue** [comment]
here i was waiting for the build and there was a hidden `[ci skip]`

**Comment by benrudolph** [comment]
nice

**Comment by esoergel** [comment]
@czue yeah, figured it didn't make sense, since travis doesn't use the dependencies thing

**Pull request merged**
