### PR TITLE
Replace xlsx files with raw-data in Tests

### PR DESCRIPTION
**Pull request by sravfeyn**
This makes the xlsx test data easily readable, and makes it easy to be tracked in git (you can't diff the binary xlsx files in git, and if there are merge conflicts on the binary files, you have to scan those xlsx files cell by cell. Hopefully writing raw data like in these tests will help git to show the diff and help us).

Curious to see if there are any downsides to this though

@orangejenny

### CODE REVIEW

**Comment by sravfeyn** [comment]
Wait for tests

**Comment by dimagimon** [comment]
There are 17 errors:

* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 114 - E501 line too long (154 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 120 - E501 line too long (124 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 125 - E121 continuation line under-indented for hanging indent
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 125 - E501 line too long (129 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 126 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 129 - E121 continuation line under-indented for hanging indent
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 136 - E121 continuation line under-indented for hanging indent
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 141 - E501 line too long (160 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 148 - E501 line too long (176 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 150 - E501 line too long (140 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 155 - E501 line too long (129 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 156 - E501 line too long (128 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 172 - E121 continuation line under-indented for hanging indent
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 249 - E501 line too long (138 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 256 - E501 line too long (144 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 266 - E501 line too long (144 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 268 - E501 line too long (134 > 115 characters)

**Comment by sravfeyn** [comment]
Feels like not helpful. Close it unless you see any improvement.

**Comment by esoergel** [comment]
I like the idea.  Is the conversion from csv to xlsx easy?  You could store the test data in csv (which should be diffable and text-editor readable), then convert xlsx in the test code.

**Comment by orangejenny** [comment]
I like this idea, too - modifying .xls-based tests is annoying, and handling merge conflicts is awful.

**Comment by sravfeyn** [comment]
csv to xlsx would be ideal and better than this tuple format. But we already have helpers methods that take format like this and generate excel. I intended to do it using csv, but it needs little more digging and it felt far too much off of what I was working on.

**Comment by esoergel** [comment]
Fair enough.  The python csv library is pretty straightforward, here's how you take a file and convert to nested tuples:
```python
import csv
with open('/path/to/my/file.csv') as f:
    lines = tuple(map(tuple, csv.reader(f)))
```
There's probably a `convert_csv_to_xlsx` function somewhere out there that'd be even better, but I understand if figuring this out is beyond the scope of what you wanted to accomplish.

**Comment by sravfeyn** [comment]
Yeah, exactly.

Having it as tuples is not as bad either, since all of the data will be in once place. With csv there is overhead of adding files for each sheet etc.

**Comment by czue** [comment]
@sravfeyn @esoergel @orangejenny I think this is a net improvement. any reason not to merge as is?

**Comment by sravfeyn** [comment]
The build just passed (It got struck for some reason till now, I kicked it again in the morning).

**Comment by czue** [comment]
cool, i'll let @esoergel decide whether he wants to block anything

**Comment by sravfeyn** [comment]
This https://github.com/dimagi/dimagi-utils/pull/287 has helper utils to convert more xlsx tests to this format

**Comment by orangejenny** [comment]
Looks good to me. I have a slight preference for CSV (I'd rather have data live in data files than in code files, but care more about that when you're dealing with large sets of data), but this is still a major improvement over editing xls files.

**Comment by esoergel** [comment]
:shipit:

**Pull request merged**
