### PR TITLE
friendly error page fr browsers that don't accept cookies

### PR DESCRIPTION
**Pull request by sravfeyn**
If you block cookies and try to login you will see dirty 403 error. This PR shows a friendlier error telling that HQ needs cookies to work
screen shot 2015-04-20 at 11 07 12 am

### CODE REVIEW

**Comment by snopoke** [comment]
Do we need to display the '403'?

**Comment by sravfeyn** [comment]
Hmm, may be not. I put it to only indicate that it is 403. Should I remove it?

**Comment by snopoke** [comment]
Most user's won't know what the 403 means so I think best to remove it.

**Comment by czue** [comment]
:+1: good call @sravfeyn !

**Pull request merged**
