### PR TITLE
Handle HTML entities in inline edit widget

### PR DESCRIPTION
**Pull request by orangejenny**
https://github.com/dimagi/commcare-hq/pull/12226/files/908e129b8dab8df2fe068c92034722ee4606910b#r68423138

That was easier than expected.

@millerdev

### CODE REVIEW

**Comment by millerdev** [comment]
Is the test failure is unrelated? (I think it is)
```
ERROR: test_basic_completed_by_user (corehq.apps.reports.tests.test_esaccessors.TestFormESAccessorsSQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/reports/tests/test_esaccessors.py", line 238, in test_basic_completed_by_user
    self._send_form_to_es(completion_time=datetime(2013, 7, 2))
  File "/mnt/commcare-hq-ro/corehq/apps/reports/tests/test_esaccessors.py", line 94, in _send_form_to_es
    form_pair.wrapped_form._attachments.update(attachment_dict)
AttributeError: 'XFormInstanceSQL' object has no attribute '_attachments'
```

**Comment by millerdev** [comment]
Solution looks great!

**Comment by orangejenny** [comment]
test failure does look unrelated; kicking build

**Comment by millerdev** [comment]
Is the test failure possibly related to https://github.com/dimagi/commcare-hq/pull/12239?

**Comment by orangejenny** [comment]
ooh, probably - thanks! merged master.

**Comment by millerdev** [comment]
merging because tests passed prior to merging master.

**Pull request merged**
