### PR TITLE
Gather some metrics for app-status-report export

### PR DESCRIPTION
**Pull request by sravfeyn**
@Rohit25negi

### CODE REVIEW

**Comment by sravfeyn** [comment]
@calellowitz

**Comment by sravfeyn** [comment]
Bump @calellowitz

**Review by calellowitz — APPROVED** [review]
Is this something that we want to track on datadog instead of via email? otherwise, the metrics themselves look fine

**Comment by sravfeyn** [comment]
I feel this is needed for a one-off performance exercise, so email seems ok for now. If they grow out of hand, I will change it to datadog.

**Pull request merged**
