### PR TITLE
fetch treating hospital as the pcp if its available and has nikshay code

### PR DESCRIPTION
**Pull request by mkangia**
Change requested:
To use treating hospital as the pcp if its present and has a nikshay code when sending nikshay registration notifications.

This modifies it for both Nikshay and 99dots.
@proteusvacuum does that sound right to change for 99dots as well?

### CODE REVIEW

**Comment by mkangia** [comment]
Hey @proteusvacuum, can you review this one?

**Comment by proteusvacuum** [comment]
@mkangia sent an email to 99DOTS. I'm not sure we will want to do this for them, but checking.

**Comment by mkangia** [comment]
@proteusvacuum looks like we are good here to merge?

**Comment by proteusvacuum** [comment]
yup!

**Pull request merged**
