### PR TITLE
remove "local install" route and related code from web apps

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
As far as I can tell this is never used but can still be called by adjusting the URL. I've examined the code and don't see any usages of the route. I also verified that the corresponding route on Formplayer has not been called in the past month.

Allowing 'local install' poses a [security risk](https://docs.google.com/document/d/13mAWSnp6Y1l-O90mJglxiA7eBUSSMoBt5t3jyViwGfU/edit).

## Safety Assurance
- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
I don't think is any coverage for this.

### QA Plan
Can QA this on staging using the regression test plan along with the associated Formplayer PR.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by ctsims — APPROVED** [review]

**Review by orangejenny — APPROVED** [review]
Looks like this was added for eNikshay's calendar, though I don't know exactly what it was for: https://github.com/dimagi/commcare-hq/pull/13144

**Comment by dannyroberts** [comment]
That's a nice find @orangejenny. To give another dimension of safety I also grepped request/response logs on all production formplayer machines for `installReference`, and it didn't appear in any of the files. Unless I'm getting the name of the property wrong, I think that means that this feature isn't used, and neither is the corresponding formplayer feature (of accepting that in the API).

**Review by dannyroberts — APPROVED** [review]

**Comment by orangejenny** [comment]
@dannyroberts good call checking the request/response logs

**Comment by snopoke** [comment]
> That's a nice find @orangejenny. To give another dimension of safety I also grepped request/response logs on all production formplayer machines for `installReference`, and it didn't appear in any of the files. Unless I'm getting the name of the property wrong, I think that means that this feature isn't used, and neither is the corresponding formplayer feature (of accepting that in the API).

Thanks for double checking that @dannyroberts. I did mention I'd already checked this. I used the cloudwatch logs to check all proxy logs for the past month.

**Pull request merged**
