### PR TITLE
Add vellum_case_management flag to ES

### PR DESCRIPTION
**Pull request by orangejenny**
@emord / @kaapstorm

### CODE REVIEW

**Comment by emord** [comment]
:+1: once this build passes: https://travis-ci.org/dimagi/commcare-hq/builds/143412332

**Comment by proteusvacuum** [comment]
FYI, this kicked off a large ES preindex this morning. When changing pillow mappings, please add the `reindex/migration` label so it can get merged before a weekend :)

**Comment by emord** [comment]
@proteusvacuum sorry about that! I thought the only ES indexes that took a long time were forms/cases

**Comment by orangejenny** [comment]
this is why we can't deploy? sorry @proteusvacuum , didn't realize it would be so large :-/

**Comment by proteusvacuum** [comment]
It's OK, I don't think it was a time thing, we just ran out of diskspace on the machine it was running on.

**Pull request merged**
