### PR TITLE
Refactor, test and fix doc_in_es

### PR DESCRIPTION
**Pull request by sravfeyn**
Fixes this view for ES7 (plus tests/refactor)

@kaapstorm

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
Looks good.

Test failure might be related.

**Comment by kaapstorm** [comment]
(:recycle: :construction_worker: just to check. It'll fail in 6 mins if it's legit.)

**Comment by kaapstorm** [comment]
( :heavy_check_mark: nice)

**Comment by sravfeyn** [comment]
Thanks!

**Pull request merged**
