### PR TITLE
Dont allow first character to be number in table name

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?232475#1187063

@millerdev 
FYI @phillipm, bugcatcher extraordinaire

### CODE REVIEW

**Comment by millerdev** [comment]
👍 - @proteusvacuum: I'm not sure about the tests on this one. Looks like travis may have been canceled. Do you know anything about that?

**Comment by czue** [comment]
`is_identifier_invalid` looks like a useful thing to have a few quick tests for. 

another thought which I'm not sure of would be to run this through an XML library for parsing validation. e.g.
```python
from xml.etree import ElementTree
try:
  ElementTree.fromstring('<{identifier} />'.format(identifier))
except ParseError:
  return False
```

(neither of those comments blocking, just thoughts)

**Comment by proteusvacuum** [comment]
@czue that is a nice idea. I wonder if there is value in also doing that when sending payloads down to the phone (where it would alert us that malformed xml was sent).

**Comment by phillipm** [comment]
It would be useful to have a report that the support team/HQ devs could look at, saying what users were sent invalid restores. That way y'all could identify places where user input isn't sanitized and proactively correct it.

**Comment by czue** [comment]
i like both of those ideas. seems like we should at least soft assert the full restores through an xml parser to see how common something like this is (and then we'd have an ad-hoc report in our email/logs)

**Pull request merged**
