### PR TITLE
Use elasticsearch 2.4.6 in docker setup

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
Like https://github.com/dimagi/commcare-hq/pull/25744 before it, this PR is just to test master against Elasticsearch 2.4.6.

### CODE REVIEW

**Comment by dannyroberts** [comment]
✅  Wooo!

**Comment by dannyroberts** [comment]
SaaS is nearly done upgrading ES to 2.4.6. I wanted to open the discussion with ICDS and Solutions about what more we need to happen before (1) we can merge this PR and have our tests run against (and only against) ES 2.4.6 and (2) what other followup steps there are before this round of the ES upgrade is out of our hands. For example @esoergel let me know how you want to manage this with respect to third parties. I am assuming at least part of the story is reformatting Sanjay's upgrade steps https://docs.google.com/document/d/1mse51QZe3WMj7R6pwtRPPvU4Dlp4E4FfqR1WJLNMDW0/edit?ts=5df72a78 as a changelog entry

**Review by millerdev — APPROVED** [review]

**Comment by esoergel** [comment]
Thanks for flagging, @dannyroberts.  Will y'all be converting that doc to a changelog, or should we?  It's on Solutions to announce to users, certainly.  We'll also need to set a deprecation date.

The last such upgrade I'm aware of was the Python 3 migration, which was announced [here](https://forum.dimagi.com/t/python-2-deprecation-notice-30-days-to-upgrade/6699).  That seems like a reasonable precedent to follow.  We gave a 30 day deadline (from the announcement) for the upgrade, though Andrea points out in retrospect that time frame was a little short.  Would 6 weeks be acceptable?

**Comment by snopoke** [comment]
Thanks @dannyroberts. ICDS is almost ready to upgrade, we're just waiting for some additional resource approval before we do so which I'm hopeful we will get this week.

I agree with @esoergel that we should give 3rd parties a period of warning. I'm not sure if that means we should hold off on merging this until that period is up or if it's OK to just commit to fixing any issues that arise during the period. Considering that there is very little development work happening around ES it seems relatively low risk to merge this now.

**Comment by dannyroberts** [comment]
Sorry for the looong delay here. We offlined on some of this but just wanted to give an update
- Sanjay's working on the upgrade instructions as you both saw in https://github.com/dimagi/commcare-cloud/pull/3580
- ~6 weeks sounds totally fine. Want to set a date like March 31 as the last day we commit to supporting ES 1 in new releases of CommCare HQ?

The last thing I wasn't totally sure of before merging this PR as is is if someone's production environment does not have `ELASTICSEARCH_MAJOR_VERSION` in their localsettings file, then it would get implicitly updated to `2` when this PR is merged. Since we first added that in [mid Dec](https://github.com/dimagi/commcare-cloud/pull/3473), @esoergel is it fair to assume all third parties would have updated their localsettings.py since then and gotten the explicit default of `ELASTICSEARCH_MAJOR_VERSION = 1`?

**Comment by esoergel** [comment]
> ~6 weeks sounds totally fine. Want to set a date like March 31 as the last day we commit to supporting ES 1 in new releases of CommCare HQ?

Yeah, that sounds fine to me, as long as we announce publicly at least 6 weeks in advance of that (meaning next Tuesday, I believe).  Solutions is planning on doing a write-up of expectations around this sort of thing, I'll see if we can bump the priority on that, as it seems pretty relevant.

> @esoergel is it fair to assume all third parties would have updated their localsettings.py since [mid December] and gotten the explicit default of ELASTICSEARCH_MAJOR_VERSION = 1?

I'm not sure we can say that with confidence.  Think it'd be sufficient to address in the changelog entry?  Or are you worried someone might do another operation first, declaring the ES version as 2 when it isn't?

We do need to improve messaging around what we expect of third-party environments if deploys and upgrades are to go smoothly (things like "you should deploy at a minimum once every two weeks").  Would you say running `update_config` on a regular basis should also be part of that obligation?

**Comment by dannyroberts** [comment]
> Would you say running update_config on a regular basis should also be part of that obligation?
That's a good question. Maybe it isn't, and we only expect them to run it when it says to do so in a changelog?

I think if we don't expect them to run it, we can't merge this PR as is until we're past the date we expected everyone to run through the changelog entry by. I think what I'll do is update the docker version (so that we're running tests against ES 2.x) now, but keep `ELASTICSEARCH_MAJOR_VERSION = 1` in settings.py, but update it in docker localsettings and in localsettings.example.py and announce to the team that people should update it in their own localsettings as soon as they've rebuilt their ES docker container with the new version.

> Yeah, that sounds fine to me, as long as we announce publicly at least 6 weeks in advance of that (meaning next Tuesday, I believe). Solutions is planning on doing a write-up of expectations around this sort of thing, I'll see if we can bump the priority on that, as it seems pretty relevant.

Sounds good. Let's do this: let's say that as soon as we merge in the changelog entry, we set a date that is **7** weeks out, I make sure to inform you @esoergel that it's ready and of the date, and that will give Solutions a week to follow your announce process, and be within the 6 week time window. Does that sound like a good way to coordinate our teams' relevant efforts? (For future things like this we can still defer to your write-up of expectations once that's settled on.)

**Comment by esoergel** [comment]
I'm on board with both of those things.  Sounds good!

**Comment by dannyroberts** [comment]
@dimagi/team-commcare-hq next time you start up the local docker services, it'll likely rebuild your elasticsearch container with the new version of elasticsearch. When that happens make sure to update your localsettings to include

```
ELASTICSEARCH_MAJOR_VERSION = 2
```
which is also now the value used in localsettings.example.py

**Pull request merged**
