### PR TITLE
Invalidate initial restore cache on form submission for everyone!

### PR DESCRIPTION
**Pull request by proteusvacuum**
Async restores were forcing initial syncs to be cached in redis, however this cache wasn't getting invalidated when a user submitted a form. Now, they are invalidated when that user submits any form. 

I'm not 100% sure this is desired behaviour, as this deviates from non-async domains which do the following:
- if the initial sync took over 1 minute, store the cache
- this cache gets invalidated after an hour, no matter if that user submitted forms or not (i.e. if they clear user data and do a restore - they will get old data)

Async domains now do the following:
- always cache the initial restore
- if the user submits a form, or after an hour, invalidate the cache (i.e. the initial restore is always recomputed if the user submits a form).

@phillipm was having issues with the integration tests as AFAIK it was relying on clearing user data and verifying that a restore worked properly.

@snopoke, do you think that we should invalidate initial restores when users submit a form for non async domains too?

CC: @kaapstorm

### CODE REVIEW

**Comment by czue** [comment]
> do you think that we should invalidate initial restores when users submit a form for non async domains too?

I know you didn't ask me, but that sounds good to me if not hard.

**Comment by snopoke** [comment]
> do you think that we should invalidate initial restores when users submit a form for non async domains too?

Agree with @czue. It's unlikely to happen often but would make it hard to debug if it did arise. Also it makes sense to have the 2 modes be consistent.

**Comment by snopoke** [comment]
:boot: :construction:

**Comment by snopoke** [comment]
merged master to fix build

**Comment by proteusvacuum** [comment]
Added invalidation whenever there is a form submission.
Also, ✅

**Comment by snopoke** [comment]
:+1:

**Comment by phillipm** [comment]
@proteusvacuum heads up that I'm still having issues with this: initial login restores a case that has been closed, but an incremental sync then correctly clears that case.

**Comment by proteusvacuum** [comment]
@phillipm and I offlined about this, but the script he was using to submit a form doesn't include a user_id, so the cache isn't getting invalidated. We'll update the script so HQ knows which user's cache to invalidate.

**Pull request merged**
