### PR TITLE
Remove eventlet from requirements and uninstall

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
We believe the presence of eventlet has been the cause of the sms_queue issues in
https://dimagi-dev.atlassian.net/browse/PLAT-188. As noted there, I have tested that
errand-boy, the only thing that has an eventlet dependency, continues to work when eventlet
is uninstalled, and confirmed that it appears to just be a testing dependency from the codebase.

##### PRODUCT DESCRIPTION
Should (hopefully) fix some recent daily delays in sms processing (UPDATE: by itself this PR didn't have the desired effect)

### CODE REVIEW

**Comment by emord** [comment]
@dannyroberts are you aware of https://github.com/dimagi/commcare-cloud/pull/2719 and https://github.com/dimagi/commcare-cloud/pull/2729. The are slightly different issues, but could be the same core issue since they were also gevent queues.

This may also allow us to re-add datadog APM for prod again?

somewhat relatedly we're running a fork of celery https://github.com/dimagi/commcare-hq/blob/6fb22b04803270979af3692548f5498908d278e4/requirements/requirements.in#L7 should that be brought in house or should we explore getting back to mainline as the core issue was with gevent https://github.com/celery/celery/issues/4737 ? I think at the moment if that @nickpell guy was a jerk and deleted that repo we might be SOL on deploying new code :P

**Review by emord — APPROVED** [review]
the manual removing of a dependency feels sketchy to me but it does appear you've done your due diligence  to make sure its safe

**Comment by dannyroberts** [comment]
@emord thanks for the links and pointing out our celery branch is not owned by Dimagi.

I'm fairly sure the error we're seeing this time with sms_queue isn't either of the things you linked, and this fix probably won't solve the issue faced there (though I guess who knows?). I made a ticket to look at the reasons we aren't on 4.3.0 and try to upgrade to that and work around those issues rather than stay permanently in this weird fork situation: https://dimagi-dev.atlassian.net/browse/PLAT-220.

As for manually removing being icky, yeah I agree it's not my favorite. I've made an issue on errand-boy asking if they'd consider moving `eventlet` to `tests_require` if that's the reason it's included at all. If they respond positively, we might be able to get rid of this workaround once they release a new version.

**Review by snopoke — APPROVED** [review]

**Comment by dannyroberts** [comment]
Oh I see duh, uninstall-requirements is run before pip install, so the fact that `errand-boy` is in the `pip install` means that it pulls in the eventlet dependency there, installing it again right after it was uninstalled. So net this PR does basically nothing except unpin the eventlet version 🤦‍♂. We might have to fork errand boy to remove the dependency there, because I don't know of a way of noting inside a requirements.txt to ignore a particular dependency.

**Comment by dannyroberts** [comment]
Or maybe the simpler thing to do is to just add a file for things we need to install _after_ deploy. Hopefully it's something that they get to soon but so far no response on https://github.com/greyside/errand-boy/issues/7

**Pull request merged**
