### PR TITLE
schedule once

### PR DESCRIPTION
**Pull request by calellowitz**
@biyeun this adds the schedule once widget to the current subscription page. will also be added to a few prelogin ones as per https://docs.google.com/document/d/1IiK3kj-wlHaOdokTP2RQ9f1ehTXiJkf0VCpthc5wvRc/edit#

I would love a second set of eyes on the colors. I grabbed the shades from the style guide but wasnt sure I should even be using the main blue and green.
screen shot 2017-02-09 at 4 44 00 pm
screen shot 2017-02-09 at 4 44 10 pm

### CODE REVIEW

**Review by biyeun — CHANGES_REQUESTED** [review]
- put white text on green
- adding `btn btn-success` to each button will take care of the above real quick. 
- add `form-control` to each of the form inputs
- make the header background around free 1-on-1 Consultation the darker color `@cc-brand-low` in the less  or `#002c5f` if you have to edit elsewhere
- get rid of the white border.
- add a box shadow `box-shadow: 0 0 5px rgba(0,0,0,.25);` to the outer container element and see how that looks
- make sure the padding around the container is `15px`
- The font for this looks slightly off. Make sure the plugin is not overriding the `font-family` from body on this page

**Comment by biyeun** [comment]
@calellowitz if you need any help on this, I am available on monday most of the day and can skype in remotely. I have user testing today from 1-5. If this is urgent, we might be able to work something out.

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
Don't merge just yet...conflicts from comms team

**Comment by calellowitz** [comment]
@biyeun cc: @NoahCarnahan this is ready for merge. (the prelogin pair to this is still not)

**Pull request merged**
