### PR TITLE
Clean up support-related emails

### PR DESCRIPTION
**Pull request by orangejenny**
Part of https://dimagi-dev.atlassian.net/browse/ICDS-1304 / https://dimagi-dev.atlassian.net/browse/SAAS-10710

I switched `CCHQ_BUG_REPORT_EMAIL` (the from address for bug reports) to the normal noreply email, because it didn't seem worth having a specific email for bug reports. Guessing this existed so that in bygone days people could filter their email. Also deprecated `BUG_REPORT_RECIPIENTS` because all bugs now go through support.

I don't think either of these decisions will be controversial or affect localhosting (doubt anyone doing localhosting currently does much with bug reports), but anyone feel free to push back. FYI @dimagi/product and @esoergel

### CODE REVIEW

**Comment by orangejenny** [comment]
@kishansampat @kcowger specifically, please confirm that the changes mentioned in the description are okay with you. Will mark this PR "don't merge" in the meantime.

**Comment by kcowger** [comment]
@orangejenny thanks for doing this. 

Just to be clear, when you say you switched CCHQ_BUG_REPORT_EMAIL to the normal noreply email, that's not support@, right (seems like it's commcarehq-noreply@example.com)? 

In SAAS-10710 we are hoping that **every email support will interact with** in HQ is just support@. Is that possible?

**Comment by kishansampat** [comment]
@orangejenny looked at the changes and they look good to me. I had the same question as Kai as well

**Comment by orangejenny** [comment]
@kcowger @kishansampat 

> Just to be clear, when you say you switched CCHQ_BUG_REPORT_EMAIL to the normal noreply email, that's not support@, right (seems like it's commcarehq-noreply@example.com)?

Yes, this is correct. Not sure why I set it to noreply, maybe was confused because it was a from email not a to. I'll update it to use support@ instead.

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
@orangejenny is there a related commcare-cloud PR?

**Comment by orangejenny** [comment]
@biyeun yes: https://github.com/dimagi/commcare-cloud/pull/3726

**Comment by kcowger** [comment]
@orangejenny double checking -- for icds all emails should go to icds-support@dimagi.com, for prod all emails should go to support@. Is that in line with what you put together?

**Comment by orangejenny** [comment]
@kcowger Yep, that's it. Once this PR and then https://github.com/dimagi/commcare-cloud/pull/3726 are merged, that will be the setup.

**Review by dannyroberts — APPROVED** [review]
This is great, thanks @orangejenny!

**Pull request merged**
