### PR TITLE
Hide help bubble on enterprise

### PR DESCRIPTION
**Pull request by proteusvacuum**
https://manage.dimagi.com/default.asp?273872#1480641

This might be too heavy handed? Not sure if this is relevant for all enterprise clients.
Best with https://github.com/dimagi/commcare-hq/pull/20127/files?w=1
@dimagi/product

### CODE REVIEW

**Comment by orangejenny** [comment]
A while ago we made the ability to report an issue its own permission specifically for ICDS (see conversation on https://github.com/dimagi/commcare-hq/pull/16078), which makes me think there are at least *some* ICDS users who should be able to see this menu...but maybe that's changed?

@snopoke is probably the best person to answer whether this should be `ENTERPRISE_MODE` or something more specific.

**Comment by emord** [comment]
enterprise mode is for icds, enikshay(RIP) and PNA. I dont' think any of these need the help bubble/link to forums since they're all heavily controlled by dimagi

**Comment by proteusvacuum** [comment]
@orangejenny I'm curious how that was working? The `allow_report_an_issue` if statement was nested after a `not enterprise_mode`, so I thought that was only relevant for non-ICDS users?

**Comment by proteusvacuum** [comment]
Thanks @orangejenny I didn't see the part about reporting an issue. I've fixed it so the bubble shows if that option is available. The fact that templates don't allow you to add parenthesis in boolean logic is very confusing.

**Comment by orangejenny** [comment]
> The fact that templates don't allow you to add parenthesis in boolean logic is very confusing.

Agreed, thanks for commenting in the template, it helps.

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
