### PR TITLE
remove unused reminders views

### PR DESCRIPTION
**Pull request by dannyroberts**
- sample_to_survey
- sample_by_domain

Don't merge!

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
:+1: whenever you and @gcapalbo are good

**Comment by gcapalbo** [comment]
Good to merge from my side, but am holding off on merging so that we can release when it's good to do so

**Comment by dannyroberts** [comment]
Net change: -2 views
Indexing load: 6 views in `_design/reminders`

**Comment by dannyroberts** [comment]
@calellowitz let's reindex this one over the weekend (ping'd you on web-team slack chat)

**Pull request merged**
