### PR TITLE
Trigger second soh on monday not wednesday

### PR DESCRIPTION
**Pull request by kkrampa**
@czue @snopoke Could you merge and deploy this tomorrow morning? (could be today but I doubt that someone is online)

### CODE REVIEW

**Comment by czue** [comment]
I can deploy this today.

**Comment by kkrampa** [comment]
@czue Thanks!

**Comment by czue** [comment]
(will merge and deploy once tests pass)

**Comment by kkrampa** [comment]
@czue :white_check_mark:

**Comment by czue** [comment]
deploy is done. not sure if the second one made it in (i merged part way through deploy)

**Pull request merged**
