### PR TITLE
Auto Case Close UAT

### PR DESCRIPTION
**Pull request by gcapalbo**
http://manage.dimagi.com/default.asp?187884

@calellowitz probably easiest to review commit by commit, the commits and the bullet points in the ticket line up almost 1:1

### CODE REVIEW

**Comment by calellowitz** [comment]
besides the one comment, this looks good to me. Someone else, should probably take a look too, if anyone has more context

**Comment by czue** [comment]
@gcapalbo any idea who else is best positioned to review this? feel free to just ping/assign someone directly

**Comment by gcapalbo** [comment]
@calellowitz @czue updated - I don't think anyone else really has any more context, most of this stuff is just cosmetic / ui updates anyway so I think we should be good to go

**Comment by czue** [comment]
sort of think we should change the kwargs thing if you agree, but other than that no blockers. i'm dropping offline but feel free to merge after that's done (or push back if you disagree)

**Comment by calellowitz** [comment]
thanks for fixing the csrf thing. all good to merge from my perspective pending action on cory's comments

**Comment by gcapalbo** [comment]
@czue @calellowitz updated

**Comment by gcapalbo** [comment]
@czue updated

**Comment by czue** [comment]
looks good - will wait for the build

**Comment by czue** [comment]
:boom:

**Pull request merged**
