### PR TITLE
migrate cvsu reports to b3

### PR DESCRIPTION
**Pull request by biyeun**
@snopoke it would be great to have a sanity check on this as not sure what the full setup entails

cc @emord

### CODE REVIEW

**Comment by snopoke** [comment]
:+1:

**Comment by biyeun** [comment]
Hmm, location reports are generating, but button sticks on Generating Report (changes to apply when filters are updated).

will look into this one. I don't think this should require a revert at this time as the report itself appears to be functional.
screen shot 2016-03-28 at 5 29 32 pm

**Comment by snopoke** [comment]
The graphs aren't showing

**Comment by biyeun** [comment]
@snopoke fix: https://github.com/dimagi/commcare-hq/pull/10966

**Pull request merged**
