### PR TITLE
Fixes issue with static widths on select2s in case management + live preview

### PR DESCRIPTION
**Pull request by biyeun**
response to this ticket
http://manage.dimagi.com/default.asp?245920

codebuddy @calellowitz 
cc @orangejenny

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Review by orangejenny — CHANGES_REQUESTED** [review]
Doesn't seem to fix issue (will attach screenshot)

**Comment by orangejenny** [comment]
screen shot 2017-02-07 at 4 09 39 pm

**Comment by biyeun** [comment]
huh that's odd.

**Comment by biyeun** [comment]
@orangejenny fixed. Finally had some time to sit with this. slightly non-trivial trying to figure out the core issue....

**Comment by orangejenny** [comment]
Hey, the `100%` width breaks the `text-overflow: ellipsis` on the case property name select, causing overlap pretty similar to the original issue:
screen shot 2017-03-07 at 11 02 16 am

The styling in this area is a pain :-/  Wonder if there's a different approach we could take, maybe wrapping the question select2 under the case property select2? Or possibly punting on this altogether since @millerdev is pretty close to getting user properties in the form builder released, which will get rid of the loading area altogether?

**Comment by biyeun** [comment]
@orangejenny IMO this is still better and more manageable than having it go completely off the table cell and distort the layout. At least now it's contained. Believe me I wrestled with this thing.

**Comment by orangejenny** [comment]
Ha, I believe you, I've had fun times working with this code, too.

Given that I think user properties in form builder will make this a non-issue soon, doesn't seem worth spending more of your time on it.

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
