### PR TITLE
add migrations for function rename

### PR DESCRIPTION
**Pull request by czue**
needed this to get the function added to my local. https://github.com/dimagi/commcare-hq/commit/816ad74afa93c10e902a270dd63b56aceed602b4#commitcomment-17663116

@snopoke feel free to either merge if this makes sense or close if there's a reason it doesn't

### CODE REVIEW

**Comment by snopoke** [comment]
Yikes. Sorry about that. Surprised the tests didn't catch it.

**Comment by snopoke** [comment]
Oh I see why the tests wouldn't catch this.

**Comment by czue** [comment]
yeah - i wonder if we should somewhat treat migration functions as immutable for reasons like this

**Comment by snopoke** [comment]
yea, good idea

**Pull request merged**
