### PR TITLE
shift submissions into the user's timezone in submit history

### PR DESCRIPTION
**Pull request by dannyroberts**
screen shot 2015-05-25 at 4 50 25 pm

Before it would have said "2015-05-25 20:34:24" (Note the time doesn't account for US/Eastern timezone).

### CODE REVIEW

**Comment by dannyroberts** [comment]
@amsagoff assuming the formatting change is OK. (If it's not, we use that date format in a bunch of places and we should pick one you like more.) The functional change (taking timezone into account and making that show up explicitly) can only be a good thing I think.

**Comment by czue** [comment]
looks good to merge once @amsagoff is signed off

**Comment by snopoke** [comment]
@amsagoff ping

**Comment by amsagoff** [comment]
Looks good to me as long as it doesn't mess with anyone's exports?

**Comment by dannyroberts** [comment]
Yup shouldn't change exports at all.

**Comment by amsagoff** [comment]
great!

**Pull request merged**
