### PR TITLE
Added url decoding of case claim params

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
HQ changes for https://github.com/dimagi/formplayer/pull/884

This can be merged with or before the formplayer PR, but case claim will break if this is deployed after the formplayer PR.

## Feature Flag
Case claim

## Product Description
Fixes error where mobile workers with special characters in their usernames are unable to claim cases.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

None known.

### QA Plan

QA team will verify.

### Rollback instructions

If this is rolled back, the associated formplayer PR also need to be rolled back.

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
Is it common for POST params to be quoted? Aren't they normally encoded as utf8?

**Review by snopoke — APPROVED** [review]

**Comment by orangejenny** [comment]
I don't know what's most common - I'm open to changing this code if there's a reason to.

**Comment by snopoke** [comment]
> I don't know what's most common - I'm open to changing this code if there's a reason to.

no need to change.

**Comment by orangejenny** [comment]
Now I see Shuham pointed out that this was already being UTF-8 encoded, so apparently it does need the URL encoding as well: https://github.com/dimagi/formplayer/pull/884#issuecomment-783882940

**Pull request merged**
