### PR TITLE
make sure that domains created from the Exchange have community subscriptions

### PR DESCRIPTION
**Pull request by nickpell**
🐡

### CODE REVIEW

**Comment by nickpell** [comment]
@benrudolph @dannyroberts

**Comment by nickpell** [comment]
@calellowitz

**Comment by calellowitz** [comment]
👍 on ✅ 
bubbles war on unused imports continues

**Comment by nickpell** [comment]
haha actually no unused imports here.  the new war is on disorganized imports

**Comment by nickpell** [comment]
✅

**Pull request merged**
