### PR TITLE
remove TDH custom reports and all related code

### PR DESCRIPTION
**Pull request by czue**
got the confirmation from @rowenaluk that we can delete these. here's hoping this reclaims a bunch of memory and performance!

@dannyroberts :rage1: :rage1: :rage1: 

(wait for tests)

### CODE REVIEW

**Comment by dannyroberts** [comment]
yaaaas, +1 −4,748. I didn't even know this was on the table—the chopping block if you will. Such a lovely surprise!

**Comment by rowenaluk** [comment]
woot!

**Comment by czue** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
pretty sweet!

**Comment by dannyroberts** [comment]
:goberserk:

**Comment by benrudolph** [comment]
woah nice! :fire: :fire:

**Pull request merged**
