### PR TITLE
Add _indexed_on to case search index

### PR DESCRIPTION
**Pull request by proteusvacuum**
This will require a reindex, and will only provide meaningful data after that point, but this is to allow us to see the approximate time that cases are added or updated in the ES index. This should start helping us debug issues with cases not showing up in search results immediately. 

Not totally sure how long the reindex will take, but here are some stats

- eNikshay - 18,074,342 docs
- Prod - 427,027 docs
- India - 24,047,827 docs (I'm pretty sure we can delete most of these, since eNikshay doesn't use this server any more and most of them are on the eNikshay domain)

This is the start of:
https://trello.com/c/742yrIUs/234-case-claim-issues

@gcapalbo

### CODE REVIEW

**Review by gcapalbo — APPROVED** [review]
looks like this reindex is probably going to need to be run separate from deploy in all environments

**Comment by emord** [comment]
I think that you don't need to change the index name here. 

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-put-mapping.html#updating-field-mappings isn't for our version, but I think the same applies to 1.7.

 It should be possible to PUT the mapping with the new property to index. Then new documents will have that property indexed and you can run a reindex in the background.

Also is case search only applicable to SQL domains? If so then you would only need to reindex sql cases and not couch cases which reduces a lot of  time to index

**Comment by proteusvacuum** [comment]
@emord thanks, I didn't know about that. Makes a lot of sense. I don't think we even need to do the reindex in the background for now (since we know when this property was added, doing the reindex would just be extra work). Case search is allowed for both sql and couch, but I think only sql domains use it for now. 

I added the PUT operation as a migration: https://github.com/dimagi/commcare-hq/pull/19145/commits/395045a9ea9cd0a0b6b0ef392d623c308d881ad4. Not sure if you think this is a good idea, or if I should just run that management command on all environments after deploy? This seemed safer.

**Comment by emord** [comment]
@proteusvacuum I'd probably default to just running the management command manually instead of making a migration, but I don't have any strong feelings on that since it'll get run on every test in the future and I usually think of migrations as purely migrating SQL. What you have looks fine to me though

**Pull request merged**
