### PR TITLE
Update docker README.md

### PR DESCRIPTION
**Pull request by esoergel**
@snopoke This worked really well, thanks for setting it up!

### CODE REVIEW

**Comment by esoergel** [comment]
I was setting this up to use docker for services and everything else locally, @snopoke would you advise against that in general?  Do you run management commands from within the container?

I had some difficulty installing requirements, in particular, the python library psycopg2 requires access to `pg_config`.  If postgres is ONLY installed through docker, it's not available.  I worked around this by installing it globally with `$ sudo apt-get install libpq-dev python-dev`, but then it's still not the correct `pg_config`.  I'm not sure whether that actually matters much, as it seemed to work.

**Comment by czue** [comment]
:books:

**Comment by snopoke** [comment]
Thanks @esoergel. I think for dev environments it makes more sense to run HQ on your local machine and use docker for the services (which is what I'm also doing) since as you discovered it can be a bit of a pain running it all inside a container.

I hadn't come across the pg_config issue but probably because I previously had postgresql installed on my machine. The psycopg2 docs have this to say about it under the section on requirements to install from source:
```
The pg_config program: it is usually installed by the libpq-dev package but sometimes it is not in a PATH directory. Having it in the PATH greatly streamlines the installation, so try running pg_config --version: if it returns an error or an unexpected version number then locate the directory containing the pg_config shipped with the right libpq version (usually /usr/lib/postgresql/X.Y/bin/) and add it to the PATH:

$ export PATH=/usr/lib/postgresql/X.Y/bin/:$PATH
You only need it to compile and install psycopg2, not for its regular usage.
```

**Comment by esoergel** [comment]
I ran into a couple other weird issues doing a clean set-up with docker (`djcelery`/`djkombu` migrations, in parrticular), but did eventually get it all working.

**Pull request merged**
