### PR TITLE
Enable showing errors in case summary

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?155092

### CODE REVIEW

**Comment by snopoke** [comment]
@sravfeyn

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Pull request merged**
