### PR TITLE
Data Dictionary View Mode

### PR DESCRIPTION
**Pull request by Jtang-1**
## Product Description
This creates a view-mode for the data dictionary tab and restricts views that require edit permission by responding with a 403 status code.

Data Dictionary tab with edit permission:
Data Dict Edit Mode USH-73

Data Dictionary tab with view permission:
Data Dict View Mode USH-73

## Technical Summary
Review commit by commit
https://dimagi-dev.atlassian.net/browse/USH-73

## Feature Flag
https://www.commcarehq.org/hq/flags/edit/data_dictionary/

### Safety story
Manual testing on local env. No changes in functionalities, only hiding certain elements/views. Change will only restrict access more since data dictionary edit mode is already accessible by all users with the feature flag on.

### Automated test coverage

No tests

### QA Plan

No QA

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by stephherbers** [comment]
The view mode looks great and thank you for adding tests for the query. To confirm, you plan on running the migration management command on prod prior to the deploy after merge? (also curious if you run the query to see how many it would change?)

**Comment by Jtang-1** [comment]
>

**Comment by Jtang-1** [comment]
@stephherbers , yes I plan to merge, then run management command before deploy. Also, good call  - the query returns 4128 affected roles on production.

**Review by snopoke — APPROVED** [review]
I haven't reviewed closely but one concern I have is the dependency between merging this and running the migration manually prior to deploy. In an ideal world we should be able to merge and deploy code that allows us to do the migration separately from the code that needs the migrated data and the forced migration (as described here: https://commcare-hq.readthedocs.io/migrations_in_practice.html#id2)

In this specific instance I'm not going to block the merge because I don't think the migration will take very long to run and therefore shouldn't block the deploy if it isn't run manually beforehand.

**Pull request merged**
