### PR TITLE
[SSO] Implement additional security on Enterprise Admin Edit IdP form

### PR DESCRIPTION
**Pull request by biyeun**
## Product Description
This makes the following changes to the Edit Identity Provider form for enterprise admins:
- the client secret is obfuscated by default in the UI if there is a value present
- sanity checks are made on the Issuer ID to ensure that a valid One Login URL is entered

Screen Shot 2022-05-17 at 8 10 27 PM
Screen Shot 2022-05-17 at 8 10 40 PM
Screen Shot 2022-05-17 at 9 56 48 PM

### Safety story
Very safe and well-tested changes to a workflow that is currently unused in production

### Automated test coverage
Yes

### QA Plan
QA will happen at a later stage for the entire SSO feature, but not needed to merge this PR

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
The code here looks fine, but I'm curious about

> the client secret is obfuscated by default in the UI if there is a value present

The way it appears in the screenshot makes it look like we have rolled our own Client ID obfuscation widget. Is that the case? Was it done specially for this SSO feature, or is that something we've used previously in other places? I'm particularly interested in the code that detects if a new Client ID and/or secret value has been submitted. Where is that implemented?

**Comment by biyeun** [comment]
@millerdev I just use knockout to simply hide/show the text input. 

This will disable the knockout code if there is no client secret present:
https://github.com/dimagi/commcare-hq/pull/31633/files#diff-3a0e18ec3001b34cabd014702d1a3b2e835c4c1cf4062a356d33ba798f69d448R804-R823

**Comment by millerdev** [comment]
When the **Client ID** field contains a value like `228*****` (which I assume means all except the first 3 characters are masked) and the user changes some other value like **Issuer URL** and submits, will the **Client ID** be overwritten with the literal value `228*****` or will that field be skipped since it did not change?

**Comment by biyeun** [comment]
@millerdev I think there might be a misunderstanding? I masked the client ID and the issuer URL in the screenshot manually. Those don't need to be obfuscated in the UI. Only the Client Secret has the hide/show functionality in the UI, which shows up only if a value for client secret was present when loading the form.

**Comment by millerdev** [comment]
> I masked the client ID and the issuer URL in the screenshot manually.

I didn't realize this, and thought the code was doing things to apply that masking automatically. So I was confused when I didn't see any of that masking implementation anywhere.

**Pull request merged**
