### PR TITLE
Remove old url

### PR DESCRIPTION
**Pull request by gcapalbo**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by benrudolph** [comment]
Is this route still in use? If so it looks like it might redirect back to that URL: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/reminders/views.py#L271

**Comment by gcapalbo** [comment]
@benrudolph Yeah, delete_reminder is still used in one place, but it will never redirect back to list_reminders (line 271 doesn't get called anymore).  From now on it can only redirect to "one_time_reminders" here: https://github.com/dimagi/commcare-hq/blob/remove-url/corehq/apps/reminders/views.py#L273.  We're going to remove this view altogether once we update the Broadcast UI.

**Comment by benrudolph** [comment]
Ok sounds good then.

**Pull request merged**
