### PR TITLE
Create DATA_FORWARDING privilege

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAASP-10175

##### SUMMARY
This creates a new `DATA_FORWARDING` privilege which is grandfathered into all existing plans on HQ. This should be deployed BEFORE the Community / Trial Revamp updates. This also implements the `DATA_FORWARDING` restrictions where repeaters are triggered, and limits access to any repeater related views.

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
All looks good to me.

**Comment by kaapstorm** [comment]
(Definitely outside the scope of this change. Just thought worth mentioning here.) Nick has been putting together a spec to bring together Repeaters, OpenMRS/Bahmmi and DHSI2 integration into a single place. Once the UI has been simplified, and is enabled with the DATA_FORWARDING privilege @dimagi/product may want to think about whether we still need the "DHIS2" and "OpenMRS" toggles.

**Comment by dannyroberts** [comment]
@kaapstorm I think as long as DHIS2 and OpenMRS integrations are owned by Solutions, they'll stay under a Solutions flag. They're both under "Solutions - Limited Use" flags, which matches with my impression that there's currently no plan for SaaS to adopt them.

So I think the main thing no note with respect to DHIS2 / OpenMRS is that going forward is that any plan that intends to use those should be on a plan that supports data forwarding. @biyeun correct me if I'm wrong, but I believe starting in mid Dec that will be Pro or above, and existing plans will be grandfathered in.

**Review by dannyroberts — APPROVED** [review]

**Comment by biyeun** [comment]
@dannyroberts yes existing plans will be grandfathered in. this change should support that

**Pull request merged**
