### PR TITLE
B3 template cleanups

### PR DESCRIPTION
**Pull request by biyeun**
Additional cleanup of bootstrap2/bootstrap3 template splits and unused templates

@orangejenny / @proteusvacuum cc @calellowitz

### CODE REVIEW

**Comment by orangejenny** [comment]
test failure looks real: `Warning: ReferenceError: Can't find variable: ko`

**Comment by biyeun** [comment]
@orangejenny yep, addressed it. waiting on ✅

**Comment by czue** [comment]
(another failure)
```
Running "mocha:export#ko" (mocha) task
Testing: http://172.17.0.12:8000/mocha/export/ko
Warning: Error: The module 'style/ko/components/inline_edit.js' has already been defined elsewhere.
    at hqDefine (http://172.17.0.12:8000/static/hqwebapp/js/hqModules.js:43)
    at undefined (http://172.17.0.12:8000/static/style/ko/components/inline_edit.js:170) Use --force to continue.
Aborted due to warnings.
```

**Comment by biyeun** [comment]
build on the struggle :bus:

**Comment by biyeun** [comment]
YAAAASSSSS @orangejenny  ✅

**Comment by biyeun** [comment]
@calellowitz bump

**Pull request merged**
