### PR TITLE
Fix naming in migration

### PR DESCRIPTION
**Pull request by Rohit25negi**
Fix naming convention of last migration file. This is just to maintain the name convention.
Changing this name will re-trigger this migration but it should pass because it is just a view update not an column change which could fail.

This is bit urgent and blocking my other Pr. Could anyone of you review this and also confirm this wont break anything as the migration with last name was already deployed.

@calellowitz  @snopoke  @czue

### CODE REVIEW

**Comment by snopoke** [comment]
why is it blocking? does it error if you try add another migration?
I think renaming it might cause more issues - did you test locally?

**Comment by snopoke** [comment]
Offlined: 

blocking in the sense that. I dont want to keep it like it and wanted to fix the naming. and my other PRs also have migrations and once they get merged. It will be near impossible to fix the naming. Therefore, I m not merging my other Prs.

Tested locally.

**Review by snopoke — CHANGES_REQUESTED** [review]
You should add the following to the migration which will prevent Django from running it again:

```
replaces = [('icds_reports', '0138_update_thr_view'), ]
```

**Comment by Rohit25negi** [comment]
> You should add the following to the migration which will prevent Django from running it again:
> 
> ```
> replaces = [('icds_reports', '0138_update_thr_view'), ]
> ```

Done. @snopoke

**Review by snopoke — APPROVED** [review]

**Pull request merged**
