### PR TITLE
Remove unnecessary js and move to bower

### PR DESCRIPTION
**Pull request by dannyroberts**
I got this by running this command https://gist.github.com/dannyroberts/272a6456e426033221ee to identify unreferenced js files, and then I investigated each one separately/carefully.

Everything that was moved to bower I checked that the files bower files match the deleted files verbatim, except syntaxhighlighter, which had minor differences that didn't seem to matter, and which I manually tested.

Mutually dependent with https://github.com/dimagi/commcarehq-prelogin/pull/60

### CODE REVIEW

**Comment by czue** [comment]
image
:heart_eyes:

**Comment by benrudolph** [comment]
nice! thanks for cleaning this up :shower:! the best +/- bower related PR: https://github.com/dimagi/commcare-hq/pull/8480

**Comment by dannyroberts** [comment]
OK, I just clicked around a bit on staging with console open, and didn't see any js errors. I'm ready to have this merged and here's my thinking:

- tested everything every submodule-to-bower change where the scripts didn't match verbatim (just one)
- the most likely human error would have been not to correctly rename an import which would result in an obvious js error when the import 404s
- also `./manage.py compress` runs fine locally

Make sure to also merge https://github.com/dimagi/commcarehq-prelogin/pull/60 when this gets merged. Also https://github.com/dimagi/commcare-hq/pull/10189 should have probably been in this PR anyways, so feel free to merge that too.

**Comment by benrudolph** [comment]
(can't merge)

**Pull request merged**
