### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by esoergel**
If there's a better way to get Django to stop complaining about app labels not being defined, I'm all ears.  This does get Django to calm down though.
@anyone

### CODE REVIEW

**Comment by czue** [comment]
poor https://github.com/anyone. must get a lot of spam emails.

**Comment by czue** [comment]
I think the build fail is real

**Comment by emord** [comment]
@esoergel it might be (http://stackoverflow.com/questions/29635765/django-1-9-deprecation-warnings-app-label): 

> Or when you're using a model before its application is loaded

But that may require painstakingly messing with ordering in `INSTALLED_APPS`

**Comment by esoergel** [comment]
:white_check_mark:

**Pull request merged**
