### PR TITLE
related case lookup fixups

### PR DESCRIPTION
**Pull request by snopoke**
## Technical Summary
* Support legacy param name in `registry_case` view

## Feature Flag
data registry

### Safety story
Small changes covered by tests that only impacts the data registry feature flag

### Automated test coverage
Updated

### QA Plan
None

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Code looks fine, but why do we need to support the legacy name? I thought there weren't any prod apps using this workflow yet.

**Comment by snopoke** [comment]
> Code looks fine, but why do we need to support the legacy name? I thought there weren't any prod apps using this workflow yet.

I'm not sure but there are definitely staging apps.

**Comment by millerdev** [comment]
Seems like long term maintenance of this feature would be easier if we did not start out with legacy design elements. What do you think of reverting this and creating a management command that can be used to fix up (migrate) staging domains?

The management command could be run on any staging domain that uses the legacy name and wants to remain functional after this is reverted.

**Comment by snopoke** [comment]
@millerdev I don't not expect this to stay around for long. Within a month or so I plan to remove the legacy names. It was just a temporary measure to avoid breaking apps in QA.

**Comment by millerdev** [comment]
Sounds good if removal is planned. Would have been nice to have a comment in the code explaining that.

**Pull request merged**
