### PR TITLE
create indexes on the correct table

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Comment by snopoke** [comment]
This will need some cleanup of indexes on the live DB

**Review by Rohit25negi — APPROVED** [review]
Thanks.

**Comment by snopoke** [comment]
@Rohit25negi @calellowitz please add a ticket to track the cleanup of duplicate indexes and addition of missing indexes

**Comment by Rohit25negi** [comment]
@snopoke  sure.

**Pull request merged**
