### PR TITLE
fix function

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by czue** [comment]
@NoahCarnahan

**Comment by czue** [comment]
might be worth waiting for build, though guessing nothing tests this given that it was broken

**Comment by NoahCarnahan** [comment]
Thanks, I'll wait just in case.

**Comment by esoergel** [comment]
Since boolean parameters are vague ("does `False` mean open or closed, or something else entirely?"), I like to always specify them as a keyword argument, as this is super obvious:
```python
return _get_case_ids(owner_id, is_closed=True)
```
although the whole point of this function is to include that information in the function name, which will be even clearer when this call is used elsewhere.

**Comment by czue** [comment]
nice, that's a good trick either way

**Pull request merged**
