### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
code buddy @TylerSheffels

**Comment by TylerSheffels** [comment]
:skull:

**Comment by czue** [comment]
@TylerSheffels getting wild with emojis! :stuck_out_tongue_winking_eye:

**Comment by TylerSheffels** [comment]
Thats because I couldn't find the youtube link to the original mad max clip of the guy yelling "kill kill kill"

**Pull request merged**
