### PR TITLE
ICDS - added api key to the UI

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @emord @calellowitz ,

I added missing API key to the dashboard HTML. Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Review by emord — APPROVED** [review]
I think @calellowitz has a better understanding if this would work, but it looks good to me

**Comment by calellowitz** [comment]
Was this able to be tested at all? I am still not convinced the js will be loaded without going through requirejs. Additionally, this does not include any of the other data we typically include in the google template, all of which are in `analytics/google.html` or `analytics/all.html`, it is probably (and safer in case something else changes) to just include one of those, specially `all.html` which is what the rest of hq uses.

**Comment by lwyszomi** [comment]
@calellowitz @emord All required js will be included by this: https://github.com/dimagi/commcare-hq/pull/20697/files#diff-5f9c86b58cde7d65542f84421ac2a45eR25, This includes all analytics js, but only GA will be working, because we don't include other credentials. Also, I removed API key and now I added ```all.html```. 

I tested this locally and all works great (sorry that on the screenshot we have all in Polish 😄but on the map, you can notice that my activity was from Gdańsk).
ga

**Comment by lwyszomi** [comment]
@emord @calellowitz but I think I found the problem with track clicks and events. This not work. Only page load works fine. I think I must use this https://github.com/revolunet/angular-google-analytics to track all data from ICDS Dashboard. I will check this tomorrow.

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
