### PR TITLE
Bulk export helptext showing html

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?165958#924777

### CODE REVIEW

**Comment by czue** [comment]
:+1: from me

**Comment by proteusvacuum** [comment]
Does a :+1: mean I should merge this myself? Just curious about process.

**Comment by czue** [comment]
typically i use it to indicate "looks good but not sure I have enough context / put enough thought in to merge" (so no)

**Comment by czue** [comment]
we typically are pretty explicit when good to self merge

**Pull request merged**
