### PR TITLE
Down with Case Activity, long live Worker Activity

### PR DESCRIPTION
**Pull request by esoergel**
http://manage.dimagi.com/default.asp?216551
@gcapalbo

### CODE REVIEW

**Comment by benrudolph** [comment]
:fire: :japanese_ogre: :fire:

**Comment by czue** [comment]
whee! :skull: 

Is the plan to fully retire this report? Do we have any plan for how we'll deal with people who have emails setup? cc @dimagi/product

**Comment by esoergel** [comment]
@dimagi/product ran some numbers on the report, and it looks like it does see some use.  It's noticeably less used than the WAR though, and the two are viewed to somewhat serve the same purpose, so this switch was made I think as a baby step in the direction of removing.  Not sure what the long-term strategy is though.

**Comment by amsagoff** [comment]
Long-term I want to fully retire the report, but that's not something I
plan on tackling soon. Let me know if there's significant load/tech debt
from this report, though.

It's are complicated because while the WAR is more widely used/definitely a
more functional report, I get a decent amount of qualitative feedback that
the WAR is confusing to learn and case activity is easier to teach
low-capacity users.

**Pull request merged**
