### PR TITLE
Remove two old cleanup files

### PR DESCRIPTION
**Pull request by esoergel**
https://github.com/dimagi/commcare-hq/commit/8cc08c6d567b88cae79db329b54c7916d91d0c39#commitcomment-14004618
@benrudolph

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
:+1: thanks

**Comment by snopoke** [comment]
@esoergel on the rampage

On 27 October 2015 at 21:00, Cory Zue <notifications@github.com> wrote:

> Merged #8819 <https://github.com/dimagi/commcare-hq/pull/8819>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/8819#event-447181394>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by czue** [comment]
:ram: :page_facing_up:

**Comment by benrudolph** [comment]
lol nice emoticon writing

**Comment by esoergel** [comment]
:large_blue_circle: :mag:

**Pull request merged**
