### PR TITLE
use integer instead of string

### PR DESCRIPTION
**Pull request by emord**
https://sentry.io/dimagi/commcarehq/issues/287633022/

I manually fixed the supervisor config to get around this

@snopoke @benrudolph @orangejenny

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]
ah annoying

**Comment by snopoke** [comment]
Updated this to make all values string (the JS doesn't handle 0 well). Also added a 'null' default.

**Comment by emord** [comment]
@snopoke was it some false-y check that was failing in JS? I didn't notice anything, but I only really checked that it would update properly

**Comment by snopoke** [comment]
yea, it also only failed after I added a new default option.

Simon Kelly
Director of Server Engineer | Dimagi

**Pull request merged**
