### PR TITLE
add different icons for advanced and report modules

### PR DESCRIPTION
**Pull request by czue**
this just adds different icons for advanced and report modules so you can tell what type of module something is in the navigation tree. http://manage.dimagi.com/default.asp?223736
image

I didn't think too hard about the icons, so if @orangejenny @biyeun or @dimagi/product want to propose something else feel free. I figured it wasn't super important since these are only R&D / mostly internal features.

### CODE REVIEW

**Comment by snopoke** [comment]
1000 :+1:

**Comment by orangejenny** [comment]
I like it. Amused that the icon for advanced modules is a warning symbol. Other possibilities might be fa-gears / fa-rocket / fa-bomb / fa-magic (from http://fontawesome.io/cheatsheet/). But I'm not opposed to the warning symbol, just waiting on tests.

**Comment by amsagoff** [comment]
Nice! Slightly concerned the warning symbol will alarm, but we always
change to rocket if it becomes a problem.

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
