### PR TITLE
New uploader toggle sarah

### PR DESCRIPTION
**Pull request by knittingarch**
This commit creates the toggle infrastructure for the new media uploader code.

### CODE REVIEW

**Comment by biyeun** [comment]
@knittingarch there are some submodule references committed to this that shouldn't be. can you remove those please?

**Review by biyeun — CHANGES_REQUESTED** [review]
remove unrelated submodule refs

**Comment by knittingarch** [comment]
@biyeun Removed!

**Review by orangejenny — APPROVED** [review]
Looks fine now. Do you have an idea where `new_multimedia_uploader.html` would be rendered or included?

**Comment by sheelio** [comment]
Is this a feature flag, or a feature preview?

**Comment by orangejenny** [comment]
@sheelio Flag - it's for allowing Sarah to toggle new multimedia widget code while it's in development...which really means it's an internal engineering flag, come to think of it. @knittingarch can you change this to use `TAG_INTERNAL`?

**Review by orangejenny — CHANGES_REQUESTED** [review]
change flag type (see comment thread on overall PR)

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
@orangejenny looks good to me

**Pull request merged**
