### PR TITLE
Update bulk ui translations test data

### PR DESCRIPTION
**Pull request by dannyroberts**
Should fix build; depends on https://github.com/dimagi/commcare-hq/pull/8640

see commit message on https://github.com/dimagi/commcare-hq/commit/533279409d1e9ccba5673cc43b6e8ee3b12c071b

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue

**Comment by czue** [comment]
gracias. g2g when tests pass

**Comment by dannyroberts** [comment]
Oops just saw my link in the description was wrong (points to this PR); I mean to link to https://github.com/dimagi/commcare-translations/pull/23, which is now merged. @benrudolph I think this might have been what had been not working for you

**Comment by dannyroberts** [comment]
(This PR linked to the right submodule commit, but since it wasn't on master yet, updating the submodule ref to master reset it to the "wrong" one. Anyway, all fixed now

**Comment by benrudolph** [comment]
aha makes more sense. thanks @dannyroberts

**Pull request merged**
