### PR TITLE
Added Nirmal district to Telangana

### PR DESCRIPTION
**Pull request by Rohit25negi**
This updates the district topojson to add a missing district in Telangana:
ticket: https://dimagi-dev.atlassian.net/browse/ICDS-1667

How I fixed it:
1. Noted that block-level topojson of Telangana has that district in it.
2. I uploaded the Telangana block topojson to https://mapshaper.org/
3. dissolved the block level boundaries to left with only district-level boundaries. Exported it back(exported_telangana.json).
4. Uploaded the district topojson.
5. downloaded it as Geojson Zip. (contains Separate JSON file for a separate state, telangana.json)
6. replaced the `telangana.json` with `exported_telangana.json`
7. uploaded the Geojson.zip back again and exported it as topojson and replace it in the codebase

Took Cory through the above steps, looked fine to him.

Open consequence: state level maps became a bit smaller. Not able to figure out how to bring it back to the normal size.

Since its a P1: it may be fine to go with it and figure out the sizing issue later, Waiting for Priyanka to judge.

### CODE REVIEW

**Comment by Rohit25negi** [comment]
Priyanka agreed to go ahead with it for now, we can figure out increasing its size later

**Comment by Rohit25negi** [comment]
Here are the size difference for others' reference


Original:
Screenshot 2020-07-16 at 9 05 51 PM


After Change:

Screenshot 2020-07-16 at 9 15 58 PM

**Review by ShubhamBansal1997 — APPROVED** [review]

**Comment by ShubhamBansal1997** [comment]
Looks good, good to test on staging and attach the images for reference.

**Comment by czue** [comment]
I'm not sure whether or not this matters, but FYI, the absolute positioning of the file looks even more messed up / weirder than it was before.

https://github.com/dimagi/commcare-hq/blob/7b6d83bd65a4cc2be1287543d9390ed3359811a7/custom/icds_reports/static/js/topojsons/districts_v4.topojson

image

Do you have a sense what's going on there and whether that is expected?

**Comment by czue** [comment]
actually I think what happened is that the state is now correctly positioned, but everything else is still off, similar to J&K and Ladakh. Maybe we can fix it one state at a time? :man_shrugging:

**Comment by Rohit25negi** [comment]
> Do you have a sense what's going on there and whether that is expected?

yeah, Its because, I took the Telangana from the block level which looks like its positioned on the map itself rather than shifted to left like the district map. Basically Telangana has become like j&k

**Pull request merged**
