### PR TITLE
Icds migration

### PR DESCRIPTION
**Pull request by emord**
Added migration for @sheelio 

http://manage.dimagi.com/default.asp?243659#1258866

@benrudolph

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]

**Comment by czue** [comment]
:athletic_shoe: :hammer_and_wrench:

**Comment by snopoke** [comment]
We should test these of softlayer first, also I think @sravfeyn had some other similar changes that could be bundled in to the same patch.

**Comment by sravfeyn** [comment]
_This_ was the migration I was looking for. I think Sheel might have already tested these out on softlayer @sheelio ?

**Comment by sheelio** [comment]
I've tested it locally against a copy of the DB on softlayer.

**Comment by sravfeyn** [comment]
(Patched and Migrated)

**Pull request merged**
