### PR TITLE
Properly sync cousins

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?189528#1062387
Opening for tests. Last commit is the relevant one. 
@czue @dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
this looks great. any reason not to merge? wasn't sure about the "opening for tests" comment

**Comment by czue** [comment]
(and thanks for digging into this!)

**Comment by proteusvacuum** [comment]
I think it's G2G. Didn't run the full phone / case tests locally, hence the comment.

**Comment by dannyroberts** [comment]
Yeah great digging. I forgot the answer but I think I've asked; what's the process for @ctsims / mobile team getting new test files that you add? In this particular case, was it only an HQ issue, or was there a corresponding mobile one?

**Comment by ctsims** [comment]
@dannyroberts Hm, not sure if I heard about this specifically. Our test corpus is here: https://github.com/dimagi/commcare/blob/master/tests/resources/case_relationship_tests.json and we can directly PR to it. @proteusvacuum It looks like you actually reverted adding this test there, was there a specific reason?

**Comment by proteusvacuum** [comment]
@ctsims I accidentally pushed directly to master (sent you and @phillipm an email about it over the holidays). My PR for the change is here: https://github.com/dimagi/commcare/pull/229

**Comment by ctsims** [comment]
Got it. Merged!

**Pull request merged**
