### PR TITLE
reduce gunicorn worker count

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by benrudolph** [comment]
We may want to think about this a little more in the sense that it seems we should also take into account how much RAM is on the machine. This will reduce the threads in India where we don't get any out of memory errors

**Comment by benrudolph** [comment]
(just read your chat on HQ Devs, i agree and that it's probably best to stop the errors on prod, though we may want to be smarter about it in the future)

**Comment by snopoke** [comment]
I had to ssh in and adjust these by had because there wasn't enough memory to to a git fetch

**Comment by benrudolph** [comment]
Woah

**Comment by dannyroberts** [comment]
Yeah woah

**Pull request merged**
