### PR TITLE
Decorator cleanup

### PR DESCRIPTION
**Pull request by biyeun**
Cleanup decorator syntax so that you don't have to call them, they immediately wrap the view functions.
Also adds better doc strings

@NoahCarnahan @benrudolph

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
@biyeun updated with the changes discussed this afternoon. I haven't tested this branch without the other changes we were making though so we should do that before removing review tag.

**Comment by benrudolph** [comment]
lgtm, conflicts with master

**Comment by czue** [comment]
:+1: nice

**Comment by biyeun** [comment]
@benrudolph conflicts resolved, @NoahCarnahan thanks for pushing changes!

**Comment by biyeun** [comment]
ok to merge when peeps think it's g2g. merge with https://github.com/dimagi/commcarehq-prelogin/pull/40

**Pull request merged**
