### PR TITLE
update loadtestendpoints urls

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
@kaapstorm

**Comment by czue** [comment]
@dannyroberts do you remember the context for this app? I wonder if we can just delete it: https://github.com/dimagi/commcare-hq/pull/2853

**Comment by nickpell** [comment]
@emord

**Comment by dannyroberts** [comment]
Oh yeah, we this can definitely go: https://github.com/dimagi/commcare-hq/pull/13471

**Pull request merged**
