### PR TITLE
Conditional Alert Warning for Parent Case Recipient Type

### PR DESCRIPTION
**Pull request by AddisonDunn**
## Product Description

Problem: In situations where applications have Parent / Extension or Host / Extension relationships, it is not clear that the Parent Case recipient option for conditional alerts does not include these extending relationships (currently an error message is displayed when trying to alert parent/extension or host/extension cases). 

Implemented solution: when the "Case's Parent Case" option is selected from the list, a warning message is shown:

Screen Shot 2021-10-05 at 11 10 19 AM

## Technical Summary
In response to [USH-1153](https://dimagi-dev.atlassian.net/browse/USH-1153). 

The warning is only shown when the "Case's Parent Case" option is selected.

Note: solving this error completely and allowing Parent / Extension and Host / Extension relationship conditional alerts is a separate task ([USH-1155](https://dimagi-dev.atlassian.net/browse/USH-1155)).

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

No tests are needed.

### Safety story

Display only and does not affect any key operations. I tested to make sure a new conditional alert could still be created

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by orangejenny** [comment]
Code looks fine, but I'm surprised at the original request. Host & extension cases are semi-hidden features. It seems weird to show a warning that references a feature that many users won't have heard of, and that we don't have public-facing docs for. @esoergel What do you think? I'm surprised we're not just fixing the issue, as described in USH-1155.

> currently an error message is displayed when trying to alert parent/extension or host/extension cases

Does "currently" here mean prior to this PR? Where is this error message?

**Comment by AddisonDunn** [comment]
> Does "currently" here mean prior to this PR? Where is this error message?

While investigating Kim received the “Error - No recipient” in the Messaging History for parent/extension and host/extension cases.

**Comment by orangejenny** [comment]
@AddisonDunn Aha, got it. I had been wondering if there was something similar to what you're adding - something on an HQ config page that references host/extension cases.

A more practical suggestion came to mind: if this warning were limited to domains with the feature flag EXTENSION_CASES_SYNC_ENABLED on, that would limit it to people who are using extension/host cases.

**Comment by AddisonDunn** [comment]
> A more practical suggestion came to mind: if this warning were limited to domains with the feature flag EXTENSION_CASES_SYNC_ENABLED on, that would limit it to people who are using extension/host cases.

@orangejenny that makes a lot of sense, so that the error won't confuse anyone without those special relationships available. I can try adding that!

**Review by orangejenny — APPROVED** [review]
My instinct would be to not include the binding if the flag is off, and to reserve js for logic that's dynamic.

```
data_bind="visible: recipientTypeSelected('{parentCase}')".format(
                    parentCase=CaseScheduleInstanceMixin.RECIPIENT_TYPE_PARENT_CASE)
                    if EXTENSION_CASES_SYNC_ENABLED.enabled(self.domain) else ""
```

Although that will result in `data-bind=""` in the HTML for non-flagged domains, which is a little weird, so I might instead modify `get_recipients_layout_fields` to not include the div at all, something like this:
```
def get_recipients_layout_fields(self):
    fields = [...recipient_types...]
    if EXTENSION_CASES_SYNC_ENABLED.enabled(self.domain):
        fields.append(...new div with warning...)
    fields.extend(...remaining fields...)
    return fields
```

...But all of that is pretty picky/academic commentary. The code you have is fine.

**Pull request merged**
