### PR TITLE
Add mark and rewind to case claim

### PR DESCRIPTION
**Pull request by proteusvacuum**
HQ component of:  https://github.com/dimagi/commcare-core/pull/368
http://manage.dimagi.com/default.asp?234248
Hold off on merge until https://github.com/dimagi/commcare-core/pull/368 is merged
@phillipm @kaapstorm

### CODE REVIEW

**Comment by kaapstorm** [comment]
:+1: LGTM

**Comment by snopoke** [comment]
I think we'd have to hold off on merge until the mobile code is released - not just merged right?

**Comment by phillipm** [comment]
As far as I know, everyone currently using case claim can operate off the dev build of CommCare, so in that sense we can merge this once https://github.com/dimagi/commcare-core/pull/368 is merged. The related changes to the double management session stack setup will need to be versioned to only generate mark/rewind stacks on 2.30 and above.

**Comment by snopoke** [comment]
👍

**Comment by proteusvacuum** [comment]
https://github.com/dimagi/commcare-core/pull/368 has been merged, so this is g2g.

**Comment by phillipm** [comment]
woohoo, so concise! 🎂

**Pull request merged**
