### PR TITLE
explicitly declare sw path

### PR DESCRIPTION
**Pull request by esoergel**
http://manage.dimagi.com/default.asp?155236
@anyone @sreddy

### CODE REVIEW

**Comment by czue** [comment]
just pinging random people on PRs. classic :trollface:

**Comment by esoergel** [comment]
ah crap.  I always get confused because the code buddy email says `sreddy`.  Sorry @sravfeyn that one was for you.

**Comment by benrudolph** [comment]
it's actually incredible how many times you and @sravfeyn have been paired

**Comment by esoergel** [comment]
Yeah, I think more than half of my code buddies have been @sravfeyn .

**Comment by sravfeyn** [comment]
Haha, there's definitely some secret bias that Ben has mixtaped into his random generator.

**Pull request merged**
