### PR TITLE
Revert "Revert "XFormInstance attachments -> blobs""

### PR DESCRIPTION
**Pull request by millerdev**
Reverts dimagi/commcare-hq#12539

Hold off on merge until the weekend.

### CODE REVIEW

**Comment by czue** [comment]
@millerdev apologies I think I should know this already, but can you just quickly explain what the scope and current state of this change/migration is?

I know the high level change is moving `XFormInstance` attachments to the blobdb. Here are some more specific questions that I had:

- Has the migration already been run on prod or it will be run after merge?
- Does the migration delete the attachments from couch/cloudant?
- What is the current state of our riak backups? Are we relying primarily on node redundancy in the case of any issues?

Just wanted to make sure I understood what was going on here.

**Comment by millerdev** [comment]
> Has the migration already been run on prod or it will be run after merge?

After merge.

> Does the migration delete the attachments from couch/cloudant?

Yes. A backup copy is saved a file created during the migration.

> What is the current state of our riak backups? Are we relying primarily on node redundancy in the case of any issues?

I think we're currently relying on node redundancy. @calellowitz might have more information.

**Comment by calellowitz** [comment]
yeah, we exclusively rely on node redundancy for riakcs backups. there was a discussion of making riak append only, to avoid application errors leading to data loss, but as far as i know that has not been implemented.

**Comment by czue** [comment]
:+1: thanks for the responses.

> > Does the migration delete the attachments from couch/cloudant?

> Yes. A backup copy is saved a file created during the migration.

Where is this saved and how long is it kept around? Just wanted to be sure that we're not running the risk of filling up a file system somewhere.

**Comment by millerdev** [comment]
> Where is [the backup] saved and how long is it kept around?

I've been putting them in a directory at `/opt/data/migration-logs` on hqdb0. I tar and gzip them after the migration is complete to reduce size (by a lot). Currently on prod the application and multimedia logs are using about 36GB (after tar/gzip). I don't have a deletion date scheduled.

**Comment by czue** [comment]
ok I think something to be very aware of when you run this on prod. it wouldn't surprise me if we have more form attachments (including xml) than disk space on hqdb0

**Comment by millerdev** [comment]
Ready to merge!

The ES reindex was run last week on a private release (not deployed publicly) by @benrudolph. This morning he confirmed that the new indexes exist and have ~ the same number of docs as the old indexes.

**Comment by benrudolph** [comment]
yay! added label back on just so we can find this easily in case something goes wrong

**Comment by benrudolph** [comment]
🎆 🎆 🎆

**Comment by czue** [comment]
woop woop.

**Pull request merged**
