### PR TITLE
Remove Survey Management code

### PR DESCRIPTION
**Pull request by gcapalbo**
This will let us remove the following couch views:

```
domain/counter
reminders/sample_by_domain
reminders/sample_to_survey
```

### CODE REVIEW

**Comment by gcapalbo** [comment]
Don't merge yet, checking to make sure I got it all

**Comment by gcapalbo** [comment]
@dannyroberts Ok this is good to go. I didn't remove any couch views in this PR to avoid a long reindexing operation but we can remove the following views now whenever we want:

    domain/counter
    reminders/sample_by_domain
    reminders/sample_to_survey

**Comment by czue** [comment]
image
:skull: :skull: :skull: :skull:

**Comment by dannyroberts** [comment]
@gcapalbo this is an amazing thing to wake up to

:goberserk:

**Comment by dannyroberts** [comment]
OK I've made PRs for these and put them into my one-a-weekend reindexing backlog

https://github.com/dimagi/commcare-hq/pull/8390 removes

```
domain/counter
```

https://github.com/dimagi/commcare-hq/pull/8547 removes

```
reminders/sample_by_domain
reminders/sample_to_survey
```

**Pull request merged**
