### PR TITLE
Remove Deprecated Properties from Case Export

### PR DESCRIPTION
**Pull request by zandre-eng**
## Technical Summary

Link to ticket can be found [here](https://dimagi-dev.atlassian.net/browse/SC-2538?atlOrigin=eyJpIjoiN2Q1Y2ZhNTFlOTE4NGM0OWE3YjBhZmFhNjc1NWIzYTciLCJwIjoiaiJ9).

When properties are marked as deprecated in the Data Dictionary, they will no longer load automatically when creating/editing a case export. Instead, there is now a filter available (similar to the deleted filter) to load these properties on demand.

deprecated_filter

If the user hasn't already loaded in deprecated properties, clicking on the deprecated filter will give the user a prompt, warning them that the properties will be loaded in and that it can take a while.

load_deprecated_prompt

Already saved exports will retain any checked properties that have been deprecated, and these will be loaded when editing an existing case export configuration. Only the unchecked deprecated properties will need to be loaded in on demand.

## Feature Flag

None.

### Safety story

- Did local testing.
- Expanded existing unit tests.

### Automated test coverage

Unit tests have been expanded to check for deprecated property.

### QA Plan

No QA plan.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by esoergel** [comment]
USH has been considering a similar task ([Jira ticket here](https://dimagi-dev.atlassian.net/browse/USH-72)).  In my ideal world, we'd switch this to use the data dictionary as the primary paradigm (probably behind a feature flag for a while).

The current case export system is not aware that the data dictionary exists, and it instead maintains its own "schema" model that is generated from applications on the domain.  As applications are modified, that schema is updated.  This is where the idea of "deleted properties" comes from.  It also has a handful of system properties pulled from a constants file.

The data dictionary is a separate, parallel system for much the same thing - it maintains a list of case properties, including system properties and those which are no longer relevant ("deprecated properties").  This also has mechanisms for staying up to date, but it's visible to the user and they can modify it.

Combining the two systems means we're saddled with the complexity of both, and we have to consider how they interact (what does it mean for something to be deprecated in the DD and deleted in case exports - do you need to enable both filters to see it?).

Further, I see that the impetus for this work was performance.  I'd guess that the primary driver of slowness here is updating the schema, not sending down a big list of properties, so I wouldn't expect filtering out deprecated properties to substantially improve speed.  Rather, does this really update the schema each time?  If so, why? Is it not being cached appropriately?  Or is it updating the schema frequently because the app sees frequent changes (we may not be able to do anything about that).

Switching entirely away from the saved export schema to the DD would eliminate the step of re-processing app builds, making this much faster to load.  It would also leave us with a simpler system (though maybe one that shares less code with form exports) and bring it more in-line with general goals of using the data dictionary more broadly.

Lastly, I recognize that what I'm proposing is a much more substantial reworking of this system - I wouldn't expect y'all to act on it in the course of PR review.  I feel obliged to float the idea, but I'll leave it to SolTech to ultimately decide upon.

**Comment by esoergel** [comment]
Also, clearly out of scope, but just as an FYI, USH is considering pulling in descriptions from the data dictionary to display in the config page.  I think we should also eventually pull in data dictionary labels as default display values for the export configs - similar to what's done with form exports:
image

**Comment by zandre-eng** [comment]
That sounds like a promising idea @esoergel. Especially given the fact that the function to rebuld/process the schema is run every time a case export is created and/or opened. This also applies to when the deleted and deprecated filters are turned on in the export configuration.

To my understanding, there is some form of "caching" that is happening, as the schema rebuild function tries to get an existing schema definition from the DB. Still, it seems to take this definition and update it by going through the application builds again.

A question I have however, is how would we ensure that the data dictionary is kept up-to-date with what is resembled in the application? I am unaware that this is done automatically, and so, to my understanding the user would need to manually keep the case types in the data dictionary updated with the properties that are present in the application. One could potentially extend the function that syncs/generates the data dictionary to also look through the applications and get the latest properties from there.

Another potential complication would be dealing with deleted properties. Currently, the data dictionary has no knowledge of deleted properties. The schema is updated by going through all the old application builds to retrieve any deleted properties. Would the idea of a deleted property be transferred over to being deprecated in the data dictionary? Again, this brings up the question on whether the user will have to manually then deprecate properties that they've deleted in the application. As mentioned previously, this could also perhaps be automated through the data dictionary generate function, by automatically deprecating properties that aren't found in the latest application builds.

I will be sure to reach out to Mary on this issue, who will be back online next week, as she will be the best person to indicate whether this is something that SolTech can take a look at :+1:

**Comment by esoergel** [comment]
> how would we ensure that the data dictionary is kept up-to-date with what is resembled in the application? 

This already happens to some extent, for example, this is called whenever a form's case management is modified:

https://github.com/dimagi/commcare-hq/blob/699c4155a07d959eef9aab2b4fc34c9bbe6105af/corehq/apps/app_manager/views/forms.py#L235-L235

The DD is used in a few other important places, like the case list explorer and the case management UI in app builder, so it's important that it be kept up-to-date.  SaaS is I believe working on making sure that's all very robust in preparation for GAing the DD.

> Would the idea of a deleted property be transferred over to being deprecated in the data dictionary?

That's what I was thinking.  I don't know of anything that does this automatically at the moment, though it's certainly doable, as you proposed.  Might be something SaaS would want to look at as part of their GA effort.  My main thought process though is that this aspect of data exports is the same thing we need to deal with in the DD and everything else that uses it, so it's a shame to maintain a separate set of tools just for exports.

And just a quick note on the practicality of this proposed change - data export configurations are saved in the DB, so I imagine this could be done in a way where it does not impact existing data exports (or their ability to be edited), only the default properties list for creating new exports.  That way backwards compatibility wouldn't be much of a blocker or disrupter.

**Comment by SmittieC** [comment]
>I will be sure to reach out to Mary on this issue, who will be back online next week, as she will be the best person to indicate whether this is something that SolTech can take a look at 

@zandre-eng did you reach out to Mary about this yet? I'd be curious as to what the outcome is/was.

**Comment by esoergel** [comment]
I also wrote down some thoughts on what that might look like - linking here for future reference: https://docs.google.com/document/d/1rpCFUXOAJAFBCmh8GMfivShOHfKjskdWPdE2ZPFkqP0/edit

And now I'm officially done derailing the progress of this PR, apologies for the misdirection, carry on!

**Review by Charl1996 — APPROVED** [review]
I'm happy with this. I reached out to Zandre and he mentioned that this has been tested on staging with an AE and the problem of loading time has been sufficiently solved with this work. 

Also, this sounds like a temporary implementation, since, from Ethan's comments, it sounds like there's plans to rewrite this to use the data dictionary.

**Pull request merged**
