### PR TITLE
Add get_location() method to CommCareUser

### PR DESCRIPTION
**Pull request by NoahCarnahan**
http://manage.dimagi.com/default.asp?239995

@proteusvacuum @esoergel

### CODE REVIEW

**Comment by proteusvacuum** [comment]
I *think* we should just be using `get_sql_location` for all your location needs right now.

**Comment by NoahCarnahan** [comment]
Ah didn't know that, thanks. This PR is to fix a usage here:
https://github.com/dimagi/commcare-hq/blob/aab7989081302e11e960c06ee418c9fe2458aa51/corehq/apps/locations/views.py#L139
@esoergel , should this usage be `user.get_sql_location()`?

Additionally, should `CommCareUser.location` be removed from that model, or renamed `_location`? or are there legitimate usages for it?

**Comment by esoergel** [comment]
The usage you linked could be either one, actually (it's just checking whether or not the user has an assigned location), so I'd be down for the fix to be switching that to SQL.

To the other question, couch locations are deprecated, so we shouldn't be introducing new usages of them, but it's legitimate for old usages to still exist, or for minor changes to use couch locations in order to interoperate with existing couch-location functionality.

**Comment by NoahCarnahan** [comment]
Good to know, thanks. Will update pr.

**Review by esoergel — APPROVED** [review]

**Pull request merged**
