### PR TITLE
Cache travis download dirs

### PR DESCRIPTION
**Pull request by benrudolph**
@czue should cache our downloads. i noticed travis is sometimes spending a long time doing the installs, hopefully this'll :horse_racing:  it up

### CODE REVIEW

**Comment by czue** [comment]
build still failing (looks like elastic not starting up)

**Comment by benrudolph** [comment]
thanks, this should hopefully do the trick. though travis is notoriously troublesome

**Comment by benrudolph** [comment]
just took at some of the timings. before:
screen shot 2015-12-16 at 2 28 44 pm
after:
screen shot 2015-12-16 at 2 29 33 pm

**Comment by benrudolph** [comment]
lol nevermind that includes all the tests

**Comment by benrudolph** [comment]
:white_check_mark:

**Pull request merged**
