### PR TITLE
all kwargs to update_subscription should default to None

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by benrudolph** [comment]
not sure i totally understand this change, aren't those params supposed to be booleans? was just looking at this: https://github.com/dimagi/commcare-hq/blob/update_subscription-kwargs/corehq/apps/accounting/models.py#L1013

**Comment by benrudolph** [comment]
👢 🚧

**Comment by nickpell** [comment]
good question - the properties are set here: https://github.com/dimagi/commcare-hq/blob/update_subscription-kwargs/corehq/apps/accounting/models.py#L1242

for the other properties, it follows the pattern that they should only be updated if specified as kwargs to ```update_subscription```.  With the three properties affected here, in the status quo they will be updated to their default values whenever no value for them is specified in the kwargs.  This change will prevent them from being accidentally set in the future.

Right now, we don't ever call ```update_subscription``` in a way that would set the wrong values, but I want to avoid somebody accidentally doing this in the future.

**Comment by benrudolph** [comment]
aha that makes a lot more sense. thanks

**Pull request merged**
