### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by emord**
Curious why we have mo files in the repo

http://docs.readthedocs.org/en/latest/i18n.html#compiling-to-mo

> Also, note that it’s not a good idea to track MO files in version control, since they would need to be updated at the same pace PO files are updated, so it’s silly and not worth it. They are ignored by .gitignore, but please make sure you don’t forcibly add them to the repository.

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
@emord we probably can remove them as long as we run compilemessages on all machines as part of deploy. is that what you're proposing?

**Comment by emord** [comment]
@czue was asking for informational purposes. Ran across that documentation while I was looking at how to update the translations and wasn't sure why we went against it

**Comment by czue** [comment]
yeah i'm guessing just that we never integrated it into deploy. should be easy though

**Comment by czue** [comment]
https://github.com/dimagi/commcare-hq/pull/6475

**Pull request merged**
