### PR TITLE
Remove zeep

### PR DESCRIPTION
**Pull request by emord**
@mkangia @kaapstorm (low priority) I think that this a question for you guys. I noticed zeep was quite out of date, but I also think it's effectively unused since enikshay code was deleted. What is the best way to assert they are no longer in use?

The mixin was originally used in the custom/eniskhay directory and doesn't appear to have anymore references https://github.com/dimagi/commcare-hq/blob/6fe86e4a1d7e79d1a59d2af69a5c83efbdaf2516/custom/enikshay/integrations/nikshay/repeaters.py#L191

I'm not sure what I would do with the following, but I think they could also be removed (along with some other references linked to their code):

https://github.com/dimagi/commcare-hq/blob/je/remove-zeep/corehq/motech/repeaters/views/repeat_records.py#L268-L271
https://github.com/dimagi/commcare-hq/blob/je/remove-zeep/corehq/motech/repeaters/views/repeaters.py#L242

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]
I think this, and the linked code is safe to remove.

**Comment by mkangia** [comment]
if we dont want to support SOAP repeaters anymore then, we should also remove SOAPCaseRepeaterForm and then related view.
Can then also remove https://github.com/dimagi/commcare-hq/blob/349bae40efbfdf3960b1b3b7b2d0c59561b4c929/corehq/motech/repeaters/forms.py#L50

And also change the repeater form to remove soap when creating a repeater as an option?

**Comment by kaapstorm** [comment]
**YES** to dropping `SOAPCaseRepeaterForm` (and `SOAPLocationRepeaterForm`, `AddCustomSOAPCaseRepeaterView`, and `AddCustomSOAPLocationRepeaterView`).

**NO** to dropping `skip_cert_verify`. Other repeaters use that too now.

**Review by kaapstorm — APPROVED** [review]

**Comment by kaapstorm** [comment]
(We use **suds-jurko** (the maintained fork of **suds**) for OpenClinica integration, which sadly has been used once. We should probably earmark it for killing too.)

**Comment by emord** [comment]
Thanks for adding the commit to remove the UI @kaapstorm

**Pull request merged**
