### PR TITLE
Standardized and condensed lookup table popup

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
Before
Screen Shot 2021-01-26 at 5 50 26 PM

After
Screen Shot 2021-01-26 at 7 48 26 PM

## Feature Flag
Case search & claim

## Product Description
Not worth announcing

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

None.

### QA Plan

Not requesting QA. Low-risk, HTML-only, tested locally.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by sravfeyn — APPROVED** [review]

**Comment by sravfeyn** [comment]
Neat 💯

**Comment by orangejenny** [comment]
Hey @sravfeyn did you mean to add another commit to this branch?

**Comment by sravfeyn** [comment]
Ah, I am so sorry, let me undo that.

**Comment by orangejenny** [comment]
@sravfeyn thanks!

**Pull request merged**
