### PR TITLE
exclude system forms form submit history

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?228874
@orangejenny

### CODE REVIEW

**Comment by czue** [comment]
@dimagi/product does this make sense to you? it will exclude forms from case importer, reassign cases, as well as random supply forms from submit history (I think these will then only be accessible through "raw forms"). @snopoke correct me if that's not right

**Comment by snopoke** [comment]
The reason this specific case is an issue is that the forms are submitted with the user_id of the mobile worker which is why they show up in that report. As far as I can tell no other 'system' forms are submitted with the user_id of a mobile worker:

* CommCare supply forms are have a different XMLNS and are submitted with the `commtrack-system` username and user_id
* The case importer uses the same XMLNS as in this PR but submits the forms as the currently logged in web user
* Reassign cases uses a different XMLNS but also submits the forms as the currently logged in web user

**Comment by czue** [comment]
offlined with @snopoke 

just to clarify - this does remove all those forms from this report for other filter configurations (e.g "unknown users") but you can still access those forms through the history tab on the case details page which seems like good behavior to me. i think it's often a source of confusion when system forms show up here

**Comment by czue** [comment]
:+1: to merge whenever product signs off

**Comment by sheelio** [comment]
@dimagi/product @snopoke @czue 

I end up using the functionality to find system forms a fair bit (i.e. to reverse a case import that when wrong).  What's driving removing these forms?  I thought they only appear under Unknown User

**Comment by czue** [comment]
supply forms show up under mobile workers. we could more surgically apply the patch there if that makes more sense. you could still access the importer forms from the case list --> history

**Comment by snopoke** [comment]
Updated so that supply forms aren't created 'as' the mobile worker. Also removed the XMLNS filter if the `Unknown Users` filter is active.

**Comment by czue** [comment]
:+1: on :white_check_mark:

**Pull request merged**
