### PR TITLE
Remove a runner

### PR DESCRIPTION
**Pull request by benrudolph**

### CODE REVIEW

**Comment by czue** [comment]
now you're just getting greedy

**Comment by benrudolph** [comment]
haha i'm gonna kill for now, but i think we're getting kind of close. maybe i'm just always too optimistic

**Comment by benrudolph** [comment]
(my math is each run is now ~30 mins, and it takes 5 mins to setup, so that's two test runners with 60 mins. however we can subtract out 5 mins since the loss of test time, thus we're sitting somewhere in the 50s)

**Comment by czue** [comment]
haha, i was mostly joking - would be amazing if we could do this and curious whether it passes or not

**Comment by emord** [comment]
I'll start this up at EOD boston time so we can see where we're at without clogging up the queue. Sounds like a great goal for test team though

**Comment by benrudolph** [comment]
indeed!

**Comment by benrudolph** [comment]
damn, close

**Comment by emord** [comment]
Tests that weren't run:

```
custom.icds_reports.ucr.tests.test_child_health_monthly.TestChildHealthDataSource ... SKIP: divided-we-run: 8 not in range 07
custom.ilsgateway.tests.handlers.rec.ReceiptTest ... SKIP: divided-we-run: e not in range 07
custom.ilsgateway.tests.handlers.soh_slab.SOHSLABTest ... SKIP: divided-we-run: 9 not in range 07
custom.ilsgateway.tests.handlers.stockout.TestStockout ... SKIP: divided-we-run: f not in range 07
custom.ilsgateway.tests.handlers.yes.TestYes ... SKIP: divided-we-run: d not in range 07
custom.ilsgateway.tests.test_delete_domain.TestDeleteDomain ... SKIP: divided-we-run: f not in range 07
custom.ilsgateway.tests.test_handlers.TestHandlers ... SKIP: divided-we-run: a not in range 07
custom.ilsgateway.tests.test_reminders.TestReminders ... SKIP: divided-we-run: f not in range 07
custom.ilsgateway.tests.test_reminders2.TestDeliveryReminder ... SKIP: divided-we-run: a not in range 07
custom.ilsgateway.tests.test_reminders2.TestRandRReminder ... SKIP: divided-we-run: d not in range 07
custom.ilsgateway.tests.test_reminders2.TestSOHThankYou ... SKIP: divided-we-run: e not in range 07
custom.ilsgateway.tests.test_reminders2.TestStockOnHandReminders ... SKIP: divided-we-run: b not in range 07
custom.ilsgateway.tests.test_report_reminders.TestRandRSummary ... SKIP: divided-we-run: 9 not in range 07
custom.ilsgateway.tests.test_report_reminders.TestSoHSummary ... SKIP: divided-we-run: c not in range 07
custom.intrahealth.tests.test_fluffs.TestFluffs ... SKIP: divided-we-run: 9 not in range 07
custom.intrahealth.tests.test_reports.TestReports ... SKIP: divided-we-run: a not in range 07
custom.openclinica.tests.test_odm_to_app.OdmToAppTest ... SKIP: divided-we-run: d not in range 07
custom.uth.tests.uth_tests.ImageUploadTests ... SKIP: divided-we-run: e not in range 07
custom.uth.tests.uth_tests.ScanLookupTests ... SKIP: divided-we-run: 8 not in range 07
custom.world_vision.tests.test_mother_fluff.TestMotherFluff ... SKIP: divided-we-run: a not in range 07
auditcare.tests.auth.AuthenticationTestCase ... SKIP: divided-we-run: b not in range 07
auditcare.tests.modelevents.ModelEventTestCase ... SKIP: divided-we-run: b not in range 07
django_digest.tests.DbBackendTests ... SKIP: divided-we-run: e not in range 07
django_digest.tests.ModelsTests ... SKIP: divided-we-run: 9 not in range 07
testapps.test_pillowtop.tests.test_app_pillow.AppPillowTest ... SKIP: divided-we-run: e not in range 07
testapps.test_pillowtop.tests.test_case_pillow.CasePillowTest ... SKIP: divided-we-run: f not in range 07
testapps.test_pillowtop.tests.test_case_search_pillow.CaseSearchPillowTest ... SKIP: divided-we-run: 9 not in range 07
testapps.test_pillowtop.tests.test_grouptouser_pillow.GroupToUserPillowDbTest ... SKIP: divided-we-run: f not in range 07
testapps.test_pillowtop.tests.test_grouptouser_pillow.GroupsToUserReindexerTest ... SKIP: divided-we-run: c not in range 07
testapps.test_pillowtop.tests.test_ledger_pillow.LedgerPillowTest ... SKIP: divided-we-run: d not in range 07
testapps.test_pillowtop.tests.test_reindexer.UserReindexerTest ... SKIP: divided-we-run: 8 not in range 07
testapps.test_pillowtop.tests.test_report_xform_pillow.ReportXformPillowTest ... SKIP: divided-we-run: a not in range 07
testapps.test_pillowtop.tests.test_report_xform_pillow.ReportXformReindexerTest ... SKIP: divided-we-run: c not in range 07
testapps.test_pillowtop.tests.test_user_pillow.UserPillowTest ... SKIP: divided-we-run: d not in range 07
testapps.test_pillowtop.tests.test_xform_pillow.XFormPillowTest ... SKIP: divided-we-run: b not in range 07
SKIP: because settings.SKIP_TOUCHFORMS_TESTS
Must be run manually (see util.TouchformsTestCase) ... SKIP: divided-we-run: f not in range 07
SKIP: because settings.SKIP_TOUCHFORMS_TESTS
```

**Comment by emord** [comment]
Close. All the tests actually ran on the failing job.

**Comment by benrudolph** [comment]
so frustrating.. haha. going to be hard to actually feel comfortable merging this

**Comment by emord** [comment]
O.O This just passed with 5 min to spare on each job

**Comment by benrudolph** [comment]
🐎 😂  let's do it!

**Comment by benrudolph** [comment]
A MAN _CAN_ WISH!

**Pull request merged**
