### PR TITLE
Removed "Enikshay: Add option to index custom location fields" flag

### PR DESCRIPTION
**Pull request by orangejenny**
@mkangia You're the only one with this turned on.

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
Huh, I'm kinda surprised ICDS doesn't use this

**Comment by orangejenny** [comment]
Do you think it's worth following up? I've been figuring there's enough overlap between the old enikshay and current ICDS teams that they're aware of all the flags that might be useful.

**Comment by emord** [comment]
fwiw I don't think its that useful for ICDS because their location usage is much more simple than enikshay's was and users sync very few locations anyways. If they aren't using it now, feels like its still good to kill

**Comment by mkangia** [comment]
Feels like i should delete all my project spaces. and then start afresh.

**Review by mkangia — APPROVED** [review]

**Comment by mkangia** [comment]
@orangejenny once these PRs are merged, the toggle would be gone and so the names of domains that have these enabled. Can you put them in the description so we/I know which ones to delete?

**Comment by orangejenny** [comment]
@mkangia The ones that only you have on are all for `enikshay-temp`

**Pull request merged**
