### PR TITLE
Fix report module icon path changes

### PR DESCRIPTION
**Pull request by NoahCarnahan**
http://manage.dimagi.com/default.asp?212305
It might be worth adding some documentation to `AppMenuMediaManager`. There are few similar properties that all seem like they could signify similar things: `ref`, `currentPath`, `savedPath`, and `customPath`.

cc @calellowitz

### CODE REVIEW

**Comment by wpride** [comment]
:tight:

**Comment by benrudolph** [comment]
i wonder what a :tight: emoji might look like...

**Comment by wpride** [comment]
@benrudolph it would look like chazzzz https://www.youtube.com/watch?v=kJVmpLGjIdE

**Comment by NoahCarnahan** [comment]
(check slack for a new way to express your emotions)

**Pull request merged**
