### PR TITLE
Add a webapps btn if the use has that default landing page

### PR DESCRIPTION
**Pull request by ghost**
**Specs:**: This is to address this task:
> The initial login when you set up 2FA just dumps you in your profile with no discernible way to get to WebApps. Can we make it direct you to the default landing page that is defined in the mobile worker's role  instead (the second login worked as expected)

from [this doc](https://docs.google.com/document/d/1gZlOGroRTeUMHXwzCuOVw2EUuJcjOsAaAe1qc2iUEe0/edit#)

**Details:** After setting up 2fa, you're given the option to generate a backup token. Because you probably still want that option (instead of automatically redirecting to webapps), I added a link to go to webapps, on both the 2fa success page, and the page where backup tokens are generated, if the user has the default landing page `webapps`

**Questions:** 
* A user can have membership to multiple domains, so I just checked whether the first one on the list has the default landing page `'webapps'`. Is there a better way to do this?

**Images:** See the 'To Webapps' links in both these screenshots (bottom right corner):

Screen Shot 2020-04-06 at 5 27 25 PM
Screen Shot 2020-04-06 at 5 27 38 PM

### CODE REVIEW

**Comment by orangejenny** [comment]
> Because you probably still want that option (instead of automatically redirecting to webapps)

I think this is logical but also think users are likely to still get lost. If these are first time users, they may not know that "web apps" is the name of the thing they want, and visually it doesn't look like the obvious next thing to click on.

Two alternatives come to mind:

1) Do the automatic redirect to web apps, and use a success message saying something like "Congratulations, you've successfully enabled two-factor authentication. Please generate a backup token in case you can recover your account." and make the "generate a backup token" text a link that opens in a new tab.

2) Modify `tabclasses.py` so WebApps shows in the top nav even when you aren't logged into a domain. You can use the [domain select view with the next_view param](https://github.com/dimagi/commcare-hq/blob/d51fd777c8108bc981915755364c9de06a08cc96/corehq/apps/domain/views/base.py#L26) to redirect someone to choose a domain and then continue on to a specific view in that domain.

What do you think?

**Comment by orangejenny** [comment]
@dimagi/product or @czue might also have thoughts on the best workflow to use here.

**Comment by czue** [comment]
> A user can have membership to multiple domains, so I just checked whether the first one on the list has the default landing page 'webapps'. Is there a better way to do this?

I think for now you can also check if they are a mobile worker (`CommCareUser`) and only invoke the custom logic if they are. Mobile workers will only have one domain.

> Do the automatic redirect to web apps, and use a success message saying something like "Congratulations, you've successfully enabled two-factor authentication. Please generate a backup token in case you can recover your account." and make the "generate a backup token" text a link that opens in a new tab.

I have mixed feelings on this. I like the navigation flow, though I think it is likely to reduce the number of people who actually generate backup tokens which may or may not be a problem...

> Modify tabclasses.py so WebApps shows in the top nav even when you aren't logged into a domain. You can use the domain select view with the next_view param to redirect someone to choose a domain and then continue on to a specific view in that domain.

This sounds like a good change regardless. If we go this route over the automatic redirect, I'd also recommend keeping the additional button, but maybe changing the text to something like "Continue" or "Go to Data Entry" (Nick might have opinions) and make it as prominent as the "generate tokens" action.

**Comment by nicknestle** [comment]
I'd prefer the auto-redirect straight to webapps before the backup tokens option.  But if you want to go to the Backup Tokens page first, the button to webapps should be green (?) and right next to the Generate Tokens button. It should say "Being Using CommCare Now".  Users don't know what webapps is.

Also, this may be a different ask ... but the landing page for enabling 2FA says "Permission Denied" really large and scarily.  The user I watched almost closed the window to try again.

@czue @orangejenny

**Comment by preeth1** [comment]
Okay, I followed @nicknestle's comment [here](https://github.com/dimagi/commcare-hq/pull/27080#issuecomment-610591638) along with some guidelines from Jenny, and updated it to look like this:
Screen Shot 2020-04-08 at 4 19 08 PM
Screen Shot 2020-04-08 at 4 20 17 PM
Screen Shot 2020-04-08 at 4 21 16 PM

One thing- in talking with @orangejenny I made this button only show up for requests with the `TWO_STAGE_USER_PROVISIONING` flag turned on (my last commit), but that makes it so that the button never shows up anymore. I believe that's because that feature flag can be turned on for a certain domain, whereas updating 2fa settings applies to a user and not a domain. Hoping to get some feedback on that!

**Comment by orangejenny** [comment]
Added a commit to update the feature flag logic, opened https://github.com/dimagi/commcare-hq/pull/27102

**Comment by nicknestle** [comment]
Awesome, thanks so much!

**Pull request merged**
