### PR TITLE
migrate attachments

### PR DESCRIPTION
**Pull request by snopoke**
Migration to retroactively copy attachments to edited forms + a fix to the copy over `content_length` and the correct bucket.

### CODE REVIEW

**Review by gcapalbo — APPROVED** [review]
would it be better if this wrote to a log file rather than use print? or were you planning on capturing standard out

**Comment by sheelio** [comment]
@gcapalbo

I think Simon is offline - is this good to merge? The customer pinged me and asked me about.

**Comment by gcapalbo** [comment]
yeah my comment is not blocking merge but i'm guessing @snopoke would likely be the one to run this since he has the most context on it and probably would like to monitor its run. i'll merge so it gets into today's deploys

**Comment by snopoke** [comment]
Meant to comment that I'd already run it on all prod, softlayer and ICDS

**Pull request merged**
