### PR TITLE
remove method added for interim

### PR DESCRIPTION
**Pull request by mkangia**
As a follow up to https://github.com/dimagi/commcare-hq/pull/24862/
The new column is now populated for all entries on
Production
Staging
TCL/ICDS
India
which were using the FF.

FF: `RELEASE_BUILDS_PER_PROFILE`

### CODE REVIEW

**Comment by orangejenny** [comment]
> The new column is not populated...

Is this supposed to read "The new column is **now** populated?

**Comment by mkangia** [comment]
@orangejenny thats right, thanks for catching that.

**Comment by orangejenny** [comment]
@mkangia cool, looks good then

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
The build failure is unrelated (job is exceeding time limit) and the change is pretty safe so going to merge this.

**Pull request merged**
