### PR TITLE
delete pathindia custom reports

### PR DESCRIPTION
**Pull request by esoergel**
Requires reindex
@czue @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
yeah :baby:!

**Comment by czue** [comment]
woohoo! :skull:

**Comment by esoergel** [comment]
@dannyroberts I just realized I'm deleting the whole design doc, so this won't actually require a reindex, right?  In that case, this is g2m whenever.

**Comment by dannyroberts** [comment]
Oh HELL yeah! Good call.

**Comment by dannyroberts** [comment]
:goberserk:

**Comment by czue** [comment]
:horse_racing:

**Pull request merged**
