### PR TITLE
disable _all field for form, case and sms indexes

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
This removes the `_all` field form case, form and SMS indexes. This will stop us from using query_string queries on these indexes but we do not use that for these anyway. We DO use query_string queries from user and group indexes so I've left the _all field on those indexes.

When this was applied to the [case_search index](https://github.com/dimagi/commcare-hq/pull/20501#issuecomment-388054271) it reduced the size from 2.26GiB to 1.69GiB.

ES docs: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-all-field.html#mapping-all-field

### CODE REVIEW

**Comment by emord** [comment]
Does this have any affect before we re-index?

**Comment by dannyroberts** [comment]
I had essentially the same question as Emord; I'm used to seeing us change the index name, e.g.

```diff
- CASE_INDEX = es_index("hqcases_2016-03-04")
+ CASE_INDEX = es_index("hqcases_2019-10-18")
```
so that the change also triggers a full reindex. Is there an alternate workflow/convention for pushing out an "optional" change like this and then allowing each teach to reindex their environments manually if and when desired?

**Comment by esoergel** [comment]
:+1: to the change.

Regarding the existing use of `_all`, I think it'd be preferable to explicitly specify search fields, and let query string queries search within that whitelist.  It really only makes sense to let users search a small subset of the mapped fields, particularly since many aren't intended to be user accessible.  I know ES lets you specify a default set of fields to search, but I'm not sure it lets you restrict the fields searched in a `"field:value"` query string query.  That's probably well out of scope for this PR, of course.

**Comment by snopoke** [comment]
:cry: @dannyroberts it would appear you are correct and you can't disable the `_all` field on an existing index. 

In that case this will have to wait until we've upgraded ES.

Also note that from v6.0 the `_all` field is deprecated: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/mapping-all-field.html#mapping-all-field

**Pull request closed without merging**
