### PR TITLE
refuse to rebuild tables that aren't based on the latest data source

### PR DESCRIPTION
**Pull request by czue**
@NoahCarnahan @TylerSheffels still not sure when this happens but I'm hoping that this might be sufficient to fix the problem.

### CODE REVIEW

**Comment by TylerSheffels** [comment]
Looks good to me, as a followup should any table rebuild also re-insert all of the previous data. E.g. 

Someone is making changes and saves a few times, during the pillow processing of each consecutive save this change prevents the table from rebuilding.  On the last save, where the table schema matches the current version the rebuild should also pick up historical data not just new data in the pillow.

**Comment by czue** [comment]
yeah potentially. the [static data source already does that](refuse to rebuild tables that aren't based on the latest data source). I'm a little concerned to just do that automatically at the moment since I think there is some value (at least load wise) of supporting multiple edits to happen and then only kicking off a single rebuild

**Comment by TylerSheffels** [comment]
Definitely agree with the performance concern, big tables take a pretty long time to rebuild.  Don't have a great answer then. Either way this is a good by me after tests.

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
