### PR TITLE
don't use queryset, return object list

### PR DESCRIPTION
**Pull request by sravfeyn**
@proteusvacuum

### CODE REVIEW

**Review by czue — APPROVED** [review]
curious why we don't want it chainable, but makes sense to do this given that we don't.

confirming you double checked no one was _already_ using it as a queryset? feel free to self merge after you confirm.

**Review by proteusvacuum — APPROVED** [review]
Thanks for the quick followup! Also curious why we don't want this to be chainable? Having it chainable would allow for filtering this list down further directly in the database, and I don't think would change the way this method is called.

**Comment by proteusvacuum** [comment]
see this commit for an argument in favour of having this method chainable: 
https://github.com/dimagi/commcare-hq/pull/14019/commits/9cc49a86d380f2432d10be013892137aa030e37f
(up to you though as to what you want to do)

**Comment by sravfeyn** [comment]
Hey, I went back n forth between two ways without much arguments in favour for either of those things. I changed it to chainable.

**Comment by benrudolph** [comment]
nice i'm a fan!

**Comment by czue** [comment]
nice

**Comment by esoergel** [comment]
Nice find, @proteusvacuum , and thanks for the update, @sravfeyn !  I agree with the arguments here and am a fan of having it chainable.

**Pull request merged**
