### PR TITLE
Improved error message

### PR DESCRIPTION
**Pull request by kaapstorm**
Current error message is misleading when the path exists, but the form element it refers to is not a question and so its value can't be assigned to a case property.

This change is for [FB 161875](http://manage.dimagi.com/default.asp?161875).

### CODE REVIEW

**Comment by kaapstorm** [comment]
BEFORE:
bug_161875_before

AFTER:
bug_161875_after

**Comment by dannyroberts** [comment]
@amsagoff while we're changing the text, do you have a suggestion for the clearest user-facing text for this error? Assigning to @amsagoff to merge when acceptable.

**Comment by dannyroberts** [comment]
for context, in this particular case, the "invalid path" was actually a path to a label (i.e. what @kaapstorm is calling "not a question")

**Comment by kaapstorm** [comment]
Indeed, @dannyroberts. @amsagoff I called it "not a question" because the code finds valid paths using the "get_questions" method. ... https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/models.py#L907 ... but maybe there's a better term, like "doesn't have a value", because hidden values aren't really questions, but are valid paths.

**Comment by amsagoff** [comment]
I propose: "The case management in form references a question that no
longer exists: "/data/restofpath". It is likely that this question has been
renamed or deleted. Please update or delete this question reference before
you make a new version".

Norman - to the user hidden values, labels, etc. are still called questions
(we dont have separate terminology)

Bonus points if you can change  "Build errors in this form" to "Errors
making a new version" :)

lmk if this doesn't make sense

**Comment by kaapstorm** [comment]
Thanks @amsagoff. I've used your wording. 

Ro has also taken back [FB 161875](http://manage.dimagi.com/default.asp?161875) and will change the case management.

**Comment by rowenaluk** [comment]
like it. thanks!

**Pull request merged**
