### PR TITLE
Added test

### PR DESCRIPTION
**Pull request by kkrampa**
Please don't merge. It fails locally and I'm curious if it also fails on travis.

### CODE REVIEW

**Comment by kkrampa** [comment]
@snopoke @nickpell @esoergel 
```
======================================================================
ERROR: corehq.apps.users.tests.test_domain_request:TestDomainRequest.test_domain_request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/users/tests/test_domain_request.py", line 10, in test_domain_request
    self.assertEqual(requests.count(), 0)
  File "/vendor/lib/python2.7/site-packages/django/db/models/query.py", line 369, in count
    return self.query.get_count(using=self.db)
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/query.py", line 476, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/query.py", line 457, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/vendor/lib/python2.7/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/vendor/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "users_domainrequest" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "users_domainrequest" WHER...
                                          ^
```

This error happens in fresh install. Probably there is no migration for that model in codebase

**Comment by nickpell** [comment]
It looks like ```DomainRequest``` was added in https://github.com/dimagi/commcare-hq/pull/7499 without a migration.  I'm confused how this has been working so far.
@orangejenny any insights?

**Comment by kkrampa** [comment]
2 years ago we used south in old django version. I guess it was created via syncdb.

**Comment by orangejenny** [comment]
@kkrampa sounds right to me.

**Comment by zbidi** [comment]
I still have that error by accessing to Web Users and Roles. Fresh install. Any idea how to solve? 

ProgrammingError at /a/commcare-hq/settings/users/web/

relation "users_domainrequest" does not exist
LINE 1: ...is_approved", "users_domainrequest"."domain" FROM "users_dom...
                                                             ^

Request Method: 	GET
Request URL: 	http://localhost:8000/a/commcare-hq/settings/users/web/
Django Version: 	1.10.7
Exception Type: 	ProgrammingError
Exception Value: 	

relation "users_domainrequest" does not exist
LINE 1: ...is_approved", "users_domainrequest"."domain" FROM "users_dom...

**Comment by orangejenny** [comment]
Hi @zbidi , try running the following.
```
> ./manage.py makemigrations
> ./manage.py migrate
```

**Comment by zbidi** [comment]
thanks @orangejenny it works!

**Pull request closed without merging**
