### PR TITLE
Add Edition.RESELLER for invoice description

### PR DESCRIPTION
**Pull request by mkangia**
http://manage.dimagi.com/default.asp?238181

### CODE REVIEW

**Comment by mkangia** [comment]
@czue : Review please.

**Comment by czue** [comment]
:+1:

**Comment by czue** [comment]
@nickpell does this look reasonable?

**Comment by nickpell** [comment]
```'description'``` could be a little more user friendly.  This is the text that gets shown for the plan at https://www.commcarehq.org/a/nick-project/settings/project/subscription/ (see https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/accounting/user_text.py#L34)

Not a big deal though since all of the Reseller software plans have a custom description that replaces the default description.  Might matter in the future though.

**Comment by mkangia** [comment]
Thanks @nickpell

**Pull request merged**
