### PR TITLE
Add stockreport server date

### PR DESCRIPTION
**Pull request by dannyroberts**
My plan for this is
- merge and deploy this
- (after deploy) PR & merge https://github.com/dimagi/commcare-hq/compare/add_stockreport_server_date...backfill_stockreport_server_date on top of it
- preindex
- run `./manage.py migrate stock` in preindex directory, thus running this migration

### CODE REVIEW

**Comment by dannyroberts** [comment]
Async migration to backfill to come.

**Comment by dannyroberts** [comment]
@czue

**Comment by dannyroberts** [comment]
@NoahCarnahan FYI

**Comment by czue** [comment]
@snopoke this table has about 8 million rows on prod. any gut sense how long we think the migration will run?

**Comment by snopoke** [comment]
Adding the column should be very quick since its allows NULL and doesn't have a default value. I'm not sure about building the index though. I suspect that will still do a full table scan and lock the table. It would probably be a good idea to add it concurrently e.g. https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/casexml/apps/stock/south_migrations/0014_auto__add_index_stocktransaction_case_id_product_id_section_id.py#L11

**Comment by dannyroberts** [comment]
Oh, that's annoying. I don't even think I consciously wanted that index, just kind of copied it from the date one. (Quickly looking at this model's index, I'm noticing there are a couple things that don't make sense—for example, the date index should be (domain, date).) I'm going to just remove the index from this PR, and add it later.

**Comment by snopoke** [comment]
👍

On 6 August 2015 at 16:03, Daniel Roberts <notifications@github.com> wrote:

> Oh, that's annoying. I don't even think I consciously wanted that index,
> just kind of copied it from the date one. (Quickly looking at this model's
> index, I'm noticing there are a couple things that don't make sense—for
> example, the date index should be (domain, date).) I'm going to just remove
> the index from this PR, and add it later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/7788#issuecomment-128376249>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
`./manage.py schemamigration stock --auto --update`, `--update` flag is pretty useful for modifying a migration you're currently working on, in-place.

**Comment by dannyroberts** [comment]
Should be ready to go, pending tests

**Comment by czue** [comment]
neat on `--update`

**Comment by czue** [comment]
:+1: fyi @nickpell  not expecting anything to go wrong, but hopefully short sql migration on deploy

**Pull request merged**
