### PR TITLE
Remove unused export templates

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts i can't seem to find any sort of reference to these templates and it fail all sorts of grep tests. loaded the export page and created an export with them deleted. wondering if you knew if this was just stuff i could delete

cc: @emord @millerdev

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
I don't recognize it. @nickpell looks like you wrote this back in July. Does it make sense that these are no longer used?

**Comment by emord** [comment]
Probably due to bootstrap 3 migration?

**Comment by nickpell** [comment]
I'd believe that these are no longer in use.  Probably part of my work on saved exports that didn't end up being used

**Comment by dannyroberts** [comment]
Great. @benrudolph I'm signed off on this once the tests pass. (They're unlikely to find anything, but just as a paranoid measure.) Thank you for deleting!

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
