### PR TITLE
update text of activation email

### PR DESCRIPTION
**Pull request by czue**
[spec](https://docs.google.com/document/d/1uXrRBe7v8WQB8t-_C7mufqfKa2IystckuN2QY9EU7j0/edit#heading=h.blt0fbwgkgt2)

@gjavetski does this look right?

image

@dimagi/product do you think we should wait for updated translations to something this public facing before deploying?

### CODE REVIEW

**Comment by gjavetski** [comment]
@czue , this looks great to me! @amsagoff

**Comment by czue** [comment]
thinking about it a bit more, I don't think the translations thing is that important since we likely don't know any language preferences at the time of sending this email.

**Comment by czue** [comment]
@biyeun cc @benrudolph @esoergel

**Comment by esoergel** [comment]
:+1: on the new language

**Pull request merged**
