### PR TITLE
add member to show

### PR DESCRIPTION
**Pull request by mkangia**
https://github.com/dimagi/commcare-hq/pull/26941#pullrequestreview-380007088

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
thanks @orangejenny , do i need to rebuild documentation or this is picked automatically?

**Comment by orangejenny** [comment]
I'm not sure, @kaapstorm or @esoergel probably know.

**Comment by esoergel** [comment]
It should be picked up automatically

**Comment by mkangia** [comment]
Thank you, I see it reflecting.

**Pull request merged**
