### PR TITLE
Greedily translate messages on class instantiation

### PR DESCRIPTION
**Pull request by esoergel**
This is blocking the TDH case upload, and resolves the error
`TypeError: <django.utils.functional.__proxy__ object at 0x7f11f1d4bf10> is not JSON serializable`
@benrudolph

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by benrudolph** [comment]
looks good thanks for catchings and fixing

**Comment by czue** [comment]
@esoergel @benrudolph the more conventional fix would have been to use https://github.com/dimagi/dimagi-utils/blob/master/dimagi/utils/web.py#L180

`my_new_json = json.dumps(obj, default=json_handler)`

**Comment by czue** [comment]
(specifically this line handles `ugettext_lazy` https://github.com/dimagi/dimagi-utils/blob/master/dimagi/utils/web.py#L194)

**Pull request merged**
