### PR TITLE
Remove Bitly

### PR DESCRIPTION
**Pull request by kaapstorm**
Best to review per commit, with whitespace off (`github.com/...&w=1`).

Context: [FB 218708](http://manage.dimagi.com/default.asp?218708)

The first commit addresses the bug. Then I figured some cleaning up was in order -- Bitly was always used in the same place as the QR code, and the JavaScript Bitly code doesn't seem to be used anywhere else. And then I thought it looked a little dumb with only one possible installation method, so I changed the copy a little. @amsagoff @orangejenny you probably want to check I haven't done anything bad.

First two commits result in this:
deploy_without_bitly

Last commit changes it to this:
deploy_with_spacing

@calellowitz @benrudolph cc @dannyroberts

### CODE REVIEW

**Comment by dannyroberts** [comment]
@kaapstorm looks good to me. Could I get an OK from someone on @dimagi/product that this is what was being requested?

**Comment by amsagoff** [comment]
Unfortunately this is not what was requested - The ticket is about the
bit.ly link on the barcode screen itself. (See image in ticket:
http://manage.dimagi.com/default.asp?218708).

I apologize, I think product/support could have been clearer when handing
off to interrupt. I'll make a greater effort to do so going forward.

**Comment by benrudolph** [comment]
dig the cleanup though!

**Comment by kaapstorm** [comment]
@amsagoff I'm so sorry. I totally missed the attachment in FogBugz (not sure how). Product/support should not take any responsibility for my inability to read. :unamused:

**Pull request closed without merging**
