### PR TITLE
restrict domain name length

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?236053

@gcapalbo 

@dimagi/product this actually restricts the url length to 25 characters

### CODE REVIEW

**Comment by snopoke** [comment]
This feels a bit crude.. open to suggestions for improvements.

**Comment by gcapalbo** [comment]
@snopoke so it looks like this will truncate a domain name if someone tries to create a domain longer than 25 characters right? i think it might be better to raise a validation error to the user and force them to choose a shorter one rather than automatically truncate

**Comment by amsagoff** [comment]
Can we take advantage of the distinction between human readable name and domain id here? i.e., truncate for the URL but keep the long name for the human readable? (this may be what you are already doing...)

**Comment by snopoke** [comment]
It will truncate the URL segment yes

**Comment by snopoke** [comment]
The issue is that the user doesn't every input the URL segment - they just
enter the domain "human readable name" which can contain spaces etc. So it
seems weird to restrict the HR name just so that we can restrict the URL
segment

**Comment by amsagoff** [comment]
Yeah I think we don't have to truncate the human readable name (or we can truncate it at something ridiculous like 100 - whatever looks good in the UI). We can truncate the id that goes in the URL before we unique-ify it, without needing to touch the human readable name.

**Comment by snopoke** [comment]
updated with more elegant shortening

**Pull request merged**
