### PR TITLE
kill Advanced Submit History Filters feature preview

### PR DESCRIPTION
**Pull request by dannyroberts**
https://trello.com/c/GPGZNZdH/8-advanced-filters-in-submit-history

### CODE REVIEW

**Comment by czue** [comment]
nice! i'm actually surprised there's not more dependent code we can :skull: at the same time

**Comment by dannyroberts** [comment]
@czue I was also surprised, but I couldn't find more than this. Basically, it removes the filter option in the submit history UI, the code that inserts the filter values into the ES query, and the part of the ES mapping pertaining to dynamic properties. Incidentally I was unable to delete the html template for the UI filters, because it's shared by all subclasses of `BaseTagsFilter`, and there's one subclass left. (I could collapse the abstraction into a single class now that there's only one subclass, but I'm not sure it's worth it.)

Can you think of any other component I should look for to delete?

**Comment by czue** [comment]
nothing off the top of my head. just seemed like it would have been a bigger feature.

**Comment by czue** [comment]
(sorry that wasn't meant to be a useful comment, was just ruminating)

**Comment by dannyroberts** [comment]
Ok, should be good to go!

**Comment by dannyroberts** [comment]
@proteusvacuum helper buddy

**Pull request merged**
