### PR TITLE
Switch sole usage of languages/list to ES

### PR DESCRIPTION
**Pull request by esoergel**
paving the way for https://github.com/dimagi/commcare-hq/pull/9958
@dannyroberts @czue @benrudolph

### CODE REVIEW

**Comment by czue** [comment]
awesome! would be pretty cool though possibly out of scope to have some tests for this function.

also not mergeable

**Comment by snopoke** [comment]
:moneybag:

**Comment by esoergel** [comment]
Well I tested it.  Not sure that was worth it, but I wanted to try out using elasticsearch in tests anyways.  There are a lot of unintuitive boilerplate steps you need to take to get it all working - I might try to make a cleaner way for this to work - maybe a decorator or something.

**Comment by czue** [comment]
thanks for following up on the test! will give you a chance to review @benrudolph's feedback but i'm ready to :shipit:

**Comment by esoergel** [comment]
:white_check_mark:

**Comment by benrudolph** [comment]
sizzlin' :fire:

**Pull request merged**
