### PR TITLE
Advanced module persitent case tiles

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Fixes [#184423](http://manage.dimagi.com/default.asp?184423).

There are two places that the `detail-persistent` attribute wasn't being set on datums:
- Datums for advanced module forms
- Datums for advanced module case list menu items

@snopoke @dannyroberts @benrudolph cc @kaapstorm 
Best reviewed commit-by-commit

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
p.s. ICDS wants this fix deployed by monday.

**Comment by snopoke** [comment]
:+1: :disappointed: no tests

**Comment by snopoke** [comment]
Build fail real:
```
======================================================================
FAIL: test_case_tile_suite (corehq.apps.app_manager.tests.test_suite.SuiteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_suite.py", line 341, in test_case_tile_suite
    self._test_generic_suite("app_case_tiles", "suite-case-tiles")
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 71, in _test_generic_suite
    self.assertXmlEqual(self.get_xml(suite_tag), app.create_suite())
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 32, in assertXmlEqual
    _check_shared(expected, actual, LXMLOutputChecker(), "xml")
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 127, in _check_shared
    raise AssertionError(message)
AssertionError: XML mismatch
--- want.xml
+++ got.xml
@@ -290,7 +290,7 @@
     </command>
     <instance id="casedb" src="jr://instance/casedb"/>
     <session>
-      <datum detail-inline="m0_case_long" detail-persistent="m0_case_short" detail-select="m0_case_short" id="case_id" nodeset="instance('casedb')/casedb/case[@case_type='child'][@status='open']" value="./@case_id"/>
+      <datum detail-confirm="m0_case_long" detail-persistent="m0_case_short" detail-select="m0_case_short" id="case_id" nodeset="instance('casedb')/casedb/case[@case_type='child'][@status='open']" value="./@case_id"/>
     </session>
   </entry>
   <entry>
```

**Comment by benrudolph** [comment]
nice! thanks for fixing noah

**Comment by dannyroberts** [comment]
Nice job on the quick turnaround @NoahCarnahan! Tests and everything :)

**Pull request merged**
