### PR TITLE
test revealing child module bug

### PR DESCRIPTION
**Pull request by snopoke**
Test only.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
I've always thought this was intentional behavior, that parent/child menus were only about the menu structure and didn't have anything to do with case selection.

**Comment by snopoke** [comment]
> I've always thought this was intentional behavior, that parent/child menus were only about the menu structure and didn't have anything to do with case selection.

Maybe that's true. Perhaps @shubham1g5  or @ctsims can give a bit more insight into the recommended structure

**Comment by ctsims** [comment]
I can confirm that we definitely intend for the child/parent structures for menus and cases to be decoupled more generally.

I think the child menu structure that was added as a first class feature was the result of a Solutions initiative that @esoergel implemented with @AndreaMKing5. They can probably provide any specifications docs outlining intended function there.

**Review by esoergel — APPROVED** [review]

**Comment by snopoke** [comment]
Closing this PR. I've added some other tests that cover this here: https://github.com/dimagi/commcare-hq/pull/31613/files#diff-8c8134585d5ca172fe67afba98d7141f40a7a357f33bdaf390c990e198712064R386-R425

**Pull request closed without merging**
