### PR TITLE
remove open cases view

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
part three of the case design doc purging. goes with https://github.com/dimagi/commcare-hq/pull/6773 and https://github.com/dimagi/commcare-hq/pull/6775. I've reviewed all other views and they aren't easy to remove so I'm gonna say these are good to go once tests pass and feedback is addressed (removing don't merge labels)

**Comment by czue** [comment]
@NoahCarnahan

**Comment by snopoke** [comment]
:white_check_mark: pending tests

**Pull request merged**
