### PR TITLE
Kill old exports-related code?

### PR DESCRIPTION
**Pull request by dannyroberts**
I think this is still just the tip of the iceberg, but it's hard for me to figure out what else is unused. In theory we shouldn't really be using any couchexport views that generate data schemas because, well, forms and cases aren't always in couch anymore, but that code seems to blend and bleed into code I'm less sure about that seems like some saved exports code.

These entry points at least I was able to verify we have no usage of as far as our proxy logs go back. The only view still in use appears to be `/a/<domain>/reports/export/saved/download/<export_id>/`, which is limited to a few domains. (I'm guessing they set up some automation using an old URL scheme we no longer recommend?)

Thoughts? Thoughts on how much more unused old exports code there might be?

### CODE REVIEW

**Comment by orangejenny** [comment]
fyi @esoergel

**Review by snopoke — COMMENTED** [review]
Hard to review with confidence but nothing stands out immediately. I imagine there is more that can be removed but it probably involves untangling it from new exports.

Have you tried something like https://pypi.org/project/vulture/?

**Comment by esoergel** [comment]
Nice, looks good to me.  Much of the old exports code is closely entwined with new exports stuff.  Several times I've pull a thread and seen how far it goes, stopping when I can't handle it anymore.  I expect getting rid of views should help a lot.

**Comment by millerdev** [comment]
Excellent! Do you feel like this is safe to deploy, or are you unsure/looking for ways to gain more confidence?

If this removal ends up being really hard maybe we can think about and document some best practices for how to evolve features with new and old versions so we do not end up with similar hard removals in the future?

**Comment by dannyroberts** [comment]
@snopoke I've never used vulture but it looks interesting. The first pass gave lots of things it wasn't sure about but I could see it being useful for some things.

@millerdev I think I'm still a little nervous, though I'm fairly sure of my process. I'm going to put it up on staging and test some exports as a sanity check. I'm also a little nervous about removing urls, but logically the fact that no one's used these urls in months should be enough, so I think I'm confident in that too.

**Review by millerdev — APPROVED** [review]

**Comment by dannyroberts** [comment]
Tests pass and everything looks good on staging. Gonna merge and get this in! I've also kicked off an effort to reach out to the last few people using the old export api so that we can do a next round of cleanup soon

**Pull request merged**
