### PR TITLE
remove URLs for old exports

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?188795

@biyeun cc: @emord

### CODE REVIEW

**Comment by biyeun** [comment]
hmm, are you sure? I'm pretty certain this will effect tests and permissions in a very negative way.

**Comment by biyeun** [comment]
@nickpell the removal of these urls should also change the way we handle assigning permissions to these specific reports, too

**Comment by nickpell** [comment]
@biyeun tests passed.  Possible though that untested code is affected in ways that I don't understand.

**Comment by emord** [comment]
looks good to me but will wait for @biyeun to sign off on permissions

**Comment by nickpell** [comment]
@biyeun I deployed these changes to staging.  Can you check if the error you're expecting is reproducible, and if so, send me repro steps?

**Pull request merged**
