### PR TITLE
Kill `hq.legacy.js`

### PR DESCRIPTION
**Pull request by NoahCarnahan**
`hq.legacy.js` is very similar to `main.js`. Both define a few functions that the other does not, and some of their shared functions have minor differences. As far as I can tell, the minor differences between shared functions were the result of people making changes/bug fixes to `main.js` without changing the corresponding code in `hq.legacy.js`.

Therefore, my approach to eliminating `hq.legacy.js` is to:
1. Remove it from pages where it is not being used
2. Adjust modules/templates so that `hq.legacy.js` contains _only_ a subset of the functionality in `main.js`
3. Replace usages of `hq.legacy.js` with `main.js`

Step 2 turned out to be not so hard after I determined that the things in `hq.legacy.js` that were not already in `main.js` were either not being used or being defined elsewhere as well.

@biyeun best reviewed commit-by-commit
cc @kaapstorm

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
I'm going to put this on staging for a few days just in case.

**Comment by NoahCarnahan** [comment]
@orangejenny you might be interested in this as well

**Comment by dannyroberts** [comment]
:joy:

**Comment by orangejenny** [comment]
This looks great to me. Agree that it should live on staging for a little bit. Assume you also did some sanity testing of reports / fixtures / some B2 pages / some B3 pages?

**Comment by biyeun** [comment]
Note that this will interfere with the B3 report migrations, as they're going off of legacy like the old reports (I didn't want to touch that as part of the migration)

**Comment by biyeun** [comment]
So, leaving it on staging will interfere with QA as is, deleting hq.legacy as part of a separate PR would be better for this

**Comment by dannyroberts** [comment]
Might be worth you two syncing about how exactly the two PRs interfere
(unless you totally understood that @NoahCarnahan; I didn't quite), in case
there's something useful that can be done—or that will have to be done—to
reconcile the too. Feel free to ignore if I'm just missing context.

**Comment by biyeun** [comment]
nm I think this will actually be fine!

**Comment by czue** [comment]
wow this is a nice unexpected :gift: !

**Comment by mwhite** [comment]
https://github.com/dimagi/commcare-hq/pull/2539

**Comment by czue** [comment]
Lol. Guess it was still relevant.

**Comment by kaapstorm** [comment]
:+1: :+1: :+1:

**Comment by biyeun** [comment]
LOL

**Comment by NoahCarnahan** [comment]
No issues reported on staging, so I think this is good to go!

**Pull request merged**
