### PR TITLE
Fix header caching when roles are updated.

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Summary

Presently if we update a role then for the next 500 seconds stale options are displayed on the header tab. The PR
- Added role revision id to the list of vary_on on template cache.
- Updates the cache busting logic and include `role._rev` in it.
- Updates the usage of function `clear_dropdown_cahe` to pass `couch_user` instead of `user_id`. 
## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Safety story

The changes only update the way we cache header tab and the way we bust it. I have tested it locally and put it on staging too.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by orangejenny** [comment]
This'll need handling for [enterprise permissions users](https://confluence.dimagi.com/display/ccinternal/Enterprise+Permissions), who can access domains where they don't have memberships. Their permissions are controlled by their membership in a controlling "source" domain, so I think you can just use the rev of their role in the source domain.

**Comment by orangejenny** [comment]
Hi Amit, your latest commit might have fixed this, but FYI I'm seeing a bunch of [these](https://sentry.io/organizations/dimagi/issues/2196122425/?environment=staging&project=136860&query=is%3Aunresolved&statsPeriod=14d) on staging. Looks like it's affecting non-domain pages like account settings.

**Comment by AmitPhulera** [comment]
> This'll need handling for enterprise permissions users, who can access domains where they don't have memberships. Their permissions are controlled by their membership in a controlling "source" domain, so I think you can just use the rev of their role in the source domain.

@orangejenny Is there a way in which I can figure it out from the user model that I have to check for source domain permissions.


> Hi Amit, your latest commit might have fixed this, but FYI I'm seeing a bunch of these on staging. Looks like it's affecting non-domain pages like account settings.

Sorry about that 😅  but I guess the deployment to staging last night fixed it. The account settings page is working fine for me now.

**Comment by orangejenny** [comment]
> Is there a way in which I can figure it out from the user model that I have to check for source domain permissions.

There's an `allow_mirroring` flag on some functions. `get_domain_membership` has it and defaults to true, so if you got the role via the membership it should work. You could also add an `allow_mirroring` param to `get_role` and add it to that function's calls to `get_domain_membership` and `is_member_of`.

**Comment by orangejenny** [comment]
Hey @AmitPhulera , is this going through QA? I think it would be a good idea.

**Comment by AmitPhulera** [comment]
Hey @orangejenny 

I have tested the case with Mirrored domain and it was working fine. But I was not able to reproduce the error that we saw on Sentry but I have handled that case.

> Hey @AmitPhulera , is this going through QA? I think it would be a good idea.

I think it would be a good idea to pass it through QA but what do you think the ideal QA strategy would be for this? Would it be entire HQ regressions testing or just making sure every page works fine?

**Comment by orangejenny** [comment]
Part of what we'd get out of QA is the QA team's perspective on what should be tested 🙂   Definitely new user registration, mirror domains, a couple of pages that are domain-specific and a couple of pages like accounting settings that aren't domain-specific. And of course the issue that you're fixing, verifying that the cache gets cleared immediately upon changing a role. Maybe also testing around linked project space user roles.

**Comment by biyeun** [comment]
agree with @orangejenny this should go through QA. I think checking the navigation headers permutating across the set of permissions that could modify them (exports, reports, apps, webapps, etc), and checking for both regular domain users and enterprise permissions. new user registration like jenny mentioned is also a great idea. and also checking that these headers update properly when the project itself has subscription downgrades (loss of webapps privilege and messaging privileges for instance).

**Comment by AmitPhulera** [comment]
Hey @orangejenny and @biyeun,
The QA has been done on this and things were looking good in QA.

**Review by orangejenny — APPROVED** [review]

**Review by biyeun — APPROVED** [review]

**Pull request merged**
