### PR TITLE
Replace group views

### PR DESCRIPTION
**Pull request by nickpell**
This came up in the perf meeting, but just wanted to check my understanding.

Replacing `groups/by_name` with a call to by_domain and filtering in python is a bad idea because domains may contain a huge number of groups. (see changes for details)

It's less clear to me whether or not replacing `groups/by_domain` is a good idea, because either way you have a view that will have to return a large number of objects.  Not sure if utilizing `get_docs_in_domain_by_class` makes this worse.  @dannyroberts Thoughts?

(PRing code I had written for reference)

### CODE REVIEW

**Comment by czue** [comment]
I don't see any reason not to replace `groups/by_domain` since it's doing the same thing as `get_docs_in_domain_by_class`, however I think we should either convert the latter to use `iter_docs` or write a second function that returns a generator and paginates the couch view.

**Comment by dannyroberts** [comment]
That sounds right. And if we follow cory's suggestion, we could also get rid of the whitelist (which was a bit of a placeholder for a better implementation anyway).

**Comment by dannyroberts** [comment]
- agree `groups/by_name` should stay as it is, as it actually does provide a useful extra index we aren't getting from the shared one.
- agree we can move anything that uses `groups/by_domain` to use the shared one instead. This appears to also be used in `get_sms_autocomplete_context` (to get all Group docs in a domain) which I don't see here. (Probably because this is an intentionally incomplete PR.)
- `refresh_group_views` was essentially a cache invalidation function (though technically what it does is make sure that the views are caught up, not actually remove a cache key); if we want to get rid of it and `stale_group_by_domain`, then I'd recommend `quickcache`ing `Group.by_domain` and calling `Group.by_domain.clear(Group, self.domain)` on any save or delete of a Group. This is made easy with the `QuickCachedDocumentMixin` and overriding its `clear_caches` method (with a call to super).

**Comment by dannyroberts** [comment]
Also `Group`s are saved in the users db like we talked about, so this won't have much of a performance gain, but it does have the benefits we agreed on before. (It also makes reindexing/adding/deleting views very easy.)

**Comment by nickpell** [comment]
closing in place of https://github.com/dimagi/commcare-hq/pull/9289

**Pull request closed without merging**
