### PR TITLE
Removed RESTRICT_APP_RELEASE flag

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
This was ICDS-only, and USH is motivated to reduce complexity in roles & permissions code.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

Limited, this is mostly UI changes.

### QA Plan

Not requesting QA.

### Safety story
Dead code removal in an area of code that's pretty rote.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by mkangia — COMMENTED** [review]
oh! I always thought of this as a good feature even outside ICDS.
not sure about other division but India division might be interested in retaining it for the nutrition project.

**Comment by orangejenny** [comment]
Do you know why it was restricted to the ICDS server? It hasn't been available to anyone else.

**Comment by mkangia** [comment]
> Do you know why it was restricted to the ICDS server?

I think it was simply because ICDS added it. Don't remember at any point when we said, that this should/could not be used outside ICDS. The "ICDS" in the name, i think, was just to identify it as being something for ICDS (but not only).

**Comment by mkangia** [comment]
Possible to hold off on this removal for now? Its okay if you need to remove it and if it makes things easier, we can always add it back if needed.
Meanwhile, I am checking with India division, and trying to have a better process around removing ICDS features.

And a short note from nitish was
> I think its a potentially good feature to have from a best practices perspective, so if there is not a lot of overhead involved I think we should not remove the feature.

And i think the overhead is low

**Comment by mkangia** [comment]
Thank you!

**Pull request closed without merging**
