### PR TITLE
Start Enterprise: Don't fail hard on duplicate message ids

### PR DESCRIPTION
**Pull request by gcapalbo**
@orangejenny

### CODE REVIEW

**Comment by orangejenny** [comment]
This doesn't look like it changes functionality - is it just for code clarity, or am I missing something?

**Comment by gcapalbo** [comment]
@orangejenny it now catches the IntegrityError raised when a duplicate message id is attempted to be inserted into the table. see the comment i left in the code for the explanation

**Comment by orangejenny** [comment]
But wouldn't the `set` previously there have prevented there from being any duplicate message ids?

**Comment by gcapalbo** [comment]
@orangejenny it turns out the duplicate message ids are getting returned from different requests - i had used `set()` because i thought they were coming from the same request, but it turns out that's not the case

**Comment by orangejenny** [comment]
Got it - thanks for explaining.

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
