### PR TITLE
Update Pillow

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?184645

Putting on staging for a bit.

### CODE REVIEW

**Comment by czue** [comment]
not to be confused with our pillows....

**Comment by czue** [comment]
:+1: whenever QA is good

**Comment by orangejenny** [comment]
Made a QA ticket: http://manage.dimagi.com/default.asp?185100

**Comment by orangejenny** [comment]
QA passed, self-merging

**Pull request merged**
