### PR TITLE
Update Abt SMS report data source

### PR DESCRIPTION
**Pull request by NoahCarnahan**
New target numbers for Rwanda
http://manage.dimagi.com/default.asp?209438
@nickpell 
cc @snopoke

### CODE REVIEW

**Comment by nickpell** [comment]
:+1:

**Comment by czue** [comment]
build fail looks related
```
======================================================================
ERROR: test_production_config (corehq.apps.userreports.tests.test_static_data_sources.TestStaticDataSource)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/userreports/tests/test_static_data_sources.py", line 28, in test_production_config
    for data_source in StaticDataSourceConfiguration.all():
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/userreports/models.py", line 415, in all
    custom_data_source_obj = cls.wrap(json.load(f)).to_json()
  File "/opt/python/2.7.9/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/opt/python/2.7.9/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/python/2.7.9/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python/2.7.9/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 368 column 19 (char 11225)
----------------------------------------------------------------------
```

**Comment by NoahCarnahan** [comment]
Should be fixed now. There was a syntax error, and `switch` expressions didn't work with constant literals.

**Comment by czue** [comment]
looks good though could be nice to add tests for literal switches

**Comment by NoahCarnahan** [comment]
Switch constant literal test: https://github.com/dimagi/commcare-hq/pull/10061

**Pull request merged**
