### PR TITLE
Set extension relationship when syncing

### PR DESCRIPTION
**Pull request by proteusvacuum**
- Index relationship was not getting set correctly in the `<index>` block
- When newly created extension cases were sent back to HQ, their relationship status was not getting set correctly. Now it should be. :two_men_holding_hands:

@kaapstorm 
code bud: @biyeun

### CODE REVIEW

**Comment by snopoke** [comment]
not tests :cry:

**Comment by proteusvacuum** [comment]
Please don't cry @snopoke

**Comment by snopoke** [comment]
:white_check_mark: :smile: no more tears

**Comment by kaapstorm** [comment]
:+1: Thanks, @proteusvacuum

**Pull request merged**
