### PR TITLE
Changed invitation email

### PR DESCRIPTION
**Pull request by kkrampa**
@biyeun 
http://manage.dimagi.com/default.asp?251771

Could you provide me a logo shown in the doc?

email

### CODE REVIEW

**Comment by biyeun** [comment]
@kkrampa can you borrow the template of the welcome email for this? This misses the banner image, for instance. Thanks!

**Comment by kkrampa** [comment]
@biyeun Should I make this exactly the same as welcome email? I thought it should look like on screen included in the doc

**Comment by biyeun** [comment]
@kkrampa it should have the same content as the doc, but the same appearance in the header and body as the welcome email.

**Comment by kkrampa** [comment]
@biyeun 
email

**Comment by biyeun** [comment]
Looks great!

**Pull request merged**
