### PR TITLE
HQ Help Bubble Text Changes

### PR DESCRIPTION
**Pull request by pnaw94**
@fyniac couldn't find the given text of "Parent Type" bubble anywhere in project.

### CODE REVIEW

**Comment by krsdimagi** [comment]
@pnaw94 this was an old help bubble that I don't think exists anymore.  It was replaced with "Parent Level" at some other point: /settings/locations/location_types/

The text for that bubble is fine - no changes needed.  Sorry for the confusion!

**Comment by biyeun** [comment]
waiting on build

**Comment by pnaw94** [comment]
@fyniac, @biyeun updated

**Comment by biyeun** [comment]
@pnaw94 looks like another set of merge conflicts. I'm now online after being on vacation for a week

**Comment by pnaw94** [comment]
@biyeun updated

**Comment by biyeun** [comment]
@pnaw94 can you pull the latest master in there? the translation `po` files shouldn't be showing up in the diff...

**Comment by pnaw94** [comment]
@biyeun updated

**Pull request merged**
