### PR TITLE
Create index even if case types are the same

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: [HI-161: Child Case Relationships Missing/Not Being Set][1]

If the child case type is the same as the parent case type, this line was preventing the parent index from being created.

This line of code has existed since 2012. @dannyroberts do you remember why you wrote that? 

I'm not certain that this change won't break anything. **Please don't merge yet.**

  [1]: https://dimagi-dev.atlassian.net/browse/HI-161

### CODE REVIEW

**Comment by dannyroberts** [comment]
Oh, boy! I surprisingly do have a memory of this I think, though it's pretty vague. It seems like something I did intentionally at the time, when we were first add the feature for people to be able to configure parent child relationships in the app builder.

One possibility is that at the time I just thought it didn't make sense to open a subcase that's the same type as the case, that creates a cyclical case relationship hierarchy. (Since then of course, plenty of people have figured out how to put cycles in their case hierarchies, and our case walking code accounts for that.) From the context of the commit, it seems like the feature was not yet being used, so it's unlikely that I did it in response to a live bug. I may still have had some good reason to do it that appeared locally.

It might be worth trying to see how many apps run into this. I think whether or not it was the right decision at the time, there may now be apps depending on this behavior. If you run the analysis and there are only a handful of apps with a subcase creation matching this condition, and most of them aren't actual real apps in use, then changing this in place is a possibility.

**Comment by kaapstorm** [comment]
There are 406 project spaces on prod where one or more apps create subcases that are the same case type as the parent case. Many are test domains, but most don't seem to be. I didn't count the number of affected cases.

**Comment by kaapstorm** [comment]
The `DONT_INDEX_SAME_CASETYPE` feature flag has been enabled for the relevant project spaces on production and softlayer. Dropping the "do not merge" label.

**Review by dannyroberts — APPROVED** [review]
Looks great, thanks for the followup!

**Pull request merged**
