### PR TITLE
[ICDS Dashboard]: fix for ICDS-740; alert banner and side nav fix

### PR DESCRIPTION
**Pull request by dhiraj-beehyv**
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/ICDS-740)

Fixed the ICDS dashboard view when alert is on and side navigation on window resize.

### CODE REVIEW

**Comment by Rohit25negi** [comment]
@dhiraj-beehyv  there are so many files changes. will it be possible for you to break these into smaller commits. so that it will be easier to review

**Comment by dhiraj-beehyv** [comment]
> o review

@Rohit25negi ,

I can break it into different commits, but still 2 of those commit has will have large number of files changed. One commit will be were I set the isAlertActive in the directives and one will be for using that variable to add a class in html templates.

Let me know if you still like to break them up.

**Comment by Rohit25negi** [comment]
can you also put the screen shot please

**Comment by dhiraj-beehyv** [comment]
Okay

**Pull request closed without merging**
