### PR TITLE
make sure set up and tear down methods are called

### PR DESCRIPTION
**Pull request by nickpell**
Need for django 1.8

@esoergel cc: @emord

### CODE REVIEW

**Comment by emord** [comment]
:+1: on :white_check_mark:

any idea why these don't break tests in django 1.7?

**Comment by nickpell** [comment]
> any idea why these don't break tests in django 1.7?

As of django 1.8, tests are run in transactions.  That makes all the setup and and tear down methods necessary or the tests will error.

**Comment by esoergel** [comment]
:one: :point_right: :8ball: !!

**Comment by nickpell** [comment]
✅

**Pull request merged**
