### PR TITLE
Local memory cache for toggles on ICDS

### PR DESCRIPTION
**Pull request by sravfeyn**
Mainly opening this for discussion.

Most of the redis hits on ICDS comes from toggles, which is very low amount of data that seldom changes. So this is a very good fit for local memory caching. If cached locally, we could avoid a substantial amount of redis hits.

Main problem with this is  invalidation, since clearing the cache would clear it on only one django worker but not all, so, if a toggle is updated, it may not be consistent for the duration of the memorize timeout. Below are some ways we could address this, in order of decreasing ease.
1. *Set a very low timeout and don't invalidate* Given that on ICDS, a toggle is mostly used for rollout of a feature (as opposed to a SaaS user testing few things and not expecting any bugs), this seems like it's an acceptable tradeoff. WIth a very low timeout such as 10minutes for ICDS env,  in at most 10 minutes, a feature could be fully rolled out. This is what this PR implements.
2. *Mirror cache bust to all worker nodes* Nginx has a mirror option. Using this, when a toggle is edited, we could mirror a specific url such as `clear_feature_toggle_cache` to all nodes instead of just one node. To implement this, we would need to setup a view to handle this and add this to nginx config.
3. *For ICDS, move toggles management to static config managed by devs*. Since toggles are rarely updated on ICDS env, this could be a possibility where we could setup a similar process as update-config.

Thoughts?

@snopoke @emord @calellowitz

### CODE REVIEW

**Comment by snopoke** [comment]
> 1. *Set a very low timeout and don't invalidate* Given that on ICDS, a toggle is mostly used for rollout of a feature (as opposed to a SaaS user testing few things and not expecting any bugs), this seems like it's an acceptable tradeoff. WIth a very low timeout such as 10minutes for ICDS env,  in at most 10 minutes, a feature could be fully rolled out. This is what this PR implements.

The big challenge here is that different workers may have different values at different times. So successive requests from the same user may have different results depending on which worker get's hit. This is why the `locmem` cache is generally only used for the duration of a request.

> 2. *Mirror cache bust to all worker nodes* Nginx has a mirror option. Using this, when a toggle is edited, we could mirror a specific url such as `clear_feature_toggle_cache` to all nodes instead of just one node. To implement this, we would need to setup a view to handle this and add this to nginx config.

This won't work because each VM has multiple workers on it that can serve a request. Since the `locmem` cache is local to the process (not just the VM) each of the worker processes has their own `locmem` cache.

> 3. *For ICDS, move toggles management to static config managed by devs*. Since toggles are rarely updated on ICDS env, this could be a possibility where we could setup a similar process as update-config.

I think this is a good option where we can use it. Note that to get the most benefit from this we need to specify `always_enabled` as well as `always_disabled`.

Another option I've been thinking of is to have a local cache installed on each webworker (and celery + pillow machines). This would be used instead of `locmem` cache and would allow sharing the cache between all processes on the VM. We'd still have the invalidation problem though.

**Comment by emord** [comment]
There are a couple of other options for improving `Toggle` access that I see here. 

Right now `Toggle`s are implemented per feature with a list of users and domains. This means that there is one(ish) request (redis + sometimes couch + write to redis) per toggle if we hit the toggle somewhere in the code paths. This means we can have up to 3 * N db hits per request, though usually just N. A tradeoff that we could make is that there's only 1 or 2 (sometimes 3 or 6) database hits per request.

1. Re-write Toggles as a SQL model. Ignore my previous documents on migrating couch -> sql models because they were optimized for ease of use migration when dealing with annoying code, not future SQL queries. If we had one row per domain or user enabled, then this would be a simple query `Toggle.objects.filter(enabled__in=[domain, username]).all()` and we could cache the result for the user's request. If we're willing to loose all Toggle changes that occur during deploy, then we could do this all in one PR without worrying about having a multiple PR migration of toggles. (I think that this is a reasonable trade off to do for this model, not in general, but don't know how we'll make that decision as a team.)
2. As much as it pains me to say, I think that we should just create a new couch view for toggles. The view would emit a row for user, or domain and the name of the toggle. We would then cache the result of this view, instead of caching the entire `Toggle` doc. This could even be done in a middleware if we wanted the values proactively. In this scenario you would need to coordinate with SaaS to preindex on production because toggles are in the main db and that's still huge because they have couch forms, but I think that this is probably the best ROI for your time.

In either of these scenarios we could have either 1 cache key for the user, domain combination or 2 cache keys, one for domain, one for users. At this time I'm in the camp of having 2 cache keys.

**Comment by sravfeyn** [comment]
Thanks for the comments!

> This won't work because each VM has multiple workers on it that can serve a request. Since the locmem cache is local to the process (not just the VM) each of the worker processes has their own locmem cache.

Ha, didn't think about the multiple gunicorn worker processes, then this is not an easy optin.


> The big challenge here is that different workers may have different values at different times. So successive requests from the same user may have different results depending on which worker get's hit. This is why the locmem cache is generally only used for the duration of a request.

True, also missed this point.

>> 3. For ICDS, move toggles management to static config managed by devs. Since toggles are rarely updated on ICDS env, this could be a possibility where we could setup a similar process as update-config.

> I think this is a good option where we can use it. Note that to get the most benefit from this we need to specify always_enabled as well as always_disabled.

This sounds like the easiest option with biggest ROI. We could turn all ICDS domain toggles into fully static toggles, by setting always_enabled/always_disabled. We can ignore user toggles since they are looked up only for the user requests which are tiny compared to domain level toggles which are lookup for every user instead of few users. I think, even for random toggles, we could use default_randomness to avoid looking up the randomness in DB. 
Additionally, if needed, we could tie always_enabled/always_disabled to localsettings. With that, we could update toggles anytime without waiting for a deploy. 


Emord, just to make sure I didn't misunderstand, the two ideas you mentioned would not affect the number of requests that go to Redis, right? They would reduce the load on couch and would reduce the amount of redis memory to store the toggle related data. My intention was mainly to reduce the number of hits to redis that lookup toggles. These are still good ideas, I can make a backlog ticket with these for latter.

**Comment by snopoke** [comment]
I do like @emord s ideas for the longer term. They would reduce the hits to redis since it would be 2 hits per request with a larger payload (1 for user toggles and 1 for domain toggles) instead of 1 hit per toggle per request.

Invalidation would be harder since we'd need to invalidate ALL the toggle keys in redis but that could be done with cache versioning (bump the version after any toggle save).

In the short term I think enabling disabling them statically in code is a good win.

**Comment by emord** [comment]
> Invalidation would be harder since we'd need to invalidate ALL the toggle keys in redis but that could be done with cache versioning (bump the version after any toggle save).

@snopoke Why would we need to invalidate all the toggle keys?

In the toggle save view, we should have access to both the old and new document. We would then only need to invalidate the keys for those domains or users that were either deleted or added. Figuring that out should just be a set difference. It looks like we're already doing something similar with this confusingly named function that appears to never actually clear the cache: 

https://github.com/dimagi/commcare-hq/blob/12fd8fb2f3a60d66e1b1225456d4d87c9279a9c7/corehq/apps/toggle_ui/views.py#L232-L244

the actual cache busting happens in the toggle save (https://github.com/dimagi/commcare-hq/blob/12fd8fb2f3a60d66e1b1225456d4d87c9279a9c7/corehq/ex-submodules/toggle/models.py#L28) but i don't see a reason we couldn't move it to the other function

**Comment by snopoke** [comment]
@emord you make a good point

**Pull request closed without merging**
