### PR TITLE
Major app manager changes

### PR DESCRIPTION
**Pull request by benrudolph**
@biyeun @orangejenny i think these two changes are huge usability wins

screen shot 2017-06-13 at 10 45 59 pm

fyi: @proteusvacuum buddy: @mkangia

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Review by biyeun — CHANGES_REQUESTED** [review]
hmm  let's think about this. changes the whole modern look and feel.

**Review by proteusvacuum — APPROVED** [review]

**Comment by biyeun** [comment]
Ok I made some changes and am satisfied with this now. Thanks, @benrudolph---and thanks @proteusvacuum for the nudges!

Why I went from light blue to dark --> The light primary color isn't really used as a main highlight anywhere, and I wanted the active background to either match the hover-ed white (original decision, but poor contrast) or match the active bg of the application name (dark blue). I went with the latter for the issues we discussed.

I really, really appreciate that you got to this @benrudolph. I think this was a good kick to wrap up a discussion we originally had with @kaapstorm a while back, but tabled because this didn't seem as urgent. He presented some options to improve contrast and I favored the darker blue. 

My only issue was that this came as a surprise PR out of nowhere with the original title of "Minor Changes" when in fact this is a pretty **major** change in UX (though the code changes are tiny). Involving the design team prior to about-to-be-merged PR phase, or at least putting a flag that this is still up for discussion and not to merge until then, would have been my preferred course of action. My fear is that anyone could have merged this in without a proper discussion about the UX implications, under the assumption that this change is minor.

screen shot 2017-06-14 at 2 47 33 pm
screen shot 2017-06-14 at 2 47 26 pm
screen shot 2017-06-14 at 2 47 12 pm
screen shot 2017-06-14 at 2 47 07 pm
screen shot 2017-06-14 at 2 46 57 pm
screen shot 2017-06-14 at 2 46 54 pm

**Review by biyeun — APPROVED** [review]

**Review by benrudolph — COMMENTED** [review]
Thanks B! This looks fantastic, and I think will be a huge help.

> My only issue was that this came as a surprise PR out of nowhere with the original title of "Minor Changes" when in fact this is a pretty major change in UX (though the code changes are tiny). Involving the design team prior to about-to-be-merged PR phase, or at least putting a flag that this is still up for discussion and not to merge until then, would have been my preferred course of action. My fear is that anyone could have merged this in without a proper discussion about the UX implications, under the assumption that this change is minor.

Fair point. Admittedly the title was a little sly/cute, but I had no intention of merging this before signed off by you or Jenny. Next time I will be sure to be more explicit. As for the impetus, I had been pulling my hair out when trying to work on some app changes. I did bring it up on the #product chat, but quickly got tabled as it had before. I realize there's a lot going on with limited capacity, so I felt like just taking things into my own hands

(can't formally approve this PR cause I opened it, but I approve! ✅ )

**Comment by biyeun** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
