### PR TITLE
Safe operators

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?222936
@NoahCarnahan 

cc @czue 

:fish:

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 9 errors:

* corehq/apps/userreports/operators.py, line 9 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 30 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 6 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 12 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 21 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 24 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 27 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 15 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 18 - E701 multiple statements on one line (colon)

**Comment by NoahCarnahan** [comment]
:+1: on :white_check_mark:

**Comment by gcapalbo** [comment]
build error:
```
File "/mnt/corehq/apps/userreports/indicators/specs.py", line 6, in <module>
from corehq.apps.userreports.operators import IN_MULTISELECT, EQUAL
ImportError: cannot import name IN_MULTISELECT```

**Comment by dimagimon** [comment]
There are 9 errors:

* corehq/apps/userreports/operators.py, line 9 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 30 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 6 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 12 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 21 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 24 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 27 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 15 - E701 multiple statements on one line (colon)
* corehq/apps/userreports/operators.py, line 18 - E701 multiple statements on one line (colon)

**Comment by gcapalbo** [comment]
(failed on a different error now, let me know if you need me to take a look so we get this in today)

**Comment by gcapalbo** [comment]
(restarted build)

**Pull request merged**
