### PR TITLE
Revert "Revert "Add static data source kafka pillow""

### PR DESCRIPTION
**Pull request by benrudolph**
Reverts dimagi/commcare-hq#10679

@czue this is the actual with your changes

### CODE REVIEW

**Comment by czue** [comment]
d'oh, what was the problem with this?

**Comment by czue** [comment]
@benrudolph @NoahCarnahan should be good when :white_check_mark:

**Comment by czue** [comment]
cc @snopoke

**Comment by snopoke** [comment]
Sorry, should have caught that in code review

**Comment by czue** [comment]
heh, I should have caught it when writing it. :disappointed:

**Pull request merged**
