### PR TITLE
Allow floats and other numbers in CaseBlock

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Addresses [#229427](http://manage.dimagi.com/default.asp?229427).
There's no stack trace so I'm not sure exactly what code path is generating the error, but I thin just the exception itself is enough info to fix this. (wait for tests)

@kaapstorm

### CODE REVIEW

**Comment by czue** [comment]
might be nice (and I think easy) to have a test case for this. I think it might be as easy as:
```python
def test():
  # this used to fail
  CaseBlock(create=True, case_id='foo', user_id='bar', update={'float': float(1.2)}).as_xml()
```

**Comment by kaapstorm** [comment]
lgtm. Will wait for test case.

**Comment by NoahCarnahan** [comment]
updated

**Comment by czue** [comment]
nice thanks. gtm on :white_check_mark:

**Pull request merged**
