### PR TITLE
Edit form fix

### PR DESCRIPTION
**Pull request by wpride**
See http://manage.dimagi.com/default.asp?212637

Cross https://github.com/dimagi/touchforms/pull/208
Cross https://github.com/dimagi/javarosa/pull/285

Set the is_editing property to true

### CODE REVIEW

**Comment by czue** [comment]
just to confirm i think you can also delete the now/today overrides, yeah?

**Comment by wpride** [comment]
@czue removed

**Comment by czue** [comment]
:+1: from me whenever QA and jars are ready

**Comment by wpride** [comment]
@dannyroberts can you ping me when you get a chance to discuss this

**Comment by wpride** [comment]
I've been looking into this bug http://manage.dimagi.com/default.asp?223323

The issue is that even when we don't fire the form start and end events, we still load the dates into our FormDef model. When these are turned into Java dates, we're automatically converting them to the system's default time zone (in this case UTC) which means that when they come from mobile submissions in other time zones we're eating that information.

Unfortunately I can't see a great way around this. The options I've considered are:

1. Allow the Java time zone to be overridden. This will allow us to otherwise use the instance loading and processing as usual. Downside is that we'd need HQ to figure out the timezone of the form submission (probably by parsing the instance XML) so HQ could no longer treat that submission as a black box. Would also require some possibly difficult Java overriding since this is just a system call at the moment.

2. HQ could could the timeStart and timeEnd values before handing over the instance to touchforms, then override these values on submission. Downside is this would require some ugly hacking and XML parsing akin to what we had before.

3. Just thought of this, but seems possible that we could change the default set-values to only write once. IE instead of

<setvalue event="xforms-revalidate" ref="/data/meta/timeEnd" value="now()"/>

we have

<setvalue event="xforms-revalidate" ref="/data/meta/timeEnd" value="now()" relevant="count(/data/meta/timeEnd) &gt; 0"/>

Since either way this is a bigger lift than I anticipated want to block on feedback

CC @czue @ctsims @dannyroberts

**Comment by czue** [comment]
I think the last part of your comment didn't make it (or at least I can't see it on github).

Regardless, I think I'm not following the fundamental problem. The timezone information is in the XML, yeah? Doesn't that mean that all you need to do is update the code that turns the XML into the data model to be able to parse timezone aware datetimes? (sorry if this is a dumb comment)

**Comment by czue** [comment]
And to be clear, I think it might be ok if the edit causes the `timeStart` to change timezones as long as the absolute time does not change (I believe that HQ should handle this fine in reports and what not). And then later if we wanted to pass information to touchforms to say "play this form using this timezone" we could do that - I think that's your option 1?

**Comment by wpride** [comment]
@czue "And to be clear, I think it might be ok if the edit causes the timeStart to change timezones as long as the absolute time does not change (I believe that HQ should handle this fine in reports and what not)." spoke with @dannyroberts and he said this was **not** the case (but this is what this PR does at the moment)

**Comment by czue** [comment]
huh, that's surprising to me if the domain is on new timezone handling. I'll let @dannyroberts weigh in.

**Comment by wpride** [comment]
@czue I think the concern was about domains on the old timezone handling

**Comment by czue** [comment]
interesting. not sure it's obviously worth supporting that since presumably it would eventually get fixed when we migrate them. was there a reason we needed to support them specifically?

**Comment by wpride** [comment]
@dannyroberts will need you to weigh in here

**Comment by dannyroberts** [comment]
Yeah @czue it would get fixed when we migrate them, but that's permanently deprioritized for the foreseeable future, and so I wouldn't act like it will definitely ever happen. In the meantime, any domain created before about 1 year ago would be seeing like 5-hour time-shifts whenever they edit forms—and that includes a lot of pretty big still-active domains, so it seems worth getting it right.

Since this is one of those cases where "the right thing" (no reason to have editing the form touch those timestamps in any way) also overlaps with the solution to that particular (pretty common) "edge-case", I'm pretty pro trying to do it that way if it's possible.

@wspride when we talked yesterday I was leaning toward allowing the timezone to be overridden to the original timezone rather than the current system timezone (UTC), but I don't have a strong opinion about it if one of the other ways is easier. I think making vellum change the `@relevant` of the timestamp nodes' bindings relies too much on external stuff to solve a problem that touchforms does theoretically already have all the information to solve internally, so that's my least favorite. If it would make touchforms' life a lot easier to have HQ determine the timezone of the form based on the XML and pass that in, I wouldn't be opposed to it.

**Comment by czue** [comment]
Agree with @dannyroberts on the solution preference order. Also I think it's important that this happens in a general way in touchforms since calculations that depended on the current time should also be handled the same way as `timeStart` and `timeEnd` (which maybe takes option 2 of the table?).

@wpride I think depending on the LOE of option 1 we should just make a judgment call on whether it's worth doing. of all the oddness pre-timezone-fix domains encounter it's possible this is just a drop in the bucket.

**Comment by wpride** [comment]
@czue @dannyroberts I thought about this with a cleared head and realized that of course this issue would already be occurring with edited forms, so this isn't a regression - old timezone domains are already this broken. In addition the current hack is somehow dropping the time zone without factoring this adjustment in to the UTC time. IE:

<n0:timeEnd>2016-04-07T19:40:18.541+05:30</n0:timeEnd>

just becomes:

<n0:timeEnd>2016-04-07T19:40:18.000Z</n0:timeEnd>

So I think this should be merged either way (pending QA) and building an additional workaround for old domains is a different discussion

**Comment by wpride** [comment]
@czue mergable, thanks

**Pull request merged**
