### PR TITLE
Put Redis on db0, and Kafka and ZooKeeper on es0

### PR DESCRIPTION
**Pull request by kaapstorm**
@czue, cc @nickpell

### CODE REVIEW

**Comment by benrudolph** [comment]
i think i've missed a few of these PRs, but have been seeing softlayer referenced a few emails. what is this for? is this what icds is going to be hosted on?

**Comment by czue** [comment]
no it's where we're moving the current india cloud

**Comment by czue** [comment]
(being forced to by cloudant)

**Comment by benrudolph** [comment]
ah gotcha. thanks

**Pull request merged**
