### PR TITLE
add Data Registry UCR processor to `case-pillow`

### PR DESCRIPTION
**Pull request by snopoke**
## Technical Summary
Add a pillow processor to the 'case-pillow' to process data registry UCRs.

An alternative would be to run a separate pillow.

@calellowitz @dannyroberts I don't know if you have a preference for the approach here (separate pillow or part of the case pillow).

### Safety story
Will be testing on staging.

### Automated test coverage
The processor itself has tests but I have not added tests for the case-pillow with data registry UCRs directly.

### QA Plan
I plan to run this on staging for a while before rolling out to prod.

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by snopoke** [comment]
Deployed this to staging today

**Comment by snopoke** [comment]
@dannyroberts I'd appreciate your input on this

**Review by dannyroberts — APPROVED** [review]
This looks good to me. I don't have a strong opinion about same pillow or separate, but it makes sense to start with the simpler option of putting them together, and then splitting it out if that ends up seeming necessary.

I'm not sure I fully understood the prefactor commit, but it looks like you're just extracting a utility function without changing any behavior there, which if you're confident about through sanity checks or tests looks good to me

**Comment by snopoke** [comment]
> I'm not sure I fully understood the prefactor commit, but it looks like you're just extracting a utility function without changing any behavior there, which if you're confident about through sanity checks or tests looks good to me

That's correct. This has also been on staging for a while now.

**Pull request merged**
