### PR TITLE
Update vellum-app-callout-templates.yaml

### PR DESCRIPTION
**Pull request by wpride**
http://manage.dimagi.com/default.asp?184498

Looks like there was a typo or just miscommunication when we setup this YAML file

### CODE REVIEW

**Comment by orangejenny** [comment]
Double checking that this is supposed to be `richard.chard.lu.android.areamapper.LAUNCH` ...`richard.chard` kind of looks like a text editor snafu.

**Comment by wpride** [comment]
@orangejenny it is in fact chard, I do not know why

https://github.com/dimagi/area-mapper/blob/master/app/src/main/AndroidManifest.xml#L3

**Comment by orangejenny** [comment]
weird

**Comment by wpride** [comment]
@orangejenny agreed, an unfortunately I don't think you can change the package without adding a completely new play store listing

**Comment by czue** [comment]
richard leaving his mark

**Pull request merged**
