### PR TITLE
Cache control

### PR DESCRIPTION
**Pull request by calellowitz**
This (mostly) stops browsers from caching hq pages to prevent unauthorized users from viewing sensitive information after logout from browser history. This does not affect static assets, which are served directly from nginx so styles, etc. will still be cached to help performance. Unfortunately, firefox appears to ignore these headers for its in-memory cache and serve directly from that in work offline mode, so for the moment this is only a 95% solution.
@TylerSheffels cc: @gcapalbo

### CODE REVIEW

**Comment by TylerSheffels** [comment]
I am going to put this on staging for a bit. Myself, Sravan and Cal have all read about this and think these headers are the right things to update, but I am always nervous messing with middleware like this.

**Comment by TylerSheffels** [comment]
By that I meant Cal has already put this on staging for a few days.

**Comment by calellowitz** [comment]
@TylerSheffels what is the plan going forward on this work

**Comment by TylerSheffels** [comment]
@czue @dannyroberts I am going to merge this because I believe that the worst case outcome is on clicking back someone would reload the page rather than used a cached copy (but I don't expect even that). Let me know if either of you disagree.

**Comment by czue** [comment]
:+1:

**Pull request merged**
