### PR TITLE
User registration fix

### PR DESCRIPTION
**Pull request by benrudolph**
buddy: @biyeun 
http://manage.dimagi.com/default.asp?179829

### CODE REVIEW

**Comment by orangejenny** [comment]
Looks like it'd be pretty easy to add a test for this page: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/tests/test_views.py

**Comment by benrudolph** [comment]
good point, i'll add one. though i think it probably belongs here: https://github.com/dimagi/commcare-hq/blob/user-reg-fix/corehq/apps/app_manager/tests/test_util.py#L47

**Comment by benrudolph** [comment]
watched test fail on master before putting on this branch

**Comment by czue** [comment]
:+1: when tests pass

**Pull request merged**
