### PR TITLE
remove djcelery dependency

### PR DESCRIPTION
**Pull request by nickpell**
https://github.com/dimagi/commcare-hq/pull/127#issuecomment-251218881

Testing on staging

@czue cc: @emord

### CODE REVIEW

**Review by czue — APPROVED** [review]
good whenever you're happy with QA. @gcapalbo might also be a good person to double check this

**Comment by nickpell** [comment]
on staging:

```
>>> update_exchange_rates.delay()
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-8-bae7226c46ba> in <module>()
----> 1 update_exchange_rates.delay()

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/celery/app/task.pyc in delay(self, *args, **kwargs)
    451 
    452         """
--> 453         return self.apply_async(args, kwargs)
    454 
    455     def apply_async(self, args=None, kwargs=None, task_id=None, producer=None,

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/celery/app/task.pyc in apply_async(self, args, kwargs, task_id, producer, link, link_error, **options)
    557             self.name, args, kwargs, task_id=task_id, producer=producer,
    558             link=link, link_error=link_error, result_cls=self.AsyncResult,
--> 559             **dict(self._get_exec_options(), **options)
    560         )
    561 

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/celery/app/base.pyc in send_task(self, name, args, kwargs, countdown, eta, task_id, producer, connection, router, result_cls, expires, publisher, link, link_error, add_to_parent, reply_to, **options)
    351                 task_id=task_id, expires=expires,
    352                 callbacks=maybe_list(link), errbacks=maybe_list(link_error),
--> 353                 reply_to=reply_to or self.oid, **options
    354             )
    355         result = (result_cls or self.AsyncResult)(task_id)

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/celery/app/amqp.pyc in publish_task(self, task_name, task_args, task_kwargs, countdown, eta, task_id, group_id, taskset_id, expires, exchange, exchange_type, event_dispatcher, retry, retry_policy, queue, now, retries, chord, callbacks, errbacks, routing_key, serializer, delivery_mode, compression, reply_to, time_limit, soft_time_limit, declare, headers, send_before_publish, before_receivers, send_after_publish, after_receivers, send_task_sent, sent_receivers, **kwargs)
    303             correlation_id=task_id,
    304             delivery_mode=delivery_mode, declare=declare,
--> 305             **kwargs
    306         )
    307 

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/messaging.pyc in publish(self, body, routing_key, delivery_mode, mandatory, immediate, priority, content_type, content_encoding, serializer, headers, compression, exchange, retry, retry_policy, declare, expiration, **properties)
    170         return publish(body, priority, content_type,
    171                        content_encoding, headers, properties,
--> 172                        routing_key, mandatory, immediate, exchange, declare)
    173 
    174     def _publish(self, body, priority, content_type, content_encoding,

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/connection.pyc in _ensured(*args, **kwargs)
    455                                            interval_start,
    456                                            interval_step,
--> 457                                            interval_max)
    458                     new_channel = self.channel()
    459                     self.revive(new_channel)

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/connection.pyc in ensure_connection(self, errback, max_retries, interval_start, interval_step, interval_max, callback)
    367         retry_over_time(self.connect, self.recoverable_connection_errors,
    368                         (), {}, on_error, max_retries,
--> 369                         interval_start, interval_step, interval_max, callback)
    370         return self
    371 

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/utils/__init__.pyc in retry_over_time(fun, catch, args, kwargs, errback, max_retries, interval_start, interval_step, interval_max, callback)
    244     for retries in count():
    245         try:
--> 246             return fun(*args, **kwargs)
    247         except catch as exc:
    248             if max_retries and retries >= max_retries:

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/connection.pyc in connect(self)
    235         """Establish connection to server immediately."""
    236         self._closed = False
--> 237         return self.connection
    238 
    239     def channel(self):

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/connection.pyc in connection(self)
    740                 self.declared_entities.clear()
    741                 self._default_channel = None
--> 742                 self._connection = self._establish_connection()
    743                 self._closed = False
    744             return self._connection

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/connection.pyc in _establish_connection(self)
    695     def _establish_connection(self):
    696         self._debug('establishing connection...')
--> 697         conn = self.transport.establish_connection()
    698         self._debug('connection established: %r', conn)
    699         return conn

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.pyc in establish_connection(self)
    114             'heartbeat': conninfo.heartbeat,
    115         }, **conninfo.transport_options or {})
--> 116         conn = self.Connection(**opts)
    117         conn.client = self.client
    118         return conn

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/amqp/connection.pyc in __init__(self, host, userid, password, login_method, login_response, virtual_host, locale, client_properties, ssl, connect_timeout, channel_max, frame_max, heartbeat, on_blocked, on_unblocked, confirm_publish, **kwargs)
    178             self.wait(allowed_methods=[
    179                 (10, 20),  # secure
--> 180                 (10, 30),  # tune
    181             ])
    182 

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/amqp/abstract_channel.pyc in wait(self, allowed_methods)
     65         default value of None means match any method), and dispatch to it."""
     66         method_sig, args, content = self.connection._wait_method(
---> 67             self.channel_id, allowed_methods)
     68 
     69         return self.dispatch_method(method_sig, args, content)

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/amqp/connection.pyc in _wait_method(self, channel_id, allowed_methods)
    238         while 1:
    239             channel, method_sig, args, content = \
--> 240                 self.method_reader.read_method()
    241 
    242             if channel == channel_id and (

/home/cchq/www/staging/current/python_env/local/lib/python2.7/site-packages/amqp/method_framing.pyc in read_method(self)
    187         m = self._quick_get()
    188         if isinstance(m, Exception):
--> 189             raise m
    190         if isinstance(m, tuple) and isinstance(m[1], AMQPError):
    191             raise m[1]

error: [Errno 104] Connection reset by peer
```

**Comment by gcapalbo** [comment]
@nickpell i think celery now supports django natively so we should be good to remove djcelery, though we should figure out the right way to do it and if there's any code we need to update as a result

**Comment by nickpell** [comment]
closing in favor of https://github.com/dimagi/commcare-hq/pull/13563

**Pull request closed without merging**
