### PR TITLE
Fetch data for current month only for AWC report- Lact women tab

### PR DESCRIPTION
**Pull request by Rohit25negi**
Fixes this: https://dimagi-dev.atlassian.net/browse/ICDS-732

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
I don't think this is going to work. Specifically on the first of the month, it won't pull any data because the current month table will be empty. This might be confusion over what that relativedelta statement does (it sets the day value of the date to 1). I think what you actually want is to subtract a day (using `days=1` instead of `day=1`, i know this library is very confusing). And then use the first of that month to determine your query, either with a second dateutil statement or just using `date.replace`

**Comment by Rohit25negi** [comment]
Im that case. Should not that be subtracting 2 days because for first two
days on dashboard we show data of previous month not just for 1.

**Comment by calellowitz** [comment]
No, as per the current spec we want this report to show the most current data possible, its not a monthly report like the others. It is meant to be live. It is worth asking Sarvesh if that is preferable behavior, and we can change the report at a later date if necessary but for the second, we want data from the first. Specifically, that is because it is meant to be a list of women who are currently lactating, and that changes each day.

**Comment by Rohit25negi** [comment]
I see. I did not know that. Cool will make that change in about  an hour.
Only concern I still have is people to again raise same query by comparing
this report with other parts of dashboard and finding it inconsistent on
2nd of month, which is how nitish caught this as inconsistency. But yeah
thia could have been supported by argument what u gave. But as u said, its
worth talking to sarvesh. I will be taking this chat with Sarvesh tomorrow.
Will keep you updated.

**Comment by calellowitz** [comment]
There should not be too much confusion, because any reports like the one Nitish saw will be downloaded for June, so the person will know they are downloading previous months. Whereas this report, like the daily attendance and other awc ones will be

**Comment by calellowitz** [comment]
Sorry, didnt mean to close that

**Review by calellowitz — APPROVED** [review]
should get rid of the print statement, otherwise looks good, although the subclassing of date and datetime (which i realize you did not start) is a little confusing

**Pull request merged**
