### PR TITLE
Use sync-request/post/@relevant to check casedb before claiming case

### PR DESCRIPTION
**Pull request by kaapstorm**
Something like this, @phillipm, @proteusvacuum? 

cc @NoahCarnahan 

(:construction_worker: :gun: Tests will fail.)

### CODE REVIEW

**Comment by kaapstorm** [comment]
This change produces this in `suite.xml`:
```xml
  <sync-request>
    <post url="http://10.0.0.11/a/nhproject/phone/claim-case/" relevant="count(instance('casedb')/casedb/case[@case_id=instance('querysession')/session/data/case_id]) = 0">
      <data ref="instance('querysession')/session/data/case_id" key="case_id"/>
    </post>
    <!-- ... -->
  </sync-request>
```

**Comment by kaapstorm** [comment]
This change is for the HQ component of [this PR][1] on mobile. It prevents sending a case claim request if the case being claimed is already owned by the user.

It opens the possibility of preventing case claims in other situations too. @dimagi/product, @sheelio, @orangejenny, can you think of use cases where we might want to restrict which cases a user can claim (other than just case type -- we've got that covered)? And if so, how do you think we should present that option in the UI? 

  [1]: https://github.com/dimagi/commcare/pull/302

**Comment by proteusvacuum** [comment]
@kaapstorm that seems good to me.

**Comment by kaapstorm** [comment]
I'll fix the tests and add one for this.

**Comment by kaapstorm** [comment]
:heavy_check_mark:

**Pull request merged**
