### PR TITLE
correct mapping

### PR DESCRIPTION
**Pull request by mkangia**
Small misconfiguration in https://github.com/dimagi/commcare-hq/pull/26791/files#diff-2289dca64bccf8fc007e2a45f4285cc7R142-R143

### CODE REVIEW

**Comment by mkangia** [comment]
@orangejenny is there a reason for not doing something like
`SpecClass.type: SpecClass`
to avoid such mixup?

**Review by Rohit25negi — APPROVED** [review]
Looks good. 
As you suggested good to have it something like, 

```
spec_classesList = [AdultFemaleMigrantDeathSpec, AdultFemaleResidentDeathSpec . . .]

spec_map = {cls.type: cls for cls in spec_classesList}

```

**Comment by mkangia** [comment]
Thanks @Rohit25negi , said the same thing earlier. Will wait for Jenny to confirm

**Comment by orangejenny** [comment]
thank you! you are a champ 🥇

**Pull request merged**
