### PR TITLE
add and test get_all_doc_ids_for_domain_grouped_by_db

### PR DESCRIPTION
**Pull request by dannyroberts**
use in Domain.delete

cherry-picked from original:
https://github.com/dimagi/commcare-hq/commit/400d3878afc5e9f5118ffb30d22b8cebe9afb4a6

to acheive the same effect without a reindex

### CODE REVIEW

**Comment by czue** [comment]
@snopoke probably best to review

**Comment by dannyroberts** [comment]
Realized my PR comments haven't given that much context. The impetus for this PR is so that deleting a domain continues to delete its users, groups, etc. after (and before) the migration.

**Comment by benrudolph** [comment]
this looks good to me. i'm pretty sure this functionality is only really used in a mgmt command and pretty rarely. gonna go ahead an merge

**Comment by benrudolph** [comment]
(take that back)

**Pull request merged**
