### PR TITLE
[ICDS Dashbaord] kpi pmo api aggregation changes changes

### PR DESCRIPTION
**Pull request by challabeehyv**
https://app.asana.com/0/1112385193248823/1167712643236679/f

##### SUMMARY
Allowed cbe_conducted, vhnd_conducted to be aggregated for all levels

##### FEATURE FLAG
No

### CODE REVIEW

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
could you fix the test cases as well.

**Comment by challabeehyv** [comment]
> could you fix the test cases as well.

done. please check

**Review by Rohit25negi — APPROVED** [review]
Looks good to me. Gtg once the test cases passes.

**Comment by challabeehyv** [comment]
> Looks good to me. Gtg once the test cases passes.

all the jobs passed in the build. But it is still showing in progress. Not sure what is going on here

**Comment by Rohit25negi** [comment]
Weird, I would wait for a couple of minute.

**Comment by challabeehyv** [comment]
> Weird, I would wait for a couple of minute.

its been there for quite some time

**Pull request merged**
