### PR TITLE
ICDS: Add Migrated Indicator to Person Cases

### PR DESCRIPTION
**Pull request by sheelio**
@calellowitz @emord 

This is coming out of this ticket: https://manage.dimagi.com/default.asp?263566

Once rebuilt, we need to update the aggregation functions to reference the not_migrated column

### CODE REVIEW

**Comment by emord** [comment]
@sheelio sorry about that. I was confused with the interaction between resident/migrant.

Is there anything we can do to filter cases that need to be rebuilt? It take a really long time to go through 40 million cases

**Comment by sheelio** [comment]
I've added a new indicator to the person cases v3 (so I think it needs a rebuild unless we copy in data from v2?).  

I looked at the indicators in that table and I don't think there is an easy way to filter the set.  You could use seeking_services = 1, but I think that would most of the cases in this table anyway?

**Comment by sheelio** [comment]
@emord 
Can you avoid rebuilds if you're adding boolean indicators to the UCR?

**Comment by sheelio** [comment]
@emord 

Just tested and adding a boolean indicator triggered a rebuild of the table.

**Comment by sheelio** [comment]
@emord 

Updated this PR to use a nullable column instead (same underlying database change).

**Comment by emord** [comment]
failure looks real

**Comment by sheelio** [comment]
@emord 

Tests are fixed.  However, I just tested adding a nullable integer column to a data source and it seems to wipe it

**Comment by emord** [comment]
@sheelio How did you test

I did the following:

1) Remove the table

```
commcarehq=# select doc_id, inserted_at, owner_id, awc_id from "config_report_icds-cas_static-person_cases_v2_b4b5d57a";
ERROR:  relation "config_report_icds-cas_static-person_cases_v2_b4b5d57a" does not exist
LINE 1: select doc_id, inserted_at, owner_id, awc_id from "config_re...
```

2) Start the pillow

```
commcarehq=# select doc_id, inserted_at, owner_id, awc_id from "config_report_icds-cas_static-person_cases_v2_b4b5d57a";
 doc_id | inserted_at | owner_id | awc_id 
--------+-------------+----------+--------
(0 rows)
```

3) Add a row

```
commcarehq=# insert into "config_report_icds-cas_static-person_cases_v2_b4b5d57a" (doc_id, inserted_at, owner_id, awc_id) VALUES ('doc_id', now(), 'owner_id', 'awc_id');
INSERT 0 1
commcarehq=# select doc_id, inserted_at, owner_id, awc_id from "config_report_icds-cas_static-person_cases_v2_b4b5d57a";
 doc_id |        inserted_at         | owner_id | awc_id 
--------+----------------------------+----------+--------
 doc_id | 2017-10-26 19:29:56.639131 | owner_id | awc_id
(1 row)

commcarehq=# select doc_id, not_migrated, inserted_at, owner_id, awc_id from "config_report_icds-cas_static-person_cases_v2_b4b5d57a";
ERROR:  column "not_migrated" does not exist
LINE 1: select doc_id, not_migrated, inserted_at, owner_id, awc_id f...
                       ^
```
(note not_migrated column does not exist)

4) checkout your branch and run the pillow

```
commcarehq=# select doc_id, not_migrated, inserted_at, owner_id, awc_id from "config_report_icds-cas_static-person_cases_v2_b4b5d57a";
 doc_id | not_migrated |        inserted_at         | owner_id | awc_id 
--------+--------------+----------------------------+----------+--------
 doc_id |              | 2017-10-26 19:29:56.639131 | owner_id | awc_id
(1 row)

```
Row is still in the table and not_migrated exists as a column

**Comment by sheelio** [comment]
Interesting - I created a non-static data source and built it.  I then added a new nullable indicator to that data source and I could no longer access it (preview didn't work) until I rebuilt it.  Is there a different path for static data sources vs. non-static data sources?

**Pull request merged**
