### PR TITLE
Add unicode names test

### PR DESCRIPTION
**Pull request by proteusvacuum**
@snopoke, here's a failing test. 
More context in the ticket: http://manage.dimagi.com/default.asp?226582#1145687

FYI @czue

### CODE REVIEW

**Comment by snopoke** [comment]
I can look into this on Monday. First thing that comes to mind is 'how does django do it?'

**Comment by snopoke** [comment]
Django does it's own quoting etc. which I guess isn't surprising since it has to deal with lots of different DB's.

Did some reading and code diving and realized we're returning an [ISQLQuote](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.ISQLQuote) object and could implement our own.

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by czue** [comment]
wow, nice research and solution. saw this still has a don't merge on it (guessing accidental) so feel free to remove/merge when ready

**Comment by proteusvacuum** [comment]
Nice!!

**Comment by proteusvacuum** [comment]
Thanks for figuring this out.

**Comment by snopoke** [comment]
👍 was quite a fun one

**Comment by benrudolph** [comment]
nice 🐻

**Pull request merged**
