### PR TITLE
Fix broken case tiles

### PR DESCRIPTION
**Pull request by wpride**
Looks like case tiles were broken, but not clear when. This PR fixes one incorrect boolean, but the main issue is this line in the polyfill:

https://github.com/FremyCompany/css-grid-polyfill/blob/master/bin/css-polyfills.js#L6535

The issue appears to be that the document.body is not defined by the time the polyfill runs. This causes the javascript not to run and the tiles not to be formatted. Removing this line causes the JS to work correctly. I'm not sure if this was introduced by changing the layout of our HTML or what. Might be good to pair on.

@benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
interesting, i noticed that as well when fooling around with the case tiles. could you surround this line in a document.ready statement? https://github.com/dimagi/commcare-hq/blob/br/error-msg-on-formplayer-down/corehq/apps/cloudcare/templates/cloudcare/formplayer_home.html#L63. this way we don't execute anything until the dom is ready
```
$(function() {
  ....
});
```

**Comment by benrudolph** [comment]
https://api.jquery.com/ready/

**Comment by wpride** [comment]
Doesn't seem to be fixing it either

**Comment by benrudolph** [comment]
merging this for now, as we tackle the other issue separately

**Pull request merged**
