### PR TITLE
Drop blobs_blobmeta view

### PR DESCRIPTION
**Pull request by millerdev**
The view is no longer needed since all data has bee migrated out of `form_processor_xformattachmentsql`. It's also messing up query plans for the riak to s3 migration, which is making it run slower than it should.

@dannyroberts

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
Looks good to me as long as you're sure nothing's relying on it!

**Review by dannyroberts — APPROVED** [review]

**Comment by millerdev** [comment]
✅

**Comment by millerdev** [comment]
Realized while laying in bed tonight that, while all enterprise and production envs have been migrated, there are probably a bunch of developers with dev environments that have not been migrated and this would negatively affect them. I'll make another PR to handle that situation first.

**Comment by millerdev** [comment]
https://github.com/dimagi/commcare-hq/pull/22887 should be merged first, and I will be making some other changes here before this can be merged.

**Comment by millerdev** [comment]
Updated

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
