### PR TITLE
hotfix the migration checkpoint changes

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by czue** [comment]
@kkrampa does this look right?

**Comment by kkrampa** [comment]
I think that this doesn't work for initial migration. For initial migration we need to start from scratch so date should be set to None but now is setting to today date.

**Comment by kkrampa** [comment]
Also I think that after your changes we are starting always from today's date not from last success.

**Comment by czue** [comment]
@kkrampa thanks - I think i'm confused about how this works. is the issue that the migration functions modify the `date` and `start_date` of the checkpoint as they're running?

maybe the easiest thing to do is revert https://github.com/dimagi/commcare-hq/commit/ba7a6fa94edb26fba8bdeba022018f0d15d8f167?

**Comment by kkrampa** [comment]
@czue I think revert is easiest way and then I can look on  https://github.com/dimagi/commcare-hq/commit/ba7a6fa94edb26fba8bdeba022018f0d15d8f167 and modify it if it's ok for you.

I agree that this date stuff is a little bit confusing. I will try to refactor this a little bit.

**Pull request closed without merging**
