### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by gcapalbo**

### CODE REVIEW

**Comment by gcapalbo** [comment]
@NoahCarnahan @snopoke @czue 
this fixes the build. the build errors that were happening seemed to be happening because we were making writes in couch that then were not available during subsequent reads. i'm guessing it broke with [this](https://github.com/klaemo/docker-couchdb/commit/5382c3bffef47e5b54a0b9e7d2b3c9952ca21ded)

this makes it so that we pin to the latest stable version rather than always pull the latest

**Comment by czue** [comment]
wow, nice find. pretty weird that couch 2.0 fails with that workflow

**Comment by snopoke** [comment]
Also strange because docker hub says `latest` is `1.6.1` unless I'm misreading it.

**Comment by gcapalbo** [comment]
@snopoke yes, that threw me off too, but when i looked [here](https://hub.docker.com/r/klaemo/couchdb/tags/) i realized `latest` could not be pointing to `1.6.1` and seemed like it was pointing to the newly-updated `2.0-rc4`

**Comment by snopoke** [comment]
Ha, well spotted. Guessing they pushed it to latest accidentally.

**Pull request merged**
