### PR TITLE
[User History] filter by bulk upload

### PR DESCRIPTION
**Pull request by mkangia**
## Summary

Feedback on https://github.com/dimagi/commcare-hq/pull/29909 was to be able to filter by a specific user upload.
This PR, adds that ability to the report.
Assumed here that it is okay to show options to select from all bulk uploads done for the domain and not need to filter to those only done by accessible users, since that is handled eventually in the report when showing user history.
Open to review if that should be reconsidered.

## Feature Flag

`USER_HISTORY_REPORT`

## Product Description

Screenshot from 2021-07-06 14-35-29

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Safety story

Tested locally that this works okay. Did a couple of imports and then used reports to filter for changes in each.

### Rollback instructions

Same as base PR

### CODE REVIEW

**Comment by snopoke** [comment]
> Assumed here that it is okay to show options to select from all bulk uploads done for the domain and not need to filter to those only done by accessible users, since that is handled eventually in the report when showing user history.

Seems OK but I don't see anywhere in the report where filtering is happening based on the current users' access.

**Review by snopoke — APPROVED** [review]

**Comment by mkangia** [comment]
Hey @snopoke 

> Seems OK but I don't see anywhere in the report where filtering is happening based on the current users' access.

the report fetches the user ids based on slug using

https://github.com/dimagi/commcare-hq/pull/29909/files#diff-97674072217e37379be148b9fdf743f686c009d5d9741d8ca3607fa16a4d526fR79

which should return ids for accessible users only.

**Comment by mkangia** [comment]
Hey @snopoke 
Just following up on your query on this PR. resolved?

**Comment by snopoke** [comment]
> Hey @snopoke
> 
> > Seems OK but I don't see anywhere in the report where filtering is happening based on the current users' access.
> 
> the report fetches the user ids based on slug using
> 
> https://github.com/dimagi/commcare-hq/pull/29909/files#diff-97674072217e37379be148b9fdf743f686c009d5d9741d8ca3607fa16a4d526fR79
> 
> which should return ids for accessible users only.

I'm not fully convinced, especially since this `return` statement seems to skip all access based filtering: https://github.com/dimagi/commcare-hq/blob/efaba52b4c64a20778af41774f80e8ff471307c3/corehq/apps/reports/filters/users.py#L349

But fine to declare that out of scope of this PR.

**Comment by mkangia** [comment]
Thanks @snopoke 

I believe that is the default behavior even on Submit History and other reports that use EMWF.
https://github.com/dimagi/commcare-hq/blob/80b7b34424f07fc9afc73f6c0e242861cbc0d83d/corehq/apps/reports/standard/inspect.py#L106

Would that mean we show all forms if no users are selected?

**Comment by snopoke** [comment]
> Would that mean we show all forms if no users are selected?

Seems like it might - would need some testing.

**Comment by mkangia** [comment]
Followed up on the filter, a ticket has been added, https://dimagi-dev.atlassian.net/browse/SUPPORT-10069.

**Comment by mkangia** [comment]
https://github.com/dimagi/commcare-hq/pull/30010#issuecomment-876284549

Getting fixed in https://github.com/dimagi/commcare-hq/pull/30033

**Pull request merged**
