### PR TITLE
remove the pathfinder app and couch views

### PR DESCRIPTION
**Pull request by czue**
this project has been dead for 6 months and they don't even have access to these on their subscription.

we can always add it back if they come back online (and maybe rewrite the reports in UCR or something while we're at it)

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
+0 −1,044 :smiling_imp:

**Comment by czue** [comment]
@emord or whoever

**Comment by esoergel** [comment]
:boom: :hammer:

**Comment by dannyroberts** [comment]
I know I'm late to the party, but :tada: :balloon: awesome!

**Pull request merged**
