### PR TITLE
fix case data page timezone

### PR DESCRIPTION
**Pull request by dannyroberts**
- refactor _to_html and how it's called from get_display_data
- replace is_utc with is_phone_time in case details spec
  - TIMEZONE_DATA_MIGRATION_COMPLETE constant is now entirely contained
    in the timezones util
- fix timezone processing within get_display_data

### CODE REVIEW

**Comment by czue** [comment]
looks good when tests pass

**Comment by dannyroberts** [comment]
I think this will fix http://manage.dimagi.com/default.asp?163282

**Comment by dannyroberts** [comment]
@czue / @nickpell up to you whether to wait for build, but i think this will fix a live bug (and this code isn't particularly well tested I don't think)

**Comment by nickpell** [comment]
@dannyroberts Builds have been *very* slow to start, so down to do it live

**Pull request merged**
