### PR TITLE
Removed stock status map report

### PR DESCRIPTION
**Pull request by orangejenny**
## Product Description
As discussed on slack, this report has very little usage, probably because the map tiles have been returning 410s since [around 2020](https://stackoverflow.com/questions/64073635/blank-map-tiles-error-410-gone-mapbox-leaflet-js).

## Feature Flag
CommCare supply

### Safety story
Removal of dead code, in a flagged feature. I tested on staging that map-based UCRs still work correctly. Map-based UCRs are the reason I couldn't remove much of the maps-related javascript.

### Automated test coverage

Unlikely

### QA Plan

Not requesting QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
:medal_sports: I love it when we can remove dependencies.

I assume since you said "this report has very little usage" that there is some usage? If so, do we need to let people who are using it know that it's going away? Is that even possible?

**Comment by orangejenny** [comment]
@millerdev We do have the URLs that have been accessed, so that gives us a list of domains who have tried to use it. I think it having been broken makes that message a little awkward, but I'm happy to ask support/product if you think it'd be valuable to do so.

**Review by snopoke — APPROVED** [review]

**Comment by orangejenny** [comment]
Spoke with product, holding off on merge while they investigate current (attempted) usage of this feature.

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
Product investigation went way faster than I had expected. Merging!

**Pull request merged**
