### PR TITLE
Remove pickle serializer from messaging tasks

### PR DESCRIPTION
**Pull request by emord**
Saw this while looking at the file for other reasons. These arguments are all text/ids, so I think these should all be safe to switch to deafult json

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Review by nickpell — COMMENTED** [review]
FYI I think existing tasks in the queue will error with this approach.  When celery reboots it will expect to find json, and instead find the pickled version of strings (which is different from the strings themselves).

**Comment by emord** [comment]
@nickpell I thought that's what `CELERY_ACCEPT_CONTENT` was for https://github.com/dimagi/commcare-hq/blob/68e84461a2a227d878542962330652848a0388c4/settings.py#L541

I thought it would accept both pickle and json, but only produce json going forward. Have I misunderstood that setting?

**Comment by nickpell** [comment]
I believe that setting is a whitelist of permitted serializers, not a list of serializers to try until one works.  But I'd be happy to be proven wrong.

https://docs.celeryproject.org/en/latest/userguide/configuration.html#accept-content

**Comment by emord** [comment]
Thanks. I don't think that I'm going to be able to test this to a very confident degree soon, so going to close it.

**Pull request closed without merging**
