### PR TITLE
Replace casegroups_groups/by_domain

### PR DESCRIPTION
**Pull request by nickpell**
@dannyroberts cc: @NoahCarnahan 

Currently on prod no domain has more than 15 case groups.  Not sure how the number of case groups is expected to scale for larger projects.

An additional optimization would be to use actual pagination/counting at the db level.

### CODE REVIEW

**Comment by nickpell** [comment]
:white_check_mark:

**Comment by dannyroberts** [comment]
As a bonus, since this is the only view in `_design/casegroups`, we can delete the view without any reindexing overhead! I think you should go ahead and do that if you agree, and then I'll merge this in.

Agree for now that optimizing pagination and counting of a max of 15 documents at a time doesn't justify an extra couch view, and doing those things in python memory is totally fine.

**Comment by nickpell** [comment]
:white_check_mark:

**Comment by dannyroberts** [comment]
Nice! One more view down :boom:

**Comment by czue** [comment]
:boom: :tada: :racehorse:

**Pull request merged**
