### PR TITLE
add statsd host

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke this'll add the statsd host to collect metrics. looks like dogstatsd by default runs on port 8125. if that seems wrong to you let me know. i think i'll load this up on staging first (even though we can `rollback` service changes now :open_mouth:)

### CODE REVIEW

**Comment by snopoke** [comment]
sweet!

**Comment by gcapalbo** [comment]
@benrudolph fyi, had to update the command string

**Comment by benrudolph** [comment]
Thanks gio, weird I copied it from the docs. Must've looked at a wrong
version or something

**Comment by benrudolph** [comment]
seems to work on staging, removing label

**Comment by snopoke** [comment]
:book:

**Pull request merged**
