### PR TITLE
Update to redis 7 in compose files

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Product Description

https://dimagi-dev.atlassian.net/browse/SAAS-14372

Updates the docker container for redis to version 7 to run tests against it.

### Safety story

Only affects tests and dev setup. Changes tested locally.
### Automated test coverage
NA

### QA Plan

NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by shyamkumarlchauhan — APPROVED** [review]

**Review by millerdev — DISMISSED** [review]

**Comment by millerdev** [comment]
If this change is merged, is the Redis on-disk data format forward-compatible, or will it require migration steps to preserve local state?

**Review by joxl — APPROVED** [review]

**Comment by AmitPhulera** [comment]
I have tested it on my local environment and things went smoothly. I briefly skimmed through the [changelog](https://github.com/redis/redis/blob/7.0/00-RELEASENOTES#L589) and did not find anything that we should be cautious about.

They mentioned one thing which I guess we can ignore as we would not be rolling back to the previous version again.

> Redis 7 uses a new version 10 format for RDB files, which is incompatible
   with older versions

@millerdev Do you suggest any other steps that we can take inorder to test it?

**Comment by millerdev** [comment]
Sounds good if you have confirmed that upgrading to a newer version of Redis does not cause problems (errors, loss of existing Redis data, etc.) for people who have been using the previous version.

If you need to test, how about a workflow like this?
- start the old version of Redis
- add a key/value pair using the Django cache framework
- upgrade to the new version
- verify that the key/value pair still exists

**Comment by AmitPhulera** [comment]
Thanks, @millerdev for the inputs. I have verified on the local system that the `dump.rdb`  is read correctly by Redis 7 and the keys created in Redis 6.x exist in version 7 after updating the container.

**Review by millerdev — APPROVED** [review]

**Comment by AmitPhulera** [comment]
This has been rolled out on prod. Merging it now.

**Pull request merged**
