### PR TITLE
Add indexes to awc_id

### PR DESCRIPTION
**Pull request by emord**
https://docs.google.com/document/d/1dp_QXUvE6V9UKsgDrpBNXvVnDxQJDltCUJcPvlqE1SA/edit

@snopoke @benrudolph you guys had an [UNCLEAR] before one of the indexes so I didn't add it here. I think this was just based on the mobile ucrs? it's probable that adding indexes all of the ids (block_id, district_id, supervisor_id etc) would help the web based ones

@sheelio

### CODE REVIEW

**Comment by benrudolph** [comment]
nice thanks for doing this. simon also had some ideas about combined indexes that would help. the `[UNCLEAR]` was because i attempted to first make that index concurrently and i eventually killed it. however when i went to recreate non concurrently, it said it already existed. i should've just deleted and recreated.. anyways, long story short, we should create an index for that column.

**Review by benrudolph — APPROVED** [review]

**Comment by snopoke** [comment]
2 things:
* before this get's merged we should rename the indexes we created to match the naming schema here
* would be good to get input from @sheelio since we only looked at reports being used by the AWW App.

**Comment by sheelio** [comment]
I think Jon has added all the ones I would suggest (indexes on supervisor_id as well, and on month for the monthly tables).

**Review by snopoke — APPROVED** [review]

**Comment by emord** [comment]
Merging so this gets in before an ICDS deploy @sheelio

**Pull request merged**
