### PR TITLE
Fix redis cache deserialization on Python 3

### PR DESCRIPTION
**Pull request by millerdev**
Fix for the issue described in https://github.com/dimagi/commcare-hq/pull/24267

@nickpell

### CODE REVIEW

**Comment by nickpell** [comment]
@millerdev I get the following new error when testing this example: https://github.com/dimagi/commcare-hq/pull/24267#issuecomment-491322571

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/nick/py3/lib/python3.6/site-packages/django_redis/client/default.py in decode(self, value)
    311         try:
--> 312             value = int(value)
    313         except (ValueError, TypeError):

ValueError: invalid literal for int() with base 10: b'\x80\x02cdjango.db.models.base\nmodel_unpickle\nq\x01X\n\x00\x00\x00accountingq\x02U\x0cSubscriptionq\x03\x86\x85Rq\x04}q\x05(U\x14do_not_email_invoiceq\x06\x89U\rsubscriber_idq\x07K\x01U\x08date_en

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-1799415d2a58> in <module>()
----> 1 Subscription.get_active_subscription_by_domain('example')

/Users/nick/Desktop/commcare-hq/corehq/apps/accounting/models.py in get_active_subscription_by_domain(cls, domain_name_or_obj)
   1713         if isinstance(domain_name_or_obj, Domain):
   1714             return cls._get_active_subscription_by_domain(domain_name_or_obj.name)
-> 1715         return cls._get_active_subscription_by_domain(domain_name_or_obj)
   1716 
   1717     @classmethod

/Users/nick/py3/lib/python3.6/site-packages/quickcache/quickcache.py in inner(*args, **kwargs)
     40             @functools.wraps(fn)
     41             def inner(*args, **kwargs):
---> 42                 return helper(*args, **kwargs)
     43 
     44             inner.clear = helper.clear

/Users/nick/py3/lib/python3.6/site-packages/quickcache/quickcache_helper.py in __call__(self, *args, **kwargs)
    177     def __call__(self, *args, **kwargs):
    178         if not self.skip(*args, **kwargs):
--> 179             return self.call(*args, **kwargs)
    180         else:
    181             content = self.fn(*args, **kwargs)

/Users/nick/py3/lib/python3.6/site-packages/quickcache/quickcache_helper.py in call(self, *args, **kwargs)
     69         key = self.get_cache_key(*args, **kwargs)
     70         logger.debug(key)
---> 71         content = self.cache.get(key, default=Ellipsis)
     72         if content is Ellipsis:
     73             logger.debug('cache miss, calling {}'.format(self.fn.__name__))

/Users/nick/py3/lib/python3.6/site-packages/quickcache/cache_helpers.py in get(self, key, default)
     66         missed = []
     67         for cache in self.caches:
---> 68             content = cache.get(key, default=Ellipsis)
     69             if content is not Ellipsis:
     70                 for missed_cache in missed:

/Users/nick/py3/lib/python3.6/site-packages/quickcache/cache_helpers.py in get(self, key, default)
     25     def get(self, key, default=None):
     26         try:
---> 27             return self.cache.get(self.prefixed_key(key), default=default)
     28         except ForceSkipCache:
     29             return default

/Users/nick/py3/lib/python3.6/site-packages/django_redis/cache.py in _decorator(self, *args, **kwargs)
     30     def _decorator(self, *args, **kwargs):
     31         try:
---> 32             return method(self, *args, **kwargs)
     33         except ConnectionInterrupted as e:
     34             if self._ignore_exceptions:

/Users/nick/py3/lib/python3.6/site-packages/django_redis/cache.py in get(self, key, default, version, client)
     79         try:
     80             return self.client.get(key, default=default, version=version,
---> 81                                    client=client)
     82         except ConnectionInterrupted as e:
     83             if self._ignore_exceptions:

/Users/nick/py3/lib/python3.6/site-packages/django_redis/client/default.py in get(self, key, default, version, client)
    208             return default
    209 
--> 210         return self.decode(value)
    211 
    212     def persist(self, key, version=None, client=None):

/Users/nick/py3/lib/python3.6/site-packages/django_redis/client/default.py in decode(self, value)
    317                 # Handle little values, chosen to be not compressed
    318                 pass
--> 319             value = self._serializer.loads(value)
    320         return value
    321 

/Users/nick/Desktop/commcare-hq/corehq/util/python_compatibility.py in loads(self, value)
     32 
     33     def loads(self, value):
---> 34         return pickle.loads(value, encoding="latin1", fix_imports=True)

TypeError: an integer is required (got type str)
```

The value stored in the cache is:
```
b'\x80\x02cdjango.db.models.base\nmodel_unpickle\nq\x01X\n\x00\x00\x00accountingq\x02U\x0cSubscriptionq\x03\x86\x85Rq\x04}q\x05(U\x14do_not_email_invoiceq\x06\x89U\rsubscriber_idq\x07K\x01U\x08date_endq\x08NU\x15auto_generate_creditsq\t\x89U\x06_stateq\ncdjango.db.models.base\nModelState\nq\x0b)\x81q\x0c}q\r(U\x06addingq\x0e\x89U\x02dbq\x0fX\x07\x00\x00\x00defaultq\x10ubU\x0efunding_sourceq\x11X\x06\x00\x00\x00CLIENTU\x02idq\x12K\rU\x0edo_not_invoiceq\x13\x88U\x13skip_auto_downgradeq\x14\x89U\x11no_invoice_reasonq\x15X\x00\x00\x00\x00U\ndate_startq\x16cdatetime\ndate\nq\x17U\x04\x07\xe3\x03\x19\x85Rq\x18U\x16salesforce_contract_idq\x19X\x00\x00\x00\x00U\x1askip_auto_downgrade_reasonq\x1aX\x00\x00\x00\x00U\x0cservice_typeq\x1bX\x07\x00\x00\x00PRODUCTU\x10is_hidden_to_opsq\x1c\x89U\x13_plan_version_cacheq\x1dh\x01X\n\x00\x00\x00accountingq\x1eU\x13SoftwarePlanVersionq\x1f\x86\x85Rq }q!(U\x0fproduct_rate_idq"K\x0bU\x0b_role_cacheq#h\x01X\x0c\x00\x00\x00django_prbacq$U\x04Roleq%\x86\x85Rq&}q\'(U\x0bdescriptionq(X\x00\x00\x00\x00U\nparametersq)c__builtin__\nset\nq*]\x85Rq+U\x0f_django_versionq,U\x071.11.20h\nh\x0b)\x81q-}q.(h\x0e\x89h\x0fh\x10ubU\x04slugq/X\x10\x00\x00\x00standard_plan_v0h\x12K&U\x04nameq0X\r\x00\x00\x00Standard PlanubU\x07plan_idq1K\nh,U\x071.11.20h\nh\x0b)\x81q2}q3(h\x0e\x89h\x0fh\x10ubU\tis_activeq4\x88U\x07role_idq5K&U\rlast_modifiedq6cdatetime\ndatetime\nq7U\n\x07\xe2\n\x17\x01"\x07\t^\xdb\x85Rq8U\x0cdate_createdq9h7U\n\x07\xe2\n\x17\x01"\x07\t9\xa8\x85Rq:h\x12K\x0bubU\naccount_idq;K\x04h4\x88U$skip_invoicing_if_no_feature_chargesq<\x89U\x0fpro_bono_statusq=X\n\x00\x00\x00FULL_PRICEh6h7U\n\x07\xe3\x03\x19\x15\x1a\x0e\x02\xf1\x9e\x85Rq>h,U\x071.11.20U\x0fplan_version_idq?K\x0bU\x15do_not_email_reminderq@\x89U\x08is_trialqA\x89h9h7U\n\x07\xe3\x03\x19\x15\x1a\x0e\x02\xf1\x00\x85RqBub.'
```

**Comment by millerdev** [comment]
@nickpell I am unable to replicate your failure, so I updated the test to load that pickle. It passes for me locally. I'm running Python 3.7.2

Does this pass for you? If not, what version of Python are you running?
```
./manage.py test corehq.util.tests.test_python_compatibility
```

**Comment by nickpell** [comment]
The test fails for me when running 3.6.7

**Comment by millerdev** [comment]
Looks like you need to update to Python 3.7

**Comment by nickpell** [comment]
Hmm ... I'm targeting Python 3.6.7 because that's the default on Bionic.  Would the issue be resolved in Python 3.6.8?

**Comment by millerdev** [comment]
> Would the issue be resolved in Python 3.6.8?

Maybe? [This bug](https://bugs.python.org/issue22005) was fixed right before 3.6.8 was released, so it might have gotten in there. You could test it. I'd personally like to see us support Python 3.7 if possible, and that's what I've been running locally.

**Review by nickpell — APPROVED** [review]
Confirmed this works with later versions of Python.  I'll explore upgrading to something beyond the Bionic default version.

Thanks for solving this problem!

**Pull request merged**
