### PR TITLE
new staging fab

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts 

hqdjango4-5: 4GB each
hqes0: 4gb
hqtouch0: 2GB
hqkafka0: 2GB

### CODE REVIEW

**Comment by dannyroberts** [comment]
:+1: whenever you're ready

**Comment by czue** [comment]
are we adding all of these machines and not decomissioning anything? can you offline costs and rationale with me? if we need them we need them but would like to understand need

**Comment by dannyroberts** [comment]
Offlined with @czue; there will be another PR removing the old machines. The plan is to break up our two 8GB "hqdjango*-staging" machines (which together host nearly all of staging's services) into 5 smaller machines, still totaling 16GB to keep the cost the same.

The main point of the change is to have better process isolation to make it easier to pinpoint the problems we're seeing with OOM errors. Hopefully with the new setup, it'll be much clearer who the culprit is when a machine starts seeing OOMs, and we can then change configuration variables or bump memory on machines as appropriate.

**Comment by benrudolph** [comment]
@esoergel i'm gonna go ahead and close this

**Comment by esoergel** [comment]
@benrudolph Sounds good - I've been referring back to this periodically, but have been merging it in piecemeal.

**Pull request closed without merging**
