### PR TITLE
uuids in UUID columns

### PR DESCRIPTION
**Pull request by snopoke**
@benrudolph @NoahCarnahan @czue @dannyroberts 
I started this today. There are a few complications that make it trickier than expected. I think in the long run (no more couch) this is worth it but it means that in the interim we're in a state that isn't great. I can't make up my mind whether its worth it or not and would appreciate opinions.

Details:
# comparing apples with apples

If we were able to use UUIDs everywhere there would be no issue but we need to support both which creates some issues 
- uuid's have multiple representations which are not equal when compared as strings

```
> uuid1 = uuid.uuid4()
> uuid1
UUID('82d17ade-1890-4518-9fe5-9c3e9ab28fc6')
> uuid1.hex
'82d17ade189045189fe59c3e9ab28fc6'
> str(uuid)
'82d17ade-1890-4518-9fe5-9c3e9ab28fc6'
> uuid1.hex == str(uuid)
False
```
- strings can't be directly compared to UUIDs

```
> case_id = uuid.uuid4().hex
> case = SqlDB.get_case(case_id)
> case.case_id == case_id
False
> case.case_id
UUID('82d17ade-1890-4518-9fe5-9c3e9ab28fc6')
> case_id
82d17ade189045189fe59c3e9ab28fc6
```

In test and SQL only code the solution to this is to normalise the UUIDS:

```
> UUID('82d17ade189045189fe59c3e9ab28fc6') == UUID('82d17ade-1890-4518-9fe5-9c3e9ab28fc6')
True
```

But in code that runs on both couch and sql we have to convert to string (as long as we're consistent with the string format):

```
> str(UUID('82d17ade-1890-4518-9fe5-9c3e9ab28fc6')) == '82d17ade-1890-4518-9fe5-9c3e9ab28fc6'
True
> str(UUID('82d17ade-1890-4518-9fe5-9c3e9ab28fc6')) == '82d17ade189045189fe5-9c3e9ab28fc6'
False
```

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/ex-submodules/casexml/apps/case/tests/test_domains.py, line 11 - E501 line too long (203 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_domains.py, line 35 - E501 line too long (203 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_domains.py, line 54 - E501 line too long (203 > 115 characters)
* corehq/ex-submodules/couchforms/tests/test_duplicates.py, line 6 - E501 line too long (120 > 115 characters)
* corehq/ex-submodules/couchforms/tests/test_edits.py, line 18 - E501 line too long (120 > 115 characters)
* corehq/form_processor/tests/test_dbcache.py, line 41 - E261 at least two spaces before inline comment
* corehq/form_processor/utils/migration.py, line 4 - F401 'namedtuple' imported but unused
* corehq/form_processor/utils/migration.py, line 6 - F401 'models' imported but unused
* corehq/form_processor/utils/migration.py, line 78 - E501 line too long (119 > 115 characters)
* corehq/form_processor/utils/migration.py, line 80 - E126 continuation line over-indented for hanging indent
* corehq/form_processor/utils/migration.py, line 98 - W391 blank line at end of file

**Comment by snopoke** [comment]
The more I think about this the the less I thino it's worth it. The gain is about 150-200Mb per million rows of either forms or cases. The cost is having to deal with uuids and strings in code + a horrible  migration at some future point. 

I don't think the storage space saved is worth it.

**Comment by benrudolph** [comment]
yeah i think i agree with you. it might be a premature optimization. that's a bummer that the uuid thing is so inconsistent. for now i'd vote for code simplicity

**Comment by czue** [comment]
yeah that all makes sense to me. is definitely a bummer, but hooray for making our lives easier!

**Pull request closed without merging**
