### PR TITLE
Remove FilterUsersField

### PR DESCRIPTION
**Pull request by czue**
@dannyroberts @biyeun more goodies. cc @benrudolph

### CODE REVIEW

**Comment by czue** [comment]
:white_check_mark:

**Comment by dannyroberts** [comment]
:goberserk:

**Comment by biyeun** [comment]
finally.

**Comment by dannyroberts** [comment]
Looks like you've been applying a little Strong Filter of your own, if you catch my drift.

:muscle:

**Comment by benrudolph** [comment]
i don't get it

**Comment by biyeun** [comment]
lol wut

**Comment by benrudolph** [comment]
:trollface:

**Pull request merged**
