### PR TITLE
make smsbillables tests faster

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
cuts 2-3 minutes out of test runtime locally.  looks like it helped on travis as well: https://travis-ci.org/dimagi/commcare-hq/builds/108642390

**Comment by nickpell** [comment]
@millerdev

**Comment by millerdev** [comment]
gtm on test pass

**Comment by benrudolph** [comment]
:horse_racing: :horse_racing: :horse_racing:

**Pull request merged**
