### PR TITLE
Enable case tile pull-down functionality

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Add an option to the case list configuration page to enable case tile pull-downs. When enabled, users can expand the case tile to show the case details.

Addresses:
https://trello.com/c/FmzEoH3r/35-case-tiles-configured-to-allow-detail-inline-datum-for-case-details
http://manage.dimagi.com/default.asp?158889

### CODE REVIEW

**Comment by snopoke** [comment]
No tests :(

**Comment by NoahCarnahan** [comment]
Ah right. I'll add those quick.

**Comment by NoahCarnahan** [comment]
@snopoke test added

**Comment by snopoke** [comment]
Sorry to be a stickler but I'm trying to move our tests away from this approach where its really hard to see what's being tested. I'll merge this anyway but please update the tests to create the app in code and use `self.assertXmlPartialEqual` to only test the portion on XML that you need to (in this case the `entry` I think).

See this comment from more details: https://github.com/dimagi/commcare-hq/pull/5752#issuecomment-77336806

**Comment by NoahCarnahan** [comment]
Didn't know about that function, thanks. Fixed here: https://github.com/dimagi/commcare-hq/pull/5833

**Comment by orangejenny** [comment]
How feasible would it be to make these checkboxes not depend on having "Use case tile" selected? (i.e., let projects using the "big textbox" version of case tiles use them)

**Comment by NoahCarnahan** [comment]
Very feasible. This should do the trick: https://github.com/dimagi/commcare-hq/pull/5847

**Comment by orangejenny** [comment]
! That'll make parto no longer a remote app. Thank you, Noah!

**Comment by NoahCarnahan** [comment]
Awesome! Glad I could help!

**Comment by czue** [comment]
"That'll make parto no longer a remote app"

awesome!

**Pull request merged**
