### PR TITLE
add fixture information to questions in Application API

### LINKED ISSUE #29170: API Endpoints - Add Lookup Table to App Structure API
Currently the App Structure API provides no context for single or multiselect questions which are set to use a Lookup Table datasource instead of hardcoded values.

The following Form Builder example question:
```
Form Builder clip	version 1
id	type	appearance	instances	itemsetData
/combobox_lookup	SelectDynamic	combobox	"{""long-sequence"":{""src"":""jr://fixture/item-list:long-sequence""}}"	"[{""instance"":{""src"":""jr://fixture/item-list:long-sequence"",""id"":""long-sequence""},""nodeset"":""instance('long-sequence')/long-sequence_list/long-sequence"",""valueRef"":""y"",""labelRef"":""x""}]"
```

for instance, is exported simply as

```
            {
              "comment": null,
              "constraint": null,
              "group": null,
              "hashtagValue": "#form/combobox_lookup",
              "is_group": false,
              "label": "",
              "label_ref": null,
              "options": [],
              "relevant": null,
              "repeat": null,
              "required": false,
              "setvalue": null,
              "tag": "select1",
              "translations": {},
              "type": "Select",
              "value": "/data/combobox_lookup"
            },
```

With no record of the instance ID. 

Suggestion is that for lookup tables which are non-custom to provide the table id (in this example `long-sequence`), potentially with the key `fixture_type` which would match the value used in the fixture api.

### PR DESCRIPTION
**Pull request by czue**
## Summary

Closes #29170

This adds the following new data for questions that reference fixtures in formbuilder:

```
"data_source": {
  "instance_id": "long-sequence",
  "instance_ref": "jr://fixture/item-list:long-sequence",              
  "label_ref": "x",
  "nodeset": "instance('long-sequence')/long-sequence_list/long-sequence",
  "value_ref": "y"
}
```

@ctsims I used a slightly different API than what you proposed, to provide more information and work with the primitives in the form instead of parsing out the "long-sequence" from the nodeset reference. Thinking that it'd be easier to offer more flexibility and let our consumers handle parsing if they need it.

Also I thought it was safe to just add this data without an additional URL param or API version, since it's only new data, and will only be present if the form had fixture references.

Recommend reviewing by commit.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

I added test coverage and manually tested every edge case I could think of. Also the only code that (currently) calls the new functionality is the API, though other things that reference form questions like app summary might benefit from it down the line.

### Automated test coverage

Added tests, and we have lots of regression tests for the modified code.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by ctsims** [comment]
Hey Cory,

This is great! Thanks for picking up the ticket, I think it's really helpful for the online community to see a path for Open Source resolution of new needs.

On the details: 

I agree with you that including the reference string is valuable information, otherwise users can't actually necessarily know precisely what data was referenced.

The only tricky thing is that there isn't necessarily a one-to-one alignment between the fixture "instance" naming and the fixture "source." IE: `instance('fixture_id')` and `jr://instance/fixture/fixture_ref`. Is it easy/possible to include both? It might be redundant for a lot of cases, but especially if people are trying to do anything automated, having access to the latter will be easier to build substring references. Maybe more importantly, since users can provide manual references there are scenarios where the former won't actually map up  to the HQ source.

**Comment by czue** [comment]
@ctsims thanks, and I had a similar thought re: instances though didn't try because of their association with the form instead of the node. I'll take a closer look tomorrow and see if it's easy to add. If not I'll probably propose launching with this version and seeing if anyone complains.

On the API side, do you think those should be part of the "question" content, or a new top-level attribute of the form? Can see the case for either option, though my first instinct is to make the API model the underlying data (i.e. a top-level form attribute) unless there's a compelling reason to not to.

**Comment by ctsims** [comment]
100% agree that if this is the difference between "pushing this out ~now" and needing to wait to implement a more complex approach that the current code is a helpful, positive change that would be valuable on its own.

Just based on how people are using the API, I think including the fixture connector in the question itself would be the most useful, and I don't think the redundancy is a big deal, but if that's hard I think it's totally fine to include at the top level and making people index the connector. If it's a big deal we can always add it downstream.

**Comment by czue** [comment]
alright @ctsims - it wasn't too bad so decided to go for it. you can see the updated API in the description.

**Review by ctsims — APPROVED** [review]
Nice, this looks great! Glad to hear it was easy to get the other pieces of metadata.

One tiny nit: Strictly speaking some of these lookups won't be fixtures. There are definitely scenarios where people do itemset selections with the casedb, for instance, so it might be helpful for the object key to be something like `datasource` (or something similarly generic) rather than `fixture_data` to prevent confusion

**Comment by czue** [comment]
ah, good point https://github.com/dimagi/commcare-hq/pull/29269/commits/3d01c432e32f38b66f903c9781151f02f02db557

**Pull request merged**
