### PR TITLE
Add view to play form attachment audio in browser

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/INDIV-28
[CommCare App PR](https://github.com/dimagi/commcare-android/pull/2533/files)

## Product Description

Adds a new link to view form attachment on web browsers using usual domain login page in case user needs to login, instead of inbuilt browser prompt, for better experience for mobile users.
The view currently available to view form attachment uses [api auth](https://github.com/dimagi/commcare-hq/blob/1b4a2a6c08ca3b50a4e6e86e2c57220a64f32b5c/corehq/apps/api/object_fetch_api.py#L141), requires mobile users to enter their full username (`<username>@<domain>.commcarehq.org`) in case it's accessed directly and user needs to login. 
Try accessing [this](https://staging.commcarehq.org/a/ccqa-mk/api/form/attachment/74042dfe-4145-4725-99fc-4c767e106752/1636569790636custom.mp3) attachment, on a private window.

A project requested that mobile users should not need to enter their full qualified name for this and enter just the username. 

## Technical Summary

When we use api_auth, we hand it over to Django to handle the auth for us, so there isn't much we can modify there.
I thought it was better to just add a new view that uses our default HQ workflow, which redirects the user to the domain login page, where mobile users can enter just their username along with their password and then are redirect back to the originally requested page.

We are working towards form attachments to play in the browser instead of user needing to download it. So this is for that usecase. The app would create the link and user would open it in browser and listen to the audio form attachment.

## Safety Assurance
Tested locally that auth works as expected. The access for form check was retained as it is.

### Safety story

Locally tested.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
Is there a reason not to change the auth for the API view so that it allows session auth?

**Comment by mkangia** [comment]
> Is there a reason not to change the auth for the API view so that it allows session auth?

Hey @snopoke 
reason for adding a new link was to avoid changing the behavior on the original link. Moreover, I was not sure if this would resolve by just supporting basic auth, because we wanted to use the special login page, that is domain specific and could create user's full username for login.

**Comment by mkangia** [comment]
@snopoke thoughts?

**Review by snopoke — COMMENTED** [review]
I would drop the class based views and just use function views, I think it would make things simpler:

```python
@location_safe
@login_and_domain_required
@require_form_view_permission
def get_form_attachment(request, domain, instance_id, attachment_id):
    return get_form_attachment_response(request, domain, instance_id, attachment_id)

@location_safe
@api_auth
@require_form_view_permission
def get_form_attachment_api(request, domain, instance_id, attachment_id):
    return get_form_attachment_response(request, domain, instance_id, attachment_id)

def get_form_attachment_response(request, domain, instance_id, attachment_id):
    # do the work
    return response
```

**Comment by mkangia** [comment]
Thanks for the review @snopoke .

Updated to use function views in https://github.com/dimagi/commcare-hq/pull/30801/commits/5985edd95aaabc8ac16c7dfe1336c6339be2829e.

Also, updated to use the new browser based view on form page in https://github.com/dimagi/commcare-hq/pull/30801/commits/5c7bd0efefcf80f82159fd98ad9a6220de5616a1. It should work the same, since the user would already be logged in when viewing form page and the same login decorator `login_and_domain_required` is used by the view `FormDataView` through `LoginAndDomainMixin`.

Also, found that the api view is used in [exports](https://github.com/dimagi/commcare-hq/commit/c511096bb887bfe9b0334271749c9bf151e3dd1b#diff-1ae97543378912bde3f3b8e1fc084780195a16a82ea8679a62ffc636e83f9cecR2124). So that should continue working as it is.

**Review by snopoke — APPROVED** [review]

**Review by esoergel — APPROVED** [review]

**Pull request merged**
