### PR TITLE
Don't show warning if report data source config is static

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: [FB 230265](http://manage.dimagi.com/default.asp?230265)

@dannyroberts @biyeun cc @sravfeyn

### CODE REVIEW

**Comment by dannyroberts** [comment]
seemed like an unrelated build error, kicked the failed job

**Comment by biyeun** [comment]
would this be covered by the build?

**Comment by dannyroberts** [comment]
haha good point, almost certainly not

**Comment by biyeun** [comment]
then shall i merge?

**Comment by dannyroberts** [comment]
👍

**Pull request merged**
