### PR TITLE
Removed unused fields from app passed to initial page data in web apps

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
Noticed tonight that the COVID app from `us-covid-performance` is 5 MB. It's almost entirely `modules` configuration, which itself is mostly default values loaded into the CI form, none of which is used. Having all of this in initial page data makes "View Source" kill my browser. Removing it might even perk up performance a bit.

Including @dannyroberts and @knguyen142 as SaaS devs who have worked with formplayer. This is a somewhat risky change without great test coverage. I'm planning to request a Web Apps UI regression from QA.

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

There's not a lot of automated coverage here.

### QA Plan

[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-2183)

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by orangejenny** [comment]
QA team did a web apps regression, this is ready to merge. Pinging for review.

**Review by dannyroberts — APPROVED** [review]

**Comment by dannyroberts** [comment]
Congrats @orangejenny this change cut our total network traffic through the nginx proxy to less than 20%

**Comment by dannyroberts** [comment]
https://app.datadoghq.com/dashboard/2ed-3e3-47s/proxy-dashboard?from_ts=1609253985886&fullscreen_end_ts=1609457408173&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1608569414953&fullscreen_widget=3799181629228018&live=false&to_ts=1609290773523

**Comment by orangejenny** [comment]
hooray 🎉

**Pull request merged**
