### PR TITLE
Add domain to notification email

### PR DESCRIPTION
**Pull request by emord**
Feature flag: "send UCR rebuild info"

Adds the domain to the notification emails subject so that it's a bit easier to track

### CODE REVIEW

**Review by czue — APPROVED** [review]
:clap: 

if you were feeling really inspired you could make it an actual email send instead of a soft assert :upside_down_face:

**Comment by emord** [comment]
Also just changed this to not notify when limit is specified. From what I can tell the limit is specified only when we want to create the preview in report builder, which means that this isn't a super useful email in that case

**Review by czue — APPROVED** [review]
nice

**Review by nickpell — APPROVED** [review]
Nice addition

**Pull request merged**
