### PR TITLE
exclude attachments from comparison

### PR DESCRIPTION
**Pull request by snopoke**
Should fix travis bulid
@benrudolph 
cc @sravfeyn

### CODE REVIEW

**Comment by czue** [comment]
:white_check_mark: when tests pass

**Comment by sravfeyn** [comment]
Test failure looks unrelated. Kicking build again
```python
ERROR: testArchive (couchforms.tests.test_archive.TestFormArchiving)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "corehq/ex-submodules/couchforms/tests/test_archive.py", line 26, in testArchive
    xml_data = self.get_xml('basic')
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 60, in get_xml
    return cls.get_file(name, 'xml', override_path)
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 46, in get_file
    with open(cls.get_path(name, ext, override_path)) as f:
IOError: [Errno 2] No such file or directory: 'corehq/ex-submodules/couchforms/tests/data/xforms/basic.xml'

**Comment by benrudolph** [comment]
thanks, i noticed i had to do that in my other PR. weird how the tests passed originally. that test failure is referring to a file that i recently added, but i just checked out this branch and it seems to be there
screen shot 2015-10-27 at 9 39 57 am

**Comment by snopoke** [comment]
@benrudolph - I don't see that file in the git repo - is it possible you didn't commit it?

**Comment by benrudolph** [comment]
ok so, `xforms/` is in our gitignore and thus the file was never committed. strange though since i had two other test files in that directory. i didn't check them in because i'm guessing they're not being used anymore

**Comment by benrudolph** [comment]
:white_check_mark:

**Comment by czue** [comment]
teamwork!

**Comment by benrudolph** [comment]
:hand:

**Pull request merged**
