### PR TITLE
drop few indicators from disha view

### PR DESCRIPTION
**Pull request by sravfeyn**
@pr33thi 

Hey @emord does this way of migration look correct for Sql view? (I created this migration by hand)

### CODE REVIEW

**Comment by lwyszomi** [comment]
Hi @sravfeyn, 

I think the migration file is not updated because you created it with reference to the migration ```0066_aggregatesqlprofile_last_included_doc_time``` but currently in the master branch, the newest migration file is ```0070_aww_name_in_agg_ccs_view```.

Regards,
Łukasz

**Comment by sravfeyn** [comment]
Phew, thanks @lwyszomi I will rebase the migration.

**Comment by lwyszomi** [comment]
👍

**Review by pr33thi — APPROVED** [review]
(approved with my limited context on this change)

**Comment by emord** [comment]
The view part looks fine to me

> (I created this migration by hand)

What part did you create by hand? Did you add all of the `RemoveField`s in the migration, or was that part autogenerated? I'm not familiar with `managed=False` models enough to know if that is expected

**Pull request merged**
