### PR TITLE
Require two factor for superusers

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
https://dimagi-dev.atlassian.net/browse/SAAS-10245. All superusers will now face the same two factor restrictions as users in domains that require two factor. That is, all pages will direct them to enable two factor until they've enabled it, and thereafter they'll have to provide provide a two factor token as part of login.

Additionally, the loophole for people who have lost their phone is not open to superusers. If they need to use the loophole, they'll have to first give up their superuser privileges, which can be added back once they've set up two factor again.

(There's also a thematically related but otherwise not related change in this PR having to do with how we calculate two_factor_enabled on a page where we show the two factor status of all supeusers.)

##### FEATURE FLAG 
This requirement only takes effect when
```
REQUIRE_TWO_FACTOR_FOR_SUPERUSERS = True
```
in `settings.py`.

### CODE REVIEW

**Comment by dannyroberts** [comment]
@snopoke @esoergel @AndreaMKing5 FYI this is a new option available for envs. I will turn it no for production and india; feel free to turn on as necessary. Alternately if you want to advocate for this being default behavior / not being under a setting, let me know

**Review by snopoke — APPROVED** [review]
The reason this wasn't rolled out a long time ago is because it breaks Excel dashboard integration (https://github.com/dimagi/commcare-hq/pull/20756 and http://manage.dimagi.com/default.asp?276165) which was a blocker for support.

Perhaps that's no longer an issue but just raising it in case it is.

**Comment by esoergel** [comment]
@dannyroberts thanks, IMO this is fine as opt-in by environment.

> it breaks Excel dashboard integration

I do believe this is still the case - I tried helping someone with that recently, and I don't think excel gave the flexibility to specify an API key in the appropriate manner.  The same issue came up with OData feeds, and was circumvented in a somewhat messy way with a [custom auth decorator](https://github.com/dimagi/commcare-hq/blob/a556c8d11d6aecb1c4b63e3184aa609e3c89f961/corehq/apps/domain/decorators.py#L326-L326).   IIRC, this allows the API key to be used as a password for those views, and in doing so, circumvents two-factor (search for `check_for_password_as_api_key`).

**Review by millerdev — APPROVED** [review]

**Comment by kcowger** [comment]
@snopoke and @dannyroberts yes, this was a blocker a while back, but we have worked around this. This is no longer a blocker for us.

**Comment by dannyroberts** [comment]
Awesome!

**Pull request merged**
