### PR TITLE
Update age in stunting and wasting indicators

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @emord,
I have updated age field for stunting and wasting indicators.
Regards, Dawid.

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Comment by emord** [comment]
test failures look related

**Comment by emord** [comment]
still looks related `FAIL: custom.icds_reports.tests.test_export_data:TestExportData.test_children_export_child_eight`

**Comment by dmydlo** [comment]
That's right eliminated after rebase, sorry.

**Comment by emord** [comment]
something weird happened with travis. Looks like the build passed, but never showed passed on github https://travis-ci.org/dimagi/commcare-hq/builds/415501918?utm_source=github_status&utm_medium=notification

**Pull request merged**
