### PR TITLE
fix get_open_case_ids_in_domain

### PR DESCRIPTION
**Pull request by dannyroberts**
See http://manage.dimagi.com/default.asp?170937 for context

### CODE REVIEW

**Comment by dannyroberts** [comment]
(The `hqcase.DBAccessorsTest`s pass locally)

**Comment by dannyroberts** [comment]
@benrudolph buddy

**Comment by czue** [comment]
@snopoke maybe you can take a look at this and validate danny's logic? (pasted below)

(unlikely) the callcenter function was relying on the fact that the query it was making would return empty if case_type was None, in which case this fix actually implements something totally different

(my guess) there was previously a bug, and this change exposed it: either case_type is never supposed to be None here, and that needs to be traced back; or a case_type of None is supposed to mean don't filter by case_type.

I'm fundamentally misunderstanding the bug or made a larger logical error in my refactoring (unlikely :p)

The PR assumes option #2 (my guess), so if that's the case then no further action's required.

**Comment by snopoke** [comment]
@dannyroberts is correct, case type should never be None but this isn't checked anywhere. I've commented in the ticket with some more context related to the specific domain.

**Pull request merged**
