### PR TITLE
Optimize pillow startup

### PR DESCRIPTION
**Pull request by emord**
When we had the ICDS rebuilds the other day, there were a lot of rebuild tasks generated because every pillow process tries to find the databases state and rebuild the table if necessary.

This PR will change this so that only one process can rebuild tables and I'm removing bootstrap_interval as I think that I originally changed that as a [work around for performance](https://github.com/dimagi/commcare-hq/pull/20831) (which shouldn't be an issue if only one process is trying this)

### CODE REVIEW

**Comment by calellowitz** [comment]
Isn't the table reflection pretty expensive? It takes 20-30 minutes before some of these pillows start actually processing change). Doing it once per hour, especially if it is unnecessary, ideally should only be on start, seems excessive

**Comment by emord** [comment]
@calellowitz I think its only as expensive as it is on ICDS because we have 150 processes trying to do it at once.

**Comment by emord** [comment]
@calellowitz With that said, It does makes sense to test this change out, and then only remove bootstra_interval if my understanding is correct

**Review by snopoke — COMMENTED** [review]
I had also been thinking about this recently. Will this not cause a race condition where the other pillows will start processing docs before the DB changes have been made?

**Comment by emord** [comment]
> I had also been thinking about this recently. Will this not cause a race condition where the other pillows will start processing docs before the DB changes have been made?

I think this should be fine. If there is an error it should go to pillow errors and be retried. And whenever a rebuild is triggered, then any processed docs should get re-processed in the rebuild command. Also there is already a race condition because all pillows are handling their own timestamping. So they will all be rebuilding at different times.

For ICDS, I think we'll get a significant speed up just from moving to citus since we're also removing all the child tables that need to be reflected.

Disclaimer, I haven't exactly flushed out  the following idea, but figured I'd at least document it publicly:

As a more long term step, I'd like to have a separate table that tracks when the last rebuild occurred. Columns could be config_id, rebuild_hash. The rebuild hash could be an md5 of a static config and the rev of a non-static data source. or we could base it off of times of last_modified for non-static data sources if we trust it. (personally I would not trust it until we can move it to a django model with auto_now). This could also open the door for us to find expression changes instead of just column changes.

**Comment by snopoke** [comment]
> As a more long term step, I'd like to have a separate table that tracks when the last rebuild occurred. 
We are tracking this in `DataSourceActionLog` but not with all the detail you mention.

**Review by snopoke — APPROVED** [review]

**Pull request merged**
