### PR TITLE
Added id property to RemoteRequestQuery

### PR DESCRIPTION
**Pull request by orangejenny**
## Product Description
Fixes build error when working with data registries.

## Technical Summary
When setting up a case search config with a data registry locally, I was getting this:
```
...
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/models.py", line 5048, in create_suite
    return SuiteGenerator(self, build_profile_id).generate_suite()
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/suite_xml/generator.py", line 79, in generate_suite
    DetailContributor(self.suite, self.app, self.modules, self.build_profile_id),
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/suite_xml/generator.py", line 68, in _add_sections
    section_elements = contributor.get_section_elements()
  File "/Users/jschweers/Documents/commcare-hq/corehq/util/timer.py", line 224, in _inner
    return fn(self, *args, **kwargs)
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/suite_xml/sections/details.py", line 98, in get_section_elements
    print_template=print_template_path,
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/suite_xml/sections/details.py", line 157, in build_detail
    for datum in datums
  File "/Users/jschweers/Documents/commcare-hq/corehq/apps/app_manager/suite_xml/sections/details.py", line 157, in <listcomp>
    for datum in datums
AttributeError: 'RemoteRequestQuery' object has no attribute 'id'
```

## Feature Flag
Data registries

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

I haven't dug into why existing tests like `test_search_data_registry` and `test_search_data_registry_additional_registry_query` don't throw this error. @snopoke @esoergel if either of you have ideas offhand I'm interested, if not I can look more closely tomorrow.

### QA Plan

Not requesting QA

### Safety story
Changes are minor and largely isolated to a feature flag that's still in development.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by snopoke** [comment]
I haven't been able to reproduce this locally.

**Comment by snopoke** [comment]
I hit this on staging: https://sentry.io/organizations/dimagi/issues/2653143846/?environment=staging&project=136860&query=is%3Aunresolved

It was triggered when I added a case list registration form. I can look into it tomorrow and write a test case if you don't get to it.

**Comment by esoergel** [comment]
I was able to reproduce this locally by adding a tab to the case details configuration (without the tab it succeeds)
image

This happens because this code block is inside
https://github.com/dimagi/commcare-hq/blob/13c6aaa943ac2c216a307be7405c744d549cfbe3/corehq/apps/app_manager/suite_xml/sections/details.py#L129-L129
though I have no idea _why_ this particular aspect of detail generation only happens for details with tabs.

**Comment by esoergel** [comment]
Just looked at the sentry issue Simon triggered on staging - I think it's the same issue manifesting in another part of the app build:
```python
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 135, in get_form_datums
    return self.get_module_datums(module_id)[form_id]
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 141, in get_module_datums
    _, datums = self._get_entries_datums()
  File "memoized.py", line 20, in _memoized
    cache[key] = value = fn(*args, **kwargs)
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 170, in _get_entries_datums
    self._add_missing_case_types(module_id, form_id, entry_datums)
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 190, in _add_missing_case_types
    form_datums_by_id = self._form_datums(module_id, form_id)
  File "memoized.py", line 20, in _memoized
    cache[key] = value = fn(*args, **kwargs)
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 187, in _form_datums
    return {d.datum.id: d for d in self.entries_helper.get_datums_meta_for_form_generic(form)}
  File "corehq/apps/app_manager/suite_xml/post_process/workflow.py", line 187, in <dictcomp>
    return {d.datum.id: d for d in self.entries_helper.get_datums_meta_for_form_generic(form)}
```

This suggests to me that there's a more fundamental discrepancy - is `RemoteRequestQuery` conceptually a `datum`?  If so, should it quack like one and work in these instances without modification?  If not, should it be returned from `get_datums_meta_for_form_generic` and `get_datum_meta_module` at all?  I'd have to do some more reading to figure that out, but do either of you know offhand?

**Comment by orangejenny** [comment]
> is RemoteRequestQuery conceptually a datum?

This is a good question. I didn't get to fully investigate this today but do think this PR needs more thought. Doing a naive search for `datum.id` turned up a couple more places where a `RemoteRequestQuery` looks like it may not belong, like [parent/child workflows](https://github.com/dimagi/commcare-hq/blob/215dd7c2be2ce0cbbc162e9fa5b9931edf2582f3/corehq/apps/app_manager/suite_xml/sections/entries.py#L849) and [EOF nav](https://github.com/dimagi/commcare-hq/blob/215dd7c2be2ce0cbbc162e9fa5b9931edf2582f3/corehq/apps/app_manager/suite_xml/post_process/workflow.py#L187).

**Comment by snopoke** [comment]
> is RemoteRequestQuery conceptually a datum? 

As far as commcare-core is concerned it is:
```java
public class RemoteQueryDatum extends SessionDatum
```

The `id` used commcare-core is the storage instance. In terms of it's use in workflows etc I don't think it should be included since it's 'computed' on entry and doesn't require user input so it should not be included in end of form nav etc. (I think).

> should it be returned from `get_datums_meta_for_form_generic` and `get_datum_meta_module` at all?

It needs to be in order to get into the entry datums but the other uses of those function don't need it. That either means creating a separate function that excludes them or filtering them out in the places where they are used.

**Comment by snopoke** [comment]
Better fix here: https://github.com/dimagi/commcare-hq/pull/30436

**Pull request closed without merging**
