### PR TITLE
update jsonobject-couchdbkit

### PR DESCRIPTION
**Pull request by emord**
@dannyroberts looks like we already do the pip freeze/grep thing you were already talking about: https://github.com/dimagi/commcare-hq/blob/master/scripts/uninstall-requirements.sh

cc: @czue

### CODE REVIEW

**Comment by emord** [comment]
Hmm. this isn't working here, although I got it to work on the django 1.7 branch.

Will look more into it after perf day

**Comment by emord** [comment]
lol. that's a real test failure. The jsonobject on prod/travis is actually jsonobject=0.6.0 instead of 0.6.3. There was some breaking change in the upgrade between 0.6.0 and 0.6.3

**Comment by czue** [comment]
I kicked the build and it passed but I'm still confused why it was failing (and think it might have to do with what time of day the tests run). 

Actually, I wonder if that's totally unrelated and a result of switching to travis containers.

**Comment by czue** [comment]
Anyway, feel free to self merge if you're good with this

**Comment by dannyroberts** [comment]
@emord I think you want to put this back on 0.7.0 and see how that goes?

**Comment by emord** [comment]
> I kicked the build and it passed but I'm still confused why it was failing (and think it might have to do with what time of day the tests run).

That seems bad and like it should get fixed, and like it will come back to bite us in random PRs, but it does seem to have gotten past that point with this test

**Comment by czue** [comment]
@emord is this good to go? feel free to self merge if so

**Comment by emord** [comment]
@biyeun Heads up in case you get any errors about `jsonobject.exceptions` on the deploy

**Comment by emord** [comment]
@dimagi/team-commcare-hq you will probably need to explicitly uninstall jsonobject and jsonobject-couchdbkit before upgrading to not run into errors

**Pull request merged**
