### PR TITLE
[ci skip] re-categorize DET export flag

### PR DESCRIPTION
**Pull request by czue**
https://github.com/dimagi/commcare-hq/pull/27025#issuecomment-616490834

##### FEATURE FLAG

Show an option to download data export tool schemas from the exports list view

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by snopoke** [comment]
This feels like it could use some kind of an integration test. What about adding one to the DET and run it on a schedule?

**Comment by czue** [comment]
> What about adding one to the DET and run it on a schedule?

Sure, happy to put this on my backlog and hopefully get to it soon. Is there infrastructure in place to do something like this already in `commcare-export`?

**Comment by snopoke** [comment]
There are already some integration tests which pull data from the `corpora` domain: https://github.com/dimagi/commcare-export/blob/master/tests/test_cli.py#L149

I've never tested this but you should be able to set up a cron job in Travis: https://docs.travis-ci.com/user/cron-jobs/

**Comment by czue** [comment]
Ok cool, thanks. I've added to my backlog but may not get to urgently. Assume is fine?

**Pull request merged**
