### PR TITLE
Added concatenate strings expression

### PR DESCRIPTION
**Pull request by kkrampa**
@czue 
I need concatenations in a couple of fields in enikshay.

### CODE REVIEW

**Review by czue — CHANGES_REQUESTED** [review]
looks good but can you add a test for it? should be lots of examples in `userreports.tests.test_expressions`

**Comment by kkrampa** [comment]
@czue Updated

**Review by czue — APPROVED** [review]
:+1: on :white_check_mark:

**Comment by kkrampa** [comment]
:white_check_mark:

**Pull request merged**
