### PR TITLE
Fix pygooglechart missing image issue

### PR DESCRIPTION
**Pull request by sravfeyn**
## Summary
Fixes a minor UI bug where the google charts image is sometimes missing in the Worker Activity Times report. https://dimagi-dev.atlassian.net/browse/SAAS-11367

Applies https://github.com/gak/pygooglechart/pull/25/ manually since a Pypi release is not yet made with that bug fix

@snopoke

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
Do we not need the other line change: https://github.com/gak/pygooglechart/pull/25/files#diff-db6fb49287744a184e2c1f8245d10f55f6b6dd22215a8f512eab7fdcb1ad6642R376

**Comment by sravfeyn** [comment]
We don't use colors, so it should be okay.

**Review by snopoke — APPROVED** [review]

**Comment by snopoke** [comment]
@sravfeyn can you update the description with any QA that was done / needs to be done (I assume you tested this locally?)

**Comment by sravfeyn** [comment]
@snopoke The issue is pretty hard to reproduce so I wasn't able to test it directly. But I tested by changing the underylying google charts URL and it works okay. (The old library of the version was using a different URL which was fixed by https://github.com/gak/pygooglechart/pull/25)

**Comment by snopoke** [comment]
@sravfeyn what I meant was have you checked that the reports still work and the charts show up?

**Comment by sravfeyn** [comment]
@snopoke Yes (sorry for the late response)

**Pull request merged**
