### PR TITLE
Make search and claim endpoints location safe

### PR DESCRIPTION
**Pull request by proteusvacuum**
Adds location safe decorator to search and claim endpoints. 

There is already messaging when you turn this feature on that you will have access to all the cases in that domain, so I figured we're pretty safe for now.

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
Sounds reasonable to me.  Have @sheelio and/or @dimagi/product greenlighted this?

(This change makes case search and case claim accessible to location-restricted users.  Those features allow the user to break out of the sandbox of their location and access data from other parts of the project, but that's kinda the point.)

**Comment by czue** [comment]
Since @sheelio and @amsagoff are both offline I'm going to say yes. This makes sense as a logical extension to the location restriction feature to me and I think very few projects are using this currently.

**Comment by proteusvacuum** [comment]
Yeah, there are only 2 projects with case claim currently. The first one are using their own location restrictions, and the other one wants to have access to all cases regardless of location, so I think this is the right behaviour currently.

**Comment by benrudolph** [comment]
niice fully functional web apps

**Comment by esoergel** [comment]
:+1:

**Pull request merged**
