### PR TITLE
dimagisphere prototype(s)

### PR DESCRIPTION
**Pull request by czue**
This adds a few admin views built on top of [django-websocket-redis](https://django-websocket-redis.readthedocs.org/en/latest/).

The main thing they do is visualize real-time form submissions as they come in:

dimagisphere

There's also this [sillly chat thing](https://staging.commcarehq.org/hq/admin/chat/) which is just modeled off the demo app that ships with the sockets library, and we can probably just delete (figured I'd leave it in for now for fun).

I'm open to feedback as to whether or not this should be part of our stack (especially for some fun, but not super useful admin visualizations). It is a fair number of additional moving parts (two new services, two new python packages) although I think that websockets themselves could open up the door to some pretty interesting and fun changes.

not sure who to ping so anyone from @dimagi/team-commcare-hq feel free to weigh in. I tried to break it up by commit, but I think probably easier to review in full and I'll just make some comments.

also depends on https://github.com/dimagi/commcarehq-ansible/pull/262

### CODE REVIEW

**Comment by biyeun** [comment]
:heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes:

**Comment by proteusvacuum** [comment]
Super awesome! Curious -- is there a tool / command that exists to simulate form submissions locally?

**Comment by czue** [comment]
@proteusvacuum not really. there's `./manage.py submit_form` or cloudcare as the two easiest options, but that'd be one at a time.

I can add a readme at some point that makes it clearer how to get it set up if it's not clear from the code changes. I'm still not clear what the best way to install kafka on dev machines is which is one reason I haven't done that yet.

**Comment by snopoke** [comment]
Just to clarify on the architecture:
* this runs a separate process which receives and processes the websocket requests
* routing to this service is handled by nginx config
* the main django instance just serves the initial view and static resources

Given that setup I'm OK with this going to prod. Initially I though the main Django process would be handling all the websocket requests as well. 

True that it is quite a few more moving parts but could be worth it if it opens the door to making HQ more responsive or whatever. Can re-evaluate in 6 months to see if we've made use of it in any meaningful way.

**Comment by czue** [comment]
(thanks for the explanation and sorry i didn't make that more clear)

**Comment by dimagimon** [comment]
There are 3 errors:

* corehq/apps/hqadmin/urls.py, line 6 - F401 'BroadcastChatView' imported but unused
* corehq/apps/hqadmin/urls.py, line 38 - E501 line too long (120 > 115 characters)
* corehq/apps/hqadmin/urls.py, line 40 - E501 line too long (127 > 115 characters)

**Comment by czue** [comment]
alright, removed the chat view since it just seemed like the type of thing that would rot. based on @snopoke's comment i took of the don't merge label so this should be ready to review

**Comment by dannyroberts** [comment]
Yeah looks awesome and seems like a worthwhile tool to have around and experiment with; like simon said we can re-evaluate if it doesn't get any meaningful use.

**Comment by dannyroberts** [comment]
@czue signed off but I'll let you self merge in case you need to coordinate ansible deploy

**Comment by czue** [comment]
yeah, I think it should be totally fine, but I'll merge and deploy this over the weekend assuming no other blockers just in case

**Comment by czue** [comment]
@dannyroberts just to confirm - you're signed off on this and https://github.com/dimagi/commcarehq-ansible/pull/262 right? i'll probably merge and deploy sometime over the weekend

**Comment by dannyroberts** [comment]
yup!

**Pull request merged**
