### PR TITLE
Add multithreaded dev server info to README

### PR DESCRIPTION
**Pull request by esoergel**
@sravfeyn

### CODE REVIEW

**Comment by czue** [comment]
django runserver is multithreaded by default as of 1.6 or something. we can just delete all of these instructions i think

**Comment by esoergel** [comment]
Nice, I didn't realize that.  I usually use `runserver_plus`, which by default isn't threaded.  Updated.

**Comment by czue** [comment]
thanks!

**Comment by proteusvacuum** [comment]
wow, for real? @dimagi/team-commcare-hq looks like you don't have to run gunicorn everytime you want to run cloudcare.

**Comment by czue** [comment]
lol, i definitely assumed everyone already knew that

**Comment by proteusvacuum** [comment]
hah, I wrote this so I never had to think about it:
```sh
#!/bin/bash
#cloudcare
bound="0.0.0.0:8000"
echo "STARTING GUNICORN ON $bound =^.^="
python manage.py run_gunicorn -w 3 --bind $bound &
echo "STARTING TOUCHFORMS"
jython submodules/touchforms-src/touchforms/backend/xformserver.py
```

**Pull request merged**
