### PR TITLE
EWS: Always get default number for user

### PR DESCRIPTION
**Pull request by kkrampa**
@gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
it looks like this assumes that every user has a verified number - is that a safe assumption to make? what would happen if someone creates a new user and doesn't verify their number?

**Comment by kkrampa** [comment]
@gcapalbo Good point I haven't thought about users created in HQ. I'm not sure that there is a sense to send reminders to users with unverified numbers since they are not able to send stock data to system, right?

**Comment by gcapalbo** [comment]
@kkrampa I'm not sure, we can probably ask Mike what he thinks the right behavior should be.  I think we can also handle that in a separate PR since it doesn't have to hold up this change from being introduced.

**Comment by kkrampa** [comment]
@gcapalbo sounds good to do this in new PR

**Pull request merged**
