### PR TITLE
Remove Report an Issue link from reports page on ICDS

### PR DESCRIPTION
**Pull request by dannyroberts**
Fixes https://dimagi-dev.atlassian.net/browse/ICDS-483

### CODE REVIEW

**Comment by orangejenny** [comment]
There are a bunch more of these: a couple of links that directly pop up the report an issue modal, and a whole lot of places that error messages have text directing the user to report an issue. Is this the only one that matters for ICDS?

**Comment by dannyroberts** [comment]
Yeah I'm not sure. Kishan was receiving issues specifically from this dialog and asked for it to be removed. There's one place in ICDS where we _don't_ want to remove the modal, and that's for the icds dashboad, where issues are submitted to a separate email address. This seemed like the easiest way of solving the Kishan's issue. I'll like him to your comment and can follow up if he thinks it's a priority

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
@dannyroberts Cool, thanks for checking with Kishan. These "hide things from ICDS" issues feel like whackamole. It'd be nice to whack all the moles at once.

**Comment by kishansampat** [comment]
@orangejenny @dannyroberts thanks for looking into this.

_There are a bunch more of these: a couple of links that directly pop up the report an issue modal, and a whole lot of places that error messages have text directing the user to report an issue._
- I am not aware of where these other links are. As Jenny said, it would be good to remove them all together. I only reported what I was seeing, but there are possibilities that in the future, if other pages 500 then those remaining will show up, and we'll start getting reports from there

**Comment by dannyroberts** [comment]
Okay, to cover all current and future links to the modal, changed the strategy here to just not create the modal to begin with under the "shouldn't be able to report an issue" condition, and also make the link look like normal text and make nothing happen when you click it. It will still read e.g. "If this issue continues, please report an issue", it just won't have a link

**Review by nickpell — APPROVED** [review]

**Pull request merged**
