### PR TITLE
skip extension case and dirty flags if not enabled

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
Don't compile dirtiness flags if the feature is not needed. Also check the extension case toggle once instead of in each loop iteration.

Found this from profiling.

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Comment by mkangia** [comment]
> Found this from profiling.

Can you tell more @snopoke ?

**Comment by snopoke** [comment]
@mkangia see https://dimagi-dev.atlassian.net/browse/IIO-502

**Comment by mkangia** [comment]
thanks @snopoke. I was asking about what profiling you did and how? Could not find that on the ticket.

**Comment by snopoke** [comment]
I used the `@profile` decorator as documented here: https://commcare-hq.readthedocs.io/profiling.html#getting-a-profile-dump

I did write a custom management command to run the import from the command line instead of the UI so that I didn't have to make changes to live code and didn't have to add the profile decorator to all VMs

**Comment by mkangia** [comment]
Thank you @snopoke

**Pull request merged**
