### PR TITLE
dbacessors cleaup

### PR DESCRIPTION
**Pull request by snopoke**
removing unused db accessors

@sravfeyn

### CODE REVIEW

**Comment by czue** [comment]
nice! :skull:

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by benrudolph** [comment]
:clap: :clap: (not mergeable)

**Comment by snopoke** [comment]
updated

**Comment by dannyroberts** [comment]
super cool :sunglasses:

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
