### PR TITLE
Fix supply map reports

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?267551

Immediate cause of bug was having script tags in async partials: when the "Apply" button is clicked, those scripts get reloaded, which errors.

Also replaced the usage of `initial_page_data` in `base_maps.html` - the replacement code uses the same general idea, but doesn't use the actual initial-page-data code because that doesn't play well with ajax reports.

Overall this PR is a band-aid. The reports front end doesn't work especially well with more modern js, I'll need to deal with that eventually but not today.

@gcapalbo / @esoergel

### CODE REVIEW

**Comment by orangejenny** [comment]
(supply is a feature flag, right?)

**Comment by orangejenny** [comment]
ignoring all stickler complaints

**Review by gcapalbo — APPROVED** [review]

**Comment by gcapalbo** [comment]
are the console.log statements there because you want to temporarily debug in production?

**Comment by orangejenny** [comment]
@gcapalbo They were statements I moved, didn't add them...and I just realized I didn't commit a deleted file. https://github.com/dimagi/commcare-hq/pull/19016/commits/2b8d3e159409df089524fab275cc02ea08b9c4ff

**Comment by gcapalbo** [comment]
ah, i see

**Review by gcapalbo — APPROVED** [review]

**Comment by esoergel** [comment]
Nice, thanks Jenny!

**Pull request merged**
