### PR TITLE
Replace Segment analytics

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Previously we used Segment's `analytics.js` library for KISSmetrics analytics. This replaces the Segment library with a light wrapper around the KISSmetrics API that mirrors the Segment API.
I've also changed some event names and changed how we identify users.

This change should be deployed at the same time as https://github.com/dimagi/Vellum/pull/400, so adding the review tag so that I can coordinate that once this PR has been signed off on. 

Best reviewed commit-by-commit.

@snopoke

### CODE REVIEW

**Comment by snopoke** [comment]
Looks good but does this still try and track stuff when you're running it without the setting?

**Comment by NoahCarnahan** [comment]
Are you thinking of the `KISSMETRICS_KEY`?
Without the `KISSMETRICS_KEY`, all the the kissmetrics api calls will have no effect, but they won't cause any errors. Looks like one of the ajax calls from the KISSmetrics boilerplate will 404 though. I'll fix that right now...

**Comment by NoahCarnahan** [comment]
@snopoke updated

**Comment by snopoke** [comment]
looks good, still has 'hold off on merge' label

**Comment by NoahCarnahan** [comment]
@snopoke Alright good to go

**Pull request merged**
