### PR TITLE
remove memcache from travis services

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
also do we ever use elasticsearch in tests?

**Comment by dannyroberts** [comment]
or rabbit mq?

**Comment by dannyroberts** [comment]
(let's see)

**Comment by czue** [comment]
huh.

**Comment by czue** [comment]
:white_check_mark: - any reason not to merge?

**Comment by czue** [comment]
gonna assume no

**Comment by dannyroberts** [comment]
Thanks!

**Pull request merged**
