### PR TITLE
Add flag to disable CodeMirror (and fix FontAwesome)

### PR DESCRIPTION
**Pull request by esoergel**
@emord

### CODE REVIEW

**Review by emord — APPROVED** [review]
:tight: Code mirror took 1.5 GB of memory when I loaded the icds app

**Comment by esoergel** [comment]
I believe it - &raw=true is a lifesaver for viewing large restores, so it's only sensible to add it here too.

**Comment by czue** [comment]
this seems fine, though I would have expected `raw=true` to just return the JSON of the doc

**Comment by emord** [comment]
agree with cory, but this seems like an improvement for now at least

**Comment by esoergel** [comment]
I thought about that, but a raw json response shows up unformatted in browsers unless you have an extension.  I suppose I could make the page just a large `<pre />` block.

**Comment by czue** [comment]
I think it's a reasonable assumption to assume someone who is using this would have an extension installed or can install one. not a fan of the pre tag since that's not too functionally different from what we have now. the useful thing about the contents actually being the raw contents is being able to save to a file, interact with whatever browser tools you have for JSON, be usable in APIs/scripts, etc..

**Pull request merged**
