### PR TITLE
remove references to selenium

### PR DESCRIPTION
**Pull request by snopoke**
@nickpell

### CODE REVIEW

**Comment by millerdev** [comment]
👍 on ✅

**Comment by czue** [comment]
the build is failing in a surprising way but it definitely seems related (i kicked it to be sure)

**Comment by millerdev** [comment]
Wonder if rebasing this on master would fix travis. Seems like it might be related to my recent docker changes (although I'm not sure why it would cause this failure).

Travis says it checked out [commit d1882e9](https://github.com/dimagi/commcare-hq/commit/d1882e9549650645ff13ac44bf9d588fd3bfe956) and failed with this:
```
$ cp .travis/localsettings.py localsettings.py
cp: cannot stat ‘.travis/localsettings.py’: No such file or directory

The command "cp .travis/localsettings.py localsettings.py" failed and exited with 1 during .
```

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
