### PR TITLE
Case List Explorer WIP / Pre-Work

### PR DESCRIPTION
**Pull request by biyeun**
Re-writing the PR/branch from https://github.com/dimagi/commcare-hq/pull/21718 because otherwise the history feels too messy. I didn't want to force push to the other branch and override feedback, so I will close that one in favor of this PR.

Will respond in the other PR to outstanding questions either directly inline, or for general questions I will respond below.

I don't want to get too wrapped up in the overall structure and how it will be extended in the future just yet. Right now I have a basic idea of how I would like to structure the different moving parts and I want to get to a working model before I run through the architecture. I will take in the comments from @czue in the original PR for round 2 of this one.

Glaring convention issues are what I really wanted to cover here. Thanks @orangejenny for being thorough with the last one. I made the js changes you requested and will comment back on the original PR.

Reviewing commit by commit is probably most helpful

### CODE REVIEW

**Comment by biyeun** [comment]
@czue 

> Did you consider using/expanding the report implementation that is used for UCR for this?

I'm building off of what farid did for the first iteration of Case List Explorer and using this as an opportunity to think of a different solution which still needs some iteration for this one problem before I think we can use it elsewhere. From the bigger picture, this solves a task similar to UCR (in that a user can configure columns in a report), but isn't at all the same thing. I guess I'm not ready for this level of review just yet.

**Comment by biyeun** [comment]
@czue 

> Also, what requirements are driving the need to go outside the current (hard to use but functional) report framework? Only asking because I get nervous about the idea of there now being three different report frameworks in the codebase.

The fact that it's hard to use and really will not do what [has been proposed](https://app.atomic.io/d/NsqtUqBTEggp) as the solution for this problem. Think of it as a UCR-type report with a user-first design approach that, if this test works well, will likely replace the old UCR...

**Comment by biyeun** [comment]
@czue 

The current report framework does not make it easy at all to have a completely asynchronous report  table / view and filters...which is what this solution requires. Also I'm first focusing on this specific use case before I extrapolate what I think can be generalized as part of a larger framework, because starting from the other direction has led to some very complex and over-engineered code. This is not at all at a stage where it's ready for a big-picture review, as it's still in the sketching stages. I just want to keep my PRs small as I move forward and not get too out of date with master due to how disruptive the timeline has been for me to work on this.

**Comment by biyeun** [comment]
@orangejenny 

> Other people probably have stronger opinions on the new reports models/approach. Is there a particular kind of feedback you're looking for?

I think when I've closed the loop on a working example that implements what's in meghan's prototype, I will ask for a higher-level architecture review. Right now all the missed new js convention issues has been great feedback. Thank you!

**Review by orangejenny — APPROVED** [review]
Looks good to me - I didn't review from top to bottom, just read through the comments on the old PR and looked at the updates. Thanks for keeping the js clean and up to date.

**Comment by orangejenny** [comment]
Build failure is real but is an easy fix: `FAIL: corehq.apps.hqwebapp.tests.test_requirejs:TestRequireJS.test_files_match_modules`

**Comment by proteusvacuum** [comment]
hey, I'd love to lurk on your work for this. think you could ping me on the PRs too?

**Pull request merged**
