### PR TITLE
lazily build jar/jar files

### PR DESCRIPTION
**Pull request by nickpell**
Round 2 of https://github.com/dimagi/commcare-hq/pull/10046.  Confirmed on staging that I can deploy a build to Android.

@dannyroberts

### CODE REVIEW

**Comment by dannyroberts** [comment]
Nice, this is looking really good. I'll wait for tests. I think the final thing to test before we merge is that you can install on a j2me phone

**Comment by dannyroberts** [comment]
(both from a pre-existing build and from a new build)

**Comment by nickpell** [comment]
QA passed: http://manage.dimagi.com/default.asp?211172

**Comment by nickpell** [comment]
> I think the final thing to test before we merge is that you can install on a j2me phone

I asked QA to check this, and it passed.

@dannyroberts Looks ready to merge

**Comment by dannyroberts** [comment]
Woohoo!

**Comment by czue** [comment]
:clap: :four_leaf_clover: :zzz: :construction: :file_folder:

**Comment by proteusvacuum** [comment]
I did a bit of profiling using the `app_builder_live_test`. 

## Results
Run 5 times:
### Time
Differences: -7.94 -18.39 -19.63 -11.02 -22.62

Average: **-15.92%**

### Memory
Differences: -66.7 -66.47 -66.7 -66.17 -66.73

Average: **-66.54%**

see more: https://gist.github.com/proteusvacuum/3d2261394474e89c480d

**Comment by proteusvacuum** [comment]
:racehorse: :chart_with_downwards_trend: :+1:

**Comment by benrudolph** [comment]
wow awesome

**Comment by dannyroberts** [comment]
@proteusvacuum great idea for getting those numbers! Great to see what a success this was!

**Pull request merged**
