### PR TITLE
Clean up DRTB Excel Import 

### PR DESCRIPTION
**Pull request by sheelio**
@nickpell @esoergel 
More changes to support the Excel import for Mumbai data.

### CODE REVIEW

**Comment by nickpell** [comment]
tests are failing

**Comment by sheelio** [comment]
@nickpell @proteusvacuum 

Can you quickly review and then I'll merge this?

**Review by nickpell — APPROVED** [review]
Looks good when tests pass

**Comment by sheelio** [comment]
@proteusvacuum 

Tests are passing - would be good to review the last set of changes I made before merging.

**Comment by sheelio** [comment]
@proteusvacuum 

This is probably good to merge (might make running it on the real environment easier).  I can make further fixes after.   Let me know if that's ok and I'll merge it.

**Pull request merged**
