### PR TITLE
ICDS: Remove Primary Key from Case ID

### PR DESCRIPTION
**Pull request by sheelio**
This is causing issues with some ICDS reports that are display raw data from the tables. 

@emord @benrudolph to review and merge. 

@sravfeyn We'll also need this deployed to NIC.

### CODE REVIEW

**Comment by emord** [comment]
I think `is_primary_key` should be defaulted to `false`, would it be better to just remove all instances of that?

**Comment by sheelio** [comment]
I think HQ will add it back in automatically (these were regular data sources before being converted to static).

Can remove if you think cleaner.

**Comment by czue** [comment]
@sheelio what are NIC reporting timelines? it's quite a process to deploy things and just want to confirm whether these are urgent or can wait until that process is smoother.

**Comment by sheelio** [comment]
Not urgent, we can bundle into a single deploy later.   

This issue will affect the phone and web-based MPR reports until deployed, but I don't think that will be used for a little bit of time.

**Comment by emord** [comment]
This is good to go from my side. 

@calellowitz @benrudolph @czue how do you guys want to handle bundling up deploys? Assuming we have to do several patches in a row, should these PRs be tagged with something like "icds to be patched"?

**Comment by benrudolph** [comment]
i'm in favor of the tagging system. this does seem unmaintainable though

**Comment by calellowitz** [comment]
@czue @emord @sravfeyn 
Is there a reason not to just do a normal fab deploy when the patch server comes online? It gets rid of the need to worry about tagging branches and manually patching. I understand if there are political restrictions around that though

**Comment by benrudolph** [comment]
i think it just depends on how urgent this is to get into the codebase. if it's not time sensitive, then i'm all for waiting for the patch server

**Comment by czue** [comment]
agreed we should wait unless @sheelio or india team explicitly needs something on a particular date.

**Comment by czue** [comment]
i think we can decide at some point soonish whether we need a more maintainable solution to this problem based on how things progress at NIC

**Comment by sheelio** [comment]
Closing this since its already fixed in a different PR.

**Pull request closed without merging**
