### PR TITLE
Removed feature flag to copy conditional alerts

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
Ran across this while working on updating SMS workflows for https://github.com/dimagi/commcare-hq/issues/25718

No one has this flag turned on (prod, india, ICDS, swiss, PNA).

##### FEATURE FLAG
Allow copying conditional alerts to another project (or within the same project).

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Do we know if this was ever used or why it was originally implemented? It seems odd to me that Giovanni would have implemented a feature that had no known/intended use case. https://github.com/dimagi/commcare-hq/pull/21749 doesn't give a reason for why it was added.

**Comment by orangejenny** [comment]
@millerdev I don't know why it was implemented, agree it's odd. My best guess is it might have been useful during a migration, given that it's a user-based flag.

**Comment by snopoke** [comment]
It was used for the eCHIS migration. It may be necessary for rec.

**Comment by orangejenny** [comment]
@snopoke Interesting. It looks like rec doesn't use conditional alerts, so we should be clear.

**Comment by mkangia** [comment]
Just hope that we don't rewrite this in future when we do a similar thing and forget that this was done in the past.

**Comment by orangejenny** [comment]
@mkangia I agree that's a risk but generally think the risk of dead code is greater. Unused code often doesn't age well.

**Comment by mkangia** [comment]
@orangejenny absolutely.

**Pull request merged**
