### PR TITLE
remove legacy app pillow and promote kafka app pillow

### PR DESCRIPTION
**Pull request by snopoke**
@czue is it time?

### CODE REVIEW

**Comment by czue** [comment]
nice. I think you'd know better than me if it's time but g2g from my side. assume the other pillow is caught up?

**Comment by snopoke** [comment]
yea, the other pillow is fully caught up so don't think we need to keep the old one around

**Comment by snopoke** [comment]
and we now have a bulk reindexer that supports resume which was the other outstanding thing

**Comment by czue** [comment]
all sounds good to me. :+1: on :white_check_mark:

**Comment by snopoke** [comment]
woo, 1 down 4 to go

**Pull request merged**
