### PR TITLE
Put services dir in `current` dir

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts last week a deploy failed during "clear_supervisor_conf" and when services were restarted, one of the nodes went down and it had me scrambling. by moving the `services` dir into the `current` dir it will be managed by the symlink cutover. this also has the benefit of being able to rollback service confs. one downside is that this really explicitly makes our supervisor coupled with cchq. in my opinion this is OK since we already use cchq to generate all the supervisor confs anyways. it also means we can't have multiple environments on one machine (staging and production etc) which in a way is a pro cause that's always a nightmare when that happens

cc: @gcapalbo

### CODE REVIEW

**Comment by benrudolph** [comment]
https://github.com/dimagi/commcarehq-ansible/pull/356

**Comment by czue** [comment]
:+1: good call

**Comment by dannyroberts** [comment]
:+1: yeah, happy about this change!

**Comment by benrudolph** [comment]
this is gonna be tough to deploy. i have to stop all supervisor services before deploying this

**Comment by benrudolph** [comment]
ok this should be safe to merge, just want to make sure it works on staging first. the idea is that this will create the supervisor templates in both the old and new directories. then i only have to work about stopping supervisor, changing the conf and then starting it again which seems more manageable. after that i will revert this commit: https://github.com/dimagi/commcare-hq/pull/10756/commits/be57518a3a36d6b63b6d1b130c8d4ea966504094

**Comment by benrudolph** [comment]
tested this out on staging. good to merge

**Comment by czue** [comment]
:beers: to one less way to bring down HQ

**Pull request merged**
