### PR TITLE
Update Dashboard docs

### PR DESCRIPTION
**Pull request by emord**
Should be able to go through commit by commit. First ones are mostly removing those items that have been out of date for quite a while now. I also wanted to flesh out a few more Citus specific commands that can be used now.

@czue @calellowitz @Rohit25negi Likely going to depend on you guys to let me know if you feel something should get added here. Either in this PR or in my future PRs.

@calellowitz I removed the old celery documentation here. Can you add some notes about airflow?

### CODE REVIEW

**Review by czue — APPROVED** [review]
This looks great to me (though am trusting you a lot on everything since I haven't gone through most/any of these myself).

Is there any replacement for `goal_state_aggregation`? I have referred to that image a few times in other docs/places and found it useful (but obviously we shouldn't keep it around if it is no longer accurate).

**Comment by czue** [comment]
fyi, @calellowitz has a [gdoc on airflow](https://docs.google.com/document/d/1TVK9zyQsXZvLUlg_lg6H-201usI5lLHb3ObOxlpGA54/edit#heading=h.u74cgo2e1o0i) that we can probably incorporate.

**Comment by emord** [comment]
> Is there any replacement for goal_state_aggregation

My reasoning was that I think we are already at that point. I believe that I originally created that before most of those data sources existed to help explain some of the migrations I was doing. As of now all form data has been pulled into separate form based UCRs instead of being read from case data. Airflow also provides an automatically generated flow chart that may be a better source

**Comment by czue** [comment]
Cool, good to know we hit our goals! Was also thinking airflow was a good replacement.

**Pull request merged**
