### PR TITLE
release guided tour

### PR DESCRIPTION
**Pull request by biyeun**
@dimagi/product 

Removes feature flags for guided tour

### CODE REVIEW

**Comment by amsagoff** [comment]
YES YES YES

**Comment by benrudolph** [comment]
:eyes:

**Comment by czue** [comment]
real build fail?
```
======================================================================
FAIL: test_app_from_template (corehq.apps.app_manager.tests.test_views.TestTemplateAppViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 250, in test_app_from_template
    self._check_response(response)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 241, in _check_response
    self.assertTrue(redirect_location.endswith(expected))
AssertionError: False is not true
```

**Comment by biyeun** [comment]
@czue should be fixed now...had updated the default view for creating an app

**Pull request merged**
