### PR TITLE
Revert "clean up cleanup"

### PR DESCRIPTION
**Pull request by snopoke**
Reverts dimagi/commcare-hq#8733

http://manage.dimagi.com/default.asp?184794
`change_submissions_app_id` url used in exports.

@dannyroberts @czue 

cc @sravfeyn

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 16 errors:

* corehq/apps/cleanup/views.py, line 1 - F401 'ResourceNotFound' imported but unused
* corehq/apps/cleanup/views.py, line 4 - F401 'render' imported but unused
* corehq/apps/cleanup/views.py, line 5 - F401 'reverse' imported but unused
* corehq/apps/cleanup/views.py, line 7 - F401 'require_GET' imported but unused
* corehq/apps/cleanup/views.py, line 8 - F401 'make_form_couch_key' imported but unused
* corehq/apps/cleanup/views.py, line 10 - F401 'DELETED_SUFFIX' imported but unused
* corehq/apps/cleanup/views.py, line 11 - F401 'memoized' imported but unused
* corehq/apps/cleanup/views.py, line 12 - F401 'random_hex' imported but unused
* corehq/apps/cleanup/views.py, line 13 - F401 'get_db' imported but unused
* corehq/apps/cleanup/views.py, line 14 - F401 'json_response' imported but unused
* corehq/apps/cleanup/views.py, line 16 - F401 'CommCareCase' imported but unused
* corehq/apps/cleanup/views.py, line 18 - F401 'require_superuser' imported but unused
* corehq/apps/cleanup/views.py, line 19 - F401 'Group' imported but unused
* corehq/apps/cleanup/views.py, line 21 - F401 'CommCareUser' imported but unused
* corehq/apps/cleanup/xforms.py, line 1 - F401 'CouchUser' imported but unused
* corehq/apps/cleanup/xforms.py, line 2 - F401 'get_es' imported but unused

**Comment by dannyroberts** [comment]
Ugh, really sorry. I think this isn't the first time I've tried to do this.

**Comment by dannyroberts** [comment]
I don't think those links have been used in years, so instead if it's alright, I'm just going to excise them form the exports template.

**Comment by snopoke** [comment]
@dannyroberts fine by me

**Comment by dannyroberts** [comment]
https://github.com/dimagi/commcare-hq/pull/8753

**Pull request closed without merging**
