### PR TITLE
Update v1 filter fields in addition to columns

### PR DESCRIPTION
**Pull request by esoergel**
I typed out some debugging details in the ticket:
https://manage.dimagi.com/default.asp?267201

I think this should fix the issue, although one thing I'm unsure of is how the data source gets updated.  I assume that happens when this is saved, otherwise the columns would break.  Would be great to get some confirmation on that though.

@sravfeyn

### CODE REVIEW

**Comment by esoergel** [comment]
@kaapstorm looks like you're area owner for report builder, can you validate that this change makes sense?

**Review by sravfeyn — APPROVED** [review]

**Comment by esoergel** [comment]
@sheelio looks like you've done a fair bit of work in this area as well.  Does this change make sense?

**Comment by sheelio** [comment]
I think this looks good (the change from v1 -> v2 was appending a data type to the possible options, but we didn't handle that for filters?)

**Review by kaapstorm — APPROVED** [review]

**Comment by kaapstorm** [comment]
This looks right. +1 for improved docs.

**Pull request merged**
