### PR TITLE
Fix bug in Case Activity report

### PR DESCRIPTION
**Pull request by NoahCarnahan**
The case type filter in the case activity report wasn't doing anything. I think the filtering capability was lost here: https://github.com/dimagi/commcare-hq/pull/4881.
Addresses http://manage.dimagi.com/default.asp?159279.

### CODE REVIEW

**Comment by snopoke** [comment]
:+1:

**Comment by NoahCarnahan** [comment]
@snopoke 
Ah, just realized this report is cached. Should I do anything to clear it out?

**Comment by snopoke** [comment]
No, I don't think so. Cache is for 1 hour not serious.

**Comment by NoahCarnahan** [comment]
Great, thanks.

**Comment by czue** [comment]
yikes, sorry about that. thanks @NoahCarnahan

**Pull request merged**
