### PR TITLE
Move pygooglechart-0.3.0.tar.gz to reliable host

### PR DESCRIPTION
**Pull request by millerdev**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
lol

**Comment by czue** [comment]
is there any way to have pip detect whether or not it already has this installed? it seems silly that we have to download the same thing and install it on every deploy, and the number of headaches it has caused has been quite annoying.

**Comment by snopoke** [comment]
Unfortunately not. Since we run pip with '--upgrade' it needs to download the package in order to check the version number since it doesn't have any other metadata for the package.

**Comment by millerdev** [comment]
> is there any way to have pip detect whether or not it already has this installed?

There is. We'd have to put our requirements on a server that allows directory listings or acts as a full-blown PyPI server. Then we could do something like this in the requirements file:

```
--find-links http://files.dimagi.com/pylibs/

pygooglechart==0.3.0
```

**Pull request merged**
