### PR TITLE
Reduce and split commtrack design doc

### PR DESCRIPTION
**Pull request by esoergel**
The commtrack design doc had quite a bunch of views.  This PR removes the now unused ones and splits the two remaining views each to their own design doc.

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
Not sure what's up with travis. Do you know?

**Comment by esoergel** [comment]
@dannyroberts I made this branch separately from the branches it depended on, as those were still being iterated on.  Consequently, travis didn't have all the needed code changes.  Now that the other branches have been merged, I rebased off master and we're g2g.

Do you think it's worth doing this in stages?  Spin up the two new views, switch the code over there, then delete commtrack after?

**Comment by dannyroberts** [comment]
If I'm understanding correctly, then I don't think that's necessary. That's basically what will happen anyway: preindex will create the new views, deploy will switch the code, and prune_couch_views will delete the old design doc. That seems like a good workflow to me.

**Pull request merged**
