### PR TITLE
call extension point function if no extension points match

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
Call the extension point function if no extension points are registered or none match the domain.

This make it much easier to have a default implementation as shown in the `validate_password` extension in this PR.

## Safety Assurance
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [X] If QA is part of the safety story, the "Awaiting QA" label is used
- [X] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage
Covered by existing tests as well as new tests added.

### Rollback instructions
- [X] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Yes, excellent! Did we discuss this when we were designing extension points? If not, I certainly thought about it, but not sure why I didn't bring it up.

**Comment by snopoke** [comment]
@millerdev I don't recall discussing it. Build failing due to renaming extension point used by ICDS. For some reason I can't get the ICDS branch to checkout. Will try a few more things today.

**Comment by mkangia** [comment]
will it still be possible to call the original definition if needed , in the extension code?
for example, in this case, if we wanted to call the HQ definition and add more validation after that instead of replacing it.

**Comment by snopoke** [comment]
> will it still be possible to call the original definition if needed , in the extension code?
> for example, in this case, if we wanted to call the HQ definition and add more validation after that instead of replacing it.

not in the current implementation - if we want to do that we can at a later stage.

**Comment by mkangia** [comment]
> not in the current implementation - if we want to do that we can at a later stage.

But it was possible before this change? Just thinking if we are adding a limitation by this change.
(Fine to punt this if you have already thought this point)

**Comment by snopoke** [comment]
> > not in the current implementation - if we want to do that we can at a later stage.
> 
> But it was possible before this change? Just thinking if we are adding a limitation by this change.
> (Fine to punt this if you have already thought this point)

Yes it was possible before though the only extension point with a default implementation is `validate_password_rules`.

**Review by millerdev — APPROVED** [review]

**Comment by snopoke** [comment]
holding off on merge till it's needed / after the 'safe defploy' period

**Pull request merged**
