### PR TITLE
Remove "Edit Mode" from app builder

### PR DESCRIPTION
**Pull request by dannyroberts**
Next up: Removing support for referrals in app building

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/apps/app_manager/views.py, line 219 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 912 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/views.py, line 977 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/views.py, line 1412 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 1727 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 1729 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 2213 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 2325 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/views.py, line 2515 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2526 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2530 - E302 expected 2 blank lines, found 1

**Comment by dannyroberts** [comment]
@czue your referrals PR reminded me. This has been on staging since 3/13 without any related 500s (just double checked my inbox by searching "label:staging-500 edit" and "label:staging-500 apps"). This wouldn't catch JS errors and such, but no one's complained about any such thing. Wonder if we still want QA team to do an app builder UI pass anyway just given how many lines of code were touched in this change.

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/apps/app_manager/views.py, line 219 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 918 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/views.py, line 983 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/views.py, line 1418 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 1737 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 1739 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 2230 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 2342 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/views.py, line 2532 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2543 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2547 - E302 expected 2 blank lines, found 1

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/apps/app_manager/views.py, line 219 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 918 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/views.py, line 983 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/views.py, line 1418 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 1737 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 1739 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 2230 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 2342 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/views.py, line 2532 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2543 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2547 - E302 expected 2 blank lines, found 1

**Comment by czue** [comment]
@christineawhite any sense how much app building happens on staging in a week? we're trying to QA this change organically and just want to make sure that most of the code has been exercised

**Comment by christineawhite** [comment]
@czue I haven't don't much app building on staging recently since most everything has been under a flag on staging.  I know sometime Matt Theis does some app building on staging but I haven't heard of anything recently.  Let me know if you want me to quick off a regression of app builder, that might be the easiest way to feel comfortable releasing.  We have a comprehensive app builder test plan now.

**Comment by benrudolph** [comment]
One way to sanity check is to check the logs and see if the relevant views have been hit in the past couple of days

**Comment by dannyroberts** [comment]
@benrudolph that's definitely a possibility, but it's hard to say that *every* page we care about has been hit unless we compile a list of every page we care about by URL or something, but that still doesn't tell use there were no JS errors... and at that point it starts to seem easier to just ask the QA team to do a pass of the app builder test plan.

@christineawhite that sounds great. It's on staging, right now. Do you have a sense of how long the app builder test takes to run?

**Comment by dannyroberts** [comment]
(@christineawhite offlining to QA ticket)

**Comment by snopoke** [comment]
Not mergable

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/apps/app_manager/views.py, line 220 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 919 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/views.py, line 984 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/views.py, line 1421 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 1740 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 1742 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 2233 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 2345 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/views.py, line 2535 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2546 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2550 - E302 expected 2 blank lines, found 1

**Comment by dannyroberts** [comment]
Thanks @snopoke

**Comment by dimagimon** [comment]
There are 11 errors:

* corehq/apps/app_manager/views.py, line 220 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 919 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/views.py, line 984 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/views.py, line 1421 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 1740 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 1742 - W601 .has_key() is deprecated, use 'in'
* corehq/apps/app_manager/views.py, line 2233 - E241 multiple spaces after ','
* corehq/apps/app_manager/views.py, line 2345 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/views.py, line 2535 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2546 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views.py, line 2550 - E302 expected 2 blank lines, found 1

**Comment by christineawhite** [comment]
@dannyroberts passed QA

**Comment by dannyroberts** [comment]
:white_check_mark:

**Comment by millerdev** [comment]
I guess technically you meant you removed the "no edit" or read-only mode :stuck_out_tongue:

**Comment by dannyroberts** [comment]
@millerdev oh, ha! I guess you're right

**Pull request merged**
