### PR TITLE
Re-apply "Added compress blocks"

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
Re-applies changes in https://github.com/dimagi/commcare-hq/pull/25291, without compressing the requirejs config files.

Since [the error](https://sentry.io/organizations/dimagi/issues/1208788280/) caused by 25291 was coming from the HQ dashboard, it's presumably related to one of the changes made to `hqwebapp/base.html`, the only one of the modified templates that is rendered by the dashboard. Of the 3 compress blocks added to that file, the most suspicious one is the one that touches requirejs files, although I don't know exactly why it would be a problem.

@millerdev Pinging you in case you're curious. If this works I'll send a retro on the whole issue.

### CODE REVIEW

**Comment by kaapstorm** [comment]
I'm a little scared to approve this. I definitely agree that we should use compress blocks universally. But I'm concerned that we didn't reproduce the problem locally, and while commit 295f026 makes sense, it doesn't seem to be a certainty that that was definitely the problem, nor that that was the only problem.

Is there any urgency in getting this merged?

If not, would it be worth trying to reproduce the error that the initial PR caused, maybe on a VirtualBox monolith, and checking that this resolves the problem and that there aren't any other unexpected issues?

Alternatively, sometimes testing takes a very long time and I would be willing to concede if you think that the amount of time that would take is not worth it. I would also not be offended if you think I'm being overly concerned -- measured risk-taking can save lots of effort.

**Comment by orangejenny** [comment]
Hi @kaapstorm I don't think you're overly concerned, I'm not terribly keen on releasing this with my current set of knowledge about the world.

> If not, would it be worth trying to reproduce the error that the initial PR caused, maybe on a VirtualBox monolith

Could you tell me more about this? The original PR worked on staging, so the problem seems to be related to something that's different about our staging and production setup. (My guess had been maybe staging only has one webworker, but it turns out that's the not true, it has two.) I'm definitely open to testing more, but I'd want to be testing something specific that's true of prod but not staging.

**Comment by kaapstorm** [comment]
> Could you tell me more about this? ... I'd want to be testing something specific that's true of prod but not staging.

Good question! I don't know. But @emord, @snopoke or @dannyroberts might.

**Comment by orangejenny** [comment]
@kaapstorm It doesn't seem that anyone has great ideas about what might be the underlying issue here (based on lack of response to this PR and on offline conversations). I removed the other compress blocks from `hqwebapp/base.html`, so if there are other issues, they'll affect a much smaller subset of HQ. I'd like to merge this, deploy to india, smoke test, and then deploy to prod if all is well on india. What do you think?

**Comment by kaapstorm** [comment]
Sounds good to me!

**Review by kaapstorm — APPROVED** [review]

**Comment by orangejenny** [comment]
Deployed to india, smoke tested affected pages and had no problems. Deploying prod now.

**Comment by orangejenny** [comment]
Deployed to prod, smoke tested, no problems.

**Pull request merged**
