### PR TITLE
add xform_ids to case json for SQL cases

### PR DESCRIPTION
**Pull request by snopoke**
This is an expensive field to add since it requires a DB query to get the list of form IDs but it is required by the API's.

Although this requires a reindex we should just be able to do it in place and since it's only for SQL cases it shouldn't take long.

@emord

### CODE REVIEW

**Comment by emord** [comment]
I don't think I understand where the reindex/db query is coming from in this commit.

**Comment by snopoke** [comment]
This changes the JSON data that get's send to ES so we need to reindex to update the existing data but since the mapping isn't changing we can just do it in place.

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by czue** [comment]
looks good. let me know if you want me/interrupt to run the reindex

**Comment by snopoke** [comment]
yea, that would be great thanks - it just needs to be the SQL forms
reindex:
```
./manage.py ptop_reindexer_v2 sql-form --reset --in-place
```

`--reset` is necessary so that it reset's the progress to the beginning

**Pull request merged**
