### PR TITLE
Pillow bootstrap

### PR DESCRIPTION
**Pull request by mkangia**
[Spec](https://docs.google.com/document/d/1SuXES-FHZTRyL-e6QdEgsoxDcbsYUngPXDww2ydKCyk/edit)

1. Add DD notification for tracking time taken by UCR pillows for bootstrap
2. An attempt to reduce bootstrap time by fetching all configs asynchronously and then fetch them after a 2-minute delay. Also fetch only once instead of once for each pillow instance. Begin just with get report configs which takes around 44 secs to load `1720` configs
```
In [2]: from corehq.util.timer import TimingContext

In [3]: with TimingContext("fetch_confs") as timing_fetch_confs:
   ...:     configs = [config for config in DataSourceConfiguration.all() if not config.is_deactivated]
   ...:

In [4]: timing_fetch_confs.duration
Out[4]: 44.13952994346619

In [5]: len(configs)
Out[5]: 1720
```
This can be then further extended to [other things](https://github.com/dimagi/commcare-hq/blob/2d60bf36b3d6d7de08650f47a6c79488bed41b22/corehq/apps/userreports/pillow.py#L145-L155)

Best review
🐟 / 🐟 

@czue thoughts?

### CODE REVIEW

**Comment by mkangia** [comment]
@snopoke 
Would like to definitely add the DD notification which is the first commit.
Also, these are code changes i was talking about.  As of now just kept it to the first step of bootstrap where all configs are loaded which saves 45 seconds each time pillow bootstraps each hour. This can be then further extended to other things if possible.
Just wanted to share the idea via code. Fine to just revert if this looks too complex or ineffective.

**Comment by czue** [comment]
leaving a quick comment since i'm about to drop offline. generally seems like a good and helpful addition to have these cached across processes so am supportive of that change if it's easy/smooth. i didn't fully wrap my head around the reset logic or any potential issues that could arise from that.

**Comment by mkangia** [comment]
Thanks @czue ,
also added a spec doc to understand the approach better

**Comment by emord** [comment]
How many data sources are deactivated? it may be worth adding a view that can filter those out before they get interpreted by jsonobject.

**Comment by snopoke** [comment]
Closing old PRs. Reopen if necessary.

**Pull request closed without merging**
