### PR TITLE
SMS export page shouldn't be location_safe

### PR DESCRIPTION
**Pull request by sravfeyn**
https://dimagi-dev.atlassian.net/browse/HI-444

Hey @esoergel 

For some reason even though, DownloadNewSmsExportView or any of its parent classes or not marked `@location_safe`, when the location middleware looks at the view, it finds that it has `is_location_safe` set to True. I haven't been able to figure out why that might be, but overriding the dispatch method fixes the issue. This is not a good solution, so if you have any idea what's going on here, I will do that instead.

### CODE REVIEW

**Comment by esoergel** [comment]
Oof, yeah, this is unfortunate.  Looks setting an attr on a method of a child class will set that attr on the parent class if the child class doesn't implement that method.  I'm pretty sure this is what's going on:

```python
In [1]: class A(object):
   ...:     def foo(self):
   ...:         return
   ...: class B(A):
   ...:     pass
   ...: class C(A):
   ...:     pass
   ...: 

In [2]: B.foo.__func__.bar = True

In [3]: B.foo.bar
Out[3]: True

In [4]: A.foo.bar
Out[4]: True

In [5]: C.foo.bar
Out[5]: True
```
It looks like it works as you'd want it to if said child class overrides that method:
```python
In [1]: class A(object):
   ...:     def foo(self):
   ...:         return
   ...: class B(A):
   ...:     def foo(self):
   ...:         return super(self, B).foo()
   ...: class C(A):
   ...:     pass
   ...: 

In [2]: B.foo.__func__.bar = True

In [3]: B.foo.bar
Out[3]: True

In [4]: C.foo.bar
...
AttributeError: 'function' object has no attribute 'bar'
```
I just played around with Django's `@method_decorator` util, and it looks like it doesn't suffer from this issue - I believe it wraps the `dispatch` method, so the wrapper gets decorated:
```python
In [10]: def new_location_safe(dispatch):
    ...:     dispatch.new_location_safe = True
    ...:     return dispatch
    ...: 

In [11]: from django.utils.decorators import *

In [12]: @method_decorator(new_location_safe, 'dispatch')
    ...: class Test(BaseDownloadExportView):
    ...:     pass
    ...: 

In [13]: Test.dispatch.new_location_safe
Out[13]: True

In [14]: DownloadNewSmsExportView.dispatch.new_location_safe
...
AttributeError: 'function' object has no attribute 'new_location_safe'
```
I believe we can adopt that same approach here by making a wrapper for the dispatch view:
```python
In [1]: from corehq.apps.export.views import *

In [2]: from django.utils.decorators import *

In [3]: def location_safe(view):
   ...:     # For the branch that handles Django views
   ...:     @wraps(view.dispatch)
   ...:     def _inner(*args, **kwargs):
   ...:         return view.dispatch
   ...:     _inner.new_location_safe = True
   ...:     view.dispatch = _inner
   ...:     return view
   ...: 

In [4]: @location_safe
   ...: class Test(BaseDownloadExportView):
   ...:     pass
   ...: 

In [5]: Test.dispatch.new_location_safe
Out[5]: True

In [6]: DownloadNewSmsExportView.dispatch.new_location_safe
...
AttributeError: 'function' object has no attribute 'new_location_safe'
```
I haven't tested this solution out any further than that, but it makes sense to me and it works in a shell session.  If you want to play with that approach, that'd be great, or feel free to kick it to me.

**Comment by sravfeyn** [comment]
Great, thanks for investigating and clear writeup. Using `@method_decorator(location_safe, 'dispatch')` on other sibling classes fixed the issue.

**Comment by esoergel** [comment]
I just pushed a commit - this is more what I was thinking - I'm concerned that the way this is currently implemented leaves open the possibility of this same issue arising in the future.  This change should apply the same fix for all view classes currently using the `@location_safe` decorator

**Comment by sravfeyn** [comment]
Ha, that's better, thanks

**Comment by sravfeyn** [comment]
@esoergel Just FYI, this is actually breaking (for good?) the old code that depended on this limitation, for e.g. [this issue](https://dimagi-dev.atlassian.net/browse/ICDS-453).

**Comment by sravfeyn** [comment]
I don't see more issues on [sentry](https://sentry.io/organizations/dimagi/issues/?project=136860&query=someone+was+just+denied&statsPeriod=14d), though. So we are probably good.

**Comment by esoergel** [comment]
Thanks for flagging.  I think that's good, although there may be some pages that should be location safe that now aren't.  The other issues are probably places where we show users links they shouldn't have access to.

**Pull request merged**
