### PR TITLE
Location-safe app releases

### PR DESCRIPTION
**Pull request by kaapstorm**
[Jira](https://dimagi-dev.atlassian.net/browse/SC-72)

This change allows location-restricted users to deploy an app to their phone using a QR code. This is a requirement of projects in Mozambique.

I'm opening this as a draft PR because the Deploy dialog has a lot of links and async requests for content leading off it, and I think we should talk more about what we want to do with those.

Currently links to pages that aren't location-safe result in a 403 page, and async requests fail silently. I'd love to hear feedback on the experience we'd like location-restricted users to have. @dimagi/product 

Things to consider:
* SMS deploys
* Deploys to Java devices
* "Click here in your mobile browser" on the barcode dialog.
* Feature-flag-hidden functionality on the Releases page and the Deploy dialog (e.g. Open in Web Apps?)

### CODE REVIEW

**Comment by esoergel** [comment]
This will give access to the app in its entirety, won't it?  Currently it's not possible to create a location-restricted role with the "Applications" permission - this seems like it would violate that.  Additionally, there is no "read only" applications permission that I'm aware of.

Is the basic idea to have a page available with a list of builds, but not allow creating or editing builds or touching the app?  Do they need all builds, or just the latest?  What permission will control who sees this?

**Comment by millerdev** [comment]
I'm going to defer to @esoergel on this one

**Comment by orangejenny** [comment]
Like @esoergel I'd be interested in hearing more about what the requirements are. I think it might make more sense to make a new, minimal interface, likely reusing the QR code modal and maybe some of the releases page HTML.

**Comment by kaapstorm** [comment]
Hey @esoergel I think your questions are on the right track, and @orangejenny your suggestion seems spot on.

To keep the conversation thread in one place, Juan's answer by email was that this is so that CHWs' managers can deploy the latest released version of an app to CHWs' devices.

If a location-restricted user opens an app, they see a minimal deploy page, with the details (name, comment, version) of the latest release of the app and a QR code.

Currently, apps can't be associated with a location (or can they?), so location-restricted users shouldn't be able to change an app (because of course their changes would affect users outside their location). Until it is a requirement that apps can be associated with a location, and location-restricted users can modify apps, it seems right (because YAGNI) that we hold-off on creating a new read-only permission for apps. If a location-restricted user navigates to an app, they are presented with this new minimal page to deploy.

Does that sound correct?

**Comment by orangejenny** [comment]
@kaapstorm That makes sense to me. I could imagine using `apps_base.html` and the QR code modal to make a pretty basic page, it sounds like they don't need anything else from the deploy modal.

> Currently, apps can't be associated with a location

Confirming this is true.

**Comment by kaapstorm** [comment]
Closing this PR in favor of that.

**Pull request closed without merging**
