### PR TITLE
Removed loading.gif

### PR DESCRIPTION
**Pull request by orangejenny**
Minor. It was bugging me that this image has a white background instead of transparent, so it looks weird in the inline edit widget.

@gbova

### CODE REVIEW

**Comment by orangejenny** [comment]
or @biyeun

**Review by gbova — APPROVED** [review]

**Review by kaapstorm — APPROVED** [review]
YES!

**Comment by biyeun** [comment]
@orangejenny did you mean to remove the loading gif with the blue background that's present on all of app manager?

**Review by biyeun — APPROVED** [review]
offlined. looks good

**Pull request merged**
