### PR TITLE
Submodule form display conditions

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?179827

@NoahCarnahan review by commit

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/app_manager/tests/test_child_module.py, line 32 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 111 - E501 line too long (128 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 166 - E501 line too long (174 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 185 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 275 - E501 line too long (152 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/app_manager/tests/test_child_module.py, line 32 - E501 line too long (122 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 111 - E501 line too long (128 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 166 - E501 line too long (174 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 185 - E501 line too long (125 > 115 characters)
* corehq/apps/app_manager/tests/test_child_module.py, line 275 - E501 line too long (152 > 115 characters)

**Comment by snopoke** [comment]
@NoahCarnahan fixed merge conflict

**Comment by NoahCarnahan** [comment]
:+1:

**Pull request merged**
