### PR TITLE
Fix multimedia_suite.xml in CLI ccz download

### PR DESCRIPTION
**Pull request by NoahCarnahan**
The "view source" page (/a/<domain>/apps/download/<app_id>/) can be used to view the files of the latest version of an app, not just builds. When doing so, the media_suite.xml file can be missing "version" attributes on its "resource" elements. This change ensures that those attributes will exist on the preview. 

More importantly, this does the same thing to the url that the CLI tool uses to get the latest ccz of an app. This fixes the issue the CLI tool has with apps that contain multimedia.

@ctsims cc @kaapstorm, @orangejenny

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
This replaces https://github.com/dimagi/commcare-hq/pull/8649, which unintentionaly changed the CCZ download in other views too.

**Comment by kaapstorm** [comment]
Do you still want the [views/download.py:318](https://github.com/dimagi/commcare-hq/pull/8649/files#diff-8c8eb3bf8735832e5061795c93ce6e7fL318) change, or is that part of the unintentional change?

**Comment by NoahCarnahan** [comment]
Yeah, thanks for pointing that out. That change isn't necessary, but might as well include it here too.

**Comment by NoahCarnahan** [comment]
:white_check_mark:

**Pull request merged**
