### PR TITLE
kill ctable

### PR DESCRIPTION
**Pull request by snopoke**
@emord 

cc @dannyroberts @czue 

:fish:

### CODE REVIEW

**Comment by emord** [comment]
```
No submodule mapping found in .gitmodules for path 'submodules/ctable-src'
The command "eval git submodule update --init --recursive" failed. Retrying, 2 of 3.
No submodule mapping found in .gitmodules for path 'submodules/ctable-src'
The command "eval git submodule update --init --recursive" failed. Retrying, 3 of 3.
No submodule mapping found in .gitmodules for path 'submodules/ctable-src'
The command "eval git submodule update --init --recursive" failed 3 times.
The command "git submodule update --init --recursive" failed and exited with 1 during .
```

**Comment by emord** [comment]
Looks good to me other than the build fail

**Comment by emord** [comment]
```
Traceback (most recent call last):
  File "./manage.py", line 96, in <module>
    execute_from_command_line(sys.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/vendor/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vendor/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/vendor/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ctable
```

**Comment by dannyroberts** [comment]
😍

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by dannyroberts** [comment]
:goberserk:

**Comment by czue** [comment]
finally!

**Pull request merged**
