### PR TITLE
autodetect xpaths in detail/@nodeset, recursively

### PR DESCRIPTION
**Pull request by dannyroberts**
and do all other checks recursively as well

### CODE REVIEW

**Comment by czue** [comment]
build fail looks related
```
======================================================================
ERROR: test_case_detail_tabs_with_nodesets (corehq.apps.app_manager.tests.test_suite.SuiteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_suite.py", line 342, in test_case_detail_tabs_with_nodesets
    self._test_generic_suite("app_case_detail_tabs_with_nodesets", 'suite-case-detail-tabs-with-nodesets')
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 71, in _test_generic_suite
    self.assertXmlEqual(self.get_xml(suite_tag), app.create_suite())
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/models.py", line 4712, in create_suite
    return SuiteGenerator(self).generate_suite()
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/suite_xml/generator.py", line 72, in generate_suite
    EntryInstances(self.suite, self.app, self.modules).update_suite()
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/suite_xml/post_process/instances.py", line 14, in update_suite
    self.add_referenced_instances(entry, details_by_id, relevance_by_menu, menu_by_command)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/suite_xml/post_process/instances.py", line 59, in add_referenced_instances
    instances = EntryInstances.get_required_instances(xpaths)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/suite_xml/post_process/instances.py", line 80, in get_required_instances
    raise UnknownInstanceError("Instance reference not recognized: {}".format(instance_name))
UnknownInstanceError: Instance reference not recognized: external
----------------------------------------------------------------------
```

**Comment by dannyroberts** [comment]
Thanks, the failure seems to be a technicality that I can easily edit the test to fix, but I'm going to check in with the test's author to make sure I'm still testing the thing they wanted to test.

**Comment by dannyroberts** [comment]
I think that test did actually expose a real(ish?) error that just wasn't exposed until we started autodetecting instance ids in `detail/@nodeset`s. Should be fixed

**Comment by dannyroberts** [comment]
:white_check_mark: good from my side but still open for review

cc: @proteusvacuum @orangejenny

**Comment by czue** [comment]
(i'll defer to someone with more app builder context to review)

**Pull request merged**
