### PR TITLE
add combined index to stock transaction table

### PR DESCRIPTION
**Pull request by snopoke**
@czue @benrudolph  not sure how long this will take on prod.

### CODE REVIEW

**Comment by benrudolph** [comment]
looks good to me

**Comment by czue** [comment]
@snopoke can this be merged if we run the migration manually right after? seems unlikely to be disruptive or take longer than 24 hours, yeah?

**Comment by snopoke** [comment]
I don't think we can since it will lock the table for writes. We will have
to use CREATE INDEX CONCURRENTLY which has to be run manually on the DB. I
can run it next week and monitor how it goes. This also means that this
migration can't be run after the index is built (since the index will
already exist).

I'll test this out locally next week and just verify that we can't run it
from the South migration.

**Comment by czue** [comment]
ah, ok, thanks for the heads up. that's annoying.

**Comment by snopoke** [comment]
Updated to create the index concurrently. I've tested this locally and on staging. It ran for about a minute on staging so not 100% sure what to expect on prod.

**Comment by snopoke** [comment]
@czue @benrudolph I ran this on prod today and it took 25 mins (and didn't return control to South till it was done).

**Comment by czue** [comment]
nice, thanks!

**Comment by benrudolph** [comment]
did you just update the preindex code and then run the migration? does make sense to have a fab task so we can run it easily as a daemon?

**Comment by snopoke** [comment]
Yup, that's what I did. A fab task could be nice.

**Pull request merged**
