### PR TITLE
Add a new indicator for LS app

### PR DESCRIPTION
**Pull request by sheelio**
Will merge once I've verified tests have completed.

### CODE REVIEW

**Comment by czue** [comment]
:white_check_mark: @sheelio wasn't quite sure what you meant by "Will merge once I've verified tests have completed" but feel free to merge now if you want this merged

**Comment by snopoke** [comment]
Is it intentional to have these in the main DB and not in the UCR DB?
(specified by `engine_id='{default/ucr}'`

**Comment by czue** [comment]
good catch. i don't think so and we should probably change it (@sheelio we'll have to rebuild the data sources when we do that)

**Comment by sheelio** [comment]
@czue @snopoke 

Thanks - I've updated the data sources.  I spoke to Noah / Nick.  They are okay with me merging changes to ICDS data sources/reports directly into master once the tests have passed.   Let me know if that is ok.

**Comment by snopoke** [comment]
@sheelio I meant that there are two options for datasource, `default` or `ucr`, sorry for the confusion.

Not so sure about pushing directly to master. Possibly OK if you run the `corehq.apps.userreports.tests.test_static_data_sources` tests locally first but I don't really see what you gain since the changes won't be live until after a deploy anyway. Even if we don't wait for builds on the PR's I think simply having a second person look at the PR reduces the risk of accidental changes slipping in.

**Comment by czue** [comment]
I think @sheelio meant self-merging the PRs after tests run. Which feels fine to me, though I don't think it hurts to have someone else take a quick look either. Since these are going to be very important reports for the ICDS project it couldn't hurt to start building cross-team knowledge about them

**Comment by czue** [comment]
@sheelio just to reconfirm - I think you'll have to manually rebuild these after deploy. there's some chance the framework will handle this for you, but good to keep an eye on it

**Pull request merged**
