### PR TITLE
Elasticsearch mapping utils and lint

### PR DESCRIPTION
**Pull request by joxl**
## Technical Summary

This is a _"utilities and cleanup only"_ update, split out from #30799.  This PR is a near-verbatim subset of that earlier PR, lacking only the actual mapping syntax changes. As such, all the mapping adjustments in _this_ PR are 100% lint, and no Elastic cluster mapping updates are needed for this change set.

The reasons for splitting these changes out and making a new PR are:
- keep the most benign parts of the change set separate to improve merge cadence
- other Elastic mapping work is being done simultaneously that can benefit from the utilities provided by this PR (e.g. #31402)
- improved commit quality

Review commit-by-commit :tropical_fish:

Jira: [SAAS-12152](https://dimagi-dev.atlassian.net/browse/SAAS-12152)

### Safety story

New tests have been added. Many existing Elastic-related tests are now labeled `es_test` (where applicable).  All linted mappings were tested for equality against their previous unlinted version.

### QA Plan

No QA.

### Migrations

There are no migrations in this PR. The mapping changes are lint-only.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
I understand the mapping changes are meant to be no-op but I'm unable to verify that via code review. Have you been able to verify that in another way?

**Comment by joxl** [comment]
> I understand the mapping changes are meant to be no-op but I'm unable to verify that via code review. Have you been able to verify that in another way?

Yes, you can dump the mapping as json pre-translate, and again post-translate, load them and assert `==`.

**Comment by joxl** [comment]
> Yes, you can dump the mapping as json ...

Note that this is effectively what the new `print_elastic_mappings` command can do, only it prints python instead of JSON.  Explained doing this the "raw, dump actual JSON" way in my previous comment because since this new management command is _part of this PR_, it may be desirable to for a PR reviewer to perform this check in a way that doesn't depend on PR code itself.

**Review by millerdev — COMMENTED** [review]
LGTM once @snopoke's concerns are addressed.

**Comment by calellowitz** [comment]
Haven't had a chance to look this over yet, but just wanted to thank you for breaking this out. I was about to suggest something similar for the same reasons you mention in the description. It will be great to have fewer long open PRs, and should make future ES work, both by you and others, much easier and safer.

**Comment by snopoke** [comment]
> > I understand the mapping changes are meant to be no-op but I'm unable to verify that via code review. Have you been able to verify that in another way?
> 
> Yes, you can dump the mapping as json pre-translate, and again post-translate, load them and assert `==`.
> 
> If you would like to do this yourself, I can provide commands. Is that something you're interested in?

Thanks, as long as you've done that then 👍🏻

**Review by snopoke — APPROVED** [review]
Thanks for the updates, looks great.

**Pull request merged**
