### PR TITLE
add management command to fix forms whose non-ascii chars are corrupted

### PR DESCRIPTION
**Pull request by nickpell**
Followup to https://github.com/dimagi/commcare-hq/pull/24791

https://dimagi-dev.atlassian.net/browse/HI-747

@dimagi/py3

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Would be nice to find a more reliable way to detect if a form was encoded with the wrong encoding. Was this caused by https://github.com/dimagi/commcare-hq/pull/24298?

**Comment by nickpell** [comment]
@millerdev is it even possible to detect if a form had the wrong encoding applied? The corrupted form sources contain valid unicode points so in principle a user might have entered them.

**Comment by nickpell** [comment]
Yes, the issue fixed in https://github.com/dimagi/commcare-hq/pull/24298 caused this

**Comment by millerdev** [comment]
> is it even possible to detect if a form had the wrong encoding applied?

Probably not definitively, but we might be able to use some other heuristics to make a better guess, such as whether the form was pickled/unpickled while the bug was live? Do we know the location of the pickle/unpickle that caused this?

**Comment by nickpell** [comment]
> Do we know the location of the pickle/unpickle that caused this?

https://github.com/dimagi/commcare-hq/pull/24791

> such as whether the form was pickled/unpickled while the bug was live?

The bug was live approximately the afternoon of July 10, so searching for apps that had forms modified during that period might make it tractable to search for issues.

**Comment by millerdev** [comment]
>> Do we know the location of the pickle/unpickle that caused this?
>
> #24791

Right, obviously. Sorry for being dense, and thanks for the follow-up.

**Pull request merged**
