### PR TITLE
add `fab <env> manage` for running mgmt cmds

### PR DESCRIPTION
**Pull request by dannyroberts**
e.g.

``` bash
fab production manage --set cmd='prune_couch_views'
```

### CODE REVIEW

**Comment by dannyroberts** [comment]
@nickpell @esoergel, thinking of you and all your current work that'll let us kill some views!

@dimagi/team-commcare-hq assuming this passes review, you can now run prod/staging management commands from fab :)

**Comment by esoergel** [comment]
woo!  Nice one, kinda surprised we didn't already have this!

**Comment by benrudolph** [comment]
sweet! long overdue

**Comment by czue** [comment]
off the charts on the xkcd scale
image

**Pull request merged**
