### PR TITLE
Remove nulls when serializing

### PR DESCRIPTION
**Pull request by benrudolph**
http://manage.dimagi.com/default.asp?157690#875994

@czue crushing this bug blind like marshawn lynch #beastmode

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
lol @benrudolph 
image

**Comment by czue** [comment]
will merge after tests run

**Comment by benrudolph** [comment]
that poster should be framed in your office/standing desk

i've been getting that pip install error on most of my builds today

**Comment by czue** [comment]
build fail looks unrelated

**Pull request merged**
