### PR TITLE
add index for domain and type

### PR DESCRIPTION
**Pull request by mkangia**

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
Will need to think about the best way to roll this out since creating the index will lock the table and also block the deploy. 

Could do this https://github.com/dimagi/commcare-hq/blob/3e88dbe4554316981e7f9a43fde34aa8870702c9/corehq/form_processor/migrations/0066_auto_20170818_2020.py but I think that will still block deploy. 

Can we do `create concurrently if exists`?

**Comment by mkangia** [comment]
@snopoke 
I am not sure how much of downtime we are talking about here, would you have an idea about it?

> Can we do create concurrently if exists?

Will check it out. Never used that before.

**Comment by snopoke** [comment]
@manish, more time than we want to lock a table for. Usually we create the index concurrently prior to rolling out the django changes and then use 'create index if exists' using one of these operations: https://github.com/dimagi/commcare-hq/blob/64b6e141aa37d75cce3c9d15ab4b04677ed64717/corehq/util/django_migrations.py#L68-L67

Could probably create one for `AlterIndexTogether`

**Comment by mkangia** [comment]
I used `AlterIndexIfNotExists` and tested it on local machine.

It creates the index when run for the first time and in case the migration is rerun it runs successfully.

**Comment by mkangia** [comment]
Also,
confirming that what we want to run on
- each shard
- each environment

would be 
```
CREATE INDEX CONCURRENTLY form_processor_commcarecasesql_domain_type_05e599e0_idx ON form_processor_commcarecasesql(domain, type);
```

**Review by snopoke — APPROVED** [review]

**Comment by emord** [comment]
Instead of running it manually on each shard, it's probably easier to setup a relase with this branch and run `./manage.py migrate_multi` in a tmux session.

**Comment by mkangia** [comment]
thanks @emord 
my understanding is that the change in this PR would lock the table even in that case and this should be run only via PG shell.

**Comment by emord** [comment]
@mkangia Err. yeah. my suggestion combined with Simon's suggestion would mean that you don't need to run it on every shard, so it'd look like:

1. Change migration to use `concurrently` and be non-atomic as in simon's linked PR
2. setup release with this branch
3. run migrate_multi in the private release branch
4. merge this PR

**Comment by mkangia** [comment]
Thanks @emord . Updated.

Looks like `AlterIndexIfNotExists` was not needed any more, so reverted that.

**Comment by snopoke** [comment]
What's the status of this?

**Comment by mkangia** [comment]
Thanks @emord. Really appreciated the laid out steps.
Can i get a review/approval on this?

**Review by emord — APPROVED** [review]

**Comment by mkangia** [comment]
Ran on staging, prod and ICDS with a setup release and then `migrate_multi`

confirmed partitions for the index.

**Comment by mkangia** [comment]
Ignoring the label error. Not sure why it is there.

**Pull request merged**
