### PR TITLE
OPM beneficiary registration fix

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue @esoergel

### CODE REVIEW

**Comment by czue** [comment]
can you link the context for this change?

**Comment by lwyszomi** [comment]
@czue 
http://manage.dimagi.com/default.asp?187634#1056625

**Comment by czue** [comment]
sorry to be annoying, but if the calculation is supposed to be going back 6 months can you explain why we're changing it to 7? guessing it makes sense, I just forget the context for this

**Comment by lwyszomi** [comment]
@czue 

for example we want 6 months before October. In method ```get_months_before``` https://github.com/dimagi/commcare-hq/blob/master/custom/opm/beneficiary.py#L380 
We subtract 6 months but in the end we add one month (first of next month). Then 10 (October) - 6 (Months) = 4 (April) and +1 we have 5 (May). [May, June, July, August, September, October] equals 6 months.
But in calculation we want 6 months before October without October.

**Comment by czue** [comment]
i see, thanks. and can you confirm this is unique to birth registration and the logic doesn't apply to the other indicators that look back 3 or 6 months?

**Comment by lwyszomi** [comment]
@czue Probably we should ask Anushree how we should calculate other indicators which look back.

**Pull request merged**
