### PR TITLE
don't serialize DB during test setup

### PR DESCRIPTION
**Pull request by snopoke**
This should speed up our tests (if it works)

@NoahCarnahan

### CODE REVIEW

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
@dimagi/team-commcare-hq you should add this to your localsettings as well

**Comment by czue** [comment]
nice

**Comment by TylerSheffels** [comment]
@snopoke Is this something that should go in `dev_settings.py`?

**Comment by snopoke** [comment]
@TylerSheffels It can't really since the DB settings get overridden by localsettings unless we change the way we do DB settings.

**Comment by TylerSheffels** [comment]
@snopoke Makes sense, thanks.

**Comment by esoergel** [comment]
It could probably go in localsettings.example though

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/9462

On 7 December 2015 at 18:00, Ethan Soergel <notifications@github.com> wrote:

> It could probably go in localsettings.example though
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/9407#issuecomment-162566953>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Pull request merged**
