### PR TITLE
do not 500 when saving an app with show_user_registration set to True

### PR DESCRIPTION
**Pull request by nickpell**
fixes http://manage.dimagi.com/default.asp?156111#868393

fyi @dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by esoergel** [comment]
know if this'd be covered by app_manager tests?

**Comment by nickpell** [comment]
a search for ```show_user_registration``` and ```get_user_registration``` only brings up https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/tests/test_app_manager.py#L181, which does not cover this case because the problem is specific to saving the app, during which fields such as ```_id``` and ```_attachments``` are removed from the object

**Comment by dannyroberts** [comment]
@nickpell I'm late to the game, but thanks, and this looks good!

**Pull request merged**
