### PR TITLE
Add tornado for celery

### PR DESCRIPTION
**Pull request by gcapalbo**

### CODE REVIEW

**Comment by czue** [comment]
dang, thanks. had no idea this was a dependency

**Comment by snopoke** [comment]
The issue here is that the version of flower that we have in our requirements depends on an older version of tornado. If we upgrade flower then we can remove the tornado dependency completely:

https://github.com/mher/flower/blob/master/requirements/default.txt

This PR is on staging now and working: https://github.com/dimagi/commcare-hq/pull/8793

**Comment by benrudolph** [comment]
ah nice, makes sense

**Comment by gcapalbo** [comment]
@snopoke do you mean remove tornado completely, or just remove it from the hq dependencies list and let flower install it? It looks like it's still required for flower to run.

**Comment by snopoke** [comment]
Yes, remove it from our requirements list and allow flower to install it.
I've tried that locally (with the latest version of flower) and it works
fine.

On 28 October 2015 at 23:21, gcapalbo <notifications@github.com> wrote:

> @snopoke <https://github.com/snopoke> do you mean remove tornado
> completely, or just remove it from the hq dependencies list and let flower
> install it? It looks like it's still required for flower to run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/8798#issuecomment-151994014>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Pull request merged**
