### PR TITLE
command for showing approximate doc distribution

### PR DESCRIPTION
**Pull request by snopoke**
Prints out something like this:
```
FORMS
Total                | 120071891           

By DB
DB                   | # Docs              
-------------------- | --------------------
p1                   | 13105946            
p10                  | 10270245            
p2                   | 13928357            
p3                   | 13425595            
p4                   | 14150227            
p5                   | 13714681            
p6                   | 10486398            
p7                   | 9907212             
p8                   | 10269591            
p9                   | 10813639            

By Host
Host                 | # Docs              
-------------------- | --------------------
10.247.164.20        | 30663201            
10.247.164.21        | 41290503            
10.247.164.64        | 21083884            
10.247.164.66        | 27034303            

CASES
Total                | 133521829           

By DB
DB                   | # Docs              
-------------------- | --------------------
p1                   | 13573388            
p10                  | 12707140            
p2                   | 13353487            
p3                   | 13433509            
p4                   | 13408841            
p5                   | 13398235            
p6                   | 13385402            
p7                   | 13436594            
p8                   | 13392739            
p9                   | 13432494            

By Host
Host                 | # Docs              
-------------------- | --------------------
10.247.164.20        | 40214735            
10.247.164.21        | 40240585            
10.247.164.64        | 26139634            
10.247.164.66        | 26926875 
```

### CODE REVIEW

**Comment by emord** [comment]
(incoming scope creep) I don't think that this is easily done through django apis but it would be nice if we could also get the doc sizes. Different forms and cases have pretty different sizes but are likely distributed ok enough. Would be good to confirm that hypothesis.

Also might be nice to have a column with % of total forms in this table so it's a bit easier to see differences.

**Comment by snopoke** [comment]
@emord added percent column: ace413d
Not going to add db sizes now

**Review by emord — APPROVED** [review]
Oops should have approved earlier. 

Didn't expect you to add anything, just thinking out loud

**Comment by snopoke** [comment]
@emord no prob, the % idea was good and easy to add

**Pull request merged**
