### PR TITLE
fix prefilters with required context

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?239710

@dannyroberts / anyone

### CODE REVIEW

**Comment by dannyroberts** [comment]
👍 on ✅

**Comment by dannyroberts** [comment]
Although it might be literally impossible for adding `**kwargs` at the end of function definition's param list to break something, so feel free to merge earlier if you need to!

**Comment by czue** [comment]
haha funny point. this is actually blocking some UCR work on india so i'm going to merge and deploy. i promise to look for a :white_check_mark: and will follow up in the unlikely event that something goes wrong.

**Comment by czue** [comment]
haha, shoot tests didn't kick off before i deleted the branch. if any issues i'll fix.

**Pull request merged**
