### PR TITLE
Update breadcrumbs in app manager

### PR DESCRIPTION
**Pull request by orangejenny**
Move the module & form names in app builder into breadcrumbs, and link-ify all items in the breadcrumbs. The point is to let user flip back and forth between form view and vellum (as of https://github.com/dimagi/commcare-hq/pull/6770) while still keeping their attention in the main content area, instead of having to go back to the sidebar.

This was quick to do, so happy to revert it if people disagree that it's an improvement. @amsagoff , what do you think?

Module view
module view new

Form view
form view new

Vellum
vellum new

### CODE REVIEW

**Comment by orangejenny** [comment]
@TylerSheffels

**Comment by TylerSheffels** [comment]
Looks great to me, will wait for Amelia's weigh in to merge

**Comment by amsagoff** [comment]
down to try it - though I think we used to have that in the breadcrumbs and
I never saw anyone click it, so we removed to reduce clutter. Pro coupling
this change with analytics and seeing how many clicks we get on breadcrumbs
vs. sidebar

**Comment by orangejenny** [comment]
Added analytics - @NoahCarnahan / @nickpell does that commit look all right?

**Comment by nickpell** [comment]
looks good.

can you make sure https://docs.google.com/spreadsheets/d/1frMdFeznNcMAIyMW3pG3zes6mmY03UG67HyMUHXlb-s/edit#gid=0 gets updated?

**Comment by orangejenny** [comment]
@nickpell thanks, updated spreadsheet

**Comment by orangejenny** [comment]
added new commit to fix broken URL & add module to breadcrumbs. @TylerSheffels can you take another look?

**Pull request merged**
