### PR TITLE
remove ab test for new user signup

### PR DESCRIPTION
**Pull request by biyeun**
@orangejenny

### CODE REVIEW

**Comment by orangejenny** [comment]
Should analytics marked "old", like https://github.com/dimagi/commcare-hq/pull/12165/files#diff-6c952bee801ac765305477f33644a8b9R9, be deleted/updated?

Would be nice to rename `NewUserRegistrationView` to `UserRegistrationView`, but that doesn't need to block this PR.

**Comment by biyeun** [comment]
@orangejenny looks like that page might still be used by invited users?

**Comment by biyeun** [comment]
@orangejenny it looks like there's a fallback view to register a new domain (part of the old step by step process) if the user's domain is not confirmed / active

Might be worth looking into removing this process but I feel that should be a separate pr just to make sure it doesn't break anything. This at least we know works. :)

**Comment by orangejenny** [comment]
Makes sense. I didn't look closely at the analytics code, basically just noticed that the text said "old" and that won't make sense to someone who's unaware this test happened.

**Pull request closed without merging**
