### PR TITLE
Updated styles for .nav-pills

### PR DESCRIPTION
**Pull request by orangejenny**
Updated as per the last designs in zeplin.

before
screen shot 2019-01-08 at 2 25 35 pm

after
screen shot 2019-01-08 at 2 25 06 pm

Don't merge yet, going to leave this on staging for a few days.

fyi @dimagi/product 
@esoergel @biyeun

### CODE REVIEW

**Comment by orangejenny** [comment]
Realized overriding `.nav-pills` doesn't work well (it's meant to work with links, futzing with javascript turn it into a toggle instead is ugly), and I can't override the default `.btn-group` styles (because there are places where we genuinely use that as a set of actions, not as this kind of toggle), so I added a new class and applied it in all the places where it looked relevant. Noticeable user-facing changes:

Report / conditional alert button group filter:
screen shot 2019-01-08 at 5 15 21 pm

App form summary:
screen shot 2019-01-08 at 5 15 53 pm

App case summary:
screen shot 2019-01-08 at 5 16 23 pm

Custom data fields:
screen shot 2019-01-08 at 5 18 24 pm

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
...and now that this is no longer updating an existing class and therefore affecting unknown parts of HQ, it doesn't need to sit on staging. Will merge once tests pass.

**Comment by czue** [comment]
what is the deal with that ginormous recipients list? is there some guideline when using this widget is just too many buttons? it seems like something that might be better served by a select2 or something else (also i'm not even sure i know where that is in the UI)

this looks great though.

**Comment by orangejenny** [comment]
@czue Yeah, that would be better as a select2, the toggles get crazy after about 5 items. There's new guidance on this about to go out: https://github.com/dimagi/commcare-hq/pull/22913 

The screenshot is from [conditional alerts](https://www.commcarehq.org/a/bosco/messaging/conditional/add/) though that widget shows up in a couple of report filters, too (the ones that use `.report-filter-button-group`). I don't know offhand how many options the other usages have.

**Comment by czue** [comment]
oh wow. seeing this before your change is even more scary! hopefully fewer options... i've never seen anything like that in the reports UI.

style guide looks great!

**Pull request merged**
