### PR TITLE
EWS: Changed way of reassigning verified number

### PR DESCRIPTION
**Pull request by kkrampa**
@gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
looks good. are there any other places in the code that do this kind of thing (delete and then save again), or is this the only place?

**Comment by kkrampa** [comment]
Yes, only in ```_reassign_number``` method.

**Comment by gcapalbo** [comment]
ok, does it need to be updated in the ils code too?

**Comment by kkrampa** [comment]
Yeah, I will do it later

**Pull request merged**
