### PR TITLE
Update prelogin submodule

### PR DESCRIPTION
**Pull request by benrudolph**
@orangejenny updated prelogin submodule (used ci skip since the only change from the last update was that html change you just merged)
cc: @millerdev

### CODE REVIEW

**Comment by orangejenny** [comment]
hurrah for prelogin tests running :)

**Comment by czue** [comment]
do they run if you `[ci skip]`?

**Comment by benrudolph** [comment]
yeah they didn't run, but felt bad bursting the bubble 😞

**Comment by benrudolph** [comment]
(reasoning for putting ci skip in the commit in PR description)

**Comment by orangejenny** [comment]
aww, yeah, they didn't run...but they didn't need to, and they *could* have run if they were needed. good enough.

**Pull request merged**
