### PR TITLE
add markdown format to case details

### PR DESCRIPTION
**Pull request by nickpell**
screen shot 2018-01-11 at 11 08 42 am

@orangejenny @ctsims cc: @emord 

@sheelio Do you approve releasing this to all users?

### CODE REVIEW

**Comment by sheelio** [comment]
@nickpell 

We may want to confirm with @orangejenny and @ctsims , but we may want to release this as an Add On?  I'm assuming there are no known gaps or bugs with the feature that would affect projects that aren't eNikshay?

**Review by emord — APPROVED** [review]

**Comment by orangejenny** [comment]
This is a great idea.

Curious why it's limited to case detail? Bold, italic, etc. might be useful on case lists.

I'd be in favor of releasing to all users behind an add-on. There's a "mobile experience" category that this would fit into.

**Comment by nickpell** [comment]
> Curious why it's limited to case detail? Bold, italic, etc. might be useful on case lists.

@ctsims suspected that markdown isn't implemented for case lists, and I confirmed that's correct.

**Comment by orangejenny** [comment]
@nickpell Could you add some kind of test? Perhaps just adding a markdown column [here](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/tests/test_suite.py#L48)?

**Comment by nickpell** [comment]
> @nickpell Could you add some kind of test? Perhaps just adding a markdown column here?

I added another ```DetailColumn``` to the test you linked (see [commit](https://github.com/dimagi/commcare-hq/commit/e3cc47be221ec30ccf66c10b75a738f6b314d835)).  It passed on both this branch and master, which makes me think it doesn't add any additional test coverage.  Thoughts on whether this is useful?

@orangejenny

**Comment by orangejenny** [comment]
> It passed on both this branch and master, which makes me think it doesn't add any additional test coverage.

Yeah, that sounds right, leaving it off sounds fine.

Thought some more about this being an add-on and I don't have strong feelings either way, since it's already buried in a rather long dropdown list.

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
