### PR TITLE
[ICDS Dashboard] Added edd to delivery form

### PR DESCRIPTION
**Pull request by challabeehyv**

### CODE REVIEW

**Review by Rohit25negi — APPROVED** [review]
Looks good. Good to add the description in the PR .

**Comment by calellowitz** [comment]
@challabeehyv Can you explain more about the rationale for this change and the use case for this indicator? We already have EDD in the dashboard

**Review by calellowitz — CHANGES_REQUESTED** [review]
Marking as request changes, pending the response

**Comment by Rohit25negi** [comment]
> @challabeehyv Can you explain more about the rationale for this change and the use case for this indicator? We already have EDD in the dashboard

Hey, responding here, We are adding edd to this form Because there is an indicator in Bihar API which needs a case property of  CCS. But since there is no link between child and ccs. So It came out from GS team that this case property of ccs can be derived from EDD and EDD is present in delivery form. 
Since, This delivery form will anyway be used for the Bihar API. So it was most logical thing to find that indicator instead of looking into ccs case property.

API name: child/vaccine
Indicator name in Bihar API: Termdays

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
