### PR TITLE
delete performance_sms/by_domain view

### PR DESCRIPTION
**Pull request by nickpell**
@dannyroberts cc: @NoahCarnahan 

Requires small preindex in meta db

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
This is meta db, so preindex will be fast

**Comment by dannyroberts** [comment]
build looked kind of unrelated, restarted it in case it doesn't happen every time. Otherwise it's either someone else's branch or worth a deeper look

**Comment by nickpell** [comment]
:white_check_mark:

**Pull request merged**
