### PR TITLE
Better check for user permissions to update users groups

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/ICDS-1443

##### SUMMARY
There was an awesome improvement done last year where [the groups form was not accounted for](https://github.com/dimagi/commcare-hq/pull/23343/files#r430241379). This PR address that form.
Currently the view has checks on ability to edit/view commcare user but not for ability to edit/view groups.

##### RISK ASSESSMENT / QA PLAN
Will be requesting Kishan to do a sanity check on staging

##### PRODUCT DESCRIPTION
User facing changes when editing a mobile worker, user would
1. see the groups tab if they have access to "View groups"
2. edit the content under groups tab if they have access to "Edit groups"
Earlier they could see it if they had permission to view commcare users, irrespective of their permission to manage groups.
Also, added a nice message
`No groups are assigned to this user.`
 in case there are no groups when viewing the read only view.

@dimagi/product

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Looks great.

**Comment by orangejenny** [comment]
@biyeun @esoergel I noticed that `commcare_user_groups.html` is blocked if you don't have location access: https://github.com/dimagi/commcare-hq/blob/92d81b1cf1bc8bc7aba0bf8ca05fada606cd1526/corehq/apps/users/templates/users/partials/commcare_user_groups.html#L6-L13

Is that intentional? I didn't know groups and locations were related.

**Comment by mkangia** [comment]
oh good point @orangejenny 
I think it was like this earlier as well as seen [here](https://github.com/dimagi/commcare-hq/pull/23343/files#diff-89509e34f46e46e625e82cda1f08413bR52) but ya curious to know why so.
fyi @dimagi/product

**Comment by esoergel** [comment]
Looks like this was [added](https://github.com/dimagi/commcare-hq/pull/8019) by Ethan Fromfiveyearsago - shame he's not around any more to ask.

> ... blocked if you don't have location access

Actually it's only if your project `needs_to_downgrade_locations` - that is, you have users assigned to locations, but you no longer have access to locations.  I suspect the reason this bubbles up on this page is because locations and groups are both used for case sharing, but they don't play well together (can't assign to more than one case sharing entity), so you need to unassign your users from locations before we let you start assigning them to groups.  There's some context in [the ticket from that change](http://manage.dimagi.com/default.asp?180156).

**Comment by orangejenny** [comment]
@esoergel That makes sense, thanks for digging.

I remember Ethan Fromfiveyearsago, he was a good guy.

**Comment by mkangia** [comment]
Tickets on fogbugz, we have come so far!

> I remember Ethan Fromfiveyearsago, he was a good guy.

Shame that I missed meeting him but i believe you @orangejenny

**Comment by mkangia** [comment]
thanks for the review and good chat on this PR @orangejenny @esoergel 
Turns out things are actually as expected by product but can be communicated better which, if needed would be a new PR, so closing this one out.

**Pull request closed without merging**
