### PR TITLE
option to compare doc counts on all domains

### PR DESCRIPTION
**Pull request by sravfeyn**
For auditing forms missing in ES.

@Rohit25negi 

https://dimagi-dev.atlassian.net/browse/HI-719

### CODE REVIEW

**Comment by sravfeyn** [comment]
@snopoke we are thinking to run this for all domains on prod in the background to hunt the extent of forms missing in ES. Does this ring any alarms for you?

**Comment by snopoke** [comment]
As long as it's run off peak. One concern is that it would run longer than a single off peak period.

**Comment by sravfeyn** [comment]
What's the offpeak for prod?

**Comment by snopoke** [comment]
Can check DD to find peak / off peak

**Comment by sravfeyn** [comment]
Closing this out, since support doesn't need this anymore.

**Pull request closed without merging**
