### PR TITLE
Get latest application build

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @esoergel see: https://github.com/dimagi/commcare-hq/pull/9790/files

### CODE REVIEW

**Comment by wpride** [comment]
:stud:

**Comment by czue** [comment]
:+1: when tests pass

**Comment by czue** [comment]
seems like it might be worth breaking that function up down the road - it feels a little "god-like"

**Comment by benrudolph** [comment]
agreed

**Comment by esoergel** [comment]
Oh crap, my B.  Thanks Ben!  @czue I definitely agree - that's part of the reason I split out the db hits, I imagine most instances want to just get the latest build or the latest star.

**Pull request merged**
