### PR TITLE
added icds-staging

### PR DESCRIPTION
**Pull request by shyamkumarlchauhan**
https://dimagi-dev.atlassian.net/browse/IIO-527

##### SUMMARY
Adding icds-staging environment for the UCR

### CODE REVIEW

**Comment by mkangia** [comment]
@shyamkumarlchauhan we would need to add them to [reports](https://github.com/dimagi/commcare-hq/tree/af349991cd8b8aada1bfdf7e81fb51c71bae76f3/custom/icds_reports/ucr/reports) as well, these are just data sources.

**Comment by shyamkumarlchauhan** [comment]
> @shyamkumarlchauhan we would need to add them to [reports](https://github.com/dimagi/commcare-hq/tree/af349991cd8b8aada1bfdf7e81fb51c71bae76f3/custom/icds_reports/ucr/reports) as well, these are just data sources.

Added them to reports as well

**Comment by sravfeyn** [comment]
The build failed due to a syntax error somewhere, may be a comma is missing or is extra.

**Comment by shyamkumarlchauhan** [comment]
> The build failed due to a syntax error somewhere, may be a comma is missing or is extra.

Fixed syntax error

**Review by sravfeyn — APPROVED** [review]

**Pull request merged**
