### PR TITLE
Changes in HQ to ensure tests pass with couch 3

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Summary

https://dimagi-dev.atlassian.net/browse/SAAS-11674

Updated `hq-compose.yml` to check if tests pass with CouchDB 3.
Presently I have created a docker image in my own docker registry to test out stuff. HQ was running fine with this docker image on my local setup. Creating this PR to check for tests.
## Safety Assurance

- [ ] Risk label is set correctly
- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [ ] If QA is part of the safety story, the "Awaiting QA" label is used
- [ ] I am certain that this PR will not introduce a regression for the reasons below

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by AmitPhulera** [comment]
Hey @dannyroberts, 
The tests are failing with the official image of couch 3.1.1. Can you look into it when you have some time?

**Comment by dannyroberts** [comment]
Hi @AmitPhulera what's the status on this. I see you got the tests passing a while ago, but then I wasn't sure if this is intended to be merged right now, or if some piece of it is intended to be split out and merged now, and other parts of it merged later when we're close to actually upgrading? Ideally we would merge any backwards compatible code changes that make our code run on both couchdb 2 and couchdb 3 in right now so that the flip itself is just an infrastructure/config change with no corresponding code change necessary.

**Comment by AmitPhulera** [comment]
Hey @dannyroberts,

I have raised a different PR https://github.com/dimagi/commcare-hq/pull/29099 for the same. We have asked devs to volunteer to work with couch 3 on their local systems. But I am not sure how many people are doing it.
We have not merged https://github.com/dimagi/commcare-hq/pull/29099 this because after that both the couch db versions will run on the local machine which would use up some resources on local dev machines as pointed out by @millerdev  https://github.com/dimagi/commcare-hq/pull/29099#pullrequestreview-583763806 

Do you have any suggestions on how we could speed things up on this?

**Comment by AmitPhulera** [comment]
Closing this out as it PR was just to ensure that we have tests running fine on couch3.

**Pull request closed without merging**
