### PR TITLE
Switch Submissions By Form Report to use FormData

### PR DESCRIPTION
**Pull request by esoergel**
This removes one of our most egregious sources of couch queries.
Previously, this report was hitting the db for every `(user, xmlns, app_id)` combination.  On a domain I happened to have locally, this amounted to several minutes of load time and around 7000 db calls.

This is now one (big) postgres call:

``` SQL
SELECT count(*) AS count_1, sofabed_formdata.xmlns, sofabed_formdata.user_id,
    sofabed_formdata.app_id FROM sofabed_formdata
WHERE sofabed_formdata.domain = :domain_1
AND sofabed_formdata.received_on >= :received_on_1
AND sofabed_formdata.received_on < :received_on_2
AND sofabed_formdata.user_id IN (:user_id_1, :user_id_2)
AND sofabed_formdata.xmlns IN (:xmlns1, :xmlns2)
GROUP BY sofabed_formdata.xmlns, sofabed_formdata.user_id, sofabed_formdata.app_id
```

@nickpell

As far as assuring consistency, I wrote some tests on the query itself, and ran the report locally against a whole bunch of forms.  To compare, I put an `assert couch == sql` in there while testing, to catch any places where they disagreed.  That's how I found the timezones issue.

### CODE REVIEW

**Comment by esoergel** [comment]
@dimagi/product FYI This should show dramatic performance improvements on the Submissions By Form report.

**Comment by czue** [comment]
this is great! out of curiosity was there a reason you went with sqlalchemy as opposed to just writing a [query in django](https://docs.djangoproject.com/en/1.8/topics/db/sql/)?

**Comment by snopoke** [comment]
One other point to note is that once we go to a partitioned database we won't be able to run queries like that.

**Comment by esoergel** [comment]
Ugh, I didn't realize the Django ORM could do this - I read through that page on aggregations, and didn't see anything about grouping by multiple fields (and all of their examples look up things from a related model, rather than counting rows).  Some googling I did also pointed me to several places saying this was explicitly more complex than django intended to allow, suggesting using the `raw` method.  In retrospect, I think I might've been confusing "group-by multiple" and "multiple group-bys".

I'll redo that part in Django.

**Comment by esoergel** [comment]
Okay, I rewrote using the django ORM.  Here's what that query looks like:
```sql
SELECT "sofabed_formdata"."xmlns", "sofabed_formdata"."user_id", "sofabed_formdata"."app_id",
    COUNT("sofabed_formdata"."instance_id") AS "count"
FROM "sofabed_formdata"
WHERE ("sofabed_formdata"."domain" = opm
AND "sofabed_formdata"."time_end" < 2015-09-25 18:30:00+00:00
AND "sofabed_formdata"."time_end" >= 2015-09-18 18:30:00+00:00
AND "sofabed_formdata"."xmlns" IN (<forms omitted for clarity>))
GROUP BY "sofabed_formdata"."xmlns", "sofabed_formdata"."user_id", "sofabed_formdata"."app_id"
```
Looks basically the same, so I think we're good to go (once I finish testing and push, that is)

**Comment by esoergel** [comment]
I rewrote the dbaccessor function, but didn't have to touch the tests or the code - encapsulation FTW!

**Comment by czue** [comment]
> I rewrote the dbaccessor function, but didn't have to touch the tests or the report code - encapsulation FTW!

:dancer:

**Comment by czue** [comment]
here's hoping nothing goes wrong! :tada: :beers: :pray:

**Pull request merged**
