### PR TITLE
[ICDS Dashboard] Fix More than 100% clean drinking water

### PR DESCRIPTION
**Pull request by sudh-kvantum**
[Link](https://dimagi-dev.atlassian.net/browse/ICDS-1134) to issue was reported.
##### SUMMARY
In the current aggregation, the first date in the six month window (while clean drinking water values being calculated) was skipping out and hence the denominator was not accurate with the percentage findings so made changes to include.

### CODE REVIEW

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
Test case failure looks real.
Also can you add a test case to verify that changed code is working fine now and including the boundary date

**Comment by sudh-kvantum** [comment]
Sure. I try to add one test case for this purpose.

**Comment by sudh-kvantum** [comment]
Updated infrastructure_v2.csv with changes on timend and received_on column so that corner case can be included hence 1st date in six month window now included and supporting changes in the code. I tested this and test_clean_water is passing with changes in code along with infrastructure_v2.csv

**Review by Rohit25negi — APPROVED** [review]
Looks good thanks

**Pull request merged**
