### PR TITLE
Do not allow users to clear choices in new cloudcare

### PR DESCRIPTION
**Pull request by benrudolph**
@ctsims buddy @emord this removes the Clear Choices button from appearing in new cloudcare

### CODE REVIEW

**Review by emord — APPROVED** [review]
Assuming product signed off on it?

**Comment by benrudolph** [comment]
@amsagoff did, but will ping product: @dimagi/product

**Comment by benrudolph** [comment]
assuming no response means OK. will merge once tests complete. easy to revert if anyone has an issue with it

**Comment by amsagoff** [comment]
Sorry, dont know how I missed this. All good though.

**Pull request merged**
