### PR TITLE
use select 2 instead of combobox 

### PR DESCRIPTION
**Pull request by biyeun**
combobox was an old custom b2 plugin

@millerdev

### CODE REVIEW

**Comment by benrudolph** [comment]
@orangejenny is this the combobox error you were referring to?

**Comment by orangejenny** [comment]
yep. is it possible to get rid of bootstrap-combobox.js, or are we still using it elsewhere?

**Comment by orangejenny** [comment]
alternatively, could/should we do a ticket (sol develo / interrupt) to remove combobox altogether, if select2 is always preferable?

**Comment by millerdev** [comment]
:+1:

I like @orangejenny's idea to remove bootstrap-combobox.js. This is good to merge if that's too complicated to do on this PR.

**Comment by biyeun** [comment]
I don't think we need to remove combobox, as b3 pages will not use it anyway and bootstrap 2 pages will phase out.

**Comment by biyeun** [comment]
select2 will be used during the migration to replace combobox

**Comment by orangejenny** [comment]
Cool, removing combobox can be a quick post-bootstrap migration task, then.

**Pull request merged**
