### PR TITLE
Check if secure_session should be unset

### PR DESCRIPTION
**Pull request by nospame**
## Technical Summary
[USH-2577](https://dimagi-dev.atlassian.net/browse/USH-2577?atlOrigin=eyJpIjoiYWY1MzEwYjBiYjIxNGVkYmI4YzFlOWYyZDNjOGIwY2EiLCJwIjoiaiJ9)
Currently, `TimeoutMiddleware` only checks if `secure_session` is newly enabled with `change_to_secure_session`, not if newly disabled, so the inactivity timeout remains active until the user starts a new session, even after deselected and saved. 

This PR extracts the logic used to set `secure_session` into a function that checks:
1. Whether the current domain uses `secure_session`
2. If the user belongs to any domains that use `secure_session`
3. If the user has visited any domains during this session that they are not a member of, but which use `secure_session`

If any of these criteria are met, `secure_session` is True. This leaves `use_secure_session` slightly overzealous, as a domain meeting criteria 3 might later turn `secure_session` off, but this is a compromise to avoid storing the name of each domain a user has visited and checking the `secure` status of each.

A previous version of this PR added a more basic check `change_from_secure_session` for whether `secure_session` should be disabled, based on the same criteria as `change_to_secure_session` but with inverted logic, however this led to situations where `secure_session` effectively ignored criteria 3, above, and was disabled too soon.

### Safety story
`secure_session` will remain True if _any_ of the 3 criteria above are met.

This change also leaves in place security-oriented actions from `change_to_secure_session`, now under the criteria `not secure_session and use_secure_session` to check if a user should be immediately logged out based on the length of their current session. 

### Automated test coverage
Covered by existing automated tests.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

[USH-2577]: https://dimagi-dev.atlassian.net/browse/USH-2577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[USH-2577]: https://dimagi-dev.atlassian.net/browse/USH-2577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
This looks right to me, nice find. It's a little surprising that it took so long to notice the setting getting correctly turned off, but it's plausible, since making sure it's **on** when appropriate is a much bigger deal.

The relevant domains here aren't the domains the user has visited in the current session, they're the current domain plus the domains the user is a member of. It's worth updating the description for future people looking quickly at this PR.

**Comment by orangejenny** [comment]
Test failures do look real, though:
`FAIL: corehq.apps.hqwebapp.session_details_endpoint.tests:SessionDetailsViewTest.test_secure_sessions`
and
`FAIL: corehq.apps.hqwebapp.tests.test_timeout_middleware:TestTimeout.test_secure`

**Comment by nospame** [comment]
> This looks right to me, nice find. It's a little surprising that it took so long to notice the setting getting correctly turned off, but it's plausible, since making sure it's **on** when appropriate is a much bigger deal.
> 
> The relevant domains here aren't the domains the user has visited in the current session, they're the current domain plus the domains the user is a member of. It's worth updating the description for future people looking quickly at this PR.

Good callout -- reading into it more it's actually the `secure_session = secure_session ...` that tries to account for domains the user has visited in the current session. I'm realizing maybe why this is structured how it is has to do with users (superusers) moving between domains they are not a member of. 

As-is, I think if someone visits a `secure_session` domain, it remains enabled for their entire session regardless of other domains they visit, which seems like intended behavior. But if a check is added to turn `secure_session` _off_ based on the current domain setting, it's not necessarily respecting the `secure_session` setting of previously visited domains. I'm not sure if there's a good way around this.

**Comment by nospame** [comment]
> Test failures do look real, though: `FAIL: corehq.apps.hqwebapp.session_details_endpoint.tests:SessionDetailsViewTest.test_secure_sessions` and `FAIL: corehq.apps.hqwebapp.tests.test_timeout_middleware:TestTimeout.test_secure`

For sure, at least one of these is because I need to set `secure_session` `True` or `False` if it's not already part of the session, rather than leaving it `None`.

**Comment by nospame** [comment]
> The only solution I've come up with would be storing the domains a user has visited in the session - probably just a subset of them, likely excluding domains they are a member of (because those are already getting checked), as well as those without `secure_session` enabled. Would that make sense at all? @orangejenny

Thinking through it further, I don't think the check needs to be perfect (which might require keeping track of which domains a user has visited). It seems like it's probably enough to store a boolean for if someone has visited a domain that: they are not a member of, and that has `secure_sessions` enabled - which if True, would err on the side of keeping `secure_session` enabled for the length of the current session.

**Review by orangejenny — APPROVED** [review]
This looks good to me, and the code is nicely readable - important when dealing with complex booleans, especially since this is security-related code.

One last thought after re-reading the description:

> the inactivity timeout remains active until the user starts a new session, even after deselected and saved

Seeing this phrasing made me realize: we could address this whole issue by logging the user out when they deselect secure sessions, right? That would be somewhat obnoxious, but we already do it when turning the setting on, and this isn't a setting that changes often. If it would dramatically simplify the code here, it's worth considering.

**Comment by orangejenny** [comment]
(flagged this PR as high risk because it changes `TimeoutMiddleware`)

**Comment by nospame** [comment]
> Seeing this phrasing made me realize: we could address this whole issue by logging the user out when they deselect secure sessions, right? That would be somewhat obnoxious, but we already do it when turning the setting on, and this isn't a setting that changes often. If it would dramatically simplify the code here, it's worth considering.

I don't know that it would _dramatically_ simplify anything, most of the checks would probably stay in place, but it would be easier to use a version of `change_from...` and `change_to...` logic. It could be annoying/confusing to be logged out after changing an option to be _less_ secure (or seemingly randomly, to other affected users), but I'm not sure how big an issue that is, and like you mentioned, it's not a setting that gets changed often.

**Comment by orangejenny** [comment]
@nospame that all makes sense to me, I defer to you on final decision

**Review by AddisonDunn — APPROVED** [review]

**Pull request merged**
