### PR TITLE
Remove unreferenced code

### PR DESCRIPTION
**Pull request by esoergel**
`_extract_domains` and `TargetSyncConfig` were only used in `DomainSyncConfig` which isn't referenced anywhere.
@nickpell

### CODE REVIEW

**Comment by esoergel** [comment]
@czue it looks like you wrote most of the code in here (well, 4 years ago, anyways).  Do you know if this module is in use anymore?

**Comment by czue** [comment]
nice find! i followed the rabbit a little bit further https://github.com/dimagi/commcare-hq/pull/9017

:rage1:

**Comment by czue** [comment]
this is good to go from my side.

**Comment by esoergel** [comment]
Not sure how ansible would handle settings out of sync, so I figure to be on the safe side, we should merge https://github.com/dimagi/commcarehq-ansible/pull/258 at the same time as this PR.

**Comment by czue** [comment]
It should be fine since having those settings around is not going to cause any problems

**Pull request merged**
