### PR TITLE
Edit description of mobile report

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?183613 

Best read commit by commit

@orangejenny 

screen shot 2015-10-14 at 1 48 45 pm

### CODE REVIEW

**Comment by orangejenny** [comment]
Code looks reasonable. Curious, where in the UI does the user specify translations of the description?

**Comment by nickpell** [comment]
The text provided by the user in the report module config page is used for the language chosen at the languages sidebar in the app builder

**Comment by nickpell** [comment]
test failure looks unrelated

**Comment by nickpell** [comment]
rebased on new master, wait for tests

**Pull request merged**
