### PR TITLE
Skip sending devicelogs for repeaters

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts @czue http://manage.dimagi.com/default.asp?218216

cc: @NoahCarnahan

### CODE REVIEW

**Comment by dannyroberts** [comment]
:+1:

**Comment by dannyroberts** [comment]
(just waiting on tests)

**Comment by czue** [comment]
good detective work @dannyroberts!

**Comment by czue** [comment]
do/can we purge the records if they have no payload on retry? would be good to get these out of the reports and queue

**Comment by benrudolph** [comment]
yeah good point, i think it's easiest to purge them in the `fire` task. if it can't find the payload it should just mark it as deleted

**Comment by czue** [comment]
yeah that sounds good

**Comment by benrudolph** [comment]
actually this already happens: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/repeaters/models.py#L536

**Comment by czue** [comment]
even better!

**Comment by benrudolph** [comment]
like finding 20:moneybag: in your :jeans:

**Pull request merged**
