### PR TITLE
Have proper pages shown

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride this fixes an issue where it would show every page of users in the paginate toolbar. this is an issue when there are 100k users

screen shot 2017-04-03 at 10 55 01 pm

cc: @proteusvacuum @dannyroberts

### CODE REVIEW

**Comment by dannyroberts** [comment]
Is the screenshot of what it did before or what it does now? (And what did it do before/does it do now?)

**Comment by benrudolph** [comment]
screen shot is of what it used to do, now it will just show the pages based on the the end and start values returned from pagesToShow

**Comment by benrudolph** [comment]
screen shot 2017-04-13 at 5 26 25 pm

**Comment by dannyroberts** [comment]
gotcha. Nice!

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
