### PR TITLE
Added filtering by Group in reports

### PR DESCRIPTION
**Pull request by lwyszomi**
@NoahCarnahan

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
Looks good, but the test failure looks real. I think there are two "owner_id" columns in `custom/pnlppgi/resources/site_reporting_rates.json`

**Comment by lwyszomi** [comment]
@NoahCarnahan I fixed test. Also I added zones in report. Please don't merge, we must update hierarchy before merge.

**Comment by NoahCarnahan** [comment]
Thanks. I'm not sure which regions should be nested under which zones, so I'm asking our field team to update that now.

**Comment by lwyszomi** [comment]
@NoahCarnahan Nynke send informations in email: Nord (St Louis, Matam, Louga); Centre (Kaolack, Diourbel); Ouest (Dakar); Sud Sud Est (Tamba, Kedougou, Ziguinchor).

**Comment by NoahCarnahan** [comment]
Oh right, thanks

**Comment by NoahCarnahan** [comment]
Hierarchy has been updated, so merging now.

**Pull request merged**
