### PR TITLE
allow running migrations test in isolation

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
Used by ICDS repo build: https://github.com/dimagi/commcare-icds/pull/161

## Safety Assurance
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by mkangia** [comment]
"allow running migrations test in isolation"
Hey @snopoke , can you expand on this please?

**Comment by snopoke** [comment]
@mkangia if you set the `TEST_MIGRATIONS` environment variable when running the build it will run the script that checks if there are any missing migrations.

**Comment by mkangia** [comment]
thanks @snopoke . I assumed I would find `TEST_MIGRATIONS` in HQ code somewhere but I didn't. Is it a django thing?

**Comment by snopoke** [comment]
@mkangia this PR is adding it. It's purely reference to an optional environment variable that can be used when running the build.

**Comment by mkangia** [comment]
thank you @snopoke . I just checked `scripts/test-django-migrations.sh` (which i should have earlier) and I understand this better.

**Pull request merged**
