### PR TITLE
Multiple choice field in custom fields

### PR DESCRIPTION
**Pull request by kkrampa**
@esoergel I need multiple choice field for ewsghana (http://manage.dimagi.com/default.asp?174048#965908). If you think that this shouldn't be added to custom fields module in corehq I can close this PR and find another solution.

Probably easiest to read commit by commit.

### CODE REVIEW

**Comment by kkrampa** [comment]
Only this commit touches core code: https://github.com/lwyszomi/commcare-hq/commit/a17ea3995f3ea479540acb4759e835b39cd06c78

**Comment by esoergel** [comment]
I'm okay with this as long as it's implemented in a productized way, and is hidden from the UI until we can put it through the proper product pipeline.

**Comment by esoergel** [comment]
@amsagoff This PR adds the ability to make a custom data field (like user data) multiselect.  Is that something we want to use/productize?

**Comment by amsagoff** [comment]
Definitely. Can release under a "product path" feature flag for now. Is
there a screenshot of what this looks like (to specify that it's multiple
answer)?

**Comment by czue** [comment]
@amsagoff there's already a screenshot here

**Comment by kkrampa** [comment]
Changes in corehq moved to: https://github.com/dimagi/commcare-hq/pull/7291
I will make separate PR for ewsghana changes.

**Comment by amsagoff** [comment]
Cool, thanks. Let's release as product path and will soon review with Biyeun, think we can release with small UI changes

**Pull request closed without merging**
