### PR TITLE
Cast provided amounts to integer

### PR DESCRIPTION
**Pull request by esoergel**
They are sent down as strings of floats, like `u'400.0'`.  This is some duck typing to see if we can interpret it as an integer

https://sentry.io/dimagi/commcarehq/issues/289037330/

@proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
@esoergel I updated it to match the spec document which says that we will accept a "decimal amount". If you have more up to date documentation than what we sent them, I'm interested in seeing it. I'm referencing the final "DataDump_Definitions" document sent on August 10.

**Comment by proteusvacuum** [comment]
I'm merging this as it should be mostly backwards-compatible with your change if my change isn't right, and I want to tell them to retrigger everything they've sent so far. @esoergel

**Comment by esoergel** [comment]
> @esoergel I updated it to match the spec document which says that we will accept a "decimal amount". If you have more up to date documentation than what we sent them, I'm interested in seeing it. I'm referencing the final "DataDump_Definitions" document sent on August 10.

This requirement was changed to be an integer during a call on Sept 1st.  We initially said "integer rounded up (ceil)", then that was later amended to be a standard rounded integer in an email on Sept 4th.

Sounds like we need to have a live copy of this document that's kept up-to-date - I will work on that.

**Comment by esoergel** [comment]
Actually let's go ahead and assume this is canon: https://docs.google.com/document/d/1HodLa86TiSrWKu3js9moSmIkUg5kwK7uma_qRThuzrw/edit
It still needs some updates, but we should go with that, since it's the most recent doc we've agreed on.

**Pull request merged**
