### PR TITLE
Add Mia the deploy bot

### PR DESCRIPTION
**Pull request by benrudolph**
@TylerSheffels or anyone

### CODE REVIEW

**Comment by benrudolph** [comment]
just need to add the settings to ansible

**Comment by orangejenny** [comment]
nice

**Comment by proteusvacuum** [comment]
:see_no_evil:

**Comment by czue** [comment]
cool stuff! why "mia"?

**Comment by czue** [comment]
assume no test coverage, so merging and giving travis a break

**Comment by snopoke** [comment]
how does this work?

**Comment by benrudolph** [comment]
i looked briefly into slack integration on friday and it literally takes 5 seconds. they have a cool approach where the apikey is essentially embedded in the url. so all you have to do is post to that url and it'll forward it to the chat. pretty sweet!

mia was my high school love who ripped my heart out and stamped it on the floor. so i'm living vicariously through a slack bot. it's a cold world out there

**Comment by czue** [comment]
:boot: :heart: :cry:

**Comment by snopoke** [comment]
right, I see. I thought this was a bot that could deploy for you

**Comment by benrudolph** [comment]
i wish... need chief then mia could probably pretty easily do that

**Pull request merged**
