### PR TITLE
[B5] Split domain app

### PR DESCRIPTION
**Pull request by orangejenny**
## Technical Summary
This splits the domain app into B3 and B5 versions. There are ~50 views in this app, so it'll be migrated in multiple PRs.

Almost all commits are automated.

### Safety story
The B5 code doesn't go live at this point, the only risk is of a file reference not getting renamed properly.

This process has been run numerous times on various apps. But this is an unusually large app and has some non-standard directory structures in the login templates, a high-risk area.

### Automated test coverage

The migration tool has test coverage. The domain views probably have some coverage in QA's selenium smoke tests.

### QA Plan

Requesting QA smoke test the login workflows: https://dimagi.atlassian.net/browse/QA-7239

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by orangejenny** [comment]
Added some commits to split the login_and_password pages, which are in a non-standard directory structure.

**Review by millerdev — APPROVED** [review]
Looked at some, but not all, _Bootstrap 5 Migration - initial auto-migration ..._ commits. All other commits were reviewed.

**Comment by orangejenny** [comment]
Added a commit to migrate the login pages to webpack so they also go through QA. Most of the rest of this app is getting migrated to webpack in https://github.com/dimagi/commcare-hq/pull/35390

**Review by millerdev — APPROVED** [review]

**Comment by orangejenny** [comment]
Merged master now that most of this app is on webpack (see https://github.com/dimagi/commcare-hq/pull/35390). Because the bootstrap migration tool didn't support the `js_entry_b3` => `js_entry` at the time I did this migration (that support has since been added in https://github.com/dimagi/commcare-hq/pull/35391), I manually updated a bunch of B5 templates that should use `js_entry` in [889c625](https://github.com/dimagi/commcare-hq/pull/35349/commits/889c625b8fd96322c99cdbcfe262d7410b7cd025).

**Review by biyeun — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Pull request merged**
