### PR TITLE
App Code with <ul>

### PR DESCRIPTION
**Pull request by kaapstorm**
This PR is an alternative to #10052. Context over there.

With app code:
app_code_li

Without app code:
app_code_li_falsey

@amsagoff @biyeun cc @wspride

### CODE REVIEW

**Comment by amsagoff** [comment]
I see what you're going for here, and I agree the spec mockup looks awkward...

@orangejenny thoughts?

In both versions, though, it's hard to tell that these are OR options rather than AND. I'm playing around with how we could show that a bit better, what do you think of something like  this:
 
image

**Comment by orangejenny** [comment]
What if we did three options across the top? So, instead of "Online Install" and "Offline Install", we had something like "Scan Barcode", "Enter App Code", and "Offline Install". This would be good if there's a definite preferred/majority option. If barcode vs app code is more of a user preference and the potential extra click is a concern, maybe we could store whatever method that user last used, and then default that tab to open?

I agree that neither of the current options are quite clear enough clear that it's A or B, not A and B.

Unrelated, this would be a

**Comment by orangejenny** [comment]
Another alternative, we could do two images side-by-side: on one side have the bar code (stop making it a click away), and on the other have a screenshot of the mobile install screen where they'll enter the app code (I don't think we have any other screenshots in HQ, but this could be a place it'd be really helpful for first-time users and not burdensome for experienced users).

**Comment by amsagoff** [comment]
In order to keep scope within the level originally planned and to make sure this gets out the door for mobile release, I propose this compromise for now:
image


The layout of the two install options is very similar to what we currently have, but it is still a definite improvement. @orangejenny your screenshot side by idea sounds really cool, I'll explore that as a separate spec

**Comment by kaapstorm** [comment]
I also like your side-by-side images idea @orangejenny -- it removes the ambiguity, simplifies the UI, and shows the barcode up front, which makes perfect sense. 

I've added "Or" in the other PR. Closing this one.

**Pull request closed without merging**
