### PR TITLE
Speed up app_manager tests

### PR DESCRIPTION
**Pull request by dannyroberts**
reduce size of zips in app_manager/tests/jadjar by removing a bunch of the files that aren't needed

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
locally, this takes a good 2 minutes+ of the app manager tests

**Comment by czue** [comment]
good stuff!

**Pull request merged**
