### PR TITLE
Use different HTTP error codes

### PR DESCRIPTION
**Pull request by proteusvacuum**
**Use different HTTP error codes**
We are going to be adding translations to the error messages

@phillipm  @kaapstorm cc: @dannyroberts

### CODE REVIEW

**Comment by proteusvacuum** [comment]
```py
if case_type == 'coffee':
    return HttpResponse("I'm a teapot", status=418)
```

**Comment by kaapstorm** [comment]
(We could call it an Easter Egg. :smiling_imp: )

**Comment by benrudolph** [comment]
fyi this breaks the test claim endpoints tests, but those tests currently aren't being run. working to fix them here:https://github.com/dimagi/commcare-hq/pull/11633/commits/f7bd6bdcdd5fe4cbcd539176db72c25534c21823 (no action required, but more as a heads up in case you change functionality again)

**Comment by proteusvacuum** [comment]
Hah, I thought it might... but then they passed and I forgot about it.

**Pull request merged**
