### PR TITLE
Fix continuous delete

### PR DESCRIPTION
**Pull request by dannyroberts**
Ran into this on fixture migration. It was a live bug during users migration as well, but it went unnoticed because apparently people delete fixtures (by the thousands) WAY more than they delete users.

(I wouldn't be surprised if exactly 0 users were deleted while the continuous migration was running but before the flip, since when I checked --stats the doc counts matched perfectly; if a few were then they got undeleted on the flip. I think it's a non-issue at this point since the workaround is for them to re-delete a user.)

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue

**Comment by dannyroberts** [comment]
@czue ran the doctypemigration tests locally. Funny enough there were like 3 tests for different aspects of this deleting, but none of them caught this because I was assuming a slightly different change format (I assumed the _rev would be the rev of the doc before deleting, rather than some theoretical "next" rev that never ends up anywhere and is useless for copying to the other db, resulting in a doc conflict.) Probably don't need to wait for tests.

**Comment by czue** [comment]
I don't think there's any way in the UI to delete users or groups from the DB so this makes sense

**Comment by dannyroberts** [comment]
oh right it's all soft deletes. Anyway, thanks!

**Pull request merged**
