### PR TITLE
Docs: Remove legacy sphinx_rtd_theme configuration

### PR DESCRIPTION
**Pull request by benjaoming**
Follow-up for @gherceg re: https://github.com/readthedocs/sphinx_rtd_theme/issues/1434#issuecomment-1472649619

### CODE REVIEW

**Comment by gherceg** [comment]
Thanks for the contribution @benjaoming! I tested this locally with `sphinxcontrib-jquery==4.1`, and unfortunately still experience the "ReferenceError: jQuery is not defined" at this point for every page:
```
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
```

**Comment by benjaoming** [comment]
@gherceg I haven't tested this, but you'll need to do a "make clean" and rebuild. LMK if you already did that or it still doesn't work?

**Comment by benjaoming** [comment]
In case it still doesn't work, another option is to add `sphinx_rtd_theme` as an extension as well, as described here: https://sphinx-rtd-theme.readthedocs.io/en/stable/changelog.html#known-issues

To my knowledge, it should be enough to unset `html_theme_path`, but it would be nice to figure out the issue since there's some other people reporting the same issue.

**Comment by gherceg** [comment]
Yeah after cleaning and rebuilding, was still hitting the jquery issue, but adding `sphinx_rtd_theme` as an extension did the trick! The search issue was resolved without removing the legacy "html_theme_path", though there were a lot more javascript errors with that legacy path still in the `conf.py`. For that reason, I created https://github.com/dimagi/commcare-hq/pull/32761 that updates `sphinxcontrib-jquery==4.1` _and_ adds `sphinx_rtd_theme` as an extension in conf.py, which keeps this PR focused on removing the legacy config.

Thanks again for your help @benjaoming and let me know if there is any other info I can provide.

**Comment by benjaoming** [comment]
Thanks for testing and giving feedback @gherceg :+1:

**Comment by gherceg** [comment]
@benjaoming was planning to merge this PR as is if you want to re-open it!

**Comment by benjaoming** [comment]
thanks :pray: :blush: 

glad that you got it working, also glad that sphinxcontrib-jquery isn't broken, it took a few failed test balloons to get it working and figure out all the edge cases :)

**Review by millerdev — APPROVED** [review]

**Pull request merged**
