### PR TITLE
switch default behavior of copy_group_data to include cases owned by users

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by czue** [comment]
easy, no test covereage

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by snopoke** [comment]
closed?

**Comment by czue** [comment]
https://github.com/dimagi/commcare-hq/pull/5481

**Comment by czue** [comment]
sorry, fixed one thing and force pushed so had to make a new PR

**Pull request closed without merging**
