### PR TITLE
Account for undefined variables before calling split.(',')

### PR DESCRIPTION
**Pull request by pr33thi**
This should fix the [broken travis tests](https://travis-ci.org/dimagi/commcare-hq/jobs/444925502).

@jmtroth0 
code buddy @sravfeyn

### CODE REVIEW

**Review by jmtroth0 — APPROVED** [review]

**Review by orangejenny — APPROVED** [review]
Did tests not run on the original PR?

**Comment by pr33thi** [comment]
@orangejenny yeah, apparently they were somehow never kicked off on the original PR

**Comment by esoergel** [comment]
Github had webooks downtime yesterday, so travis tests didn't kick off

**Comment by orangejenny** [comment]
ah, forgot about that

**Comment by esoergel** [comment]
Gonna go ahead and merge this, but we should still keep an eye on [the build](https://travis-ci.org/dimagi/commcare-hq/builds/445214264)

**Comment by esoergel** [comment]
:tada:

**Pull request merged**
