### PR TITLE
delete no longer used couch views

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by benrudolph** [comment]
:hammer:

**Comment by czue** [comment]
fyi, failing any complaints my plan is to merge this after deploy on friday and kick off a preindex. @dannyroberts @snopoke @emord

**Comment by snopoke** [comment]
👍

On 4 November 2015 at 10:17, Cory Zue <notifications@github.com> wrote:

> fyi, failing any complaints my plan is to merge this after deploy on
> friday and kick off a preindex. @dannyroberts
> <https://github.com/dannyroberts> @snopoke <https://github.com/snopoke>
> @emord <https://github.com/emord>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/8830#issuecomment-153630559>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
:+1: :yellow_heart:

**Comment by dannyroberts** [comment]
:goberserk:

**Comment by czue** [comment]
Party time

**Pull request merged**
