### PR TITLE
Removed DeviceLogRequest.device_id

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
https://dimagi-dev.atlassian.net/browse/ICDS-1299

https://github.com/dimagi/commcare-hq/pull/26814/ should have removed the column altogether instead of just making it nullable.

This leaves device id as part of the heartbeat request and only removes it from the log request object. @shubham1g5 let me know if that's not right.

### CODE REVIEW

**Review by mkangia — COMMENTED** [review]
I was thinking of the reason why this was added at the first place,
a username can be used to login from multiple devices and hence they should be separate logs?

**Comment by shubham1g5** [comment]
@mkangia yeah that was the exact reasoning though Android not stops us from accessing the deviceId from phone and therefore we don't have a mechanism to handle multiple devices at this point.

**Comment by mkangia** [comment]
ah yes, thanks @shubham1g5 
So any new device logs won't have device id ever and hence we want to just club all pending and new pending device log requests together.

wishful thinking: `PendingDeviceLogRequest` would have been a better if i am understanding the purpose of that model correctly.

**Comment by shubham1g5** [comment]
> So any new device logs won't have device id ever and hence we want to just club all pending and new pending device log requests together.

@mkangia This feature has not been used before for a real user in production so all log requests will be new one.  Even for old device log requests, the heartbeat won't contain the device id the logd were requested for and therefore HQ won't be able to match the device Id in the old log requests against device id in heartbeat requests. So it makes sense to remove it for all the device log requests and not consider it as an attribute to get a device match.

**Comment by mkangia** [comment]
I see, thanks @shubham1g5

**Comment by snopoke** [comment]
@shubham1g5 is there a plan to find a replacement for device ID? If not there are a number of other places that this will impact which we'll need to plan for.

**Review by snopoke — APPROVED** [review]

**Comment by shubham1g5** [comment]
@snopoke In place of the device id, Mobile will be now sending an `instance id` that's generated by CC on a fresh install. Though this is not tied in to any of the device attributes and is a completely virtual id and will differ across 2 fresh installations on the same device. So `instance_id` is not going to be an ideal replacement but we don't have a better choice at this point.

**Comment by snopoke** [comment]
@shubham1g5 thanks for the follow up. That seems totally fine and should work for all the use cases I can think of. Are we going to have a new metadata property called `instance_id` or are we going to reuse `device_id`?

**Comment by shubham1g5** [comment]
@snopoke We are going to reuse `device_id` to minimize the impact of the change, So any `device_id` value from CC 2.48 onwards will actually represent the instance id for the installation.

**Comment by snopoke** [comment]
ok, perfect. Thanks

**Pull request merged**
