### PR TITLE
ICDS: Update Datasources for Tableau

### PR DESCRIPTION
**Pull request by sheelio**

### CODE REVIEW

**Comment by czue** [comment]
this looks fun.

image:dizzy_face:

**Comment by czue** [comment]
haha @sheelio just passed @proteusvacuum and @millerdev in terms of [lines of code added](https://github.com/dimagi/commcare-hq/graphs/contributors?from=2009-03-08&to=2016-08-16&type=a).

**Comment by benrudolph** [comment]
holy moly! 18,000 lines of ucr config!

**Comment by sheelio** [comment]
Its not my proudest moment :) 

(I think I could cut these significantly back if i added helper expressions or allowed named expressions to reference each other).

**Pull request merged**
