### PR TITLE
remove south_migrations folders

### PR DESCRIPTION
**Pull request by emord**
don't see any reason we need these here

cc: @czue

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
image
might be a new record

**Comment by czue** [comment]
(assume i don't need to review closely) 

:+1: when tests pass

**Comment by nickpell** [comment]
I think we need to add back datamigrations including
https://github.com/dimagi/commcare-hq/blob/b1ef1d62cdd2384313f82ca62870ff364c6a4f64/corehq/apps/smsbillables/south_migrations/0002_bootstrap.py
and
https://github.com/dimagi/commcare-hq/blob/b1ef1d62cdd2384313f82ca62870ff364c6a4f64/corehq/apps/accounting/south_migrations/0013_roles_and_plans_migration_p1m2.py
to make sure new instances of HQ have smsbillable and accounting defaults set.
@emord Does that sound right?

**Pull request merged**
