### PR TITLE
Pollsensor on revalidate

### PR DESCRIPTION
**Pull request by orangejenny**
HQ side for https://github.com/dimagi/commcare-android/pull/1380

@dannyroberts 
cc @benrudolph @phillipm

### CODE REVIEW

**Comment by orangejenny** [comment]
@phillipm does merging this depend on the mobile code being merged & released?

**Comment by benrudolph** [comment]
👍 when you're ready

**Comment by phillipm** [comment]
Merging this now will have the effect that when a form is completed, it will re-launch GPS polling for another 5 mins or until it has gotten down to 5 meters of accuracy. It will also update the form model with the GPS location updates after the form has completed, but I don't think that should mess with anything.

So I guess we should wait until 2.29 is out before merging this. And at that point we should be comfortable with the fact that auto-capture on older devices will use more battery... Maybe there is a way to only make this change to apps targeting 2.29 and up?

**Comment by orangejenny** [comment]
Unless it's a lot more battery, I'm inclined to not use different code for 2.29+ versus older versions.

**Comment by benrudolph** [comment]
we have a way to require minimum versions here: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/feature_support.py which the ApplicationBase model inherits which makes it fairly easy to require minimum versions. don't know if that helps at all but thought i'd mention

**Comment by orangejenny** [comment]
yeah, it's a small change, bit I'd still err on the side of not adding complexity

**Comment by benrudolph** [comment]
👍

**Comment by dannyroberts** [comment]
I should have chimed in 10 days ago, but to me we're either ok merging this now (because it doesn't really negatively affect anyone using <2.29) or we want to make this change only on 2.29+ (because it *does* negatively affect anyone using <2.29). Unless we believe that adoption of a new version is so fast that it doesn't really matter (which I don't think we do), it seems like it would be one or the other. I'm personally ok with adding that level of complexity to the code in the name of preventing noticeable behavior changes/degradation in people's apps. The simple system @benrudolph mentioned is relatively self-documenting and gives us a central place to go and look for tech-debt we can remove once a version is officially not supported. @phillipm do you have a sense of which side of the line this falls on? (Adversely affects <2.29 vs. does not adversely affect <2.29?) I'm also open to alternative reasoning that says I'm drawing too hard a line here or creating a false dichotomy. To me if there's a chance that this causes problems for people, baking the distinction in now prevents a fair amount of support burden/service degradation later.

**Comment by phillipm** [comment]
It is very hard to tell how negative of an effect this will have on users running pre-2.29 CommCare. If they are in a place where they can get an accurate GPS lock, it will have almost no effect on their battery life. In NW Nepal, this wasn't the case, and GPS polled for the full 5 mins, so this change on a pre-2.29 device would cause another 5mins of polling. And of course, if users never re-deploy/update their app, they won't even get this update.

**Comment by phillipm** [comment]
Also, if doing these version dependent changes on HQ is too much work. I can look into other ways to solve this problem on mobile. The way I approached on mobile was the least effort and made the most sense in my head at the time, but that was before I realized the negative effects on battery this would have on pre-2.29 versions of CommCare

**Comment by orangejenny** [comment]
It's definitely easier to do version-dependent code on HQ than on mobile. I might have been being too obstinate about not wanting more branching code in HQ, but it really isn't *much* code. I'll add it in.

**Comment by dannyroberts** [comment]
Thanks @orangejenny. I also want to say thanks for considering complexity—you're definitely right that adding branching logic to account for one more use-case is not always worth the technical debt it incurs. In this case I think our strong commitment to consistent user-experience over time and backwards compatibility of non-deprecated versions outweighs the relatively minor change to what's (fortunately) a low-touch area of the code, so I think in the end that's the right decision. Thanks everyone!

**Comment by orangejenny** [comment]
Updated to limit to 2.29+

**Comment by dannyroberts** [comment]
Now that it's limited to 2.29+, I think we can merge now as soon as you're confident in the logic.

**Comment by orangejenny** [comment]
oops, yes, meant to take the label off. this is ready.

**Comment by dannyroberts** [comment]
🎉

**Pull request merged**
