### PR TITLE
EWS Reports: several small improvements

### PR DESCRIPTION
**Pull request by agrzywinski**
http://manage.dimagi.com/default.asp?169151
http://manage.dimagi.com/default.asp?169148
http://manage.dimagi.com/default.asp?169061
http://manage.dimagi.com/default.asp?169062
http://manage.dimagi.com/default.asp?169063
http://manage.dimagi.com/default.asp?169057

### CODE REVIEW

**Comment by czue** [comment]
(not mergeable. also, please ping someone else if you need these merged urgently - i'm offline most of today and tomorrow)

**Comment by agrzywinski** [comment]
@czue @snopoke

**Comment by snopoke** [comment]
:white_check_mark: once build passes

**Comment by benrudolph** [comment]
talk about 2 birds with one stone

**Pull request merged**
