### PR TITLE
hotfix a last-minute optimization

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@esoergel, would love to get this in quickly! cc: @proteusvacuum @orangejenny, @czue FYI

I'm kind of plagued by not having written tests for this portion of the code, even though it's somewhat imminently testable. I should go do that.

**Comment by orangejenny** [comment]
no test coverage

**Comment by proteusvacuum** [comment]
curious what the performance gain of this is?
I did a `timeit` on `len(set[1,2,3,4])) <= 0` and `set([1,2,3,4]) <= 0` and the results were almost identical.

```py
In [11]: %%timeit
   ....: len(set([1,2,3,4])) <= 0
   ....:
The slowest run took 6.56 times longer than the fastest. This could mean that an intermediate result is being cached
1000000 loops, best of 3: 472 ns per loop

In [12]: %%timeit
   ....: set([1,2,3,4]) <= 0
   ....:
The slowest run took 8.01 times longer than the fastest. This could mean that an intermediate result is being cached
1000000 loops, best of 3: 506 ns per loop
```

**Comment by czue** [comment]
@proteusvacuum I think the optimization was in a prior commit and the hotfix makes the code actually run again

**Comment by proteusvacuum** [comment]
Ah, thanks.

**Comment by dannyroberts** [comment]
:+1:

**Pull request merged**
