### PR TITLE
Bucket restore times instead of histogram

### PR DESCRIPTION
**Pull request by millerdev**
Follow-up on https://github.com/dimagi/commcare-hq/pull/17030

Clayton had the idea of putting counts in time buckets, which is much more useful and flexible for aggregate stats. Any aggregations we were doing in the past were likely close to meaningless because of the number of tags sent to the histogram call.

@snopoke @benrudolph @ctsims

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
:boot: :construction:

**Comment by benrudolph** [comment]
would love to offline at some point about this. read the previous PR and still not quite sure why we couldn't use the histogram type if we just used it for the `avg`. we've recently switched a  lot of metrics to histogram, are you concerned that those could be wrong as well?

**Comment by millerdev** [comment]
> we've recently switched a lot of metrics to histogram, are you concerned that those could be wrong as well?

Yes. Did you read https://help.datadoghq.com/hc/en-us/articles/211545826-Why-histogram-stats-are-all-the-same-inaccurate-Characteristics-of-Datadog-histograms-? Unless you're graphing per-host (non-aggregated) stats, and likely not using tags, I believe datadog's histogram is not very useful. Especially see the section in that article under **Consequence 2: ...**

**Comment by benrudolph** [comment]
wow, ok missed that article. that definitely seems like our metrics our off then. though the `avg` could be close to correct if we are load balancing correctly and every host seems the same number of metrics per 10 second interval... though that seems unlikely

**Pull request merged**
