### PR TITLE
Small debugger button

### PR DESCRIPTION
**Pull request by benrudolph**
@biyeun @orangejenny this makes the debugger button smaller and less intrusive for app preview. what do you think? i also think this is way less intrusive when you use one question per screen. there's always loads of whitespace at the bottom.

veolmahtic

cc: @emord

### CODE REVIEW

**Comment by emord** [comment]
Would it make sense to have that icon on the bottom right? In your gif it looks like it would be less likely to interfere with question labels on the right than left

**Comment by benrudolph** [comment]
👍

**Comment by benrudolph** [comment]
moved to the right side, but got rid of the hack to make sure the bar wasn't the full with of the screen. i think it looks fine on old cloudcare:

screen shot 2017-01-11 at 6 51 36 pm

this is preview:

screen shot 2017-01-11 at 6 52 13 pm

**Comment by biyeun** [comment]
good move to put it on the bottom right! NICE suggestion @emord :+1:

**Review by biyeun — APPROVED** [review]

**Review by emord — APPROVED** [review]

**Pull request merged**
