### PR TITLE
Migrate intrahealth reports to b3

### PR DESCRIPTION
**Pull request by biyeun**
@kkrampa cc @gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
looks good to me. @kkrampa @lwyszomi looks like you worked on these reports - could one of you just test these updates out locally to make sure all looks good?

**Comment by kkrampa** [comment]
@gcapalbo There are a couple of problems. I made PR to this branch which fixes most of problems. (#11131)

**Comment by biyeun** [comment]
merged @kkrampa's changes from the other branch. Kamil, feel free to give a last :+1: here and then we can get this merged

**Comment by kkrampa** [comment]
@biyeun Reports look good on my local machine.

**Pull request merged**
