### PR TITLE
name 'metrics_counter' is not defined

### PR DESCRIPTION
**Pull request by esoergel**
This popped up on #ush-500-to-0
https://sentry.io/organizations/dimagi/issues/3088472236/
from https://github.com/dimagi/commcare-hq/pull/31232

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Why did stickler not catch that on the original PR?

**Comment by calellowitz** [comment]
ugh

**Comment by esoergel** [comment]
> Why did stickler not catch that on the original PR?

Not sure - pylint and flake8 both catch the error for me locally

**Comment by calellowitz** [comment]
> > Why did stickler not catch that on the original PR?
> 
> Not sure - pylint and flake8 both catch the error for me locally

Maybe it didn't run? Of the 10 passed checks I see in that PR, I do not see stickler.

**Comment by esoergel** [comment]
Huh, nor on this one

**Pull request merged**
