### PR TITLE
indicate when media paths are set and allow unsetting

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?221122
@amsagoff @biyeun @orangejenny 

I opted for putting the 'remove' button on the main control row to also cover the case where the media path is the default but no media has been uploaded. See images below:
#### Media with custom path

image
#### Media with default path but no matching binary

image

### CODE REVIEW

**Comment by orangejenny** [comment]
> the case where the media path is the default but no media has been uploaded

Not quite following this - what happens if no media has been uploaded, the media path is default, and you click remove?

**Comment by snopoke** [comment]
@orangejenny it unsets the path in `app.module[x].media_yyy`

**Comment by orangejenny** [comment]
Sorry, not phrased well. What's the reason that a user would decide to click on that button?

**Comment by snopoke** [comment]
@orangejenny see http://manage.dimagi.com/default.asp?222332

**Comment by amsagoff** [comment]
This makes sense to me, thanks simon

**Comment by orangejenny** [comment]
Ohhhh, I see, thanks! It's a little weird that the remove button will be visible on brand new apps, but I don't have a better way.

**Comment by amsagoff** [comment]
From my understanding, the remove button is only visible if there's a mm
file uploaded or you have set a custom path. Otherwise, the remove button
should not be there. Let me know if that's not the case.

**Comment by orangejenny** [comment]
ugh, sorry, i misread...this whole PR. rather, i didn't read enough of the surrounding code. ignore my comments.

**Pull request merged**
