### PR TITLE
adding missing accounting migration

### PR DESCRIPTION
**Pull request by calellowitz**
this migration was supposed to be a part of https://github.com/dimagi/commcare-hq/pull/9379
I am not sure how it was left out but I also do not think it affects functionality. It changes one of the choices in the char field but since django does not actually enforce those choices it is not really important. Nonetheless, it seems more correct to have this migration included in the repository.
@nickpell @gcapalbo

### CODE REVIEW

**Comment by nickpell** [comment]
looks good pending tests

**Comment by gcapalbo** [comment]
not a blocker, but it's usually nice to give the migration file a descriptive name to make it easier to understand why it's there

**Comment by calellowitz** [comment]
@gcapalbo fixed

**Comment by gcapalbo** [comment]
:+1: just going to wait on tests

**Pull request merged**
