### PR TITLE
Fix abt data source

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Data type was wrong
@emord / anyone

### CODE REVIEW

**Comment by emord** [comment]
:+1: on :white_check_mark:

**Comment by NoahCarnahan** [comment]
✅

**Comment by emord** [comment]
FYI I think your local gitconfig might not match your github profile. https://github.com/dimagi/commcare-hq/pull/12495/commits/8a0776513df44d428971d402007b0939382d2227 doesn't seem to associate to your account

**Comment by NoahCarnahan** [comment]
Thanks for the heads up. Likely related to my hard drive failure and the only semi-restored state of my machine at the moment :(

**Pull request merged**
