### PR TITLE
error message if formplayer is offline

### PR DESCRIPTION
**Pull request by zandre-eng**
## Technical Summary

Link to ticket [here](https://dimagi-dev.atlassian.net/browse/SC-2481)

This aims at providing better information to users when the formplayer service is offline. When a user tries to update the app version, and formplayer is down, then they will be given an appropriate error message as follows:

Screenshot from 2023-03-08 15-50-23

## Feature Flag

None.

### Safety story

Small UI change, have done local testing.

### Automated test coverage

N/A.

### QA Plan

N/A.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by Charl1996 — APPROVED** [review]
:+1:

**Comment by kaapstorm** [comment]
This is going to make an extra call to formplayer, and it will return information that we will know as soon as we try to validate the form. `formplayer_api.validate_form()` will know that it is unable to connect:
```python
def validate_form(form_xml):
    try:
        response = requests.post(...)
    except RequestException as e:
        notify_exception(None, "Error calling Formplayer form validation endpoint")
        raise FormplayerAPIException(e)
```

Instead of making the extra call every time we want to validate a form, we can bubble the information we want up to the caller:
```python
def validate_form(form_xml):
    try:
        response = requests.post(...)
    except RequestException as e:
        notify_exception(None, "Error calling Formplayer form validation endpoint")
        raise FormplayerAPIException(e) from e  # <--
```

Then you can catch it in the caller using [`Exception.__cause__`](https://legacy.python.org/dev/peps/pep-3134/):

```python
    try:
        validation_results = formplayer_api.validate_form(source)
    except FormplayerAPIException as err:
        if isinstance(err.__cause__, RequestException):
            raise XFormValidationFailed("Unable to connect to Formplayer")
        else:
            raise XFormValidationFailed("Unable to validate form")
```

**Comment by zandre-eng** [comment]
@kaapstorm This is a good idea, and would help with slightly simplifying the unit test as well since the `check_formplayer` function would not have to be mocked out anymore. I have committed a change as per your suggestion. :+1:

**Review by kaapstorm — APPROVED** [review]
:+1: Thank you

**Pull request merged**
