### PR TITLE
Kill cross project reports privilege

### PR DESCRIPTION
**Pull request by nickpell**
Looks like all usages of `can_see_organization` were removed in https://github.com/dimagi/commcare-hq/pull/8739, so this removes the setting and the corresponding privilege.

@dannyroberts @biyeun

### CODE REVIEW

**Comment by dannyroberts** [comment]
nice! Will wait for tests just in case

**Comment by czue** [comment]
good stuff. is there also something that could/should get cleaned in the DB? (doesn't seem blocking either way)

**Comment by czue** [comment]
:skull:

**Comment by nickpell** [comment]
@czue 
> is there also something that could/should get cleaned in the DB?

https://github.com/dimagi/commcare-hq/pull/10173

**Comment by czue** [comment]
:+1:

**Pull request merged**
