### PR TITLE
Migrate m4change reports to b3

### PR DESCRIPTION
**Pull request by biyeun**
@emord did you back stop on these? if so, want to take a quick peek that it's working alright?

screen shot 2016-03-03 at 7 33 38 pm

### CODE REVIEW

**Comment by czue** [comment]
@kkrampa @lwyszomi do either of you guys have a setup to test this?

**Comment by lwyszomi** [comment]
@czue I think we have database for this on cloudant. I will download it and test these changes.

**Comment by czue** [comment]
that would be great, thanks!

**Comment by millerdev** [comment]
Reviewed (quickly) :+1:

**Comment by lwyszomi** [comment]
@czue @millerdev @biyeun 

In these reports:
- Facility ANC HMIS Report
- Facility L&D HMIS Report
- Facility Immunization HMIS Report
- Facility ALL HMIS Report
- Project Indicators Report
- Aggregate Facility Web HMIS Report
- mCCT Monthly Aggregate Report
we have some problems:
- in left menu we have wrong title style
- month and year filters are so wide that they take the whole line
- labels are too close to inputs

image

**Comment by lwyszomi** [comment]
@czue @biyeun @millerdev 

Sorry my mistake I didn't download changes before checking reports :)

**Comment by lwyszomi** [comment]
Now I checked with the changes :smile:  and I found one issue, very wide inputs in filter section (in all m4change reports)
example image:
image

**Comment by biyeun** [comment]
@lwyszomi <https://github.com/lwyszomi> i'm not seeing that locally. did
you make sure that static files + filters were not being cached? If it was
cached then it'll show up like that

On Fri, Mar 4, 2016 at 9:57 AM, Łukasz Wyszomirski <notifications@github.com

**Comment by biyeun** [comment]
@lwyszomi <https://github.com/lwyszomi> specifically referring to case
search. Other fields are fine

**Comment by biyeun** [comment]
@czue updated and fixed the problem with the Case Search filter
screen shot 2016-03-09 at 7 16 55 pm

**Pull request merged**
