### PR TITLE
Updated js docs on naming conventions

### PR DESCRIPTION
**Pull request by orangejenny**
As discussed in today's retro.

### CODE REVIEW

**Comment by orangejenny** [comment]
killing build, forgot to `ci skip`

**Review by biyeun — APPROVED** [review]

**Comment by czue** [comment]
Hungarian notation FTW!

**Comment by millerdev** [comment]
I thought it had been established that Hungarian notation was an anti-pattern...

**Comment by orangejenny** [comment]
@millerdev I agree but I don't have a better idea. Prefixing `$` or `_` are already their own conventions.

**Comment by czue** [comment]
I think this particular convention and the issue it addresses fits squarely into this [relevant Joel article](https://www.joelonsoftware.com/2005/05/11/making-wrong-code-look-wrong/)

**Comment by orangejenny** [comment]
@czue Thanks for the article. I've been mulling over this problem for a while and have been averse to dealing with it via naming convention, but that article makes a good case for this kind of change.

**Comment by millerdev** [comment]
Haha! I had scanned this PR yesterday and avoided voicing my discomfort at that time, but then @czue [lured me into it](https://github.com/dimagi/commcare-hq/pull/25394#issuecomment-532547079)... while I usually despise Hungarian notation it may be the best option for observables. I don't have a better idea for that one, so carry on.

We could debate the `$jqueryVar` convention, which I find very ugly most of the time, but it's probably not worth it.

**Pull request merged**
