### PR TITLE
Remove m4change custom reports from settings.py

### PR DESCRIPTION
**Pull request by dannyroberts**
part of https://dimagi-dev.atlassian.net/browse/SAAS-10957

##### SUMMARY
Removes m4change custom reports, without actually deleting the code yet. (We want to delete the code and disconnecting it is a first step.)

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
🎉

**Comment by orangejenny** [comment]
🍰

**Comment by orangejenny** [comment]
Will the whole m4change directory be deleted? I care because they have a custom couch model.

**Comment by dannyroberts** [comment]
@orangejenny it can be, I just dropped it after this little push. If you're inspired you can go ahead and remove, though if not I'll come back and remove it in the next couple weeks

**Comment by orangejenny** [comment]
@dannyroberts Sweet, if I have a slow day I'll pick it up and if not you can grab it 🙂

**Comment by sravfeyn** [comment]
@orangejenny Ethan is cleaning up some of it here https://github.com/dimagi/commcare-hq/pull/28398

**Comment by esoergel** [comment]
Yeah, it would be nice to kill - anyone know of a documentation about the process of killing a couch model?  There's also a fluff model, does that require any special incantation to clean up?

I'm guessing we just manually delete those documents from the server?

**Comment by orangejenny** [comment]
I don't know about the fluff model. For couch documents we haven't been actually deleting them, but we add the doc type to [deleteable_doc_types.py](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cleanup/deletable_doc_types.py). I've been figuring SaaS will decide when we'd get a cost or performance benefit from deleting them.

**Pull request merged**
