### PR TITLE
[INTRAHEALTH] change path to user id in fluffs

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @esoergel 

I changed the way in which we collect user_id from the form. Please let me know if you have any questions. Link to the case: https://manage.dimagi.com/default.asp?266528#1429919

Regards,
Łukasz

### CODE REVIEW

**Comment by fyniac** [comment]
@nickpell when you deploy today, can you please deploy the PNA server as well. Please remember to update the log

**Comment by lwyszomi** [comment]
Hi @nickpell 

After deploy, we need to rebuild all intrahealth fluffs. Could you do this also.

Thanks,
Łukasz

**Comment by nickpell** [comment]
@lwyszomi what command should I run to do this?

**Comment by lwyszomi** [comment]
@nickpell 

I think you can run ```manage.py ptop_reset_checkpoint IntraHealthFormFluffPillow```

**Comment by emord** [comment]
>I think you can run manage.py ptop_reset_checkpoint IntraHealthFormFluffPillow

I don't think that this will work since we have migrated to PNA. I think you'll need to use ptop_reindexer_fluff but i've never actuallyused that command before

**Comment by nickpell** [comment]
Good point @emord

**Comment by nickpell** [comment]
Looks like the pillow is not configured for reindexing:

```
./manage.py ptop_reindexer_fluff IntraHealthFormFluffPillow
2017-12-06 13:11:52,583 INFO AXES: BEGIN LOG
CommandError: Reindexer not configured for topic: form-sql
```

**Pull request merged**
