### PR TITLE
quickcache Document mixin

### PR DESCRIPTION
**Pull request by esoergel**
Throwing up here to run tests

### CODE REVIEW

**Comment by esoergel** [comment]
Hey, tests passed!  @dannyroberts

**Comment by dannyroberts** [comment]
Want to put this up on staging for a while first?

**Comment by esoergel** [comment]
probably wise.

**Comment by esoergel** [comment]
@dannyroberts This has been on staging for about 2 weeks, and I haven't heard anything about it (which admittedly doesn't say much).  Got any suggestions for more due-diligence or are you happy with this as-is?

**Comment by dannyroberts** [comment]
That seems totally fine to me!

**Pull request merged**
