### PR TITLE
Remove mock dependency 

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

**Reviewing by commit should make it slightly easier**

As of Python 3.3, mock is a standard part of python under the `unittest` package. We have a mixture of code that references the built-in `unittest` version of mock, and code that references the 3rd party version of `mock`. This was mostly find and replace, with a few spots that used the syntax `from unittest.mock import mock` which I don't believe is correct, so I modified those slightly. I didn't run anything locally since there are so many files it seemed most efficient to just run via github actions. 

The django-digest submodule imports mock as well, so I plan to create a PR to address that. I'm not sure if that submodule relies on HQ importing the `mock` library, but if so, we can make sure that PR is merged before merging this. 

UPDATE: as noted below, it looks like django-digest depends on HQ's requirements. PR to remove mock dependency from django-digest [here](https://github.com/dimagi/django-digest/pull/44).

I want to run `isort` on the modified files, but that results in lots of modifications that may cause conflicts/be unnecessary. And part of me thinks a better method would be to go app by app, and creating individual PRs for apps to minimize conflicts. This would also only be worth doing if the team is set on using isort and wants to maintain that import organization moving forward.

### Safety story

As mentioned below, we can be confident this is safe if all tests pass.
### Automated test coverage

This change _only_ impacts automated tests, so as long as tests still pass, it is safe.
### QA Plan

No QA necessary.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
That answers my question about django-digest.
Screen Shot 2021-11-11 at 4 56 06 PM

**Comment by gherceg** [comment]
django-digest PR: https://github.com/dimagi/django-digest/pull/44

**Comment by snopoke** [comment]
@gherceg this is great, it's been on my list for a while

**Review by millerdev — COMMENTED** [review]
:trophy: Thanks for doing this!

> go app by app [running isort], and creating individual PRs for apps to minimize conflicts

+1 for individual app PRs

> That answers my question about django-digest.

In case not obvious, the submodule will need to be updated after the django-digest PR is merged.

**Review by millerdev — APPROVED** [review]

**Comment by joxl** [comment]
:tada:

**Review by kaapstorm — APPROVED** [review]
Awesome

**Pull request merged**
