### PR TITLE
Change 'Get Free Trial' to 'Request Custom Trial'

### PR DESCRIPTION
**Pull request by biyeun**
## Product Description
We are changing the "Get Free Trial" text here:
Screen Shot 2022-08-09 at 6 43 29 PM

To "Request Custom Trial" here:
Screen Shot 2022-08-09 at 6 43 14 PM

Here is the requesting ticket:
https://dimagi-dev.atlassian.net/browse/SAAS-13842

### Safety story
just a text change

### Automated test coverage
text only

### QA Plan
N/A

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by gherceg — COMMENTED** [review]
Disclaimer: not a UI expert

I appreciate that we want to convey our willingness to customize a solution for users, but worry that removing "free" from this text will result in fewer users taking advantage of this. My reaction was "is this trial no longer free?" despite reading the description of just a text change.

**Review by joxl — COMMENTED** [review]
My review here is really a review of the ticket and not this PR, but this seems to be the best forum for my concern at the moment, so I'll leave my feedback here.

I'm with @gherceg, I think removing "Free" could potentially dissuade interested parties and should remain as long as this trial is free.  The word "free" in big text accompanying a trial page (and most commonly, the button/link itself) is the defacto standard for SaaS products (e.g. [Datadog](https://www.datadoghq.com/free-datadog-trial/), [Salesforce](https://www.salesforce.com/ap/form/signup/freetrial-sales/), [Atlassian](https://www.atlassian.com/software/free), [Quickbooks](https://quickbooks.intuit.com/online/advanced/free-trial/), [Slack](https://slack.com/trials), [GitLab](https://about.gitlab.com/enterprise/), [Zendesk](https://www.zendesk.com/), just to name a few), and customers come to registration pages specifically looking for that word in bold advertising.

In regards to putting "Custom" on the button itself: to me this makes the trial sound clunky or complex. The fact that the product is "customizable" is a feature of the product, not a feature of the free trial. I would advocate for alternative wording elsewhere if the idea that "the trial is customizable" needs more fanfare, because I don't think the button is the correct place for that information.

**Comment by biyeun** [comment]
Hey all. This is coming direct from sales. The free text removal was 100% intentional.

**Review by gherceg — APPROVED** [review]
> This is coming direct from sales. The free text removal was 100% intentional.

Cool. In that case looks good. Out of curiosity, are we removing free trials? The JIRA ticket gave me the impression there was **not** any fundamental change to free trials.

**Comment by biyeun** [comment]
@gherceg let's keep internal conversation to the JIRA ticket. Thank you! :)

**Pull request merged**
