### PR TITLE
Fixed issue with properties in case xml api

### PR DESCRIPTION
**Pull request by lwyszomi**
@fyniac 
http://manage.dimagi.com/default.asp?140450#1306070

### CODE REVIEW

**Comment by fyniac** [comment]
@dannyroberts can you please review?

**Comment by dannyroberts** [comment]
@lwyszomi nice find! Small suggestion: could you use `include_case_on_closed=True` instead of just `True` so it was more obvious to someone reading it what the `True` stands for?

**Comment by lwyszomi** [comment]
@dannyroberts updated

**Comment by lwyszomi** [comment]
@dannyroberts bump

**Comment by dannyroberts** [comment]
Looks good!

**Pull request merged**
