### PR TITLE
[B3 Reports] Worker Monitoring

### PR DESCRIPTION
**Pull request by biyeun**
Touches the following reports:
screen shot 2016-01-21 at 4 34 03 pm

Some previews:
screen shot 2016-01-21 at 4 34 17 pm
screen shot 2016-01-21 at 4 34 33 pm
screen shot 2016-01-21 at 4 34 41 pm
screen shot 2016-01-21 at 4 34 52 pm
screen shot 2016-01-21 at 4 34 59 pm
screen shot 2016-01-21 at 4 35 05 pm

@dimagi/product 
@benrudolph @czue @orangejenny

### CODE REVIEW

**Comment by orangejenny** [comment]
looks good, waiting on tests

**Comment by orangejenny** [comment]
Tangentially, this PR reminds me we should have an official strategy/design for indicating required fields. Would be a good addition to consistency guidelines.

**Comment by amsagoff** [comment]
+1

**Comment by biyeun** [comment]
@orangejenny note QA flag

**Comment by czue** [comment]
wow, awesome and amazing how little code this takes!

**Comment by biyeun** [comment]
QA has completed on this

**Comment by biyeun** [comment]
@czue / @orangejenny / @benrudolph :white_check_mark: build ok and qa ok

**Pull request merged**
