### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by gcapalbo**
@orangejenny code review buddy
i think this might have just been a timing issue between https://github.com/dimagi/commcare-hq/pull/10418 and https://github.com/dimagi/commcare-hq/pull/10481

### CODE REVIEW

**Comment by millerdev** [comment]
:+1:
gtm on test pass

**Comment by gcapalbo** [comment]
(@benrudolph @esoergel @pnaw94 fyi)

**Comment by gcapalbo** [comment]
@esoergel @pnaw94 can one of you run this locally just to make sure it works as you were intending? it looks like the template referenced before doesn't exist anymore.

**Comment by NoahCarnahan** [comment]
Merging now because I accidentally deployed the bug this fixes

**Comment by benrudolph** [comment]
:golf:

**Pull request merged**
