### PR TITLE
Remove Itemset.wrap

### PR DESCRIPTION
**Pull request by orangejenny**
## Technical Summary
Branched off of https://github.com/dimagi/commcare-hq/pull/31129 - only the last commit is new.

Marked "don't merge" until 31129 is deployed.

## Feature Flag
Case claim

### Safety story
Minor dead code removal

### Automated test coverage

There are related tests for suite xml generation.

### QA Plan

Not requesting QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
👍🏻  on preemptively creating this PR to do the cleanup!

**Review by esoergel — APPROVED** [review]
Assuming this PR is to be rolled out after we believe 3rd party envs have also ran the migration, should this also delete the management command and make that migration a noop?  (ie `run_once_off_migration`)

**Comment by orangejenny** [comment]
@esoergel good point, added b0b5deca63b (the commit hash is marked TODO until https://github.com/dimagi/commcare-hq/pull/31143 is merged)

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
It's been six weeks since the script was run, so this is ready to go.

Added a couple of commits because I didn't actually delete the script previously.

**Review by esoergel — APPROVED** [review]

**Pull request merged**
