### PR TITLE
[Django 2] Surgically rearrange SQLInvitation db migrations

### PR DESCRIPTION
**Pull request by dannyroberts**
Replaces https://github.com/dimagi/commcare-hq/pull/27114

##### SUMMARY
0011 leaves SQLInvitation in a state that is illegal in Django 2,
but that Django 1 was silently accepting.
Originally we tried squashing the last four migrations
(https://github.com/dimagi/commcare-hq/pull/27114)
but there was then no reasonable way to sequence the
custom data migration part.

So instead we are surgically merging the 0011 back into
the original migration that created SQLInvitation
in a way that still leaves it workable for
the custom migration code which runs during 0010

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Review by orangejenny — APPROVED** [review]
🥇

**Comment by orangejenny** [comment]
Tests seem unhappy, though: `django.db.utils.ProgrammingError: multiple primary keys for table "users_invitation" are not allowed`

**Comment by dannyroberts** [comment]
OK the issue is that `AutoField` always means primary_key=True, apparently. Not sure what the way around it is. We may need to go back and make sure the migration works with this `id` field being an IntegerField with a default value of null afterall

**Comment by dannyroberts** [comment]
OK fixed, offlined with @orangejenny and we looked through the migration code and agreed nothing there relied on `id` being an auto-incrementing integer field (or even mentioned it at all), so I decide to push all changes to SQLInvitation into the first migration file, have the next run the data migration (as it already did) and leave the last two empty.

**Review by orangejenny — APPROVED** [review]

**Comment by dannyroberts** [comment]
Thank you @orangejenny for all your support on slack as I muddled my way through the different approaches until finally finding something that works well!

**Pull request merged**
