### PR TITLE
[ICDS Dashboard] wasting details

### PR DESCRIPTION
**Pull request by calellowitz**
https://dimagi-dev.atlassian.net/browse/ICDS-470

Best reviewed commit by commit. 
The first one reverts https://github.com/dimagi/commcare-hq/pull/24371
The second changes the logic to use the same metric of heigh measurement as other reports (specifically the stunting details page)

### CODE REVIEW

**Review by czue — APPROVED** [review]
(caveat that I didn't review the revert commit)

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
is this still live? @calellowitz 
Had left a couple questions.
also test failure looks real: https://travis-ci.org/dimagi/commcare-hq/jobs/582670055#L10057

**Comment by calellowitz** [comment]
Tests now passing, will merge as soon as @Rohit25negi approves

**Review by Rohit25negi — APPROVED** [review]
looks good. Thanks

**Pull request merged**
