### PR TITLE
Test get_form_ids_by_type with date params

### PR DESCRIPTION
**Pull request by esoergel**
These are the tests accompanying https://github.com/dimagi/commcare-hq/pull/18315
This passes locally, but I made a change to a widely-used test util, so I wanna see the full build pass.

### CODE REVIEW

**Comment by esoergel** [comment]
@proteusvacuum @calellowitz

**Comment by proteusvacuum** [comment]
kicked build

**Comment by esoergel** [comment]
Tests passed

**Review by proteusvacuum — APPROVED** [review]

**Comment by esoergel** [comment]
Weird, when I checked this earlier, tests had shown up as successful (Travis was green, not just the check mark).  Now it's pending - may be related to the Travis load issues.  Oh well, no urgency on this PR anyways

**Pull request merged**
