### PR TITLE
Dont force height on form notice

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?217493

@orangejenny 

screenshot from 2016-02-23 11-34-08

### CODE REVIEW

**Comment by orangejenny** [comment]
There are small screen height rules for `.form-notice-container` and `.form-notice-container-tall` a couple of rows down, for small screens, which also ought to be updated...and after that, there's no reason for `.form-notice-container-tall` to exist at all.

Do you know why these containers had explicit heights in the first place? If not, probably worth checking with @biyeun

**Comment by proteusvacuum** [comment]
Yeah, not sure why those were there, and it doesn't seem to have caused any issues when I removed them. Will defer to @biyeun, but I think this change should be OK.

**Comment by orangejenny** [comment]
Makes sense. You might as well remove `form-notice-container-tall` from the template, then this looks good to go.

**Comment by biyeun** [comment]
The explicit height is for the download in progress / filter blocking notification. You should make sure that all the filters are disabled and covered by this div while the download is in progress but the button is still accessible and you should try this across all the types of downloads (form, case, deid, multiple) I think you might find issues then.

@proteusvacuum (cc: @orangejenny )

**Comment by biyeun** [comment]
Btw, the height needs to be explicit on that container because `height:100%` on the child popup won't work otherwise

**Comment by proteusvacuum** [comment]
Thanks for the tip. Will test out all the different permutations.

**Comment by orangejenny** [comment]
> The explicit height is for...

Would be nice to add a comment to that effect.

**Comment by proteusvacuum** [comment]
hey, I tested all the different permutations I could think of and those that @biyeun suggested for different exports, and this change was positive in all of them. I'm happy with this unless there is major pushback.
@orangejenny

**Pull request merged**
