### PR TITLE
fix restore perms

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?242732

@benrudolph not sure if this is the most elegant fix. 

cc @NoahCarnahan

### CODE REVIEW

**Review by NoahCarnahan — APPROVED** [review]
👍

**Comment by czue** [comment]
i'm just gonna deploy this. seems to be causing pain for a few different people

**Comment by benrudolph** [comment]
Ah shoot. Forgot we did this in old cloudcare. Thanks, I'll follow up with
a test case for this scenario later today

**Comment by czue** [comment]
nice, yeah that'd be good. feel free to also test [this case](https://github.com/dimagi/commcare-hq/pull/14075), or find a smarter way to address these if that makes more sense (i didn't go down the path of figuring out why `as_user` was being set to the same as the calling user)

**Comment by benrudolph** [comment]
Ok, will do. It's an oddity about cloudcare sqlite restore. We always send
the as user whether we need it or not and don't suffix mobile workers with
commcarehq.org which adds a fair bit of complexity that I want to get rid of

**Comment by czue** [comment]
> and don't suffix mobile workers with commcarehq.org which adds a fair bit of complexity that I want to get rid of

haha, yeah just been wrestling with this and was much more annoying than I expected

**Pull request merged**
