### PR TITLE
fix ucr choice list 500ing

### PR DESCRIPTION
**Pull request by dannyroberts**
_get_report_filter can return a DynamicChoiceListFilter which isn't always picklable

http://manage.dimagi.com/default.asp?240153

### CODE REVIEW

**Comment by dannyroberts** [comment]
@proteusvacuum cc @czue

**Comment by proteusvacuum** [comment]
still curious about what exactly was causing this, but looks good.

**Comment by czue** [comment]
seems fine to me. @proteusvacuum was there a reason you originally added caching there and any concerns with it going away (assuming that was you)?

**Comment by proteusvacuum** [comment]
Yeah, I was calling that method twice at some point, but then refactored so that it was only needed once  ([here](https://github.com/dimagi/commcare-hq/commit/18f1656d55c5f31c3416bf90ea58f4569787f369)), and forgot to remove the quickcache. The caching is no longer necessary, so no concerns about it being removed.

**Review by proteusvacuum — APPROVED** [review]

**Pull request merged**
