### PR TITLE
Add a setting for image inflation

### PR DESCRIPTION
**Pull request by amstone326**
Add dropdown for enabling new image inflation technique.

The confluence page that is referred to in the message hasn't actually been updated yet; will updated it  concurrently with this getting merged

### CODE REVIEW

**Comment by czue** [comment]
build fail looks real
```
======================================================================
ERROR: test_basic_app (corehq.apps.app_manager.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 140, in test_basic_app
    ], kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_views.py", line 119, in _test_status_codes
    response = self.client.get(reverse(name, kwargs=kwargs), follow=False)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/domain/decorators.py", line 77, in _inner
    return view_func(req, domain_name, *args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/views/apps.py", line 384, in view_app
    return view_generic(request, domain, app_id)
  File "submodules/dimagi-utils-src/dimagi/utils/couch/resource_conflict.py", line 24, in new_fn
    return fn(*args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/views/view_generic.py", line 118, in view_generic
    context.update(get_app_view_context(request, app))
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/views/apps.py", line 138, in get_app_view_context
    get_commcare_settings_layout()[app.get_doc_type()])
  File "submodules/dimagi-utils-src/dimagi/utils/decorators/memoized.py", line 11, in _inner
    return m(*args, **kwargs)
  File "submodules/dimagi-utils-src/dimagi/utils/decorators/memoized.py", line 127, in __call__
    value = self.func( *args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/commcare_settings.py", line 74, in get_commcare_settings_layout
    for doc_type in ('Application', 'RemoteApp')
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/commcare_settings.py", line 73, in <dictcomp>
    doc_type: _load_commcare_settings_layout(doc_type)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/commcare_settings.py", line 59, in _load_commcare_settings_layout
    ', '.join(settings.keys())
Exception: CommCare settings layout should mention all the available settings. The following settings went unmentioned: properties.cc-inflation-target-density
```

**Comment by amstone326** [comment]
@wpride Hey, it looks like commcare-settings-layout.yaml also needs to be updated for this to work properly, but I don't have an hq env so I can't update this PR to include a commit to another file. Would you be able to grab this PR and add that?

**Comment by wpride** [comment]
@amstone326

**Comment by czue** [comment]
looks good to me but i'll let one of the app builder folks merge just in case since i don't really know how this works. cc @dannyroberts

**Comment by dannyroberts** [comment]
Nice! It's sweet to see the mobile team being able to iterate on an app-building-facing mobile feature end-to-end easily and without waiting on a server dev!

**Pull request merged**
