### PR TITLE
Performance: Update Elasticsearch queries for direct ID match to reduce per request latency

### PR DESCRIPTION
**Pull request by esoergel**
## Product Description
Performance improvement with no user facing changes.

## Technical Summary
For Elasticsearch requests, this change eliminates the use of `_id` as a direct scalar query match in favor of the already available `ids` vector match. This pattern is now the canonical way recommended by Elastic to perform direct ID matches.

This has high potential for improving latency in individual retrieval traversals, because the `_id` field under the hood is part of the ES `stored_fields` record instead of the `doc_values` record, and the latter is significantly more optimized for read overheads. 

image

### Safety story
This will be piloted through staging and evaluated for performance in tranche 3, along with #34429, to be measured through the nightly load against the baseline. 

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
🚀

**Comment by snopoke** [comment]
Tests in this file need to be updated: `corehq.apps.case_search.tests.test_filter_dsl`, maybe also the doc here: https://github.com/dimagi/commcare-hq/blob/67a1c9d39026170c1733cacf82f567e5d0709df4/docs/elasticsearch.rst#L39

**Comment by esoergel** [comment]
https://github.com/dimagi/commcare-hq/pull/34433#issuecomment-2058473665
@snopoke wow, that message is apt.  Not sure how to update the doc though, as _hopefully_ the recommendation will be a little different with `ids` vs `term: _id`.  I'm sure `GET` is strictly speaking better than searching regardless, though.

**Review by MartinRiese — APPROVED** [review]

**Review by snopoke — APPROVED** [review]
nice

**Pull request merged**
