### PR TITLE
support for named filters in expressions

### PR DESCRIPTION
**Pull request by czue**
addresses http://manage.dimagi.com/default.asp?152731

just passes the context all the way through the chain to make sure nested filters have access to it

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@dannyroberts or @nickpell

**Comment by czue** [comment]
not sure why the build is failing but it's definitely unrelated. i ran ucr tests locally

**Comment by dannyroberts** [comment]
:+1:

**Pull request merged**
