### PR TITLE
sms email model alter date

### PR DESCRIPTION
**Pull request by knguyen142**
##### SUMMARY

Related to https://github.com/dimagi/commcare-hq/pull/27788#pullrequestreview-430896510, did not look at first param and forgot to remove `null=true` for date.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
will this cause an issue where the original migration was already run? I think we would be asked to provide a default value for null entries, even if there aren't any?

**Comment by knguyen142** [comment]
> will this cause an issue where the original migration was already run? I think we would be asked to provide a default value for null entries, even if there aren't any?

The original migration is not run in prod yet, I believe? But even if it is, the code that actually creates the email rows has not been deployed yet https://github.com/dimagi/commcare-hq/pull/27805

**Comment by knguyen142** [comment]
There was a migration conflict so the original email migration needs to be incremented. Because it was not run and needs to be incremented, this PR https://github.com/dimagi/commcare-hq/pull/27820 brings the email date change into it as well.

**Comment by mkangia** [comment]
@knguyen142 you can check labels on a commit to be sure
https://github.com/dimagi/commcare-hq/pull/27788/commits/e0352037ecd001608bf8887a5112156153a1ff27

**Pull request closed without merging**
