### PR TITLE
 python-modernize deployment/ -w --future-unicode

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
@millerdev I'm going to merge this now to get the changes deployed but will check now if this is Python 3 compatible and update as necessary.

**Comment by nickpell** [comment]
It looks like restkit currently does not support python 3.   Running ```from restkit.session import set_session``` with restkit version 4.2.2 throws an error

```
File "/Users/Nick/.virtualenvs-py3/venv/lib/python3.6/site-packages/restkit/__init__.py", line 21, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by emord** [comment]
@nickpell restkit is a particularly nasty library to port over to py3 as it sends directly to sockets using socketpool. My solution was going to be to move couchdbkit off of restkit and stop using it, although i think we use it in some other places too.

**Comment by snopoke** [comment]
@millerdev `b'string'` is python 3 compatible

**Pull request merged**
