### PR TITLE
[ICDS Dashboard]: Minor MPR UI fix

### PR DESCRIPTION
**Pull request by ShubhamBansal1997**
Removed the span `Select Sector or AWC` as the MPR is allowed for state and below levels also.
https://dimagi-dev.atlassian.net/browse/QA-1760?focusedCommentId=81092##### SUMMARY

### CODE REVIEW

**Comment by orangejenny** [comment]
Why not delete it altogether?

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
good to delete the code instead of commenting it out.

**Comment by ShubhamBansal1997** [comment]
Updated

**Review by orangejenny — APPROVED** [review]

**Review by Rohit25negi — APPROVED** [review]

**Comment by Rohit25negi** [comment]
fine for now. But good to make the PR title a bit more contextual rather than just naming it as minor or major fix.

**Pull request merged**
