### PR TITLE
Migrate MVP Reports + Indicators to B3

### PR DESCRIPTION
**Pull request by biyeun**
that moment where I revisit the past **shudder**

@czue / @millerdev  / anyone
should this be formally QA'd? I checked it out locally and things were functioning as expected.

screen shot 2016-03-03 at 3 38 59 pm
screen shot 2016-03-03 at 3 39 05 pm
screen shot 2016-03-03 at 3 39 14 pm
screen shot 2016-03-03 at 3 39 24 pm
screen shot 2016-03-03 at 4 23 16 pm
screen shot 2016-03-03 at 4 23 22 pm
screen shot 2016-03-03 at 4 35 24 pm
screen shot 2016-03-03 at 4 35 36 pm

### CODE REVIEW

**Comment by biyeun** [comment]
(review commit-by-commit)

**Comment by czue** [comment]
@biyeun since you're the owner of these reports I think you and @amsagoff should make the call how closely to QA. If you've run everything locally (and also tested the email versions) and are confident then I'd be comfortable not doing anything formally.

**Comment by czue** [comment]
didn't review closely (and not sure it needs to be reviewed closely given it's a one off). I'd be fine merging once we're ok with QA situation. also I think you meant to ping @millerdev

**Comment by millerdev** [comment]
reviewed

**Comment by millerdev** [comment]
g2g when you're satisfied that you've done enough testing @biyeun

**Comment by dmiller** [comment]
Can you get me off this chain?
I'm getting announcements.
I have nothing to do with this project.

**Comment by millerdev** [comment]
@dmiller: sorry for the inconvenience. I think you are the only one who can do that. There's an *Unsubscribe* button in the right sidebar that you can click to disable notifications.

**Comment by biyeun** [comment]
@millerdev good to merge

**Comment by biyeun** [comment]
@millerdev last commit addressed the `console.log` shouldn't affect the passed build

**Pull request merged**
