### PR TITLE
Yeksi Naa Reports | Change Rupture rate by PPS denominator

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @czue,
This is a fix for Yeksi Naa Rupture rate by PPS by changing denominator.

### CODE REVIEW

**Review by czue — APPROVED** [review]

**Comment by czue** [comment]
looks like build is now failing:
```
======================================================================
FAIL: custom.yeksi_naa_reports.tests.reports.test_dashboard_3:TestDashboard3.test_valuation_of_pna_stock_per_product_data_report
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/yeksi_naa_reports/tests/reports/test_dashboard_3.py", line 57, in test_valuation_of_pna_stock_per_product_data_report
    ['Produit 1', '0.00', '0.00', '0.00']]
AssertionError: Lists differ: [[u'DISPOSITIF INTRA UTERIN (T... != [[u'NEVIRAPINE 200MG CP.', u'0...
First differing element 0:
[u'DISPOSITIF INTRA UTERIN (TCU 380 A) - DIU', u'0.00', u'0.00', u'0.00']
[u'NEVIRAPINE 200MG CP.', u'0.00', u'0.00', u'0.00']
```

**Comment by czue** [comment]
@dmydlo you'll need to resolve conflicts on this one before it can get merged

**Comment by dmydlo** [comment]
Sure, yet this [PR](https://github.com/dimagi/commcare-hq/pull/20161) will also create conflicts.
I would like to get that one merged first as rebasing changes from this PR is going to be easy

**Comment by czue** [comment]
> I would like to get that one merged first as rebasing changes from this PR is going to be easy

done!

**Comment by czue** [comment]
accidentally merged with a broken build but I think the build fail is unrelated. will keep an eye on https://github.com/dimagi/commcare-hq/pull/20196 to make sure current build is still passing

**Pull request merged**
