### PR TITLE
Billing metatdata

### PR DESCRIPTION
**Pull request by calellowitz**
spec here: https://docs.google.com/spreadsheets/d/1AHqozvqKQpvpoOgpqh9zSHBFu71fx-l1kuJwxkW7W1A/edit#gid=1830814960
in far right column. only implemented the highlighted fields
@nickpell 
cc: @snopoke @biyeun 
@dimagi/product

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/accounting/models.py, line 1012 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/models.py, line 1013 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/models.py, line 1014 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/payment_handlers.py, line 72 - E303 too many blank lines (2)
* corehq/apps/accounting/payment_handlers.py, line 347 - E303 too many blank lines (2)

**Comment by snopoke** [comment]
Does this need a migration to convert existing data?

**Comment by calellowitz** [comment]
@snopoke 
No, of the 5 fields, only two are existing. One of them is only a UI change and a change of the default value, and the other created more options, but existing domains can be left as is. The 3 new fields can all be safely set to the default for existing domains.

**Comment by nickpell** [comment]
I'd encourage you to squash related django migrations:
https://docs.djangoproject.com/en/1.8/topics/migrations/#squashing-migrations

It's a good practice to limit the number of migrations in a PR to keep the history more readable.

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/accounting/models.py, line 1012 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/models.py, line 1013 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/models.py, line 1014 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/accounting/payment_handlers.py, line 72 - E303 too many blank lines (2)
* corehq/apps/accounting/payment_handlers.py, line 347 - E303 too many blank lines (2)

**Comment by calellowitz** [comment]
@nickpell migrations fixed

**Comment by nickpell** [comment]
awesome, thanks

**Comment by calellowitz** [comment]
merge reverted in #9212 
will set up another PR on this when it passes QA

**Pull request merged**
