### PR TITLE
Pin to sqlagg pre-release commit

### PR DESCRIPTION
**Pull request by dannyroberts**
https://dimagi-dev.atlassian.net/browse/SAAS-11003

##### SUMMARY

I think we want to do this "right" tomorrow and make a sqlagg release that we pin to instead, but we decided it was important to get this out quick, and I didn't want to have that process be a potential blocker.

This fixes UCR's total counts (used in the paginated report table), which were previously being incorrectly estimated under some condition that included a column having null values

### CODE REVIEW

**Comment by dannyroberts** [comment]
Hmm, testing on staging isn't showing this helping, so looks not ready yet

**Comment by snopoke** [comment]
@dannyroberts what was the issue on staging? Did it not make any change?

**Comment by snopoke** [comment]
FYI that this PR should be merged before bumping sqlagg version: https://github.com/dimagi/commcare-hq/pull/27863

**Review by millerdev — DISMISSED** [review]

**Comment by dannyroberts** [comment]
Closing in favor of: https://github.com/dimagi/commcare-hq/pull/27870

**Pull request closed without merging**
