### PR TITLE
More HTTP Verbs for Repeaters

### PR DESCRIPTION
**Pull request by proteusvacuum**
## Product Description

This adds the ability to send PUT and DELETE requests from repeaters.
This was motivated by the DIVOC integration which requires a PUT request to update a record.

### Safety story

Tested locally

### Automated test coverage
This area of code is reasonably well covered, and I added a few extra tests.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by proteusvacuum** [comment]
@kaapstorm I went back and forth on whether to include `DELETE` here, since YAGNI. I'm open to deleting that (har har). 
I'd initially also included `GET` and others, but decided I couldn't figure out what the usecase for that was (also, YAGNI).

**Review by Charl1996 — APPROVED** [review]
My only comment would be to maybe remove the DELETE verb if we haven't got a use-case for it, otherwise we could've just as well included GET for completeness sake...in any case I think the way you've written this makes it very easy to add it later, should we need it, but happy to hear others' opinions.

**Review by kaapstorm — APPROVED** [review]
I can think of a use case for DELETE.

`Dhis2EntityRepeater` supports complex workflows involving events associated with tracked entities. But if a project just wants to export cases as tracked entity instances, one could do that with `CaseExpressionRepeater` if it supported POST, PUT and DELETE for registering, updating and closing cases. (More info on the [DHIS2 API calls here](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/tracker.html#webapi_tracked_entity_instance_management).)

**Comment by kaapstorm** [comment]
:thinking: Perhaps way too late for this suggestion, but what if the expression is used not only for the request body, but for all properties of a request:
* Body
* Method
* Headers
* Endpoint (which you'd append to the `ConnectionSettings` base URL

**Comment by proteusvacuum** [comment]
@kaapstorm I love that idea! We discussed it offline and decided that those are all totally possible additions to the `ExpressionRepeater`, and we'll implement them soon (and that this PR moves the needle in that direction)

**Pull request merged**
