### PR TITLE
make autopay more fault tolerant

### PR DESCRIPTION
**Pull request by nickpell**
To avoid a repeat of an issue like http://manage.dimagi.com/default.asp?222722 I've made the autopay workflow more fault tolerant (like in https://github.com/dimagi/commcare-hq/pull/11071)

Recommend 🐡 

@kaapstorm

### CODE REVIEW

**Comment by kaapstorm** [comment]
Nice.

**Comment by nickpell** [comment]
I don't think tests were run yet, but they've passed locally

**Comment by kaapstorm** [comment]
:flushed: For some reason your PRs have not been showing me the Travis build status. I double-checked on your previous PRs by going to Travis and looking up the PR, and noticed that you'd pinged me after the build passed (or, at least, that's what it seemed). This time I didn't check. I'll be more cautious next time.

**Comment by nickpell** [comment]
yeah looks like none of my outstanding PRs show the build status :(

**Pull request merged**
