### PR TITLE
Added name to export_instances_by_domain view

### PR DESCRIPTION
**Pull request by orangejenny**
Prep work for paginating exports UI.

@esoergel

### CODE REVIEW

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
@esoergel I added is_daily_saved_export and export_format to key after realizing the exports views filter on those two properties. Is there any reason not to do that?

**Comment by esoergel** [comment]
Another option here would be to add this meta information to the value being emitted.  Then it would still be available for in-memory work, but it wouldn't be part of the key that's used to index the doc.  For examples of how that works, check out how `applications_brief` is used.

The gist is that couch views return four things.   With an emit like this:
```javascript
emit([doc.domain, doc.doc_type, doc.is_deidentified], {
    'is_daily_saved': doc.is_daily_saved_export,
    'export_format': doc.export_format,
    'name': doc.name
});
```
The results from a view call would be a list with each entry containing:
id - doc._id
key - [doc.domain, doc.doc_type, doc.is_deidentified]
value - that value dict from above with the metadata
doc - the actual document, only included if `include_docs=True` is passed to the view

I don't think we do this frequently enough to have a set practice, but IMO these fields should go in the value field so we don't clutter up the key (potentially making this harder to change in the future), while still being available without doing the full query.

**Comment by orangejenny** [comment]
@esoergel updated

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
One more change: added `owner_id` because when the exports ownership flag is on, exports are split into sections based on owner. I think those sections will paginate separately.

**Review by esoergel — APPROVED** [review]
That seems reasonable

**Comment by orangejenny** [comment]
fyi @biyeun this updates a couch view, but it shouldn't take long to reindex (it's in the meta db) and hopefully won't add significant time to today's deploy

**Pull request merged**
