### PR TITLE
remove manage app releases permissions

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
Remove ICDS feature flag for restricting permissions on managing app releases by user role.

This feature flag was restricted to ICDS environments so it is not available to any other envs and hence currently completely unused.

## Feature Flag
RESTRICT_APP_RELEASE (restrict_app_release): ICDS: Permission to manage app releases on user roles

## Product Description
Remove the permissions that allow restricting which apps a user can manage releases for.

@dimagi/product the alternative to to GA this if you want this ability in the product.

Docs: https://confluence.dimagi.com/display/IndiaDivision/Restricting+Release+Management+to+Specific+Users

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### QA Plan
Tested locally:
- create role
- update role
- delete role
- view releases
- create new release

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
I thought this was generally useful and would ultimately become a part of the product.

**Comment by mkangia** [comment]
> the alternative to to GA this if you want this ability in the product.

Was it GA?

**Comment by snopoke** [comment]
> > the alternative to to GA this if you want this ability in the product.
> 
> Was it GA?

Make it Generally Available (remove the feature flag restriction)

**Review by snopoke — COMMENTED** [review]
Got approval from product & solutions to remove this.

**Comment by mkangia** [comment]
:wave: manage app release

**Pull request merged**
