### PR TITLE
drop checkbox from mm uploader outside of formbuilder

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?142336

Ought to be deployed with https://github.com/dimagi/Vellum/pull/370

### CODE REVIEW

**Comment by orangejenny** [comment]
@emord / @millerdev

**Comment by czue** [comment]
:+1: from me. love only deletions PRs!

**Comment by emord** [comment]
Should the relevant code in the HQ endpoint be deleted as well? I assume there is dead code parsing share options from vellum that will be unused now

**Comment by orangejenny** [comment]
@emord 
Created PR in MediaUploader to get rid of the code that handles that checkbox

**Pull request merged**
