### PR TITLE
Evaluate selection

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride
selections

### CODE REVIEW

**Comment by wpride** [comment]
@benrudolph Do I need to run anything to get this to work correctly? hitting "evaluate" is reloading the page and the debugger is only taking up ~2/3 the screen: 

screen shot 2016-11-29 at 5 04 27 pm

Maybe just needs to be tested with normal Nimbus?

**Comment by benrudolph** [comment]
hmm i tested on both and it was working fine. did you use the formplayer branch as well?

**Comment by benrudolph** [comment]
https://github.com/dimagi/formplayer/pull/195

**Comment by benrudolph** [comment]
this is what i'm seeing:
screen shot 2016-11-29 at 5 22 26 pm
i think it may be a bower thing or something

**Comment by benrudolph** [comment]
ok formplayer branch is ready to go on this too

**Comment by benrudolph** [comment]
bump

**Pull request merged**
