### PR TITLE
remove unused views

### PR DESCRIPTION
**Pull request by snopoke**
https://docs.google.com/a/dimagi.com/spreadsheets/d/12JPPfO6zlV5jx7NjZWPSIzzxYW1ZXsCBp9VfIXMQD0o/edit#gid=0

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
don't forget to `prune_couch_views` if there are any design docs that are no longer relevant.

**Comment by snopoke** [comment]
Yup, I've added that to the trello card. Will do that on Monday.

**Comment by dannyroberts** [comment]
First of all, this is awesome, and big thanks to @snopoke

In addition to being awesome, it also re-raises the question of whether we should be more careful about merging and deploying things that require a preindex. Preindexing this even just staging, and definitely staging and production, basically made the site so slow as to be unusable for the rest of Friday afternoon.

It's hard to know what the right thing to do would have been, but I think something like this. Notify deployer to merge right after Friday deploy, and tell the deployer to kick off a preindex right after merging so it will be preindexed by Monday. I think that's better than merging, because it makes it impossible for someone who wasn't paying attention (like me today) to by mistake start a preindex during work hours. What do people think?

**Comment by czue** [comment]
@dannyroberts are you sure that it was the reindexing that caused the cloudant issues? it sounded like they just had a complete failure of two of our nodes.

your workflow makes sense if we think that reindexing is likely to cause major issues, but i'm not sure that we need to be that cautious or whether yesterday was more of a fluke.

**Comment by dannyroberts** [comment]
At the time it definitely seemed related, just timing wise, but from the exchange with Cloudant it sounds that it triggered some much worse problem that we're unlikely to see again. It still makes sense to me to start a long preindex right after a deploy, just so that we don't end up blocking that day's deploy on it.

**Comment by snopoke** [comment]
That makes sense. It's not likely that this will happen very often but got
to try and plan it better.

**Comment by czue** [comment]
yeah agree there's no downside to that.

**Comment by dannyroberts** [comment]
Ran `prune_couch_views` on staging FYI

**Comment by dannyroberts** [comment]
Output was, so if we haven't run this on prod for a while, it's likely to be a big win!

```
deleting from staging_commcarehq:
---------------------
appstore
callcenter
cleanup
custom_data_fields
custom_data_fields-tmp
doc_summary
eula_report-<Database staging_commcarehq>
exports_forms-<Database staging_commcarehq>
fixtures
formtrends
groupexport-<Database staging_commcarehq>
hqbilling
languages-<Database staging_commcarehq>
management
management-tmp
migration
mvp_births-<Database staging_commcarehq>
mvp_child_health-<Database staging_commcarehq>
mvp_chw_referrals-<Database staging_commcarehq>
mvp_chw_visits-<Database staging_commcarehq>
mvp_deaths-<Database staging_commcarehq>
mvp_maternal_health-<Database staging_commcarehq>
mvp_over5-<Database staging_commcarehq>
opm_tasks
opm_tasks-tmp
prescriptions
receiverwrapper
reportconfig-<Database staging_commcarehq>
reports_apps-<Database staging_commcarehq>
reports_forms-<Database staging_commcarehq>
submituserlist
trialconnect
trialconnect-tmp
```

**Comment by snopoke** [comment]
@czue ran this on prod last Monday and deleted bunch of views. It needs to
be run again now that we've deleted some more design docs e.g callcenter
and appstore

**Pull request merged**
