### PR TITLE
remove custom success message

### PR DESCRIPTION
**Pull request by dannyroberts**
for tests

### CODE REVIEW

**Comment by dannyroberts** [comment]
@ctsims once @amsagoff is signed off, we'll be deploying this, which will change the success message to "✓" for all J2ME phones using manual send forms mode.

**Comment by amsagoff** [comment]
comms sent, fine to deploy tmrw

**Comment by dannyroberts** [comment]
@amsagoff I made a QA request to do a sanity test of this against staging on a J2ME phone. Is that overkill? Just want to make sure the checkmark doesn't, like, crash the phone or look super confusing

**Comment by amsagoff** [comment]
when in doubt, QA it out!

**Comment by czue** [comment]
can't wait to get rid of this bad boy

**Comment by dannyroberts** [comment]
@amsagoff looks like this. Good enough?

photo on 9-30-15 at 5 06 pm

**Comment by amsagoff** [comment]
can we center it so it looks like a checkmark rather than a mystery smudge?

**Comment by ctsims** [comment]
Wow, a new J2ME Feature request.

I think we can put it on our todo for 2.24?

-Clayton

**Comment by dannyroberts** [comment]
For now I'm going to try surrounding it with non-breaking whitespace

**Comment by dannyroberts** [comment]
'Bout as good as it's gonna get
imag0343

**Comment by ctsims** [comment]
ship that shit

**Comment by amsagoff** [comment]
.....can we just get rid of manual send altogether? I think only a handful
of j2me project still using that.

**Comment by dannyroberts** [comment]
@benrudolph would you like to do the honors?

**Comment by dannyroberts** [comment]
(last commit probably doesn't need to wait for tests)

**Comment by czue** [comment]
oh hells yeah

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
