### PR TITLE
remove "Monthly" from text

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?183551

This definitely fixes it, though it wasn't obvious to me what else whould be affected by this change. @biyeun or @nickpell can you confirm this seems fine for this ticket?

### CODE REVIEW

**Comment by nickpell** [comment]
This would also affect the text in the Usage Summary box in the Current Subscription page:

screen shot 2015-10-05 at 11 37 26 am

Wondering if this is preferred or should stay the same?  @dimagi/product

**Comment by amsagoff** [comment]
That should stay "Monthly SMS" because the table is showing monthly usage.

When you buy credits you are buying them for all time (not monthly), so
there we just want to say "SMS"

**Comment by biyeun** [comment]
Yeah, I think the thing here is not to reuse the language in both places...

**Comment by benrudolph** [comment]
this was handled in different PR

**Pull request closed without merging**
