### PR TITLE
Check data_source attribute exists

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: [Sentry](https://sentry.io/organizations/dimagi/issues/1719793816/?project=136860)

##### SUMMARY

When viewing a report, users with `is_staff` enabled can see report data source queries. But custom reports whose data source is `CombinedDataSource` crashes, because `CombinedDataSource` doesn't have a `data_source` attribute.

I am opening as a draft PR for feedback:
* Do we care about queries for `CombinedDataSource`? 
* If we do, is `CombinedDataSource.original_data_source.data_source.get_query_strings()` even a thing?
* Any other reason why we shouldn't rather go with
  ```python
        if (
            self.request.couch_user.is_staff
            and hasattr(self.data_source, 'data_source')
        ):
            context['queries'] = self.data_source.data_source.get_query_strings()
  ```

### CODE REVIEW

**Comment by kaapstorm** [comment]
Oh, [non-work-related context](https://en.wikiquote.org/wiki/Turtles_all_the_way_down).

**Comment by esoergel** [comment]
I'm unfamiliar with `CombinedDataSource`, looks like it's a custom thing for `abt`.  In that light, I think I'd push for your second approach, or if necessary, modifying `CombineDataSource` to have a `data_source` method if that _is_ useful.

**Review by esoergel — COMMENTED** [review]
:+1:

**Comment by kaapstorm** [comment]
Sorry @esoergel I should have switched this to a normal PR sooner.

**Review by esoergel — APPROVED** [review]

**Pull request merged**
