### PR TITLE
[ICDS Dashboard] Removed ff for dashboard usage activity report

### PR DESCRIPTION
**Pull request by challabeehyv**
##### SUMMARY
Removed ff for dashboard usage activity report

##### FEATURE FLAG
No

### CODE REVIEW

**Review by Rohit25negi — APPROVED** [review]
Looks good. Did you tested it locally?
@challabeehyv

**Comment by Rohit25negi** [comment]
Not to be merged, as QA is not through.

**Comment by challabeehyv** [comment]
> Looks good. Did you tested it locally?
> @challabeehyv

yes

**Comment by Rohit25negi** [comment]
QA is through

**Pull request merged**
