### PR TITLE
add a bootstrap 3 version of the settings base template

### PR DESCRIPTION
**Pull request by biyeun**
adds a b3 version of settings' base_template

@emord / anyone

### CODE REVIEW

**Comment by biyeun** [comment]
Cc @benrudolph or @dannyroberts :-)

**Comment by benrudolph** [comment]
i specifically removed this cause this logic was being done in the b3 base template. are you finding otherwise?

**Comment by biyeun** [comment]
@benrudolph can you clarify? I believe I'm finding otherwise.

**Comment by biyeun** [comment]
ah, I see perhaps it's `var path = '{{ request.path }}';` which is EW. will look into this when I return (currently reviewing for urgent responses)

**Comment by biyeun** [comment]
It might be the case we don't need this template at all, so closing for now

**Pull request closed without merging**
