### PR TITLE
Design improvement to custom banners

### PR DESCRIPTION
**Pull request by mkangia**
## Product Description

Minor improvement to design of Custom domain alerts page.
1. Club all buttons under "Actions"
2. Add icons to buttons for edit and delete

Before
Screenshot from 2024-02-18 01-01-38

After
Screenshot from 2024-02-19 12-24-41

## Technical Summary

https://dimagi.atlassian.net/browse/SC-3395

### Safety story

Tested locally.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by SmittieC — COMMENTED** [review]
Nice!. Small suggestion: Since the column is `status` now, would it not make sense to rename the text to "active" / "not active"? Since it's a button already, I think it should be clear that one can switch the status by simply clicking on it. Thoughts?

**Review by zandre-eng — APPROVED** [review]
Looks good. Just one question however, will you be splitting the edit and delete buttons into separate columns? This would make it work better with screen readers, and so could be an quick win change.

**Comment by Charl1996** [comment]
> Since the column is `status` now, would it not make sense to rename the text to "active" / "not active"? Since it's a button already, I think it should be clear that one can switch the status by simply clicking on it. Thoughts?

Yeah, I agree, since the Status column gives the impression that it's going to report on the actual status of the banner, otherwise the button needs to move into the Actions column, since it's technically an action.

**Comment by mkangia** [comment]
Hey @SmittieC 

> would it not make sense to rename the text to "active" / "not active"? Since it's a button already, I think it should be clear that one can switch the status by simply clicking on it. Thoughts?

I am aligned on the first point, Since the column says "Status" it would be better to have "Active" / "Inactive" as the values in that column.
I am hesitant to have that on the buttons though, since buttons are "actions", and for buttons "Activate" / "Deactivate" would make sense.

If the column headers are confusing, I could go with Jenny's [original suggestion](https://github.com/dimagi/commcare-hq/pull/33909#discussion_r1445121933) on the PR where this feedback came from to remove the headers entirely and have just the buttons.

**Comment by mkangia** [comment]
> Looks good. Just one question however, will you be splitting the edit and delete buttons into separate columns? This would make it work better with screen readers, and so could be an quick win change.

Hey @zandre-eng 

Ya, i tried that change and it didn't look well. It looked weird design wise. I shared how that looked [here](https://dimagi.slack.com/archives/CP7S2N58W/p1706700129925719)
As an alternate I tired the [btn-group](https://getbootstrap.com/docs/3.3/components/#btn-groups) suggested by Jenny, though I am not certain that would work because we have an anchor tag and a form with a button here.
This is how I tried adding it
```
<td>
  <div class="btn-group" role="group">
    <a class="btn btn-default" data-bind="attr: {href: editUrl}" style="float: left; margin-right: 5px;">
      <i class="fa fa-edit"></i>
        {% trans "Edit" %}
    </a>
    <form action="{% url 'delete_domain_alert' domain %}" method="post" style="float: left">
      {% csrf_token %}
      <input name="alert_id"
        type="hidden"
        data-bind="value: id">
      <button type="submit" class="btn btn-danger">
        <i class="fa fa-trash"></i>
        {% trans "Delete" %}
      </button>
    </form>
  </div>
</td>
```
Plus, I when I use "tab" to navigate the page, I do get to each button separately, I don't have screen reader installed and it seemed out of scope to setup and test it.

**Comment by mkangia** [comment]
> otherwise the button needs to move into the Actions column, since it's technically an action.

Following @Charl1996's suggestion which sounds right and also resonates with something that was originally requested in the slack thread.

Here is how that looks like, I let go of the "Status" column entirely since the button already tells what the current status is, though I am happy to add it back if needed.

Screenshot from 2024-02-19 12-24-41

And here it is without the headers entirely that was suggested. I like this.
Screenshot from 2024-02-19 12-25-08

@zandre-eng @Charl1996 @SmittieC let me know your thoughts on this.

**Comment by SmittieC** [comment]
> If the column headers are confusing, I could go with Jenny's [original suggestion](https://github.com/dimagi/commcare-hq/pull/33909#discussion_r1445121933) on the PR where this feedback came from to remove the headers entirely and have just the buttons.

Removing the headers for this and keeping the buttons seems fine. In this case I think as @Charl1996 mentioned, it might make more sense to move this into the actions column then, since it's an action we take on the alert.

**Comment by zandre-eng** [comment]
> Ya, i tried that change and it didn't look well. It looked weird design wise. I shared how that looked [here](https://dimagi.slack.com/archives/CP7S2N58W/p1706700129925719)
As an alternate I tired the [btn-group](https://getbootstrap.com/docs/3.3/components/#btn-groups) suggested by Jenny, though I am not certain that would work because we have an anchor tag and a form with a button here.
This is how I tried adding it
...

@mkangia Thanks for the clarification. Given that this doesn't sound like a quick win, I agree it's fine to leave it as is since it is out of scope for this ticket.

**Comment by Charl1996** [comment]
I agree with @zandre-eng 's sentiment for still having the "Actions" header present.

**Comment by Charl1996** [comment]
Otherwise looks great! Thanks, @mkangia !

**Comment by mkangia** [comment]
Thanks for the close review everyone,
Updated to club all buttons under Actions.

**Review by SmittieC — APPROVED** [review]

**Review by zandre-eng — APPROVED** [review]
Looks good! :rocket:

**Pull request merged**
