### PR TITLE
CMR report changes

### PR DESCRIPTION
**Pull request by agrzywinski**
@esoergel http://manage.dimagi.com/default.asp?151510#861685

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
(not mergeable)

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by agrzywinski** [comment]
@czue @esoergel

**Pull request merged**
