### PR TITLE
Improve efficiency of app publishing

### PR DESCRIPTION
**Pull request by NoahCarnahan**
The project publishing form sent the ids of the documents returned by `app.get_latest_saved()` to the server. However, snapshot process required the ids of the original apps, not the latest saved. This meant a query had to be made for each app during the save process. This fixes the problem by sending the original app ids to the server instead. This is a follow on from https://github.com/dimagi/commcare-hq/pull/5167.

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@NoahCarnahan this looks great and much simpler than what was here previously. do you know why the original app ids ere being sent in the first place? it seems odd that it was done so intentionally and yet was totally unnecessary.

**Comment by NoahCarnahan** [comment]
@czue I'm not certain why the latest saved ids were being used instead of the original app ids. I do know though that this behavior has existed for several years. As best I can tell so far, it looks like the `app.get_latest_saved()` usage was first introduced [here](https://github.com/dimagi/commcare-hq/commit/f9e98993e285968df921c90b4c7ac87abe14cabf) maybe? It's tough to track though because that commit seems to only be on master (and not in any PR).

My best guess is that at one point, making a domain snapshot involved copying the applications in such a way that the latest build ids were more useful than the original app ids.

Perhaps someone who is more familiar with the snapshot process or that view has more insight. Looks like @emord worked on it lately, and @biyeun maybe made some larger changes a while ago.

**Comment by biyeun** [comment]
@NoahCarnahan I mostly refactored the view to move from a view function to a class. Didn't really touch the logic from what it originally was. Why we did that, I'm not certain, but this looks great. :-)

**Pull request merged**
