### PR TITLE
add includeFilter to patient report

### PR DESCRIPTION
**Pull request by benrudolph**
@kkrampa / @lwyszomi i'm 95% certain this fixes this bug: http://manage.dimagi.com/default.asp?218229#1096181

do you think you could test locally?

cc: @NoahCarnahan

### CODE REVIEW

**Comment by kkrampa** [comment]
@benrudolph Unfortunately, I have already deleted database for this project.

**Comment by lwyszomi** [comment]
@benrudolph I'm confused because problem is in SUCCEED domain and you sent changes for CVSU domain.

**Comment by benrudolph** [comment]
you're definitely right! haha not sure what i was thinking yesterday. i imagine the fix is about the same though. do any of you have this report locally to test out?

**Comment by kkrampa** [comment]
@benrudolph I have data for this project on my local machine.

**Comment by benrudolph** [comment]
thanks @kkrampa could you take a look at this guy? http://manage.dimagi.com/default.asp?218229 there was recently a change that made you explicitly set the search field (`includeFilter`) so that may be a lead

**Comment by kkrampa** [comment]
I will check this and make PR.

**Pull request closed without merging**
