### PR TITLE
Add workflow field to DomainCaseRuleRun

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

We create `DomainCaseRuleRun`s when a task to run rules for a specific case type on a domain is kicked off. As far as I can tell, this doesn't contain any information pertaining to which workflow is being run (we do run deduplicate and update workflows in separate tasks). I'm working on improving the reporting of past rule runs and I think this information will be helpful.

I've held off on including the change to actually save the `workflow` field when creating `DomainCaseRuleRun`s as a way to decouple the migration from the change that depends on the migration.

### Database concerns

I've confirmed that on production, there is not an instance of `AutomaticUpdateRule` that does not contain one of the three values for the `workflow` field, but in the event that a value does exist outside of these three choices, I'm not sure how the django orm will handle that.

The `DomainCaseRuleRun` `workflow` field needs a default, which I've allowed to be null in this case. The alternative would be to add an UNKNOWN option to the workflow choices, but that seems unnecessary. I don't love that the two `workflow` fields are not identical, but since we are adding this new field to DomainCaseRuleRun I don't see any way around needing to set the field to nullable.

### Safety story

We currently only save the three workflow values to the `workflow` field for `AutomaticUpdateRule`, so I don't think there is any risk by limiting this field to the set of choices. 

### Migrations

- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

If we need to roll this back, make sure we also roll back https://github.com/dimagi/commcare-hq/pull/32257

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
> I've confirmed that on production, there is not an instance of AutomaticUpdateRule that does not contain one of the three values for the workflow field, but in the event that a value does exist outside of these three choices, I'm not sure how the django orm will handle that.

I don't know how it will handle loading it from the DB but it will almost certainly fail if you try to save a model with a value outside of the specified choices.

I don't know why the original workflow field did not have the choices set. Possibly so that migrations are not needed when new workflows are added. 

Before rolling this out I think it would be prudent to also check the other envs including staging to make sure there are no other workflow options in the data.

> The DomainCaseRuleRun workflow field needs a default, which I've allowed to be null in this case. The alternative would be to add an UNKNOWN option to the workflow choices, but that seems unnecessary. I don't love that the two workflow fields are not identical, but since we are adding this new field to DomainCaseRuleRun I don't see any way around needing to set the field to nullable.

+1 to having the default be `null`

**Review by joxl — APPROVED** [review]
LGTM, pending @snopoke's value check suggestion.

Just one nit: Is there a preference to leave/omit the automatic migration names? I think something like `0030_add_workflow_choices` would be a bit more descriptive.

**Comment by gherceg** [comment]
> Before rolling this out I think it would be prudent to also check the other envs including staging to make sure there are no other workflow options in the data.

I checked staging, india, and swiss as well running the same thing I ran on prod:
```
from corehq.apps.data_interfaces.models import AutomaticUpdateRule
AutomaticUpdateRule.objects.all().exclude(workflow__in=['CASE_UPDATE', 'DEDUPLICATE', 'SCHEDULING']).count()
```
and the result was 0 for all envs. 

> Is there a preference to leave/omit the automatic migration names? I think something like 0030_add_workflow_choices would be a bit more descriptive.

I believe we have a preference to rename automatic migration names, I just didn't rename it well enough 😉. See 7b8fb9ccd67b4362393602edbae8ca2459ef10e1

**Review by joxl — APPROVED** [review]

**Review by snopoke — APPROVED** [review]
Can you just confirm what the sql output from the migration will be please: `./manage.py sqlmigrate <app> <migration>`

**Comment by gherceg** [comment]
@snopoke here is the sql output. I'm curious what in particular you are looking for/concerned about.

0030_add_workflow_choices
```
BEGIN;
--
-- Add field workflow to domaincaserulerun
--
ALTER TABLE "data_interfaces_domaincaserulerun" ADD COLUMN "workflow" varchar(126) NULL;
--
-- Alter field workflow on automaticupdaterule
--
COMMIT;
```

0031_add_domaincaserulerun_status_choices
```
BEGIN;
--
-- Alter field status on domaincaserulerun
--
COMMIT;
```

**Comment by snopoke** [comment]
> @snopoke here is the sql output. I'm curious what in particular you are looking for/concerned about.

Nothing specific. I just find it useful to see the actual SQL output, especially in instances like this where we are not expecting any DB changes for many of the operations.

**Pull request merged**
