### PR TITLE
Migrate Mobile Template to B3

### PR DESCRIPTION
**Pull request by biyeun**
@millerdev / anyone

QA'd locally. Seems small enough that that should be ok. @dimagi/product for a second opinion

screen shot 2016-03-04 at 2 17 23 pm
screen shot 2016-03-04 at 3 42 53 pm
screen shot 2016-03-04 at 3 47 54 pm

### CODE REVIEW

**Comment by amsagoff** [comment]
I'm not familiar enough with what this is to sign off...can you give me
some context? Feel free to ping me off thread

**Comment by czue** [comment]
These are the bihar supervision reports.

@biyeun the only thing that matters is that these look good on a Nokia C2. Can you test that?

**Comment by millerdev** [comment]
looks good, but can't merge

**Comment by benrudolph** [comment]
i see a day where HQ can be used on an :iphone:

**Comment by benrudolph** [comment]
the day is pretty far off though

**Comment by millerdev** [comment]
@biyeun are you ready to have this merged?

**Comment by biyeun** [comment]
@millerdev better to merge this https://github.com/dimagi/commcare-hq/pull/10620

**Pull request closed without merging**
