### PR TITLE
Form context simple

### PR DESCRIPTION
**Pull request by benrudolph**
@esoergel @czue i'm going to throw this on staging so it can get QA'd with @wpride's persistence

### CODE REVIEW

**Comment by czue** [comment]
sounds good. threw a QA label on it.

**Comment by czue** [comment]
g2m after qa

**Comment by benrudolph** [comment]
If we've gotten rid of `delegation` I can remove some more stuff in `cases.js`. let me know if you think it's worth it to keep it around. other wise i'll wipe it out @czue

**Comment by czue** [comment]
happy to get rid of it as long as @gcapalbo agrees

**Comment by gcapalbo** [comment]
yup, as far as I know we can get rid of all the delegation stuff

**Comment by snopoke** [comment]
:boom:

**Comment by gcapalbo** [comment]
Actually, I just happened to notice https://confluence.dimagi.com/display/commcarepublic/Delegation+Subcases. Is there a way to check and see if anyone is still using this feature?

**Comment by benrudolph** [comment]
Good catch, i'm not too sure. we can play it safe and keep it in? it'd be
cool to have some sort of functionality to check if it's still being used.
i could put in a soft assert so it emails me every time delegation is true

**Comment by gcapalbo** [comment]
@dannyroberts I think you built the delegation feature right? What's the best way to tell if it's still being used - do we just search for any cases with case type `cc_delegation_stub`?

**Comment by dannyroberts** [comment]
@gcapalbo Yeah searching for `cc_delegation_stub` should probably be enough. (Though you'd have to do that across all domains; maybe you can do that in elasticsearch?) Another possibility is searching for applications that have a module where `module.task_list.show` is `true`, but that may be harder to search for.

**Comment by gcapalbo** [comment]
Ok, just confirmed that the delegation feature is not being used

**Comment by benrudolph** [comment]
Ok, thanks for looking into that @gcapalbo. I think this is g2g then

**Comment by benrudolph** [comment]
scratch that, I suppose I should wait for the full round of QA to be done. I'll ping this thread again when it's ready to go

**Comment by dannyroberts** [comment]
> Ok, just confirmed that the delegation feature is not being used

Woohoo!!

**Comment by benrudolph** [comment]
Ok I think this is g2g. I sync'd with Christy the bugs that were found in QA don't have anything to do with this change

**Comment by dannyroberts** [comment]
@benrudolph looks good to me. Feel free to self merge (just being overly cautious since there's no activity in the last 5 days and I've been out of the loop)

**Pull request merged**
