### PR TITLE
Add number of minutes to deploy

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts can be merged independently of https://github.com/dimagi/commcare-hq-deploy/pull/93

cc: @orangejenny

### CODE REVIEW

**Comment by orangejenny** [comment]
interesting, code looks good, just waiting on tests

**Comment by dannyroberts** [comment]
Nice

**Comment by czue** [comment]
next step: publish to datadog and put on a graph

**Comment by benrudolph** [comment]
💡  good idea

**Pull request merged**
