### PR TITLE
upgrade django-celery

### PR DESCRIPTION
**Pull request by nickpell**
https://github.com/celery/django-celery/blob/master/Changelog

### CODE REVIEW

**Comment by nickpell** [comment]
requires running 
```
./manage.py migrate djcelery --fake-initial
```

before deploy

**Comment by snopoke** [comment]
I thought celery had native support for django now and that this package
was deprecated.

**Comment by nickpell** [comment]
@snopoke That's correct.  But I'm going with this for now just to get us to django 1.9 sooner.

**Comment by snopoke** [comment]
👍

**Comment by nickpell** [comment]
@benrudolph I'll be online tonight so seems like a good day to merge this

**Comment by benrudolph** [comment]
ok mergin!

**Pull request merged**
