### PR TITLE
Create custom repeater for beneficiary registration in BETS

### PR DESCRIPTION
**Pull request by esoergel**
@nickpell @proteusvacuum

### CODE REVIEW

**Review by nickpell — APPROVED** [review]

**Comment by proteusvacuum** [comment]
Don't you need a view for this? Or does the generic view just pick this one up?

**Comment by proteusvacuum** [comment]
Also, you don't have a payload generator attached to this, so I think this will have undefined behaviour.

**Comment by esoergel** [comment]
It works with the generic view, actually.  It's a subclass of CaseRepeater, so it uses the default CaseRepeaterJsonPayloadGenerator.  They didn't want a modified payload, so I figured we'd just stick with that.

**Comment by esoergel** [comment]
The way payload generators are linked to repeaters changed recently, so now it's specified as a [class attr](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/repeaters/models.py#L312-L312), meaning they'll be inherited.  Not sure what would've happened with the old decorator syntax.

**Pull request merged**
