### PR TITLE
docker improvements

### PR DESCRIPTION
**Pull request by snopoke**
@benrudolph 
- [x] reuse common vars in scripts
- [x] reduce image size
- [x] split image into 2 and publish base image

cc @philipkaare

### CODE REVIEW

**Comment by snopoke** [comment]
:skull: :construction:

**Comment by czue** [comment]
I think @biyeun is offline this week. is there anyone else who understands this well enough to review?

**Comment by czue** [comment]
(also happy to just merge, though I don't feel like i have much context)

**Comment by benrudolph** [comment]
fwiw seems logical to me. unmergeable

**Comment by snopoke** [comment]
Also setup an automated build to keep the base image up to date: https://hub.docker.com/r/dimagi/commcarehq_base/

**Comment by snopoke** [comment]
self merging

**Comment by benrudolph** [comment]
i was curious about the automated build. last time i took a look all of them had error'd out. is the plan to still use that?

**Comment by snopoke** [comment]
Yes, I just need to fix the build.

**Pull request merged**
