### PR TITLE
Removed USE_SMS_WITH_INACTIVE_CONTACTS flag

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
Only used by ilsgateway and ewsghana domains.

This has test coverage so it'll fail until https://github.com/dimagi/commcare-hq/pull/25904 is merged.

##### FEATURE FLAG
Use SMS with inactive contacts

### CODE REVIEW

**Comment by mkangia** [comment]
> Only used by ilsgateway and ewsghana domains.
and these two are inactive now?

**Review by mkangia — APPROVED** [review]
assuming the two domains are now inactive, I am not completely sure if its okay to remove such project specific implementation till we have actually deleted the projects from HQ just in case they revive.
But if that has been talked about and considered, definitely good to remove the dependencies

**Comment by orangejenny** [comment]
@mkangia yeah, sorry, I should have given more context. These projects are done, and GS signed off on removing the custom functionality built for them. I don't know when/if we'll delete the actual domains - my interest is just in decluttering the code base, especially the custom reports (they aren't compatible with requirejs).

**Comment by mkangia** [comment]
Sounds good, thanks @orangejenny

**Pull request merged**
