### PR TITLE
ipm-senegal reports refactor

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue 

we need rebuild all fluff tables for intrahealth module

### CODE REVIEW

**Comment by lwyszomi** [comment]
@czue 

I let you know when Fio give me a feedback.

**Comment by lwyszomi** [comment]
@czue 

Can we merge this before Friday deploy and start recalculations over the weekend?

**Comment by czue** [comment]
yes. @calellowitz is that something you can take care of? need to:

- merge before friday's deploy
- deploy
- stop all intrahealth pillows
- reset checkpoints for all intrahealth pillows
- start all intrahealth pillows

**Comment by calellowitz** [comment]
@czue sounds good. I should be able to do all that on friday

**Comment by czue** [comment]
@calellowitz just wanted to confirm that you're going to run through these steps after today's deploy

**Comment by calellowitz** [comment]
@czue will do. unlike wednesday

**Comment by calellowitz** [comment]
@czue @lwyszomi @nickpell 
closing this to deal with merge conflicts. replacement here https://github.com/dimagi/commcare-hq/pull/8869

**Comment by nickpell** [comment]
IntraHealthFluffPillow checkpoint reset

**Comment by czue** [comment]
:+1: thanks for the support

**Pull request closed without merging**
