### PR TITLE
include empty attributes for all types that have children

### PR DESCRIPTION
**Pull request by czue**
workaround for http://manage.dimagi.com/default.asp?233467

@proteusvacuum @emord buddy

### CODE REVIEW

**Comment by emord** [comment]
:+1: on :white_check_mark:

**Comment by czue** [comment]
fyi if timing works out it'd be nice to get this in before india deploy

**Comment by emord** [comment]
kicking build. failed on

```
======================================================================
FAIL: test_transfer_first_doc_order (corehq.apps.commtrack.tests.test_xml.CommTrackBalanceTransferTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 399, in test_transfer_first_doc_order
    self.check_product_stock(self.sp, product, final, 0)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 228, in check_product_stock
    self.assertEqual(expected_soh, latest_trans.stock_on_hand)
AssertionError: Decimal('50.0') != 150
```

**Comment by emord** [comment]
> fyi if timing works out it'd be nice to get this in before india deploy

@czue got it in

**Comment by czue** [comment]
nice thanks

**Comment by proteusvacuum** [comment]
:+1:

**Pull request merged**
