### PR TITLE
[AAA Dashboard] QA fixes

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @emord 

I sent fixes for QA issues:
https://dimagi-dev.atlassian.net/browse/QA-312
https://dimagi-dev.atlassian.net/browse/QA-313
https://dimagi-dev.atlassian.net/browse/QA-315
https://dimagi-dev.atlassian.net/browse/QA-316
https://dimagi-dev.atlassian.net/browse/QA-318
https://dimagi-dev.atlassian.net/browse/QA-319

for each issue we have separate commit.
Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Review by emord — APPROVED** [review]
Test failure, otherwise it looks good

```

[0m  1) Eligible Couple models eligible couple list view model test model properties:
[0m[31m     AssertionError: expected 'Yes' to equal 1[0m[90m
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:2178
      at http://localhost:8000/static/aaa/spec/models/eligible_couple.spec.js:57
[0m
```

**Comment by lwyszomi** [comment]
@emord updated, I forgot to merge master and I didn't have all tests.

**Comment by lwyszomi** [comment]
@emord I added fix for this ticket: https://dimagi-dev.atlassian.net/browse/QA-330

**Review by emord — APPROVED** [review]
There were some unrelated test failures that will require to merge master in again

**Pull request merged**
