### PR TITLE
Ce/location sync

### PR DESCRIPTION
**Pull request by calellowitz**
@esoergel @proteusvacuum 
https://manage.dimagi.com/default.asp?274558

Each of the two things here are currently fetched once per location in a restore. Some ICDS users have over 100000 users. In preliminary profiling, these fixes bring the restore time from 960 seconds to 30 seconds.

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]
Fun!

**Review by esoergel — APPROVED** [review]
Nice!  I think ICDS is the only environment not currently using the CTE version of this, which I think doesn't have this issue.
@millerdev FYI

**Comment by snopoke** [comment]
@calellowitz this broke restores on PNA FYI: https://sentry.io/dimagi/commcarehq/issues/550048536

I've manually reverted this on PNA but need a proper fix before next PNA deploy.

**Comment by snopoke** [comment]
On second thoughts, probably safest to just revert until we have a fix: https://github.com/dimagi/commcare-hq/pull/20470

**Pull request merged**
