### PR TITLE
showing all countries in admin page

### PR DESCRIPTION
**Pull request by calellowitz**
fixes
http://manage.dimagi.com/default.asp?190323#1067048
@proteusvacuum 
cc: interrupt @kaapstorm @benrudolph 

Not sure why the old code stopped working but they should be functionally identical

### CODE REVIEW

**Comment by benrudolph** [comment]
how does this fix the issue? was the data being loaded just not shown?

**Comment by calellowitz** [comment]
yeah. the page loads all of the countries in the side bar with a hide class. the more button shows them. for some reason it looks like the switch to bootstrap 3 made `.show()` no longer work (could be a jQuery change) but `removeClass('hide')` accomplishes the same thing.

**Comment by benrudolph** [comment]
cool :+1:

**Comment by benrudolph** [comment]
killing build

**Pull request merged**
