### PR TITLE
Rename the domain used in form XMLNS

### PR DESCRIPTION
**Pull request by kaapstorm**
##### SUMMARY
This is just the result of `sed -i 's/openrosa.org/org.commcarehq/g'` (Clayton's domain name suggestion).

##### RISK ASSESSMENT / QA PLAN
Is this wildly naive? This feels high risk, but my initial test run passed. I will see what Travis has to say, and if that's green, sanity test on Staging.

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
This is just about impossible to review. I wonder it could be split out into reference in core code vs references in tests? Otherwise per app maybe (or one commit per app)?

**Comment by kaapstorm** [comment]
(:hear_no_evil: Ignoring Stickler)

**Comment by millerdev** [comment]
Why `http://org.commcarehq` instead of `http://commcarehq.org`?

**Comment by kaapstorm** [comment]
Good idea, @snopoke. There are 329 test files affected, and 97 non-test files. That is still a lot, but 97 feels a little more manageable.

Please excuse me replacing that commit.

Asking people to inspect hundreds of instances of identical search-and-replace operations feels rude, and I'm not sure it's an efficient way of evaluating this change.

I was aiming for a general discussion of the idea, and thinking of Travis as the first hurdle. I'm a little concerned about deploying to Staging. Maybe running through the [New Environment QA](https://dimagi.github.io/commcare-cloud/setup/new_environment_qa.html) in a local monolith might be a good idea, before making changes to Staging.

Curious to hear your thoughts.

**Comment by kaapstorm** [comment]
Actually, you know what?

**This is going to break every filter of every form export, and every Data Export Tool config. It is a terrible idea!**

Closing.

**Comment by kaapstorm** [comment]
:thinking: Maybe it won't. Anyway, going to drop this idea for now.

**Comment by esoergel** [comment]
I'm pretty nervous about the change as well, since xmlnss are stored in the DB, including in old app builds, in form xml blobs, on users devices, and possibly on 3rd party systems like API consumers or DETs.  We do also use xmlns as an identifier, I think for things like reporting (as you mentioned), the app diff page (I think), linked applications, and likely in external integrations.

I could be convinced that it's safe to switch new xmlns generation to this root, however, as long as that doesn't modify existing form definitions.

**Pull request closed without merging**
