### PR TITLE
Added bindparam to the parameter

### PR DESCRIPTION
**Pull request by kkrampa**

### CODE REVIEW

**Comment by kkrampa** [comment]
@emord @calellowitz

**Review by emord — APPROVED** [review]
Looks ok, but not sure what `bindparam` does. Seems like other filters use it though

**Comment by emord** [comment]
Would also be nice to have a test for this filter

**Comment by kkrampa** [comment]
@emord ```self.paramater``` is just the name of the parameter. ```bindparam``` make sure that actual value is bind at expression time.

**Comment by kkrampa** [comment]
I will add test in separate PR

**Comment by kkrampa** [comment]
@emord :white_check_mark:

**Comment by kkrampa** [comment]
I will add test to this PR

**Review by emord — APPROVED** [review]

**Comment by kkrampa** [comment]
@emord :white_check_mark:

**Pull request merged**
