### PR TITLE
Use report_domain

### PR DESCRIPTION
**Pull request by emord**
Introduced here https://github.com/dimagi/commcare-hq/pull/21243/files#diff-3af365e79b93f051d416585bcba61b7eL791 Could use a test, but I'm not sure why domain is even optional. will need to look more into it

https://sentry.io/dimagi/commcarehq/issues/617686018/events/25560017373/

will hotfix to ICDS

### CODE REVIEW

**Comment by emord** [comment]
Updated to require domain in the call, but it's probably not needed? It's not clear to me why this parameter was included since StaticDataSourceConfiguration does not require by_id to pass domain

**Review by czue — APPROVED** [review]

**Comment by snopoke** [comment]
I think it might be because you can put the ID in a url which might not match the domain you belong to. At least that's what I surmised when looking at it before.

**Comment by emord** [comment]
> I think it might be because you can put the ID in a url which might not match the domain you belong to. At least that's what I surmised when looking at it before.

That's also true for data sources, though that's under a feature flag. (and you can't change static reports /data sources anyways, and they're public in our code repo)

**Comment by snopoke** [comment]
I was thinking more about running the report to view the data like here: https://github.com/dimagi/commcare-hq/blob/72f2560dacb24b0b4c7264d8a3b633624d95ec41/corehq/apps/userreports/reports/view.py#L178

**Pull request merged**
