### PR TITLE
fix broken test

### PR DESCRIPTION
**Pull request by nickpell**
@benrudolph @snopoke cc: @sravfeyn

### CODE REVIEW

**Comment by snopoke** [comment]
:+1:

**Comment by benrudolph** [comment]
failed on same test

**Comment by nickpell** [comment]
here's the real fix.  The problem was that ```subscription_length``` was evaluated as falsify when equal to zero, causing it to be ignored.

**Comment by benrudolph** [comment]
yay! thanks for the :mag:

**Comment by benrudolph** [comment]
:x: :disappointed_relieved:

**Comment by benrudolph** [comment]
this might have to do with some randomization going on. sometimes if you kick the build it just works

**Pull request closed without merging**
