### PR TITLE
Couch form case count

### PR DESCRIPTION
**Pull request by dannyroberts**
doing some informal analytics for sheel and hsph-betterbirth http://manage.dimagi.com/default.asp?238804

### CODE REVIEW

**Comment by dannyroberts** [comment]
@sheelio when this is deployed, you can do queries like `/a/droberts/couch_doc_counts/?start=1999-01-01&end=2016-01-01` and you'll get a response like
```json
{
    "CommCareCase": 10,
    "XFormInstance": 23
}
```

**Comment by czue** [comment]
is there possibly missing url/view code for this?

**Comment by sheelio** [comment]
@dannyroberts 
Thanks for putting this together!
For forms, does this include archived forms, demo data, etc?  
For cases, i'm curious what the date range refers to - is it the case created date?

**Comment by dannyroberts** [comment]
yup definitely forgot to push that last night. All set now pending build!

**Comment by dannyroberts** [comment]
@sheelio 

XFormInstance doesn't include deleted or archived, CommCareCase doesn't include deleted, but does include closed. No distinction is drawn at this level with demo_user data or anything.

For CommCareCase the date range refers to the date it was opened on.

**Comment by dannyroberts** [comment]
I thought someone had signed off and I self-merged, realized immediately that that hadn't happened, and @calellowitz is reviewing. Will roll back or fix if any issues.

**Comment by calellowitz** [comment]
post merge 👍

**Comment by sheelio** [comment]
@dannyroberts 

Thanks for this! I verified the numbers between the API and couch and they're the same.

**Pull request merged**
