### PR TITLE
Icds reports google analytics

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @emord,
I have added google analytics events and route tracking for dashboard.
Let me know if you have any questions.
Regards, Dawid

### CODE REVIEW

**Comment by emord** [comment]
@orangejenny I think we can ignore these stickler warnings, but can you verify that?

@calellowitz I think you might know the most about this code. Can you verify that this will only include GA and not any of our other analytics or google tag manager? (I noticed a reference to a `global.html`)

**Comment by orangejenny** [comment]
> I think we can ignore these stickler warnings, but can you verify that?

Global variables aren't great, but it seems that horse is pretty far out of the barn already when it comes to this dashboard so yeah, ignoring those seems fine. The parse error is worth looking into, though.

**Comment by orangejenny** [comment]
Will leave it to @calellowitz to review more thoroughly, but as is this isn't going to send any data because [analytics are only enabled for saas environments](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/analytics/templates/analytics/initial/global.html#L2-L6).

**Comment by calellowitz** [comment]
@dmydlo 
As jenny said, the `hq/analytix/google` invocation of analytics will not work on the dashboard since normal hq analytics are disabled on the ICDS server. The dashboard uses a simple google provided html snippet here https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/templates/icds_reports/dashboard.html#L24 which refers to this page https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/analytics/templates/analytics/google.html

I think you should be able to do most of the event tracking here with the `ga` variable created there instead of the `google` one you use but let me know if you have any questions

**Review by calellowitz — APPROVED** [review]
Looks good to me. thanks

**Pull request merged**
