### PR TITLE
don't auto create ES indices

### PR DESCRIPTION
**Pull request by sravfeyn**
Two main changes.
1. HQ manages all index creation and doesn't depend on the fact that ES autocreates an index if one doesn't exist. So, we can turn off `action.auto_create_index` which prevents auto index creation. 
2. Make docker setup use the elasticsearch.yml file

### CODE REVIEW

**Comment by dannyroberts** [comment]
Looks okay to me, but could you provide a bit more of a description? More context & motivation would be helpful

**Comment by sravfeyn** [comment]
Hey @dannyroberts I updated the description now, I discovered as part of alias work, that if we send docs to ES without creating indices, ES automatically creates those indices, that's not good, so this will make such code fail.

**Review by snopoke — APPROVED** [review]

**Comment by sravfeyn** [comment]
@dannyroberts this is g2g?

**Review by dannyroberts — APPROVED** [review]

**Comment by sravfeyn** [comment]
It looks like this config is [already set](https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/elasticsearch/templates/config/elasticsearch.yml.j2#L84) on all the envs correctly just that the travis wasn't using the setting, so no extra work to roll out on envs.

**Pull request merged**
