### PR TITLE
require build version 2.43 or higher for training modules

### PR DESCRIPTION
**Pull request by nickpell**
@amstone326 We may want to hold off merging this until 2.43 is live on ICDS.

### CODE REVIEW

**Comment by amstone326** [comment]
@nickpell Adding the 'hold off on merge' label to this based on our slack discussion. Once 2.43 is released I'll try to remember to ping back here!

**Comment by nickpell** [comment]
beat you to it

**Review by proteusvacuum — APPROVED** [review]

**Review by orangejenny — CHANGES_REQUESTED** [review]
Can you use https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/feature_support.py instead of directly checking the version?

**Review by orangejenny — APPROVED** [review]

**Comment by nickpell** [comment]
@amstone326 I saw 2.43.0 was live on the play store - is this good to merge?

**Pull request merged**
