### PR TITLE
Added missing report to the settings file

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi,

I added missing configuration in settings for one report which was added in this PR: https://github.com/dimagi/commcare-hq/pull/18933

Please let me know if you have any questions

Regards,
Łukasz

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Comment by lwyszomi** [comment]
@kaapstorm @proteusvacuum Could you kick off the build, I think fail is not related to my changes.

**Comment by proteusvacuum** [comment]
Kicked build

**Review by proteusvacuum — APPROVED** [review]

**Comment by lwyszomi** [comment]
@proteusvacuum tests pass

**Comment by proteusvacuum** [comment]
merged already :)

**Comment by lwyszomi** [comment]
@proteusvacuum In the same moment you merged the PR and I added the comment :)

**Pull request merged**
