### PR TITLE
Fixed problems in care reports

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?217204#1138511

### CODE REVIEW

**Comment by sravfeyn** [comment]
Pasting Kamil's note from the ticket
>Could you run commands below on prod once this PR: https://github.com/dimagi/commcare-hq/pull/11491 is merged and deployed?

> ./manage.py ptop_fast_reindex_fluff care-macf-malawi custom.care_pathways.models.GeographyFluffPillow

> ./manage.py ptop_fast_reindex_fluff care-macf-malawi custom.care_pathways.models.FarmerRecordFluffPillow

**Comment by czue** [comment]
@snopoke are you the right person to review this?

**Comment by snopoke** [comment]
not me but changes look OK

**Comment by snopoke** [comment]
Assigned ticket to interrupt

**Pull request merged**
