### PR TITLE
Set minimum year to 1950

### PR DESCRIPTION
**Pull request by emord**
@orangejenny pretty sure this is not want you wanted when you suggested it. https://manage.dimagi.com/default.asp?273985#1500027

We currently use daterangepicker 2.1.13, but the docs are for 3.x. I didn't see anyway to get a versioned of the docs, so I looked at the code and found `minDate` instead of `minYear`: https://github.com/dangrossman/daterangepicker/blob/v2.1.27/daterangepicker.js Also we can't currently upgrade because we have an angular-daterangepicker dependency. I think we can get rid of that, but guessing you know most about the state of removing angular and how that library may be used.

This works in always showing the minimum as 1950, but you can no longer go past that. previously it appears that this works by using a window of x years. By default it goes back 50 years to 1968. When you select 1968, the dropdown will then go back to 1918, which seems not ideal, but better than this. Looking through the code it does not seem possible to change this window

### CODE REVIEW

**Comment by orangejenny** [comment]
> This works in always showing the minimum as 1950, but you can no longer go past that.

That does seem slightly worse than the current behavior.

> Also we can't currently upgrade because we have an angular-daterangepicker dependency.

`angular-datepicker` was added fairly recently in https://github.com/dimagi/commcare-hq/pull/18486 for the champ reports, which have since been converted to knockout. I don't think we use it in HQ's angular. How about removing `angular-datepicker` and upgrading daterangepicker to v3?

**Comment by emord** [comment]
image

FWIW the UI would change a bit. don't know how much of an issue that would be. (this will go on staging on the next staging deploy)

**Comment by orangejenny** [comment]
Those dropdowns are kind of ugly/sharp-cornered, but not a reason to avoid upgrading.

**Comment by emord** [comment]
@orangejenny I'm satisfied with my testing, if you think that this is good to go from a UX perspective

**Comment by orangejenny** [comment]
@emord go for it

**Comment by nickpell** [comment]
Is this expected?

```
$ bower install
bower                     invalid-meta for:/Users/Nick/commcare-hq/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower bootstrap-daterangepicker#^2.0.0           cached https://github.com/dangrossman/bootstrap-daterangepicker.git#2.1.27
bower bootstrap-daterangepicker#^2.0.0         validate 2.1.27 against https://github.com/dangrossman/bootstrap-daterangepicker.git#^2.0.0
bower bootstrap-daterangepicker#3.0.3            cached https://github.com/dangrossman/bootstrap-daterangepicker.git#3.0.3
bower bootstrap-daterangepicker#3.0.3          validate 3.0.3 against https://github.com/dangrossman/bootstrap-daterangepicker.git#3.0.3

Unable to find a suitable version for bootstrap-daterangepicker, please choose one by typing one of the numbers below:
    1) bootstrap-daterangepicker#^2.0.0 which resolved to 2.1.27 and is required by angular-daterangepicker#0.2.2
    2) bootstrap-daterangepicker#3.0.3 which resolved to 3.0.3 and is required by CommCareHQ

Prefix the choice with ! to persist it to bower.json
```

**Comment by emord** [comment]
@dimagi/team-commcare-hq You may need to run `bower prune` before `bower install` on your next updates of bower, because this PR removes a library that has an old version of ` bootstrap-daterangepicker` as a depenedency

**Pull request merged**
