### PR TITLE
preserve user group ids and group names in ES on user save

### PR DESCRIPTION
**Pull request by dannyroberts**
previously saving the user would wipe its group membership by excluding __group_ids and __group_names

Fixes https://manage.dimagi.com/default.asp?251023.

I should test this on staging to make sure it works the way I think it does, but what do you think of the approach? The other option is to pull these from what's currently in elasticsearch, but pulling from source of truth seems better to me, even if it's somewhat redundant.

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]
this seems like the right and in the most foolproof place to do it to me

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
@dannyroberts build fail potentially real?

**Comment by dannyroberts** [comment]
yeah, pushed a fix, but there may be other test failures. Basically this adds a db call where there wasn't one before, which incidentally affects `SimpleTestCase`s. Easy solution is to mock patch them to have `Group.by_user` just always return `[]` for those tests that aren't specifically testing that functionality.

**Comment by dannyroberts** [comment]
I've also discovered that there's no mechanism to _remove_ group membership from users in ES when a group saved after removing a user. But tested that the thing I was trying to fix is now fixed on staging, so I'm going to merge.

**Pull request merged**
