### PR TITLE
[ICDS Dashboard]Using CSV format so that '\' is not special character

### PR DESCRIPTION
**Pull request by Rohit25negi**
##### SUMMARY
Currently `\` is considered as a special character because of which its throwing error in other parts of dashboard not here in this code.  This is because the default format in copy is text where `\` is a special character. To resolve that we would have needed to replace all instances of `\`(in column values) with  `\\\\`. It could be tricky and it also does not take care of `"` around the cell value. But  changing mode to csv resolves  both problem. 

##### FEATURE FLAG
NA

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
I think you either need to skip the first line or add  the `HEADER` to your query. Otherwise, it will try to read all the headers in as a value.
Additionally, how well tested is this?

**Comment by Rohit25negi** [comment]
> I think you either need to skip the first line or add the `HEADER` to your query. Otherwise, it will try to read all the headers in as a value.
> Additionally, how well tested is this?

hey, I already added HEADER in my query.
I have tested this pretty heavily on the django shell. If you want I can test it on India server as well.

**Comment by Rohit25negi** [comment]
@calellowitz  tested on India Server. Final state of code working as expected.

**Comment by calellowitz** [comment]
> hey, I already added HEADER in my query.

I might be missing something obvious, but where is this?

**Comment by Rohit25negi** [comment]
Ha ha. Sory i removed the header in my second commit after i made this
comment. And removed the first line from the data

**Comment by Rohit25negi** [comment]
@calellowitz  fixed the test cases as well. 
All work on this PR is done. This is good for final review and merge

**Review by snopoke — APPROVED** [review]

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
