### PR TITLE
Drop cmitfb toggles

### PR DESCRIPTION
**Pull request by orangejenny**
Don't merge until https://github.com/dimagi/commcare-hq/pull/11794 is merged & run.

@emord 
cc @sravfeyn 

resolves http://manage.dimagi.com/default.asp?226670

### CODE REVIEW

**Comment by emord** [comment]
@orangejenny should this get merged once conflicts are resolved? #11794 was merged/run a while ago

**Comment by orangejenny** [comment]
@emord Fixed merge conflicts, thanks for the reminder. #11794 was merged, it wasn't run. But yeah, it should be run on prod & india (I'll likely do it tomorrow morning/lunch) and then this can be merged.

**Comment by emord** [comment]
Ah. I thought that was the one we ran before release. Looks good to go once your run it

**Comment by orangejenny** [comment]
decided to wait until https://github.com/dimagi/commcare-hq/pull/12502 is merged...but regardless, should happen sometime this week.

**Comment by emord** [comment]
merged #12502 but will respect the open for review tag

**Comment by orangejenny** [comment]
@emord Feature-flagged domains have all been merged (prod + india), so this can go into tomorrow's deploy.

**Pull request merged**
