### PR TITLE
Select2 not returning expected results

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?256667

Seems that the results text itself can't be truncated without interfering with search.

Introduced in https://github.com/dimagi/commcare-hq/pull/16644

@benrudolph / @biyeun

### CODE REVIEW

**Comment by biyeun** [comment]
😱

**Comment by biyeun** [comment]
now we're really going to have wrapping issues. UGH this select2 widget.

**Comment by orangejenny** [comment]
> now we're really going to have wrapping issues

?? This shouldn't affect how the widget is displayed, just the search.

**Comment by biyeun** [comment]
ohhhhh i see what you did here. ok cool

**Pull request merged**
