### PR TITLE
Migrate Dhis2Connection from couch to sql (3 of 3)

### PR DESCRIPTION
**Pull request by orangejenny**
Branches off of https://github.com/dimagi/commcare-hq/pull/26399, first new commit is "Removed Dhis2Connection"

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Review by kaapstorm — APPROVED** [review]

**Comment by orangejenny** [comment]
Added a few commits to rename `SQLDhis2Connection` to `Dhis2Connection`. I had some merge conflict issues, so It's probably easier to review the PR as a whole.

**Review by kaapstorm — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by orangejenny** [comment]
Doing some commits to fix Travis. No need to re-review for now.

**Comment by orangejenny** [comment]
11c3aa03495f99fd6f06d190ffaa6f03756e01ad fixes tests, though in a way that feels sketchy. If no one objects to that commit, I'll probably roll this out tomorrow.

**Comment by orangejenny** [comment]
The issue with tests was that `0006_sqldhis2connection.py` names the table `dhis2_sqldhis2connection`, it still has that name when the `0007_populate_sqldhis2connection` is run, and then it gets renamed to `dhis2_dhis2connection` in `0008_rename_sqldhis2connection`. If you run the `0007` migration after the code has renamed the `SQLDhis2Connection` class to `Dhis2Connection`, the default table name doesn't work properly.

Renaming tables/classes is more troublesome than I expected; I'm planning to update the docs to suggest using `MyClass.objects.model._meta.db_table` to specify the expected final table name in the very first PR, and then remove it when the class is renamed, rather than have to deal with this again.

**Review by millerdev — APPROVED** [review]
Seems reasonable to me, and I agree, this is a pain. Your plan for future migrations seems solid.

**Comment by orangejenny** [comment]
Deployed to prod, verified SQL data matches old couch data.

**Pull request merged**
