### PR TITLE
disable gsid custom code

### PR DESCRIPTION
**Pull request by snopoke**
@benrudolph

### CODE REVIEW

**Comment by snopoke** [comment]
Must also remember to actually delete the view from couch.

**Comment by benrudolph** [comment]
:+1: feel free to self merge. wasn't sure if you wanted to follow up with your comment about deleting the view or not.

**Comment by snopoke** [comment]
I meant using the `prune_couch_views` management command once this has been deployed

**Comment by benrudolph** [comment]
ah got it thanks

**Pull request merged**
