### PR TITLE
Migrate riak blobs to other riak

### PR DESCRIPTION
**Pull request by emord**
This allows you to copy all external attachments stored in riak from one domain or in a zip file to either a zip file or another riak cluster.

Going to test this out by copying attachments from staging to my local install

@snopoke @czue

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 9 - F401 'settings' imported but unused
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 34 - E124 closing bracket does not match visual indentation
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 40 - E124 closing bracket does not match visual indentation
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 46 - E124 closing bracket does not match visual indentation
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 52 - E124 closing bracket does not match visual indentation
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 57 - E124 closing bracket does not match visual indentation
* corehq/blobs/management/commands/migrate_blob_to_other_datacenter.py, line 62 - E124 closing bracket does not match visual indentation

**Review by millerdev — CHANGES_REQUESTED** [review]
Did you consider using the existing [migration framework](https://github.com/dimagi/commcare-hq/blob/d329426d1dff4b99422475485821d587b7f65a97/corehq/blobs/migrate.py)? You're re-implementing a lot of what that already does. Seems like it would be much simpler to implement another class similar to [`BlobDbBackendMigrator`](https://github.com/dimagi/commcare-hq/blob/d329426d1dff4b99422475485821d587b7f65a97/corehq/blobs/migrate.py#L232), and you'd get a lot of things for free like resumability and not loading everything into memory at once.

**Comment by emord** [comment]
> Did you consider using the existing migration framework?

d'oh. you mean like having a zip file as a db backend? That just clicked for me. Thanks

Does look like I'll have to create support for SQL blobs and filtering based on domain, but agreed that that makes a lot of sense

**Comment by emord** [comment]
closing in favor of using existing migration framework

**Pull request closed without merging**
