### PR TITLE
Add ability to search for deactivated user data

### PR DESCRIPTION
**Pull request by pr33thi**
- Add ability to search for deactivated user data
- Adds a label to that username to make it clear that the user is deactivated

This is working off of this PR: 
https://github.com/dimagi/commcare-hq/pull/21259

Which I reverted here (to ensure this change would be rolled out at the same time as that):
https://github.com/dimagi/commcare-hq/pull/21265

This is the only commit that wasn't on that previous PR:
https://github.com/dimagi/commcare-hq/pull/21266/commits/eccb148c8bd4030f13863c9941b7eba2d456aaa1

### CODE REVIEW

**Comment by pr33thi** [comment]
Note to self: look at this comment:

https://github.com/dimagi/commcare-hq/pull/21265#issuecomment-406429018

**Review by esoergel — APPROVED** [review]

**Comment by nickpell** [comment]
(kicked tests)

**Review by esoergel — APPROVED** [review]
Out of curiosity, was `pv_is_active` a reference to your initials?

**Comment by pr33thi** [comment]
@esoergel yes it is haha. I actually am probably going to overhaul this a little bit (and remove all references to my initials) as of a meeting I had earlier this morning, so I'll be closing this pr for now.

**Pull request closed without merging**
