### PR TITLE
Update ES index.max_result_window setting in docker

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
@czue I said a few days ago that I would PR this, but I just found it in an un-PR'd branch, so I must have not.

### CODE REVIEW

**Review by czue — APPROVED** [review]
thanks

**Review by biyeun — APPROVED** [review]

**Comment by millerdev** [comment]
@dannyroberts what, if any, impact does this have for people running ES in docker?

**Comment by czue** [comment]
It fixes a certain category of errors that could come up on certain ES queries (I saw them on submit history)

**Comment by dannyroberts** [comment]
Yeah what Cory said. If you aren't having any issues with ES locally, then no need to try to roll this out. If you are seeing errors related to `max_result_window` then rebuilding (or maybe just restarting?) your ES docker container to pick up this change will help

**Pull request merged**
