### PR TITLE
ignore unused task results

### PR DESCRIPTION
**Pull request by snopoke**
@emord @gcapalbo

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 9 errors:

* corehq/apps/ivr/tasks.py, line 16 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 29 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 66 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 76 - E302 expected 2 blank lines, found 1
* corehq/apps/reports/tasks.py, line 223 - E302 expected 2 blank lines, found 1
* corehq/apps/sms/tasks.py, line 172 - E302 expected 2 blank lines, found 1
* corehq/apps/telerivet/tasks.py, line 18 - E302 expected 2 blank lines, found 1
* corehq/apps/users/tasks.py, line 31 - E302 expected 2 blank lines, found 1
* corehq/apps/users/tasks.py, line 31 - E501 line too long (138 > 115 characters)

**Comment by dimagimon** [comment]
There are 9 errors:

* corehq/apps/ivr/tasks.py, line 16 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 29 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 66 - E302 expected 2 blank lines, found 1
* corehq/apps/reminders/tasks.py, line 76 - E302 expected 2 blank lines, found 1
* corehq/apps/reports/tasks.py, line 223 - E302 expected 2 blank lines, found 1
* corehq/apps/sms/tasks.py, line 172 - E302 expected 2 blank lines, found 1
* corehq/apps/telerivet/tasks.py, line 18 - E302 expected 2 blank lines, found 1
* corehq/apps/users/tasks.py, line 31 - E302 expected 2 blank lines, found 1
* corehq/apps/users/tasks.py, line 31 - E501 line too long (138 > 115 characters)

**Comment by czue** [comment]
good stuff. did you have a process for ensuring that we weren't using the results of these or did you just manually look up each one?

**Comment by snopoke** [comment]
Manually looked at each one. Also excluded any that do progress updates.

**Comment by gcapalbo** [comment]
What's the reason for introducing this?

Also, does this mean that we won't be able to view the running / completed status for these tasks in flower?

**Comment by snopoke** [comment]
This comes from the celery best practices:
http://celery.readthedocs.org/en/latest/userguide/tasks.html#task-best-practices

Flower doesn't use task results, it uses evens so shouldn't be affected by
this.

On 21 April 2015 at 16:45, gcapalbo <notifications@github.com> wrote:

> What's the reason for introducing this?
>
> Also, does this mean that we won't be able to view the running / completed
> status for these tasks in flower?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/6388#issuecomment-94823110>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by gcapalbo** [comment]
ok sounds good

**Comment by czue** [comment]
:+1:

**Pull request merged**
