### PR TITLE
upgrade sqlalchemy to 1.0.9

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by czue** [comment]
does this need QA? cc @snopoke

**Comment by snopoke** [comment]
Considering how big of a jump this is I think its definitely worth QA. @nickpell did you go through the change logs at all?: http://docs.sqlalchemy.org/en/latest/changelog/

**Comment by nickpell** [comment]
I went through the changelogs from 0.8.2 to 1.0.9; didn't find any red flags.  I did some tests of UCR and sqlagg and didn't find any issues.  Agree QA would be useful, let me know if you have a rough list of other features that would need testing.

**Comment by nickpell** [comment]
relatedly, is there a QA workflow for the custom reports that use sqlalchemy?  (or custom reports more generally? - @christineawhite @nsclark )

**Comment by czue** [comment]
my guess is that @christineawhite and @nsclark don't have anything. sqlagg + ucr + fluff seem like the big ones to me. if all of those work, then I think we could roll this out and just make sure to quickly test custom reports right after the deploy

**Comment by snopoke** [comment]
You should also do the upgrade on fluff and sql-agg which both have their
own tests. That should also give us more confidence in the upgrade.

On 10 November 2015 at 09:29, Cory Zue <notifications@github.com> wrote:

> my guess is that @christineawhite <https://github.com/christineawhite>
> and @nsclark <https://github.com/nsclark> don't have anything. sqlagg +
> ucr + fluff seem like the big ones to me. if all of those work, then I
> think we could roll this out and just make sure to quickly test custom
> reports right after the deploy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/9030#issuecomment-155344244>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by nickpell** [comment]
Update: upgrades to fluff and sqlagg have been tested and merged.  I've poked around with UCR and haven't found any issues.  Is this enough confidence to merge?  I can test custom reports after deploy today.

**Comment by nickpell** [comment]
@czue @snopoke bump

**Comment by czue** [comment]
i'm ok merging this. you still have the "awaiting QA" label on, fyi. if that's a mistake feel free to merge yourself

**Comment by snopoke** [comment]
:+1: what @czue said

**Comment by nickpell** [comment]
sounds good, thanks

**Comment by nickpell** [comment]
custom reports look good

**Comment by czue** [comment]
woot! thanks for pushing this out!

**Pull request merged**
