### PR TITLE
Display github link to commits new to this deploy

### PR DESCRIPTION
**Pull request by esoergel**
@proteusvacuum I liked how you linked to this in your deploy announcement, so I thought I'd whip this up to make that a bit easier.
@sravfeyn ping

### CODE REVIEW

**Comment by proteusvacuum** [comment]
woop!

**Comment by czue** [comment]
nice, though would be even nicer if it goes in the "deploy successful" email

**Comment by czue** [comment]
(and in the deploy history so you can link to it from the system info page)

**Comment by sravfeyn** [comment]
nice! 
Assuming cory's comments can done as a separate PR and merging

**Comment by esoergel** [comment]
@czue those are both good ideas, although I probably won't get to them right away, so anyone else should feel free if they wanna take a crack at it.  I'd never actually seen that [deploy history code](https://github.com/dimagi/commcare-hq/blob/c393a33a1d289777c34a87e07591493d5d3dbce7/corehq/apps/hqadmin/models.py#L5) before, good to know about.

My one caveat is that I think if we store it in the deploy history, we should store the commit hash associated with the tag, as that is guaranteed to be fixed, whereas these tags might eventually be deleted.

**Comment by czue** [comment]
took a crack https://github.com/dimagi/commcare-hq/pull/7422

we're already storing the commit hashes so i just added the links. i think that's fine since they fall off the front page after 5 anyways

**Pull request merged**
