### PR TITLE
Generalize case property list configuration template

### PR DESCRIPTION
**Pull request by NoahCarnahan**
This PR refactors a few parts of the `case_list_properties.html` template and its associated view model (in `detail-screen-config.js`) to make the template suitable for reuse in an upcoming user configurable reports interface.

Changes include:
- moving the `format_warning` and `grip` jQuery elements from the view model into the template/knockout
- adding `block` template tags to sections of the interface that will be overwritten in the child template

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by NoahCarnahan** [comment]
FYI @nickpell

**Comment by dannyroberts** [comment]
can't merge

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by NoahCarnahan** [comment]
Don't merge. Accidentally committed other files.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by NoahCarnahan** [comment]
Good to go now

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dannyroberts** [comment]
This looks good to me. Code reuse is always good, but it then introduces the problem of how to expose the correct interface so that the shared code is solving a well defined problem in a way that the calling code can rely on and that isn't awkward to write against, etc. I'd be interested to sit down with you two at some point to talk about the shared problem and stuff if you ever want another set of eyes.

**Pull request merged**
