### PR TITLE
add blacklisted domains

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Review by gcapalbo — APPROVED** [review]

**Review by benrudolph — APPROVED** [review]
👍 may be easier for you in the future to have this as a toggle. easy to change to toggle if you find it annoying to have to update code everytime

**Comment by snopoke** [comment]
Converted to toggle

**Review by benrudolph — APPROVED** [review]

**Review by gcapalbo — APPROVED** [review]

**Comment by snopoke** [comment]
@gcapalbo can you remind me why we can't migrate these?

**Comment by gcapalbo** [comment]
@snopoke last i saw they use custom code which directly references the old versions of some supply-related models

**Pull request merged**
