### PR TITLE
tweak docs/couchdb.rst

### PR DESCRIPTION
**Pull request by dannyroberts**
- fix title format
- recalculate number of views

### CODE REVIEW

**Comment by dannyroberts** [comment]
Nice to see we've killed 11 views since November! #slowlybutsurely :tada:

**Comment by dannyroberts** [comment]
@proteusvacuum

**Comment by proteusvacuum** [comment]
:+1: 
However, that command only works in bash. 
For zsh:

```sh
find . -path '*_design*/map.js' | wc -l
```

**Comment by dannyroberts** [comment]
@proteusvacuum good call. Feel free to make a PR with that and any other changes you'd like to make after you read through that doc. (Github makes it super easy to edit an RST file, preview it, and PR the change all from the web interface!)

**Pull request merged**
