### PR TITLE
ICDS Reports code refactor

### PR DESCRIPTION
**Pull request by kkrampa**
@emord 
Once we have test coverage I slightly refactored one of the views. Idea is to make code more object-oriented instead of using functions.

Aggregated whole location filter code in one class:
https://github.com/dimagi/commcare-hq/compare/master...lwyszomi:icds-refactor-v2?expand=1#diff-9599cc958d81b2887d4875abb3a1a4c0R225

Views get proper instance of report based on the filters via factory (https://github.com/dimagi/commcare-hq/compare/master...lwyszomi:icds-refactor-v2?expand=1#diff-9599cc958d81b2887d4875abb3a1a4c0R225)

### CODE REVIEW

**Comment by emord** [comment]
tests failed

**Comment by kkrampa** [comment]
@emord Could you restart the build?

**Comment by emord** [comment]
restarted

**Comment by kkrampa** [comment]
✅

**Review by emord — CHANGES_REQUESTED** [review]
Didn't finish reviewing this because this says "refactor", but it looks like you're just adding code. Why isn't this deleting code? for example "refactored adhaar report" adds some files that do queries, but you aren't actually removing any old methods

**Comment by kkrampa** [comment]
Sorry for bothering you with this one. Closing this.

**Pull request closed without merging**
