### PR TITLE
Get rid of extraneous white space from persistent menu navigation

### PR DESCRIPTION
**Pull request by minhaminha**
## Product Description

Removes extra white space in the menu by making the width auto flexible (and tiny bit of padding around the exit button to make it not so squished)

Before:
image

After:
image

Update:
I decided to implement the maximum width sizing (and also proper text wrapping) at Martin's suggestion. Now when either the app name or a menu/form name is too long it'll wrap around like this.

Screen Shot 2024-09-13 at 6 32 36 PM

## Technical Summary

[Jira Ticket](https://dimagi.atlassian.net/browse/USH-4935)

From the ticket: "The framing for this specific ticket is a short-term fix for BHA." This PR is exactly that - a quick and easy fix to unblock users before we start to consider more nuanced design choices found in future planned work like how it'll live alongside form content instead of just being overlaid. 

## Feature Flag

[Persistent Menu Navigation](https://staging.commcarehq.org/hq/flags/edit/persistent_menu_setting/)

### Safety story

Only UI changes

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by MartinRiese** [comment]
we might want to line break at some point.
image

**Review by AddisonDunn — APPROVED** [review]
Approving in light of the "quick fix for the partner" mentality, and since this feature is FF'd so won't be used for other projects.

I think the padding on the X button prevents this, but it might worth double checking that the app name doesn't encroach, so that if you click too close to the X you accidentally click the app name.

**Comment by minhaminha** [comment]
@MartinRiese I was able to figure out how to make the text wrap to the right of the icon! Turns out media object is really only for B4 and flex boxes are king in B5.

@AddisonDunn This is the padding around the exit button so I think it should be fine.
Screen Shot 2024-09-13 at 6 35 05 PM

**Review by MartinRiese — APPROVED** [review]
@minhaminha Just making sure the 400px don't interfere with small screens.

**Comment by minhaminha** [comment]
Making a note that I did test it out on smaller screens and it looks fine / there's no text bleeding out of the menu

**Pull request merged**
