### PR TITLE
Revert "E-mail if isEmailable, not isExportAll"

### PR DESCRIPTION
**Pull request by sravfeyn**
Reverts dimagi/commcare-hq#11776 See [comment](https://github.com/dimagi/commcare-hq/pull/11776#issuecomment-230426985) on PR
Fixes http://manage.dimagi.com/default.asp?231457#1177451 http://manage.dimagi.com/default.asp?231355

@proteusvacuum @benrudolph

### CODE REVIEW

**Comment by sravfeyn** [comment]
Will reopen this PR once discussion on https://github.com/dimagi/commcare-hq/pull/11776 gets confirmed

**Comment by kaapstorm** [comment]
:+1: I'll wait for build.

**Comment by sravfeyn** [comment]
Failed on unrelated issue `The command "scripts/docker test --noinput --stop --verbosity=2 --no-migration-optimizer --divide-depth=1" exited with 1.` Kicked build again

**Comment by sravfeyn** [comment]
✅

**Pull request merged**
