### PR TITLE
Preserve whitespace in app comments

### PR DESCRIPTION
**Pull request by esoergel**
`white-space: pre;` - the poor man's markdown.

@kaapstorm it looks like you added this originally.  Thoughts?

### CODE REVIEW

**Comment by kaapstorm** [comment]
I was never overjoyed with the styling of app comments. Any improvements welcome. 

*(Hmmm. Markdown. Now there's an idea.)*

**Comment by esoergel** [comment]
Yeah, markdown would be lovely.  I could see something like this current feature as a quick summary, and then a whole page of markdown for a detailed description.  This was a 5 minute fix that I find nice, so figured it was worth it.

**Comment by orangejenny** [comment]
There are app comments in a couple of different places (apps, modules, and forms) - this commit shows them all: https://github.com/dimagi/commcare-hq/commit/a90f3ae91b700e476846ebaeb39ad44db7b944a4

It's probably simplest to change the `<div>` to a `<pre>`, which will both preserve whitespace and style the area a bit.

**Comment by kaapstorm** [comment]
:+1:

**Comment by esoergel** [comment]
`<pre>` makes it monospace though, which looks kinda weird.

**Comment by orangejenny** [comment]
yeah, fair enough

**Comment by esoergel** [comment]
Should be g2m now.  Note that this doesn't affect form-builder comments - are those treated differently?

**Pull request merged**
