### PR TITLE
Remove users/by_org_and_team view

### PR DESCRIPTION
**Pull request by esoergel**
For a friday preindex whenever we get to it
@nickpell

### CODE REVIEW

**Comment by czue** [comment]
given that it's just the users db this would affect i'm guessing is fine to merge and preindex whenever

**Comment by czue** [comment]
:+1: from me - won't merge in case you or @dannyroberts are worried but my instinct is that it's completely safe

**Comment by dannyroberts** [comment]
Yup, user db reindexes is freaky fast. I'll just merge and preindex right now.

**Comment by dannyroberts** [comment]
And preindex complete!

**Comment by esoergel** [comment]
awesome!  Thanks Danny!

**Pull request merged**
