### PR TITLE
try rebalancing tests to reduce timeouts

### PR DESCRIPTION
**Pull request by czue**
The third test group has been timing out regularly and the first one seems the shortest, so trying to move them there.

I think I did this right?

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Restarted tests. All workers errored at ~5 min.

**Comment by snopoke** [comment]
Could it be that most case importer tests are taking 122 seconds:
```
corehq.apps.case_importer.tests.test_importer:ImporterTest.testCaseLookupDomainCheck,122.51552152633667
```
Still tyring to figure out why.

**Comment by snopoke** [comment]
Looks like it's kafka:
```
Tue May  5 12:59:33 2020    /tmp/testParentCase-2020-05-05T10:57:32.906413

         214776 function calls (206495 primitive calls) in 120.266 seconds

   Ordered by: cumulative time, call count
   List reduced from 2044 to 200 due to restriction <200>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  120.266  120.266 /home/skelly/src/cchq/corehq/apps/case_importer/tests/test_importer.py:343(testParentCase)
        2    0.000    0.000  120.212   60.106 /home/skelly/src/cchq/corehq/apps/hqcase/utils.py:35(submit_case_blocks)
        2    0.000    0.000  120.204   60.102 /home/skelly/src/cchq/corehq/apps/receiverwrapper/util.py:30(submit_form_locally)
        2    0.000    0.000  120.198   60.099 /home/skelly/src/cchq/corehq/form_processor/submission_post.py:217(run)
        6    0.000    0.000  120.153   20.025 /home/skelly/.virtualenvs/hq/lib/python3.7/site-packages/ddtrace/tracer.py:412(func_wrapper)
        2    0.000    0.000  120.072   60.036 /home/skelly/src/cchq/corehq/form_processor/submission_post.py:367(save_processed_models)
        2    0.000    0.000  120.067   60.033 /home/skelly/src/cchq/corehq/form_processor/interfaces/processor.py:182(save_processed_models)
        2    0.000    0.000  120.032   60.016 /home/skelly/src/cchq/corehq/form_processor/backends/sql/processor.py:94(save_processed_models)
        2    0.000    0.000  120.004   60.002 /home/skelly/src/cchq/corehq/form_processor/backends/sql/processor.py:150(publish_changes_to_kafka)
        2    0.000    0.000  120.004   60.002 /home/skelly/src/cchq/corehq/form_processor/change_publishers.py:7(publish_form_saved)
        2    0.000    0.000  120.003   60.002 /home/skelly/src/cchq/corehq/apps/change_feed/producer.py:42(send_change)
        3    0.000    0.000  120.001   40.000 /usr/lib/python3.7/threading.py:534(wait)
        3    0.000    0.000  120.000   40.000 /usr/lib/python3.7/threading.py:264(wait)
        2    0.000    0.000  120.000   60.000 /home/skelly/.virtualenvs/hq/lib/python3.7/site-packages/kafka/producer/kafka.py:529(send)
        2    0.000    0.000  120.000   60.000 /home/skelly/.virtualenvs/hq/lib/python3.7/site-packages/kafka/producer/kafka.py:655(_wait_on_metadata)
```

**Comment by snopoke** [comment]
found that locally this happens if the kafka docker image isn't running. When it's running this test takes 2s. So I think the issue could be that the kafka docker image is crashing at some point during the bulid.

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/27377

**Comment by czue** [comment]
put a "don't merge" on since this is likely not the right solution (thanks @snopoke )

**Comment by millerdev** [comment]
@snopoke I had noticed a while ago that there are some tests that take something like 1 or 2 minutes because they are blocked on a case lock in combination with `CELERY_TASK_ALWAYS_EAGER = True` (I think) where the task also locks the same case, and therefore has to wait for timeout. Never made time to dig into it deeply, but maybe that's a lead?

**Comment by czue** [comment]
still failed, this clearly isn't the path forward

**Pull request closed without merging**
