### PR TITLE
Pass on release lock error

### PR DESCRIPTION
**Pull request by benrudolph**
@gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
:+1: feel free to self-merge once tests pass

**Comment by czue** [comment]
what scenario would trigger this? something taking a really long time to forward?

**Comment by gcapalbo** [comment]
this would happen every time it has a lot to process because it's acquiring a lock with a 4 minute 50 second timeout but runs for 5 minutes and then tries to release it (so it's always expired by the time it tries to release it).  if it didn't have a lot to process, it wouldn't happen

note this is the periodic process which spawns process repeat record tasks, not the actual process repeat record task itself

**Comment by czue** [comment]
makes sense - thanks for the explanation

**Pull request merged**
