### PR TITLE
Remove migrating_blobs_from_couch flag

### PR DESCRIPTION
**Pull request by millerdev**
Removed from classes:
- Application
- CommcareMultimedia
- XFormInstance

Now that the migrations are complete in all environments (prod, india, swiss).

@proteusvacuum cc @dannyroberts @snopoke

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by proteusvacuum** [comment]
👢 👷

**Comment by millerdev** [comment]
kicked again. All nodes failed at ~4:50, but no clear indication in the logs of what caused the failure.

**Comment by millerdev** [comment]
one more time because this is supposedly an intermittent failure...

**Comment by millerdev** [comment]
The build fails were real. Fixed (and now docker should show a better error).

**Comment by millerdev** [comment]
New test failures are real. Working on it...

**Comment by millerdev** [comment]
✅

**Pull request merged**
