### PR TITLE
Update HQ logo

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?216757

@proteusvacuum / @gcapalbo 
cc @dimagi/product

### CODE REVIEW

**Comment by benrudolph** [comment]
O_o very cool. is there any chance the logo can be vertically centered?

**Comment by orangejenny** [comment]
@benrudolph yes, should be better now

screen shot 2016-03-24 at 6 38 46 pm

**Comment by amsagoff** [comment]
Yesssss

**Comment by benrudolph** [comment]
cha-ching :moneybag:

**Comment by czue** [comment]
nice. can we not also delete the supply/messaging logos and all the code that tries to guess what logo we should show you?

**Comment by orangejenny** [comment]
@czue I can delete the files, but the logic also controls text differences between supply and vanilla; are we removing those?

**Comment by czue** [comment]
oh i dunno. @dimagi/product ?

**Comment by biyeun** [comment]
@orangejenny the flower does not scale for 2x displays, can you add some styling to support 2x please? Otherwise it will look blurry on a number of devices (one of the peeves with the current logo, but didn't prioritize to fix)

**Comment by amsagoff** [comment]
Ro's input was that we could change the logo for Supply, but we didn't
discuss the text changes. I think that's a separate discussion to have.

**Comment by czue** [comment]
@amsagoff not sure from your message whether you're planning on taking next steps - can you clarify what you're suggesting happens next to resolve?

**Comment by amsagoff** [comment]
It looks like we changed the logo for normal and supply domains, which was
the scope of this piece of work. No one has been pushing for text
differences to go away - let me know if it introduces significant tech debt
and I can check with Ro about it, otherwise I don't think there's a reason
to prioritize.

**Comment by czue** [comment]
@orangejenny what are the text differences in question? Seems like it'd be nice to eliminate the supply/messaging customization entirely (except for reports) but not sure what the scope of that is.

**Comment by czue** [comment]
And tabs i guess. :( 

Probably easier to add to #kill than to try and sort out now if not a product priority to unify the UX.

**Comment by orangejenny** [comment]
@czue I just meant the `site_name`, `can_be_your`, `public_site`, and `domain_type` that are defined in `get_per_domain_context`, which look like they're just used within the login flow (though I didn't do an exhaustive search).

So it's differences like whether the login screen says "Learn more about how CommCare HQ can be your mobile solution for your frontline workforce" (and links to prelogin) or says "Learn more about how CommCare Supply can be your mobile logistics solution" (and links to a supply-specific section of prelogin).

Easy to remove, not causing significant tech debt.

**Comment by orangejenny** [comment]
@biyeun Do you mean to serve different images based on screen size (as in https://github.com/dimagi/commcarehq-prelogin/blob/master/static/prelogin/less/components/misc.less#L270-L293), or to use a selector like `@media only screen and (-webkit-min-device-pixel-ratio: 2),(min-resolution: 192dpi)` to then serve a higher-res version of the image?

**Comment by czue** [comment]
@rowenaluk @sheelio see https://github.com/dimagi/commcare-hq/pull/10937#issuecomment-202996617

is it OK if we remove the supply and messaging-specific customizations from the login/sign up page?

(created a [trello card for this](https://trello.com/c/z1bB8qRA/20-custom-login-pages-for-supply-messaging) as well)

**Comment by rowenaluk** [comment]
works for me

On Thu, Mar 31, 2016 at 10:02 AM, Cory Zue <notifications@github.com> wrote:

> @rowenaluk <https://github.com/rowenaluk> @sheelio
> <https://github.com/sheelio> see #10937 (comment)
> <https://github.com/dimagi/commcare-hq/pull/10937#issuecomment-202996617>
>
> is it OK if we remove the supply and messaging-specific customizations
> from the login/sign up page?
>
> (created a trello card for this
> <https://trello.com/c/z1bB8qRA/20-custom-login-pages-for-supply-messaging>
> as well)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/10937#issuecomment-203806161>
>



-- 
Rowena Luk
VP of Strategy
Dimagi, Inc.

Skype: rowenaluk
Cape Town: +27 76 078 8015
Senegal: +221 78 291 23 25
USA: +1 857 919 5178

**Pull request merged**
