### PR TITLE
ILS: Include all groups in help message

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?222874

### CODE REVIEW

**Comment by czue** [comment]
:+1: @gcapalbo do these need swahili translations or anything?

**Comment by gcapalbo** [comment]
@czue yeah we'll need a translation, i just updated the ticket to ask Mike if we should wait for a translation or move forward. 

also @kkrampa i think the R&R handler still raises an exception if any one of the groups is missing. i'm thinking we should make that fail more gracefully but i asked Mike in the ticket to confirm

**Comment by czue** [comment]
@kkrampa @gcapalbo are these still relevant? just happened to see them and seemed like they should either be merged or closed

**Comment by gcapalbo** [comment]
yes, we've been waiting for confirmation in the ticket, i'll follow-up again

**Comment by gcapalbo** [comment]
posted an update in http://manage.dimagi.com/default.asp?222874

**Comment by kkrampa** [comment]
Almost 2 years!

**Comment by orangejenny** [comment]
@czue Saw this pop up in my email and for a second I was scared we were re-opening ILS.

**Comment by czue** [comment]
haha, hope i didn't give you a heart attack!

**Pull request closed without merging**
