### PR TITLE
kill hqadmin Message Logs Across All Domains

### PR DESCRIPTION
**Pull request by dannyroberts**
@gcapalbo This page doesn't load (times out), so I figure if we want this report we have to rewrite it. Sound right?

### CODE REVIEW

**Comment by gcapalbo** [comment]
@amsagoff and @sheelio do you still use this report / should we get rid of it?
@dannyroberts alternatively, all the sms data exists in postgres too right now, so it might be very easy to just write a simple group by query and produce the same data much more efficiently

**Comment by czue** [comment]
let's just kill it and bring it back later if anyone complains :smiling_imp:

**Comment by czue** [comment]
build fail is surprisingly real
```
======================================================================
ERROR: test_authenticate_as (corehq.apps.hqadmin.tests.test_authenticate_as.AuthenticateAsIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/hqadmin/tests/test_authenticate_as.py", line 86, in test_authenticate_as
    resp = self.client.get(reverse(AuthenticateAs.urlname))
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/hqadmin/views.py", line 172, in dispatch
    return super(AuthenticateAs, self).dispatch(*args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 155, in get
    return self.render_to_response(context)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/hqwebapp/views.py", line 687, in render_to_response
    return render(self.request, self.template_name, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 1136, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/hqwebapp/templatetags/menu_tags.py", line 96, in format_sidebar
    sections = s.sidebar_items
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/hqwebapp/models.py", line 1459, in sidebar_items
    'url': reverse('message_log_report')},
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'message_log_report' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
----------------------------------------------------------------------
```

**Comment by sheelio** [comment]
I don't use it directly - there are some columns in the Admin ddomain report that lists # of SMS incoming/outgoing per domain (over last 30 days, and all time).  I do use these on occasion to figure out active SMS projects. 

Does removing this report affect that?

**Comment by gcapalbo** [comment]
@sheelio no, removing this report doesn't affect the project list report

**Comment by dannyroberts** [comment]
Thanks, tests!

**Comment by amsagoff** [comment]
kill it! kill it!

**Comment by gcapalbo** [comment]
ok, good to merge once tests pass

**Comment by dannyroberts** [comment]
great thanks @gcapalbo and @sheelio

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
