### PR TITLE
increase connection pool size for migrations

### PR DESCRIPTION
**Pull request by jmtroth0**
I see a lot of warning like this one `2018-11-29 22:04:58,606 WARNING Connection pool is full, discarding connection: 10.202.20.138` when running the couch sql migration. I am guessing it's because I'm abusing gevent a bit because it's so i/o bound. I think this should fix that, and hopefully make it a bit more efficient

@millerdev @snopoke buddy: @kaapstorm

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Interesting, never seen that before. Are we at all concerned about the load this has on couch?

**Comment by jmtroth0** [comment]
That's a good question, but I haven't seen much evidence of the migration having too much of an impact on couch performance. I'll keep an eye on it as I start using this though.

**Review by millerdev — APPROVED** [review]

**Review by millerdev — APPROVED** [review]
Kicked build, which failed on a test I've seen fail elsewhere recently:
```
FAIL: custom.icds_reports.tests.test_aggregation_script:AggLsAggregationTest.test_agg_ls_2017_05_01_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 365, in test_agg_ls_2017_05_01_1
    sort_key=['state_id', 'district_id', 'block_id', 'supervisor_id']
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 138, in _load_and_compare_data
    self._load_csv(path)
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 94, in _fasterAssertListEqual
    self.fail('Lists are not equal')
AssertionError: Lists are not equal
```

**Comment by jmtroth0** [comment]
thanks @millerdev and @kaapstorm for the travis help

**Pull request merged**
