### PR TITLE
don't use deprecated request.REQUEST in Unicel models

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by czue** [comment]
i'm pretty sure we could quickly check and that all of these are either GET or POST but likely not both

**Comment by nickpell** [comment]
> i'm pretty sure we could quickly check and that all of these are either GET or POST but likely not both

@gcapalbo do you know off the top of your head?

**Comment by czue** [comment]
(guessing we could quickly grep the proxy logs if not)

**Comment by gcapalbo** [comment]
just confirmed that all these parameters always come from GET

**Comment by nickpell** [comment]
updated

**Comment by nickpell** [comment]
@gcapalbo looks like it tests for POST
```
ERROR: testPostToIncomingAscii (corehq.messaging.smsbackends.unicel.tests.test_create_from_request.IncomingPostTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py", line 37, in testPostToIncomingAscii
    response, log = post(fake_post)
  File "/mnt/corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py", line 58, in post
    response = client.post('/unicel/in/', data)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 482, in post
    secure=secure, **extra)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 296, in post
    secure=secure, **extra)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/vendor/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/corehq/messaging/smsbackends/unicel/views.py", line 10, in incoming
    message = create_from_request(request)
  File "/mnt/corehq/messaging/smsbackends/unicel/models.py", line 97, in create_from_request
    sender = request.GET[InboundParams.SENDER]
  File "/vendor/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'send'"
```

**Comment by gcapalbo** [comment]
yeah just saw that - the test is wrong, we can just update this line to use get and pass all the params as get params:

https://github.com/dimagi/commcare-hq/blob/REQUEST-unicel/corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py#L58

**Comment by benrudolph** [comment]
:boom:

**Pull request merged**
