### PR TITLE
Strongly encourage users to not delete users

### PR DESCRIPTION
**Pull request by esoergel**
@sravfeyn
deactivate

### CODE REVIEW

**Comment by esoergel** [comment]
@dimagi/product

**Comment by czue** [comment]
:+1: whenever product signs off. note that the link goes to the confluence page on deactivating users.

**Comment by snopoke** [comment]
Talk about a scary button 👹

**Comment by esoergel** [comment]
(this page: https://confluence.dimagi.com/display/commcarepublic/Create+and+Manage+CommCare+Mobile+Workers#CreateandManageCommCareMobileWorkers-D.Deactivate(Formerly"Archive")andDeleteMobileWorkers)  I thought about also putting in an actual deactivate button, but currently the deactivate button on the mobile workers page has a whole modal confirmation thing, and I wasn't sure if it made sense to duplicate that here.  Happy to revisit if we think that'd make a difference.

**Comment by amsagoff** [comment]
Curious what is motivating this? That might impact how I'm reviewing the
text.

(FYI, I expected the link to take me to a deactivate user page in CCHQ
rather than documentation, but I think we can fix that by tweaking the
wording. Also, we have that text/link in the modal confirmation)

**Comment by esoergel** [comment]
We've had a number of issues recently around users deleting and then recreating mobile workers, so this is more effort discouraging that.  I actually didn't notice the link in the modal until I started looking at the HTML for that feature - I think I (and other people, I imagine) decide that I wanted to delete a user, then click "Delete", and just click past any confirmation stuff as quickly as possible.

My hope was that we can catch their attention before they decide that they want to delete.  Do you think having a "deactivate" button right here would make a difference?  That way it'd be as easy as deleting, if you're already on this page.

**Comment by amsagoff** [comment]
Ah, yeah, if that's the problem I think having the deactivate button here
will be more effective than the extra text. We could add/improve the info
text under each button to summarize what it does and link to this help
page. E.g. "Deleting a mobile worker will permanently delete all data
submitted by that worker"

**Comment by czue** [comment]
another thought would be to change the text of the button to "Delete Mobile Worker and All Their Data" or  similar

**Comment by esoergel** [comment]
Closing this out, as I think the real issue is that users want to wipe all data submitted by that user (because it was testing/training data).  Deactivating isn't really the right workflow in that use-case, but I do think we should try directing them to better options.

**Pull request closed without merging**
