### PR TITLE
Bitly once

### PR DESCRIPTION
**Pull request by benrudolph**
@proteusvacuum i've reworked the bitly generation to only get the modal on click. some of the logic confused me a bit, so i wanted your keen eye to make sure i didn't do anything crazy (and i think you were last to touch). http://manage.dimagi.com/default.asp?219698

@dimagi/product this is what it now looks like:

On initial load:
screen shot 2016-03-03 at 6 24 43 pm

On failure to get app code:
screen shot 2016-03-03 at 6 24 10 pm

On success of getting app code:
screen shot 2016-03-03 at 6 24 48 pm

### CODE REVIEW

**Comment by amsagoff** [comment]
This is what I envisioned! 

For some reason, "Enter App Code" doesn't look like a button to me (it's flat?)

I should have thought of this before, but I now notice "Scan Application Bar Code" and "Enter App Code" both initiate a further action, so they should have the same style. 

Path of least resistance here is probably making "Enter App Code" a link like the barcode action. 

since I've wandered into UX territory: @orangejenny @biyeun

**Comment by orangejenny** [comment]
Looks good. Agree that making "Enter App Code" a link might look better. Other minor ux tweaks:
- When the app code isn't available, remove or disable the "Enter App Code" button/link
- When the app code is generated, include some explanatory text, like "Enter app code on installation screen: 1ppzVvn"

**Comment by proteusvacuum** [comment]
Looks good! That was my first PR :neckbeard: 

I would also advocate for the use of ellipses after both of those links to suggest that there is a followup action that will need to be taken. 

Agree with Jenny's points

**Comment by benrudolph** [comment]
cool that makes sense to me. i like the ellipsis idea too. so to finalize it should be:

Scan Application Barcode...

Enter App Code...

and then Enter App Code turns into "Enter app code on installation screen: `1ppzVvn`"

:neckbeard: i think this code has just gone through too many iterations without a refactor

**Comment by amsagoff** [comment]
The ellipses are kind of weird to me, I don't think we use them to indicate
an action anywhere else on the site. But will defer to Jenny

**Comment by orangejenny** [comment]
Agree with dropping ellipses. If anything, make them both buttons to make them obviously actions. (Leaving them as links is fine, too, don't think it's a big deal either way.)

**Comment by benrudolph** [comment]
k updated:

screen shot 2016-03-04 at 1 20 05 pm
screen shot 2016-03-04 at 1 14 42 pm
screen shot 2016-03-04 at 1 14 59 pm

@orangejenny disabling a link is actually a bit more trouble than i think it's worth. instead i decided to hide the button when it's loading and when it fails

**Comment by orangejenny** [comment]
> disabling a link is actually a bit more trouble than i think it's worth

Agreed. New screenshot looks good to me.

**Comment by amsagoff** [comment]
:star:

**Comment by benrudolph** [comment]
:white_check_mark:

**Comment by czue** [comment]
looks good to me but didn't review closely so will let @orangejenny or @proteusvacuum push the button

**Comment by proteusvacuum** [comment]
:computer: :1234: :iphone: :+1:

**Pull request merged**
