### PR TITLE
[ci skip] add comment about side effects of FIX_LOGGER_ERROR_OBFUSCATION

### PR DESCRIPTION
**Pull request by czue**
@millerdev just banged my head against this for a while trying to figure out why i couldn't test http://manage.dimagi.com/default.asp?177091

### CODE REVIEW

**Comment by czue** [comment]
up for grabs

**Comment by snopoke** [comment]
I've also banged my head on that one before

**Comment by benrudolph** [comment]
hugely so when doing the error email. i almost feel like we should print a message saying that: Logger X got changed to this logger. so we know what's happening

**Comment by millerdev** [comment]
Another solution would be to make it possible to import `couchlog.handlers.CouchHandler` without importing `settings` (or anything else that depends on django being in some partially good state when logging is configured) as a side effect. Then we wouldn't need this silly hack that I implemented.

**Pull request merged**
