### PR TITLE
Releases on demand

### PR DESCRIPTION
**Pull request by orangejenny**
If the deploy page is accessed from one of the other app_view pages (settings, multimedia, languages, copy, delete), load content only, rather than refreshing the whole page.

This only hits the server the first time the deploy link is clicked, as I don't think there's anything else you can do in app manager that would require the deploy page to be re-generated.

There's some code duplication here with github.com\dimagi\commcare-hq\pull\10319 which I'll deal with in another PR.

@proteusvacuum

### CODE REVIEW

**Comment by czue** [comment]
very cool! :snowman:

**Comment by proteusvacuum** [comment]
LGTM, but there are conflicts :melon:

**Comment by orangejenny** [comment]
merge conflict resolved, just waiting on tests

**Comment by snopoke** [comment]
:candy:

**Comment by proteusvacuum** [comment]
:boot: :construction_worker:

**Pull request merged**
