### PR TITLE
Move py3 Dockerfile to root of repo

### PR DESCRIPTION
**Pull request by millerdev**
https://github.com/docker/hub-feedback/issues/371#issuecomment-279184690

@nickpell

### CODE REVIEW

**Comment by millerdev** [comment]
Does not affect tests.

**Comment by millerdev** [comment]
@nickpell I think this part is working now, but the [docker hub build](https://hub.docker.com/r/dimagi/commcarehq_py3/builds/bww2deawzqpzbysq5nwbmob/) is failing due to a requirements issue:
```
Collecting jsonobject-couchdbkit==0.9.0.0 (from -r /vendor/requirements.txt (line 6)) 

  Downloading jsonobject-couchdbkit-0.9.0.0.tar.gz (73kB) 
  
    Complete output from command python setup.py egg_info: 
    Traceback (most recent call last):
      File "<string>", line 1, in <module> 
      File "/tmp/pip-build-ij7_jb3i/jsonobject-couchdbkit/setup.py", line 25, in <module> 
        long_description = file( 
    NameError: name 'file' is not defined 

    ----------------------------------------

[91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ij7_jb3i/jsonobject-couchdbkit/
[0m
Removing intermediate container 3992dcb65412 

The command '/bin/sh -c git config --global url."https://".insteadOf git:// && pip install --upgrade pip && pip install -r /vendor/requirements.txt -r /vendor/dev-requirements.txt --user --upgrade && rm -rf /root/.cache/pip' returned a non-zero code: 1 
```

**Comment by millerdev** [comment]
@nickpell it occurred to me as I was waking up this morning that we can change the branch monitored by docker hub from *master* to some other branch, so we could create a *py3test* branch where we can do whatever is necessary to make the Python3-based docker image build. Of course we will eventually want to merge that into the main line, so would be good to keep it as simple as possible.

🛌 💤 💡

**Comment by nickpell** [comment]
That's a good idea.  I added a branch ```np/py3/docker-image``` and set the py3 docker image to track it: https://hub.docker.com/r/dimagi/commcarehq_py3/~/settings/automated-builds/

**Pull request merged**
