### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by proteusvacuum**
WTF.

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by benrudolph** [comment]
lol

**Comment by benrudolph** [comment]
taking one for the team

**Comment by proteusvacuum** [comment]
https://gist.github.com/proteusvacuum/11b1fd45891c134dba1b

**Comment by proteusvacuum** [comment]
I think there's a way we can make HQ generate those spreadsheets itself? Will be annoying if we have to do that every release. Added to my backlog to look into it when I'm on interrupt next.

**Comment by proteusvacuum** [comment]
:white_check_mark:

**Comment by benrudolph** [comment]
beauty

**Comment by benrudolph** [comment]
agree with trying to autogenerate/make this test more dependable

**Pull request merged**
