### PR TITLE
use size(0)

### PR DESCRIPTION
**Pull request by czue**
@dimagi/scale-team tracked down a few of these (the one in the case activity report could be big)

### CODE REVIEW

**Comment by czue** [comment]
This PR I think addresses anything that was incorrectly using `FormES` or `CaseES`. Not sure what other things I should be looking for

**Comment by snopoke** [comment]
I don't think we're doing aggregations in any other way

**Comment by snopoke** [comment]
:+1: on :white_check_mark:

**Comment by benrudolph** [comment]
think this needs a master merge

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
