### PR TITLE
Fix VCM emails not displaying newlines

### PR DESCRIPTION
**Pull request by orangejenny**
ugggggh

@benrudolph 

Would be nice to go in today's deploy.

### CODE REVIEW

**Comment by benrudolph** [comment]
hahah

**Comment by benrudolph** [comment]
👍

**Comment by benrudolph** [comment]
hmm tests failed, but i don't htink this has any tests. should i just merge?

**Comment by orangejenny** [comment]
That's a rather unlucky test run - one docker error, one `test_transfer_first_doc_order`, one `test_basic_fixture_generation`. Yeah, there isn't test coverage for this, should be fine to merge.

**Pull request merged**
