### PR TITLE
Add commtrack settings to copied domains

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?186397#1046813

I think raising a 404 makes sense here - domains without commtrack settings shouldn't really be going to that page... (unless I misunderstood the ticket). 

@millerdev

### CODE REVIEW

**Comment by czue** [comment]
so I think this is an improvement, but I think we should also create the `CommTrackConfig` for you when you copy a commtrack app from the exchange. I just reproduced the root cause by making a new project from here: https://www.commcarehq.org/exchange/62f1d1f57bf2dded4f39569a124061f4/info/ and then trying to navigate to the commtrack --> sms option.

(fine merging this but think we should leave the ticket open until the latter is also done).

**Comment by czue** [comment]
actually it looks like this also needs to be fixed in some other places, e.g.  /a/[project]/settings/commtrack/project_settings/

**Comment by proteusvacuum** [comment]
If you add a commtrack app to an already existing project, that project doesn't currently get commtrack enabled. We decided to leave it that way for now. 
```
Farid Rener [5:10 PM] 
OK, figured it out. Works if you create a new domain, but not if you add the app to an existing domain.

Cory Zue [5:12 PM] 
ah

​[5:12] 
then let's just mimic that for now

​[5:12] 
and not worry about the second case

Farid Rener [5:13 PM] 
ok. so only generate the CommTrackConfig if it is a new domain?

Cory Zue [5:13 PM] 
yeah

Farid Rener [5:13 PM] 
(and 404 for others?)

Cory Zue [5:14 PM] 
sure. i think those links only show up because the domain has the commtrack flag set so hopefully they don't get triggered much
```

**Comment by millerdev** [comment]
Looks good. Don't feel like I have enough context to merge.

**Comment by czue** [comment]
looks good - thanks!

**Pull request merged**
