### PR TITLE
Deidentified Verbal Autopsy Report

### PR DESCRIPTION
**Pull request by katembu**
New Deidentified Verbal Autopsy Report.
screen shot 2015-07-06 at 10 11 53 am

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 16 errors:

* custom/_legacy/mvp/reports/va_deidentifiedreport.py, line 40 - E501 line too long (131 > 115 characters)
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 1 - Missing name in function declaration.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 13 - ['case_id'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 18 - ['death_month'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 19 - ['death_year'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 22 - ['age_category'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 25 - ['last_chw_visit'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 30 - ['received_treatment'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 33 - ['received_treatment'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 69 - ['no_treatment_reason'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 77 - ['death_place'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 80 - ['death_place'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 83 - ['death_place'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 86 - ['death_place'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 89 - ['death_place'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_verbal_autopsy_indicators/views/all_va_forms_cases/map.js, line 184 - ['medical_reason'] is better written in dot notation.

**Comment by katembu** [comment]
@czue @biyeun Let me know if this report makes sense. 
Its Pulls Data from Completed Verbal Autopsy Forms and display it in report form. Each Case has only one verbal Form which is closed when Verbal Autopsy Interview is done.
Utmost were not expecting more than 300 cases/forms submission per site unless there is disease outbreak.

**Comment by czue** [comment]
@katembu my initial reaction is that we should implement this report in the UCR framework instead of introducing new couch views.

**Comment by katembu** [comment]
@czue  Thanks. Is UCR interface active. Last time I checked it was in Development mode.

**Comment by czue** [comment]
@katembu the framework is production-ready. The UI is not released yet. I would recommend taking a look at the [readme file](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/userreports/README.md) and see if it looks like it would support this. You can also use the static data sources paradigm. The [abt app](https://github.com/dimagi/commcare-hq/tree/master/custom/abt) would be a good place to start.

I know this is frustrating after having done this work, but if we get on a path to switching frameworks now it will significantly improve performance and long term maintainability of these reports. Could you look into it and report back on how feasible it is looking?

**Comment by katembu** [comment]
@czue managed to set it up and displayed one Indicator. Will let you know how it goes tomorrow when I start working on the complex ones.

**Comment by czue** [comment]
awesome! happy to help with some of the complicated stuff if it means we don't need to add new couch views. i'm putting a "don't merge" tag on this for now and will wait for you to report back.

**Comment by biyeun** [comment]
yay UCR for mvp!

**Pull request closed without merging**
