### PR TITLE
rework requirements to fix the docs

### PR DESCRIPTION
**Pull request by czue**
## Summary

This [fixes the documentation build](https://readthedocs.org/projects/commcare-hq/builds/). 

This is a pretty annoying situation. 

https://github.com/dimagi/commcare-hq/pull/28938/ introduced a dependency that doesn't work on readthedocs. And readthedocs doesn't provide an interface for OS-level installations, or a custom docker image, just [mocks](https://docs.readthedocs.io/en/latest/faq.html#my-documentation-requires-additional-dependencies) (which don't help us since the build is failing at the requirements installation step). I also explored whether we really needed all of HQ's requirements to build the docs, but we definitely need a lot of them to get the code-level doc-strings included.

So my conclusion is that unless we want to get off readthedocs and host our own docs (which may actually be a better plan, but I didn't have the energy to pursue it), then we need to explicitly have a separate doc-requirements file ([again](https://github.com/dimagi/commcare-hq/pull/24316/)).

I restructured things to be the most DRY I could think of, by splitting up `requirements.in` into `base-requirements` and `annoying-requirements` and then excluded the latter from `docs-requirements.in`. The other option I considered was just copying `requirements.in` into `docs-requirements.in` and removing the offending libraries, but that seems less future-proof.

:man_shrugging: 

As a side note - two possibly known other issues surfaced during this process:

1. I couldn't run `pip-compile -r requirements/requirements.in` without having a `requirements.txt` already there. I got the following error:
```
Could not find a version that matches greenlet<=0.4.15,==0.4.17,>=0.4.14 (from -r base-requirements.in (line 56))
Tried: 0.1, 0.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.9, 0.4.9, 0.4.10, 0.4.10, 0.4.11, 0.4.11, 0.4.11, 0.4.12, 0.4.12, 0.4.13, 0.4.13, 0.4.14, 0.4.14, 0.4.15, 0.4.15, 0.4.16, 0.4.16, 0.4.17, 0.4.17, 1.0.0, 1.0.0, 1.0.0
Skipped pre-versions: 1.0a1, 1.0a1, 1.0a1
There are incompatible versions in the resolved dependencies:
  greenlet==0.4.17 (from -r base-requirements.in (line 56))
  greenlet>=0.4.14 (from gevent==1.4.0->-r base-requirements.in (line 53))
  greenlet (from django-websocket-redis==0.6.0->-r base-requirements.in (line 41))
  greenlet<=0.4.15 (from gipc==1.1.1->-r base-requirements.in (line 55))
```

2. We have tons of [docs warnings](https://gist.github.com/czue/49e9149f6a7e5b3c5ec59276e35f0806). Do we care?

Both of these seem not great but.... :man_shrugging: 

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

Should be docs only, but it did touch requirements so good to review those changes carefully and confirm nothing of substance was included.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
This sounds super painful! Thanks for dealing with it. I'm not fond of the final situation but I don't see a decent alternative at present.

In the long run it could make sense to host these ourselves or else use github pages (assuming that would allow us to control the build).

> I couldn't run pip-compile -r requirements/requirements.in without having a requirements.txt already there.

I've had this before elsewhere, I don't recall how I resolved it in that case. Did you just copy one of the other files?

> We have tons of docs warnings. Do we care?

Nothing serious but could do some cleaning up!

**Comment by czue** [comment]
> I've had this before elsewhere, I don't recall how I resolved it in that case. Did you just copy one of the other files?

Yep. Seems like something is broken in our dependency chain but it doesn't seem to be causing any problems.

**Review by millerdev — COMMENTED** [review]
Can we rename _annoying-requirements.in_ to _sso-requirements.in_ (and move all SSO requirements in there), and then include it from _test-requirements.in_, and _prod-requirements.in_? I think this would make it unnecessary to have the new _base-requirements.in_

**Comment by czue** [comment]
> Can we rename annoying-requirements.in to sso-requirements.in (and move all SSO requirements in there), and then include it from test-requirements.in, and prod-requirements.in? I think this would make it unnecessary to have the new base-requirements.in

@millerdev what role do you see `requirements.txt` playing in that case? On the current codebase, if you don't have the SSO libs installed then you cant e.g. `runserver` locally, which seems like a bad situation to be in. It might be the case that we could change the code to remove the dependency from non-prod environments, but that's not the case today.

**Comment by biyeun** [comment]
@czue Just some background on these requirements.

I actually had gone through several iterations and great length experimenting with separating out the `sso-requirements` for use only on prod and test (see the commit history in the PR you referenced). This included making SSO an optional app. However, after chatting with @dannyroberts and realizing that SSO would be tightly woven in with HQ in its final state, such a decision would introduce too much complexity and be a far more dangerous option. FYI state that SSO is in now is NOT the final state. What's merged are simply the initial views and models to test that we have everything we need on HQ's side to complete a SAML2 handshake.

I also strongly disagree with the naming of `annoying-requirements` and would be in favor of keeping a separate `sso-requirements` file. I appreciate you taking the time to find a solution, as the docs build was not at the top of my mind. While it certainly is annoying to separate, the name places unnecessary emotion and judgment on valid and necessary work. A `base-requirements` file is, unfortunately, necessary in this case as the dependencies are required to run HQ locally (again there was substantial thought & effort put into avoiding this scenario only to decide it was a bad idea to move in that direction).

**Comment by biyeun** [comment]
another name could be `system-requirements` or some way of indicating that python requirements in these files are closely coupled with brew/apt requirements (as I'm sure the requirements for SSO will not be the only time we'll encounter this)

**Comment by czue** [comment]
Thanks for sharing that additional context @biyeun and I appreciate you weighing in.

I'm sorry about the poorly-chosen name. It was simply meant to represent "[requirements which are more annoying to install](https://github.com/dimagi/commcare-hq/pull/29141/files#diff-2d88edd924033b49783dcb4f93a0ed0ec8aae0b6aac3bad984a2c1d323b93c37R2)", and was in no way intended as a statement on the validity of the work that introduced those packages. I agree a less emotional word would be better. 

It's not perfect, but I think I'll just go with your suggestion of `sso-requirements` for now since it accurately reflects what they are, and we can change it later if others come up. @millerdev and I did brainstorm yesterday on a concise way of describing "requirements which are unable to be installed easily in certain environments" and failed to come up with a better option.

**Comment by czue** [comment]
Ok, merged master and renamed files. if this gets approved after I've signed off for the day could the reviewer please merge? these requirements merges are a bit painful.

**Review by millerdev — APPROVED** [review]

**Review by snopoke — APPROVED** [review]

**Pull request merged**
