### PR TITLE
remove announcements app (from circa 2013)

### PR DESCRIPTION
**Pull request by dannyroberts**
Wait for tests. I'm also going to throw this up on staging and make sure it doesn't 500. Double checked this with @amsagoff who's all for it.

This will conflict trivially with https://github.com/dimagi/commcare-hq/pull/7218 (like url entries next to each other, etc.), but I can resolve that when it comes up, and the two PRs are otherwise totally independent.

### CODE REVIEW

**Comment by snopoke** [comment]
@dannyroberts on a roll :roller_coaster:

**Comment by dannyroberts** [comment]
I think this is good to go, deployed to staging without problems so far.

**Comment by dannyroberts** [comment]
@benrudolph @kaapstorm buddy

**Comment by czue** [comment]
#crushingit

**Comment by kaapstorm** [comment]
Nice!

**Pull request merged**
