### PR TITLE
Ongoing cleanup of FormsByApplicationFilter and drop remote app support

### PR DESCRIPTION
**Pull request by czue**
mostly cleanup but one big change is that this removes the remote app drilldown to select a form. remote app forms will now only show up by XMLNS under "unknown forms".

I checked the proxy logs and no one has tried to drill down by remote app since August (which was as far back as they went). On india there was exactly one instance of someone doing it since August.

As a bonus this also entirely removes a view and couchapp with no reindexing burden.

@dimagi/product in case any concerns about the remote apps.

this was going :blowfish: but the removal of remote apps kind of blows away most of the rest of the changes.

@benrudolph @snopoke @dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/reports/filters/forms.py, line 125 - E127 continuation line over-indented for visual indent
* corehq/apps/reports/filters/forms.py, line 125 - E501 line too long (121 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 165 - E501 line too long (127 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 167 - E501 line too long (130 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 428 - E226 missing whitespace around arithmetic operator

**Comment by czue** [comment]
putting "don't merge" on to give product a chance to sign off

**Comment by amsagoff** [comment]
Good by me! Thanks for doing the proxy log search.

**Comment by czue** [comment]
woop! :white_check_mark:

**Comment by snopoke** [comment]
very nice

**Comment by dannyroberts** [comment]
:heart_eyes:

**Pull request merged**
