### PR TITLE
don't 500 when unauthenticated user hits urls with guided tours

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?227141

@NoahCarnahan

### CODE REVIEW

**Comment by benrudolph** [comment]
would `login_and_domain_required` work if wrapped around the dispatch function?

**Comment by nickpell** [comment]
@benrudolph also works

**Comment by benrudolph** [comment]
arguably more robust than the `if` clause, but not major

**Comment by NoahCarnahan** [comment]
:+1: thanks nick

**Pull request merged**
