### PR TITLE
Set role in bulk upload

### PR DESCRIPTION
**Pull request by emord**
https://docs.google.com/document/d/1Ta9TMnDHxNbYT-oa8_3HbejyK0wsSJXkXD_MbMHZIZY/edit#heading=h.y22a4p42hzym

buddy @czue

### CODE REVIEW

**Comment by czue** [comment]
@benrudolph 
```
======================================================================
FAIL: test_transfer_first_doc_order (corehq.apps.commtrack.tests.test_xml.CommTrackBalanceTransferTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 399, in test_transfer_first_doc_order
    self.check_product_stock(self.sp, product, final, 0)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 228, in check_product_stock
    self.assertEqual(expected_soh, latest_trans.stock_on_hand)
AssertionError: Decimal('50.0') != 150
-------------------- >> begin captured stdout << ---------------------
```
image

:cry:

**Comment by czue** [comment]
:+1: on :white_check_mark: (kicked)

**Comment by czue** [comment]
now conflicts

**Comment by benrudolph** [comment]
😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭

**Comment by benrudolph** [comment]
damn i'm so mad!

**Comment by emord** [comment]
:white_check_mark:

**Pull request merged**
