### PR TITLE
Add user namespace to preview flag

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @esoergel good suggestion

cc: @dannyroberts

### CODE REVIEW

**Comment by esoergel** [comment]
I think you may also need to update this line: https://github.com/dimagi/commcare-hq/blob/9eec196be5ed4d951a951d9725ed23c6ec4c5b07/corehq/apps/cloudcare/views.py#L251-L251

```python
if not couch_user.is_web_user or not toggles.PREVIEW_APP.enabled(domain):
    # If this is called by a mobile user, it's most likely a mistake so we should
    # not close all their cases.
    return json_response({'status': 'fail'}, status_code=400)
```

**Comment by benrudolph** [comment]
good catch, thanks

**Comment by esoergel** [comment]
:memo: :computer: :memo: :computer:
:arrow_down: :hourglass:

**Comment by benrudolph** [comment]
😻 😍 😂

**Pull request merged**
