### PR TITLE
Remove some hqmedia couch views

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
Branched off of https://github.com/dimagi/commcare-hq/pull/26006 - only the last two commits are new.

For deploy after https://github.com/dimagi/commcare-hq/pull/25919 and https://github.com/dimagi/commcare-hq/pull/26006 which remove all references to `hqmedia/by_domain`. There are already no references to `hqmedia/tags`.

Will require reindex because `hqmedia/by_hash` will be the one remaining view in this design doc.

### CODE REVIEW

**Review by emord — APPROVED** [review]
just checked last two commits. looks good

**Review by dannyroberts — APPROVED** [review]
Yup last two commits look good. Good call on a separate PR for the view cleanup that requires a reindex

**Comment by orangejenny** [comment]
deployed to production and india

**Comment by dannyroberts** [comment]
🎉 Nice work @orangejenny!

**Pull request merged**
