### PR TITLE
remove unused sofabed case indexes

### PR DESCRIPTION
**Pull request by snopoke**
Drop a few unused columns and indexes from sofabed tables.

@NoahCarnahan

### CODE REVIEW

**Comment by czue** [comment]
before we merge this should we purge all records from the table with the other doc types?

**Comment by snopoke** [comment]
@czue I did do that already but to be safe we can deploy this first then run the deletions again before this gets merged.

**Comment by snopoke** [comment]
@czue this = https://github.com/dimagi/commcare-hq/pull/7390

**Comment by NoahCarnahan** [comment]
Looks like this can't be merged automatically anymore. (probably because of #7390)

**Comment by snopoke** [comment]
This can only happen after the next deploy anyway.

**Comment by snopoke** [comment]
I'm going to wait till #7390 gets deployed to india before rolling this out

**Comment by czue** [comment]
cool, just ping when you want this merged. :+1: from me

**Comment by snopoke** [comment]
This is GTG.

**Comment by NoahCarnahan** [comment]
Looks like there's a merge conflict now

**Comment by snopoke** [comment]
@NoahCarnahan rebased with master

**Comment by NoahCarnahan** [comment]
:+1: Any need to wait for tests?

**Comment by snopoke** [comment]
I did run them locally so I don't think so.

**Pull request merged**
