### PR TITLE
[bugfix] fix search again workflows in Web Apps

### PR DESCRIPTION
**Pull request by snopoke**
Jira: https://dimagi-dev.atlassian.net/browse/SUPPORT-12986, https://dimagi-dev.atlassian.net/browse/USH-1804
Companion to https://github.com/dimagi/formplayer/pull/1100

Note: must be deployed after or at the same time as the Formplayer PR

## Technical Summary

Since the changes to pass `force_manual_action` in the query data the value must be associated with the correct 'command'. This only impacts the 'see more' and 'default search' workflows since it skips the query screen where the queryKey was being set.

* https://github.com/dimagi/commcare-hq/pull/31152
* https://github.com/dimagi/formplayer/pull/1097

## Feature Flag
SYNC_SEARCH_CASE_CLAIM (search_claim)

### Safety story
Setting the `queryKey` for entity list screens should not affect the other workflows since the value will still get reset on query screens. In examining the code I think this was an issue before (the query data did not have the right key for the 'default search' workflow) but it wasn't noticed because the values being passed had the same effect as if the data was missing.

As evidence of this you can see that this test in the formplayer PR that made the change was passing before with the incorrect 'queryKey' but after the change the 'queryKey' had to be updated to the correct one: https://github.com/dimagi/formplayer/pull/1097/files#diff-d4b07acb174a84dd6775d061dae7329cc1795ded0b517da1876d744cd236fd42R223

### Automated test coverage
None

### QA Plan
I do not think this needs QA but since there have been 2 bugs related to the set of PRs linked above I'm going to request a set or regression tests be run.

https://dimagi-dev.atlassian.net/browse/QA-3996

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by shubham1g5** [comment]
+1 on QA on this just beacause of the fragility around all different use cases of this code. Also checking if there is possibility of adding regression tests around the couple recent bugs we have had.

**Comment by snopoke** [comment]
> +1 on QA on this just beacause of the fragility around all different use cases of this code. Also checking if there is possibility of adding regression tests around the couple recent bugs we have had.

In order to really test this we'd need to run integration tests with Formplayer. I don't think we can currently do that but defer to @orangejenny.

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
We don't have the test infrastructure to run a realistic test, unfortunately, we're reliant on manual regression tests. The web apps js tests are pretty limited.

**Review by orangejenny — APPROVED** [review]

**Comment by snopoke** [comment]
I'm going to merge this so that it can be deployed on Monday. The QA will go on regardless.

**Pull request merged**
