### PR TITLE
Restored test_2b data source

### PR DESCRIPTION
**Pull request by kkrampa**
It seems this one was accidentally removed. I guess it needs to be rebuilt.

### CODE REVIEW

**Comment by kkrampa** [comment]
@NoahCarnahan

**Comment by kkrampa** [comment]
If there are still data in that datasource, can we try to rebuild it in-place?

**Comment by kkrampa** [comment]
After last commit, we need rebuild following data sources: episode_2b, episode_drtb, test_2b, test_drtb.
I think all of them can be rebuild in place.

**Comment by NoahCarnahan** [comment]
Thanks Kamil.

**Comment by NoahCarnahan** [comment]
Data sources are now rebuilt.

**Pull request merged**
