### PR TITLE
Revert Application Error Report from GA

### PR DESCRIPTION
**Pull request by zandre-eng**
## Product Description

The Application Error Report will no longer be accessible to users, unless the new feature flag is enabled for them.

## Technical Summary

Link to ticket [here](https://dimagi.atlassian.net/browse/SC-3591).

The Application Error Report is being moved back into a feature flag. This is because the report has no useful function on production (due to mobile logs being sent to Sumologic).

## Feature Flag

A new `APPLICATION_ERROR_REPORT` feature flag is created.

### Safety story

- Local testing of migration (as well as migration revert)
- Tested on staging

### Automated test coverage

N/A

### QA Plan

No QA planned.

### Migrations

- [X] The migrations in this code can be safely applied first independently of the code

This PR includes a migration to delete the `Role` associated with the `APPLICATION_ERROR_REPORT` privilege. Upon reverting this migration, the `Role` object will be re-created.

This PR reverts what was done in the migration from [this change](https://github.com/dimagi/commcare-hq/pull/33078) which moved the `APPLICATION_ERROR_REPORT` feature flag to a privilege.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Comment by mkangia** [comment]
> This PR includes a migration to delete the Role associated with the APPLICATION_ERROR_REPORT privilege

Should not this be done as a separate follow up PR to avoid errors on HQ in the interim when migrations are run and the code is updated? So this PR should just remove the use of that privilege in the code first and then ones that has been deployed, we should add a new PR to migrate and remove the redundant privilege?

**Comment by zandre-eng** [comment]
> Should not this be done as a separate follow up PR to avoid errors on HQ in the interim when migrations are run and the code is updated? So this PR should just remove the use of that privilege in the code first and then ones that has been deployed, we should add a new PR to migrate and remove the redundant privilege?

@mkangia I was following the process that was done in this PR where the migration and code were done in a single PR. I do agree however, that it might make things easier to have these split off into two PRs. I'll create the necessary PRs and close this one off.

**Comment by zandre-eng** [comment]
Closing this PR off in favour of:
- [Revert Application Error Report from GA (Code Changes)](https://github.com/dimagi/commcare-hq/pull/34514)
- [Revert Application Error Report from GA (Migration)](https://github.com/dimagi/commcare-hq/pull/34515)

**Comment by mkangia** [comment]
> I was following the process that was done in this PR where the migration and code were done in a single PR

@zandre-eng I assume you are referring to where the permission was added. That seems like a safe migration to do before the code changes take place. Removing a record/column are operations that would leave DB in a state that would conflict with the old version of code running on the environment.

**Comment by zandre-eng** [comment]
> I assume you are referring to where the permission was added. That seems like a safe migration to do before the code changes take place. Removing a record/column are operations that would leave DB in a state that would conflict with the old version of code running on the environment.

@mkangia Ah apologies, I forgot to add a link to the PR I was referring to in my previous comment. I was following the structure of [this](https://github.com/dimagi/commcare-hq/pull/33311) PR which I used as an example for how to do a feature revert.

**Comment by mkangia** [comment]
Cool, thanks for sharing that @zandre-eng.
I believe we are doing a good approach here with keeping migration separate. :+1:

**Pull request closed without merging**
