### PR TITLE
Smart linking in web apps: Stack queries

### PR DESCRIPTION
**Pull request by orangejenny**
PR into https://github.com/dimagi/commcare-hq/pull/30441, removed safety info from PR template.

Depends on https://github.com/dimagi/formplayer/pull/1014

This adds HQ support for stack queries: a new XML model and the necessary updates to suite generation.

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by snopoke** [comment]
@orangejenny I was thinking about this and for the smart linking use case I think the form entry should be a normal entry (and not have any queries in it). If the case that get's loaded is from a different domain then the link will be active and take the user to the other domain (instead of going into the form). In the case is from the user's domain then we want the form to work as normal with the usual case management etc.

So what I'm thinking is that I should remove the 'registry' changes to modules that use smart linking. Let me know what you think.

**Comment by shubham1g5** [comment]
> If the case you select isn't a local case then we execute the 'smart link' redirect to the other domain

@snopoke The issue happens in executing the 'smart link' redirect itself. As Jenny [noted](https://github.com/dimagi/commcare-hq/pull/30562#issuecomment-940978448), to do the smart link redirect we need to [know the next screen](https://github.com/dimagi/formplayer/blob/jls/smart-linking-in-web-apps/src/main/java/org/commcare/formplayer/services/MenuSessionRunnerService.java#L121) that's going to come after the case selection and to know that we need to play the formplayer session with the remote case selected. Let me know if it's helpful to offline around that. 

@orangejenny One idea @ctsims mentioned on this is HQ can try to figure out the next screen after case selection by itself when making an app build. I am not sure if that's possible but that would be something to think about. If yes, we can define the complete smart link url with the endpoint id in the suite.xml itself (probably by using an action in case detail screen).

**Comment by shubham1g5** [comment]
@snopoke sorry for the oversight, I was wrong about that. This seems like a good idea and agree that the original navigation issue won't appear in this case. Also agree that we should remove the `if` condition from the stack `push` because of the reason you mentioned. 

My only point of concern on this design would be if having 2 command ids in a single session frame would play out correctly or not. But we would know better on testing.

**Comment by orangejenny** [comment]
@snopoke I tested out the XML above but don't quite have it working. There are two issues, I think both related to it not using the rewind that's usually part of case claim:
1. The `search_case_id` doesn't get renamed to `case_id` - this probably isn't a big deal.
2. When the form is done and `doEndOfFormNav` runs, it hits [this exception](https://github.com/dimagi/commcare-core/blob/bda93dfcb401333716e8acb2a017c83c7aada564/src/main/java/org/javarosa/core/model/instance/ExternalDataInstance.java#L105). This one I'm more stuck on.

As an alternative, I'm experimenting with getting rid of the queries in the entries for smart linking, and instead of adding a new `<query>` element to the stack like in this PR, adding a new `<nav>` element that includes the entire URL. This depends on HQ being able to predict the next screen and figure out the smart linking URL, as @shubham1g5 pointed out, but I think that's possible, similarly to how HQ figures out "Previous Screen" EOF nav.

```
    <action><!-- case search action -->
      ...
      <stack>
        <push>
          <mark/>
          <command value="'search_command.m1'"/>
        </push>
        <push if="instance('results')/results/case[@case_id=instance('commcaresession')/session/data/case_id]/commcare_project = instance('commcaresession')/session/user/data/commcare_project">
          <query id="something" value="'http://localhost:8000/a/DOMAIN/app/v1/123456/endpoint_id/'"/>
        </push>
      </stack>
   </action>
```

**Pull request closed without merging**
