### PR TITLE
Add some hqDefines

### PR DESCRIPTION
**Pull request by orangejenny**
@millerdev 

Needed a short & brainless task to do at the end of the day.  `hqDefine` wrapping to the rescue.

Musing on this work (feel free to ignore)...

This uses `hqDefine` a bit non-traditionally. As documented in the js-guide, an `hqDefine` call typically returns an object that acts as that module's api, and then those functions are then called from other modules. But many of our modules aren't reusable functionality that other js depends on, they're widgets: single-use chunks of code that define the behavior for a piece of UI (whether a small piece or an entire page). For these, I've created `hqDefine` modules that return nothing and instead contain a document ready handler that sets up some event handlers and/or calls `koApplyBindings`. I'm not sure this is going to become our best practice for defining widgets, but it's a step forward: the js is external, the `hqDefine` call acts as a namespace, and the codebase is getting more consistent.

The js I've touched recently is lengthy and has a lot of stylistic variation, but the dependencies aren't particularly complex. Which might mean that a module system won't be a big of a win as I've been thinking it is...Or maybe I haven't hit the more complex areas yet...Or maybe our js could be much more modular but that hasn't been apparent for any number of reasons, so we haven't refactored out the right reusable pieces yet.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 79 errors:

* corehq/apps/appstore/static/appstore/js/appstore_base.js, line 24 - 'gaTrackLink' is not defined. (no-undef)
* corehq/apps/commtrack/static/commtrack/js/products_and_programs.async.js, line 4 - 'BaseListViewModel' is not defined. (no-undef)
* corehq/apps/commtrack/static/commtrack/js/products_and_programs.async.js, line 18 - 'next_or_last' is defined but never used (no-unused-vars)
* corehq/apps/commtrack/static/commtrack/js/products_and_programs.async.js, line 33 - Missing trailing comma. (comma-dangle)
* corehq/apps/commtrack/static/commtrack/js/products_and_programs.async.js, line 40 - 'index' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/admin_restore.js, line 5 - 'myCodeMirror' is defined but never used (no-unused-vars)
'CodeMirror' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/admin_restore.js, line 14 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 8 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 9 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 10 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 11 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 16 - 'd3' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/couch_changes.js, line 19 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 11 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 44 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 54 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 67 - 'ws4redis' is defined but never used (no-unused-vars)
'WS4Redis' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 100 - 'd3' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 108 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 117 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 118 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 119 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 120 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 126 - 'd3' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 128 - 'nv' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 146 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 175 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 181 - Expected '!==' and instead saw '!='. (eqeqeq)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 201 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 211 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 244 - 'map' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 280 - 'map' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 297 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 318 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 324 - 'i' is already defined (no-redeclare)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 328 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 331 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/dimagisphere_helper.js, line 360 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/domain_faceted_report.js, line 30 - 'HQVisualizations' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/domain_faceted_report.js, line 40 - Expected indentation of 8 space characters but found 4. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/hqadmin_base_report.js, line 6 - 'HQReportDataTables' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/project_map.js, line 233 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/project_map.js, line 268 - Unnecessary semicolon. (no-extra-semi)
* corehq/apps/hqadmin/static/hqadmin/js/project_map.js, line 275 - 'map' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/project_map.js, line 296 - 'map' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/project_map.js, line 328 - 'map' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/raw_couch.js, line 8 - 'myCodeMirror' is defined but never used (no-unused-vars)
'CodeMirror' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/raw_couch.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 15 - 'second_str' is already defined (no-redeclare)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 29 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 71 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 78 - 'error' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 82 - Empty block statement. (no-empty)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 205 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 228 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 229 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 230 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 231 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 232 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 233 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 234 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 235 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 242 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 243 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 244 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 245 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 246 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 247 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 248 - Expected indentation of 12 space characters but found 16. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 249 - Expected indentation of 16 space characters but found 20. (indent)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 273 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 293 - Missing trailing comma. (comma-dangle)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 299 - 'alert_user' is not defined. (no-undef)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 303 - 'error' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 307 - Empty block statement. (no-empty)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 315 - Missing semicolon. (semi)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 318 - 'DbComparisons' is defined but never used (no-unused-vars)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 334 - 'couchViewModel' is already defined (no-redeclare)
* corehq/apps/hqadmin/static/hqadmin/js/system_info.js, line 336 - 'couchViewModel' is already defined (no-redeclare)

**Comment by orangejenny** [comment]
(ignoring dimagimon)

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Do you prefer the use of `hqDefine` in these cases, or does it feel like extra boilerplate and a `$(function () { ... });` wrapper would be just as good or better?

Here are the pros/cons I can see:

- Pro/wash: `hqDefine` is great anywhere where names would otherwise leak into the global namespace. Granted, a `$(function () { ... });` wrapper works just as well, so no real benefit in most (all?) cases in this PR.
- Pro: consistency. Using our module system everywhere makes it easier to tell if a module has been converted.
- Con: aside from consistency, `hqDefine` is completely unnecessary biolerplate in some cases.

If you think the boilerplate cruft outweighs the advantage of consistency, I'd be open to considering `$(function () { ... });` as an alternative valid module wrapper if the module is entirely self contained and exports nothing to be used by dependent modules.

**Comment by orangejenny** [comment]
I'm happy to do `hqDefine` because I think it'll fit better with modules later - when/if [this code](https://github.com/dimagi/commcare-hq/pull/12359/files#diff-73c73327e873d0e5f5f4e17c3251a1ceR42) makes it to production, then at that point I'll have to add dependencies but will already have the module named. Also like the consistency.

**Pull request merged**
