### PR TITLE
Enable modeliteration plugin in form builder

### PR DESCRIPTION
**Pull request by millerdev**
This can be merged before, but will do nothing until https://github.com/dimagi/Vellum/pull/306 is merged.
UPDATE: the above statement is wrong.

@emord

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by millerdev** [comment]
Correction: Vellum currently crashes if an unknown plugin is specified in the list of plugins to load. Do not merge yet.

**Comment by millerdev** [comment]
Wait to merge until https://github.com/dimagi/Vellum/pull/307 has been merged (into HQ, not just Vellum)

**Comment by millerdev** [comment]
Wait to merge until https://github.com/dimagi/Vellum/pull/307 has been merged (into HQ, not just Vellum)

**Comment by millerdev** [comment]
dimagi/Vellum#306 has been merged into HQ master, so this is now good to go

**Pull request merged**
