### PR TITLE
split up suite_xml.py

### PR DESCRIPTION
**Pull request by snopoke**
@dimagi/team-commcare-hq hackathon output

Not complete yet but getting there.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 33 errors:

* corehq/apps/app_manager/suite_xml/details.py, line 24 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/details.py, line 80 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/details.py, line 205 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/details.py, line 252 - E123 closing bracket does not match indentation of opening bracket's line
* corehq/apps/app_manager/suite_xml/details.py, line 315 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/entries.py, line 360 - E303 too many blank lines (2)
* corehq/apps/app_manager/suite_xml/entries.py, line 367 - E501 line too long (118 > 115 characters)
* corehq/apps/app_manager/suite_xml/entries.py, line 414 - E501 line too long (129 > 115 characters)
* corehq/apps/app_manager/suite_xml/entries.py, line 812 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/fixtures.py, line 8 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/instances.py, line 64 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/instances.py, line 109 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/suite_xml/menus.py, line 6 - F401 'SESSION_CASE_ID' imported but unused
* corehq/apps/app_manager/suite_xml/menus.py, line 14 - F401 'AdvancedForm' imported but unused
* corehq/apps/app_manager/suite_xml/resources.py, line 34 - E225 missing whitespace around operator
* corehq/apps/app_manager/suite_xml/scheduler.py, line 8 - E501 line too long (120 > 115 characters)
* corehq/apps/app_manager/suite_xml/scheduler.py, line 101 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/utils.py, line 11 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/suite_xml/workflow.py, line 116 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/suite_xml/workflow.py, line 213 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/suite_xml/workflow.py, line 215 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/suite_xml/workflow.py, line 377 - E303 too many blank lines (4)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 1 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 64 - E501 line too long (194 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 65 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 66 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 68 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 69 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 70 - E501 line too long (171 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 273 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/suite_xml_old.py, line 29 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/suite_xml_old.py, line 31 - E301 expected 1 blank line, found 0
* corehq/apps/app_manager/tests/test_suite.py, line 726 - E501 line too long (117 > 115 characters)

**Comment by dimagimon** [comment]
There are 31 errors:

* corehq/apps/app_manager/suite_xml/contributors.py, line 42 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/features/scheduler.py, line 8 - E501 line too long (120 > 115 characters)
* corehq/apps/app_manager/suite_xml/features/scheduler.py, line 100 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/post_process/instances.py, line 64 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/post_process/instances.py, line 109 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 115 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 212 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 214 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 376 - E303 too many blank lines (4)
* corehq/apps/app_manager/suite_xml/sections/details.py, line 24 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/sections/details.py, line 80 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/sections/details.py, line 205 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/sections/details.py, line 252 - E123 closing bracket does not match indentation of opening bracket's line
* corehq/apps/app_manager/suite_xml/sections/entries.py, line 360 - E303 too many blank lines (2)
* corehq/apps/app_manager/suite_xml/sections/entries.py, line 367 - E501 line too long (118 > 115 characters)
* corehq/apps/app_manager/suite_xml/sections/entries.py, line 414 - E501 line too long (129 > 115 characters)
* corehq/apps/app_manager/suite_xml/sections/entries.py, line 812 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/sections/fixtures.py, line 8 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/sections/menus.py, line 13 - F401 'AdvancedForm' imported but unused
* corehq/apps/app_manager/suite_xml/sections/resources.py, line 34 - E225 missing whitespace around operator
* corehq/apps/app_manager/suite_xml/utils.py, line 16 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/suite_xml/utils.py, line 58 - W391 blank line at end of file
* corehq/apps/app_manager/suite_xml/xml_models.py, line 1 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 64 - E501 line too long (194 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 65 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 66 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 68 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 69 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 70 - E501 line too long (171 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 273 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/tests/test_suite.py, line 726 - E501 line too long (126 > 115 characters)

**Comment by dimagimon** [comment]
There are 9 errors:

* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 115 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/suite_xml/sections/details.py, line 252 - E123 closing bracket does not match indentation of opening bracket's line
* corehq/apps/app_manager/suite_xml/sections/fixtures.py, line 8 - W293 blank line contains whitespace
* corehq/apps/app_manager/suite_xml/xml_models.py, line 67 - E501 line too long (194 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 68 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 69 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 71 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 72 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/suite_xml/xml_models.py, line 73 - E501 line too long (171 > 115 characters)

**Comment by snopoke** [comment]
This should be good to go if tests pass

**Comment by czue** [comment]
:tada:

**Comment by dannyroberts** [comment]
Yeah this is so heroic. Even after splitting suite_xml into **sixteen** files, the largest one is still 800+ lines. Big shout out to @snopoke and the hackathon team!

**Comment by kaapstorm** [comment]
\o/ This is great.

**Comment by snopoke** [comment]
:joy:

**Comment by proteusvacuum** [comment]
This is huge. Amazing work @snopoke !! And in the middle of summit no less! :balloon:

**Pull request merged**
