### PR TITLE
Upgrade attrs to 21.4.0

### PR DESCRIPTION
**Pull request by millerdev**
Preparation for use of attrs on the Lookup Tables Couch to SQL migration. A [lot of nice things](https://www.attrs.org/en/latest/names.html#tl-dr) have been added to attrs since 18.2. Going forward the recommended usage pattern is
```py
from attrs import define, field

@define
class Point:
    x = field()
    y = field()
```

The new names have some different and better defaults, but the old `@attr.s` and `x = attr.ib()` way still works.

### Safety story

The change logs have detailed explanations of backward-incompatible changes, none of which appear to be problematic for us. Attrs has a very strong backward compatibility guarantee.

### Automated test coverage

Some of our uses of attrs are covered by tests. Unknown if all are.

### QA Plan

No QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by millerdev** [comment]
FYI @dimagi/team-commcare-hq

**Comment by esoergel** [comment]
@millerdev now that we have access to `@dataclass`, do you think we should continue writing new code with attrs?  I'm not too well versed in the differences, though I understand attrs may be more feature rich.  Might be useful to have some guidelines about when to reach for one vs the other.

**Comment by millerdev** [comment]
@esoergel You're correct, attrs has a bunch of features that are not present in dataclasses. Here's a [reasonable comparison of the two](https://www.revsys.com/tidbits/dataclasses-and-attrs-when-and-why/). Namely, attrs has conversion and validation features that dataclasses does not. There is a new-ish [improvements to (de)serialization](https://github.com/python-attrs/attrs/pull/653) in attrs that I think could be super handy for us.

I think it's fine to use whichever one seems appropriate for your context, although given that it's less feature rich I rarely consider dataclasses unless I am in a situation where I want to only depend on the standard library (usually not when I'm working on HQ).

**Review by joxl — APPROVED** [review]

**Review by snopoke — APPROVED** [review]
Almost seems like we could replace jsonobject with attrs :trollface:

**Comment by millerdev** [comment]
@snopoke that's my hope and plan!

**Pull request merged**
