### PR TITLE
Remove dev requirements, but install test requirements

### PR DESCRIPTION
**Pull request by proteusvacuum**
Should have done this in the first place.

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
I expected the last one to be ok since the `run.sh` script installs `test-requirements`: https://github.com/dimagi/commcare-hq/blob/011d25be3817159dfbea302b2c18c7bddb4dbed6/docker/run.sh#L18

I also checked the build output and `coverage` was definitely getting installed so perhaps it's just in a different location.

**Comment by proteusvacuum** [comment]
Weird. Why are the requirements getting installed twice? From the comment at the top, it looks like `run.sh` only gets run inside the web container... is that the container our tests run in?

**Comment by snopoke** [comment]
I think it's so that the test won't fail if you're adding requirements in the PR - ie. before the container has the updated requirements file.

**Comment by proteusvacuum** [comment]
@snopoke do you think I should try this route, or just abandon this?

**Comment by snopoke** [comment]
I think it's worth a shot

**Pull request merged**
