### PR TITLE
Make it less convenient to ignore flake8 warnings

### PR DESCRIPTION
**Pull request by millerdev**
You must reinstall git hooks (typically done with `git-hooks/install.sh`) to apply this change to your environment.

FYI @dimagi/team-commcare-hq

### CODE REVIEW

**Review by gherceg — APPROVED** [review]
Reasonable modification. Looks good.

**Comment by proteusvacuum** [comment]
I'd never actually seen that we had this... Maybe the first step could be to tell people to install this hook? Unless I'm the only one...

**Comment by orangejenny** [comment]
This is not the direct purpose of this PR, but it bugs me that this hook takes ages to run on merge commits. Now I can just pass `--no-verify`. Wonderful.

**Comment by millerdev** [comment]
Per @proteusvacuum's comment: @dimagi/team-commcare-hq please install at least the pre-commit hook if you don't already have it installed.

**Review by kaapstorm — APPROVED** [review]

**Pull request merged**
