### PR TITLE
add methods to reduce complexity

### PR DESCRIPTION
**Pull request by Robert-Costello**
## Product Description

This is to reduce the complexity of `edit_module_detail_screens` which has been flagged with a `HELPME` message after radon code static analysis. This change reduced the complexity score from an `F` to a `C`
### Safety story

refactor, no logical changes. 

### QA Plan

no QA planned

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by nospame — COMMENTED** [review]
I think this looks good. Just to make sure I understand, is the main purpose of this chunk of code is to build and set `module.search_config`?

**Review by esoergel — APPROVED** [review]
"Hide whitespace" really helps make this readable
https://github.com/dimagi/commcare-hq/pull/33988/files?diff=split&w=1

**Comment by Robert-Costello** [comment]
> "Hide whitespace" really helps make this readable

Wow, that really makes a difference

**Comment by Robert-Costello** [comment]
> I think this looks good. Just to make sure I understand, is the main purpose of this chunk of code is to build and set `module.search_config`?

@nospame yes, that's right. apologies for the slow response to your question.

**Review by esoergel — COMMENTED** [review]
:tada:

**Review by nospame — APPROVED** [review]

**Pull request merged**
