### PR TITLE
Improve error on metrics provider lookup failure

### PR DESCRIPTION
**Pull request by millerdev**
Previously it caused an unhelpful error: `TypeError: 'NoneType' object is not callable`

This error is happening intermittently in Celery tasks on staging.

### Safety story

Very simple change that will ~cause a more helpful error to be raised~ log the error to Sentry and skip the provider when metrics provider lookup fails.

### Automated test coverage

No.

### QA Plan

This PR is to help with an ongoing QA testing of Django 3. See https://dimagi-dev.atlassian.net/browse/QA-4035

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by calellowitz — COMMENTED** [review]
Is it possible to catch these errors, send them to sentry with `notify_exception`, rather than fail a celery task because metrics are improperly configured?

It looks like sometimes `_get_metrics_provider` is called in a `try ... except` block, but often its not, and even where it is, we log that exception in a file where it is way less visible than sentry

**Review by calellowitz — APPROVED** [review]
Thanks!

**Review by snopoke — APPROVED** [review]
Very odd, does that mean Celery is executing the task without fully initialising Django? If that's the case this might point to a more serious issue.

**Comment by millerdev** [comment]
> does that mean Celery is executing the task without fully initialising Django?

I don't know. My working hypothesis is that a stale celery worker was unable to import the metrics provider since the release source code had been removed.

**Comment by snopoke** [comment]
> > does that mean Celery is executing the task without fully initialising Django?
> 
> I don't know. My working hypothesis is that a stale celery worker was unable to import the metrics provider since the release source code had been removed.

👍🏻 that does makes more sense

**Pull request merged**
