### PR TITLE
remove care_benin custom reports

### PR DESCRIPTION
**Pull request by nickpell**
Domain is on a community plan and can't view the custom reports anyway.  We've confirmed with the partner that they don't need them anymore.

@benrudolph

### CODE REVIEW

**Review by czue — APPROVED** [review]
sweet! i think these were our first sql reports. :wave:

**Comment by benrudolph** [comment]
nice!

**Comment by nickpell** [comment]
self-merging approved PR

**Comment by dannyroberts** [comment]
❤️ for UCR Custom Reports. This is the dream; we have arrived. 🌈

**Pull request merged**
