### PR TITLE
Prevent user from creating redundant exports

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAASP-10281

##### SUMMARY
This adds support for saving export download states, so they can be resumed in case of a refresh.

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
I'm guessing that since this solution uses a cookie it will not carry over to other sessions (for example, if a user loads the page on another computer or in a different browser, deletes cookies, etc.). Is that true? Would it be hard to store information about in-progress/canceled downloads on the server so it could be loaded based on the logged-in user?

**Comment by biyeun** [comment]
@millerdev sure, I certainly considered that. this was the lowest input for the best result resolution to this problem, not necessarily the most perfect result. Doing the second route would require making some more calls from the UI to store and clear this information on the server-side, when it was super easy to do this on the client-side. I think the reason this got prioritized is that after talking, Danny and I agreed that this is an easy quick solution for a pretty big win. Most people are not going to switch browser sessions mid-download.

**Comment by dannyroberts** [comment]
Yeah I agree with all that. There's no huge need for this to be foolproof, just that it redirects most users in the course of typical behavior to wait on their already-requested download rather than requesting a new duplicate one. If the user wants to re-create an export so bad that they open up a new browser or clear their cookies (or just happen to do that for some other reason and that results in them recreating an export), we're fine with that.

**Review by dannyroberts — APPROVED** [review]
@biyeun can you think of any situation that would result in a user _permanently_ unable to generate an export because the current one is stuck? Are there any celery states such as when it's been long enough that the task no longer exists that would be registered as the task still being pending but never finishing? We could get around being _totally_ sure by having a way to cancel the current task and start a new one instead (which wouldn't be a fix but would unblock users), but as it is it seems like that's a possible failure mode that a user wouldn't be able to get out of

**Review by millerdev — APPROVED** [review]
> Would it be hard to store...

Sounds like the answer to this is yes. And I agree, the easy win is worth it until we find out there is some common use case that breaks it (if ever).

**Comment by biyeun** [comment]
@dannyroberts 

> can you think of any situation that would result in a user permanently unable to generate an export because the current one is stuck? 

If there is a timeout or error sent to the UI, it will automatically delete the cookie. So as long as every error state we are aware of results in some sort of timeout (which I think there is a check for this) then the user will be able to refresh and restart the export

**Comment by biyeun** [comment]
QA passed. merging this in for the next deploy :)

**Comment by dannyroberts** [comment]
Awesome! I'm surprisingly excited about this :)

**Pull request merged**
