### PR TITLE
Add meta fields to form models

### PR DESCRIPTION
**Pull request by sravfeyn**
@calellowitz

### CODE REVIEW

**Comment by sravfeyn** [comment]
Uh, sorry about the PR format, except the last two commits everything else comes from merge from master

**Comment by calellowitz** [comment]
@sravfeyn I think you are missing migrations?

**Comment by sravfeyn** [comment]
@calellowitz Yeah, thanks, I have pushed them now.

**Review by calellowitz — APPROVED** [review]

**Comment by snopoke** [comment]
Maybe a merge of master into `ce/auto-batches` would be better first?

**Comment by sravfeyn** [comment]
closing in favor of https://github.com/dimagi/commcare-hq/pull/19700

**Pull request closed without merging**
