### PR TITLE
add a soft assert for a loaded domain field on Subscriber

### PR DESCRIPTION
**Pull request by nickpell**
I came across a `ResourceConflict` during testing when a `Subscriber`'s `domain` is  of type `Domain` instead of `basestring`.  I think this is related to a similar error I've seen in production but have been unable to reproduce.  I'm adding a soft assert to help track it down.

### CODE REVIEW

**Comment by nickpell** [comment]
@kaapstorm

**Comment by kaapstorm** [comment]
Failure real; clearly the assert's working though. :stuck_out_tongue_winking_eye:

**Comment by nickpell** [comment]
@kaapstorm

**Comment by nickpell** [comment]
✅

**Pull request merged**
