### PR TITLE
Use lxml's E instead of xml's Element

### PR DESCRIPTION
**Pull request by kaapstorm**
Small refactor. lxml's [E](http://lxml.de/tutorial.html#the-e-factory) is fast with a nice interface. I was working near this code and noticed you'd written a method to do what it does. I thought I'd try E instead. 

@dannyroberts cc @nickpell 

(Trying hard to resist puns.)

### CODE REVIEW

**Comment by dannyroberts** [comment]
Oh, wow, this looks great! Didn't even know `lxml.builder.E` existed—looks way better!

**Comment by dannyroberts** [comment]
build fail real
```
======================================================================
ERROR: setUpClass (corehq.apps.app_manager.tests.test_report_config.ReportFiltersSuiteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_report_config.py", line 135, in setUpClass
    fixture, = report_fixture_generator(cls.user, '2.0')
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/fixtures/mobile_ucr.py", line 45, in __call__
    reports_elem.append(self._report_config_to_fixture(report_config, user))
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/fixtures/mobile_ucr.py", line 90, in _report_config_to_fixture
    rows_elem.append(row_elem)
AttributeError: 'functools.partial' object has no attribute 'append'
```

**Comment by czue** [comment]
:+1: looks great once tests are passing. @kaapstorm does the build fail imply that this code hasn't been run until they ran?

**Comment by kaapstorm** [comment]
@czue, yes, and from your question, I guess that's a Bad Idea. I wanted to get back to what I was doing and thought I'd let Travis run the tests for me. 

In future, should I have labelled this "Do not merge" / commented "Wait for tests", or should I rather not have PRed this until I ran the tests locally? ... Or not trust the tests, and actually run the code by creating a report?

**Comment by czue** [comment]
I think it's extremely dangerous to PR code you haven't run, and you should definitely strive to always run code before it is PR'd (either manually or with tests) or make it very clear that you haven't so that the reviewer can be sure to look extra-close for potentially breaking changes.

Also, the test suite should not be considered a proxy for ensuring the code you wrote has run unless you're sure there is good coverage. Plenty of the code in HQ isn't covered in tests, and given that this is a new area of the codebase for you I would think you should default to thinking there's not coverage, or at least ask someone more familiar with the code first.

**Comment by kaapstorm** [comment]
Thanks @czue. All very good points. In future I'll make sure my code changes have been run.

**Comment by czue** [comment]
@kaapstorm still think this is a great change once it's ready. just ping whenever you've had a chance to test it

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/app_manager/tests/test_report_fixtures_provider.py, line 19 - E126 continuation line over-indented for hanging indent
* corehq/apps/app_manager/tests/test_report_fixtures_provider.py, line 27 - E126 continuation line over-indented for hanging indent
* corehq/apps/app_manager/tests/test_report_fixtures_provider.py, line 36 - E126 continuation line over-indented for hanging indent
* corehq/apps/app_manager/tests/test_report_fixtures_provider.py, line 44 - E126 continuation line over-indented for hanging indent
* corehq/apps/app_manager/tests/test_report_fixtures_provider.py, line 86 - W391 blank line at end of file

**Comment by kaapstorm** [comment]
:white_check_mark: Added a test.

**Comment by dannyroberts** [comment]
Nice. My only hesitation is that it now returns an `lxml.etree._Element` instead of an `xml.ElementTree.Element`. The calling code also uses `xml` (not `lxml`), so I thought it was worth further consideration. I did a basic test locally and I could append an `lxml.etree._Element` to an `xml.ElementTree.Element` and then serialize it without problems. Not sure if it breaks down with something more complicated.

Anyone have any intuition on this? (And if there's any test that tests fixtures at a level where this would get caught, that for me resolves the discussion.)

**Comment by czue** [comment]
I don't have any intuition. I took a quick glance at the [compatibility guide](http://lxml.de/compatibility.html) and didn't see anything obvious that would affect us, but list of small changes is quite long

**Comment by czue** [comment]
@dannyroberts do you think if we (either manually or via a test) sync a user that has both a mobile UCR fixture and other fixtures that would be sufficient?

**Comment by kaapstorm** [comment]
It's definitely worth testing, @dannyroberts. I know `lxml.etree` aims to ducktype `xml.etree.ElementTree` as far as possible (with digressions noted in that [compatibility guide][1]), but in the past I've defaulted to lxml instead of mixing them (... and tests always trump intuitions).

  [1]: http://lxml.de/compatibility.html

**Comment by dannyroberts** [comment]
@kaapstorm I this @czue suggestion is the right level of test (I'm fine if you do it manually, though automated test is of course very welcome). As long as we test that it "basically works" I'm fine with the risk of hitting an edge case in the wild and then reverting; just trying to catch easily forseeable bugs before deploying.

**Comment by kaapstorm** [comment]
Thanks, @dannyroberts, @czue. Using a dummy UCR, here is a report built using lxml's E, inside the rest of the XML built using xml's ElementTree: 

mobile_ucr_using_e

It doesn't have a total row, but it does run every line that uses E.

**Comment by czue** [comment]
thanks for checking on that!

**Comment by dannyroberts** [comment]
:+1: Yeah thanks @kaapstorm! This is a big improvement!

**Pull request merged**
