### PR TITLE
Requirejs: Project Settings > Subscription

### PR DESCRIPTION
**Pull request by orangejenny**
@millerdev / @emord 

[QA ticket](https://manage.dimagi.com/default.asp?280110)

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Kicked the build (intermittent failure).

**Comment by orangejenny** [comment]
missed the Change Plan page, added a commit

**Review by millerdev — APPROVED** [review]

**Comment by orangejenny** [comment]
Removed the commit the migrates Change Plan, because @gbova incorporated those changes into https://github.com/dimagi/commcare-hq/pull/21456/

**Comment by orangejenny** [comment]
Merged master to pull in https://github.com/dimagi/commcare-hq/pull/21722 and added a commit to use the new `include_directories` option. Planning to sanity test one last time on staging and then release tomorrow.

**Review by millerdev — APPROVED** [review]
Really like what you did with `include_directories`—maintaining those lists seemed like an error-prone process.

**Pull request merged**
