### PR TITLE
[ICDS Dashboard] fix for ICDS-747

### PR DESCRIPTION
**Pull request by dhiraj-beehyv**
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/ICDS-747)

##### SUMMARY
In earlier changes for ICDS-747 changes I had missed passing the feature flag for call, this is for fixing that.

##### FEATURE FLAG
ICDS Dashboard

### CODE REVIEW

**Review by Rohit25negi — APPROVED** [review]
Looks good. Did you tested it? @dhiraj-beehyv

**Comment by dhiraj-beehyv** [comment]
> Looks good. Did you tested it? @dhiraj-beehyv

I don't have much data on my local to test it properly.

**Comment by Rohit25negi** [comment]
> > Looks good. Did you tested it? @dhiraj-beehyv
> 
> I don't have much data on my local to test it properly.

I mean, can you check this is not breaking anything on that page.

**Comment by dhiraj-beehyv** [comment]
> I mean, can you check this is not breaking anything on that page.

I ran the local, didn't see any errors

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
