### PR TITLE
Always return `None` if a resource has no data

### PR DESCRIPTION
**Pull request by kaapstorm**
## Summary

This is one of a pair of pull requests that implement two possible solutions to a problem.
[The other one](https://github.com/dimagi/commcare-hq/pull/29342)

**Context:** [QA-2736](https://dimagi-dev.atlassian.net/browse/QA-2736)

**TL;DR:** If a user requests a FHIR resource via the FHIR API, and that resource has no data, either we return `{"id": <case ID>, "resourceType": <resource type>}` or a validation error will be raised if the resource type has other required properties.

I am opening this as a draft pull request because it feels like the wrong solution, but opening it anyway for the sake of discussion.

This change returns `None` to the API if mappings exist, but they return no values. The API will presumably respond to the user with a 404.

But this might not be the best outcome. If mappings exist, it would be reasonable to believe that the administrator intends to return something. If the mappings result in no values, that's a problem, but the problem lies with the administrator, so a silent 404 will hide the problem.

This PR tries to determine the intent of a hypothetical administrator. I am not confident that I've nail it. Do you have any thoughts?

## Feature Flag
"FHIR Integration"

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Safety story

The FHIR API has not been released.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by mkangia** [comment]
Hey @kaapstorm 

>  If a user requests a FHIR resource via the FHIR API, and that resource has no data, either we return {"id": <case ID>, "resourceType": <resource type>}

Can you add more on why this is not good?

**Comment by mkangia** [comment]
sorry, not sure why this comment got missed when browsing the ticket

https://dimagi-dev.atlassian.net/browse/QA-2736?focusedCommentId=128217

So the challenge is that there is a required field according to the FHIR standard, that is not getting populated because its not available on the case or if its not configured for the case.
Then i think i would be in favor of raising an error "ResourceIncomplete", instead of "ConfigurationError" because the configuration is correct but data is not available. Does that make sense?

**Comment by kaapstorm** [comment]
> i would be in favor of raising an error "ResourceIncomplete", instead of "ConfigurationError" because the configuration is correct but data is not available. Does that make sense?

It does make sense.

I feel like it's as if I distrust the person responsible for configuring the integration, and take the data as a brute fact (i.e. the data is "just how it is" and it's up to the admin to "work with what they've got"), where you come from the perspective of trusting the person configuring the integration, and distrusting the data.

I take your point though. I am being unfair on the administrator. It's not necessarily on them that the resource has no data. Perhaps an app changed. Perhaps a case import missed properties that the integration needs.

But I'd prefer to call the new exception "ResourceEmpty" because although being empty guarantees that it's incomplete, it could also be incomplete without us knowing, if it has some data but not everything it should have. Would that be fair?

**Comment by mkangia** [comment]
> I take your point though. I am being unfair on the administrator. It's not necessarily on them that the resource has no data. Perhaps an app changed. Perhaps a case import missed properties that the integration needs.

Yup. There are more contributors other than the person who configures the integration and the data itself, the app builder or data collector.

> But I'd prefer to call the new exception "ResourceEmpty" because although being empty guarantees that it's incomplete, it could also be incomplete without us knowing, if it has some data but not everything it should have. Would that be fair?

Not sure, i would still say "ResourceIncomplete"/"IncompleteResource" or "ResourceMissingInformation", Empty would mean it has no data, which is not what the validation is complaining about. Like you said "it has some data but not everything it should have"

**Comment by kaapstorm** [comment]
> Empty would mean it has no data

That's exactly what's happening. [The resource is empty](https://github.com/dimagi/commcare-hq/pull/29341/files#diff-433e7032abf02a0c78231568078bff8181998607bf011edb22ea4b1d3018041fR204). The validation error is happening because it's missing a required property.

**Comment by mkangia** [comment]
Unless we are planning to add two different exceptions, "ResourceIncomplete", "ResourceEmpty" else then "ResourceIncomplete" would account for both.

Confirming when you say resource empty, you are not referring to a resource property but the complete resource object being empty?

**Comment by kaapstorm** [comment]
> Confirming when you say resource empty, you are not referring to a resource property but the complete resource object being empty?

Sorry, I should have explained the code that I linked to in my previous comment. For each FHIR resource property, line 202 instantiates a ValueSource, which line 203 uses to set a value in the FHIR resource that we are building. If there is no value, the property does not get set. Line 204 checks whether *any* values have been set in the complete resource object. We know from line 200 that it's a dict, so if it's falsey, it's because the whole resource is empty.


> Unless we are planning to add two different exceptions, "ResourceIncomplete", "ResourceEmpty" else then "ResourceIncomplete" would account for both.

I think the bit I'm struggling with is what you mean by "Incomplete". Consider these two resources:
```javascript
{"id": "123", "resourceType": "Patient"}
{"id": "123", "resourceType": "Observation"}
```
This is what the code currently returns when a Patient and an Observation resource are empty. The Patient is valid. The Observation raises a validation error, because it's missing a required property.

Which one is incomplete?

Only the second one, because it's missing a required property?

Or both, because before we added the case ID and resource type, the resource was empty?

What about this one?
```javascript
{"id": "123", "resourceType": "Patient", "deceasedBoolean": false}
```

Is this incomplete? It tells us nothing about the patient other than that they are alive. *Maybe* that's all we know about the patient. But most probably, it's not complete.

I would say that the code has no idea whether the resource is complete or not. All it knows is whether the resource is empty.

**Comment by mkangia** [comment]
> I would say that the code has no idea whether the resource is complete or not. All it knows is whether the resource is empty.

I think that is a great direction. HQ does not know if resource is complete or not, and plus being empty is also not a real issue for HQ (you can possibly have a resource that is perfectly okay being empty as well).
I suggest, we don't change the logic during building fhir resource,
and then let `_build_fhir_resource` raise the exception about resource being invalid and have any code that calls _build_fhir_resource handle that accordingly. (this would also mean not having `skip_empty` i believe, and would make code much cleaner with _build_fhir_resource doing just one thing, building)

I propose we ask Farid, to help come on a conclusion on this, if we are not able to conclude this now, for quicker resolution.

**Comment by proteusvacuum** [comment]
If I can summarize here for clarity:
- You can define a mapping from case types to Resource Types, and case properties to Resource Properties.
- For some Resource Types, there are some Resource Properties that are `required`
- A user requests a Resource from the FHIR API, but for some reason or another these required Resource Properties are missing, so the Resource is invalid

If that is what is happening here, I would lean towards the solution in https://github.com/dimagi/commcare-hq/pull/29342/ where you are explicitly saying that the requested resource exists, but that it isn't valid, so cannot be sent. A `404` would be wrong. 

I'm not sure about the "fully empty" resource, where there are no required properties, but there is also no data mapped to any field, but the resource is valid. I feel like the correct response here would be to just return the empty Resource.

```json
{"id": "123", "resourceType": "Patient"}
```

**Comment by mkangia** [comment]
thanks for weighing @proteusvacuum 

> If that is what is happening here
i will let @kaapstorm confirm this,
I think another challenge for HQ is not knowing if all the required fields are present or not. Basically HQ does not have a way to tell if resource is complete or not. Hence this PRs are simply talking empty and non-empty (with just id and type default fields present) resources.

**Comment by kaapstorm** [comment]
> * You can define a mapping from case types to Resource Types, and case properties to Resource Properties.
> * For some Resource Types, there are some Resource Properties that are `required`

Yes.

> * A user requests a Resource from the FHIR API, but for some reason or another these required Resource Properties are missing, so the Resource is invalid

Yes, but this is not the scenario I'm concerned about, because if the resource is invalid then it will fail validation, and raise an error.

I'm concerned about a scenario where it *doesn't* raise an error, and I'm wondering whether it should. Based on @mkangia 's feedback, I might have nothing to worry about, and maybe I can close both this PR and #29342 .

I'm coming at this from the perspective of data forwarding, and I want to know if something similar applies to the API: Data forwarding is triggered by a form submission, and it builds FHIR resources for each case touched by that form. Some cases won't have any values for the case properties that are mapped to FHIR resource properties. Even if the case was touched, the case properties affected might not be relevant to the FHIR integration. **If there is no data to be forwarded** (i.e. the resource is empty) then the Repeater should skip that case.

Is there an analogous scenario for the API? If an API user asks for a FHIR Patient, and all the case properties that are mapped to FHIR resource properties have no values, what should we do?

* Return a 404
* Return the case ID
* Something else

It seems from this conversation that we should return the case ID. That is the current behavior. If we think that's the right behavior, then I'm OK with that.

**Comment by kaapstorm** [comment]
... Just to be clear, this PR is only to change the function that the API and data forwarding use, and to figure out what it should tell the API:
* I got nothing. Everything is fine. (This PR.)
* I got nothing, but I'm not going to tell you that. Instead I'll just give you back the case ID you gave me. (No change)
* I got nothing. Is that right? Maybe you wanna tell someone. (#29342 )

It doesn't change the API or the Repeater. The API and the Repeater still get to decide what they want to do with the result.

...

Am I overthinking this? If I originally wrote this function to raise an `IGotNothingWarning()`, then the Repeater could skip the case, and the API could return the case ID that the user asked for, and we'd have exactly the same behavior that we have at the moment. ... So I'm starting to lean towards closing these PRs. If it turns out this is not just an imaginary problem, then we will find out about it in the future, and when we do, we'll still have these branches.

**Comment by proteusvacuum** [comment]
I think the current state is fine. If I was a consumer of the API, and I saw that all I got was the case_id, I would know what that means (no FHIR-relevant data, but the case exists).

**Comment by kaapstorm** [comment]
Resolved. Current state is fine.

**Pull request closed without merging**
