### PR TITLE
remove custom aaa directory

### PR DESCRIPTION
**Pull request by mkangia**
## Summary

https://dimagi-dev.atlassian.net/browse/ICDS-1811
Got confirmation from Nitish that we can remove the custom app "aaa" from HQ codebase now.
This was maintained in case we need to showcase abilities from REACH pilot.

Have dumped a zip of the folder on [dropbox](https://www.dropbox.com/work/Dimagi%20-%20Projects/gates%20foundation/reach/Tech/Code%20Backup) in case this is a need to put this back again and a simple revert of this PR isn't an option.

I believe we don't need to worry about removing the tables for this custom app on existing environments because adding new migrations for that, again leaves references for "aaa" in the HQ codebase.
May be I can delete the tables manually if there is any concern with tables lying around in databases.

The label "reindex/migration" is added but there are no migrations to run

Steps to restore and shared in the document in the dropbox folder
```
To restore this back in CommCare HQ
1. Either simply revert the PR  https://github.com/dimagi/commcare-hq/pull/28896 or put this folder back in place where it was before the PR and restore settings as before the PR
2. Create a PR to put it back and let tests run
```
## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
This is fine with me but I was under the impression we were keeping this on purpose. @proteusvacuum do you have more context.

**Comment by proteusvacuum** [comment]
No issues from me, although I don't have much context on this...

**Comment by mkangia** [comment]
Hey @snopoke 

This was in the README of this doc

```
# Current Status

As said in the overview section, this directory contains a reporting dashboard for a pilot of an extension of CAS.
It is no longer currently used in a production or test environment.
All real production data associated with this project has been deleted.
This is still in the repository for the team to showcase when discussing future steps for convergence (using QA test data).

*To remove this* you should get sign-off of the Program Management team in the CAS division.
```
So i reached out to Nitish and he got us an approval.

**Review by snopoke — APPROVED** [review]

**Comment by mkangia** [comment]
holding off merge till we are back in deploy mode in 2021

**Comment by mkangia** [comment]
Note to self: Update [custom/aaa/templates/aaa/dashboard.html](https://github.com/dimagi/commcare-hq/pull/28981/commits/05ddfa0dba33bbde6075117c4fc2fe1bba0eb9c3#diff-f34c3beed008ad874c85ad5549d9ec39a50dfc14a1249e9dc472c34c87e06b3d) in the zip folder after merge.

**Comment by mkangia** [comment]
had it on staging for quite a while, no issues reported to going to merge this now.

**Comment by mkangia** [comment]
This has no new migration but still has the label `reindex/migration` because the migrations were removed that were a part of the custom app directory.

**Comment by proteusvacuum** [comment]
Do those migrations need to be rolled back to remove these unneeded tables from the DB?

**Comment by mkangia** [comment]
hey @proteusvacuum 

I mentioned this in the description

> 
> I believe we don't need to worry about removing the tables for this custom app on existing environments because adding new migrations for that, again leaves references for "aaa" in the HQ codebase.
> May be I can delete the tables manually if there is any concern with tables lying around in databases.

**Pull request merged**
