### PR TITLE
Upgrade openpyxl

### PR DESCRIPTION
**Pull request by nickpell**
Needed for applying formatting to excel sheets for Abt.

@dannyroberts

### CODE REVIEW

**Comment by nickpell** [comment]
requires https://github.com/dimagi/couchexport/pull/148

**Comment by czue** [comment]
build failed.

```
======================================================================
FAIL: test_bad_column_name (corehq.apps.app_manager.tests.test_bulk_app_translation.BulkAppTranslationBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_bulk_app_translation.py", line 245, in test_bad_column_name
    u'App Translations Updated!'
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_bulk_app_translation.py", line 55, in upload_raw_excel_translations
    [m[1] for m in messages], expected_messages
AssertionError: Lists differ: ['Skipping sheet "Modules_and_... != [u'Sheet "module1_form1" has l...
First differing element 0:
Skipping sheet "Modules_and_forms", could not find label column
Sheet "module1_form1" has less columns than expected. Sheet will be processed but the following translations will be unchanged: default_fra
First list contains 1 additional elements.
First extra element 3:
App Translations Updated!
+ [u'Sheet "module1_form1" has less columns than expected. Sheet will be processed but the following translations will be unchanged: default_fra',
+  u'Sheet "module1_form1" has unrecognized columns. Sheet will be processed but ignoring the following columns: default-fra',
- ['Skipping sheet "Modules_and_forms", could not find label column',
-  'Skipping sheet "module1", could not find case_property or list_or_detail column.',
-  'Skipping sheet "module1_form1", could not find label column',
   u'App Translations Updated!']
----------------------------------------------------------------------
```

might also be worth reading release notes and understanding if we need more thorough QA

**Comment by nickpell** [comment]
:white_check_mark: 

I'm fairly comfortable with this upgrade since openpyxl is only used in a small number of well-encapsulated functions.  I'm open to more QA though.

**Comment by czue** [comment]
:+1:

**Pull request merged**
