### PR TITLE
don't constantly ping server on resize

### PR DESCRIPTION
**Pull request by czue**
@snopoke / anyone

http://manage.dimagi.com/default.asp?221237

### CODE REVIEW

**Comment by orangejenny** [comment]
Looks fine, although `_.throttle` would be more concise.

**Comment by czue** [comment]
nice trick. updated

**Comment by orangejenny** [comment]
cool. guessing this doesn't have test coverage?

**Comment by czue** [comment]
would be shocked if it did, but not in a rush to get it merged either

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
