### PR TITLE
Command to reset PillowSeqStore to 0

### PR DESCRIPTION
**Pull request by benrudolph**
@TylerSheffels this is so we can reset some of our pillow seq stores and stop receiving the errors

### CODE REVIEW

**Comment by czue** [comment]
what, no UI?

**Comment by czue** [comment]
(g2m when tests pass - or if you want to merge before then because you know the test you wrote is good)

**Comment by TylerSheffels** [comment]
:+1: from me too

**Comment by benrudolph** [comment]
double checked tests locally. gonna go ahead and merge

**Pull request merged**
