### PR TITLE
Loadtest users, post-migration

### PR DESCRIPTION
**Pull request by kaapstorm**
## Product Description

Makes the "Loadtest users" feature Generally Available for Pro Plan subscriptions and higher.

This change adds some guard rails:
* Loadtest users are unable to sync payloads over 500,000 cases
* The "loadtest factor" field is moved from the mobile worker's Basic Info form, to under the "Actions" tab, where it is less likely to cause confusion for users just trying to create a normal mobile worker.

## Technical Summary

See the original PR https://github.com/dimagi/commcare-hq/pull/31095 for context and discussion.

This PR is rebased onto its migration, https://github.com/dimagi/commcare-hq/pull/31312 which will be merged separately.

## Feature Flag

Was "Loadtest Users", now Pro Plan or higher.

### Safety story

The [safety story for users is documented here](https://docs.google.com/document/d/15nNnRAh8vx4v5ds9VF9cJHmlLE-NoFi1P0THKI86UCk/edit#).

### Automated test coverage

Changes covered by tests.

### QA Plan

Currently in QA: [QA-3958](https://dimagi-dev.atlassian.net/browse/QA-3958)

### Migrations

Migration in separate PR #31312 to be applied in advance.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by kaapstorm** [comment]
@proteusvacuum and @Charl1996 you approved the original PR #31095.

Since then the [safety story](https://docs.google.com/document/d/15nNnRAh8vx4v5ds9VF9cJHmlLE-NoFi1P0THKI86UCk/edit#) has been built out, and [the documentation](https://confluence.dimagi.com/display/saas/Loadtest+Users) has been updated with findings and technical details.

QA is wrapping up. Would you be able to check this new PR, which is just a rebase of the commits of the original PR?

**Comment by dannyroberts** [comment]
@kaapstorm noticed this during monthly compliance sweep. It looks like this was never actually reviewed/approved. Did you get review/approval offline, and was this just an oversight?

**Comment by kaapstorm** [comment]
@dannyroberts the commits in this branch are included in PR https://github.com/dimagi/commcare-hq/pull/31663 which is where they were reviewed and approved.

I ought to have closed this PR before merging that one. When that PR was merged, GitHub marked this one as merged too.

**Comment by dannyroberts** [comment]
Got it! I forgot that github does that; that didn't occur to me. Makes total sense, thanks for the explanation.

**Pull request merged**
