### PR TITLE
Aggregate agg_awc_daily for last 3 days

### PR DESCRIPTION
**Pull request by Rohit25negi**
Aggregation agg_awc_daily for last three days.

### CODE REVIEW

**Comment by Rohit25negi** [comment]
hey @calellowitz , Do we still need this.

**Comment by calellowitz** [comment]
Don't know how this got lost, but i still think this is a good idea. If you fix the conflict, i would be happy to merge this

**Comment by calellowitz** [comment]
I merged master and it appeared to reveal some test failures, do you have any intent to pick this back up?

**Comment by Rohit25negi** [comment]
> I merged master and it appeared to reveal some test failures, do you have any intent to pick this back up?

Sure. Will be picking up today

**Comment by calellowitz** [comment]
@Rohit25negi any update on this

**Comment by Rohit25negi** [comment]
> @Rohit25negi any update on this

Corrected all test cases

**Pull request merged**
