### PR TITLE
Refresh install for app preview

### PR DESCRIPTION
**Pull request by benrudolph**
@biyeun @wpride this adds the functionality to app preview to allow for refreshing an app. When a user clicks the refresh button it will wipe the application db so that on a subsequent request it will install a new one. can be read commit by commit or all at once

cc: @dannyroberts

### CODE REVIEW

**Comment by wpride** [comment]
👍

**Comment by benrudolph** [comment]
✔️

**Comment by biyeun** [comment]
:fire:

**Comment by benrudolph** [comment]
just a heads up, this won't work until this is merged: https://github.com/dimagi/formplayer/pull/99

**Pull request merged**
