### PR TITLE
form json fix

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?235579
Will require an in-place reindex of SQL forms

@emord

### CODE REVIEW

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by benrudolph** [comment]
👍

**Comment by gcapalbo** [comment]
@NoahCarnahan can you run the command after today's deploy of both environments?
@snopoke can you give Noah the command to run?

**Comment by snopoke** [comment]
I'll add it to the ticket

**Comment by NoahCarnahan** [comment]
👍

**Pull request merged**
