### PR TITLE
Pass a string, not an Exception instance

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: [FB 246864](http://manage.dimagi.com/default.asp?246864)

This change doesn't resolve the underlying exception, but does avoid HQ from trying to encode an Exception instance as JSON. 

I'm opening this PR to discuss why the KeyError is being raised in the first place. I can't see why ["emw" is hardcoded here](https://github.com/dimagi/commcare-hq/blob/d8a8c3101c74d63d61351ad6472a325b6bdf4ea3/corehq/apps/export/views.py#L2250-L2250) (where the KeyError is being raised). It seems to refer to [`ExpandedMobileWorkerFilter.slug`](https://github.com/dimagi/commcare-hq/blob/0f511188e207f92ffebb64cd6229791257c6ea06/corehq/apps/reports/filters/users.py#L195-L195), but it's not obvious to me why that particular slug is used here. How do we know it's not going to be the slug of a subclass?

@mkangia @NoahCarnahan @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
hmm strange, it seems likely that `emw` was removed from the in_data and that change was not reflected on the server for multimedia uploads: https://github.com/dimagi/commcare-hq/commit/83ad01d8. @mkangia does that sound correct?

**Comment by NoahCarnahan** [comment]
I agree it looks like it shouldn't be hard coded there, but don't know off the top of my head how the correct slug should be determined. I think Manish will have some insight, but I'm happy to look more closely at it if not.

**Comment by mkangia** [comment]
@kaapstorm Did a similar fix in Noah's changes [here](https://github.com/dimagi/commcare-hq/pull/14440/commits/83ad01d8d2f7142b99751522718e9932939b66f2). "emw" was used earlier and was updated. I think can do the same change `LocationRestrictedMobileWorkerFilter.slug` which should be the new param used now. Thanks for addressing this.

**Comment by kaapstorm** [comment]
Thanks for the help guys. Commit 9a5dbff should resolve the error.

@emord cc @czue @proteusvacuum

**Review by czue — APPROVED** [review]

**Pull request merged**
