### PR TITLE
UCR Summary: Fix summary for count and choice list columns

### PR DESCRIPTION
**Pull request by sheelio**
Product Note: Fixes bugs in the UCR summary for Count and ChoiceList columns.

### CODE REVIEW

**Comment by sheelio** [comment]
Was leading to this error:
https://sentry.io/dimagi/commcarehq/issues/431144351/

**Comment by emord** [comment]
What is a count column? I don't see it documented anywhere. It looks like it's based on a boolean column?

**Comment by sheelio** [comment]
I think it just gives you a 1 in the row (to help you get a count of the number of documents if you're grouping by something).  Report builder uses it for a Number of Cases or Number of Forms columns. 

(I think its from before expression columns existed).

**Comment by emord** [comment]
Ah cool. so it's basically a shorthand version of something you can do with booleans. Can you add a description to the readme (or point me to where it's documented in case I missed it)?

**Comment by sheelio** [comment]
They're deprecated at this point.  There's this note in the Readme:
"Note/todo: there are also other supported formats, but they are just shortcuts around the functionality of these ones they are left out of the current docs."

We may want to have Norman update Report Builder to not rely on the count type.

**Review by emord — APPROVED** [review]
Cool. that seems fine then. Thanks for the explanation

**Pull request merged**
