### PR TITLE
Copy custom user data to the usercase on creation

### PR DESCRIPTION
**Pull request by kaapstorm**
[FB 180623](http://manage.dimagi.com/default.asp?180623)

@snopoke, cc @gcapalbo

### CODE REVIEW

**Comment by kaapstorm** [comment]
Mmm. This ought to have a couple tests. I'll add them in the morning.

**Comment by gcapalbo** [comment]
:+1: , will wait for you to add the tests before merging

**Comment by kaapstorm** [comment]
Tests added

**Comment by kaapstorm** [comment]
After discussion with @snopoke, changed this to copy custom user data to the usercase always. To avoid overwriting values, app builders will need to use different property names for properties set using case management. I will update documentation accordingly.

**Comment by snopoke** [comment]
:+1: once tests pass

**Pull request merged**
