### PR TITLE
Remove formplayer submodule

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @czue this'll remove the formplayer submodule since it'll soon be obsolete anyways. will remove label when it's ready

### CODE REVIEW

**Comment by benrudolph** [comment]
cha-ching ready

**Comment by benrudolph** [comment]
https://github.com/dimagi/commcare-hq-deploy/pull/90
https://github.com/dimagi/commcarehq-ansible/pull/486

**Comment by czue** [comment]
sorry i should probably know this but how does formplayer get installed now?

**Comment by czue** [comment]
nvm, figured it out

**Comment by benrudolph** [comment]
yeah it's actually more confusing having the submodule because might think the build respects the submodule commit, but it doesn't at all

**Pull request merged**
