### PR TITLE
Add migration status column

### PR DESCRIPTION
**Pull request by bagnolil**
@calellowitz

### CODE REVIEW

**Comment by calellowitz** [comment]
@emord were you saying this is how we should be making these changes

**Review by calellowitz — APPROVED** [review]

**Comment by emord** [comment]
@calellowitz for some reason the boolean type wasn't created with is_nullable. I haven't dug into why that was chosen, but for now the workaround is to use an integer with 0/1

**Comment by orangejenny** [comment]
@bagnolil First PR? Welcome to the dev team.

Test failure looks real: `WrappingAttributeError: can't set attribute corresponding to u'is_nullable' on a <class 'corehq.apps.userreports.indicators.specs.BooleanIndicatorSpec'>`

**Comment by emord** [comment]
For some reason this table was included in the aggregation script tests so they failed.

I've removed it from the tests as it's not used by the script

**Comment by emord** [comment]
@bagnolil @calellowitz These columns are available on ICDS now

**Pull request merged**
