### PR TITLE
Automatically succeed duplicates for 99DOTS registrations

### PR DESCRIPTION
**Pull request by proteusvacuum**
@mkangia 
I was resolving these manually with a management command before, but I think we're moving away from that as we put this to bed.

code buddy @biyeun

### CODE REVIEW

**Comment by proteusvacuum** [comment]
bump

**Review by mkangia — APPROVED** [review]
nit: might want to add a case property to identify these separately if needed, like `force_99_dots_registered`

**Comment by mkangia** [comment]
@proteusvacuum is this not needed anymore?

**Comment by proteusvacuum** [comment]
Not really since we are turning everything off in a month. This was more if we were going to be dealing with this for the next ~6 months in the private sector. Merging anyway.

**Pull request merged**
