### PR TITLE
simpler way to get orm table

### PR DESCRIPTION
**Pull request by snopoke**
I looked at this since I was getting an error from SQLAlchemy
saying that 'doc_id' was already a column in the table when
running against PG11.

This seems like the right approach since we're not actually extending the table with any additional columns. I think it may also have worked if I'd specified `keep_existing` instead of `extend_existing` but this approach seemed ideal since we just want to create and ORM class from an existing table.

### CODE REVIEW

**Comment by snopoke** [comment]
See build here for example: https://travis-ci.org/dimagi/commcare-hq/jobs/505770979

**Comment by snopoke** [comment]
@calellowitz FYI in case you come across this error

**Comment by snopoke** [comment]
:white_check_mark:

**Review by millerdev — APPROVED** [review]

**Comment by emord** [comment]
With this does it still work to add and remove columns to a live UCR? I can't find an automated test for this (there is one for partitioning, so that should continue to work)

**Review by kaapstorm — APPROVED** [review]
:sparkles:

**Comment by snopoke** [comment]
>With this does it still work to add and remove columns to a live UCR? I can't find an automated test for this (there is one for partitioning, so that should continue to work) 

Good question, I don't see how this would impact that feature since this is solely used for partitioning but I'll check.

**Comment by snopoke** [comment]
There are a few tests in this class which test adding / removing columns and indexes: https://github.com/dimagi/commcare-hq/blob/731d427b5f931f30a8f44232fb5f09de0cfdf71c/corehq/apps/userreports/tests/test_pillow.py#L709

**Pull request merged**
