### PR TITLE
Fix ucr templates

### PR DESCRIPTION
**Pull request by emord**
@nickpell @NoahCarnahan

### CODE REVIEW

**Comment by nickpell** [comment]
or...we could just fork django 1.7 #goodIdeas

**Comment by nickpell** [comment]
looks good when tests pass

**Comment by czue** [comment]
what's the root cause here?

**Comment by emord** [comment]
A refactor in BaseContext caused an error in templates when using {% include 'foo' with context=bar %}

https://github.com/django/django/blob/1.6.11/django/template/context.py#L37-L40 

https://github.com/django/django/blob/1.7.10/django/template/context.py#L53-L54

1.7.10 self is passed in as context (https://github.com/django/django/blob/1.7.10/django/template/context.py#L18) but when using include with it there's a kwarg with key context, so context was passed in twice

**Comment by czue** [comment]
makes sense, thanks

**Pull request merged**
