### PR TITLE
notify user when a data source is deactivated

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?190068 (https://github.com/dimagi/commcare-hq/pull/9739#issuecomment-168214366)

screen shot 2016-01-08 at 6 04 26 pm

@NoahCarnahan @orangejenny @czue cc: @emord

### CODE REVIEW

**Comment by czue** [comment]
could maybe use a less scary style, but :+1: from me when tests pass

**Comment by nickpell** [comment]
screen shot 2016-01-11 at 11 01 13 pm

@czue better? I would prefer ```alert-warning``` but I'm not sure I know how to do that with the django messages framework

**Comment by czue** [comment]
it looks like in the base template you could just add something to `tags`: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/style/templates/style/bootstrap3/base.html#L241.

**Comment by czue** [comment]
(but i think either of the two options you've already done are totally fine especially since it's an internal UI)

**Pull request merged**
