### PR TITLE
Edit submissions release

### PR DESCRIPTION
**Pull request by czue**
This is finally out of QA/UAT!

This adds a new "data cleanup" privilege and puts edit submissions there. @sravfeyn you might want to use this for https://github.com/dimagi/commcare-hq/pull/7584 as well.

anyone / @emord buddy

### CODE REVIEW

**Comment by czue** [comment]
@amsagoff not sure if you have anything in mind for communications.

**Comment by snopoke** [comment]
Woop

**Comment by amsagoff** [comment]
Wohoo! Double checking this is a new privilege on "pro"

**Comment by czue** [comment]
@amsagoff yep, exactly

**Comment by benrudolph** [comment]
Nice! This is a sweet feature

**Pull request merged**
