### PR TITLE
Custom Reports for champ-cameroon domain

### PR DESCRIPTION
**Pull request by lwyszomi**
Tests will be sent in another PR (Monday/Tuesday)

@fyniac Could you assign someone to review?

### CODE REVIEW

**Comment by lwyszomi** [comment]
Could you kick off the build, looks like travis fails is not related.

**Comment by fyniac** [comment]
@emord can you please review?

**Comment by emord** [comment]
where's the spec for these?

**Comment by fyniac** [comment]
@emord sent you the spec in email

**Review by emord — CHANGES_REQUESTED** [review]

**Comment by lwyszomi** [comment]
@emord updated

**Review by emord — APPROVED** [review]

**Pull request merged**
