### PR TITLE
INDDEX reports UI simplifications

### PR DESCRIPTION
**Pull request by esoergel**
https://docs.google.com/document/d/1fy7_JYhZwy4z8VA8ikygXSXTTSHNqaTFUWaj1AHcVD0/edit

##### SUMMARY
This is a series of simplifications to the reports UI.  I'd prefer to drop them entirely, but we don't have an in-product support for showing multiple tables on a single page (that I'm aware of).  This was an effort to strip off the irrelevant copy/pasted code and refactor things to make more sense.

Read by commits.

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
Awesome.

What do you have in mind for `FoodData.from_request()`?

**Comment by esoergel** [comment]
> What do you have in mind for FoodData.from_request()?

Each of the report classes needs to parse parameters out of their request object, and those parameters will (mostly?) be used to filter the FoodData class, so I figure it makes sense to share that there.  I used a classmethod because I didn't want to require `request` in the main constructor - I figure this way lets me share the logic that interprets request parameters, while still being explicit about what it actually takes to instantiate `FoodData`.  What are your thoughts?  How would you approach that issue?

**Comment by kaapstorm** [comment]
I agree with your choice to make `FoodData.from_request()` a class method, and I really like how it constructs the class.

I can't visualise how I would implement the TODOs in `GapsDetailReport.report_config()` and `GapsSummaryReport.report_config()` though.

**Comment by esoergel** [comment]
Oh yeah, that's why I left those as TODOs for now.  I'm planning on getting rid of `report_config` entirely, and having only `FoodData` interface with the UCR.  So rather than making the report classes assemble parameters to pass to the UCR, `FoodData.from_request` will do that, and the report classes will interact with an instance of `FoodData` rather than whatever combination of data classes they're using now.

**Pull request merged**
