### PR TITLE
set CELERY_BROKER_HEARTBEAT = 0 to workaround bug with gevent workers

### PR DESCRIPTION
**Pull request by nickpell**
Resolves the issue mentioned in https://github.com/celery/celery/issues/4817 which was observed for the sms_queue on staging.

### CODE REVIEW

**Review by gbova — APPROVED** [review]

**Comment by emord** [comment]
what are the effects for a worker that doesn't use gevent?

**Comment by nickpell** [comment]
@emord None that I'm aware of.  Is there anything I should be looking out for?

**Comment by emord** [comment]
Read over the docs and it looks like its not related to our flower heartbeat that makes sure celery queues are up. is that correct? Its something with the internal comms between rabbitmq and celery?

**Review by emord — APPROVED** [review]

**Comment by nickpell** [comment]
@emord That was my take on it as well.

**Pull request merged**
