### PR TITLE
skip sheets not expected

### PR DESCRIPTION
**Pull request by mkangia**
fixes [888323457](https://sentry.io/organizations/dimagi/issues/888323457/)

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
A comment would be helpful.

**Review by emord — APPROVED** [review]
agreed about comment. the build failure looked unrelated (something in api test) so I restarted

**Comment by mkangia** [comment]
Comment added.

I think this is a quick fix for now but not the ideal one. This should still have all sheets in the expected rows and then ignore them if not uploaded. Going to ship this one to unblock ICDS team but will do a follow up PR.

@emord thoughts?

**Comment by mkangia** [comment]
Thank you for the review @orangejenny. Comment added

**Comment by emord** [comment]
note travis ran and passed on previous even though github does not list it https://travis-ci.org/dimagi/commcare-hq/builds/503472610?utm_source=github_status&utm_medium=notification

**Comment by mkangia** [comment]
Thanks @emord

**Pull request merged**
