### PR TITLE
Remove old reminders views

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
I came across this while looking at something else; it looks very much like all of the old couch based reminders models are completely unused. Does anyone know anything about why these weren't deleted in https://github.com/dimagi/commcare-hq/pull/21832?

I think before we actually go through with this (if it's confirmed to be a good idea), we should figure out what to do with the existing reminders data in couch. It seems to be all from around the time of that other removal commit.

But yeah removing views like this could (when they add up) translate to faster couch and/or being able to downsize the existing machines to save significantly.

### CODE REVIEW

**Comment by orangejenny** [comment]
🌟 💫 🌟

**Comment by esoergel** [comment]
This is superb - would be great to delete all of this.  I don't know why these weren't removed at the time - might've been that there wasn't the time to do the proper clean-up associated with it.  Think there's any need to do a dump of this data for posterity before deleting it?  Looks like it might not be real program data - just outddated configuration stuff, does that sound right?

**Review by millerdev — APPROVED** [review]
I think Giovanni didn't get around to removing them before he left, but I can't find the documentation he said he was going to write in #21832. I'm fairly certain nothing is using the old reminders code, so this should be safe to remove.

**Review by orangejenny — APPROVED** [review]
Any chance of this getting merged? I forgot about this and spent some time this week looking into doing it myself before stumbling back upon this PR. More significantly, I just did a bunch of work in https://github.com/dimagi/commcare-hq/pull/25757 to add app_id to SurveyKeyword and SurveyKeywordAction and migrate the existing docs, which, if this data is no longer relevant, was a waste of time.

It sounds like the only blocker is deciding to delete the existing data. The models being deleted (SurveyKeyword, SurveyKeywordAction, CaseReminder, CaseReminderHandler, and CaseReminderEvent) have no meaningful usage, they're only referenced in models.py, the various map.js files, docs, and my new migration. I'm fairly certain these models have been inaccessible to users since https://github.com/dimagi/commcare-hq/pull/21832 was merged in late 2018. My read of [migration.py](https://github.com/dimagi/commcare-hq/blob/master/corehq/messaging/scheduling/models/migration.py) is that all of these documents are now either broadcasts or conditional alerts.

@dannyroberts Is there any further due diligence that you'd like to be comfortable merging this?

**Comment by orangejenny** [comment]
I merged master and added 05fd1a0a8d9 to delete my recent work. I'm not certain how django-y it is to delete a migration outright, but it's the most recent migration and I can't imagine there will be any more.

**Comment by dannyroberts** [comment]
Oh wow, my apologies @orangejenny. This basically just fell off the map and I forgot to follow up on it.

I think I'm happy just leaving a list of domains we know we've deleted somewhere in the code. I'm thinking of adding them to `purge_docs` management command, unless we know of such a place already. I think beyond just flagging for later that it's something we can and should clean up, no blockers from me

**Comment by orangejenny** [comment]
@dannyroberts I am not 100% sure what you mean about deleted domains, but you sound like there's a good path forward. If there's anything I can contribute to getting this done soon-ish (next couple of weeks?) I would be happy to spend time on it, just let me know.

**Comment by dannyroberts** [comment]
Sorry I meant doc_types, not domains. Updated my comment.

Here's what I meant about noting down the doc_types somewhere: https://github.com/dimagi/commcare-hq/pull/25994

**Pull request merged**
