### PR TITLE
Catch invalid decimal strings

### PR DESCRIPTION
**Pull request by esoergel**
https://manage.dimagi.com/default.asp?249649
@emord @millerdev

### CODE REVIEW

**Comment by millerdev** [comment]
this seems like a great thing to write a test for (the test should be easy to write and fast)

**Review by millerdev — APPROVED** [review]
feel free to merge if there's a good reason for not writing a test (like if it's not worth it)

**Comment by calellowitz** [comment]
hey, i forgot to mark the ticket. thats my bad but i made a pr on this yesterday that did the same (hence the conflicts). https://github.com/dimagi/commcare-hq/pull/15405

**Comment by esoergel** [comment]
For shame, Cal, for shame.

**Comment by calellowitz** [comment]
this is what happens when i work while in transit. forget silly things. :frowning_face:

**Pull request closed without merging**
