### PR TITLE
BETS Voucher Report

### PR DESCRIPTION
**Pull request by proteusvacuum**
@esoergel 

This pulls from the `voucher_fulfilled_by_location_id` property, but you can still search by district (by looking up all the pertinent child location ids and pulling vouchers that were fulfilled there). 

If you don't enter a district, it just returns no values (this is probably only going to be used by us / Abhishek, so figure it's fine)

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by proteusvacuum** [comment]
@gcapalbo Is there a way I can add an "SMS sent" status to this report?

**Comment by gcapalbo** [comment]
@proteusvacuum it might be a little difficult to tie the voucher to the sms after the fact but we might be able to do it. we send 3 sms alerts for vouchers, did you want to include all of them here?

**Comment by proteusvacuum** [comment]
@gcapalbo yes, if it is possible, I think it would be useful to show which vouchers have had which SMS messages sent against them, and if possible, the status of this SMS from our end. I think this would help in debugging issues and creating trust that the system is working as it should be.

**Comment by gcapalbo** [comment]
@proteusvacuum added here: https://github.com/dimagi/commcare-hq/pull/18198

**Pull request merged**
