### PR TITLE
Remove UCR extensions

### PR DESCRIPTION
**Pull request by sheelio**
Product Note: This removes the ext_* UCR expressions.  They aren't really used anywhere but a few test projects.

### CODE REVIEW

**Comment by emord** [comment]
How sure are you that these aren't used in a real project? Seems like something that could sneak in without someone noticing

**Comment by sheelio** [comment]
That's fair - I know of one project that has used them and they stopped using them and haven't really shared them with any other projects.  So not sure, but pretty sure. 

What would be the best way to verify this?  Write a management command that checks all data sources?

**Comment by sheelio** [comment]
The other thought would be to watch for errors on sentry and revert if they are used, but that seems riskier..

**Comment by emord** [comment]
I think the easiest is to have a management command that dumps the json and just greps for the particular string. That way you don't need to worry about how the expression is nested

**Review by emord — APPROVED** [review]
I think this is good to go if the build passes

**Pull request merged**
