### PR TITLE
Remove a thing

### PR DESCRIPTION
**Pull request by proteusvacuum**
## Summary

There was a thing in the wrong place. I think the thing probably was not meant to be there, maybe it was a test thing? 

## Feature Flag

ucr

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

html only

### Safety story

This is just removing a piece of html on a UCR page. I believe this to be very safe
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
damn

**Review by orangejenny — APPROVED** [review]
That looks like the kind of thing I'd leave lying around. Thanks!

**Review by kaapstorm — APPROVED** [review]
Things

**Comment by mkangia** [comment]
haha, @kaapstorm!

**Pull request merged**
