### PR TITLE
[ICDS Dashboard] CBE Denominator

### PR DESCRIPTION
**Pull request by calellowitz**
##### SUMMARY

https://app.asana.com/0/1112385193248823/1142969323504661/f
Changing the threshold from 1 to 2 and making it a percent

### CODE REVIEW

**Comment by Rohit25negi** [comment]
@calellowitz  This would make the SDD inconsistent without historical data correction. Did you already plan how you would do it?

**Comment by Rohit25negi** [comment]
Test case failure. Looks real.

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
Change looks good. Just two points left

**Comment by calellowitz** [comment]
> @calellowitz This would make the SDD inconsistent without historical data correction. Did you already plan how you would do it?

Since there is only about 4 months of this, and the query is very quick. I was going to manually correct it tonight for all the past months

**Review by Rohit25negi — APPROVED** [review]
Looks good. good to go after test cases passes

**Pull request merged**
