### PR TITLE
Microseconds Everywhere

### PR DESCRIPTION
**Pull request by dannyroberts**
The approach I'm taking here is to completely override DateTimeProperty to accept datetimes with and without microseconds and always produce them with microseconds, affecting all of our models throughout our code (except for a couple places like pact which relied on overly specific bizarre behavior of the old property; for those cases I used `OldDateTimeProperty` to reference the current/old behavior). Depends on https://github.com/dimagi/dimagi-utils/pull/266 which introduces the shim that lets us easily swap in the DateTimeProperty by just importing all couchdbkit properties from a different module. The following submodules also have corresponding updates:
- https://github.com/dimagi/auditcare/pull/20
- https://github.com/dimagi/couchexport/pull/130
- https://github.com/dimagi/couchlog/pull/19
- https://github.com/dimagi/ctable/pull/81
- https://github.com/dimagi/fluff/pull/100
- https://github.com/dimagi/pillowtop/pull/115
- https://github.com/dimagi/toggle/pull/12

This touches a lot of code. Here are some reasons I feel ok about it:
- I changed `json_format_datetime` to also produce ISO dates with microseconds
  - `"2015-04-13T12:00:00.000000Z" < "2015-04-13T12:00:00Z"`, so using these as `startkey`s for couch is completely backwards compatible. Using them as `endkey`s is actually technically not (because by default `inclusive_end` is set to `true`, so `endkey="2015-04-13T12:00:00Z"` _will_ include that value while `endkey="2015-04-13T12:00:00.000000Z"` won't. I think it's very rare if it happens at all that we rely on whether the end key is inclusive one way or another, so I'm pretty confident this won't affect anything. Still wanted to flag it in case anyone thought otherwise.
- I changed all instances of directly parsing `"%Y-%m-%dT%H:%M:%SZ"` (except for a few individually considered cases) to use a function (`iso_string_to_datetime`) that accepts either format.
- When I first made changes, I expect a few tests to fail, and some did, but what I found was notable in two ways. First, only a small handful of tests failed (or rather I only had to make a small handful of fixes to get all tests passing), and second, for the tests that did fail, I could trace each of them back to a bug in the calling code (mostly under `custom/`).

[Closing https://github.com/dimagi/commcare-hq/pull/6182 and https://github.com/dimagi/commcare-hq/pull/6277 in favor of this branch.]

Here's a list of stuff we want to understand / verify before this gets merged:
- [x] explicit confirmation that the "export dates for excel" feature didn't change/still works.
- [x] confirmation from all interested parties that they can handle the API changes:
  - [x] MOTECH / bihar project
  - [x] CRS / scott l / brian d project
  - [x] commcare-export
  - [x] tula
  - [x] data platform
  - [x] HSPH (sheel)
  - [x] at least 1 week's notice sent out via commcare-users list with no positive responses
- [x] confirmation from all interested parties that they can handle the data forwarding changes:
  - [x] MOTECH / bihar project
  - [x] at least 1 week's notice sent out via commcare-users list with no positive responses
- [x] confirmation that casexml generation on datetimes has not changed or that the changes have been thoroughly tested across commcare versions and java/android

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/hqadmin/views.py, line 473 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/registration/models.py, line 1 - F401 'IntegerProperty' imported but unused
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/hqadmin/views.py, line 473 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/registration/models.py, line 1 - F401 'IntegerProperty' imported but unused
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)
* custom/m4change/reports/mcct_project_review.py, line 6 - F401 'DateTimeProperty' imported but unused

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/hqadmin/views.py, line 473 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/registration/models.py, line 1 - F401 'IntegerProperty' imported but unused
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)
* custom/m4change/reports/mcct_project_review.py, line 6 - F401 'DateTimeProperty' imported but unused

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/hqadmin/views.py, line 473 - E251 unexpected spaces around keyword / parameter equals
* corehq/apps/registration/models.py, line 1 - F401 'IntegerProperty' imported but unused
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)
* custom/m4change/reports/mcct_project_review.py, line 6 - F401 'DateTimeProperty' imported but unused

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/hqadmin/views.py, line 79 - F811 redefinition of unused 'json_format_datetime' from line 79
* corehq/apps/receiverwrapper/models.py, line 21 - F811 redefinition of unused 'json_format_datetime' from line 21
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dannyroberts** [comment]
Tests pass, ran very basic mobile test on staging (download an app log in submit, check data)

**Comment by dannyroberts** [comment]
@czue @snopoke  @NoahCarnahan FYI

**Comment by dannyroberts** [comment]
(all the submodule tests are passing now, it was just their dimagi-utils dependency)

**Comment by dannyroberts** [comment]
Another thing to note is that for the time being I've moved this jsonobject/couchdbkit shim into dimagi-utils instead of editing jsonobject directly. Eventually, I will move it into jsonobject directly, do a significant version bump, change all these imports back, and get rid of the shim in dimagi-utils. I didn't want to do that for the time being because I wanted to be able to iterate quickly on (in the case of hotfixes for example) without having to think about the implications on jsonobject as a library

**Comment by czue** [comment]
@dannyroberts what are you thinking should be done for QA?

**Comment by dannyroberts** [comment]
I think it's worth doing an official QA pass on it. I made a ticket for the QA team just now: http://manage.dimagi.com/default.asp?165202. My own intuition is that this won't break anything except in the most superficial way (maybe some dates displaying in the UI with decimal places when that wasn't desired or something), but I'd rather not leave it up to my biased point of view.

@christineawhite FYI

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 98 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dannyroberts** [comment]
(oops didn't meant to close)

**Comment by dannyroberts** [comment]
I just realized how hard it must be to review this commit—full diff is too big, commit by commit has too much churn. I'm rebasing to remove commits that undo each other etc. without changing the overall diff with master

**Comment by dimagimon** [comment]
There are 6 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/receiverwrapper/models.py, line 17 - F401 'iso_string_to_datetime' imported but unused
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 6 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/receiverwrapper/models.py, line 17 - F401 'iso_string_to_datetime' imported but unused
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dannyroberts** [comment]
Ok, I've rebased it down to 13 logical commits (from 21!), and I've checked carefully that there were no substantial changes in the rebase (all of the changes can be seen in a commit I only made for the purpose of comparison: https://github.com/dimagi/commcare-hq/commit/6249113fb4125be342553cb7f66a60e999f1cfcb). One of them I've cherry-picked into it's own PR since it's a good change on its own: https://github.com/dimagi/commcare-hq/pull/6318 (bringing it to 12).

In addition, I've moved the worst and most rote commits (that, like, change every import in every file according to some pattern) to the beginning to make it easy to do a compare of the rest, if that interests you (though please do still take a look at those commits too). That diff (excluding the worst commits) is: https://github.com/dimagi/commcare-hq/compare/f966c7cc11a63ae4bdd308ea03649fff2a4d71d2...usec.

Hope that helps you all review! It certainly helped me think through my own changes agian

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dannyroberts** [comment]
From QA FYI @czue:
screen shot 2015-04-15 at 2 38 33 pm

Display format in CloudCare case list is changing from `2015-04-15T14:15:13Z` to `2015-04-15T14:15:13.455000Z`; in my opinion that's out of scope to address in this PR—it's a symptom of a different bug/feature request "respect Date format (as configured in App Builder) in case list in CloudCare".

**Comment by czue** [comment]
correct that is out of scope.

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 96 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dannyroberts** [comment]
Christy signed off on QA ticket here: http://manage.dimagi.com/default.asp?165202

**Comment by dannyroberts** [comment]
Offlining with @czue on appropriate timeline for merging this

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 12 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by czue** [comment]
@dannyroberts :white_check_mark: from me code wise.

Here's a list of stuff I would want to understand / verify before this gets merged:

- [ ] explicit confirmation that the "export dates for excel" feature didn't change/still works.
- [ ] understanding that form and case APIs are not affected
- [ ] OR confirmation from all interested parties that they can handle the changes:
   - [ ] MOTECH / bihar project
   - [ ] CRS / scott l / brian d project
   - [ ] commcare-export
   - [ ] at least 1 week's notice sent out via commcare-users list with no positive responses
- [ ] understanding that form and case forwarding/repeater behavior is not changed
- [ ] OR confirmation from all interested parties that they can handle the changes:
   - [ ] MOTECH / bihar project
   - [ ] at least 1 week's notice sent out via commcare-users list with no positive responses
- [ ] confirmation that casexml generation on datetimes has not changed or that the changes have been thoroughly tested across commcare versions and java/android

**Comment by dannyroberts** [comment]
@czue re: - checked API requests in our logs on the domain from thread https://groups.google.com/forum/#!topic/commcare-users/JhUleVbgyNQ. The problem is that they are submitting a `received_on_start` url param that includes microseconds. Somewhat ironically, this PR will fix that, but for now I'll respond to remove the microseconds

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/fixtures/models.py, line 7 - E501 line too long (162 > 115 characters)
* corehq/apps/userreports/reports/specs.py, line 2 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_v2_parsing.py, line 148 - E501 line too long (152 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py, line 106 - E501 line too long (138 > 115 characters)
* custom/ewsghana/api.py, line 10 - E501 line too long (124 > 115 characters)

**Comment by czue** [comment]
:tada: :confetti_ball: :fireworks: :heart_eyes_cat:

**Pull request merged**
