### PR TITLE
drilldown filters again

### PR DESCRIPTION
**Pull request by jmtroth0**
i put this on staging and mentioned it to clark. it's a straight revert of the previous 3 reverts and it seems to work for me. I still can't find the bug in the asha_report that makes it so you can't see the other drilldown controls immediately, but that might be a task for sol develo, since it doesn't _look_ like that is an issue with the filter, but rather with the request being made to the server

@orangejenny

### CODE REVIEW

**Comment by orangejenny** [comment]
Can you also revert https://github.com/dimagi/commcare-hq/pull/20364/ and double-check that the view lookup tables page is working? (I realize breaking seemingly-unrelated RequireJS pages is one of the more fragile parts of this work, I'm thinking about better ways to deal with that.)

> I still can't find the bug in the asha_report that makes it so you can't see the other drilldown controls immediately, but that might be a task for sol develo

That sounds reasonable to me, since the default not being selected is how it's currently working in prod, but can you make sure that Kishan/Kai know this and get their opinion on what the priority of getting it investigated would be? Also, it looks like Łukasz has worked on these reports relatively recently and might be able to confirm how they should be working.

**Comment by jmtroth0** [comment]
@orangejenny reverted, and the `view lookup tables` page seems to work for me, although i only had very simple data populated. Is there also a drilldown that should work there as well or is it as it appears, just a simple dropdown?

I'll loop support in once I'm ready to merge this in

**Comment by jmtroth0** [comment]
>breaking seemingly-unrelated RequireJS pages

afaik, there isn't a way to deal with this kind of problem without comprehensive testing (or at least smoke testing) or fastidiously taking weeks to look into where modules are used.

**Comment by orangejenny** [comment]
That sounds good. Simple data is fine: view lookup table doesn't use the drilldown, but it does depend on `reports/filters/main.js`, so touching any of the filters included in main can break it.

**Review by orangejenny — APPROVED** [review]

**Comment by jmtroth0** [comment]
What does it depend on in main.js? All I see is it [calling](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/fixtures/static/fixtures/js/view-table.js#L26) `.init()`, which is pretty obfuscating. Is there anyway to break out what's used twice or is it actually just all of it?

**Comment by orangejenny** [comment]
> What does it depend on in main.js?

It depends on the `.report-filter-single-option` logic. As far as whether we should be more explicit about which specific code it depends on...dunno. The current setup, where widgets are grouped into "libraries" like filters/main, is more obscure than having pages specify the individual widget(s) they need, but it's also less dev friction. When we last talked about this in a group, I think there were people who leaned towards being more explicit and also people who leaned towards just having one massive library of all widgets in HQ.

> afaik, there isn't a way to deal with this kind of problem without comprehensive testing

The specific issues that the original PR caused with view tables were related to how we bundle modules - one was that module names didn't match filenames, the other was that there were non-RequireJS files in a bundle used by a RequireJS page - which are, happily, more tractable than the general problem of changing a dependency and breaking some other page that depends on it. (Although having smoke tests would also be a good thing...)

**Pull request merged**
