### PR TITLE
Clean couchforms views

### PR DESCRIPTION
**Pull request by dannyroberts**
(I'm gonna do more, just opening to run tests.)

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue curious if you have insight (no rush, prob not gonna continue working on this until monday). 

Looks like the fast reindexers uses `couchforms/by_xmlns` and then filters out the device logs by xmlns. If we use `couchforms/all_submissions_by_domain` (as it's been modified in this PR) instead, do you know if we'll be able to filter on the xmlns that in the doc? I.e. does the thing passed into `custom_filter` include docs?
https://github.com/dimagi/commcare-hq/blob/d6d63526fc7ca3881a73b123e63c12808e5e51ff/corehq/apps/hqcase/management/commands/ptop_fast_reindex_xforms.py#L12-11

**Comment by czue** [comment]
(i don't know off the top of my head, but sounds easy to test)

**Comment by dannyroberts** [comment]
:+1:

**Comment by dannyroberts** [comment]
@czue I think a lot of PRs are failing with this error.

```
======================================================================
FAIL: test_delete_one_of_multiple_indices (casexml.apps.phone.tests.test_sync_mode.FileRestoreSyncTokenUpdateTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "corehq/ex-submodules/casexml/apps/phone/tests/restore_test_utils.py", line 45, in inner
    return helper(*args, **kwargs)
  File "corehq/ex-submodules/casexml/apps/phone/tests/restore_test_utils.py", line 32, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/tzmigration/test_utils.py", line 28, in call_with_settings
    fn(*args, **kwargs)
  File "corehq/ex-submodules/casexml/apps/phone/tests/restore_test_utils.py", line 28, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 330, in test_delete_one_of_multiple_indices
    child_id: [parent_ref_2]})
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 108, in _testUpdate
    self._checkLists(index_ids, sync_log.index_tree.indices[case_id].values())
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 93, in _checkLists
    self.assertEqual(set(l1), set(l2))
AssertionError: Items in the second set but not the first:
u'parent_id'
```

I can't reproduce it exactly; both master and this branch run the phone tests fine, though if I add

```python
TESTS_SHOULD_USE_CLEAN_RESTORE = True
TESTS_SHOULD_TRACK_CLEANLINESS = False
```
to my localsettings, both branches fail but not with that particular error.

**Comment by czue** [comment]
@dannyroberts thanks for the ping. I noticed this yesterday and split the test out to try and understand it better in https://github.com/dimagi/commcare-hq/pull/6925 (couldn't ever repro locally either). In some ways it's comforting that it's still failing after being broken out, though super annoying that it seems very hard to reproduce.

Anyways, https://github.com/dimagi/commcare-hq/pull/6939 should fix it for now and when I'm off interrupt and looking at ownership cleanliness again I'll look into a proper fix.

**Comment by dannyroberts** [comment]
:+1: Great thanks for looking into that—seems really annoying.

So, this PR is done and can be merged with https://github.com/dimagi/commcare-hq/pull/6860. When you review, I'd like to hear your thoughts on the slight change in functionality—which is that the db comparison section of the system admin page will now include logs.

**Comment by dannyroberts** [comment]
Actually hold off on merge for a little longer

**Comment by dannyroberts** [comment]
I think it's been too long for a reasonable merge. Going to look into salvaging parts of this.

**Pull request closed without merging**
