### PR TITLE
[Icds Dashboard] make sdr available starting from 2020

### PR DESCRIPTION
**Pull request by Rohit25negi**
make SDR available starting from 2020 only.
ticket: https://dimagi-dev.atlassian.net/browse/QA-1071

### CODE REVIEW

**Review by czue — APPROVED** [review]
way out of scope, but i would love if we could centralize this logic somewhere

**Comment by Rohit25negi** [comment]
> way out of scope, but i would love if we could centralize this logic somewhere

I might be missing something. But these logics are specific to tabular reports only. Why do you want to centralize them? to be shared by the mobile dashboard?

**Comment by czue** [comment]
> Why do you want to centralize them? to be shared by the mobile dashboard?

Just because having a data structure that said:
```
REPORT_START_DATES: {
  "SDR": "2019-01-01"
}
```

would be much clearer to find/maintain than having to chase down the exact place in each report to insert some set of checks. it'd require a lot of other work which is why i said it's way out of scope (I was just musing)

**Comment by Rohit25negi** [comment]
> 01

**Comment by Rohit25negi** [comment]
> Just because having a data structure that said:

I see, that makes sense to me as well. Cool, I will add this cleanup to my dashboard backlog. Thanks for putting that out.

**Pull request merged**
