### PR TITLE
Upgrade gevent to 1.3.7

### PR DESCRIPTION
**Pull request by millerdev**
One small part of work being done to mitigate general slowness seen on production env. May improve gevent performance a bit. [Ad-hoc benchmark](https://github.com/millerdev/gtime) showed small improvement over gevent 1.2.2. The plan is to deploy to staging first for a bit, and then to production if nothing comes up on staging.

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]
Sounds like a good plan

**Comment by emord** [comment]
Guessing this isn't a hard requirement, but [gevent tests are using cython 0.28.5](https://github.com/gevent/gevent/blob/1.3.7/ci-requirements.txt#L8) and [we're on 0.27.3](https://github.com/dimagi/commcare-hq/blob/master/requirements/requirements.in#L3). May be worth going ahead with an upgrade to cython 0.29

**Comment by millerdev** [comment]
@emord are you suggesting that I also upgrade cython in this PR?

**Comment by emord** [comment]
I don't have a concrete suggestion on upgrading or not as long as it's not a hard requirement in gevent. 

Mentioned this here because I saw some notes in the changelog about using more modern cython idioms which made me go back to look at our cython versions. Its possible that different cython versions would have an impact on performance if they're generating different c code.

there's also a [note in the change log](https://github.com/gevent/gevent/blob/master/CHANGES.rst#dependencies-1) that cython is not required to build from pypi, so it's possible that HQ just uses some provided C files

**Comment by millerdev** [comment]
I think that last part is mostly correct, although I'm not even sure it needs a compiler at all. 

> For ease of installation on Windows, OS X and Linux, gevent 1.3 is distributed as pre-compiled binary wheels, in addition to source code. [[source](http://www.gevent.org/whatsnew_1_3.html#platform-support)]

The next question is, do we use Cython for anything else? If not, I think we can remove it from requirements.

**Comment by snopoke** [comment]
We use it for jsonobject (any maybe others but that's the one I know for
sure).

**Comment by emord** [comment]
We use it for jsonobject, but we also provide C files. So I think that jsonobject install in an HQ virtualenv should not rely on Cython. I'm not sure if any other libraries depend on it

**Pull request merged**
