### PR TITLE
update readme instructions on running formplayer locally

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Review by gbova — APPROVED** [review]

**Comment by nickpell** [comment]
@dimagi/team-commcare-hq A few people were having trouble running formplayer locally - it should work if you follow the steps added to the docs here.

**Comment by czue** [comment]
do we know why this works?

**Comment by nickpell** [comment]
@jmtroth0 could explain more but it involved threading

**Comment by esoergel** [comment]
My theory on this was that it has something to do with concurrent request handling or even just responsiveness.  When I was running into this issue, formplayer would sometimes work, othertimes it'd timeout, though that would happen very quickly (less than a second, IIRC).  Perhaps adjusting some timeout parameters in formplayer's http code would allow it to work with the regular runserver.  Not sure, though I can confirm that switching to Werkzeug locally also fixed it for me.

**Comment by jmtroth0** [comment]
Something with concurrent request handling was what I mentioned as well. 

Another observation is that the main difference between using werkzeug and our standard setup is the redis websockets, [as set here](https://github.com/dimagi/commcare-hq/blob/8cbdd3b538ce32d2769082ee6593bba0a7fb5e9f/settings.py#L576). When I comment out that line, it also works. I'm not 100% sure why that is, but it's possible that there is something odd happening with how it hijacks the main response loop. [This article](https://media.readthedocs.org/pdf/django-websocket-redis/latest/django-websocket-redis.pdf) had some interesting reading. The "Django with WebSockets for Redis in development mode" section is particularly relevant. Since formplayer uses the same session info, it's possible it sees it as the closing the same websocket at the wrong time or something unexpected like that.

Also, it generally seems like using runserver_plus is good practice since it has some nice debugging capabilities.

**Comment by czue** [comment]
cool, thanks for the info!

**Pull request merged**
