### PR TITLE
Fix sort for real

### PR DESCRIPTION
**Pull request by nickpell**
opening for tests

http://manage.dimagi.com/default.asp?220845

### CODE REVIEW

**Comment by czue** [comment]
@nickpell I was able to repro the issue locally and this worked. i cleaned it up a little. I think this is good to go when :white_check_mark:. cc @snopoke

**Comment by czue** [comment]
(i wish I had written a test, but seemed like a fair bit of bootstrap and didn't have time today. would be good to do that though)

**Comment by czue** [comment]
(fixing tests)

**Comment by czue** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
Not that familiar with all the UCR changes but looks OK on the surface

**Pull request merged**
