### PR TITLE
Check can_edit_or_view_location on location_lineage

### PR DESCRIPTION
**Pull request by nospame**
## Technical Summary
[SAAS-15892](https://dimagi.atlassian.net/browse/SAAS-15892)
Adds a decorator to `location_lineage` to ensure a user can at edit or at least view the specific location they are getting the lineage for. Currently a user can potentially view location lineages they should not be able to, including those in other project spaces.

### Safety story
This is a really small change to add on a security check. The decorator itself is already used pretty widely through locations views, there is decent test coverage of the locations app, and I believe the risk is quite low. Tested locally to ensure this does the right thing - limits access to `location_lineage` to only those users who have access to edit or view the particular location.

### Automated test coverage
There are existing automated tests for some of the views in the locations app. I think a test of this particular change wouldn't necessarily add anything, since it'd effectively be testing the decorator itself.

### QA Plan
Not planning QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

[SAAS-15892]: https://dimagi.atlassian.net/browse/SAAS-15892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jingcheng16 — APPROVED** [review]

**Comment by orangejenny** [comment]
You didn't introduce this, but I'm surprised `can_edit_or_view_location` isn't prefixed with `require_`. Does it behave differently than decorators like `require_can_edit_or_view_locations`?

**Comment by orangejenny** [comment]
@nospame But then shouldn't it be called `require_can_edit_or_view_location`? Although then it's only one letter off of `require_can_edit_or_view_locations` which is also easy to confuse.

**Comment by nospame** [comment]
> @nospame But then shouldn't it be called `require_can_edit_or_view_location`? Although then it's only one letter off of `require_can_edit_or_view_locations` which is also easy to confuse.

Yeah, I'm assuming it's related to avoiding name confusion. I also read them slightly differently as "Require the user has 'can edit or view location' permission" versus "the user can edit or view this location". I prefer the current naming to the small difference that with/without an 's' would be, but I agree it's not perfect. We do have some `user_can_` decorators that might be a nicer pattern to use here.

**Comment by orangejenny** [comment]
Ah, I see what you mean, that's insightful.

**Pull request merged**
