### PR TITLE
Don't offset datetime.date enddate objects for SQL query

### PR DESCRIPTION
**Pull request by sravfeyn**
http://manage.dimagi.com/default.asp?230388

@proteusvacuum @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
👍 looks good. kicked build

**Comment by sravfeyn** [comment]
bump @benrudolph

**Comment by czue** [comment]
nice tests!

**Comment by kaapstorm** [comment]
Nicely done, Sravs!

**Pull request merged**
