### PR TITLE
Make web user location IDs available in restore and usercase

### PR DESCRIPTION
**Pull request by esoergel**
## Product Description

Jira: [USH-4317](https://dimagi.atlassian.net/browse/USH-4317?atlOrigin=eyJpIjoiOTNiZjdkNjgwMTc3NGM1M2E4MWI0YmIzYTU1ZTU0YjkiLCJwIjoiaiJ9)

Makes a web user's location IDs available in the restore file (in the registration element) and the usercase.

This missing data was noticed as part of QA on the recent user data modifications. 

## Technical Summary

Nothing fancy. Adding the IDs data XML to the test registration element felt a bit hacky, but this can be seen as [tech debt](https://dimagi.atlassian.net/browse/USH-4317?focusedCommentId=320297) addressed at a later time.

### Safety story

- Mostly straightforward change
- Changes should be limited to web users only. Existing tests verify this
- New tests cover expected result pretty well, I think
- Going to do a run-through on staging

### Automated test coverage

Added new tests to see that the IDs are added properly.

### QA Plan

None. Going to take a quick look on a client test domain on staging.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

[USH-4317]: https://dimagi.atlassian.net/browse/USH-4317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by esoergel** [comment]
That's handy - the test failures show exactly where tests are needed :grin:

**Review by esoergel — COMMENTED** [review]
approved (since I opened the PR, github won't let me approve it via their UI)

**Review by AddisonDunn — APPROVED** [review]

**Comment by esoergel** [comment]
Yeah, I get
> Pull request authors can’t approve their own pull request
Should be able to get someone to rubber stamp to satisfy the bot

**Review by orangejenny — APPROVED** [review]
Here is my rubber stamp.

**Pull request merged**
