### PR TITLE
Show commtrack questions when toggle is enabled

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?187632#1049127

@millerdev

### CODE REVIEW

**Comment by czue** [comment]
looks fine, but curious whether we could just consolidate the two toggles and kill `VELLUM_TRANSACTION_QUESTION_TYPES`?

**Comment by czue** [comment]
It also looks like [`_enable_commtrack_previews`](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/commtrack/util.py#L115) should have done this automatically. odd.

**Comment by czue** [comment]
it looks like we can kill `VELLUM_TRANSACTION_QUESTION_TYPES` though it means doing a one-time migration. I'll make a new ticket on the interrupt backlog to reconcile these flags more comprehensively and we can see if any of us get to it.

**Comment by millerdev** [comment]
> it looks like we can kill VELLUM_TRANSACTION_QUESTION_TYPES

:+1:

**Pull request merged**
