### PR TITLE
default to running tests with new restore code

### PR DESCRIPTION
**Pull request by czue**
just want to run tests

### CODE REVIEW

**Comment by czue** [comment]
note to self:
```
======================================================================
FAIL: test_delete_one_of_multiple_indices (casexml.apps.phone.tests.test_sync_mode.FileRestoreSyncTokenUpdateTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 330, in test_delete_one_of_multiple_indices
    child_id: [parent_ref_2]})
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 108, in _testUpdate
    self._checkLists(index_ids, sync_log.index_tree.indices[case_id].values())
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_sync_mode.py", line 93, in _checkLists
    self.assertEqual(set(l1), set(l2))
AssertionError: Items in the second set but not the first:
u'parent_id'
```

**Comment by czue** [comment]
note to self: 
```
======================================================================
ERROR: test_multiple_batches_sync (casexml.apps.phone.tests.test_batched_mode.BatchRestoreTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/test/utils.py", line 249, in inner
    return test_func(*args, **kwargs)
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_batched_mode.py", line 24, in test_multiple_batches_sync
    restore_id=self.sync_log.get_id)
  File "corehq/ex-submodules/casexml/apps/case/tests/util.py", line 131, in assert_user_doesnt_have_cases
    should_have=False, version=V2, **kwargs)
  File "corehq/ex-submodules/casexml/apps/case/tests/util.py", line 160, in check_user_has_case
    payload_string = restore_config.get_payload().as_string()
  File "corehq/ex-submodules/casexml/apps/phone/restore.py", line 433, in get_payload
    self.validate()
  File "corehq/ex-submodules/casexml/apps/phone/restore.py", line 420, in validate
    self.restore_state.validate_state()
  File "corehq/ex-submodules/casexml/apps/phone/restore.py", line 280, in validate_state
    if self.last_sync_log:
  File "submodules/dimagi-utils-src/dimagi/utils/decorators/memoized.py", line 11, in _inner
    return m(*args, **kwargs)
  File "submodules/dimagi-utils-src/dimagi/utils/decorators/memoized.py", line 127, in __call__
    value = self.func( *args, **kwargs)
  File "corehq/ex-submodules/casexml/apps/phone/restore.py", line 310, in last_sync_log
    sync_log = self.sync_log_class.from_other_format(sync_log)
  File "corehq/ex-submodules/casexml/apps/phone/models.py", line 185, in from_other_format
    type(other_sync_log), cls,
IncompatibleSyncLogType: Unable to convert from <class 'casexml.apps.phone.models.SimplifiedSyncLog'> to <class 'casexml.apps.phone.models.SyncLog'>
```

**Comment by czue** [comment]
@dannyroberts @snopoke I'm thinking we have < 1 week until everyone's on new sync so we should make this the default. :white_check_mark:

**Comment by snopoke** [comment]
nice

**Comment by dannyroberts** [comment]
:+1:

**Comment by proteusvacuum** [comment]
:+1:

**Pull request merged**
