### PR TITLE
kill legacy form case pillows

### PR DESCRIPTION
**Pull request by snopoke**
@czue @benrudolph 
cc @calellowitz 

:fish:

### CODE REVIEW

**Comment by benrudolph** [comment]
👍 on ✔️ big moves!

**Comment by benrudolph** [comment]
```
ERROR: test_case_reindexer_v2 (testapps.test_pillowtop.tests.test_reindexer.PillowtopReindexerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/testapps/test_pillowtop/tests/test_reindexer.py", line 66, in test_case_reindexer_v2
    call_command('ptop_reindexer_v2', index_id, cleanup=True, noinput=True, reset=True)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 101, in call_command
    klass = load_command_class(app_name, name)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/mnt/commcare-hq-ro/corehq/apps/hqcase/management/commands/ptop_reindexer_v2.py", line 35, in <module>
    class Command(BaseCommand):
  File "/mnt/commcare-hq-ro/corehq/apps/hqcase/management/commands/ptop_reindexer_v2.py", line 68, in Command
    help='Run the reindex in place - assuming it is against a live index.'),
  File "/usr/local/lib/python2.7/optparse.py", line 578, in __init__
    checker(self)
  File "/usr/local/lib/python2.7/optparse.py", line 664, in _check_type
    "must not supply a type for action %r" % self.action, self)
OptionError: option --in-place: must not supply a type for action 'store_true'

```
^^ bunch of ones like that

**Comment by czue** [comment]
yes, this is amazing. i think this also opens up the door to removing `HQPillow` and `AliasedElasticPillow` and probably a whole bunch of other cleanup but guessing it makes sense to do that separately

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by czue** [comment]
:tada:

**Pull request merged**
