### PR TITLE
Revert "Revert "exponential backoff for form reprocessing queue""

### PR DESCRIPTION
**Pull request by snopoke**
Reverts dimagi/commcare-hq#27129

### CODE REVIEW

**Comment by snopoke** [comment]
@dannyroberts I've added a few commits to limit the size of the backoff and also limit the number of retries.

**Comment by snopoke** [comment]
+ some tests

**Review by dannyroberts — APPROVED** [review]

**Comment by dannyroberts** [comment]
So now unfinished form stubs will be retried up to 7 times with increasing delays up to a little over 2 months, after which they'll be permanently left for dead. Is that right?

**Comment by snopoke** [comment]
@dannyroberts Yes that's right. After that point we could assume that they will never succeed without manual intervention of some kind.

**Pull request merged**
