### PR TITLE
Remove obsolete Lookup Table couch views and couch_id

### PR DESCRIPTION
**Pull request by millerdev**
Wait to deploy until 2023-01-18

### Safety story

Deleting unused code and a database field.

### Automated test coverage

No.

### QA Plan

No QA.

### Migrations

- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

This PR contains a destructive database change: deleting the `couch_id` column. The data in that column will be lost and cannot be recovered by rolling back the migration. However, it may be possible to recover the contents of that column by reading documents in Couch if that somehow became necessary.

Either of the two distinct things done in this PR can be rolled back independently by rolling back individual commits.

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
The code looks good to me, but it looks like there's a build error

```
ERROR: corehq.couchapps.tests.test_all_docs:AllDocsTest.test_get_all_doc_ids_for_domain_grouped_by_db
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/mnt/commcare-hq-ro/corehq/couchapps/tests/test_all_docs.py", line 46, in test_get_all_doc_ids_for_domain_grouped_by_db
      get_db('fixtures').uri: [],
    File "/mnt/commcare-hq-ro/corehq/ex-submodules/dimagi/utils/couch/database.py", line 48, in get_db
      db_url = settings.EXTRA_COUCHDB_DATABASES[postfix]
  KeyError: 'fixtures'
```

**Review by esoergel — APPROVED** [review]
exciting!  Think it'd make sense to separate the design doc deletion and the sql column deletion?  I don't have any particular reason in mind, just wanted to make sure the idea was considered.

**Comment by millerdev** [comment]
@esoergel interesting suggestion. So you're proposing two separate PRs, which I can see could be convenient. However, those things were done in separate commits, and it would only be a tiny bit more work to revert a commit ([or](https://github.com/dimagi/commcare-hq/pull/32403/commits/b60b456a00a1fe015e1305f649cb8c51b6a48c24) [two](https://github.com/dimagi/commcare-hq/pull/32403/commits/7953d670988cef7bb124b5bd4c512b469cc38a36) in the case of the design docs) in a new PR than to revert an entire PR.

Do you think it's reasonable to leave this as a single PR with the following note?

**Either of the two distinct things done in this PR can be rolled back independently by rolling back individual commits.**

**Comment by esoergel** [comment]
@millerdev yeah that seems fine by me

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
