### PR TITLE
add latest translations and translate "edit submission" to french

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?154865

### CODE REVIEW

**Comment by czue** [comment]
@twymer is there a process i'm screwing up by doing this manually?

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by twymer** [comment]
Running `tx pull` and `tx push` before and after, respectively, is the only other important step. For now, though, I've just been doing that manually as there are translation changes. https://confluence.dimagi.com/display/commcarehq/Internationalization+and+Localization+-+Post+Login

**Comment by twymer** [comment]
Is the update po commit running makemessages or something manual?

**Comment by czue** [comment]
makemessages

**Comment by twymer** [comment]
Hm, yeah there shouldn't be any problem with this. I'll push the new changes to transifex now.

**Pull request merged**
