### PR TITLE
GOOD BYE OLD CLOUDCARE

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride

The world will know that free men stood against a tyrant, that few stood against many, and before this battle was over, even a god-king can bleed.

cc: @proteusvacuum 

(label to test out edit forms)

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
:clap: :clap: :clap: :clap: :clap: :clap:

**Comment by dannyroberts** [comment]
```
  43 passing (194ms)
  2 failing
  1) WebForm WebFormSession Should queue requests:
     AssertionError: expected false to be true
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:558
      at addProperty (http://localhost:8000/static/chai/chai.js:3901)
  2) WebForm WebFormSession Should ensure session id is set:
     AssertionError: expected null to equal 'my-session'
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:2178
      at http://localhost:8000/static/cloudcare/js/form_entry/spec/webformsession_spec.js:223
>> 2/45 tests failed (0.19s)
Warning: Task "mocha:cloudcare#form_entry" failed. Use --force to continue.
```

**Comment by dannyroberts** [comment]
@benrudolph merged for you. Any idea how bad these tests would be to fix?

**Comment by benrudolph** [comment]
🙌  probably not that hard. i can take a look

**Comment by benrudolph** [comment]
https://github.com/dimagi/commcare-hq/pull/16091/commits/bef142b82f834e05fa71645fbad88493b451a4d6 -- fixed here

**Review by dannyroberts — APPROVED** [review]

**Comment by dannyroberts** [comment]
NBD

**Comment by benrudolph** [comment]
BFD

**Comment by snopoke** [comment]
I'm drinking wine to celebrate 🍷🍾

**Comment by benrudolph** [comment]
i'm chugging wine to celebrate. and it's only 11am! 🍷 🍷 🍷

**Pull request merged**
