### PR TITLE
fix JS error when there are graph configs in the report module

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?226803

### CODE REVIEW

**Comment by czue** [comment]
looks good to me but don't have complete context. should @orangejenny look?

**Comment by orangejenny** [comment]
looks fine. @nickpell if you have an explanation about why this is broken and why the fix works, i'd be interested. (looks like it broke due to https://github.com/dimagi/commcare-hq/commit/cf7c7417e84496b94bb78d96897417860fd3779d which @esoergel wrote and i merged without 100% following why it was needed)

**Comment by nickpell** [comment]
looks like https://github.com/dimagi/commcare-hq/commit/cf7c7417e84496b94bb78d96897417860fd3779d#diff-2fc48f8d9cd3d1ba8d69e5b62c2806a1R71 changed the variable being accessed.  I'm speculating that this wasn't tested using a report with graphs.

**Comment by esoergel** [comment]
This looks correct - the issue in the other PR was that unrecognized data-binds weren't being called at all, so switching to the onload handler restored the 2.x behavior.

**Pull request merged**
