### PR TITLE
use codemirror to make editing UCRs a bit nicer

### PR DESCRIPTION
**Pull request by dannyroberts**
@NoahCarnahan what do you think?

screen shot 2015-07-31 at 5 26 35 pm

### CODE REVIEW

**Comment by czue** [comment]
nice!

**Comment by NoahCarnahan** [comment]
:+1:

**Comment by dannyroberts** [comment]
@dimagi/team-commcare-hq Heads up on changing the textarea widget for manually editing UCRs. If anyone experiences problems with this (browser compatibility, etc.) ping me on it. Worked great locally.

**Comment by nickpell** [comment]
:+1: :+1: :+1: :fireworks: :tada:

**Comment by benrudolph** [comment]
super cool! wonder if this would jazz up our custom xpath textarea widget. could be nice to have syntax highlighting there as well

**Comment by dannyroberts** [comment]
Heh, I doubt that codemirror has an xpath syntax plugin, but even just the
monospaced text editor mode may be an improvement

**Comment by benrudolph** [comment]
true, just checked and they do not. though they do have XQuery which may just work

**Pull request merged**
