### PR TITLE
Remove safe filter from inddex

### PR DESCRIPTION
**Pull request by mjriley**
## Technical Summary
One of many PRs [removing safe from templates](https://dimagi-dev.atlassian.net/browse/SAAS-12098)

### Safety story
This will be QA'd on staging

### Automated test coverage

None

### QA Plan
Will be releasing several PRs to QA for easier testing.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by orangejenny** [comment]
@esoergel Didn't you work on inddex? Do you know why reports were using `safe`?

**Comment by orangejenny** [comment]
Alternatively, @mjriley how do you know this own't negatively affect these reports?

**Comment by esoergel** [comment]
Looking briefly at the code, this looks kinda bananas.  The INDDEX reports all use simple strings for headers, but those strings are wrapped with `DataTablesHeader`, which defaults `complex = True`.  Then header HTML is generated by datatables in python [here](https://github.com/dimagi/commcare-hq/blob/457df86164aca4a6185aef09db594081fa1b5a19/corehq/apps/reports/datatables/__init__.py#L202-L220).  That could probably be detangled significantly, but it's something that I guess applies to all reports.

**Comment by mjriley** [comment]
`./manage.py populate_inddex_test_domain` doesn't appear to work (I get a 'Bad type' for Domain), but my trace through the code agrees with your assessment about the danger of removing `safe` here. I'm going to go ahead and write a test suite for `DataTablesHeader`, and then rework the code, so that this output is safe.

**Comment by mjriley** [comment]
Updated the datatables render methods so that rendering functionality should not be affected

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
