### PR TITLE
add low prepaid credit modal

### PR DESCRIPTION
**Pull request by nickpell**
Screenshots:
Screen Shot 2019-03-29 at 8 57 16 AM
and
Screen Shot 2019-03-29 at 8 57 25 AM

### CODE REVIEW

**Review by gbova — APPROVED** [review]

**Comment by orangejenny** [comment]
prepaid_modal.js and downgrade_modal.js really ought to share code.

```
$ diff corehq/apps/hqwebapp/static/hqwebapp/js/prepaid_modal.js corehq/apps/hqwebapp/static/hqwebapp/js/downgrade_modal.js
4c4
< hqDefine("hqwebapp/js/prepaid_modal", [
---
> hqDefine("hqwebapp/js/downgrade_modal", [
13c13
<         $.cookie(cookieName(slug, domain), true, { expires: 30, path: '/' });
---
>         $.cookie(cookieName(slug, domain), true, { expires: 1, path: '/' });
21c21
<         var $modal = $("#prepaid-modal"),
---
>         var $modal = $("#downgrade-modal"),
35c35
<         $modal.on('click', '#prepaid-snooze', function () {
---
>         $modal.on('click', '#overdue-invoice-snooze', function () {
42,44c42,43
<         $("#prepaid-link").on('click', function () {
<             kissmetrics.track.event(
<                 '[Credit Running Out Notification] Clicked Add Credits or Modify Subscription button');
---
>         $("#overdue-invoice-link").on('click', function () {
>             kissmetrics.track.event('[Overdue Notification] Clicked Pay invoice now');
46,47c45,46
<         $("#prepaid-snooze").on('click', function () {
<             kissmetrics.track.event('[Credit Running Out Notification] Clicked Remind me later');
---
>         $("#overdue-invoice-snooze").on('click', function () {
>             kissmetrics.track.event('[Overdue Notification] Clicked Remind me later');
```

**Comment by orangejenny** [comment]
prepaid_modal.html and downgrade_modal.html, too

**Comment by nickpell** [comment]
@orangejenny I'm gonna take a pass at refactoring this over the weekend.

Do you have any thoughts on the button sizes?  Is it preferable to make "Remind me later" take up more space so it becomes a similar size as "Add Credits or Modify Subscription"?

**Comment by orangejenny** [comment]
I think button size is okay. They are fairly different, but the big one is the one we want them to click on, so...seems fine.

I don't think we've ever talked about having standard buttons sizes, we always let them depend on the text. It's an interesting design thought.

**Comment by nickpell** [comment]
> I'm gonna take a pass at refactoring this

Unfortunately, this did not pan out.

**Pull request merged**
