### PR TITLE
Only add case filter group which is selected

### PR DESCRIPTION
**Pull request by Rohit25negi**
fixes https://dimagi-dev.atlassian.net/browse/HI-673

pending for testing on staging

### CODE REVIEW

**Review by biyeun — APPROVED** [review]

**Comment by orangejenny** [comment]
Checking my understanding:
- Each group will now show at most once in the dropdown
- Reporting groups will be marked "[group]"
- Case sharing groups will be marked "[case sharing]"
- Groups that are both reporting and case sharing will be marked "[group]"

Yes? @Rohit25negi @djmore9

**Comment by Rohit25negi** [comment]
> Checking my understanding:
> 
> * Each group will now show at most once in the dropdown
> * Reporting groups will be marked "[group]"
> * Case sharing groups will be marked "[case sharing]"
> * Groups that are both reporting and case sharing will be marked "[group]"
> 
> Yes? @Rohit25negi @djmore9

Reporting group will be marked as '[group]': Yes
Case sharing groups will be marked "[case sharing]": Yes
Groups that are both reporting and case sharing will be marked "[group]": No, So in the filter dropdown, user will still see two items( [group] and [case sharing]). But if user selects one of them. and click apply. Filter wont automatically fill the other one. Filter will show only the item([group] or [case sharing]) which is selected by the user. BUT  to reiterate they both will exist as separate entity in the options list. This was decided in the ticket because they both posses different meaning.

**Comment by orangejenny** [comment]
@Rohit25negi cool, thanks for explaining

**Comment by Rohit25negi** [comment]
Tested on Staging. Ready for Final review and merge

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
