### PR TITLE
EWS: Products Fix

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue 

http://manage.dimagi.com/default.asp?157858

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by lwyszomi** [comment]
@czue 

Please let me know when this will be deployed, because we must rerun the task to assign products to locations. We can do this tomorrow morning (my timezone), then all will be ready to show client.

**Comment by czue** [comment]
@lwyszomi sorry forgot to notify you but was deployed last night. i think you saw.

**Comment by lwyszomi** [comment]
@czue 

No problem, I noticed.

**Pull request merged**
