### PR TITLE
Added initial pull of multimedia to link_app

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
https://dimagi-dev.atlassian.net/browse/USH-483

One of the performance optimizations in https://github.com/dimagi/commcare-hq/pull/25010/ was that when updating a downstream app, HQ now only pulls *new* multimedia from the upstream remote app. But now when creating a new remote linked app, any multimedia that was present in the upstream app at the time the downstream app was created is never pulled.

This PR adds a multimedia pull to `link_app` to fetch that initial multimedia. The new code is taken from [here](https://github.com/dimagi/commcare-hq/blob/7a6514835e9a7e161c9ffce4e05221deeb06e32a/corehq/apps/app_manager/views/utils.py#L363-L369).

## Feature Flag
Linked project spaces

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

None.

### QA Plan

Not requesting QA. Creating new remote linked apps is a rare, dev-only process. I did verify locally that I can still create new non-remote linked apps without issue.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by mkangia — COMMENTED** [review]
A bit confused here.
So the improvement that was done earlier changed the process to pull "missing" files, which should still be true right? After making a linked app, when a version is pulled, it should pull the missing files which should be all of them in the first pull.
Or
Are we just now doing that upfront and not wait for the first version pull?
If yes, then that does not relate to the older PR linked right? It's an improvement on its own.

**Comment by orangejenny** [comment]
> After making a linked app, when a version is pulled, it should pull the missing files which should be all of them in the first pull.

This won't be true if the app was first copied, and then `link_app` was called afterwards, which I think is what happened here. I believe the project team copied the app from prod to staging and then @calellowitz set up the link. So on the first pull, little or no multimedia was recognized as new.

**Comment by mkangia** [comment]
thanks for the response @orangejenny 

> So on the first pull, little or no multimedia was recognized as new.

Why is that? On the first pull, won't HQ find that the multimedia files are missing?
https://github.com/dimagi/commcare-hq/blob/2a4000d67046c3842d2587d27c650ebd93fa1c50/corehq/apps/linked_domain/util.py#L83

**Comment by orangejenny** [comment]
@mkangia I think the issue is that because of [this](https://github.com/dimagi/commcare-hq/blob/18bb17cd471720c943f5d70131a4dd479767a09e/corehq/apps/app_manager/views/utils.py#L351), all multimedia references in the previous version are ignored, and in this case, the previous version has a bunch of multimedia.

**Comment by mkangia** [comment]
@orangejenny may be I am missing something here, but `pull_missing_multimedia_for_app` is called later in that method, which checks for corresponding multimedia for each of those ids and then pulls them if they are missing for a remote app. Should not that fetch the Multimedia files?

**Comment by orangejenny** [comment]
@mkangia Maybe my head is still fuzzy from being on vacation. Here are my thoughts:
* You start with version 10 of app A, which includes an image.
* You copy app A to a different server with [this process](https://confluence.dimagi.com/pages/viewpage.action?pageId=12223694). This creates A' version 1, which contains a reference to the image, but doesn't have the multimedia file since mm files aren't included when you copy an app between servers.
* You run `link_app_to_remote` to link A' to A.
* You update app A and add a second image.
* You pull A', the first time it's ever been pulled.
   * In `update_linked_app`, `old_multimedia_ids` includes the first image, since it's in the current version of A'
   * `pull_missing_multimedia_for_app` will pull the second, "new", image, but not the first one.
   * A' version 2 gets created, but it only has the second image, not the first one.

**Comment by mkangia** [comment]
Thanks for writing that out @orangejenny 

This is the step which I was concerned about
> pull_missing_multimedia_for_app will pull the second, "new", image, but not the first one.

Reading that method more carefully now, The issue is at this step?
https://github.com/dimagi/commcare-hq/blob/2a4000d67046c3842d2587d27c650ebd93fa1c50/corehq/apps/linked_domain/util.py#L80
where the MM is actually "missing" but is getting ignored. That makes sense.
I believe we can't remove that continue block, which would resolve such scenarios, otherwise it will bombard the blob db for checking on mm files.

**Review by mkangia — APPROVED** [review]

**Comment by orangejenny** [comment]
@mkangia Yes, exactly. Thanks for talking this through!

**Pull request merged**
