### PR TITLE
Add secret placeholders for abdm

### PR DESCRIPTION
**Pull request by akashkj**
## Product Description
Add secrets required for interacting with the ABDM APIs
Related commcare cloud PR: https://github.com/dimagi/commcare-cloud/pull/5456

## Technical Summary
https://docs.google.com/document/d/1gbQcAC3H4kj22iMCMMKSYMVO5_7kt56qiS8OWkd6e34/edit#

## Feature Flag
NA

## Safety Assurance
Keys are added with no sensitive data

### Safety story
Referred to https://confluence.dimagi.com/display/saas/How+to+add+new+secrets+or+other+local+settings for the changes

### Automated test coverage
NA

### QA Plan
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
Given how small this PR is, would it make sense to include this with the code that uses these new settings?

**Comment by akashkj** [comment]
@millerdev These values are to be used in https://github.com/dimagi/commcare-hq/pull/32109/files#diff-dfc12d613e146b0f1b19d47ae57e7572559c3043eba9d3f22ad567a8301c9d51R9 but since that is still not completed, plan is to do the testing by deploying on staging(without other PR merge in recent future). Hope that clarifies the intention.

**Comment by dannyroberts** [comment]
@akashkj, could you do that by just putting https://github.com/dimagi/commcare-hq/pull/32109 on staging? or are you saying that that PR isn't ready to go on staging and that you want to test just the presence of these localsettings on staging separately from the work being ready to test on staging?

**Comment by akashkj** [comment]
Got your points, I had some confusion. Please ignore my previous comments. Have put this code also in the same PR.

**Pull request closed without merging**
