### PR TITLE
Remove "_entered convention" wrap functions

### PR DESCRIPTION
**Pull request by AddisonDunn**
## Product Description

This is the final step in tech debt work for the "save only edited form fields"/"remove the _entered convention" feature.

Link: [Jira ticket](https://dimagi-dev.atlassian.net/browse/USH-1673?atlOrigin=eyJpIjoiOTllZDU3ZTU4MmNiNDZjNzg5MWU5MGQ5MWM3Y2UwNDYiLCJwIjoiaiJ9).

Note for reviewers: review by commit since this PR includes changes to a lot of JSON files and the "Files Changed" UI will be messy.

## Technical Summary

This PR removes all the wrap functions we added to app manager when we merged [the code for the "save only edited form fields" feature](https://github.com/dimagi/commcare-hq/pull/30910). One of the goals of running [the migration around this feature](https://github.com/dimagi/commcare-hq/pull/31877) was to enable us to clean up app manager code by removing these wrap functions.

It technically should be possible to remove *all* the wrap functions in app manager at this time, but that'll likely require a deeper tech debt push than is allocated for this work (which I think has gone well beyond its estimated story points already). However, if one were to attempt such a job, they might find the document attached to the above linked Jira ticket interestng, which logs all the errors encountered when we wrapped every app we have. There were errors with some apps/domains which are mostly old and have outdated formatting that makes them unusable anyways.

## Feature Flag

Not specific to any FF, affects all apps on all domains.

### Safety story

Played around with apps locally. This code has been live on staging for week with no reported issues from what I've heard.

### Automated test coverage

None.

### QA Plan

Not sure if we can do more detailed QA than "do apps break".

### Migrations

Prior migration was run in #31877.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
❤️ seeing wrap methods get deleted.

**Comment by orangejenny** [comment]
> It technically should be possible to remove all the wrap functions in app manager at this time, but that'll likely require a deeper tech debt push than is allocated for this work

Can you say more about this? It looks like the migration wrapped and saved all wrappable apps, including builds and linked apps, which indeed ought to make the `wrap` functions removable. I think most of those functions are old enough that they're rarely/never executed anyway.

Not asking you to take this on, only asking if there's specific additional work you had in mind.

**Comment by orangejenny** [comment]
Cool, thanks, I agree with all that. If it's a slow week I'll take a stab at killing some of those additional wrap functions.

**Review by snopoke — APPROVED** [review]

**Review by esoergel — APPROVED** [review]

**Comment by snopoke** [comment]
@AddisonDunn is this waiting on something?

**Comment by snopoke** [comment]
> @snopoke yeah, [the migration](https://github.com/dimagi/commcare-hq/pull/31877) needs to be run again before merging. 

Why does it need to be run again?

**Comment by snopoke** [comment]
I think we can run it as a management command and then create a migration for 3rd party envs. 

You could a strategy like [this](https://github.com/dimagi/commcare-hq/commit/dbd9660626f15722fa44c5071eccc3ac34299095) to determine if the migration needs to be run.

**Comment by orangejenny** [comment]
@AddisonDunn Has anything changed since last review?

**Review by snopoke — APPROVED** [review]

**Pull request merged**
