### PR TITLE
add hqpillowtop0 to inventory

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dannyroberts** [comment]
@dimagi/team-commcare-hq Must be merged before next normal deploy. (So far I've been deploying by checking out this branch first.)

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by NoahCarnahan** [comment]
Nice! Let's not forget to update this: https://confluence.dimagi.com/display/commcarehq/Firefighting+HQ

**Comment by dannyroberts** [comment]
@NoahCarnahan, so on point! Updated

**Comment by snopoke** [comment]
Should also add a graph to slow.commcarehq.org. I spent a few minutes trying to figure out where its hosted but didn't get far.

**Comment by czue** [comment]
it's not in a very intuitive place: https://github.com/dimagi/salt-states/blob/master/docs/new-worker-machine.rst#activate-new-relic-and-monitoring-dashboards

**Comment by snopoke** [comment]
SSH to whereis is super slow. In case anyone else wants to try the charts are:

hqpillowtop0 CPU - <iframe src="https://rpm.newrelic.com/public/charts/7g1t1HN5OiR" width="500" height="300" scrolling="no" frameborder="no"></iframe>
hqpillowtop0 MEM - <iframe src="https://rpm.newrelic.com/public/charts/lD5VE6W9MNs" width="500" height="300" scrolling="no" frameborder="no"></iframe>

**Pull request merged**
