### PR TITLE
Custom scheduled subject

### PR DESCRIPTION
**Pull request by nickpell**
(For Abt) Allows specifying a custom subject line in the email sent by Scheduled Reports.

Screenshot 1)

screen shot 2015-08-27 at 3 21 26 pm

Screenshot 2)

screen shot 2015-08-27 at 3 22 05 pm

Holding off merge for feedback from @dimagi/product 

@dannyroberts

### CODE REVIEW

**Comment by amsagoff** [comment]
@biyeun for UX input

Feels like we should just have a text box that says "Email Subject" with the default text in it that users can choose to update or not rather than a checkbox.

Also think it makes sense to put the email subject box above the recipients box (to mimic the organization of an actual email). So it would be the first setting on the page.

**Comment by nickpell** [comment]
@amsagoff 
> Feels like we should just have a text box that says "Email Subject" with the default text in it that users can choose to update or not rather than a checkbox.

One complication is that we translate the default subject, so we'd have to consider whether we still want to translate the default subject if it's explicitly shown to the user.

> Also think it makes sense to put the email subject box above the recipients box (to mimic the organization of an actual email). So it would be the first setting on the page.

:+1:

**Comment by amsagoff** [comment]
Interesting. I forget if the subject gets translated based on the sender's
information or the recipients'. If sender then we might consider not
translating.

**Comment by biyeun** [comment]
can we not have a checkbox? Just put Subject: and then Description. If subject is blank show the defaults to message underneath

**Comment by nickpell** [comment]
@amsagoff The subject gets translated based on the recipient's language.  Unfortunately this complicates things a bit.

**Comment by czue** [comment]
my personal opinion is we should push translation out of scope

**Comment by amsagoff** [comment]
Sounds good

**Comment by nickpell** [comment]
:+1:

**Comment by nickpell** [comment]
closing in favor of https://github.com/dimagi/commcare-hq/pull/8069

**Pull request closed without merging**
