### PR TITLE
Use multiple windows for growth monitoring aggregation

### PR DESCRIPTION
**Pull request by emord**
@calellowitz this should make aggregations faster which will help the 0's during the day issue caused by aggregations lasting into IST.

There should be no functional change, just changing this from being 1 insert & 5 updates to 1 monster of a query. If postgres every implements `IGNORE NULLS` this will be very simple with only one window function.

@czue may be interested as this is probably the most complex aggregation for ICDS.

stickler will yell about line length, but I left them for readiblilty

### CODE REVIEW

**Review by jmtroth0 — APPROVED** [review]
lgtm from a general perspective. only nit would be the `over`'s and `as`'s that are inconsistently cased in the query, which makes it a bit odd to look at.

also, the same logic is repeated so many times it almost seems worthwhile to add a pg function

**Comment by emord** [comment]
> only nit would be the over's and as's that are inconsistently cased in the query, which makes it a bit odd to look at.

Thanks that annoys me too, and fixed in latest commit

> also, the same logic is repeated so many times it almost seems worthwhile to add a pg function

Is it possible to add a pg function for just columns in a where clause or a window aggregation? I agree that this was a smell to me, but when I started to extract the logic into a helper function, it always felt less readable

**Comment by czue** [comment]
after 15 minutes of staring and reading docs I think i understand this query. dear lord.

**Review by calellowitz — APPROVED** [review]
Looks good

**Comment by emord** [comment]
> after 15 minutes of staring and reading docs I think i understand this query. dear lord.

Yeah. window functions are great, but they took me a bit to wrap my mind around. Happy to attempt to document more or chat about this query if needed

**Comment by czue** [comment]
> Happy to attempt to document more or chat about this query if needed

Thanks but not asking for that. It was the named window syntax that was harder to find in the first few doc sources I looked at. Once you understand the primitives the query itself is pretty reasonable.

**Pull request merged**
