### PR TITLE
Temporarily remove XFormInstance

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke if we deploy this branch in a private release, and i run 

```
./manage.py ptop_reindexer_v2 form
```

that should do the trick right? observed locally and from your comment that it does the reindex in place. going to test it out on staging and then run it for real

### CODE REVIEW

**Comment by snopoke** [comment]
Yup. That should do the trick though it could be a good idea to add this so
that the index settings don't get changed
https://github.com/dimagi/commcare-hq/commit/4d00b28cdaeb29c14edbc6fe761a704cc8be85fc

**Comment by benrudolph** [comment]
👍

**Comment by benrudolph** [comment]
cool so that updates the command to:
```
./manage.py ptop_reindexer_v2 form --in-place
```

**Comment by benrudolph** [comment]
(done)

**Pull request closed without merging**
