### PR TITLE
add absolute_import across repo

### PR DESCRIPTION
**Pull request by nickpell**
```python-modernize . -w -f libmodernize.fixes.fix_import```

@dimagi/py3

### CODE REVIEW

**Comment by orangejenny** [comment]
bless you

**Review by esoergel — CHANGES_REQUESTED** [review]
Looks like this PR rmoves `custom/ucr_ext/tests.py`, guessing that's a mistake.

**Comment by esoergel** [comment]
Actually maybe not - run `$ git show 3e88dbe4554316981e7f9a43fde34aa8870702c9 custom/ucr_ext/tests.py`, it shows it as every line removed, but then added back with the future import.  Might just be a fluke in the diff algorithm.

**Comment by nickpell** [comment]
yeah, it looks like a fluke to me

**Comment by esoergel** [comment]
Ah, I see it now - looks like the editing process converted that file from carriage returns to normal line breaks.  Must've been edited by someone on Windows in a weird editor.

**Review by esoergel — APPROVED** [review]

**Comment by millerdev** [comment]
woohoo 🎉

**Pull request merged**
