### PR TITLE
option to hide unreleased builds in deploy page

### PR DESCRIPTION
**Pull request by sravfeyn**
@nickpell 
Note checkbox on top-right corner
screen shot 2016-02-15 at 3 40 23 pm

FYI @dimagi/product (This was an idea from Sri)

### CODE REVIEW

**Comment by czue** [comment]
lgtm. will let @dimagi/product take a look in case they have any feedback. is it right that this just hides the others, but doesn't do anything smart when you try to load more results?

**Comment by sravfeyn** [comment]
Right, it doesn't do any smart loading (like fetching only starred builds) but it does hide unstarred builds after fetching more builds. Smart loading involves modifying a couch-view (reindex didn't seem worthy) and figured this is a good alternative after chatting with Sri (original proposer of idea)

**Comment by czue** [comment]
cool. so the only confusing thing I could see about that is if you fetch more, but they are all unstarred then you won't actually see anything different and may be confused why that's happening. Also, it will load an inconsistent number of builds each time you click on it when it's checked. not sure if these are blockers, just pointing out

**Comment by amsagoff** [comment]
This is cool - is this trying to address the pain point of when your released version is paginated out of sight, so it's hard for infrequent HQ users to find? Or some other pain point too?

In general, we are trying to avoid adding additional checkboxes/configurations unless the pain point is significant and there is no other solution. (This is something I've gone back and forth with Cory about before). Checkboxes add noise to UI and can lead to decision paralysis/choice overload (read more here: http://uxmyths.com/post/712569752/myth-more-choices-and-features-result-in-higher-satisfac)

Any one checkbox might not be a big deal, but if you apply that thinking to every checkbox/choice you're thinking about putting in the product, it can add up. For this reason, I've been taking a hard line recently against checkboxes/choices.

It may take some more thinking about the user experience to get this right (or, the right way to do this might be too much LOE to accomplish right now). UX Team: @orangejenny @biyeun  - any thoughts?

**Comment by orangejenny** [comment]
Accessing old build on this page is obnoxious, so I think this is a cool idea. But I also agree with

> In general, we are trying to avoid adding additional checkboxes/configurations unless the pain point is significant and there is no other solution.

plus this is a problem

> if you fetch more, but they are all unstarred then you won't actually see anything different

Repeatedly clicking "View More" is a pain, because you have to click, then scroll, then click, then scroll...Infinite scroll would be cool, but getting that to interact correctly with the footer could be tricky. Some thoughts:
- Update the "View More" code to scroll to the bottom of the page after rendering the new rows
- Default to showing more builds (don't think it's a problem if this page scrolls, because most people only care about the top)
- Instead of a checkbox at the top, add a button at the bottom, so there's "View more builds" and "View more starred builds" (different wording, you get the idea)

**Comment by orangejenny** [comment]
Another thought, expanding on this

> Instead of a checkbox at the top, add a button at the bottom, so there's "View more builds" and "View more starred builds" (different wording, you get the idea)

...doesn't have to be a second button, could be a button dropdown where the main option is "View More" and there are options to "View More Starred" or "View All" or "View All Starred" or whatever.

**Comment by czue** [comment]
Reading through @amsagoff and @orangejenny's feedback I agree that we should give this some more thought before merging it in. Is a cool idea, but in it's current form I think the downsides outweigh the upsides. @sravfeyn if you wanted to roll this out as-is for DSI you could consider putting it behind a feature flag.

**Comment by proteusvacuum** [comment]
@sravfeyn is this PR still active?

**Comment by sravfeyn** [comment]
I think there is a backlog ticket where folks are trying to decide the right behaviour. I don't think it's worth putting such a small UI tweak on flag. Hopefully the backlog ticket gets worked on at some point. I am closing this PR

**Pull request closed without merging**
