### PR TITLE
Added location safe

### PR DESCRIPTION
**Pull request by Rohit25negi**
fixing the location safe: https://dimagi-dev.atlassian.net/browse/ICDS-453?atlOrigin=eyJpIjoiNGMyODhmODIwZWRlNGVlZjk3MWViY2I3ODA4NmI1M2QiLCJwIjoiaiJ9

### CODE REVIEW

**Review by sravfeyn — APPROVED** [review]

**Comment by emord** [comment]
Can you add a test that creates a user, assigns location, and attempts to resolve each view?

**Comment by millerdev** [comment]
Please fix lint errors before merging. Thanks!

**Comment by Rohit25negi** [comment]
> Please fix lint errors before merging. Thanks!

done

**Comment by Rohit25negi** [comment]
> Can you add a test that creates a user, assigns location, and attempts to resolve each view?

Hey @emord, Dont want to make the icds deploy wait, I will be adding the test cases in the followup Pr. created a ticket [here](https://dimagi-dev.atlassian.net/browse/ICDS-458). I will most probably pick this up tomorrow.
@calellowitz

**Pull request merged**
