### PR TITLE
add a symlink to fab directory

### PR DESCRIPTION
**Pull request by dannyroberts**
to preserve current docs, scripts; to simplify fabfile.py

### CODE REVIEW

**Comment by dannyroberts** [comment]
@benrudolph fyi. @snopoke do you happen to know if symlinking was intentionally rejected for this? (Like does it not work on some system?)

**Comment by dannyroberts** [comment]
@millerdev buddy

**Comment by millerdev** [comment]
it won't work on windows, but I doubt our deploy would work on windows anyway

**Comment by millerdev** [comment]
👍

**Comment by snopoke** [comment]
I don't know of any reason why symlinking wasn't used.

**Comment by dannyroberts** [comment]
Thanks!

**Comment by benrudolph** [comment]
nice much better

**Pull request merged**
