### PR TITLE
Display UCR examples to rtd and expression docs to classes

### PR DESCRIPTION
**Pull request by emord**
I started this a while ago and forgot to push

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
I haven't reviewed the content since I assume it's just copy paste from the RST doc.

**Review by kaapstorm — APPROVED** [review]
Great to have this close to the code and still available from the README

**Comment by emord** [comment]
> I haven't reviewed the content since I assume it's just copy paste from the RST doc.

Yeah. its just copy/paste. one thing I noticed is that some of these comments are written as part of the guide, which isn't super appropriate for code level documentation (e.g. https://github.com/dimagi/commcare-hq/pull/24072/files#diff-0e68f78798297203e3bf8a3548376485R160  "Last, but certainly not least, are named expressions")

but I figured any changes should happen as part of a later PR/ad-hoc

**Comment by esoergel** [comment]
This is great!  Looks like the autodoc build is working too, did you have finagle anything to get that running?  I thought it'd been broken last I checked (seems to break every few months).

**Comment by emord** [comment]
@esoergel I haven't finagled with anything in the past couple of months. We were using an old integration a while ago that I updated, but I believe its been running since then

**Pull request merged**
