### PR TITLE
UCR rename cleanup

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Review by emord — APPROVED** [review]
Thanks for cleaning up. Has this been migrated on PNA yet? I think they have a couple of static data sources

**Comment by emord** [comment]
Oh. also does this need changelog for echis?

**Comment by snopoke** [comment]
@emord this shouldn't be merged yet. I'm going to wait some more time before merging. Re changelog I don't think it's required since the renames will happen during normal deploy. Perhaps what should happen is that I should create a migration that checks if the rename has taken place and if not fail with a message.

I'll update this branch with that approach.

**Comment by snopoke** [comment]
This has now been rolled out to all envs we are aware of. Any envs that have not rolled this out will get a failure message when running migrations with instructions on how to proceed.

**Review by emord — APPROVED** [review]

**Pull request merged**
