### PR TITLE
Bring back fab india

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dannyroberts** [comment]
@dimagi/team-commcare-hq you can now deploy to the new india server with `fab india awesome_deploy`

**Comment by esoergel** [comment]
:star2:

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dannyroberts** [comment]
g2m

**Comment by czue** [comment]
nice.

**Pull request merged**
