### PR TITLE
fix prior date_to_json fix

### PR DESCRIPTION
**Pull request by dannyroberts**
- use string_to_utc_datetime instead of dateutil
- do not use DefaultProperty().wrap—that doesn't work

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue if you're still on. I'll deploy after dinner. @gcapalbo FYI (since you just asked me a question about fri a few minutes ago and want you to know this is getting fixed)

**Comment by millerdev** [comment]
looks good. do you want to wait for tests?

**Comment by dannyroberts** [comment]
Might as well

**Comment by dannyroberts** [comment]
Just kidding, these builds are taking forever to start. Given that this can only really be as bad as it already is in production and these errors are continuing to happen, I'm going to self merge and deploy

**Pull request merged**
