### PR TITLE
Revert "register index and add adapter when using custom pillow"

### PR DESCRIPTION
**Pull request by joxl**
Reverts dimagi/commcare-hq#32251 now that the backfill pillow is no longer in use.

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
I think it's great to remove the unused backfill pillow, but worth keeping the name change until the new reindexing method is ready, since it looks likely we will need to reindex other indices before then, and the name change keeps it as a "public" method.

**Comment by joxl** [comment]
@calellowitz, that function was private by design, and this is reverting to the original design to avert new dependencies on a private function.

**Review by millerdev — APPROVED** [review]

**Comment by calellowitz** [comment]
> @calellowitz, that function was private by design, and this is reverting to the original design to avert new dependencies on a private function.

Until the multiplexer is ready, is there another way to reindex than to use this function? If not, I think keeping it public makes sense, since it seems likely we will need to reindex again due to the current ES stability issues.

**Comment by joxl** [comment]
If this code is needed again before the replacement is ready, you can change it back. I didn't block Simon when he submitted the PR that's being reverted.

**Review by calellowitz — APPROVED** [review]
If we have a known use case for this function, I would prefer it stayed public to signal that, rather than renaming each time we want to use it, but that is not blocking.

**Pull request merged**
