### PR TITLE
profile slow export view

### PR DESCRIPTION
**Pull request by nickpell**
@orangejenny 

@esoergel would be nice to get in before deploy

### CODE REVIEW

**Comment by orangejenny** [comment]
@nickpell is it reasonable to not wait for tests on this?

**Comment by nickpell** [comment]
I'd say so

**Comment by czue** [comment]
Please revert this. These files are huge and only meant to be run locally

**Comment by czue** [comment]
sorry @nickpell I should have mentioned that / it should be clearer in the docs that it's only meant for local profiling

**Pull request merged**
