### PR TITLE
Add travis node to reduce timeouts

### PR DESCRIPTION
**Pull request by millerdev**
@snopoke

### CODE REVIEW

**Comment by snopoke** [comment]
:+1: on :white_check_mark:

**Comment by czue** [comment]
whoa super cool that's all this takes

**Comment by orangejenny** [comment]
hooray

...does this really need to wait for tests?

**Comment by snopoke** [comment]
image

**Comment by czue** [comment]
:white_check_mark: :heavy_check_mark: :ballot_box_with_check: :heavy_check_mark: :white_check_mark:

**Pull request merged**
