### PR TITLE
Remove USE_FORMPLAYER_FRONTEND toggle

### PR DESCRIPTION
**Pull request by benrudolph**
@czue this was followup from the PR where i bumped it to 100%. we need to add these domains when this gets merged. will coordinate with interrupt. all the domains with a check box need to be added to the toggle

- [x] 'hsph-betterbirth'		
- [x] 'figo-ppiud-srilanka'	
- [x] 'broadreach-sa'	
- [x] 'goal-global'	
- [ ] 'ipm-senegal'		
- [x] 'madla-malaria'	
- [x] 'myrice'
- [x] 'pact'		
- [x] 'icrc-almanach' <- for swiss

(this'll probably break a bunch of tests)
cc: @emord

### CODE REVIEW

**Comment by emord** [comment]
I think if you want to avoid the battles with travis of fix 1 test, restart test, fix next test that breaks you can take `stop` out of https://github.com/dimagi/commcare-hq/blob/master/.travis.yml#L34

**Comment by benrudolph** [comment]
👍 good call

**Comment by czue** [comment]
huh, this seems a bit more annoying than I expected. don't feel obligated to do this on my account, though does feel like a better end state to be in, i think. 100% toggle also seems fine though if this doesn't feel worth it.

**Comment by benrudolph** [comment]
✅

**Comment by emord** [comment]
@benrudolph added these domains to prod. will add to swiss once I deploy

**Comment by benrudolph** [comment]
thanks j$

**Pull request merged**
