### PR TITLE
Specify UTF-8 encoding for enterprise report downloads

### PR DESCRIPTION
**Pull request by mjriley**
## Technical Summary
Associated ticket: https://dimagi.atlassian.net/browse/SAAS-15743

Django, by default, encodes its HTTP responses with UTF-8. Excel, by default, reads files as if they were using ASCII. This means that, when a CSV includes a character like `é`, Excel reads it as `√©`. Specifying a leading Byte Order Marker (BOM) allows Excel to detect the UTF-8 encoding automatically and display everything correctly.

In addition, it appears that the MIME-type for these downloads has never been correct (it was a dictionary), so I've corrected to it 'text/csv; charset=UTF-8'.

While adding tests, I noticed how awkward it was that we only create an enterprise report in order to determine it's filename. I feel like it would make a lot of sense to simply store the filename along with its contents, and thus we'd only need to pull from redis. However, I think that kind of change would be kind of tricky, as it would mean we'd risk any existing download links would break. Since this functionality wasn't broken, I opted not to fix it.

### Safety story
Verified this change by performing local downloads, verifying their response headers in the Chrome Inspector, and then verifying the downloaded contents within Excel.

### Automated test coverage

I've corrected my laziness and added the appropriate tests in the new test suite _test_views_

### QA Plan

No QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by dreesefadil — APPROVED** [review]

**Review by nospame — APPROVED** [review]

**Review by nospame — COMMENTED** [review]
Tests and the associated refactor look good, but admittedly I don't fully understand what `_patch_decorators` is doing here.

**Comment by mjriley** [comment]
> Tests and the associated refactor look good, but admittedly I don't fully understand what `_patch_decorators` is doing here.

The code under test (`enterprise_dashboard_download`) is decorated by `require_enterprise_admin` and `login_and_domain_required`. If I want to call `enterprise_dashboard_download` as a function, any call will need to pass those decorators. `require_enterprise_admin` requires a full accounting hierarchy to get the billing account (subscription, subscriber, billing account). `login_and_domain_required` requires a real domain object and user object, complete with either permissions or granted superuser access.

Because none of the test code cares about those objects, and because setting them up would significantly complicate the tests, I thought it was better to mock out both decorators to just return the decorated function. Decorators are more difficult to mock out, however, because by the time you want to mock the decorator, the original function has already been imported and decorated. That's why the code patches the decorators and then reloads the original function.

I'd still like to improve the readability, however. Is the mock->start->stop generally confusing, or was `lambda x: x` also a source of confusion. I wonder if creating a `no_op_decorator` for the latter would make things more easily understood.

**Comment by nospame** [comment]
> I thought it was better to mock out both decorators to just return the decorated function.

I agree with that for sure.

>  Is the mock->start->stop generally confusing

Maybe it's this. I think what's throwing me off at this point is the same `_patch_decorators` and `reload` lines called in both `setUpClass` and `setUp`.

> or was `lambda x: x` also a source of confusion.

I wasn't familiar with this offhand, but I think that's on me for not knowing the particular syntax.

**Comment by mjriley** [comment]
> Maybe it's this. I think what's throwing me off at this point is the same `_patch_decorators` and `reload` lines called in both `setUpClass` and `setUp`. If that's just the way it has to work, a comment might be helpful.

Thanks for calling this out. This is an error on my part, because the code started in `setup` and I moved it to `setupClass`.

**Review by nospame — APPROVED** [review]

**Pull request merged**
