### PR TITLE
Externalize JS: deletion modal for old exports

### PR DESCRIPTION
**Pull request by orangejenny**
@jmtroth0 / @millerdev 
@jmtroth0 / @esoergel I haven't tested this - what's the due diligence needed here?

code buddy @gcapalbo

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
Honestly I wouldn't worry about it - there are only a few old exports remaining, and I don't expect them to be around much longer.

**Review by jmtroth0 — APPROVED** [review]
Seems like a pretty simple change either way. 

What is the expected behavior from this though? It looks like all it might just block that chrome popup "are you sure you want to leave this page while submitting", which seems a bit hacky?

**Comment by jmtroth0** [comment]
From the commit name, that's exactly what happening. https://github.com/dimagi/commcare-hq/commit/79f48489db94aebd886813795ee7456e696fbe33#diff-cca39dcdc416953577a5563f252e7d84R333. Any idea why this was necessary?

**Review by gcapalbo — APPROVED** [review]

**Comment by orangejenny** [comment]
> Honestly I wouldn't worry about it

Sweet, I was hoping you'd say that.

> Any idea why this was necessary?

I'm guessing it was a usability improvement. The modal asks if you're sure you want to delete the export, so clicking ok and then having the page itself give you the onbeforeunload alert about unsaved changes would be surprising/annoying.

**Pull request merged**
