### PR TITLE
Remove onerror

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @esoergel i think it's pretty fair to say this has just turned to spam. it may be worth having the actual url route in case we want to log any javascript errors?

### CODE REVIEW

**Comment by esoergel** [comment]
Not sure I understand the ramifications of removing this, so I'll punt to @czue

**Comment by benrudolph** [comment]
Fine to punt; just for some context this was an attempt I made at logging some of our Javascript errors. It turned out that this kind of flooded our inbox and made up over half of the errors coming from HQ even with exponential backoff. I tried for a while to make some use of them and only a few were reproducible from the url

**Comment by esoergel** [comment]
Oh I didn't realize this had just been added.  Makes sense then.

**Comment by czue** [comment]
bummer, but a good test and also nice to stop doing things. 

I guess we'll keep the endpoint around in case we want to do it explicitly on individual pages or whatever?

**Comment by benrudolph** [comment]
yea that's what i was thinking

**Pull request merged**
