### PR TITLE
Allow manually modifying form link datums

### PR DESCRIPTION
**Pull request by proteusvacuum**
This shows a button that allows you to modify form link datums even if those form links can be "automatically" linked.
This allows for form linking between forms with the same case type, where the first form both loads and creates a case of the same type. This way you can choose the case you want to load (i.e. the case that is loaded, or the case that is created). 
@snopoke heads up
@millerdev

### CODE REVIEW

**Comment by millerdev** [comment]
@proteusvacuum: not sure if @snopoke got a notification on this since it looks like you @ mentioned his name in the PR description in an edit that happened after the original submission.

**Review by millerdev — APPROVED** [review]
Would it be hard to add tests for the JS code changes? Maybe they're too small to bother? Otherwise nothing stuck out to me, but I don't feel like I have much context here.

**Comment by benrudolph** [comment]
there are actually tests for this exact file 😄 https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/static/app_manager/spec/form_workflow_spec.js

**Comment by benrudolph** [comment]
though it does look like you might not get that many useful tests from your changes

**Pull request merged**
