### PR TITLE
Restore overwrite cache

### PR DESCRIPTION
**Pull request by benrudolph**
http://manage.dimagi.com/default.asp?165375#920282

### CODE REVIEW

**Comment by benrudolph** [comment]
@czue 
enchantress: @millerdev

**Comment by czue** [comment]
build fail looks real:
```
======================================================================
FAIL: testRestoreAttributes (casexml.apps.phone.tests.test_ota_restore.FileRestoreOtaRestoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "corehq/ex-submodules/casexml/apps/phone/tests/test_ota_restore.py", line 244, in testRestoreAttributes
    self.assertTrue('<dateattr somedate="2012-01-01">' in restore_payload)
AssertionError: False is not True
----------------------------------------------------------------------
Ran 17 tests in 12.959s
```

**Comment by benrudolph** [comment]
weird, i'm getting the same failure on master. will have to look into this one

**Comment by benrudolph** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
@benrudolph thanks

**Pull request merged**
