### PR TITLE
Skip tasks if DHIS2 API integration is not enabled

### PR DESCRIPTION
**Pull request by kaapstorm**
(DHIS2 API integration is disabled by default in settings.py)

cf. [FB 154801](http://manage.dimagi.com/default.asp?154801)

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
build fail:
```
FAIL: test_sync_child_entities (custom.dhis2.tests.TaskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/custom/dhis2/tests.py", line 421, in test_sync_child_entities
    pull_mock.assert_called_with(DOMAIN, foo)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/mock.py", line 859, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: pull_child_entities('wv-lanka', <object object at 0x3e4da00>)
Not called
```

**Comment by czue** [comment]
presumably in the test setup, you just need to add `settings.DHIS2_ENABLED = True`

**Comment by kaapstorm** [comment]
Doh! Thanks Cory.

**Comment by dannyroberts** [comment]
Aha! Thanks this has been annoying me :)

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by kaapstorm** [comment]
(Pushed to both this branch and dhis2)

**Pull request merged**
