### PR TITLE
Requirejs my saved reports

### PR DESCRIPTION
**Pull request by orangejenny**
Probably easier to review by commit. Makes some progress on the global vars in `standard_hq_report.js` but that's still a messy area. Sending through QA for that reason.

Product: marked all-users because this fixes an error on prod where you can't edit saved reports.

@millerdev / @Rohit25negi 
code buddies @pr33thi @snopoke 

[QA ticket](http://manage.dimagi.com/default.asp?281811)

### CODE REVIEW

**Comment by orangejenny** [comment]
ignoring stickler except for the parse error

**Review by millerdev — APPROVED** [review]
Good call on the QA. Tricky to follow all the moving parts here.

**Review by snopoke — APPROVED** [review]
Nice cleanup.

**Comment by orangejenny** [comment]
QA passed, merging

**Pull request merged**
