### PR TITLE
Revert "Set `request.project` in middleware"

### PR DESCRIPTION
**Pull request by emord**
Reverts dimagi/commcare-hq#6463

### CODE REVIEW

**Comment by emord** [comment]
@NoahCarnahan

**Comment by czue** [comment]
@NoahCarnahan reverted due to http://manage.dimagi.com/default.asp?166702 - maybe you can take a look at email reports and fix #6463 ?

**Comment by NoahCarnahan** [comment]
Gah, sorry @emord and @czue . Will fix today.

**Comment by czue** [comment]
no worries. this is the second time in recent history we've broken email reports - it's a brittle and untested portion of the code. major bonus points if the fix comes with a test!

**Pull request merged**
