### PR TITLE
No forms errors

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?187362
(this error already showed for advanced modules)

cc @millerdev

### CODE REVIEW

**Comment by czue** [comment]
I suspect this might break ReportModules

**Comment by czue** [comment]
@dimagi/product is it right that having no forms in a (non-report) module should always be a build error? or do we want to support a single case-list menu item?

**Comment by proteusvacuum** [comment]
@czue, it doesn't affect `ReportModule` (just added to regular `Module` class, not `ModuleBase`).

**Comment by czue** [comment]
ah cool, thanks. saw "`Module`" and assumed was the base class.

**Comment by czue** [comment]
given that this checks forms and case list I think it's fine to merge.

**Pull request merged**
