### PR TITLE
ICDS - Update mapping in tests

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @czue, @sravfeyn  

I updated the mapping in tests. I talked with @sravfeyn about this and now we have correct values for ```complementary_feeding``` and ```thr_form```.

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Review by czue — APPROVED** [review]
code looks good. will let @sravfeyn merge since he's got context.

**Review by sravfeyn — APPROVED** [review]
Thanks for the fix. LGTM after build pass

**Comment by sravfeyn** [comment]
https://github.com/dimagi/commcare-hq/pull/20203

**Comment by czue** [comment]
guessing test fail is related?

```
======================================================================
FAIL: custom.icds_reports.tests.reports.test_children_initiated:TestChildrenInitiated.test_average_with_two_locations_represent_by_one_topojson
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/reports/test_children_initiated.py", line 203, in test_average_with_two_locations_represent_by_one_topojson
    self.assertEquals(data['rightLegend']['average'], 80.71428571428572)
AssertionError: 0.0 != 80.71428571428572
----------------------------------------------------------------------
```

**Comment by lwyszomi** [comment]
:open_mouth:

**Comment by lwyszomi** [comment]
@czue @sravfeyn We can close this. My mistake, we have other file where we have data for ```ucr_table_name_mapping``` (https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/tests/fixtures/ucr_table_name_mapping.csv). I don't know why but I thought that this table is updated by this mapping.

**Pull request closed without merging**
