### PR TITLE
fix unicode in jar creation

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?217527

Not clear why this bug manifested itself now.

### CODE REVIEW

**Comment by nickpell** [comment]
@dannyroberts Would like to get merged once tests pass so I can deploy tonight and not hold up 2.26 QA 

@wspride

**Comment by dannyroberts** [comment]
@nickpell I'm guessing that it used to be the fact that everything that was passed in was an `str`, i.e. a bytestring (one char = one byte), and now some `unicode`s are getting passed in. My guess is that this is related to the lazy jar PR, and furthermore that it has to do with the fact that couchdbkit's `fetch_attachment` method will convert things that it *thinks* are unicode strings to the `unicode` type. That's happening here: https://github.com/dimagi/commcare-hq/blob/aa1f1add5b52e27bdc8cda8f745441496e50ccdd/corehq/apps/app_manager/models.py#L4189-4189.

I consider this bad behavior on couchdbkit's part, since `str` and `unicode` mean *very* different things, and when you're asking for an attachment it should return a the binary type (`str`), and let you decode it to unicode if you want. But, alas, that's what couchdbkit does. I would recommend adding something like

```
all_files = {name: (file if isinstance(file, str) else file.encode('utf-8')) for name, file in all_files.items()}
```

after the line I linked to, dealing with it at it's source rather than down the road. Also it's not clear to me that this solution will always work—if some of the files came back as byte strings and some came back as unicode, then calling encode on the bytestrings will fail.

**Comment by nickpell** [comment]
I'm fine modifying the fix here, but I won't be able to implement it and QA
it and get a deploy in all during off-hours in time for tomorrow's QA, FYI
Will

**Comment by dannyroberts** [comment]
I went ahead and implemented it in case someone wanted to merge/deploy while we were asleep.

**Comment by dannyroberts** [comment]
https://github.com/dimagi/commcare-hq/pull/10376

**Comment by czue** [comment]
:+1: thanks

**Pull request closed without merging**
