### PR TITLE
Kill hqmedia tags

### PR DESCRIPTION
**Pull request by dannyroberts**
This is a few different pieces of random cleanup, but the first commit was my main goal: getting rid of the last usage of `hqmedia/tags`. For fun, I'd like to share the entire contents (reduced) of that view in production for the world to see:

| key | value |
| --- | --- |
| "speaker" | 1 |
| "analyze_think" | 1 |
| "analyze" | 1 |
| "" | 1950 |

### CODE REVIEW

**Comment by dannyroberts** [comment]
:white_check_mark:  @proteusvacuum @orangejenny

**Comment by proteusvacuum** [comment]
:skull:

**Comment by czue** [comment]
lol

**Comment by czue** [comment]
get those deletion numbers up! :rage1:

**Pull request merged**
