### PR TITLE
Exports: Add missing arg

### PR DESCRIPTION
**Pull request by NoahCarnahan**
I guess the run through was worth it :P
@benrudolph 
cc @emord

### CODE REVIEW

**Comment by benrudolph** [comment]
Haha wow! It was indeed

**Comment by benrudolph** [comment]
This is very obviously a weak point in our tests. We should probably write
two or three view tests and just ensure we get a 200 response back (I can
do that on Monday, doesn't need to block this)

**Comment by snopoke** [comment]
lol

**Comment by czue** [comment]
hmm seems like this whole "not releasing today" thing is a good call. (kicked build)

**Pull request merged**
