### PR TITLE
Removed old CVSU reports

### PR DESCRIPTION
**Pull request by kkrampa**
@czue

### CODE REVIEW

**Comment by czue** [comment]
can you fix tests? should just be removing the section in `all-pillow-meta.json`

**Comment by czue** [comment]
======================================================================
FAIL: test_instantiate_all (testapps.test_pillowtop.tests.test_settings.PillowtopSettingsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/testapps/test_pillowtop/tests/test_settings.py", line 31, in test_instantiate_all
    self.assertEqual(len(all_pillow_configs), len(expected_meta))
AssertionError: 43 != 44

**Comment by czue** [comment]
looks good though the diff is really confusing. can you confirm you just replaced `reports` with `new_reports`?

**Comment by lwyszomi** [comment]
@czue :white_check_mark:

**Comment by czue** [comment]
@lwyszomi can you just confirm my other comment is accuate?

**Comment by lwyszomi** [comment]
@czue No exactly. I moved Kamil new reports to old classes because I think after removing old reports this is more readable. When Kamil was working on new reports he extends old classes and in new one he only overrides some methods.

**Comment by czue** [comment]
got it - thanks

**Pull request merged**
