### PR TITLE
hqDefine CloudCare

### PR DESCRIPTION
**Pull request by dannyroberts**
Can review :blowfish:, should also use ?w=1 or else it's a disaster

Also threw in another random file in there (`domain/js/media_manager.js`). I'm open to accusations of laziness.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/domain/static/domain/js/media_manager.js, line 23 - 'i' is already defined.
* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 79 - Missing semicolon.
* corehq/apps/cloudcare/static/cloudcare/js/backbone/cases.js, line 126 - Missing semicolon.
* corehq/apps/cloudcare/static/cloudcare/js/backbone/cases.js, line 45 - Use '===' to compare with '0'.
* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 56 - Missing semicolon.
* corehq/apps/domain/static/domain/js/media_manager.js, line 32 - Use '===' to compare with 'null'.
* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 39 - Missing semicolon.
* corehq/apps/domain/static/domain/js/media_manager.js, line 30 - Use '===' to compare with 'false'.

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 79 - Missing semicolon.
* corehq/apps/cloudcare/static/cloudcare/js/backbone/cases.js, line 126 - Missing semicolon.
* corehq/apps/cloudcare/static/cloudcare/js/backbone/cases.js, line 45 - Use '===' to compare with '0'.
* corehq/apps/domain/static/domain/js/media_manager.js, line 33 - Use '===' to compare with 'null'.
* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 56 - Missing semicolon.
* corehq/apps/domain/static/domain/js/media_manager.js, line 31 - Use '===' to compare with 'false'.
* corehq/apps/cloudcare/static/cloudcare/js/util.js, line 39 - Missing semicolon.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dannyroberts** [comment]
buddy @emord, cloudcare folks @czue @benrudolph

**Comment by benrudolph** [comment]
is it me or is w=1 not working?

**Comment by czue** [comment]
also not working for me. :disappointed:

**Comment by dannyroberts** [comment]
Ugh, @github, rude. @benrudolph @czue try https://github.com/dimagi/commcare-hq/compare/use-more-hqDefine?w=1

**Comment by benrudolph** [comment]
wow nice, much easier. all looks good. i can't comment on that diff, but just wanted to flag that this will actually change functionality:
```
return firstUnchecked === null;
```
i know it's better practice, but if firstUnchecked was `0` or `false` or anything falsey it would've previously evaluated to true. that being said, not too too worried about it

**Comment by dannyroberts** [comment]
Yeah I looked at that and the output of the function call above will be
null in the case they're checking for. Definitely good to check, and thanks
for the vigilance!

**Comment by benrudolph** [comment]
:cloud: :pill:

**Pull request merged**
