### PR TITLE
make UCR date filter inclusive if DateSpan is inclusive

### PR DESCRIPTION
**Pull request by nickpell**
1) Make the "Since Date" option in saved reports useful for UCR.
2) Make UCR date filters consistent with other reports.

### CODE REVIEW

**Comment by nickpell** [comment]
@NoahCarnahan @czue

**Comment by nickpell** [comment]
If we decide to reject this change or deploy a branch that does not have this commit on it, we need to let Gillian know, since her saved reports rely on this change.

**Comment by NoahCarnahan** [comment]
It looks like this fixes the behavior of comparing `datetime`s to `date`s, but I think it will change the behavior of the filter when it is being applied to a plain `date` field. For example, if the filter is `2015-05-28 to 2015-05-19`, then rows where the date is `2015-05-20` will be returned as well.

One way to solve this might be to add the largest `timedelta` less than one full day to the enddate. So, something like this I think:
```python
self.value.enddate + timedelta(days=1) - timedelta.resolution
```

**Comment by NoahCarnahan** [comment]
@nickpell 
I realized you're on vacation so I made the change. Updated this PR with my recommendation.

**Comment by NoahCarnahan** [comment]
Ha, looks like @czue is also on vacation, so reassigning.

**Comment by snopoke** [comment]
@NoahCarnahan is the `- timedelta.resolution` really necessary. I think that will just make `2015-05-20t00:00:00.0000` into `2015-05-19t23:59:59.9999` so unless you're dropping the timestamp somewhere else it should work fine.

**Comment by NoahCarnahan** [comment]
@snopoke I believe it is necessary because this filter is sometimes applied to date columns, and sometimes applied to timestamp columns. The `value.enddate` property of the filter is always a `date`. If the value being compared against is a timestamp, then the `- timedelta.resolution` won't make a difference. But, if the value being compared against is a date then it will matter.

**Pull request merged**
