### PR TITLE
sort products fixture on code

### PR DESCRIPTION
**Pull request by esoergel**
@snopoke @anyone

### CODE REVIEW

**Comment by czue** [comment]
build fail real:
```
======================================================================
FAIL: test_product_fixture (corehq.apps.commtrack.tests.test_fixture.FixtureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/commtrack/tests/test_fixture.py", line 115, in test_product_fixture
    ElementTree.tostring(fixture[0])
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 28, in assertXmlEqual
    _check_shared(expected, actual, LXMLOutputChecker(), "xml")
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/util.py", line 82, in _check_shared
    raise AssertionError(message)
AssertionError: XML mismatch
--- want.xml
+++ got.xml
@@ -1,5 +1,17 @@
 <fixture id="commtrack:products" user_id="66d7a7d5b5b58d41f54dcafedac170ac">
   <products>
+    <product id="f140eb18c372cc20212098e2817486aa">
+      <name>fubrsvdmzzpxtnzduslk</name>
+      <unit>egjrhthzkbylwlwgvpmc</unit>
+      <code>vwqwdjpxtsykpcngimrt</code>
+      <description>lqxqgvkffxapsyswkmkf</description>
+      <category>hwzlwaurccpvltfssbja</category>
+      <program_id>vawhdwsufkklzrvecxex</program_id>
+      <cost>0</cost>
+      <product_data>
+        <special_number>555111</special_number>
+      </product_data>
+    </product>
     <product id="f140eb18c372cc20212098e281748651">
       <name>hlqtprxuaqbxyhavlmqy</name>
       <unit>hwzogcnetyaebypkcoqf</unit>
@@ -18,17 +30,5 @@
       <program_id>fsirlsfwuzfijfuxvlod</program_id>
       <cost>72.2562</cost>
     </product>
-    <product id="f140eb18c372cc20212098e2817486aa">
-      <name>fubrsvdmzzpxtnzduslk</name>
-      <unit>egjrhthzkbylwlwgvpmc</unit>
-      <code>vwqwdjpxtsykpcngimrt</code>
-      <description>lqxqgvkffxapsyswkmkf</description>
-      <category>hwzlwaurccpvltfssbja</category>
-      <program_id>vawhdwsufkklzrvecxex</program_id>
-      <cost>0</cost>
-      <product_data>
-        <special_number>555111</special_number>
-      </product_data>
-    </product>
   </products>
 </fixture>
----------------------------------------------------------------------
```

**Comment by czue** [comment]
:+1: to merge when you fix tests

**Comment by snopoke** [comment]
👍

**Comment by snopoke** [comment]
👍

**Comment by esoergel** [comment]
Updated tests

**Pull request merged**
