### PR TITLE
[ICDS] moved each aggregation helper class to own file

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @calellowitz,

I clean aggregation file because it grows up and is hard to find what you want. So I moved each class to own file. 

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Comment by lwyszomi** [comment]
@calellowitz I think we can skip linter errors because this is in the SQL scripts.

**Comment by emord** [comment]
@lwyszomi thanks for splitting this up.

 This conflicted with some changes I made to the child_health_monthly step here: https://github.com/dimagi/commcare-hq/pull/22005/

**Comment by lwyszomi** [comment]
@emord @calellowitz I updated the PR waiting

**Comment by emord** [comment]
@lwyszomi I've been offline for the past couple of weeks. Looks like there's another merge conflict.

**Comment by lwyszomi** [comment]
@emord @calellowitz updated

**Comment by emord** [comment]
```
======================================================================
FAIL: custom.icds_reports.tests.test_aggregation_script:AggChildHealthAggregationTest.test_agg_child_health_2017_04_01_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 269, in test_agg_child_health_2017_04_01_1
    sort_key=self.sort_key
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 137, in _load_and_compare_data
    self._load_csv(path)
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_aggregation_script.py", line 129, in _fasterAssertListEqual
    self.fail('\n'.join(messages))
AssertionError: 
                    Actual and expected row 6 are not the same
                    Actual:   block_id: All, caste: All, resident: All, gender: F, supervisor_id: All, age_tranche: 6, height_measured_in_month: 1, district_id: All, disabled: All, state_id: st1, weighed_and_height_measured_in_month: 1, awc_id: All, minority: All
                    Expected: block_id: All, caste: All, resident: All, gender: F, supervisor_id: All, age_tranche: 6, height_measured_in_month: 0, district_id: All, disabled: All, state_id: st1, weighed_and_height_measured_in_month: 0, awc_id: All, minority: All
                
----------------------------------------------------------------------

```

related test failure. Can you do these sort of refactors in a more piece-wise manner? Its very difficult to reason about a 2,500 line commit and figure out why the test failure happend

**Comment by lwyszomi** [comment]
Hi @emord,

sorry for that mess in the commits, too many rebases. I changed the commits and now each helper we have in one commit. 

Please let me know if you have any questions.

Regards,
Łukasz

**Pull request merged**
