### PR TITLE
Remove name in excel web query

### PR DESCRIPTION
**Pull request by benrudolph**
@NoahCarnahan @emord this thing has been driving me nuts. in the end i decided to remove the name after trying various number of things with this html page: https://benrudolph.github.io/excel-web-query/. i still have to ensure it won't break old excel queries

http://manage.dimagi.com/default.asp?253389
http://manage.dimagi.com/default.asp?254400

### CODE REVIEW

**Comment by benrudolph** [comment]
ok tested going from having a header to not having a header and excel updates fine. other solution if we're worried about older version of excel not handling this correctly is to pass a param in and conditionally exclude the excel header and then only pass that param in on new dashboard links. that isn't my preferred solution as it will take a lot of parameter passing and i'm not super keen to introduce that tech debt

**Comment by emord** [comment]
test failure looks real

**Review by NoahCarnahan — APPROVED** [review]
I'm guessing excel still imports the entire page, regardless of what is selected, right? This would still be a problem who have multiple tables in an export, although it's probably a less common workflow, so I think this fix makes sense while excel is broken.

**Comment by benrudolph** [comment]
yes that is true and i thought about if there was a way to handle that. but at least in that case we can tell people the work around is to only select the table you want to import into excel :/ not great

**Pull request merged**
