### PR TITLE
Add index on sms processed timestamp

### PR DESCRIPTION
**Pull request by mkangia**
Add index to help speed up queries.

##### SUMMARY
ICDS generates a report for SMSes sent that [filters on processed_timestamp](https://github.com/dimagi/commcare-icds/pull/86/files#diff-308a8f0a0b59f4ec40dcdbb217a33df8R130) which is getting painfully slow.
So adding an index on that column to asses if that can improve things. Adding it only on the SMS model and not QueuedSMS (both inherit from SMSBase)

Note: I am getting `django.db.utils.InternalError: CREATE INDEX CONCURRENTLY cannot run inside a transaction block` after changing the migration to run concurrently, which I am not clear to why its happening. I have used the same process from other such migrations.
Also, if this does not need to run concurrently, we can keep it as a normal migration [as in first commit]

Some cost analysis on ICDS
```
In [8]: query = SMS.objects.filter(                                                                                
   ...:                 domain=domain,                                                                             
   ...:                 processed_timestamp__gt=start_timestamp,                                                   
   ...:                 processed_timestamp__lte=end_timestamp,                                                    
   ...:                 backend_api=AirtelTCLBackend.get_api_id(),                                                 
   ...:                 direction='O',                                                                             
   ...:                 processed=True,                                                                            
   ...:             )                                                                                              
    
For 30 day period                                                                                                               
In [9]: query.explain()                                                                                            
Out[9]: "Seq Scan on sms_sms  (cost=0.00..10085650.38 rows=12325361 width=3172)\n  Filter: (processed AND (process$d_timestamp > '2020-07-31 18:30:00'::timestamp without time zone) AND (processed_timestamp <= '2020-08-31 18:30:00$::timestamp without time zone) AND ((backend_api)::text = 'AIRTEL_TCL'::text) AND ((direction)::text = 'O'::text) $ND ((domain)::text = 'icds-cas'::text))

For 1 day period
In [12]: query.explain()
Out[12]: "Seq Scan on sms_sms  (cost=0.00..10085650.38 rows=808733 width=3172)\n  Filter: (processed AND (processed_timestamp > '2020-07-31 18:30:00'::timestamp without time zone) AND (processed_timestamp <= '2020-08-01 18:30:00'::timestamp without time zone) AND ((backend_api)::text = 'AIRTEL_TCL'::text) AND ((direction)::text = 'O'::text) AND ((domain)::text = 'icds-cas'::text))"
```

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
I'm not certain about the transaction error, but could it be the connection isolation mode? I notice that all other instances of `CREATE INDEX CONCURRENTLY` are in `form_processor` and `blobs`, which have their models in partitioned databases, which are in "autocommit" mode. That seems like it may be related. I don't have an immediate suggestion for a workaround though, sorry.

I do think we need to use `CREATE INDEX CONCURRENTLY` because the SMS table is large. If you do not use that option the migration will lock the table while it creates the index.

**Review by snopoke — COMMENTED** [review]
This should fix the transaction isolation issue

**Comment by mkangia** [comment]
> I do think we need to use CREATE INDEX CONCURRENTLY because the SMS table is large

Thanks for confirming that @millerdev

**Comment by mkangia** [comment]
@snopoke just confirming that the step now is to run this on prod and ICDS directly on pg shell and then merge it for rest yes?

**Comment by snopoke** [comment]
> just confirming that the step now is to run this on prod and ICDS directly on pg shell and then merge it for rest yes?

You could use a pg shell but I think the preferred approach is to run the django migrations from a limited release. 
You should run this first to ensure it's only your migration that's going to be run `python manage.py showmigrations | grep "\[ \]"`

You should also only migrate the main DB: `python manage.py migrate` (don't use `migrate_multi`)

**Comment by mkangia** [comment]
Cool, thanks @snopoke for sharing the ideal approach and the steps clearly. I will do that.

**Comment by mkangia** [comment]
[Cost Comparison, Original in description]
after adding index on ICDS
```
For 31 days
Index Scan using sms_sms_process_fa9dfa_idx on sms_sms  (cost=0.57..7089033.84 rows=12262220 width=3172)\
n  Index Cond: ((processed_timestamp > '2020-07-31 18:30:00'::timestamp without time zone) AND (processed_timestamp <= '2020-08-31 18:30:00'::timestamp without time zone))\n  Filter: (processed AND ((backend_api)::text = 'AIRTEL_$CL'::text) AND ((direction)::text = 'O'::text) AND ((domain)::text = 'icds-cas'::text))

for 1 day
Index Scan using sms_sms_process_fa9dfa_idx on sms_sms  (cost=0.57..913634.17 rows=812680 width=3172)\n
Index Cond: ((processed_timestamp > '2020-07-31 18:30:00'::timestamp without time zone) AND (processed_timestamp <$ '2020-08-01 18:30:00'::timestamp without time zone))\n  Filter: (processed AND ((backend_api)::text = 'AIRTEL_TCL$::text) AND ((direction)::text = 'O'::text) AND ((domain)::text = 'icds-cas'::text))
```

Ran count query which was defnitely faster than what I saw earlier.

**Comment by mkangia** [comment]
ran this on production as well, index getting picked

```
SMS.objects.filter(domain='test', processed_timestamp__gt=datetime.utcnow()).explain()

Index Scan using sms_sms_process_fa9dfa_idx on sms_sms  (cost=0.44..4.54 rows=1 width=666)\n  Index Cond: (processed_timestamp > '2020-09-03 15:10:14.490562'::timestamp without time zone)\n  Filter: ((domain)::text = 'test'::text)
```

**Review by millerdev — APPROVED** [review]

**Pull request merged**
