### PR TITLE
start phasing out requisitions

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?164582

just running tests for now - lots more to do here.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 433 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 433 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 433 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 434 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 434 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 434 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/commtrack/exceptions.py, line 27 - W391 blank line at end of file
* corehq/apps/commtrack/sms.py, line 434 - F841 local variable 'there' is assigned to but never used
* custom/requisitions/utils.py, line 36 - E501 line too long (143 > 115 characters)
* custom/requisitions/utils.py, line 37 - E501 line too long (162 > 115 characters)
* custom/requisitions/utils.py, line 38 - E501 line too long (154 > 115 characters)

**Comment by dannyroberts** [comment]
(wasn't mergeable so i just rebased onto master)

**Comment by dannyroberts** [comment]
@czue would love to merge this code—since it touches a few places, I'm working off of it for some cleanup. What's left to get it in?

**Comment by dannyroberts** [comment]
(tests passed, phantom post-test fail)

**Comment by czue** [comment]
I think fine to merge if tests are passing. Just more to do on top of it

**Comment by dannyroberts** [comment]
Ok great. I'm merging then

**Comment by dannyroberts** [comment]
This PR unlocked some pretty good cleanup here: https://github.com/dimagi/commcare-hq/pull/7438

**Pull request merged**
