### PR TITLE
restore rawes version

### PR DESCRIPTION
**Pull request by czue**
depends on https://github.com/dimagi/pillowtop/pull/182

@snopoke @emord @esoergel

### CODE REVIEW

**Comment by snopoke** [comment]
Do we need to add exception handling or anything to the HEAD request in `assume_alias`

**Comment by czue** [comment]
oh good call, forgot about the other trace (this was the only one i got locally). will look

**Comment by czue** [comment]
also needs https://github.com/dimagi/pillowtop/pull/183/ (can just wait till both are merged for this)

**Comment by czue** [comment]
submodule update now includes both PRs (can wait for build if we want)

**Pull request merged**
