### PR TITLE
Update to django-angular==0.8.6 including rename to djng

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
This is a prerequisite for the Django upgrade. I think the incompatibilities with Django 2.2.11 are very minor and could if absolutely necessary be handled by forking it and patching just what needs to be updated ourselves, but that seems like throwaway work that's not worth it.

This PR itself won't get us to Django 2.2.11 compatibility with django-angular, but is a stepping stone. The latest version is 2.2.0, and the first Django 2–compatible version is [2.0.1](https://django-angular.readthedocs.io/en/latest/changelog.html#id6) but I wanted to first do this big rote renaming change on a version with minimal differences, before then
trying to sift through any other incompatibilities with the big version
jump.

I'll be sure to QA this on staging before assuming it works after travis tests pass

### CODE REVIEW

**Comment by czue** [comment]
Do you know how/whether this affects ICDS Dashboard? I think not based on it only being referenced in the `mocha.html` file, but just wanted to confirm.

**Comment by dannyroberts** [comment]
@czue That was on my mind, thanks for raising. If ICDS is willing to run a test and come back with any issues, I'm happy to wait for you to do that, just let me know how you want to do that

**Review by millerdev — APPROVED** [review]

**Comment by czue** [comment]
> If ICDS is willing to run a test and come back with any issues, I'm happy to wait for you to do that, just let me know how you want to do it

Sure. I propose:

1. Someone runs a test of dashboard locally before we merge.
2. We make sure to merge/deploy India and do a second sanity test there before deploying to TCL

For 1) I'm happy to do that. Can you tell me the set of steps I should follow after checking out your branch to ensure I have everything updated? Obviously pip install, but is there any front-end bower stuff that I also need to run?

For 2 it might make sense to coordinate with @orangejenny (who usually handles deploys) and the QA-team directly.

**Comment by dannyroberts** [comment]
@czue Sounds like a good plan. This shouldn't change any front-end stuff except for the `django-angular.js` file that is apparently only loaded in the icds mocha spec, and that too is packaged with the `django-angular` pip package, so there's no separate step there.

So yeah to update your local environment to test things, checking out the branch and running `pip install -r requirements/requirements.txt` should be all that's needed.

As a side note, I previously thought that the landing page "dashboard" (the one that's just a big nav page to Applications, Reports, etc.) also used it, but it must have been rewritten a while ago not to use angular. As far as I can tell ICDS and maybe one other custom report is the only thing using angular.js (most of the changes in this PR are from places that use utils from django-angular without actually using angular as far as I can tell).

**Comment by orangejenny** [comment]
> As far as I can tell ICDS and maybe one other custom report is the only thing using angular.js (most of the changes in this PR are from places that use utils from django-angular without actually using angular as far as I can tell).

Confirming the ICDS dashboard should be the only place using angular js. What's the other custom report you're thinking of?

I think it's confusing that we use djangular in places that don't actually use AngularJS. I've thought about removing it in the past but couldn't justify it with anything more concrete than "it would be less weird."

And yeah, feel free to ping me to coordinate deploys for this.

**Comment by dannyroberts** [comment]
Thanks @orangejenny, that's validating. Thanks both of you for volunteering a little time on this effort! See you on slack

**Comment by czue** [comment]
@dannyroberts conducted local testing on dashboard and mobile dashboard and all looks clear.

**Review by czue — APPROVED** [review]

**Comment by dannyroberts** [comment]
Thanks @czue! I'll coordinate offline with you @orangejenny and QA about rollout + testing on india

**Comment by dannyroberts** [comment]
From @Ben-Talbot:
> https://dimagi-dev.atlassian.net/browse/QA-1100
> Green light!
> She did a UI pass on every main page, everything loaded fine and data appeared as expected. I also asked her to generate data and ensure it appears on the dashboard as expected
> "I have completed the checklist and verified data is updating on Dashboard too."

**Pull request merged**
