### PR TITLE
Add TOC to UCR Readme

### PR DESCRIPTION
**Pull request by proteusvacuum**
@benrudolph @sravfeyn

### CODE REVIEW

**Comment by proteusvacuum** [comment]
(killed travis)

**Comment by benrudolph** [comment]
:clap: :clap:

**Comment by snopoke** [comment]
wow, I hope there's an automated way of doing that....

**Comment by proteusvacuum** [comment]
Hah! Yes. I used https://github.com/ardumont/markdown-toc, which worked
perfectly. I'm sure other text editors have similar functionality. On
Thursday, June 30, 2016, Simon Kelly <notifications@github.com> wrote:
> wow, I hope there's an automated way of doing that....
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/pQnCiBqbsHABW2Q-Rrc9iJenysCt7iSAD0-XhTeqvnQrgwtN-tP63JqXdSu-O3lJhx5ypDE8-D1dJrQm9N5udt0jcwiocjf2j-b-vMtJ4y4qPqRQ8brSogwvrvSZ3X1txCUpz2ScNaN5Mt-vBiGdtWe1zm_f-A=s0-d-e1-ft#https://github.com/notifications/beacon/AAI90HeLJQ8SaUf-Av25QhCRyBMQCT-Mks5qQ3VCgaJpZM4JBf8N.gif
>

**Comment by czue** [comment]
amazing. thanks!

**Pull request merged**
