### PR TITLE
Remove fab

### PR DESCRIPTION
**Pull request by dannyroberts**
~Only merge _after_ https://github.com/dimagi/commcarehq-ansible/pull/1179~

This is Part Two of https://github.com/dimagi/commcarehq-ansible/pull/1179, and removes the commcare-hq-deploy submodule from commcare-hq, as it now lives under commcarehq-ansible/fab as part of that repo (and not as a submodule).

Before merging this PR, merge:
- https://github.com/dimagi/commcarehq-ansible/pull/1204 (improve check_install.sh output)

Right after merging this PR, merge:
- https://github.com/dimagi/commcare-hq-deploy/pull/489 (Deprecate commcare-hq-deploy repo)

### CODE REVIEW

**Comment by dannyroberts** [comment]
@dimagi/team-commcare-hq For the next couple weeks, I'd recommend running any fab commands from the respective control machine rather than from your laptop. If you do make a change to the `commcare-hq-deploy` submodule (which I deem unlikely over the holidays), make sure to merge it back into commcarehq-ansible with

```
commcarehq-ansible$ git remote add -f commcare-hq-deploy https://github.com/dimagi/commcare-hq-deploy.git
commcarehq-ansible$ git fetch
commcarehq-ansible$ git merge commcare-hq-deploy/master
```

**Comment by dannyroberts** [comment]
Looks like we're already merging things into commcarehq-ansible without merging into the commcare-hq-deploy repo, and I've had a number of people confirm the new setup works for them.

I think it's time to go ahead and merge this so people can follow these instructions for getting themselves set up, and that should also avoid any issues that come from a diverging commcare-hq-deploy repo in this interim.

**Comment by dannyroberts** [comment]
See also https://github.com/dimagi/commcarehq-ansible/pull/1204, responding to feedback from when I test-ran these instructions with @esoergel

**Review by czue — APPROVED** [review]
love all this self-documenting stuff you're doing. :clap:

**Comment by dannyroberts** [comment]
I'm not actually in today, but I figured if people are working today, having this merged is less likely to cause trouble than not having this merged and risking a diverging commcare-hq-deploy. Just as likely no one will try to deploy today in which case this doesn't really make any difference.

**Pull request merged**
