### PR TITLE
[ICDS Dashboard]removed present month from the months filter

### PR DESCRIPTION
**Pull request by challabeehyv**
##### SUMMARY
removed present month from the months filter

##### FEATURE FLAG
No

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
This should only be for the performance (incentive) report. Other reports should be available in the current month

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
@challabeehyv  along with What Cal said. Test case failure looks related. Please fix that also.

**Review by calellowitz — APPROVED** [review]
It looks like you are removing the part of the code that ensures you are only able to download last month's report after the 15th. You will need to fix that immediately so we can get make sure it is deployed before the end of the month. The correct logic is to allow last month's report if after the 15th or two months ago's report if before the 15th.

**Comment by calellowitz** [comment]
Merging with the caveat that a fuller fix needs to be picked up tomorrow, in order to get this part of the fix out today

**Pull request merged**
