### PR TITLE
Disable intermittently failing aaa mocha test pregnant_women.spec.js

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
to be added back when fixed.

I think it's considered fair game in our new structure to push failures like this onto the team that cares about them if it's affecting the general open source project, to decide whether they're important enough to fix / make not brittle. Let me know if you disagree!

The failure looks like
```
 Pregnant women models
  1) "after each" hook
    Pregnant women config model
  37 passing (425ms)
  1 failing
  1) Person models "after each" hook:
     Uncaught Error: URL 'unified_beneficiary_details' not found in registry (http://localhost:8000/static/hqwebapp/js/initial_page_data.js:94)
  
>> 1/38 tests failed (0.42s)
Warning: Task "mocha:aaa" failed. Use --force to continue.
```
and frequently requires me to restart the js tests job on PRs.

### CODE REVIEW

**Review by emord — APPROVED** [review]
> fair game in our new structure to push failures like this onto the team that cares about them if

A+ totally agree. I think the issue is that no one on tech cares about them, but BD does. it does seem way better to not have them (I would maybe even suggest killing all the tests)

I've been meaning to document the reason this is even still in the codebase. will do my own pr to do that

**Comment by dannyroberts** [comment]
Oh, okay it sounds like it's more nuanced than I thought (I thought these were just ICDS tests, I don't actually know what aaa is or what these tests test). Could you ping me on your documentation PR? I'll wait for it as that'll probably answer any questions I have without me having to figure out how to ask them.

**Comment by dannyroberts** [comment]
I guess it wasn't just that one test. The same error on a different test
```
  1) Eligible Couple models "after each" hook:
     Uncaught Error: URL 'unified_beneficiary_details' not found in registry (http://localhost:8000/static/hqwebapp/js/initial_page_data.js:94)
```

**Comment by dannyroberts** [comment]
Reaching out to you @snopoke to get your signoff. If it passes before you have a chance, I'll probably merge it with the understanding that you'll revert it with a low bar

**Review by snopoke — APPROVED** [review]

**Pull request merged**
