### PR TITLE
Added information about when charts can be rendered in Report Builder

### PR DESCRIPTION
**Pull request by AmitPhulera**
https://dimagi-dev.atlassian.net/browse/SAAS-10739
##### SUMMARY

When the user clicks on the "Add Chart" button in Report Builder, then feedback is added notifying the conditions when the chart cannot be displayed.

## Case 1
 - Chart generated will have default feedback about which columns will be displayed in the chart.
chart_displayed

##  Case 2
- When there is no column which is eligible to be displayed in the chart, then feedback will be given why the chart is not rendered properly
chart_not_displayed

## Case 3
- The warning disappears when the user removes the chart from the report
No chart

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
This is a nice first pass, but I think I'd change the approach, and I'll try to describe why.

The way it's implemented here, the showing of the message is tied directly to the action of clicking the button (assuming that's the only thing that calls `addChart`). That means for reports already configured, there's no indication to the user as to why they can't get a (non-Sum/Average) column to show up. Conversely, when you add a bar chart and remove it, the message doesn't go away. This second thing is easily fixable without changing the approach, but I'll suggest the following as a new approach that will handle both of these use cases.

Instead of the message being tied to the click action, I'd suggest we tie it to the page _state_ (`self.selectedChart() == 'bar'`) in the template, and to have different messages when `self.areColumnsValidForChart()` is true and when it's false. (And to have no message when `self.selectedChart() != 'bar'`.)

If `self.selectedChart() == 'bar' && self.areColumnsValidForChart()` then I'd suggest the message

> Only properties with FORMAT <strong>Sum</strong> and <strong>Average</strong> will show up in this bar chart.

which is pretty similar to what you have here.

If `self.selectedChart() == 'bar' && !self.areColumnsValidForChart()` then I'd suggest the message

> This bar chart below will not be shown in the report because it is not configured to show any data. To show the bar chart, please add at least one property with FORMAT <strong>Sum</strong> or <strong>Average</strong>.

I think this will also make the code easier to reason with, as whether it shows up or not isn't based so much on click history, but on the same state variables that the rest of the page is based on.

**Comment by AmitPhulera** [comment]
Thanks for the review.
I like the idea of binding the feedbacks to `self.selectedChart()== 'bar'`. I can see it would make more sense to do it this way. 
I was also thinking of having different feedbacks for different cases, but was not sure whether it would be the best approach. 
I will make the changes and let you know.
Thanks.

**Comment by AmitPhulera** [comment]
Hey @dannyroberts,
I have made the changes that you suggested and have updated the description with the new screenshots.
Thanks.

**Comment by dannyroberts** [comment]
Nice. Do the warning messages show up on the actual report page as well, or just the preview of it when you're editing the report config? (We want it to only show up when editing.)

**Comment by AmitPhulera** [comment]
No. They don't show up on actual page, only while creating/editing a report.

**Review by dannyroberts — APPROVED** [review]
This passed QA and is ready for us to merge on Monday!

**Pull request merged**
