### PR TITLE
use form received_on as ledger modified date

### PR DESCRIPTION
**Pull request by snopoke**
@dannyroberts @czue 

I think this is all that needs changing. Should the consumption calculations also use the server dates i.e. for selecting which transactions are in the window?

### CODE REVIEW

**Comment by czue** [comment]
build fails look real:
```
======================================================================
ERROR: test_report_with_exclude_disabled (casexml.apps.stock.tests.test_logistics_consumption.LogisticsConsumptionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "corehq/ex-submodules/casexml/apps/stock/tests/test_logistics_consumption.py", line 95, in test_report_with_exclude_disabled
    self.create_transactions(self.domain.name)
  File "corehq/ex-submodules/casexml/apps/stock/tests/test_logistics_consumption.py", line 50, in create_transactions
    txn.save()
  File "corehq/ex-submodules/casexml/apps/stock/models.py", line 77, in save
    force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/vendor/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "corehq/ex-submodules/casexml/apps/stock/signals.py", line 19, in stock_transaction_post_save_signal_receiver
    update_stock_state_for_transaction(instance)
  File "corehq/ex-submodules/casexml/apps/stock/signals.py", line 133, in update_stock_state_for_transaction
    state.save()
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/vendor/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/vendor/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/vendor/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "last_modified_date" violates not-null constraint
DETAIL:  Failing row contains (9, stock, eaa09883c52d497190376fc0420b0e7e, 7ba81b01fbb04a319746b7cead4df8f4, 10.00000, null, null, null, 13, 484ef00d5e614eb8b0f97d558b540a80).
----------------------------------------------------------------------
```
and similar

**Comment by czue** [comment]
> Should the consumption calculations also use the server dates i.e. for selecting which transactions are in the window?

My guess is yes, but I think I need to think through a bit more so maybe let's not make that change yet but can put in a backlog?

**Comment by snopoke** [comment]
Added here: https://docs.google.com/document/d/1XX_WCEf8ozxt7cJoigu3R03W9vPqY45P7vFFY3stVO4/edit?pli=1#

**Comment by czue** [comment]
:+1: thanks. this looks good - kicked build

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
