### PR TITLE
Fix calendar appearing on clicking help text

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Summary

Fixes an issue coming in webapps where when we click on help text the calendar used to appear as well.
https://dimagi-dev.atlassian.net/browse/SAAS-11570
## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

It is a small JS change and has been tested on local and staging envs and no issues were observed in the testing.
### Safety story

Changes have been tested on local and on staging, [Link to staging](https://staging.commcarehq.org/a/ap-test-project/cloudcare/apps/v2/#%7B%22appId%22%3A%227b71a2a377124be8bc8389a4656f0ca5%22%2C%22copyOf%22%3A%2270920c6ee9136f4fc99dd5ca57f5cfe9%22%2C%22steps%22%3A%5B0%2C0%5D%2C%22page%22%3Anull%2C%22search%22%3Anull%7D)
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Is it possible that making this changes means that [this span](https://github.com/dimagi/commcare-hq/blob/cc2e746911411279f6c642be71bc90ce2968a514/corehq/apps/cloudcare/templates/form_entry/templates.html#L142-L145) could be a button? Seems like this might prevent the auto-clicking action described in that comment.

**Comment by AmitPhulera** [comment]
Hey @orangejenny,

I just tested it out on local and updated
```
<span class="btn btn-default help-modal-close" data-dismiss="modal">{% trans "Close" %}</span>
```
 with
```
<button class="btn btn-default help-modal-close" data-dismiss="modal">{% trans "Close" %}</button>
```
The modal was not closing automatically irrespective of the changes I have made in this PR. Maybe updating the libraries might have resolved the issue that was observed before. 
Should I go ahead and make it a `button` instead of `span`?

**Comment by orangejenny** [comment]
@AmitPhulera Huh, indeed, maybe a library update changed the behavior. Yes, please do change it now that it works with a button. Thank you for testing that out.

**Comment by AmitPhulera** [comment]
Done 👍

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
