### PR TITLE
check formplayer service

### PR DESCRIPTION
**Pull request by benrudolph**
@esoergel @wpride checks to ensure formplayer is up. label is on so we wait for the serverup check in formplayer to be merged

### CODE REVIEW

**Comment by esoergel** [comment]
Nice!  gtm on build and whenever you're ready.

**Comment by benrudolph** [comment]
g2g

**Comment by benrudolph** [comment]
ah wait don't think this'll work on production since FORMPLAYER_URL doesn't specify the entire url

**Comment by esoergel** [comment]
:white_check_mark: on :construction_worker:

**Comment by esoergel** [comment]
Still want that `Open for review: hold off on merge`?

**Comment by benrudolph** [comment]
nope g2g

**Pull request merged**
