### PR TITLE
dump mm docs

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
Add back couch view and code required to dump MM docs for a domain.

Still need to export blob data. Will submit a separate PR for that.

### CODE REVIEW

**Comment by millerdev** [comment]
This looks like it reverts things done in https://github.com/dimagi/commcare-hq/pull/26006 (fyi @orangejenny)

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
@millerdev Thanks for flagging. Ethan did bring this up with me, it was a mistake that I removed this - https://github.com/dimagi/commcare-hq/pull/26006#discussion_r414806854

@snopoke Thank you for taking this.

**Comment by dannyroberts** [comment]
@snopoke I noticed this was very slow to reindex on staging. On production we'll probably want to trigger the reindex separately before deploy later today. Mind pinging me directly on PR's with a reindex in the future, since there's usually then something we have to think about on SaaS envs?

**Comment by snopoke** [comment]
@dannyroberts I meant to comment earlier - I've already run the preindex on `india` and it's currently running on `production` (past 3 hours). Apologies for merging before the preindex was done.

**Comment by dannyroberts** [comment]
Okay no worries, just wanted to make sure the protocol was clear for the future, but it sounds like just a simple oversight/mixup

**Pull request merged**
