### PR TITLE
Extract DateTime logic

### PR DESCRIPTION
**Pull request by mjriley**
## Product Description
Purely a backend change.

## Technical Summary
The recent CommCare Version Tile made me aware that we're inconsistent in how we're treating deserialization. The full logic is in `DateTimeProperty._wrap()`, but because it is an instance method, we ended up doing our own manual deserialization with `datetime.strptime(date_of_use, ISO_DATETIME_FORMAT)`. Although this works, it ignores the additional checks that `DateTimeProperty` does. Since, in both cases, we're handling data from the same source (data that was serialized by `DateTimeProperty`), I've added a class method to allow us to re-use the same logic.

### Safety story
I haven't done any testing beyond the unit tests, but I believe those tests are sufficient to prove that the existing behavior has been preserved.

### Automated test coverage

Added new tests to verify that the existing behavior has not been disrupted while adding the `deserialize` method.

### QA Plan
No  QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by jingcheng16** [comment]
>data that was serialized by DateTimeProperty

Can you show where is `last_submission.date_of_use` and `last_device.date_of_use` being serialized?

**Comment by mjriley** [comment]
> Can you show where is `last_submission.date_of_use` and `last_device.date_of_use` being serialized?

I haven't traced through this, but my understanding is that somewhere along either the Pillow or Couch process, Document models are converted to JSON using the field definitions from jsonobject. Jsonobject serializes and deserializes via its `wrap` and `unwrap` methods

**Comment by jingcheng16** [comment]
@mjriley Without confirming we did `_unwrap` the `DateTimeProperty`, I'm not very confident to approve the PR. I searched `_unwrap` in commcare-hq and cannot find any reference.
@dannyroberts @millerdev (Tagging people who might more familiar with Couch. )

**Review by millerdev — APPROVED** [review]

**Comment by jingcheng16** [comment]
One question ( no need to address it in your PR ):
Can we say all occurrences of `datetime.strptime(date_of_use, ISO_DATETIME_FORMAT)` can be replace with your new deserialize function now?

**Comment by mjriley** [comment]
> @mjriley Without confirming we did `_unwrap` the `DateTimeProperty`, I'm not very confident to approve the PR. I searched `_unwrap` in commcare-hq and cannot find any reference. @dannyroberts @millerdev (Tagging people who might more familiar with Couch. )

@esoergel was kind enough to point me to the code (mostly) responsible for this.

The code that inserts it into ElasticSearch is [here](https://github.com/dimagi/commcare-hq/blob/7aac52fe46bf71ba5f79d3726c8121061b947f86/corehq/apps/es/users.py#L88-L93). which you can see from the method's docstring:
> Takes a user dict and applies required transfomation to make it suitable for ES.
        :param user: an instance ``dict`` which is result of ``CouchUser.to_json()``

The parent class has that `to_json` call [here](https://github.com/dimagi/commcare-hq/blob/7aac52fe46bf71ba5f79d3726c8121061b947f86/corehq/apps/es/client.py#L528-L549), where, because `ElasticUser`'s `model_cls` is `CouchUser`, we'll be calling `to_json` on a `CouchUser` object.

At that point, the details of how `to_json` ends upcalling `unwrap` is within Couch's `Document` class and JSONobject.

**Comment by mjriley** [comment]
> One question ( no need to address it in your PR ): Can we say all occurrences of `datetime.strptime(date_of_use, ISO_DATETIME_FORMAT)` can be replaced with your new deserialize function now?

Provided these calls represented data that was serialized by `DateTimeProperty`, yes.

**Review by jingcheng16 — APPROVED** [review]
Nice! Thank you for the explanation I also learned something new from it.

**Pull request merged**
