### PR TITLE
Revert "Bump flake8 from 3.8.4 to 3.9.1 in /requirements"

### PR DESCRIPTION
**Pull request by gherceg**
Reverts dimagi/commcare-hq#29590

Reverting due to a `ModuleNotFoundError: No module named 'flake8_polyfill'` error when using the 3.9.1 version of flake8. The temporary fix appeared to be installing `flake8_polyflil`, but I'd like to understand why this isn't marked as a dependency of flake8 if it is needed. 

Worth noting after installing `flake8_polyfill` there is an additional dependency for `flake8` - `radon: 4.5.0`

### CODE REVIEW

**Review by joxl — APPROVED** [review]

**Review by millerdev — APPROVED** [review]
Can you add a note about why you're reverting this? The new versions appear to be working for me locally.

**Comment by joxl** [comment]
> The new versions appear to be working for me locally.

It is? What flake dependencies do you have?

```bash
$ pip freeze | grep flake8
flake8==3.9.1
```

**Comment by joxl** [comment]
> Can you add a note about why you're reverting this?

On Linux, the upgrade causes `flake8` to bomb:

```bash
$ flake8 --version
Traceback (most recent call last):

<snip>

flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "R70" due to No module named 'flake8_polyfill'.
```

**Comment by millerdev** [comment]
```
$ pip freeze | grep flake8
flake8==3.9.1

$ flake8 --version
3.9.1 (mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.7.7 on
Linux
```

**Comment by gherceg** [comment]
Confirmed this was an issue on python 3.7 too btw.

**Comment by gherceg** [comment]
Joel figured out this is attributed to radon, not the flake8 upgrade so this revert is not necessary.

**Pull request closed without merging**
