### PR TITLE
delete groupexport/by_domain view

### PR DESCRIPTION
**Pull request by nickpell**
Requires https://github.com/dimagi/commcare-hq/pull/9293

@dannyroberts cc: @NoahCarnahan

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
(note to self: this *is* the main db, but no reindex because it's deleting the entire design doc)

**Comment by nickpell** [comment]
seems like a safe idea to wait until https://github.com/dimagi/commcare-hq/pull/9293 is deployed and no issues are reported before removing this design doc from the main db

**Comment by dannyroberts** [comment]
ok, sure. We do have to manually run `prune_couch_views` in order to actually delete the view, but I suppose someone could run that immediately and blow away the index and then we find there's some bug. Definitely being overly cautious, but I'm fine holding off on a merge

**Comment by nickpell** [comment]
no bugs reported so far; removed "hold off on merge"

**Comment by dannyroberts** [comment]
:tada:

**Comment by czue** [comment]
woop!

**Pull request merged**
