### PR TITLE
bump toggle

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @wpride graphs on prod still looking pretty

cc: @emord

### CODE REVIEW

**Comment by czue** [comment]
woop woop!

**Review by czue — APPROVED** [review]

**Comment by wpride** [comment]
Now we're cooking with gas!

**Comment by esoergel** [comment]
:hocho: :construction:

**Comment by esoergel** [comment]
Surprisingly enough, the build DID actually fail on this - the predictably random toggle now enables cloudcare for some test cases where it shouldn't.   @calellowitz is fixing.

**Comment by calellowitz** [comment]
😢

**Pull request merged**
