### PR TITLE
Accessibility: Add label for tabular checkboxes in apps

### PR DESCRIPTION
**Pull request by akashkj**
## Product Description
For options in a tabular checkbox formatting, screen reader is not reading the values of options.
image

## Technical Summary
https://dimagi-dev.atlassian.net/browse/USH-1508

For check boxes, screen reader is using value from `span` element and not from `value` attribute of `input` element. This span is not constructed in case of tabular formatting. Change is made to always create the `span` node and set class to `sr-only` when label is intended to be hidden for tabular formatting.

HTML for a formatted checkbox currently:
image

HTML for a formatted checkbox with fix: 
image

## Feature Flag
NA

### Safety story
Locally tested using Linux's screen reader
Before fix:
https://user-images.githubusercontent.com/14318173/215317969-c291115e-e19b-4ef9-814a-47da29e2b671.mp4

After fix:
https://user-images.githubusercontent.com/14318173/215317978-f1cad1aa-1322-434c-9293-6d5f82b59224.mp4

### Automated test coverage
NA

### QA Plan
https://dimagi-dev.atlassian.net/browse/QA-4761

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
Thanks @akashkj 
Looks great. Good to merge post a :+1: from @orangejenny or anyone from USH team

**Comment by mkangia** [comment]
And successful test run!

**Comment by orangejenny** [comment]
Nice - deferring to @stephherbers or @Robert-Costello for USH signoff.

**Review by stephherbers — APPROVED** [review]
Looks great-- thanks for including the screen recordings (sometimes it's hard to get the audio of the actual screen reader included so-- amazing). Just confirm tests

**Pull request merged**
