### PR TITLE
Web Apps collapsible groups

### PR DESCRIPTION
**Pull request by orangejenny**
##### SUMMARY
https://dimagi-dev.atlassian.net/browse/USH-159

Depends on https://github.com/dimagi/formplayer/pull/760

##### RISK ASSESSMENT / QA PLAN
[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-1896)

##### PRODUCT DESCRIPTION
Adds three appearance attributes:
* `group-collapse` indicates that a group should use the new collapsible styling
* `collapse-closed` means the group will be collapsed when the page loads
* `collapse-open` means the group will be open when the page loads

Appearance attributes are space-separated, so an open group should have the appearance attribute `group-collapse collapse-open`. If the group doesn't specify open/closed, it will default to closed.

Collapsible groups are displayed in panels, with an angled icon, and clicking the panel header will show or hide the questions in the group. Groups without a label still show the icon and header.

These attributes only apply in web apps and only apply to groups - not question lists, and not repeat groups. You can make collapsible question lists / repeat groups by putting a collapsible group inside the question list / repeat group (see below). @ctsims is the most likely person to have an opinion on the appearance attribute config.

Markdown does not work for collapsible group labels. Form builder will show you markdown, but in web apps, it will not be rendered.

Screen Shot 2020-09-15 at 11 24 37 AM

In app preview, with one question per screen turned off, the collapsibility works:
Screen Shot 2020-09-08 at 9 40 35 AM

With one questions per screen turned on, there's no icon and no collapsibility:
Screen Shot 2020-09-08 at 9 41 35 AM

When a collapsed group is **closed** and contains required questions, the header displays an asterisk. Similarly, if it contains questions with failed validation, the header shows a warning icon:

Screen Shot 2020-09-15 at 11 25 44 AM

### CODE REVIEW

**Review by stephherbers — APPROVED** [review]
This is an awesome feature-- maybe a border box would help with the alignment of a groups without a label, but also it still feels intuitive without one

**Comment by ctsims** [comment]
> This is an awesome feature-- maybe a border box would help with the alignment of a groups without a label, but also it still feels intuitive without one

Totally agreed that it would be useful to group visibly somehow, it's a bit hard to visually differentiate the accordion style view

**Review by ctsims — APPROVED** [review]
Very cool that this was possible with so little code.

One nitpick: Since we are moving towards a "tag" style system for attributes, my bias would be for the "Default open" or "Default close" behavior to be a second tag, since that would permit a future where if there were three modifiers instead of two, we would only need five tags  (`collapsable`, `col-default-open`, `col-default-closed`, `col-something-state1`, `col-something-state2`) to support the 9 states instead of fully unrolling to need all 9 (`collapsable-open-state1`...

**Comment by orangejenny** [comment]
@ctsims 387bf1389c2 updates the attributes so there's one to indicate collapsibility and an optional second one to indicate the default state.

@stephherbers @ctsims There's discussion going on in the ticket about possible different UI treatments, feel free to read/comment. I just added a commit to add panel styles, not sure yet if it will be the final UI:
Screen Shot 2020-09-14 at 4 13 51 PM

**Review by ctsims — APPROVED** [review]
Awesome, thanks for the update!

**Comment by orangejenny** [comment]
Added a few commits to update the UI, changing the icon and adding an asterisk for collapsed groups that contain required questions. Updated PR description to reflect changes. @stephherbers could you read through the recent commits?

**Comment by orangejenny** [comment]
FYI @dimagi/product this will make minor UI changes to web apps: changes the error icon from an X to a triangle with exclamation point, and shifts the asterisk for required questions from the right to the left. @djmore9 @biyeun and I have offlined about this.

**Review by stephherbers — COMMENTED** [review]
Looked over the updates you made-- looks good to me. The UI improvements look fantastic

**Review by biyeun — APPROVED** [review]

**Comment by orangejenny** [comment]
Added a commit to indent all of `fullform-ui.js`. It's a little weird, but it should reduce the conflicts between this branch and https://github.com/dimagi/commcare-hq/pull/28530

Ignoring Stickler.

**Comment by orangejenny** [comment]
> Added a commit to indent all of fullform-ui.js. It's a little weird, but it should reduce the conflicts between this branch and #28530

This ended up making the conflicts dramatically worse. Rebased and removed that commit. No need for re-review.

**Pull request merged**
