### PR TITLE
update to use checkpoint instead of checkpoint_manager

### PR DESCRIPTION
**Pull request by czue**
goes with https://github.com/dimagi/pillowtop/pull/154

### CODE REVIEW

**Comment by czue** [comment]
wait for tests

**Comment by dannyroberts** [comment]
not mergeable

**Comment by dannyroberts** [comment]
(and https://github.com/dimagi/pillowtop/pull/154 just got merged, so may need to warn people not to update the submodule or settle quickly.)

**Comment by czue** [comment]
I'll fix as soon as tests finish running. Assuming you'll be cool if we don't wait after merge.

**Comment by dannyroberts** [comment]
Yeah sounds good

**Comment by czue** [comment]
:white_check_mark: and mergeable

**Comment by czue** [comment]
:tada: :smile_cat:

**Pull request merged**
