### PR TITLE
Improve fragile logic in pillowtop `build_bulk_payload()` utility

### PR DESCRIPTION
**Pull request by joxl**
## Technical Summary

Identified through [code review](https://github.com/dimagi/commcare-hq/pull/31125#discussion_r824204860) of #31125

The existing function is missing an `else` clause. If the `else` condition were to ever happen, it would result in an Elastic bulk `insert` action with an "empty" payload. The result of this action would definitely not be desirable.

### Safety story

The existing functionality is fragile at best and buggy at worst. This makes it less of both.

It is possible that the (missing) `else` clause was never actually hit -- that is, the existing logic was actually somehow always working as designed, narrowly avoiding falling off the proverbial cliff. If that is the case, then this change is an effective no-op, making it safe.

### Automated test coverage

Test added to verify the bug.

### QA Plan

No QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Wow, there are a lot of unaccounted for edge cases:

* `is_deleted` also has no `else` clause
* `is_deleted` could return False even if `change.deleted` is True
* `get_doc_meta_object_from_document` could return `None` which would raise an `AttribueError` (though in this instance it won't because it's guarded by the `if`)

Given what I know about where this code is called and how we produce `Change` objects I think it is OK though I feel a bit icky saying that and wouldn't be averse to raising an exception in the `else` if `change.get_document` returned `None` (though I think it's likely that `doc_transform` will raise some kind of error if `doc` is `None`) or the doc didn't have a valid `_id`.

**Comment by calellowitz** [comment]
> The result of this action would definitely not be desirable.

Can you expand a bit more on this? What would the result of this action be?

**Comment by calellowitz** [comment]
> Wow, there are a lot of unaccounted for edge cases:

I can speak to some of these edge cases

> * `is_deleted` also has no `else` clause

This should probably have `return False` at the end, although if it doesn't return `True`, it ends up equivalent to returning `False`, so while we should definitely fix that, I don't think it will cause any bugs.

> * `is_deleted` could return False even if `change.deleted` is True

This is intentional, if poorly commented. Specifically if the doc has been undeleted since the change was created, this prevents us from deleting the doc. This is especially important in light of pillow retries that can cause changes to be processed out of order, the undelete being processed before the delete, which has caused missing ES docs in the past.

> Given what I know about where this code is called and how we produce `Change` objects I think it is OK though I feel a bit icky saying that and wouldn't be averse to raising an exception in the `else` if `change.get_document` returned `None` (though I think it's likely that `doc_transform` will raise some kind of error if `doc` is `None`) or the doc didn't have a valid `_id`.

I think `change.get_document` will always return `None` if it has been hard deleted (such as following a domain deletion request), and we would want to delete that from ES rather than raise an exception.

**Comment by calellowitz** [comment]
> > Can you expand a bit more on this? What would the result of this action be?
> 
> Sorry, I left this out because I covered it in my comment on the other PR. I was implying [this explanation](https://github.com/dimagi/commcare-hq/pull/31125#discussion_r825195137):
> 
> > ... an action lacking the `_op_type` key defaults to an `index` action. This means that the above, sparse bulk action item will always perform an `index` action for document `_id = change.id`. This will do one of:
> > 
> > 1. index a new, empty (i.e. `_source = {}`) document which may or may not be using a valid `_id`, or
> > 2. clear all properties on an existing document with that `_id`.

Thanks! That makes a lot of sense and definitely does not sound what we want. I am curious if the correct course of action here may actually be to no-op, adding
```
else:
    continue
```
rather than changing the `elif` and indexing a doc when the kafka change is marked `deleted`. I think this can only happen in the specific race condition described above, when a doc is deleted, then undeleted and the deletion is processed by the pillow after the doc has been restored, but more generally it feels wrong to update a doc when the change is marked as a deletion, even if we no longer want to delete the doc.

**Comment by calellowitz** [comment]
Curious also if @snopoke has opinions on which of those two behaviors is preferable. I don't think there is harm in indexing in this case, but when faced with this contradiction `_is_deleted == False and changed.deleted == True`, passing seems safest. The restore action will trigger its own kafka change to reindex the doc.

**Comment by joxl** [comment]
> when faced with this contradiction `_is_deleted == False and changed.deleted == True`, passing seems safest. The restore action will trigger its own kafka change to reindex the doc.

My gut says "I want to _know_ that that is the case before I discard a change", but I don't know how it's possible to know that (without adding new capabilities to the change feed flow).  I'm on board adding an `else: continue` instead of the current change. I'll wait for @snopoke to weigh in with his thoughts before I push that.

**Comment by calellowitz** [comment]
> My gut says "I want to _know_ that that is the case before I discard a change",

That's fair, and a reasonable way to think about it. I think I approached it from the opposite angle, "if the change is marked 'deletion', it violates the principle of least surprise to update the doc". Doing nothing is sort of the awkward middle ground for a weird case where we know that we do not want to do what the kafka message is asking us to do.

**Review by snopoke — APPROVED** [review]
Could do with tests for the other cases (deleted change, deleted change with a doc)

**Comment by joxl** [comment]
> Could do with tests for the other cases

@snopoke you beat me to it (I also forgot to update the existing test, so it would have failed).

**Pull request merged**
