### PR TITLE
Build version removed in App Status Reports

### PR DESCRIPTION
**Pull request by AmitPhulera**
https://dimagi-dev.atlassian.net/browse/ICDS-1052
##### SUMMARY
For ICDS envs, remove Build Version from `Select Application` filter in App Status Reports.

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
Looks good.
I think you can limit this to icds-cas project only too.

**Comment by AmitPhulera** [comment]
Will we not need it in icds-staging or india, don't we test out stuff there?

**Comment by mkangia** [comment]
I think the requirement is only for the icds-cas project from visibility perspective. Can confirm that if needed.

**Review by orangejenny — APPROVED** [review]
Looks good once Manish's feedback is resolved.

**Comment by AmitPhulera** [comment]
Hey @mkangia @orangejenny, 
It would become a bit messy if we try to keep it to icds only as `is_icds_cas_project` https://github.com/dimagi/commcare-hq/blob/master/custom/icds/view_utils.py#L24 expects `domain` parameter which is not available during setting `default_text` property of class. 
https://github.com/dimagi/commcare-hq/pull/27847/files#diff-22509adf8ddc1553878328cc43e82cfdR107  
So I think we should go with the way it is now.

**Comment by mkangia** [comment]
Sounds good to me @AmitPhulera

**Pull request merged**
