### PR TITLE
convert user supporting pillows to be a python pillow

### PR DESCRIPTION
**Pull request by czue**
and misc cleanup. read commit by commit 

the two pillows touched are the one that saves unknown users from xforms and the one that maps users to groups.

@dannyroberts @benrudolph cc @emord

### CODE REVIEW

**Comment by benrudolph** [comment]
lgtm, will let danny respond

**Comment by czue** [comment]
fyi @benrudolph I added some more commits so good for you or @dannyroberts to review those before merging and not just the one i pinged danny on

**Comment by snopoke** [comment]
:white_check_mark: from me but will let @dannyroberts respond to comment before merging

**Comment by czue** [comment]
given @dannyroberts's comment i think this is good to go unless anyone sees any issues

**Pull request merged**
