### PR TITLE
Fix repeater report

### PR DESCRIPTION
**Pull request by benrudolph**
@proteusvacuum this should fix the report to include those records http://manage.dimagi.com/default.asp?249894

cc: @biyeun

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]
Yay.

**Comment by mkangia** [comment]
Thank You @benrudolph

**Comment by benrudolph** [comment]
you are welcome! thank you for reporting

**Comment by biyeun** [comment]
:fire:

**Comment by proteusvacuum** [comment]
(This db took a while to reindex last time, might want to hold off until the weekend)

**Comment by mkangia** [comment]
@benrudolph can we include some timestamp on that key to have some sense of ordering when fetching them for the listing of repeat records?

**Comment by benrudolph** [comment]
hmm yeah, i can revert this and add a timestamp. it sounds like though we might want to take another pass on this report given the amount of work you guys are doing with repeaters

**Comment by mkangia** [comment]
Thanks @benrudolph. 
From what i know we are not modifying anything about how repeaters work but mostly using them and hence notifying any bugs/challenges we find. I think this report is still a good to have and should not wait.
@proteusvacuum?

**Comment by benrudolph** [comment]
(don't think we should wait on this particular change either, just saying
it may help in the long term to take another look at revamping it if you're
going to be doing a lot more repeater work)

**Comment by proteusvacuum** [comment]
Yeah, there's a bunch of things that we should add to this report (e.g. the payload_doc id). I think fine to leave this as-is, and @mkangia and I can work on figuring it out.

**Pull request merged**
