### PR TITLE
fix date comparison

### PR DESCRIPTION
**Pull request by katembu**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by katembu** [comment]
@biyeun

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by biyeun** [comment]
@katembu can you also make this change to the new indicator views? thanks!

**Comment by biyeun** [comment]
(they have been merged into master)

**Comment by katembu** [comment]
@biyeun replacing this one with #5369

**Pull request closed without merging**
