### PR TITLE
link Dockerfile

### PR DESCRIPTION
**Pull request by snopoke**
I'm hoping this will fix the dockerhub build
@benrudolph

### CODE REVIEW

**Comment by snopoke** [comment]
self merging

**Comment by snopoke** [comment]
So far so good: https://hub.docker.com/r/dimagi/commcarehq_base/builds/ba9eslmhjmjjakhtogpdfbc/

**Comment by snopoke** [comment]
Build now working! :rocket:

**Comment by czue** [comment]
:dancers:

**Comment by benrudolph** [comment]
it's :umbrella: :white_check_mark:

**Pull request merged**
