### PR TITLE
ILS: Warehouse runner tweak v2

### PR DESCRIPTION
**Pull request by kkrampa**
@gcapalbo 

I moved updating historical data into smaller facility subtasks.

Please read commit by commit.

Could you just set has_error to False for ilsgateway-test-2 report run. Generating historical data isn't needed for initial report run.

### CODE REVIEW

**Comment by gcapalbo** [comment]
@kkrampa looks good.  i think i just don't understand the process well enough but i'm not sure i understand why generating the historical data isn't needed for the initial run or how the code in this pr is addressing that - can you describe that in a little more detail?

also yes i can make that update - do i need to do that at a specific time or coordinate it with the deploy of this pr?

**Comment by kkrampa** [comment]
Let's consider initial run between 2012-01-01 and 2016-02-15. In this run we are generating data for all months between those two dates. Next run will be between 2016-02-15 and 2016-02-16 and then data  will be generated only for February. So, if there is some location created after initial run we need to fill with zeros data for all previous months all the way to 2012-01-01. I only wonder if we really need to go back and generate that data. I leave this behavior because it's code moved from v1 and I'm not sure about purpose of this.

You can do this at whatever time.

**Comment by gcapalbo** [comment]
got it, understood now thanks

**Comment by gcapalbo** [comment]
also, i just set has_error to False for the ReportRun entry for that domain

**Pull request merged**
