### PR TITLE
fix /builds/edit_menu/ underscore.js import

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@benrudolph looks like this got lost in the shifting; no worries, just wanted you to know in case it rings any other bells

**Comment by benrudolph** [comment]
ah shoot thanks danny. just did another grep and that looks to be the only one for underscore messed up

**Comment by benrudolph** [comment]
(no test coverage)

**Comment by dannyroberts** [comment]
thanks!

**Pull request merged**
