### PR TITLE
Save form before attempting to put_attachment

### PR DESCRIPTION
**Pull request by esoergel**
http://manage.dimagi.com/default.asp?182634

There's a lot of weird interactions happening here - but I think this missing _rev issue is related to a race condition between here and the other handlers of the signal that gets called in the save form process.

I'm not crazy about double-saving the doc, but this is an edge case which shouldn't occur under normal operation.  I'm open to alternate suggestions.

At any rate, this was consistently reproducible locally, and this change fixes it.

@snopoke

### CODE REVIEW

**Comment by czue** [comment]
put a don't merge tag on this. I don't think this is the right place for this and we should not add this to the core form processing workflow just for parct

**Comment by czue** [comment]
@esoergel please assign me the ticket if you don't have any better plan for this

**Comment by czue** [comment]
actually, looking at the surrounding code can you just add a `soft_assert` here to the dev team? then I think this is g2g.

**Comment by esoergel** [comment]
Updated

**Comment by czue** [comment]
thanks! (and sorry for misleading comments)

**Pull request merged**
