### PR TITLE
[ICDS Dashboard] password hash fix in registration page

### PR DESCRIPTION
**Pull request by challabeehyv**
https://app.asana.com/0/1185205808600689/1186445439810551/f

##### SUMMARY
 password hash fix in registration page

##### FEATURE FLAG
No

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Comment by challabeehyv** [comment]
Screenshot from 2020-08-04 22-05-11
without fix

**Comment by challabeehyv** [comment]
Screenshot from 2020-08-04 22-03-25
without fix

**Review by orangejenny — APPROVED** [review]
Initial page data has a `strict` option that's useful for booleans like this, which throws a js error if the key isn't found: https://github.com/dimagi/commcare-hq/blob/104765a7e1be3be5e45f7f157f197e115eb57a66/corehq/apps/hqwebapp/static/hqwebapp/js/initial_page_data.js#L37-L45

It'd be a good addition to supply `strict` in the places where `implement_password_obfuscation` is accessed. Looks like that's `registration/js/new_user.ko`, `nic_compliance/js/encoder`, and `users/js/mobile_workers`.

**Comment by mkangia** [comment]
@challabeehyv 
oops, I thought i had already merged this. please let me know when you have concluded suggestion from Jenny.

**Comment by challabeehyv** [comment]
> @challabeehyv
> oops, I thought i had already merged this. please let me know when you have concluded suggestion from Jenny.

added the changes. please merge

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
@orangejenny , Challa and I offlined that 'use strict' was already present on 2/3 files. So was only added to one more file.

**Comment by orangejenny** [comment]
Hi @challabeehyv , Manish and I just offlined, we were misunderstanding each other. The `use strict` declaration is a javascript language feature. It isn't related to the `strict` initial page data param, which is just a regular variable that happens to be named "strict".

I'm sorry for the back and forth. Could you reapply the changes from https://github.com/dimagi/commcare-hq/pull/28295/commits/aaa8e8ec1ab946ef5f9a6496885ac7b21fb1ff41, please?

**Comment by challabeehyv** [comment]
> Hi @challabeehyv , Manish and I just offlined, we were misunderstanding each other. The `use strict` declaration is a javascript language feature. It isn't related to the `strict` initial page data param, which is just a regular variable that happens to be named "strict".
> 
> I'm sorry for the back and forth. Could you reapply the changes from [aaa8e8e](https://github.com/dimagi/commcare-hq/commit/aaa8e8ec1ab946ef5f9a6496885ac7b21fb1ff41), please?

done.

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
not blocking on the build because this does not really get covered in the test coverage anyway and was tested locally by challa

**Pull request merged**
