### PR TITLE
formplayer deploy instructions in staging.yaml

### PR DESCRIPTION
**Pull request by orangejenny**
fyi @wpride

### CODE REVIEW

**Comment by wpride** [comment]
@orangejenny Curious why `touchforms-src` was deleted as a submodule?

**Comment by orangejenny** [comment]
isn't it deprecated?

**Comment by wpride** [comment]
No, `touchforms-src` still contains a bunch of code for messaging

**Comment by orangejenny** [comment]
good to know. put it back in https://github.com/dimagi/commcare-hq/commit/13f21193e7112e19edda8dc97a54b2a8e03108dd

**Pull request merged**
