### PR TITLE
only fetch one message to popultate highwater

### PR DESCRIPTION
**Pull request by snopoke**
@czue

Consuming the full log can take a long time.
ref: http://stackoverflow.com/a/27060520

### CODE REVIEW

**Comment by czue** [comment]
nice. :+1: on :white_check_mark:

**Comment by czue** [comment]
build fail looks real
```
======================================================================
ERROR: test_process_doc_from_couch (corehq.apps.userreports.tests.test_pillow.IndicatorPillowTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vendor/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/mnt/corehq/apps/userreports/tests/test_pillow.py", line 157, in test_process_doc_from_couch
    self.pillow.process_changes(since=since, forever=False)
  File "corehq/ex-submodules/pillowtop/pillow/interface.py", line 87, in process_changes
    for change in self.get_change_feed().iter_changes(since=since, forever=forever):
  File "/mnt/corehq/apps/change_feed/consumer/feed.py", line 83, in iter_changes
    for message in consumer:
  File "/vendor/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 290, in next
    return six.next(self._get_message_iterator())
  File "/vendor/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 341, in fetch_messages
    fail_on_error=False
  File "/vendor/lib/python2.7/site-packages/kafka/client.py", line 497, in send_fetch_request
    KafkaProtocol.decode_fetch_response)
  File "/vendor/lib/python2.7/site-packages/kafka/client.py", line 179, in _send_broker_aware_request
    correlation_id=requestId, payloads=payloads)
  File "/vendor/lib/python2.7/site-packages/kafka/protocol.py", line 277, in encode_fetch_request
    payload.max_bytes))
error: cannot convert argument to integer
----------------------------------------------------------------------
```

**Comment by snopoke** [comment]
damn, super irritating. Can't figure out why this is failing. Will dig deeper later.

**Comment by snopoke** [comment]
closing in favour of upgrading client https://github.com/dimagi/commcare-hq/pull/12425

**Pull request closed without merging**
