### PR TITLE
small sync test updates

### PR DESCRIPTION
**Pull request by czue**
The main relevant change is https://github.com/dimagi/commcare-hq/commit/0014a6029f6a5ae0177cace8724571144b713126 which just reenables the broken test that I've been [wrestling with](https://github.com/dimagi/commcare-hq/pull/7448) [for a while](https://github.com/dimagi/commcare-hq/pull/7442). The rest is just minor test cleanup.
## Backstory for those who are interested

(The rest of this note is not specific to this PR, but is just me bran dumping for posterity. Please don't let the length of this note deter you from merging since the PR itself is very simple/straightforward.)

So this is a small set of changes pulled out from https://github.com/dimagi/commcare-hq/pull/7508 which is an entertaining saga of me trying to track down the intermittent test failure that's been bugging me for over a month.

I don't have a complete story but I'm pretty sure that the root culprit of those test failures is that the travis machines can intermittently get a stale version of `jsonobject` running in the venv. Specifically one that doesn't properly support the pop method that @NoahCarnahan implemented here: https://github.com/dimagi/jsonobject/pull/117

I was able to reproduce the failures down to a [pretty simple test case](https://github.com/dimagi/commcare-hq/pull/7508/files#diff-691758bf253b4cfef0bf952314f3c15eR224), and then I was never able to get that test to fail locally unless I installed `jsonobject==0.6.0` in which case it failed every time. This is consistent with the fact that whether or not the same test passed on travis seemed to be dependent on a property of the _environment_ and not the _test_ (so it either passed all 10 times or failed on the first time).

I don't have a complete story for why this version of `jsonobject` was ever getting installed. I think it might have to do with the [minimum requirement of couchdbkit](https://github.com/dimagi/couchdbkit/blob/jsonobject/setup.py#L56) and some odd install/uninstall-order. That said, I feel pretty confident that https://github.com/dimagi/commcarehq-venv/pull/6 will fix it. The reason is just based on pure brute force. Namely, the way I was getting builds to fail on https://github.com/dimagi/commcare-hq/pull/7508 was just by restarting travis over and over again until it passed (usually in about 1-5 times), and I've now run the build with the latest venv probably 8-10 times with it showing no sign of failing.

fyi @dannyroberts @snopoke and cc @dimagi/team-commcare-hq just because this was one of the hardest, oddest, most annoying issues I've tracked down in a long time and I figured it couldn't hurt to share my story. I did find that, once I had a streamlined build and logging setup, iterating directly on travis wasn't super-duper painful, so if you ever need to do that you can use https://github.com/dimagi/commcare-hq/pull/7508/ as a blueprint.

### CODE REVIEW

**Comment by czue** [comment]
wait for tests :)

**Comment by snopoke** [comment]
:+1: looks good. Thanks for the writeup.

**Comment by czue** [comment]
:white_check_mark:

**Comment by dannyroberts** [comment]
wild

**Comment by emord** [comment]
> I don't have a complete story for why this version of jsonobject was ever getting installed.

Should be fixed https://github.com/dimagi/commcare-hq/pull/7566 :)

**Pull request merged**
