### PR TITLE
fixed 500 error when planning method is None

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @emord 

I sent changes for this ticket: https://dimagi-dev.atlassian.net/browse/QA-314

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Comment by emord** [comment]
```

======================================================================
FAIL: custom.aaa.tests.test_eligible_couple_query_helper:TestEligibleCoupleBeneficiarySections.test_eligible_couple_details_with_history
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/aaa/tests/test_eligible_couple_query_helper.py", line 71, in test_eligible_couple_details_with_history
    'preferredFamilyPlaningMethod': 'N/A',
AssertionError: {u'maleChildrenAlive': 0, u'preferredFamilyPlaningMethod': u'N/A', u'femaleChild [truncated]... != {u'maleChildrenAlive': 0, u'preferredFamilyPlaningMethod': u'N/A', u'femaleChild [truncated]...
  {u'ashaVisit': u'N/A',
   u'familyPlaningMethod': u'condom',
-  u'familyPlanningMethodDate': datetime.date(2019, 3, 1),
+  u'familyPlanningMethodDate': u'2019-03-01',
   u'femaleChildrenAlive': 0,
   u'femaleChildrenBorn': 0,
   u'maleChildrenAlive': 0,
   u'maleChildrenBorn': 0,
   u'preferredFamilyPlaningMethod': u'N/A',
   u'previousFamilyPlanningMethod': u'iud'}
```

**Comment by lwyszomi** [comment]
Hi @emord 

I added to this PR some other fixes:
https://dimagi-dev.atlassian.net/browse/QA-318
https://dimagi-dev.atlassian.net/browse/QA-316
https://dimagi-dev.atlassian.net/browse/SL-88

Please let me know if you have any questions.

Regards,
Łukasz

**Review by emord — COMMENTED** [review]
I think the langcodes change was unintentional

**Comment by lwyszomi** [comment]
Hi @emord yes, I added this by mistake, PR is updated.

**Pull request merged**
