### PR TITLE
Add data filter to supplimentary nutrition for mpr

### PR DESCRIPTION
**Pull request by Rohit25negi**
applying date filter to mpr supplementary nutrition 
https://dimagi-dev.atlassian.net/browse/ICDS-520,

@sravfeyn  @calellowitz

### CODE REVIEW

**Comment by sravfeyn** [comment]
I don't have the spec context, but it looks good.

**Comment by sravfeyn** [comment]
I think this is right and was probably an oversight, at least per the indicator definition which says 'Average no. days AWCs ____ during the month?' and when I load reports for some locations, this is more than 30 since it looks for all data without filtering for the month. 

I am merging this in.

**Comment by sravfeyn** [comment]
Holding because of the hold-on tag. @Rohit25negi This is good to go

**Comment by Rohit25negi** [comment]
@sravfeyn  if it looks good. feel free to approve. I can then mege

**Pull request merged**
