### PR TITLE
pickle emailed file attachments to support non-JSON serializable data

### PR DESCRIPTION
**Pull request by nickpell**
Opening for tests - manually testing on staging right now.

Data flow:

python -> (pickled) bytes -> b64 encoded bytes -> unicode -> JSON in celery -> unicode -> b64 encoded bytes -> bytes -> python

### CODE REVIEW

**Comment by nickpell** [comment]
Error on staging:

```
Traceback (most recent call last):
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/corehq/apps/reports/tasks.py", line 98, in send_report
    notification.send()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/corehq/apps/reports/models.py", line 796, in send
    self._get_and_send_report(language, emails)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/corehq/apps/reports/models.py", line 825, in _get_and_send_report
    pickled_file_attachments=pickled_file_attachments)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 494, in _ensured
    return fun(*args, **kwargs)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 38, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 831, in default_channel
    self.ensure_connection(**conn_opts)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 332, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/connection.py", line 308, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/home/cchq/www/staging/releases/2018-08-31_13.47/python_env/local/lib/python2.7/site-packages/amqp/connection.py", line 623, in _on_close
    (class_id, method_id), ConnectionError)
AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
```

**Review by esoergel — APPROVED** [review]
Could this be done as part of a custom serializer?

**Comment by nickpell** [comment]
> Could this be done as part of a custom serializer?

Probably - although I'm not sure what the advantage would be over just using pickle.  I ended up going with https://github.com/dimagi/commcare-hq/pull/21713 in the end.

**Comment by gcapalbo** [comment]
@nickpell fyi i noticed this same error on staging today. it seems to be the case that if a celery task tries to create another celery task, this error is raised. i noticed that the celery_bash_runner.sh script used on staging is different from the one in use in [production](https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/commcarehq/templates/celery_bash_runner.sh.j2).

the one on staging is not using `python manage.py celery worker`, which might have something to do with why celery tasks can't create other tasks.

**Pull request closed without merging**
