### PR TITLE
Use reasonable sorting icons

### PR DESCRIPTION
**Pull request by proteusvacuum**
There's currently no way of knowing if a column in a report is sortable, short of clicking every single one of them (the cursor doesn't even change). Also, chevrons are very confusing.

screenshot from 2018-06-11 14-32-59

I would have gone with the default datatables classes (`sorting`, `sorting_asc`, `sorting_desc`), except for some reason we render the table header twice (one has no content, so it isn't shown). Using the default classes adds content to both of those headers, showing the second one. I decided to not try and fix that issue, and used the structure we already have. 

cc @czue

### CODE REVIEW

**Comment by proteusvacuum** [comment]
For context, the most important change that I want to get in here is the fact that we have no way of showing that a column is sortable, which seems like a very significant discoverability issue.

**Review by orangejenny — APPROVED** [review]
definite improvement

**Comment by czue** [comment]
:fire:

**Comment by biyeun** [comment]
😻

**Comment by djmore9** [comment]
<3

**Pull request merged**
