### PR TITLE
[USH-2363] use released app versions when processing SMS

### PR DESCRIPTION
**Pull request by snopoke**
https://dimagi-dev.atlassian.net/browse/USH-2362

## Product Description
This change will make messaging processing always use the latest
released version of an app instead of the latest dev version.

## Technical Summary
This changes the DB accessor used when processing SMS messages to load the latest released version instead of the current dev version.

### Safety story
This could impact live project if they are relying on the current functionality (SMS processing relies on unreleased app changes).

I have added a feature release toggle to give us a quick fallback in case this does cause issues on any domain.

### Automated test coverage
NA

### QA Plan
None

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — DISMISSED** [review]

**Comment by millerdev** [comment]
Is there a plan to eventually make this (use released app) the default rather than opt-in with a flag? Seems like that would be ideal, although comms are probably necessary before we can roll that out.

**Comment by snopoke** [comment]
> Is there a plan to eventually make this (use released app) the default rather than opt-in with a flag? Seems like that would be ideal, although comms are probably necessary before we can roll that out.

This is actually set up as an opt-out flag. The toggle randomness is defaulted to `1.0` meaning it will be enabled for everyone. I don't think we need comms but I'll check with support.

**Comment by millerdev** [comment]
I missed the `default_randomness=1.0`, and I think others are likely to do the same when reading the code. Also, is it true that this flag would do nothing when enabled for a domain because of the `default_randomness` setting? Is it even possible to disable this flag for a single domain without changing `default_randomness`, which would affect other domains as well?

Suggestion: Could we flip the meaning of the flag (by changing its name and description) so it's clear that the development app version will be used when the flag is enabled (and it's not enabled by default)?

**Comment by snopoke** [comment]
> I missed the `default_randomness=1.0`, and I think others are likely to do the same when reading the code. Also, is it true that this flag would do nothing when enabled for a domain because of the `default_randomness` setting? Is it even possible to disable this flag for a single domain without changing `default_randomness`, which would affect other domains as well?
> 
> Suggestion: Could we flip the meaning of the flag (by changing its name and description) so it's clear that the development app version will be used when the flag is enabled (and it's not enabled by default)?

Thanks, that's much better: 4e4683d375e

**Comment by snopoke** [comment]
> > Is there a plan to eventually make this (use released app) the default rather than opt-in with a flag? Seems like that would be ideal, although comms are probably necessary before we can roll that out.
> 
> This is actually set up as an opt-out flag. The toggle randomness is defaulted to `1.0` meaning it will be enabled for everyone. I don't think we need comms but I'll check with support.

No upfront comms required.

**Review by millerdev — APPROVED** [review]

**Comment by snopoke** [comment]
> > > Is there a plan to eventually make this (use released app) the default rather than opt-in with a flag? Seems like that would be ideal, although comms are probably necessary before we can roll that out.
> > 
> > 
> > This is actually set up as an opt-out flag. The toggle randomness is defaulted to `1.0` meaning it will be enabled for everyone. I don't think we need comms but I'll check with support.
> 
> No upfront comms required.

Revert that - comms to be sent firts.

**Comment by snopoke** [comment]
This has been approved. Will merge after build passes

**Pull request merged**
