### PR TITLE
dont show .0 when rounding

### PR DESCRIPTION
**Pull request by jmtroth0**
https://manage.dimagi.com/default.asp?270447#1471873

Changes the display of decimals on reports. Whenever a .0 would have been show before, it will not be shown now.

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
Can you describe to me where `get_short_decimal_display` gets used? In order to get this consistent behavior, does a column need to use a special "short_decimal" format/transform/type? Is that being created in this PR for the first time, or does it already exist? Etc.

**Comment by jmtroth0** [comment]
Good question! This pr is incredibly abstruse. 

It's used in the [data source](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/reports/sqlreport.py#L51) as a formatting function based on column, which is set [here](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/userreports/reports/builder/columns.py#L113). It is possible that we should allow some customizability for that format function, or make it smarter in some way, but I don't think that would make sense as an interrupt ticket.

Also, rather than copy the images diffs here (since i can't figure out how to adjust their size), I'm also going to mention that they are in this comment --> https://manage.dimagi.com/default.asp?270447#BugEvent.1473086

**Comment by dannyroberts** [comment]
Do you think it's accurate to say that this fixes the discrepancy in one class of situations (aggregations?) but does not address the wider fact that when given a decimal like `1.0`, the mobile and the browser will display it differently? That's my reading of the PR; I think it's fine to fix that way, but just wanted to be explicit about it if that's the case.

**Comment by jmtroth0** [comment]
I would say that is generally accurate. The one caveat I might add is that given a report with an aggregation function (I might be wrong, but I'd assume a majority?), _every_ column in the report will be formatted using this function, which should make it consistent for most situations there would be a decimal, as (I think as you said in the ticket) JS will always cut off that 0, while the phone would not without this.

I'm also not sure what other classes of situations you are considering though.

**Comment by dannyroberts** [comment]
Okay cool. Yeah I'm not sure what other classes of situations I'm considering either, I just got a hunch from the change that there would be other similar situations this solution might not catch.

I'm happy with the paper trail we've left in this PR discussion on this topic; at least now someone else (or one of us in a few months) can use this for reference if they find another similar situation.

**Review by dannyroberts — APPROVED** [review]

**Comment by jmtroth0** [comment]
Sweet! Thanks for leading it here

**Pull request merged**
