### PR TITLE
Added auto launching of actions

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
Support for https://github.com/dimagi/formplayer/pull/783

## Feature Flag
Case claim

## Product Description
Adds a new case claim option:
Screen Shot 2020-11-15 at 9 16 22 PM

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

There's test coverage for the suite file changes.

### QA Plan

[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-2114)

### Safety story
This work is relevant only to COVID projects, who will be testing it, and is well-isolated from other projects.

### Rollback instructions

There's no reason to roll back this PR. If there's a problem, it'll be in Web Apps, and the formplayer PR linked above will be the one to roll back.

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]
Have you been able to test this on mobile? Just want to make sure that having this extra attribute that mobile doesn't know about won't adversely affect things.

**Comment by orangejenny** [comment]
@proteusvacuum Good question. I'm planning to merge the commcare-core PR into the formplayer branch, not into master, so that code won't be on phones at all.

https://github.com/dimagi/commcare-core/pull/949

**Comment by proteusvacuum** [comment]
Right, I mean what does the phone do if it encounters this new attribute? Since you are changing things in the suite, to be safe I would make sure that this code change doesn't change any behaviour on the phone. (unlikely... but you never know).

**Comment by orangejenny** [comment]
@proteusvacuum Oh, you're right, I was thinking about it backwards. I agree it's unlikely to be an issue but will include a note with QA.

**Comment by orangejenny** [comment]
Confirming I tested on staging on mobile that the new setting has no effect.

**Comment by orangejenny** [comment]
Noting that QA has somewhat passed: there are outstanding issues, but this needs to be deployed for internal testing on prod that should not be affected by the outstanding issues. I wrapped these changes in an "engineering tools" feature flag so they will be hidden from other projects that use case claim. Planning to remove that flag once all qabugs are addressed.

**Pull request merged**
