### PR TITLE
add case-type column in related cases view

### PR DESCRIPTION
**Pull request by sravfeyn**
@benrudolph @proteusvacuum useful in projects with complicated case structure.
Would also be good to add relationship type since now we have3 types of relations 'extension', 'subcase' and 'indexed', but may be latter.

### CODE REVIEW

**Comment by czue** [comment]
can you screenshot where this ends up?

**Comment by sravfeyn** [comment]
3rd column in this
screen shot 2015-10-05 at 5 51 35 pm

**Comment by czue** [comment]
nice. looks good but @dimagi/product should probably weigh in

**Comment by sheelio** [comment]
looks good!

**Pull request merged**
