### PR TITLE
reindex user indexes

### PR DESCRIPTION
**Pull request by snopoke**
https://github.com/dimagi/commcare-hq/pull/10303
http://manage.dimagi.com/default.asp?216669

@emord

### CODE REVIEW

**Comment by czue** [comment]
fyi, this is going to cause the unknown users index to fire and likely fail or take ages to finish. I'm tempted to recommend just commenting out / removing [this line](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqcase/management/commands/ptop_preindex.py#L32) until we have a better workflow for that

**Comment by snopoke** [comment]
@czue I did manage to run the unknown user reindex when I did the ES migration but agree that it will take a long time

**Comment by snopoke** [comment]
updated

**Comment by czue** [comment]
thanks. will wait for tests for kicks

**Comment by emord** [comment]
Build fail real:

```
======================================================================
FAIL: test_instantiate_all (testapps.test_pillowtop.tests.test_settings.PillowtopSettingsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/testapps/test_pillowtop/tests/test_settings.py", line 33, in test_instantiate_all
    self.assertEqual(expected_meta[pillow_config.name], _pillow_meta_from_config(pillow_config))
```

**Pull request merged**
