### PR TITLE
Pick display format from style itself

### PR DESCRIPTION
**Pull request by mkangia**
## Product Description

Fix markdown in case details modal.
Markdown was not working as expected at times. This was fixed at formplayer end.
This PR updates HQ implementation originally done in https://github.com/dimagi/commcare-hq/pull/29557/files to support markdown with the fix now done in formplayer (https://github.com/dimagi/commcare-core/pull/1066 and https://github.com/dimagi/formplayer/pull/1087)

The change is backward compatible to avoid formplayer deploy dependency.

## Technical Summary

https://dimagi-dev.atlassian.net/browse/INDIV-29
The original implementation to support markdown from formplayer was buggy and was reverted in favor of an already present way of identifying markdown.
This PR just updates the corresponding HQ part.
To avoid deploy dependency with formplayer deploy we have kept things working with old implementation as well. 
So for the old response from formplayer, we simply populate `obj.style.displayFormat` at HQ, which is currently empty. This simply replicates what formplayer would [do now](https://github.com/dimagi/commcare-core/pull/1066/files).
For new response, `obj.style.displayFormat` would already be set for markdown.

### Safety story

Simple enough change. Tested on staging

### QA Plan

No QA needed

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
Tested that this is working fine on [staging](https://staging.commcarehq.org/a/ccqa-mk/cloudcare/apps/v2/#%7B%22appId%22%3A%224385344dca44410aa94dadfb21f57176%22%2C%22queryData%22%3A%7B%7D%7D),

formplayer deploy (after rebuild), gave back in response for getDetails
```
{
	"styles": [
		{
			"fontSize": 0,
			"widthHint": -1,
			"displayFormat": null
		},
		{
			"fontSize": 0,
			"widthHint": -1,
			"displayFormat": "Markdown"
		}
	]
}
```

and in HQ html template, we had
`else if (style.displayFormat === 'Markdown'` which mapped perfectly.

**Comment by mkangia** [comment]
Holding off merge based on conversation in https://github.com/dimagi/formplayer/pull/1087#issuecomment-1025544023 and merge it right before next formplayer deploy.

**Comment by mkangia** [comment]
@orangejenny 

Got some push back on the the deploy plan hence made this compatible with both old and new implementation of formplayer.
Once this is deployed, it will continue working for old implementation and will also work for the new one once formplayer is deployed.
As a follow up will remove the part marked as to be removed, next week.
Updating description.

Requesting for a re-review.

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
Tested on [staging](https://staging.commcarehq.org/a/ccqa-mk/cloudcare/apps/v2/#%7B%22appId%22%3A%224385344dca44410aa94dadfb21f57176%22%2C%22queryData%22%3A%7B%7D%7D) that this is working okay post new changes

**Pull request merged**
