### PR TITLE
OPM - changes in report

### PR DESCRIPTION
**Pull request by lwyszomi**
http://manage.dimagi.com/default.asp?191131#1078606

### CODE REVIEW

**Comment by lwyszomi** [comment]
@esoergel

**Comment by esoergel** [comment]
Looks great overall, but I'm confused about the `birth_spacing_bonus_denominator` and `nutritional_bonus_denominator` calculations - why do they only factor in the child's age for certain blocks?  Don't both blocks need that check?

**Comment by lwyszomi** [comment]
@esoergel If I good remember we had in specification that the ```birth spacing bonus``` should be only calculated for block ```wazirganj```:
https://github.com/dimagi/commcare-hq/blob/master/custom/opm/health_status.py#L492
https://github.com/dimagi/commcare-hq/blob/master/custom/opm/beneficiary.py#L638

but ```nutritional bonus``` only for block ```atri```:
https://github.com/dimagi/commcare-hq/blob/master/custom/opm/health_status.py#L498
https://github.com/dimagi/commcare-hq/blob/master/custom/opm/beneficiary.py#L604

**Comment by esoergel** [comment]
Sounds right - I'd forgotten about that.

**Pull request merged**
