### PR TITLE
Append missing Z to datetime

### PR DESCRIPTION
**Pull request by kaapstorm**
Thanks, @snopoke  

BTW, are we going to have the same problem with other models?

```
    $ git grep 'DateTimeProperty()' | wc -l
    74
```

Is the problem only with models related to locations? e.g. FacilityRegistry, SQLProduct, SQLLocation also have datetime fields. 

Buddy @millerdev

### CODE REVIEW

**Comment by dannyroberts** [comment]
A quick look through a search of `=.*isoformat` makes this appear to be the last one. All three (groups, locations, and now products) came about because in a migration to add and populate a `last_modified` field, the element in json was directly initialized to the *string value* `datetime.datetime.utcnow().isoformat()` (instead of going through the property, or being careful to put it in the conventional string format with a Z.)

**Comment by dannyroberts** [comment]
You should probably add a test for this fix. See https://github.com/dimagi/commcare-hq/pull/6576/files#diff-2a997341ab83e91ee54b52976047595cR420

**Comment by kaapstorm** [comment]
Thanks @dannyroberts, will do.

**Comment by lwyszomi** [comment]
@dannyroberts @kaapstorm 

I created case for this. http://manage.dimagi.com/default.asp?167771#935480. Today this error jumped me on HQ.

**Comment by dannyroberts** [comment]
oops sorry @kaapstorm I got confused and merged this before you had a chance to make the small change. Just pr it when you're ready

**Comment by kaapstorm** [comment]
Cool, thanks, @dannyroberts

**Pull request merged**
