### PR TITLE
Make new user number easy to disable

### PR DESCRIPTION
**Pull request by dannyroberts**
and disable it

quick response to https://manage.dimagi.com/default.asp?252377

in the future to enable just change

```
NewUserNumberAbTestMixin = NewUserNumberAbTestMixin__Disabled
```

back to

```
NewUserNumberAbTestMixin = NewUserNumberAbTestMixin__Enabled
```

For context I'm doing this because it's already been added, reverted, and then re-added (see https://github.com/dimagi/commcare-hq/pull/14557). The chance that there's some more back and forth on this reasonable, and this is a tiny little gift to whoever eventually enables it again.

### CODE REVIEW

**Comment by dannyroberts** [comment]
@calellowitz how does this look? I tested the page (/register/user) after each commit, and tested that the re-enabled step (not committed here) will work. cc: @orangejenny buddy

**Review by orangejenny — APPROVED** [review]

**Review by calellowitz — COMMENTED** [review]
In general, looks good and I would be fine merging. My one concer is that I think its pretty unlikely it will be enabled again. I think we did an a/b test and it failed. Tried another and it failed again. So I doubt we will want this again and there is a lot of code that may just sit around. May be cleaner to just kill all this code, as its easy enough to re add. 
Additionally, if what you are going for is an easy switch to turn the A/B test on and off, what we have done in the past is just set both options to off, so we didnt need to change view code. Then when we wanted to turn it on we just changed one of the options to showing the phone number. However, I dont have a strong opinion over whether that solution is better than this, so if you prefer this solution that is fine by me.

**Comment by biyeun** [comment]
@calellowitz I think we should revert and remove the A/B test code for the sake of cleanliness and simplicity.

**Comment by dannyroberts** [comment]
Okay, I was working off of what Audrey said in the ticket

> (I hope it does not take too much time to remove: we might have to put it back in a few weeks, but for now we don't have enough bandwith to use it and it is decreasing the number of sign-ups without the additional benefit of using the phone nummber). 
>
> It might be quicker to keep the 2 A/B group - even if they see the exact same page, so that we can re-use that structure when we want to re-launch the test?

**Comment by biyeun** [comment]
@dannyroberts ah ok, then in that case I'll keep this PR in favor of https://github.com/dimagi/commcare-hq/pull/15836

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
