### PR TITLE
add indexes to enikshay episode data source

### PR DESCRIPTION
**Pull request by emord**
@proteusvacuum @benrudolph 

Went through the postgres logs on india and saw a decent amount of errors about locking on this table. I think the main issue here was swappiness on india (which has since been fixed), but this should make these queries much faster. 

buddy @orangejenny

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]

**Review by benrudolph — APPROVED** [review]
great doesn't hurt to add these

**Comment by benrudolph** [comment]
test failure maybe real? 
```
======================================================================
FAIL: custom.enikshay.ucr.tests.test_episode_datasource:TestEpisodeDatasourceES.test_diagnostic_test_after_end_of_ip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/enikshay/ucr/tests/test_episode_datasource.py", line 206, in test_diagnostic_test_after_end_of_ip
    self.assertEqual(query.count(), 1)
AssertionError: 0 != 1
----------------------------------------------------------------------
Ran 2383 tests in 907.636s

```

**Comment by emord** [comment]
✅

**Comment by proteusvacuum** [comment]
does this need a datasource rebuild?

**Comment by emord** [comment]
@proteusvacuum adding create_index doesn't need a full rebuild #15710 we've done it on NIC without requiring a total rebuild

**Comment by emord** [comment]
We can also add them manually and it won't attempt to rename or remove/create the indexes so if you ever need to test before you can add them in postgres concurrently and add them later to the datasource

**Comment by proteusvacuum** [comment]
OK. I think doing a rebuild takes about ~12 hours so not that big of a deal
-- we can kick it off after today's deploy and have it run over the weekend?

**Comment by emord** [comment]
no rebuild necessary (offlined)

**Pull request merged**
