### PR TITLE
Remove report build tours

### PR DESCRIPTION
**Pull request by benrudolph**
@NoahCarnahan, @sheelio created a ticket to remove these tours: http://manage.dimagi.com/default.asp?231791. Is this the best way to do that? (I haven't worked much with tours). I clicked around the seemingly affected pages and got no errors, but would like to test it out a bit more just to make i didn't miss something dumb (added label)

cc: @proteusvacuum @sravfeyn

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Looks good to me. 👍 when you are happy with it.

**Comment by NoahCarnahan** [comment]
Looks good. I think there were also a couple lines in `dashboard_domain.html` and `reports_home.html` that can be removed as well. I think the two commits that introduced the tour are https://github.com/dimagi/commcare-hq/pull/11435/commits/1e444db53b9934bb2f49c1bc98a0beb660cc694a and https://github.com/dimagi/commcare-hq/pull/11435/commits/77aa8a440eb7c1f10d593ae19a9c4ae2d028421f.

**Comment by benrudolph** [comment]
k happy with this now. made a report all the way through without any errors. g2m on ✅

**Comment by NoahCarnahan** [comment]
👍 on ✅ , although looks like travis isn't running tests?

**Comment by proteusvacuum** [comment]
For some reason it isn't updating here, https://travis-ci.org/dimagi/commcare-hq/builds/143404685

**Comment by benrudolph** [comment]
thanks, that's frustrating

**Pull request merged**
