### PR TITLE
ICDS - new topojsons

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @emord 

I added new topojsons, I didn't remove old for now. Case: http://manage.dimagi.com/default.asp?273601

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Comment by emord** [comment]
These new files are quite large. District file is 13x the size as before.

Looking at htis it looks like a user has to download the entire file even if they only look at one district. Is there a way to only send down a part of the file? Otherwise I think there will be a lot of performance issues

**Comment by lwyszomi** [comment]
@emord most of the lines in topojson must be in the one file (~4 millions lines), even when we split rest for the smallest files I think this will not help.

Currently, the topojson is very detailed, I think we can round a little the shapes in new topojsons, If you think that we can have issues with performance.

**Comment by emord** [comment]
I think there will definitely be performance issues, though I haven't played around with it. Could you put these files behind a feature flag so that someone could test htis on a less powerful computer and internet connection?

Also what's the need for having all of them in the same file? Would it be possible to have them split up in the following files:

* state topojosn (smallest possible topojson that allows clicking each state)
* district_state_1.json (all districts for state_1)
* district_state_2.json (all districts for state_2)
....
* block_state_1.json (all blocks for state_1)
* block_state_2.json (all blocks for state_2)

Also have you tried using toposimplify? https://github.com/topojson/topojson-simplify I'm not very familiar with these files but it didn't look like htat was part of the process on confluence

**Comment by lwyszomi** [comment]
Hi @emord 

Currently, new shapefiles will be hidden by icds feature flag. I'm still searching what we can do to decrease files size.

Here https://github.com/topojson/topojson/wiki/Introduction we have a good definition of what is included in topojson.

As you can notice in the first example, ```arcs``` in ```arube``` use the definition from main ```arcs``` property. I can try to create some script which split big topojson into smaller ones.

Regards,
Łukasz

**Comment by lwyszomi** [comment]
Hi @emord 

I reduced the size of district topojson from 25.1 MB to 6.35 MB.

Regards,
Łukasz

**Comment by emord** [comment]
Can you rebase this so that the 25 MB file is removed from the history?

**Comment by lwyszomi** [comment]
@emord 👍

**Comment by lwyszomi** [comment]
@emord done

**Review by emord — APPROVED** [review]
Thanks will just wait for tests

**Pull request merged**
