### PR TITLE
Upgrade Celery to 4.4.7 and get rid of redis-py-cluster

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAAS-137

##### SUMMARY
Upgrades Celery to 4.4.7. Due to a whole [series of dependency upgrade requirements](https://gist.github.com/biyeun/ee9c9004c278f150bd5f0594587a2452), @snopoke's note that ICDS is no longer using `redis-py-cluster`, and the fact that `redis-py-cluster` has a questionable package maintenance strategy...this PR also removes `redis-py-cluster`.

I'll also link a followup commcare-cloud ticket to remove `is_redis_cluster` from settings files...

##### RISK ASSESSMENT / QA PLAN
Leaving this on staging for the next week and will trigger a QA ticket for it.

### CODE REVIEW

**Comment by dannyroberts** [comment]
I wonder if you could remove `redis-py-cluster` as it's own simpler PR that wouldn't need much QA to just really isolate the bigger/scarier celery change. Would that work?

**Review by snopoke — APPROVED** [review]

**Comment by biyeun** [comment]
@dannyroberts i thought about that...but I was worried that removing `redis-py-cluster` might at least need a sanity check. I can create a smaller PR if you think it doesn't though

**Comment by dannyroberts** [comment]
Yeah I think if you thought about it and decided this is better, than I'm fine with that. There are definitely benefits, like being able to do one QA pass for both, so sounds good.

Unrelatedly, looks like there's a (very simple) conflict to resolve with Daniel's python2/3 migration cleanup PR

**Review by dannyroberts — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by biyeun** [comment]
@dannyroberts yes i'm on it. had some annoying derailments yesterday getting my personal machine set up for dev work again, as my work laptop is in repair 🤕

**Review by millerdev — APPROVED** [review]

**Comment by biyeun** [comment]
test finally pass ✅

**Review by millerdev — APPROVED** [review]

**Comment by biyeun** [comment]
QA is complete!

**Pull request merged**
