### PR TITLE
delete unused filters

### PR DESCRIPTION
**Pull request by snopoke**
@biyeun

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by biyeun** [comment]
looks like the build failure was an intermittent thing, restarted ...will merge when it's all go :+1:

**Comment by czue** [comment]
I think the build fail is real
```
Traceback (most recent call last):
  File "manage.py", line 69, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "custom/_legacy/a5288/__init__.py", line 1, in <module>
    from a5288.reports import MissedCallbackReport
  File "custom/_legacy/a5288/reports.py", line 5, in <module>
    from corehq.apps.reports.standard import CustomProjectReport
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/reports/standard/__init__.py", line 8, in <module>
    from corehq.apps.reports import util
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/reports/util.py", line 29, in <module>
    from .models import HQUserType, TempCommCareUser
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/reports/models.py", line 51, in <module>
    from couchforms.filters import instances
ImportError: No module named filters
```

**Comment by snopoke** [comment]
dammit

**Pull request closed without merging**
