### PR TITLE
B3 Reminders Views Prep + Cleanup

### PR DESCRIPTION
**Pull request by biyeun**
Removes unused reminders views and adds in B3 support in preparation for future reminders views

### CODE REVIEW

**Comment by gcapalbo** [comment]
@biyeun so far i removed the reminders in error view and the old broadcast ui views from this. i think that's everything for the unused view code but i'm going to doublecheck to make sure there's nothing else.

**Comment by biyeun** [comment]
@gcapalbo rebased with master. did you find out if there was anything else missing?

**Comment by gcapalbo** [comment]
@biyeun found and removed a few more things, that should be everything now.  feel free to have a look if you like, this is good to merge from my side

**Comment by biyeun** [comment]
@gcapalbo thanks! looks good to me as well @millerdev want to be the third party and merge? :)

**Comment by gcapalbo** [comment]
ok, i think i'll merge if we're both good with it - i'd like to merge this into another branch where i'm making some other updates to avoid conflicts

**Comment by biyeun** [comment]
:tada:

**Comment by czue** [comment]
:blue_heart: :large_blue_circle: :large_blue_diamond:

**Pull request merged**
