### PR TITLE
Tests for ping_login

### PR DESCRIPTION
**Pull request by orangejenny**
Branches off of https://github.com/dimagi/commcare-hq/pull/27630, only the last commit is new.

### CODE REVIEW

**Comment by orangejenny** [comment]
Added a commit with some js tests. Rebased to shorten the commit history now that the parent PR is merged, didn't change the content of any commits.

**Comment by orangejenny** [comment]
Rebased to clean up commit history and resolve conflicts with other PRs; I don't think anyone had started reviewing yet.

Marking don't merge just because this now also removes logging that was added earlier today, and I want to leave that logging on prod for a few days.

**Review by millerdev — APPROVED** [review]
These are great!

**Comment by orangejenny** [comment]
Added a commit to restore the logging. I'd like to get the tests merged but leave the logging up for a few more days.

**Review by millerdev — APPROVED** [review]

**Comment by orangejenny** [comment]
I'm going to add a tiny bit of buffer in the tests to fix this:
```  
1) inactivity inactivityTimeout should ping when there are 2 minutes left:
     AssertionError: expected 179999 to equal 180000
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:2178
      at http://localhost:8000/static/hqwebapp/spec/inactivity_spec.js:18
```

**Review by millerdev — APPROVED** [review]

**Pull request merged**
