### PR TITLE
Show "Reports" nav item when editing UCReports

### PR DESCRIPTION
**Pull request by NoahCarnahan**
FYI @czue I took this one from the UCR backlog

This one took a while to track down. The issue was that some of the top navigation bar items did not show when viewing pages like the "edit ucr report" page.

It looks like this tab (and the Dashboard tab) are dependent on the `project` attribute existing on the request object. The request object for this page never had `project` set.

It turns out that the `login_and_domain_required` decorator modifies the request object. `apps.domain.decorators.load_domain()`, which is called by `login_and_domain_required`, adds attributes to the request object, including the `project` attribute.

`UITab` objects store the values of `request.project`, and the `ProjectReportsTab` (which is a `UITab` subclass) checks for the existence of the project in its `is_viewable` method, which in turn determines if the `Reports` nav item will be shown.

It makes sense that the Reports tab wouldn't be visible for pages without a domain/logged in user, but it doesn't seem very intuitive that the `login_and_domain_required` decorator would modify the request or would have an affect on how the page is rendered. It's also confusing because `login_and_domain_required` isn't the only way to check if there is a user logged in and domain associated with the page. In this case the `toggles.USER_CONFIGURABLE_REPORTS.required_decorator()` decorator was performing that check. Anyone have any thoughts on that?

It would nice if `request.project` gets set in a more explicit or universal way, although I'm not sure off the top of my head where that should happen. (In middleware perhaps?)

@dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
yikes, sorry about that. 

Big :+1:  to "It would nice if request.project gets set in a more explicit or universal way, although I'm not sure off the top of my head where that should happen. (In middleware perhaps?)"

**Comment by czue** [comment]
We should also add a backlog item to enforce domain subscription checks on UCR pages (definitely required before removing the toggle, though probably better to do as early as possible).

**Comment by NoahCarnahan** [comment]
(backlog item added)

**Comment by dannyroberts** [comment]
Might be worth adding another middleware class to this file that does it: https://github.com/dimagi/commcare-hq/blob/1e0a807e31315f3974a360bfb4cafc892c82781c/corehq/apps/domain/middleware.py, where you add both `request.domain`, `request.org` (both currently, arbitrarily here right now: https://github.com/dimagi/commcare-hq/blob/1e0a807e31315f3974a360bfb4cafc892c82781c/corehq/apps/users/middleware.py#L29-29), and `request.project`, if the url has a domain at all, of course. (Make sure to add it to https://github.com/dimagi/commcare-hq/blob/1e0a807e31315f3974a360bfb4cafc892c82781c/settings.py#L120-120, probably near the top of the custom ones, since other middlewares may rely on `request.domain` and/or `request.project`.)

**Pull request merged**
