### PR TITLE
Remove old export models

### PR DESCRIPTION
**Pull request by benrudolph**
The beginning of the end of old exports. Still have a couple domains left to migrate. This'll get rid of the old models though

@NoahCarnahan cc: @proteusvacuum

### CODE REVIEW

**Review by NoahCarnahan — APPROVED** [review]
niiiiiiice

**Comment by proteusvacuum** [comment]
💀 ☠️

**Comment by benrudolph** [comment]
not gonna have time to finish this 😞

**Comment by emord** [comment]
@benrudolph can you write what blocked you from merging this? I thought you completed the migration before last week

**Pull request closed without merging**
