### PR TITLE
Make Spanish translations appear on HQ

### PR DESCRIPTION
**Pull request by esoergel**
Michelle is working on a proposal to get HQ translated into Spanish.  I noticed that we're already set up for translations on transifex, but we don't actually display those translations.  Turns out that's simply because `'es'` isn't in `settings.LANGUAGES`.  Ideally we'd only show options from `settings.LANGUAGES` in the dropdown where you select a language (since those are the only ones we'll actually sorta translate), but we currently need to keep the full list of every language because that's used in cloudcare for app translations.

Read the commits separately, the messages have more context.

### CODE REVIEW

**Comment by esoergel** [comment]
@czue @orangejenny

**Comment by orangejenny** [comment]
Slightly surprised that the middleware change isn't worth running tests for, is that overly paranoid?

**Comment by esoergel** [comment]
Couldn't hurt, this won't be deployed until tomorrow anyways.

**Comment by orangejenny** [comment]
thanks :)

**Pull request merged**
