### PR TITLE
let transifex override translations in the same place

### PR DESCRIPTION
**Pull request by sravfeyn**

### CODE REVIEW

**Comment by sravfeyn** [comment]
@twymer

**Comment by sravfeyn** [comment]
responding to https://github.com/dimagi/commcare-hq/commit/e8b884289964895c40b438303db93bd4e2c6f3f0#commitcomment-10713258

**Comment by twymer** [comment]
I don't actually understand why this is necessary. It has always overwritten the previous file when I ran the commands I put in the wiki page about this, but this seems more correct so if it works that's cool.

**Comment by sravfeyn** [comment]
Interesting, it creates new files in `po/hinhin.po` (where lang is hin) for me as per `file_filter = po/<lang><lang>.po`, while the translation it should be `locale/hin/LC_MESSAGES/django.po`

**Pull request merged**
