### PR TITLE
Properly translate a bunch of strings

### PR DESCRIPTION
**Pull request by esoergel**
bulk-replace `ugettext_noop` with `ugettext_lazy` and hope for the best

Found this good explanation http://blog.bessas.me/post/65775299341/using-gettext-in-django

``` python
import logging
from django.http import HttpResponse
from django.utils.translation import ugettext as _

def view(request):
    msg = ugettext_noop("An error has occurred")
    logging.error(msg)
    return HttpResponse(_(msg))
```

basically, `ugettext_noop` lets you mark the string for translation, and pass it around untranslated, that way you can log it in English, but you still need to actually translate before displaying to the user.  Normally you wouldn't pass dynamic args to `ugettext`, but in this case you know msg to be a static string.
My read of that is that we should only use `ugettext_noop` in instances where we have a good reason to keep the untranslated string around.  It looks like most of our usages of that are wrong, and we should be using `ugettext_lazy` instead.
This PR does a bulk replace of `ugettext_noop` for `ugettext_lazy` and some related cleanup to remove duplicate imports and such.  The bulk replace is committed separately so you can skip that commit when reviewing.
I'm throwing this on staging, but I'd love to hear a reason why this isn't needed, so if you've got an idea, send it my way.  Anyways, we should really try to get this sorted quickly, because the merge conflicts are gonna be horrific.

### CODE REVIEW

**Comment by czue** [comment]
in my opinion we shouldn't use such blunt hammer here. I think we should probably review/understand each change and do them individually. the noops are hurting anyone - the major downside is that some of them don't later get translated which we can fix as they come up.

@gcapalbo just [pointed out](https://github.com/dimagi/commcare-hq/pull/7502#issuecomment-122895818) one way that this can fail unexpectedly. Also, if you call `json.dumps` on anything that contains a lazily translated string it will crash.

**Comment by czue** [comment]
also fyi we have our own docs on this (though they don't distinguish from lazy and noop very well) http://commcare-hq.readthedocs.org/en/latest/translations.html#internationalization

**Comment by dimagimon** [comment]
There are 16 errors:

* corehq/apps/domain/forms.py, line 192 - E501 line too long (137 > 115 characters)
* corehq/apps/reminders/event_handlers.py, line 31 - E501 line too long (124 > 115 characters)
* corehq/apps/reminders/forms.py, line 440 - E501 line too long (121 > 115 characters)
* corehq/apps/reminders/forms.py, line 1588 - E501 line too long (116 > 115 characters)
* corehq/apps/reports/commconnect/system_overview.py, line 128 - E501 line too long (170 > 115 characters)
* corehq/apps/reports/commtrack/standard.py, line 217 - E501 line too long (123 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 725 - E501 line too long (136 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 726 - E501 line too long (132 > 115 characters)
* corehq/apps/reports/standard/monitoring.py, line 442 - E501 line too long (137 > 115 characters)
* corehq/apps/sms/messages.py, line 35 - E501 line too long (141 > 115 characters)
* corehq/apps/sms/verify.py, line 13 - E501 line too long (149 > 115 characters)
* custom/bihar/fields.py, line 1 - F401 'ugettext_lazy' imported but unused
* custom/bihar/reports/indicators/reports.py, line 188 - W291 trailing whitespace
* custom/fri/forms.py, line 6 - F401 'ugettext_lazy' imported but unused
* custom/fri/views.py, line 10 - F401 'ugettext_lazy' imported but unused
* custom/succeed/utils.py, line 1 - F401 '_' imported but unused

**Comment by dimagimon** [comment]
There are 16 errors:

* corehq/apps/domain/forms.py, line 192 - E501 line too long (137 > 115 characters)
* corehq/apps/reminders/event_handlers.py, line 31 - E501 line too long (124 > 115 characters)
* corehq/apps/reminders/forms.py, line 440 - E501 line too long (121 > 115 characters)
* corehq/apps/reminders/forms.py, line 1588 - E501 line too long (116 > 115 characters)
* corehq/apps/reports/commconnect/system_overview.py, line 128 - E501 line too long (170 > 115 characters)
* corehq/apps/reports/commtrack/standard.py, line 217 - E501 line too long (123 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 725 - E501 line too long (136 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 726 - E501 line too long (132 > 115 characters)
* corehq/apps/reports/standard/monitoring.py, line 442 - E501 line too long (137 > 115 characters)
* corehq/apps/sms/messages.py, line 35 - E501 line too long (141 > 115 characters)
* corehq/apps/sms/verify.py, line 13 - E501 line too long (149 > 115 characters)
* custom/bihar/fields.py, line 1 - F401 'ugettext_lazy' imported but unused
* custom/bihar/reports/indicators/reports.py, line 188 - W291 trailing whitespace
* custom/fri/forms.py, line 6 - F401 'ugettext_lazy' imported but unused
* custom/fri/views.py, line 10 - F401 'ugettext_lazy' imported but unused
* custom/succeed/utils.py, line 1 - F401 '_' imported but unused

**Comment by dimagimon** [comment]
There are 16 errors:

* corehq/apps/domain/forms.py, line 192 - E501 line too long (137 > 115 characters)
* corehq/apps/reminders/event_handlers.py, line 31 - E501 line too long (124 > 115 characters)
* corehq/apps/reminders/forms.py, line 440 - E501 line too long (121 > 115 characters)
* corehq/apps/reminders/forms.py, line 1588 - E501 line too long (116 > 115 characters)
* corehq/apps/reports/commconnect/system_overview.py, line 128 - E501 line too long (170 > 115 characters)
* corehq/apps/reports/commtrack/standard.py, line 217 - E501 line too long (123 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 725 - E501 line too long (136 > 115 characters)
* corehq/apps/reports/filters/forms.py, line 726 - E501 line too long (132 > 115 characters)
* corehq/apps/reports/standard/monitoring.py, line 442 - E501 line too long (137 > 115 characters)
* corehq/apps/sms/messages.py, line 35 - E501 line too long (141 > 115 characters)
* corehq/apps/sms/verify.py, line 13 - E501 line too long (149 > 115 characters)
* custom/bihar/fields.py, line 1 - F401 'ugettext_lazy' imported but unused
* custom/bihar/reports/indicators/reports.py, line 188 - W291 trailing whitespace
* custom/fri/forms.py, line 6 - F401 'ugettext_lazy' imported but unused
* custom/fri/views.py, line 10 - F401 'ugettext_lazy' imported but unused
* custom/succeed/utils.py, line 1 - F401 '_' imported but unused

**Comment by esoergel** [comment]
Okay, closing in favor of https://github.com/dimagi/commcare-hq/pull/7550, but I still think that the overwhelming majority of our `ugettext_noop`s aren't being translated, and that we should chip away at those as we can.

**Comment by czue** [comment]
:+1: to chipping away. not sure i agree about the "vast majority" bit, but would be good to better understand it. my sense is that most people who use HQ in french complain about bad translations pretty quickly, but i could be wrong about that.

**Comment by benrudolph** [comment]
thanks for sharing the blog post, was a good read

**Comment by esoergel** [comment]
@czue do you know of specific instances where `ugettext_noop` is used correctly?  I'd like to see where that's done (maybe calling `ugettext` on `page_title` when it's added to the context, for instance) to get a better idea of how prevalent this is.

**Comment by czue** [comment]
so here's where description and name get translated in the sidebar for class-based reports: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/reports/dispatcher.py#L189

**Comment by czue** [comment]
is that what you were looking for?

**Comment by esoergel** [comment]
Nice, yeah.  Do you know if there's a reason to prefer that pattern over `ugettext_lazy`?

**Comment by czue** [comment]
I think the shortest answer is that you rarely need it. The longer one goes back to my skype rant and to understand when these two points might come into play:

- lazy translations can have unexpected behavior if they become string-like before you have the threadlocals context
- lazy translations can also have unexpected behavior if they are explicitly expected to be strings

**Pull request closed without merging**
