### PR TITLE
[B5 Migration] Add support for ES6 Modules and split core javascript into bootstrap5 and bootstrap3 versions

### PR DESCRIPTION
**Pull request by biyeun**
## Technical Summary
This ensures that `build_requirejs` makes two builds, one for `bootstrap3` and one for `bootstrap5`

For `bootstrap3`, the only changes that should be present are renaming of core relevant files.

Otherwise, for the `bootstrap5` requirejs build this creates the following changes:
- adds support for the `requirejs-babel7` plugin so that `es6` modules can be built with `requirejs`
- a list of apps that currently do not support bootstrap5 have also been added to `build_requirejs`. As the migration proceeds, this list will of course be updated as the javascript gets updated.

### Safety story
Leaving this on staging for the rest of this week. The earlier test branch already was able to catch a few issues nearly immediately after deploy to staging. The issues these changes will cause for active HQ pages would be 404s related to missed files/strings during the renaming process.

I've consolidated and cleaned up the changes from the [test branch](https://github.com/dimagi/commcare-hq/pull/32894/files) to only what is minimally needed to split our core javascript into `bootstrap3` and `bootstrap5` versions.

### Automated test coverage
Yes

### QA Plan
Leaving on staging for this week should be enough

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by biyeun** [comment]
related commcare cloud pull request https://github.com/dimagi/commcare-cloud/pull/5949

**Review by millerdev — COMMENTED** [review]
Looking good. I assume test failures will need to be addressed before this is merged.

**Review by gherceg — COMMENTED** [review]
@nospame and I pair reviewed this (though mainly spent time trying to better understand this work as a whole). Looks good so far!

**Comment by biyeun** [comment]
@millerdev test failures addressed btw :)

**Review by millerdev — APPROVED** [review]

**Pull request merged**
