### PR TITLE
Delete bad doc types and convert CommCareCases to IndicatorCase

### PR DESCRIPTION
**Pull request by esoergel**
http://manage.dimagi.com/default.asp?158402#903268
@biyeun

### CODE REVIEW

**Comment by esoergel** [comment]
@dannyroberts would you mind taking a look at this?

**Comment by dannyroberts** [comment]
Oh, dear. Sorry for botching this Ethan.

**Comment by benrudolph** [comment]
Hey just did some initial analysis on this. The document id that @nickpell pointed out was missing has a domain of `mvp-tiby`, yet when you check [MVP.DOMAINS](https://github.com/benrudolph/commcare-hq/blob/master/custom/_legacy/mvp/models.py#L15), mvp-tiby is not listed. Perhaps this could be the cause? @dannyroberts @esoergel. If this makes sense, I can update that list, though I'm not sure where to find to the master copy of the domains that mvp has.

**Comment by esoergel** [comment]
@benrudolph That information is also here: https://github.com/dimagi/commcare-hq/blob/9e7b34ca0cded7d8da8c89c1f081c7d5460741f6/settings.py#L1314-L1319
What you suggested sounds reasonable to me, but we should certainly loop in @biyeun in case there's a reason to exclude `mvp-tiby`

**Comment by benrudolph** [comment]
ok thanks, will wait for confirmation then

**Comment by czue** [comment]
i'm pretty sure we should just add mvp-tiby

**Comment by benrudolph** [comment]
k

**Pull request merged**
