### PR TITLE
Optimize, fix, and test compress command

### PR DESCRIPTION
**Pull request by benrudolph**
@millerdev @biyeun this fixes and optimizes the compress test from 20 seconds to 13 seconds (on my machine, daniel i switched to using the master branch when comparing which showed a bigger difference).

cc: @proteusvacuum

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 6 errors:

* corehq/apps/style/noop.py, line 1 - F401 'os' imported but unused
* corehq/apps/style/noop.py, line 2 - F401 'subprocess' imported but unused
* corehq/apps/style/noop.py, line 5 - F401 'FilterError' imported but unused
* corehq/apps/style/noop.py, line 6 - F401 'CompilerFilter' imported but unused
* corehq/apps/style/noop.py, line 8 - F401 'fstr' imported but unused
* corehq/apps/style/noop.py, line 9 - F401 'settings' imported but unused
F811 redefinition of unused 'settings' from line 3

**Comment by millerdev** [comment]
No idea if the test fail is related or not, but it failed:
```
======================================================================
ERROR: This should execute a basic transferring of domains. user will transfer a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/domain/tests/test_domain_transfer.py", line 223, in test_basic_workflow
    resp = self.client.get(reverse(TransferDomainView.urlname, args=[self.domain.name]))
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 422, in request
    response = self.handler(environ)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 110, in __call__
    response = self.get_response(request)
  File "/vendor/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/vendor/lib/python2.7/site-packages/django/core/handlers/base.py", line 243, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/mnt/commcare-hq-ro/corehq/apps/hqwebapp/views.py", line 98, in server_error
    '500traceback': traceback_key,
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/vendor/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/vendor/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/vendor/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/vendor/lib/python2.7/site-packages/django/test/utils.py", line 88, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 1136, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/vendor/lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 32, in statici18n
    return static(get_path(locale))
  File "/vendor/lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 19, in get_path
    return os.path.join(settings.STATICI18N_OUTPUT_DIR,
  File "/vendor/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'STATICI18N_OUTPUT_DIR'
-------------------- >> begin captured logging << --------------------
auditcare.middleware: DEBUG: Middleware is running in a test context, disabling monkeypatch
--------------------- >> end captured logging << ---------------------
```

**Comment by biyeun** [comment]
hmmm, why isn't the build shown above the merge button on this pr? o_O

**Comment by millerdev** [comment]
I think because the last commit had `[ci skip]`

**Comment by biyeun** [comment]
@benrudolph ping

**Pull request closed without merging**
