### PR TITLE
Sanitize case_json

### PR DESCRIPTION
**Pull request by benrudolph**
@czue this ensures that all properties that are None are now "" when sending JSON back to mobile. @ctsims do you think it's fine to always encode `null` as `""`? Or do some values have a distinction between `null` and `""`. If so I'll just put a quick line in to just make `case_type` an empty string.

http://manage.dimagi.com/default.asp?158655#890304

### CODE REVIEW

**Comment by dannyroberts** [comment]
I can let @czue weigh in, but to me this doesn't feel like a clean solution, I think for two reasons, if I understand it correctly. One is that `None` and `""` do generally mean different things, and sort of optionally converting all of one to another, while it may serve a specific purpose, seems sloppier than deciding upfront which value a particular field represents and going with that.

The second has to do with the nature of the original issue, which is that data is bad in the first place, and we want to (1) figure out how it got that way and (2) make it so that the things that are already that way behave "the most appropriately possible" given the situation. My intuition is that this solution goes in too deeply to the internals (like modifying `CommCareCase.get_json`) in addressing (2), when there's hopefully a more superficial solution that is more clearly there directly to address this case.

I don't fully understand the ramifications of the blank case_type issue, so it could very well be that I'm missing something important.

**Comment by czue** [comment]
@dannyroberts for what it's worth the current casexml generation essentially does this already so if the goal of the json API is to acheive parity with casexml then i don't think it's necessarily bad. from cloudcare's perspective this actually makes the API more accurately like what would happen on a phone (which is the bug that's being fixed).

https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/casexml/apps/case/xml/generator.py#L13
https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/casexml/apps/case/xml/generator.py#L31

i agree we should deliberately decide that's what this function is for though before agreeing this is the right way to proceed and your general reservations make sense - though we might decide this is the correct thing to do for now.

**Comment by czue** [comment]
(we're also definitely going to look into what happened to those cases)

**Comment by benrudolph** [comment]
@dannyroberts, good points for sure. I agree it's not the best solution, but if mobile is just treating `null` and `""` as falsey values and sometimes chokes on `null` then I don't think it's too terrible. If it distinguishes between the two, then yea, we should definitely not fix it like this. We could also explicitly move this logic to the `CaseAPIResult` which would make it more of a specific solution for sending data back to mobile. I think the best would be adding constraints on couch (not sure if this is possible) so it throws an error when it's null right away. Chasing an error down during transmission to the phone is probably one of the worst places we could fail since it takes a concerted effort on both teams to debug.

Alternatively, we can drop this for now and manually change the documents that are corrupted and then try and figure out how they got that way.

**Comment by benrudolph** [comment]
(test failure is real)

**Comment by czue** [comment]
(definitely vote not to drop - at a minimum we should patch the APIs cloudcare uses with conversions that the engine might choke on)

**Comment by dannyroberts** [comment]
sounds good and like you've got a handle on it, and were already basically considering the things I mentioned :+1:

**Comment by benrudolph** [comment]
ok i feel comfortable with this for now then. if it looks good, i'm hoping to get this in before the deploy today

**Pull request merged**
