### PR TITLE
proper parens for PhoneTime in WAT

### PR DESCRIPTION
**Pull request by benrudolph**
@nickpell minor bug i caused: http://manage.dimagi.com/default.asp?218052. fixed here

cc: @NoahCarnahan

### CODE REVIEW

**Comment by nickpell** [comment]
looks good

**Comment by nickpell** [comment]
tests haven't started :/

**Comment by benrudolph** [comment]
dammit.. will rebase in a bit

**Comment by benrudolph** [comment]
(though there's clearly no test coverage since this bug would've been caught if there was)

**Comment by nickpell** [comment]
truth

**Pull request merged**
