### PR TITLE
Select2 4.0 for Bootstrap 3 Templates

### PR DESCRIPTION
**Pull request by biyeun**
See what's new: https://select2.github.io/announcements-4.0.html

@benrudolph

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 90 errors:

* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/az.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/az.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/bg.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/bg.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ca.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ca.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/cs.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/cs.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/cs.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/da.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/da.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/de.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/de.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/en.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/en.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/es.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/es.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/et.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/et.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/eu.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/eu.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fa.js, line 3 - This character may get silently deleted by one or more browsers.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fa.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fa.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fi.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fi.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fr.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/fr.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/gl.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/gl.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/he.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/he.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hi.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hi.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hr.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hr.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hr.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hu.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/hu.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/id.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/id.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/is.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/is.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/it.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/it.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ko.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ko.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lt.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lt.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lt.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lv.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lv.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/lv.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/mk.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/mk.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/nb.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/nb.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/nl.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/nl.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pl.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pl.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pt-BR.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pt-BR.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pt.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/pt.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ro.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ro.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ru.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ru.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/ru.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sk.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sk.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sr.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sr.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sr.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sv.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/sv.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/th.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/th.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/tr.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/tr.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/uk.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/uk.js, line 3 - 'e' is already defined.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/uk.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/vi.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/vi.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/zh-CN.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/zh-CN.js, line 3 - Missing semicolon.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/zh-TW.js, line 3 - 'e' used out of scope.
* corehq/apps/style/static/style/lib/select2-4.0/dist/js/i18n/zh-TW.js, line 3 - Missing semicolon.

**Comment by benrudolph** [comment]
so just to be sure, the `full` js file will allow us to use the old version still and notify us of anything that won't work when we upgrade. thus we can go ahead and merge this correct?

**Comment by biyeun** [comment]
@benrudolph yes, and as a backstop, this is only used in B3 templates at the moment (I'll switch it over after a bit of testing in the wild)

**Comment by benrudolph** [comment]
cool looks neat

**Pull request merged**
