### PR TITLE
Web Apps: block submit while validation in progress

### PR DESCRIPTION
**Pull request by orangejenny**
https://dimagi-dev.atlassian.net/browse/SAAS-10830

This disables the submit button in Web Apps while an answer validation request is in progress. Web apps already has a concept of a blocking request, which disables all inputs. This adds a semi-blocking request, which disables only the submit button.

This does not affect App Preview.

Review as you like, the commits are small.

### CODE REVIEW

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
What do you think about the `fa fa-spin fa-spinner` icon when the `Working...` text shows up? Or maybe alongside the submit button so that the perception is that something external/operational is going on?

**Comment by orangejenny** [comment]
@biyeun I like that, will take a look at adding an icon.

**Comment by orangejenny** [comment]
Updated UX: instead of disabling the submit button on every validation, the submit button now stays enabled until it gets clicked (then is disabled to prevent duplicate clicks) but it waits to actually send the submission until any pending validation request has returned.

This makes for a better UX in the case where your cursor is in a question input and you click directly on the submit button (previously, the button would have been briefly disabled, foiling your click).

**Comment by orangejenny** [comment]
Killed the python test jobs. JS job is running.

**Comment by dannyroberts** [comment]
✅

**Pull request merged**
