### PR TITLE
migrate role + list user views to use SQL role

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
Migrate the following views to use SQL roles:

* list / create / update / delete role
* list web / mobile users
* web user invitations

All references to Couch UserRole are migrated to SQLUserRole in `corehq/apps/users/views`.

Can review by commit.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
Added for role CRUD

### QA Plan
* Role CRUD
* Mobile user create & edit (not including bulk import / download)
* Web user create & edit (including bulk import involving roles)

QA ticket: https://dimagi-dev.atlassian.net/browse/USH-978

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by orangejenny — COMMENTED** [review]
All the code here looks good, just two questions:

Doesn't switching `assignable_by` to the couch id in e291b040c45aadd8ac0df600c637bfb63e61b03d mean there are current sql roles on prod where assignable_by is a sql and it needs to be updated to be a couch id? Or has the populate command not been run yet?

There are some references to `_id` in the UI, in `roles.js` and `roles_and_permissions.html`. Do those need to be switched to `couch_id`?

**Comment by snopoke** [comment]
@orangejenny great questions:

> Doesn't switching `assignable_by` to the couch id in [e291b04](https://github.com/dimagi/commcare-hq/commit/e291b040c45aadd8ac0df600c637bfb63e61b03d) mean there are current sql roles on prod where assignable_by is a sql and it needs to be updated to be a couch id? Or has the populate command not been run yet?

The data model has not changed, only what values are returned by `role.assignable_by`. Previously it was returning the list of SQL IDs, but now it's the list of Couch IDs. The underlying data doesn't change though.

> There are some references to `_id` in the UI, in `roles.js` and `roles_and_permissions.html`. Do those need to be switched to `couch_id`?

These are already using couch IDs : https://github.com/dimagi/commcare-hq/blob/58e0ab5d615b96a548cb21bd913895715ff2d408/corehq/apps/users/models_sql.py#L258-L259

**Review by orangejenny — APPROVED** [review]

**Comment by snopoke** [comment]
@orangejenny I realized I left out the django migration in this PR: added now: 57d9929d791

**Comment by snopoke** [comment]
`populate_user_role` migration has been run on production and india

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
