### PR TITLE
Fix stray case_details URLs

### PR DESCRIPTION
**Pull request by orangejenny**
Followup for https://github.com/dimagi/commcare-hq/pull/19922 - noticed app preview was broken locally. Should be merged before next deploy.

@proteusvacuum / @czue

### CODE REVIEW

**Review by czue — APPROVED** [review]

**Comment by czue** [comment]
do we feel like whatever allowed this to slip through the cracks the first time has now been covered? seems lucky that this got caught before anything went out but also makes me a little nervous there might be other instances that were missed.

**Comment by orangejenny** [comment]
@czue Yeah, nervousness seems warranted...I'll admit I didn't do my own full grep when reviewing the original PR and should have. Just did one. @proteusvacuum Looks like these files still reference the old `case_details` url name, maybe your original grep didn't include custom code or non-python files?
```
custom/_legacy/pact/reports/patient.py
custom/enikshay/templates/enikshay/duplicate_ids_report.html
corehq/apps/case_search/templates/case_search/case_search.html
corehq/apps/hqadmin/templates/hqadmin/callcenter_test.html
corehq/apps/locations/templates/locations/manage/location.html
```

**Comment by proteusvacuum** [comment]
oof, sorry about that. yes, I forgot to replace in html files :man_facepalming: 
Thanks for flagging.

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/19941

**Pull request merged**
