### PR TITLE
set ignore_malformed in settings and not mapping

### PR DESCRIPTION
**Pull request by snopoke**
From what I can tell (with local testing and looking at the prod index metadata) this setting has never been in effect since it wasn't in the right place. Post v1.0 ES raises an error if there are unknown fields in the mapping.

Since this hasn't been set before it seems like removing it would be the right thing to do. If we agree that's the way forward I'll update the PR. @esoergel @czue 

Docs for `ignore_malformed`
- 0.90: https://www.elastic.co/guide/en/elasticsearch/reference/0.90/mapping.html#mapping-settings
- latest: https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html

### CODE REVIEW

**Comment by esoergel** [comment]
That's unusual - we made a mistake which resulted in *increased* strictness!  Since we're doing fine with the stricter setting, my preference would be to stick with that - sounds like if anything, `ignore_malformed` would swallow errors we should know about.

**Comment by czue** [comment]
wild. agree with both of you that removing it seems right for now.

**Comment by czue** [comment]
fun stuff, the build is failing, likely because the [default legacy behavior](https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/pillowtop/listener.py#L546) is to take the md5 of the json mapping and return that as the unique id. since renaming the index would involve a reindex, I'd propose overriding `get_unique_id` to just return the current hash/index, and then making that explicit somewhere.

also, the pillow tests finally caught something useful! hooray.

**Comment by snopoke** [comment]
updated :white_check_mark:

**Comment by czue** [comment]
thanks for catching this!

**Pull request merged**
