### PR TITLE
update user index to new value

### PR DESCRIPTION
**Pull request by czue**
should hopefully fix build. @esoergel @emord

### CODE REVIEW

**Comment by snopoke** [comment]
Original cause: https://github.com/dimagi/commcare-hq/pull/9085

**Comment by czue** [comment]
arg, missed a couple references on the first go - ran tests locally this time though still good to wait for build

**Comment by czue** [comment]
:white_check_mark:

**Comment by esoergel** [comment]
Oh nice, thanks.  Sorry about that, I had no idea we referenced the full index names anywhere.

**Pull request merged**
