### PR TITLE
Removed a few Domain attributes

### PR DESCRIPTION
**Pull request by orangejenny**
Noticed a few unfamiliar attributes while working on something else, did some quick grepping.

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by snopoke** [comment]
Since this will trigger a domain reindex we may as well also remove the `_all` field by adding this to the mapping:
```json
'_all': {'enabled': False},
```

**Comment by snopoke** [comment]
There are some places that will need to updated in tests:
* testapps/test_pillowtop/tests/data/all-pillow-meta.json
* testapps/test_elasticsearch/tests/test_prod_es_indices.py

**Comment by orangejenny** [comment]
@snopoke Thanks, thought I had forgotten something. Updated.

**Review by biyeun — APPROVED** [review]

**Comment by mkangia** [comment]
what does changing the "_all" field achieve?

**Comment by snopoke** [comment]
@mkangia https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-all-field.html

**Comment by mkangia** [comment]
thanks @snopoke 
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/mapping-all-field.html#mapping-all-field
so this should be disabled on forms & cases etc as well because we always search on specific fields only?

**Comment by snopoke** [comment]
Yes that's correct. We are planning to reindex those indexes as well which is when we'll remove the field

**Comment by mkangia** [comment]
Do we need to update such usages before doing so?
https://github.com/dimagi/commcare-hq/blob/949627d77919c9dcc7b6133956425539cf7ae79a/corehq/apps/users/dbaccessors/all_commcare_users.py#L44

**Comment by snopoke** [comment]
no we don't, the `_all` field is only used if you explicitly specify it

**Comment by mkangia** [comment]
okay, thanks @snopoke

**Pull request merged**
