### PR TITLE
Fixed UCR help links

### PR DESCRIPTION
**Pull request by orangejenny**
##### FEATURE FLAG
UCR

##### PRODUCT DESCRIPTION
Fixes a few help links and removes the unused "Report Source" and "Data Source Source" buttons.

### CODE REVIEW

**Review by emord — APPROVED** [review]
How did you verify that they were unused?

**Comment by orangejenny** [comment]
@emord Google analytics. Which admittedly is only prod, but with usage that low I'm skeptical anyone is using them on india or elsewhere either. They're only useful if you use UCR but also don't have access to the raw doc page.

**Comment by emord** [comment]
That's probably fine to delete this one, but in general for "advanced" features, I think I'd expect them to get used relatively more on "enterprise" setups since we have a habit of implementing magic features for them

**Comment by orangejenny** [comment]
@emord sounds fine

**Comment by czue** [comment]
How did you check Google Analytics? I would expect us to log analytics on the page views since they are returning JSON. But maybe we have analytics on the buttons?

**Comment by czue** [comment]
whoops i made this comment on the wrong PR

**Comment by orangejenny** [comment]
@czue Good point. I was checking page usage, and since it showed some data I didn't think further about it. I can put them back.

**Pull request merged**
