### PR TITLE
Update clear_locations reference and fix spelling

### PR DESCRIPTION
**Pull request by esoergel**
Small bug I just noticed.  I added a reference to clear_locations and Cory renamed it clear_location_delegates at the same time.
@sravfeyn @anyone

### CODE REVIEW

**Comment by sravfeyn** [comment]
:+1: waiting for the build.

**Comment by sravfeyn** [comment]
@esoergel build fail is real - there is [some code](https://travis-ci.org/dimagi/commcare-hq/jobs/58730681#L1202) that points to `clear_locations_delgates` instead of `clear_location_delegates`

**Comment by sravfeyn** [comment]
Feel free to self-merge after the fix.

**Comment by czue** [comment]
oops. ditto what @sravfeyn said

**Pull request merged**
