### PR TITLE
Release show all scheduled reports from behind flag

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?272433

QA & UAT are done.

@czue / @dannyroberts

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]
🎉

**Review by czue — APPROVED** [review]
:rocket:

**Comment by dannyroberts** [comment]
Hey @xbryanc just thought you might like to know, we're releasing your feature to the public!

**Comment by xbryanc** [comment]
Thanks Danny, I'm very honored to have been able to contribute to this!

**Pull request merged**
