### PR TITLE
Catch type and zero division errors in UCR evaluator expression

### PR DESCRIPTION
**Pull request by NoahCarnahan**
http://manage.dimagi.com/default.asp?235729

cc @esoergel @millerdev

### CODE REVIEW

**Comment by czue** [comment]
:+1: on :white_check_mark:

**Comment by millerdev** [comment]
Intermittent test failure:
```
FAIL: test_transfer_first_doc_order (corehq.apps.commtrack.tests.test_xml.CommTrackBalanceTransferTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 399, in test_transfer_first_doc_order
    self.check_product_stock(self.sp, product, final, 0)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 228, in check_product_stock
    self.assertEqual(expected_soh, latest_trans.stock_on_hand)
AssertionError: Decimal('50.0') != 150
```

**Comment by millerdev** [comment]
same failure again. possibly real?

**Comment by NoahCarnahan** [comment]
This test has been failing intermittently for a while, and I don't see any way that this change could have caused it, so I've kicked the build again.

**Pull request merged**
