### PR TITLE
Location Reassignment validate parents

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/QA-1193
https://dimagi-dev.atlassian.net/browse/QA-1198

##### SUMMARY
Add validations to ensure parent assigned is at the expected location level

##### FEATURE FLAG
`LOCATION_REASSIGNMENT`

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by esoergel** [comment]
Flagging [again](https://github.com/dimagi/commcare-hq/pull/27079#issuecomment-611234458) that this all exists already in the bulk uploader:

> There's also LocationTreeValidator, which makes sure the bulk action doesn't do things like create duplicate site codes, or assign a location to a parent that isn't an appropriate type. Even if you're not able to reuse the exact code, it's worth looking over the validation that happens there to make sure you're replicating whatever's applicable here. (another one to check is whether this tool allows you to make sibling locations with the same name - that's prohibited elsewhere)

This PR adds one of the validations I mentioned, "assign a location to a parent that isn't an appropriate type"  What about the other two?  Does anything:

* Prevent uploading two locations with the same site code
* Prevent creating sibling locations with the same name

How about conflicts between a location specified in the upload and one that's not?


https://github.com/dimagi/commcare-hq/blob/ab37ff55dea523f55d61d3902b781d4f2d3add70/corehq/apps/locations/bulk_management.py#L498-L534

**Comment by mkangia** [comment]
Hey @esoergel 
I remember your comment on last PR about this one, I am working on code changes to realign / strengthen validations which will be a follow up PR and keeping this in mind, going to merge this to unblock QA

> Prevent uploading two locations with the same site code

We do check this for old and new site codes, and that they should repeat only when expected. For instance in case of a "Split" operation, the location getting split will be present in multiple rows. If they repeat for any other operation it would be an error. Similarly for new locations, in case of a "Merge", the new location would repeat for each row of old location.

> Prevent creating sibling locations with the same name
I see that is checked in the code you linked. It is not covered in the validations we have covered so far. Why is that an error though?

**Comment by esoergel** [comment]
> We do check this for old and new site codes, and that they should repeat only when expected.

:+1: 

Sibling locations with the same name are prohibited because there's no way to distinguish between them in the UI, such as report filters or on the locations list page.  Seems like it opens the door to confusion.  You can safely distinguish between two cities named Cambridge because they have different paths (Cambridge UK or Cambridge Massachusetts?), but if they shared a parent you'd need more information to tell which was which.

**Comment by mkangia** [comment]
@esoergel 
I see. That is not going to happen here because ICDS location names have location site code, but i will still try to add it so that we have all restriction applied as the bulk upload

**Pull request merged**
