### PR TITLE
handle missing itext

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?153671

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by snopoke** [comment]
build failure fixed by https://github.com/dimagi/commcare-hq/pull/5272

**Comment by NoahCarnahan** [comment]
Hey @snopoke,
Definitely good to prevent 500s here. I'm not sure what will happen if you try to do an upload of a translation for a form that was missing an `itext` node though. The bulk app translation upload logic assumes that the forms are already using itext node references for all labels. I haven't experimented with it extensively, but I think the upload won't work as expected in this case. If that's the case, we might want to throw an error when the user attempts the bulk app download (or upload).
Thoughts?

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by snopoke** [comment]
@NoahCarnahan I've added code to handle to upload side.

I think it's good to support this since it is supported in most other places in the code. It won't have any effect on the translations since the downloaded file doesn't have any translations for that form so there is nothing to translate.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
is the build fail real?

```
======================================================================
FAIL: test_localize (corehq.apps.app_manager.tests.test_xform_parsing.XFormParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_xform_parsing.py", line 31, in test_localize
    self.fail()
AssertionError: None
```

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by esoergel** [comment]
[XFormError: Can't find <itext>](https://travis-ci.org/dimagi/commcare-hq/jobs/47519204), looks real

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by snopoke** [comment]
@NoahCarnahan :white_check_mark:

**Comment by NoahCarnahan** [comment]
Thanks!

**Pull request merged**
