### PR TITLE
Cache reminder definition ids lookup

### PR DESCRIPTION
**Pull request by gcapalbo**
@czue @snopoke @esoergel 

Should fix the high view counts to `reminders/handlers_by_reminder_type`

Just want to test a couple things and this should be good to go

### CODE REVIEW

**Comment by czue** [comment]
sweet! didn't look closely yet, but curious if you considered `quickcache` for this and if so why it couldn't be used

**Comment by gcapalbo** [comment]
@czue I didn't think quickcache invalidates itself right?  Basically we want to make sure that we always get the latest list of reminder definition ids otherwise we won't setup the reminders correctly, so we can cache on the first lookup but also need to expire the cached value on reminder definition save.

**Comment by czue** [comment]
quickcache has a `skip` option that lets you circumvent the cache, but doesn't explicitly handle invalidation (though it will repopulate the cache with whatever got skipped). not sure if that would be suitable for this use case or not. even if it would work it's not clear to me that the code would be any cleaner so definitely seems fine to me to do what you're doing here

**Comment by esoergel** [comment]
There's a [`QuickCacheDocumentMixin`](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cachehq/mixins.py#L42) that hooks in to invalidation on `save`, `save_docs`, and `delete`.  Danny used it on a bulk getter here: https://github.com/dimagi/commcare-hq/pull/8669/files, and I just used it here: https://github.com/dimagi/commcare-hq/pull/8675

What you've done here looks good to me though, without introducing another ancestor into an already very large class, so both options seem fine to me.

**Comment by czue** [comment]
this is :+1: to merge from my side as soon as you're happy with it. assuming you'll ping/remove label when you're good

**Comment by gcapalbo** [comment]
@czue yup, just going to test out a couple things and then we should be good

**Comment by dannyroberts** [comment]
I'd echo cory and ethan's suggestions. I think quickcache + QuickCachedDocumentMixin would provide better invalidation (support for save_docs and delete) with less boilerplate.

```diff
- class CaseReminderHandler(Document):
+ class CaseReminderHandler(QuickCachedDocumentMixin, Document):
...
      @classmethod
+     @quickcache(['domain', 'reminder_type'])  # you can also set timeout and memoize_timeout
      def get_handler_ids(cls, domain, reminder_type_filter=None):
...
+     def clear_caches(self):
+         super(CaseReminderHandler, self).clear_caches()
+         self.get_handler_ids.clear(CaseReminderHandler, self.domain, self.reminder_type), 0)
+         self.get_handler_ids.clear(CaseReminderHandler, self.domain, None), 0)
```

**Comment by gcapalbo** [comment]
just to close the loop on this, this was implemented using quickcache in https://github.com/dimagi/commcare-hq/pull/10257

**Pull request closed without merging**
