### PR TITLE
Fix delay issue

### PR DESCRIPTION
**Pull request by sravfeyn**
Fixes the initial location delay issue when loading 'Edit Mobile Worker' page. [FB](http://manage.dimagi.com/default.asp?240625#1257616). Also does small refactor.

### CODE REVIEW

**Comment by sravfeyn** [comment]
@gcapalbo 
FYI @esoergel

**Review by gcapalbo — APPROVED** [review]

**Comment by gcapalbo** [comment]
looks good to me, will let @esoergel sign off

**Comment by esoergel** [comment]
`+27 −52` *and* a functionality improvement?  Nice!

**Comment by mkangia** [comment]
@sravfeyn was working on the same approach for the same issue.. https://github.com/dimagi/commcare-hq/pull/14010

**Comment by sravfeyn** [comment]
Ha, didn't realized I duplicated some effort, I grabbed it from Orgs trello.

**Comment by mkangia** [comment]
@sravfeyn No worries. I think your approach was much better and quick. I am glad you took a shot at it. 👍 Plus got a lot to learn in what i did as well. So its a win-win!

**Pull request merged**
