### PR TITLE
EWSGhana: reminders tester

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?157124#875671
Also, now reminders are using products assigned to location not all as before.

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by millerdev** [comment]
cannot be merged

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by kkrampa** [comment]
@millerdev

**Pull request merged**
