### PR TITLE
Add HIPAA compliant field

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?187532#1048498

I think this gets automatically added to the api, as it pulls `_doc` to generate properties (AFAIK).

@millerdev

### CODE REVIEW

**Comment by millerdev** [comment]
Test fail, not sure if related to this change. Also, I don't feel like I have enough context to merge this.

**Comment by czue** [comment]
looks good, thanks!

**Comment by proteusvacuum** [comment]
@czue I noticed that there is the `def _rewrite_file(self, pillow_configs)` method on the test class that was failing. When I ran that it overwrote all of the `couchdb_url`s in the `all-pillow-meta.json` file, with `http://{username}:{pass}:127.0.0.1(etc)`.
Curiously, the test with the changes I made above were still failing locally (but were passing with the changed urls). Not sure if that is indicative of something or not, but wanted to flag just in case.
I can look into it further if you think it warrants it.

**Comment by czue** [comment]
yeah that sounds expected. it's dependent on a few local settings, including your couch db server addres (and any credentials), db name, and `PILLOWTOP_MACHINE_ID`. 

i find this test to be hugely helpful for me to refactor pillowtop around and make sure I haven't broken/changed anything about our prod configs. that said, I've also noticed that it trips people up a lot when they rename/move things. It sort of still feels worth it to me, since the accidental introduction of an index or db name change would be pretty disastrous, but am open to feedback that this test should be changed/removed if people don't agree.

**Comment by czue** [comment]
more to your comment - I think it could be cleaned up to only check the database name and not the full URL pretty easily which would prevent the specific issue you ran into moving

**Comment by proteusvacuum** [comment]
ok, thanks. That's kind of what I figured which is why I didn't commit those changes.

**Pull request merged**
