### PR TITLE
Add user flags to feature flag summary page

### PR DESCRIPTION
**Pull request by orangejenny**
Added user-specific flags to the summary of domain-specific flags. Figured it'd be useful to be able to see both at one time, and that this combined view should still live in the domain app, since domain-specific flags are preferred over user-specific ones.

code friend @nickpell 

cc @amsagoff

Before:
screen shot 2015-08-04 at 1 33 21 pm

After:
screen shot 2015-08-04 at 1 31 19 pm

### CODE REVIEW

**Comment by amsagoff** [comment]
lovely!

**Comment by nickpell** [comment]
looks good pending tests

**Comment by dannyroberts** [comment]
Nice!

**Comment by czue** [comment]
:heart_eyes:

**Comment by benrudolph** [comment]
super cool! all the muggles will love it!

**Pull request merged**
