### PR TITLE
proper var name for import app

### PR DESCRIPTION
**Pull request by benrudolph**
@TylerSheffels accidentally broke this

### CODE REVIEW

**Comment by czue** [comment]
> @TylerSheffels accidentally broke this

looks like you're making accusations

**Comment by czue** [comment]
(no test coverage)

**Comment by benrudolph** [comment]
haha oops: i accidentally broke this**

**Comment by TylerSheffels** [comment]
https://www.youtube.com/watch?v=bCY9L3Xidoo @benrudolph

**Comment by benrudolph** [comment]
lol

**Pull request merged**
