### PR TITLE
don't load all apps from the DB when you only need one

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?212304 / http://manage.dimagi.com/default.asp?209460

@esoergel I think you meant to do this?

cc @proteusvacuum / anyone

### CODE REVIEW

**Comment by snopoke** [comment]
:boom:

**Comment by esoergel** [comment]
What!?  Does `.first()` really not do that already?  Should probably do the same for `get_latest_released_app_doc` just above this one too.

**Comment by esoergel** [comment]
https://github.com/dimagi/commcare-hq/pull/10134

**Comment by esoergel** [comment]
https://github.com/dimagi/commcare-hq/pull/10134

**Pull request merged**
