### PR TITLE
handle ascii gracefully

### PR DESCRIPTION
**Pull request by nickpell**
https://sentry.io/dimagi/commcarehq/issues/506856471/ / https://manage.dimagi.com/default.asp?273255

@emord

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by emord** [comment]
FWIW I tried that once, but it didn't seem to work. Unfortuantely since it's an intermittent failure, I don't think i'll be able to reproduce it

**Comment by nickpell** [comment]
@emord That makes sense - I converted other unicode strings to byte strings.  Most likely this was introduced in a py3 conversion script.

**Review by kaapstorm — APPROVED** [review]

**Comment by emord** [comment]
>  I converted other unicode strings to byte strings.

I think that I don't understand why this failed. any insight on why this wouldn't work as unicode? (can offline if that's easier)

**Comment by nickpell** [comment]
(offlined)

**Pull request merged**
