### PR TITLE
Update flag names

### PR DESCRIPTION
**Pull request by nickpell**
@NoahCarnahan cc: @calellowitz 

fixes http://manage.dimagi.com/default.asp?182154 upon deploy, no manual rebuild of data sources required.

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
It looks like her text editor used non-standard quote characters (`“`[U+201C] instead of `"`[U+0022]). Not sure if the yaml parser will choke on that or not, but might be worth replacing or trying to parse the file if you haven't already.

**Comment by NoahCarnahan** [comment]
(Feel free to self-merge if my comment is not an issue or you've resolved it)

**Comment by nickpell** [comment]
@NoahCarnahan Nice catch - the quotations were being included in the flag names in the data source.

Resolved now; self-merging.

**Comment by NoahCarnahan** [comment]
:+1:

**Pull request merged**
