### PR TITLE
Incorporate pt_PT translations into por

### PR DESCRIPTION
**Pull request by kaapstorm**
Recently a slew of Portuguese translations were done in Transifex, but the the "Portuguese (Portugal)" language (code "pt_PT") instead of to the "Portuguese" language (code pt").

This PR is an attempt to consolidate those new translations into our existing Portuguese translations.

Once this is merged, I can push back to Transifex, and try to drop or deprecate the "Portuguese (Portugal)" translations to avoid this in the future.

### CODE REVIEW

**Comment by kaapstorm** [comment]
(Cancelled build)

**Comment by kaapstorm** [comment]
I realise translations are normally merged without review. Also, I appreciate that while you are collectively fluent in French and Italian, Portuguese might not be your thing. I am deploying this to Staging, and the PM & partner will review. When I get an OK from them I will self-merge, if that's OK with y'all.

**Comment by kaapstorm** [comment]
Translations verified on Staging.

I've pushed the merged translations to Transifex as /"Portuguese"/"pt"/"por"/what CommCare HQ is configured to use, so they're going to be pulled into master the next time translations are updated.

Gonna close this PR.

**Review by proteusvacuum — COMMENTED** [review]
Obrigado :world_map:

**Pull request closed without merging**
