### PR TITLE
delete no longer used couch views

### PR DESCRIPTION
**Pull request by czue**
this is a PR into https://github.com/dimagi/commcare-hq/pull/8826/

unclear to me whether we want to do both at the same time or do this after that gets merged

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by snopoke** [comment]
to err on the side of caution we should not delete these until we know we don't need to roll back (not that rolling back is going to be much of an option but don't want to have to rebuild these under ANY circumstances)

**Comment by czue** [comment]
yeah good point.

**Comment by czue** [comment]
redoing PR to master

**Pull request closed without merging**
