### PR TITLE
Add Status Page Links

### PR DESCRIPTION
**Pull request by biyeun**
Adds status page links to 500 page and the help dropdown menu

screen shot 2019-03-05 at 4 47 55 pm
screen shot 2019-03-05 at 8 18 40 pm

### CODE REVIEW

**Comment by orangejenny** [comment]
That second screenshot is missing styles, could you post another?

**Comment by orangejenny** [comment]
It looks like the menu item is visible to enterprise environments, but the status page only shows production and india. Is that intentional?

**Comment by kishansampat** [comment]
@biyeun I also wanted to confirm whether you've added this to the blue maintenance page which shows when we're carrying out maintenance.

@orangejenny the status page is only for india and prod. So we should make sure it's not available on swiss, pna, icds

**Comment by biyeun** [comment]
@orangejenny whoops wrong screenshot. my internet has been crap the last day due to maintenance and that was a different screenshot of my 1995 experience

**Comment by biyeun** [comment]
@kishansampat https://github.com/dimagi/commcare-hq-errorpages/pull/15

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
