### PR TITLE
Combined FormBase and IndexedFormBase

### PR DESCRIPTION
**Pull request by orangejenny**
https://github.com/dimagi/commcare-hq/pull/22779#pullrequestreview-191727737

For some reason this feels risky, but it isn't really complicated.

@emord / @esoergel

### CODE REVIEW

**Review by emord — APPROVED** [review]
I agree this feels scarier than it should for something that just moves around code. Is it worth it to deploy to staging and create an app, release it, mess with some existing apps as a smoke test?

**Comment by orangejenny** [comment]
@emord Yeah, that's a good point. I'll do some more testing on staging and plan to release in a couple of days.

**Review by esoergel — APPROVED** [review]
Nice, it'd be great to reduce the number of classes in this hierarchy

**Comment by orangejenny** [comment]
This breaks something about the form's ability to find its `_parent`. On staging, if I create a new app and submit forms, that new app doesn't show in the app dropdown on submit history, and if I do find those forms in submit history, the "Form" column displays the xmlns instead of the form's name.

Debugged a bit but didn't get anywhere, don't think this is worth sinking more time into. Closing.

**Pull request closed without merging**
