### PR TITLE
support for repeat data in configurable reports

### PR DESCRIPTION
**Pull request by czue**
this is a bit of a monster, though the diff in the readme (https://github.com/dimagi/commcare-hq/commit/92b2eac08a7733667cc2b268a1ab61551321ba08) documents all the "user-facing" changes.

in addition to those there are a bunch of bits of mostly cleanup.

can read individual commits for details.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/apps/userreports/filters/__init__.py, line 4 - F401 'warnings' imported but unused
* corehq/apps/userreports/specs.py, line 1 - F401 'DictProperty' imported but unused
* corehq/apps/userreports/specs.py, line 1 - F401 'JsonObject' imported but unused
* corehq/apps/userreports/tests/test_app_manager_integration.py, line 28 - E501 line too long (118 > 115 characters)
* corehq/apps/userreports/tests/test_app_manager_integration.py, line 29 - E501 line too long (117 > 115 characters)
* corehq/apps/userreports/tests/test_app_manager_integration.py, line 30 - E501 line too long (118 > 115 characters)
* corehq/apps/userreports/tests/test_data_source_repeats.py, line 11 - E302 expected 2 blank lines, found 1

**Comment by czue** [comment]
@snopoke @nickpell @NoahCarnahan have fun :)

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
(build fail is unrelated - I ran UCR tests locally)

**Comment by NoahCarnahan** [comment]
Looks good.

**Pull request merged**
