### PR TITLE
ILSGateway, EWSGhana changes

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?148847#837455
http://manage.dimagi.com/default.asp?134684#831319
http://manage.dimagi.com/default.asp?148852#831253
changes in checkpoint according to discussion in google group.  
@czue @twymer

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 15 errors:

* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 2 - F401 'datetime' imported but unused
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 5 - F401 'models' imported but unused
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 7 - E302 expected 2 blank lines, found 1
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 10 - W293 blank line contains whitespace
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 20 - E501 line too long (124 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 25 - E303 too many blank lines (2)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 26 - W293 blank line contains whitespace
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 31 - E303 too many blank lines (2)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 31 - F811 redefinition of unused 'models' from line 5
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 40 - E501 line too long (131 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 43 - E501 line too long (130 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 45 - E501 line too long (132 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 48 - E501 line too long (161 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 51 - E501 line too long (150 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 71 - E501 line too long (132 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 2 - F401 'datetime' imported but unused
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 5 - F401 'models' imported but unused
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 7 - E302 expected 2 blank lines, found 1
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 10 - W293 blank line contains whitespace
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 20 - E501 line too long (124 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 25 - E303 too many blank lines (2)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 26 - W293 blank line contains whitespace
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 31 - E303 too many blank lines (2)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 31 - F811 redefinition of unused 'models' from line 5
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 40 - E501 line too long (131 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 43 - E501 line too long (130 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 45 - E501 line too long (132 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 48 - E501 line too long (161 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 51 - E501 line too long (150 > 115 characters)
* custom/logistics/migrations/0002_add_model_StockDataCheckpoint.py, line 71 - E501 line too long (132 > 115 characters)

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
closing as per @kkrampa's request

**Pull request closed without merging**
