### PR TITLE
Add last_modified to case list properties

### PR DESCRIPTION
**Pull request by wpride**
I have no idea if this is actually this straightforward but worked for me and seems correct to have this property @orangejenny @emord possibly?

### CODE REVIEW

**Comment by wpride** [comment]
screen shot 2016-12-14 at 8 21 28 am

**Review by czue — APPROVED** [review]
nice little quick PI! 

looks good to me though will let someone else confirm if this isn't right.

**Comment by orangejenny** [comment]
looks good to me

**Comment by emord** [comment]
Unrelated, but why doe `#owner_name` have a # ?

**Comment by czue** [comment]
guessing, but i think because it's magic that resolves to something fancy and we need a way to differentiate that from a property named `owner_name`

**Pull request merged**
