### PR TITLE
always use touchforms case list filters in cloudcare on sql

### PR DESCRIPTION
**Pull request by czue**
@benrudolph @snopoke - should avoid the case filter hack mentioned in https://github.com/dimagi/commcare-hq/pull/11231

### CODE REVIEW

**Comment by benrudolph** [comment]
haha nice this is probably way easier than making people make a filter. thanks. 👢 🚧

**Comment by czue** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
@czue up with the birds 🌄

**Comment by czue** [comment]
:bird:

**Pull request merged**
