### PR TITLE
Pull some models out of UNKNOWN in the domain dump test

### PR DESCRIPTION
**Pull request by esoergel**
## Technical Summary

In the spirit of https://github.com/dimagi/commcare-hq/pull/32078/files

### Safety story
Minor change

### Automated test coverage
included

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by esoergel** [comment]
Finally dealt with the merge conflicts here - should be good to merge now

**Comment by esoergel** [comment]
pinging for re-review since it's been a minute and I changed some stuff @snopoke @AddisonDunn @Robert-Costello

**Review by AddisonDunn — APPROVED** [review]
Maybe merge master before merging though?

**Comment by esoergel** [comment]
offlined to clarify that I'd recently rebased off latest master

**Pull request merged**
