### PR TITLE
kill OldPermissions and migration

### PR DESCRIPTION
**Pull request by czue**
@dannyroberts 

follow up from https://github.com/dimagi/commcare-hq/pull/10051

### CODE REVIEW

**Comment by czue** [comment]
:white_check_mark: / :arrow_up: :four_leaf_clover: :fist:

**Comment by snopoke** [comment]
:arrow_up: translation required

**Comment by czue** [comment]
:up: : up
:four_leaf_clover: for
:fist: grabs

**Comment by benrudolph** [comment]
:heart: :bulb:

**Comment by dannyroberts** [comment]
:tada:

**Pull request merged**
