### PR TITLE
ICDS Dashboard: select all filter option for Child Growth Monitoring Tabular Report

### PR DESCRIPTION
**Pull request by saiprakash-v**
https://app.asana.com/0/1172925702295169/1167686585490809
##### SUMMARY

This PR adds "Select All" check box for the "Child Growth Monitoring" Tabular Report

Screenshot from 2020-05-08 16-34-20

### CODE REVIEW

**Review by czue — APPROVED** [review]
Code looks good. Did you get any guidance on the UX? I find the checkbox off to the right to be in a weird place and would think just putting it at the top of the list (or above it) might be more intuitive.

**Comment by saiprakash-v** [comment]
> Code looks good. Did you get any guidance on the UX? I find the checkbox off to the right to be in a weird place and would think just putting it at the top of the list (or above it) might be more intuitive.

I Agree. Made the change

**Review by czue — APPROVED** [review]
thanks

**Comment by czue** [comment]
this PR will also need to be updated @msienkiewicz

**Pull request merged**
