### PR TITLE
Respect the `wrap` parameter

### PR DESCRIPTION
**Pull request by kaapstorm**
@nickpell @snopoke

### CODE REVIEW

**Comment by kaapstorm** [comment]
For a little context @nickpell this fixes a bug where `FormProcessorCouch.hard_rebuild_case()` was expecting `FormProcessorCouch.get_case_with_lock()` to return a `CommCareCase` instance, but instead was getting a dict.

**Comment by snopoke** [comment]
I think you still need to pass in `wrap=True` to the call in `FormProcessorCouch.hard_rebuild_case()`

**Comment by kaapstorm** [comment]
:white_check_mark:

**Review by snopoke — COMMENTED** [review]
Since I wrote some of this I'll let @nickpell approve

**Pull request merged**
