### PR TITLE
update static UCRs

### PR DESCRIPTION
**Pull request by mkangia**
Implements changes for first three in https://dimagi-dev.atlassian.net/browse/ICDS-1062,
Please refer "UCR Fixes for MPR - updated.docx"

### CODE REVIEW

**Comment by mkangia** [comment]
2 of these are changes to reports but one is change to data source, this needs to be rolled out differently? making a new data source, letting it populate and then change reports etc or we just rebuild in place or something?

**Review by Rohit25negi — APPROVED** [review]

**Review by calellowitz — APPROVED** [review]

**Comment by calellowitz** [comment]
No need to roll it out separately, but you will have to rebuild manually (or just backfill that column if possible). This is a massive data source so it will be quite tough to do though

**Comment by mkangia** [comment]
thanks @calellowitz 

rebuild would destroy the table and recreate it right? which we can't do
backfill would mean running a query to fix the values for that column because its not a new one but an existing one?

**Comment by emord** [comment]
`attended_children` is already its own column https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/ucr/data_sources/daily_feeding_forms.json#L393 so you could loop through all the supervisor_ids and run something like:

```
UPDATE "daily_feeding_form_table" SET
   open_pse_count = 0
WHERE supervisor_id = 'supervisor_id' and submitted_on >= '2019-10-01' and attended_children = 0
```

(suggesting this query because there's an index on supervisor_id and submitted_on and we probably don't actually care about updating the data older than october)

**Comment by mkangia** [comment]
Thanks @emord 
Merging it and will run that post next deploy.

**Comment by mkangia** [comment]
@calellowitz can you suggest how to implement what Emord suggested.
running the update for each supervisor id?

Noting down some stats to help decide

```
SELECT count(*)
FROM "ucr_icds-cas_static-daily_feeding_forms_85b1167f"
WHERE attended_children = 0 AND open_pse_count = 1;

15,67,381
```

```
SELECT count(*)
FROM "ucr_icds-cas_static-daily_feeding_forms_85b1167f"
WHERE attended_children = 0 AND open_pse_count = 1 and submitted_on >= '2019-10-01';

4,85,842
```

```
EXPLAIN UPDATE "ucr_icds-cas_static-daily_feeding_forms_85b1167f"
SET open_pse_count = 0
WHERE submitted_on >= '2019-10-01' AND attended_children = 0;

 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 64
   Tasks Shown: One of 64
   ->  Task
         Node: host=100.71.184.232 port=6432 dbname=icds_ucr
         ->  Update on "ucr_icds-cas_static-daily_feeding_forms_85b1167f_104378" "ucr_icds-cas_static-daily_feeding_forms_85b1167f"  (cost=0.43..65852.72 rows=34027 width=364)
               ->  Index Scan using "ix_ucr_icds-cas_static-daily_feeding_forms_85b1_beee54e4_104378" on "ucr_icds-cas_static-daily_feeding_forms_85b1167f_104378" "ucr_icds-cas_static-daily_feeding_forms_85b1167f"  (cost=0.43..65852.72 rows=34027 width=364)
                     Index Cond: (submitted_on >= '2019-10-01'::date)
                     Filter: (attended_children = 0)
(9 rows)
```

```
EXPLAIN UPDATE "ucr_icds-cas_static-daily_feeding_forms_85b1167f"
SET open_pse_count = 0
WHERE supervisor_id = 'supervisor_id' and submitted_on >= '2019-10-01' AND attended_children = 0;

 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=100.71.184.224 port=6432 dbname=icds_ucr
         ->  Update on "ucr_icds-cas_static-daily_feeding_forms_85b1167f_104440" "ucr_icds-cas_static-daily_feeding_forms_85b1167f"  (cost=0.55..12.86 rows=1 width=365)
               ->  Index Scan using "ix_ucr_icds-cas_static-daily_feeding_forms_85b1167_06644_104440" on "ucr_icds-cas_static-daily_feeding_forms_85b1167f_104440" "ucr_icds-cas_static-daily_feeding_forms_85b1167f"  (cost=0.55..12.86 rows=1 width=365)
                     Index Cond: ((supervisor_id = 'supervisor_id'::text) AND (submitted_on >= '2019-10-01'::date))
                     Filter: (attended_children = 0)
(9 rows)
```

**Comment by mkangia** [comment]
Updated all records, took roughly 4 minutes
i think it would have been better to run 
`UPDATE "ucr_icds-cas_static-daily_feeding_forms_85b1167f" SET open_pse_count = 0 WHERE attended_children = 0 and open_pse_count=1`
so that it would have attempted to update exactly the rows needed.

```
icds_ucr=# UPDATE "ucr_icds-cas_static-daily_feeding_forms_85b1167f" SET open_pse_count = 0 WHERE attended_children = 0;
UPDATE 10831331
icds_ucr=# SELECT count(*)
FROM "ucr_icds-cas_static-daily_feeding_forms_85b1167f"
WHERE attended_children = 0 AND open_pse_count = 1;
 count
-------
     0
(1 row)
```
fyi @calellowitz

**Pull request merged**
