### PR TITLE
have chat.html extend minimal base template

### PR DESCRIPTION
**Pull request by czue**
[One commit](https://github.com/dimagi/commcare-hq/commit/0c4eba2900d987332349931fe63ef0e7793ae094) on top of https://github.com/dimagi/commcare-hq/pull/25963

@orangejenny  do you have any guidance on how I can test this didn't break anything? or maybe @millerdev since it's SMS chat functionality?

### CODE REVIEW

**Comment by orangejenny** [comment]
If you deploy to staging you can test on https://staging.commcarehq.org/a/gc-staging/sms/chat_contacts/ (as I say that I realize this should be written down, will add a README to the sms app).

**Comment by orangejenny** [comment]
@czue Found some SMS docs on readthedocs, but that doesn't seem like the right place to put 
the name of a test domain (really, neither is a README checked into the codebase). Where would you think to look for this info?

**Comment by czue** [comment]
thanks @orangejenny 

> Where would you think to look for this info?

Is a good question. In full transparency I didn't really look at all as I figured someone on the team would know and it wasn't time sensitive. If I didn't get any positive inputs I would have gone to the SMS docs on confluence and combined with the code figured out the necessary steps to get a local version of the chat running (I got to the point of needing to create a contact, thought that it was likely the case that involved submitting a case of a particular type with certain properties, and then bailed out and decided to ask on the PR). Though that's not an answer to the best place to figure out where to put the staging documentation....

Maybe if we had a confluence page for features/areas of the codebase you can test on staging mapped to domains / links or something? (don't love that just don't have a better idea)

**Comment by czue** [comment]
Anyways, closing this PR since we've decided to make the base template custom to ICDS

**Comment by orangejenny** [comment]
@czue Thanks for the thoughtful response. That `gc-staging` link is something I have saved locally from an old chat with Giovanni and I don't know if anyone else on the team knows it exists, so sharing it flagged my "wait, this should be somewhere more public" alarm. But maybe I'm overthinking it and creating a contact locally isn't a big deal - I had the same experience as you a while back of digging through the code and then deciding it was simpler to ask Gio. Anyway, I'll follow up with QA to see if they have a repository of this kind of knowledge.

**Pull request closed without merging**
