### PR TITLE
Set file encoding

### PR DESCRIPTION
**Pull request by kaapstorm**
Addresses Travis failure. ([FB 230333](http://manage.dimagi.com/default.asp?230333))

The test didn't fail the same way locally, but this fixed them, and I suspect the cause might be the same. (Also dropped shebang because this file never gets executed directly.)

@sravfeyn @czue

### CODE REVIEW

**Comment by czue** [comment]
nice find! :+1: on :white_check_mark:

**Comment by czue** [comment]
(introduced in https://github.com/dimagi/commcare-hq/commit/eb45f828ab85e182ffa61c493835ea81ff0eddc8)

**Comment by benrudolph** [comment]
Ah! I caused it myself! Nice find sorry about that totally did not expect that

**Comment by kaapstorm** [comment]
No worries. It turns out Guido van Rossum likes vim modelines (a.k.a. weird vim thing), and accommodated them in [PEP 263][1] "Source Code Encodings". (See "Defining the Encoding".)

  [1]: https://www.python.org/dev/peps/pep-0263/

**Comment by benrudolph** [comment]
that's fascinating and somewhat unintuitive. you'd think something prefixed with `vim:` would only affect the vim editor

**Comment by proteusvacuum** [comment]
Interesting! you can also use:
`# This python file uses the following encoding: utf-8`
Or something like:
`# This file has some characters that could look strange if you don't use encoding: utf-8`

**Pull request merged**
