### PR TITLE
Cache already compressed files

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts D🐶 this'll shave 10 or so minutes off of deploy 😮 . gonna give this a go on staging first of course, but essentially this does the following:
1. do not rebuild compressed JS file if it already exists since the hash is based on the contents of the file
2. copy over staticfiles from previous release
3. purge any files in the staticfiles dir that do not exist in the `manifest.json`

cc: @sravfeyn @proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
:open_mouth: :clap:

**Comment by czue** [comment]
wow! :floppy_disk: :watch: :moneybag:

**Comment by benrudolph** [comment]
fast deploys are ready when you are! ✅

**Comment by sravfeyn** [comment]
Nice! Will let @dannyroberts review and merge

**Comment by dannyroberts** [comment]
⚡

**Pull request merged**
