### PR TITLE
Don't fail when stock state doesn't exist

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?221032#1106808

### CODE REVIEW

**Comment by gcapalbo** [comment]
(asked Mike if there should be an error message response here)

**Comment by kkrampa** [comment]
@gcapalbo Updated

**Comment by gcapalbo** [comment]
looks good, just pending one question i posed to Mike in that ticket

**Comment by kkrampa** [comment]
@gcapalbo Updated

**Pull request merged**
