### PR TITLE
Bump up z-index of top-nav

### PR DESCRIPTION
**Pull request by proteusvacuum**
Places long tab-lists above footer, but now it get's truncated by the end of the browser window, not sure what the desired option is (need to scroll down either way...)
http://manage.dimagi.com/default.asp?187328#1047428
@biyeun I just randomly picked number above the footer's z-index. Not sure if there is a science to how that is done normally... 
cc: @millerdev

### CODE REVIEW

**Comment by orangejenny** [comment]
Food for thought on z-index: https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06#.6u5ehz31w (Ctrl+F "The 2nd Project: Scales")

(we don't have anything like this I don't think, it's on my theoretical backlog)

**Comment by millerdev** [comment]
Cool article @orangejenny. Good stuff in there.

Did anyone else find this juxtaposition in the first style guide ... interesting?

> Page level overrides should be minimal and under a single page level class nest.
> 
> ```less
.home-page {
  .nav {
    margin-top: 10px;
  }
}
```
> ## Nesting
>
> Don't nest. Ever.

**Comment by NoahCarnahan** [comment]
Good read, thanks @orangejenny !

**Comment by orangejenny** [comment]
> juxtaposition

ha, I didn't notice that contradiction. I don't agree with him that nesting is bad practice - I think it's a major advantage of LESS - but agree with most of the rest of his recommendations.

**Comment by millerdev** [comment]
> I don't agree with him that nesting is bad practice

Did you notice that the nesting section is missing from the final version of his style guide?

**Comment by orangejenny** [comment]
ah, looks like it's in the first style guide but not the second one. goody.

**Comment by biyeun** [comment]
regardless of that article, this looks good

**Comment by czue** [comment]
z-index scale seems pretty legit

**Pull request merged**
