### PR TITLE
ValueSource documentation

### PR DESCRIPTION
**Pull request by kaapstorm**
## Summary

Adds documentation for the ValueSource module.

Part of a larger effort to add documentation for integrations.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Safety story

Only documentation

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by proteusvacuum — APPROVED** [review]
Do you think this would be good to have in ReadTheDocs?

**Comment by kaapstorm** [comment]
It is in ReadTheDocs ... It gets [included here](https://github.com/dimagi/commcare-hq/blame/89678e2264d54557c8133fef3a3629fdca72231f/corehq/motech/openmrs/docs/index.rst#L1109) ... but! Thank you for asking, because that's not a great place to include it! I'll move it.

**Review by esoergel — APPROVED** [review]
In case helpful, I recently added some quick guidance on troubleshooting autodoc builds and running it locally:
https://commcare-hq.readthedocs.io/documenting.html#troubleshooting
(I didn't see any indication that this failed, just seemed like a good excuse to plug that :laughing: )

**Comment by kaapstorm** [comment]
When I looked into moving the docs around in ReadTheDocs, I discovered existing docs to merge the new docs into. I think the flow is a bit better now, and links directly off the top level, under Integrations:
image

... It makes me want to move DHIS2 and FHIR docs around too now. Maybe later.

**Comment by proteusvacuum** [comment]
Thanks for the update!

**Pull request merged**
