### PR TITLE
Remove sms design docs

### PR DESCRIPTION
**Pull request by gcapalbo**
Removes 7 couch views which are no longer needed.

@dannyroberts I remember you had mentioned one time that this wouldn't cause a reindex because we're deleting all of the views in the app (although I will just need to run the prune views command).

This also removes a filter.  Do you know if this PR will cause any bad side effects, or should we wait until the weekend to merge?

cc @calellowitz

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
build fail looks real:
```
  File "manage.py", line 96, in <module>
    execute_from_command_line(sys.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/vendor/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/vendor/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/vendor/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/vendor/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/vendor/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/mnt/corehq/sql_db/operations.py", line 27, in database_forwards
    super(HqOpMixin, self).database_forwards(app_label, schema_editor, from_state, to_state)
  File "/vendor/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/mnt/corehq/apps/smsbillables/migrations/0002_bootstrap.py", line 52, in bootstrap_sms
    get_preindex_plugin('sms').sync_design_docs()
AttributeError: 'NoneType' object has no attribute 'sync_design_docs'
```

**Comment by dannyroberts** [comment]
Can you tell if this error is related or not?
```
======================================================================
ERROR: test_get_call_center_domains (corehq.apps.callcenter.tests.test_utils.CallCenterDomainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/apps/callcenter/tests/test_utils.py", line 347, in test_get_call_center_domains
    _create_domain('cc-dom1', True, True, 'flw')
  File "/mnt/corehq/apps/callcenter/tests/test_utils.py", line 376, in _create_domain
    doc=domain.to_json(),
  File "/mnt/corehq/elastic.py", line 54, in send_to_elasticsearch
    doc_exists = doc_exists_in_es(index, doc_id)
  File "/mnt/corehq/elastic.py", line 44, in doc_exists_in_es
    return get_es_new().exists(es_meta.index, es_meta.type, doc_id)
  File "/vendor/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/vendor/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 290, in exists
    id), params=params)
  File "/vendor/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/vendor/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/vendor/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(503, u'')
----------------------------------------------------------------------
```

**Comment by dannyroberts** [comment]
Ah, same error in https://github.com/dimagi/commcare-hq/pull/11725#issuecomment-221275717 so probably not

**Comment by dannyroberts** [comment]
(try merging master?)

**Comment by czue** [comment]
that error can be resolved by :boot: ing it a few times. I think @snopoke mentioned he might be looking into root cause

**Comment by snopoke** [comment]
Wait for https://github.com/dimagi/commcare-hq/pull/11720

**Comment by gcapalbo** [comment]
:white_check_mark:

**Comment by czue** [comment]
:skull:

**Comment by dannyroberts** [comment]
🎉 Let's see what https://app.datadoghq.com/dash/105160/app-builder-pageloads?live=true&page=0&is_auto=false&from_ts=1463592739038&to_ts=1464197539038&tile_size=m looks like in a week! I no longer have a good feel for what the incremental gain of removing e.g. 7 views is now that our cluster's more stable, so this'll be a good measurement

**Comment by dannyroberts** [comment]
Looking at the data after a week:

| Area | May 19-May 26 | May 26-Jun 2 | Change (s) | Change (%) |
|------|------|------|-------|--------|
| App Settings Page | 1.64 | 1.52 | -0.12 | -7.32% |
| Module Page | 2.25 | 2.04 | -0.21 | -9.33% |
| Form Page | 2.38 | 2.77 | +0.39  | +16.39% |
| Formbuilder | 4.73 | 4.68 | -0.05 | -1.06% |
| All of HQ | 4.19 | 4.02 | -0.17 | -4.06% |

So as you can see overall, request response times went down across HQ and different specific pages in app builder, with a notable exception of the form page. I'm tempted to attribute the overall improvement in response time to removing 7 views, and the increase in average response time of the form page to "chance" (like heavy edits over the week on a particular form whose validation takes longer than average) and/or code changes on that particular page. (That is of course an interpretation that's very biased by what I wanted to see in the first place.)

**Comment by dannyroberts** [comment]
In a classic turn of events, Giovanni told me he hasn't actually deleted those 7 views yet, but is doing so today. So (1) my interpretation of the data was totally wrong (2) this shows how biased I am in interpreting data to fit what I expect and (3) I'll run this again in another week. I have no explanation for why our pageload times went down this last week, but even if I did, it would probably be incorrect as well.

**Comment by snopoke** [comment]
Lol! Sorry Danny but that's really funny.

**Comment by czue** [comment]
:trollface:

**Comment by dannyroberts** [comment]
This time I'm not going to make any comments. The intention here is that the first period (copied from above) is before deleting these views and the second period is after.

| Area              | May 26-Jun 2 | Jun 2-Jun-9 | Change (s) | Change (%) |
|-------------------|--------------|-------------|------------|------------|
| App Settings Page | 1.52         | 1.29        | -0.23      | -15.13%    |
| Module Page       | 2.04         | 2.38        | 0.34       | 16.67%     |
| Form Page         | 2.77         | 2.74        | -0.03      | -1.08%     |
| Formbuilder       | 4.68         | 4.52        | -0.16      | -3.42%     |
| All of HQ         | 4.02         | 3.67        | -0.35      | -8.71%     |

**Pull request merged**
