### PR TITLE
Revert "Remove unused imports"

### PR DESCRIPTION
**Pull request by benrudolph**
Reverts dimagi/commcare-hq#10904

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 296 errors:

* corehq/apps/accounting/async_handlers.py, line 9 - F401 'WebUser' imported but unused
* corehq/apps/accounting/decorators.py, line 3 - F401 'messages' imported but unused
* corehq/apps/accounting/decorators.py, line 4 - F401 'force_unicode' imported but unused
* corehq/apps/accounting/decorators.py, line 5 - F401 'mark_safe' imported but unused
* corehq/apps/accounting/decorators.py, line 6 - F401 'ugettext' imported but unused
* corehq/apps/accounting/decorators.py, line 8 - F401 'SoftwarePlanVisibility' imported but unused
* corehq/apps/accounting/decorators.py, line 10 - F401 'Http404' imported but unused
* corehq/apps/accounting/generator.py, line 12 - F401 'add_months' imported but unused
* corehq/apps/accounting/management/commands/2014_06_30_recalc_sms_line_items.py, line 1 - F401 'make_option' imported but unused
* corehq/apps/accounting/tasks.py, line 23 - F401 'utils' imported but unused
* corehq/apps/accounting/tests/test_autopay.py, line 1 - F401 'datetime' imported but unused
* corehq/apps/accounting/tests/test_autopay.py, line 2 - F401 'random' imported but unused
* corehq/apps/accounting/tests/test_invoicing.py, line 6 - F401 'call_command' imported but unused
* corehq/apps/accounting/views.py, line 70 - F401 'toggles' imported but unused
* corehq/apps/api/object_fetch_api.py, line 3 - F401 'ResourceNotFound' imported but unused
* corehq/apps/api/object_fetch_api.py, line 11 - F401 'XFormInstance' imported but unused
* corehq/apps/app_manager/download_urls.py, line 1 - F401 'include' imported but unused
* corehq/apps/app_manager/download_urls.py, line 2 - F401 'media_download_urls' imported but unused
* corehq/apps/app_manager/fields.py, line 2 - F401 'settings' imported but unused
* corehq/apps/app_manager/fields.py, line 11 - F401 'Application' imported but unused
* corehq/apps/app_manager/fields.py, line 14 - F401 'XFormInstance' imported but unused
* corehq/apps/app_manager/fixtures/mobile_ucr.py, line 9 - F401 'Application' imported but unused
* corehq/apps/app_manager/management/commands/download_app_forms.py, line 4 - F401 'RemoteApp' imported but unused
* corehq/apps/app_manager/suite_xml/post_process/instances.py, line 3 - F401 'UnknownInstanceError' imported but unused
* corehq/apps/app_manager/tests/test_bulk_ui_translation.py, line 1 - F401 'codecs' imported but unused
* corehq/apps/app_manager/tests/test_bulk_ui_translation.py, line 3 - F401 'os' imported but unused
* corehq/apps/app_manager/tests/test_child_module.py, line 3 - F401 'APP_V2' imported but unused
* corehq/apps/app_manager/util.py, line 5 - F401 'itertools' imported but unused
* corehq/apps/app_manager/views/app_summary.py, line 3 - F401 'method_decorator' imported but unused
* corehq/apps/builds/views.py, line 8 - F401 'TemplateView' imported but unused
* corehq/apps/callcenter/tests/sql_fixture.py, line 5 - F401 'settings' imported but unused
* corehq/apps/callcenter/tests/sql_fixture.py, line 6 - F401 'make_url' imported but unused
* corehq/apps/callcenter/tests/sql_fixture.py, line 7 - F401 'date' imported but unused
* corehq/apps/callcenter/tests/test_indicator_fixture.py, line 4 - F401 'pytz' imported but unused
* corehq/apps/callcenter/tests/test_indicators.py, line 3 - F401 'V2' imported but unused
* corehq/apps/callcenter/tests/test_indicators.py, line 4 - F401 'MONTH1' imported but unused
* corehq/apps/casegroups/models.py, line 3 - F401 'CommCareCase' imported but unused
* corehq/apps/casegroups/models.py, line 5 - F401 'Document' imported but unused
* corehq/apps/casegroups/models.py, line 6 - F401 'iter_docs' imported but unused
* corehq/apps/cleanup/models.py, line 1 - F401 'models' imported but unused
* corehq/apps/commtrack/management/commands/check_product_migration.py, line 6 - F401 'iter_docs' imported but unused
* corehq/apps/commtrack/management/commands/check_product_migration.py, line 7 - F401 'datetime' imported but unused
* corehq/apps/commtrack/models.py, line 6 - F401 '_' imported but unused
* corehq/apps/commtrack/models.py, line 13 - F401 'get_case_updates' imported but unused
* corehq/apps/commtrack/sms.py, line 24 - F401 'V2' imported but unused
* corehq/apps/commtrack/util.py, line 17 - F401 'V2' imported but unused
* corehq/apps/dashboard/views.py, line 3 - F401 'method_decorator' imported but unused
* corehq/apps/data_interfaces/dispatcher.py, line 7 - F401 'PermissionDenied' imported but unused
* corehq/apps/data_interfaces/tests/tests.py, line 19 - F401 'generator' imported but unused
* corehq/apps/data_interfaces/views.py, line 14 - F401 'BulkUploadForm' imported but unused
* corehq/apps/data_interfaces/views.py, line 33 - F401 'DataInterfaceDispatcher' imported but unused
* corehq/apps/data_interfaces/views.py, line 38 - F401 'CaseReassignmentInterface' imported but unused
* corehq/apps/domain/calculations.py, line 10 - F401 'iso_string_to_datetime' imported but unused
* corehq/apps/domain/calculations.py, line 11 - F401 'ApplicationBase' imported but unused
* corehq/apps/domain/calculations.py, line 24 - F401 'make_form_couch_key' imported but unused
* corehq/apps/domain/decorators.py, line 23 - F401 'has_privilege' imported but unused
* corehq/apps/domain/decorators.py, line 36 - F401 'privileges' imported but unused
* corehq/apps/domain/forms.py, line 1 - F401 'copy' imported but unused
* corehq/apps/domain/forms.py, line 77 - F401 'BootstrapDisabledInput' imported but unused
* corehq/apps/domain/management/commands/delete_domain.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/domain/management/commands/remove_duplicate_domains.py, line 1 - F401 'defaultdict' imported but unused
* corehq/apps/domain/middleware.py, line 5 - F401 'method_decorator' imported but unused
* corehq/apps/domain/middleware.py, line 6 - F401 'sensitive_post_parameters' imported but unused
* corehq/apps/domain/models.py, line 21 - F401 'connection' imported but unused
* corehq/apps/domain/tests/test_views.py, line 10 - F401 'toggles' imported but unused
* corehq/apps/domainsync/management/commands/copy_case.py, line 2 - F401 'Database' imported but unused
* corehq/apps/es/tests/test_esquery.py, line 6 - F401 'ESQuerySet' imported but unused
* corehq/apps/export/custom_export_helpers.py, line 2 - F401 'toggle_enabled' imported but unused
* corehq/apps/export/custom_export_helpers.py, line 3 - F401 'PermissionDenied' imported but unused
* corehq/apps/export/custom_export_helpers.py, line 8 - F401 'export' imported but unused
* corehq/apps/fixtures/models.py, line 1 - F401 'Decimal' imported but unused
* corehq/apps/fixtures/models.py, line 19 - F401 'LOCATION_REPORTING_PREFIX' imported but unused
* corehq/apps/hqadmin/escheck.py, line 2 - F401 'datetime' imported but unused
* corehq/apps/hqadmin/escheck.py, line 6 - F401 'itertools' imported but unused
* corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py, line 5 - F401 'sys' imported but unused
* corehq/apps/hqadmin/management/commands/cchq_prbac_bootstrap.py, line 12 - F401 'mail_admins' imported but unused
* corehq/apps/hqadmin/management/commands/fix_checkpoint_after_rewind.py, line 1 - F401 'datetime' imported but unused
* corehq/apps/hqadmin/management/commands/fix_checkpoint_after_rewind.py, line 3 - F401 'pytz' imported but unused
* corehq/apps/hqadmin/management/commands/list_deploys.py, line 1 - F401 'timedelta' imported but unused
* corehq/apps/hqadmin/reporting/reports.py, line 32 - F401 'Sum' imported but unused
* corehq/apps/hqadmin/reports.py, line 4 - F401 'use_bootstrap3' imported but unused
* corehq/apps/hqadmin/reports.py, line 4 - F401 'use_datatables' imported but unused
* corehq/apps/hqadmin/reports.py, line 4 - F401 'use_jquery_ui' imported but unused
* corehq/apps/hqadmin/system_info/checks.py, line 6 - F401 'human_bytes' imported but unused
* corehq/apps/hqadmin/system_info/utils.py, line 4 - E303 too many blank lines (3)
* corehq/apps/hqcase/tests/test_explode_cases.py, line 13 - F401 'V2' imported but unused
* corehq/apps/hqcase/tests/test_object_cache.py, line 11 - F401 'CommCareCase' imported but unused
* corehq/apps/hqcase/tests/test_object_cache.py, line 12 - F401 'TEST_CASE_ID' imported but unused
* corehq/apps/hqcase/utils.py, line 7 - F401 'ResourceNotFound' imported but unused
* corehq/apps/hqcase/utils.py, line 17 - F401 'V2' imported but unused
* corehq/apps/hqcouchlog/models.py, line 4 - F401 'signals' imported but unused
* corehq/apps/hqcouchlog/models.py, line 4 - W292 no newline at end of file
* corehq/apps/hqcouchlog/tasks.py, line 6 - F401 'settings' imported but unused
* corehq/apps/hqmedia/cache.py, line 2 - F401 'logging' imported but unused
* corehq/apps/hqmedia/models.py, line 11 - F401 'messages' imported but unused
* corehq/apps/hqmedia/models.py, line 17 - F401 'get_db' imported but unused
* corehq/apps/hqmedia/utils.py, line 1 - F401 'XFormException' imported but unused
* corehq/apps/hqmedia/utils.py, line 1 - F401 'XFormValidationError' imported but unused
* corehq/apps/hqpillow_retry/filters.py, line 3 - F401 'BaseSingleOptionFilter' imported but unused
* corehq/apps/hqpillow_retry/filters.py, line 3 - F401 'CheckboxFilter' imported but unused
* corehq/apps/hqwebapp/doc_info.py, line 7 - F401 'CouchUser' imported but unused
* corehq/apps/hqwebapp/encoders.py, line 2 - F401 'datetime' imported but unused
* corehq/apps/hqwebapp/models.py, line 15 - F401 'feature_previews' imported but unused
* corehq/apps/hqwebapp/templatetags/menu_tags.py, line 1 - F401 'logging' imported but unused
* corehq/apps/hqwebapp/views.py, line 72 - F401 'expect_GET' imported but unused
* corehq/apps/importer/tasks.py, line 13 - F401 'V2' imported but unused
* corehq/apps/indicators/admin/crud.py, line 2 - F401 'settings' imported but unused
* corehq/apps/indicators/admin/forms.py, line 2 - F401 'settings' imported but unused
* corehq/apps/indicators/admin/forms.py, line 8 - F401 'NoGroupCouchIndicatorDefBase' imported but unused
* corehq/apps/indicators/admin/forms.py, line 8 - E501 line too long (377 > 115 characters)
* corehq/apps/ivr/api.py, line 10 - F401 'HQMediaMapItem' imported but unused
* corehq/apps/ivr/tasks.py, line 1 - F401 'logging' imported but unused
* corehq/apps/locations/tests/test_location_types.py, line 1 - F401 'uuid' imported but unused
* corehq/apps/mobile_auth/views.py, line 4 - F401 'login_or_digest_ex' imported but unused
* corehq/apps/ota/forms.py, line 4 - F401 'FormActions' imported but unused
* corehq/apps/reminders/event_handlers.py, line 28 - F401 'json_format_datetime' imported but unused
* corehq/apps/reminders/forms.py, line 4 - F401 'ResourceNotFound' imported but unused
* corehq/apps/reminders/forms.py, line 5 - F401 'FormActions' imported but unused
* corehq/apps/reminders/forms.py, line 5 - F401 'StrictButton' imported but unused
* corehq/apps/reminders/forms.py, line 17 - F401 'CheckboxSelectMultiple' imported but unused
* corehq/apps/reminders/forms.py, line 28 - F401 'BootstrapMultiField' imported but unused
* corehq/apps/reminders/forms.py, line 28 - F401 'FieldsetAccordionGroup' imported but unused
* corehq/apps/reminders/forms.py, line 28 - F401 'HiddenFieldWithErrors' imported but unused
* corehq/apps/reminders/forms.py, line 28 - F401 'InlineColumnField' imported but unused
* corehq/apps/reminders/forms.py, line 81 - F401 'string_to_datetime' imported but unused
* corehq/apps/reminders/forms.py, line 82 - F401 'TimeZoneChoiceField' imported but unused
* corehq/apps/reminders/forms.py, line 84 - F401 'InvalidFileException' imported but unused
* corehq/apps/reminders/management/commands/remove_dup_reminders.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/reminders/management/commands/run_reminder_queue.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/reminders/management/commands/run_reminder_queue.py, line 4 - F401 'CaseReminderHandler' imported but unused
* corehq/apps/reminders/urls.py, line 2 - F401 'REMINDER_TYPE_ONE_TIME' imported but unused
* corehq/apps/reminders/views.py, line 9 - F401 'render' imported but unused
* corehq/apps/reminders/views.py, line 64 - F401 'CommCareUser' imported but unused
* corehq/apps/reminders/views.py, line 67 - F401 'get_sample_list' imported but unused
* corehq/apps/reminders/views.py, line 68 - F401 'VerifiedNumber' imported but unused
* corehq/apps/reminders/views.py, line 69 - F401 'register_sms_contact' imported but unused
* corehq/apps/reminders/views.py, line 69 - F401 'update_contact' imported but unused
* corehq/apps/reminders/views.py, line 71 - F401 'Group' imported but unused
* corehq/apps/reminders/views.py, line 72 - F401 'CommCareCase' imported but unused
* corehq/apps/reminders/views.py, line 73 - F401 'parse' imported but unused
* corehq/apps/reminders/views.py, line 75 - F401 'bigcouch_quorum_count' imported but unused
* corehq/apps/reminders/views.py, line 75 - F401 'is_bigcouch' imported but unused
* corehq/apps/reminders/views.py, line 75 - F401 'iter_docs' imported but unused
* corehq/apps/repeaters/models.py, line 2 - F401 'defaultdict' imported but unused
* corehq/apps/repeaters/signals.py, line 3 - F401 'is_device_report' imported but unused
* corehq/apps/reports/dispatcher.py, line 14 - F401 'toggles' imported but unused
* corehq/apps/reports/display.py, line 1 - F401 'json' imported but unused
* corehq/apps/reports/display.py, line 2 - F401 'cache' imported but unused
* corehq/apps/reports/display.py, line 8 - F401 'memoized' imported but unused
* corehq/apps/reports/display.py, line 13 - F401 'soft_assert' imported but unused
* corehq/apps/reports/dont_use/fields.py, line 9 - F401 'Program' imported but unused
* corehq/apps/reports/dont_use/fields.py, line 10 - F401 'Group' imported but unused
* corehq/apps/reports/dont_use/fields.py, line 11 - F401 'HQUserType' imported but unused
* corehq/apps/reports/dont_use/fields.py, line 13 - F401 '_' imported but unused
* corehq/apps/reports/dont_use/fields.py, line 19 - F401 'WebUser' imported but unused
* corehq/apps/reports/filters/base.py, line 5 - F401 '_' imported but unused
* corehq/apps/reports/filters/forms.py, line 17 - F401 'soft_assert' imported but unused
* corehq/apps/reports/standard/cases/careplan.py, line 8 - F401 'reverse' imported but unused
* corehq/apps/reports/standard/cases/data_sources.py, line 1 - F401 'ResourceNotFound' imported but unused
* corehq/apps/reports/standard/cases/data_sources.py, line 5 - F401 'reverse' imported but unused
* corehq/apps/reports/standard/cases/data_sources.py, line 13 - F401 'CommCareUser' imported but unused
* corehq/apps/reports/standard/deployments.py, line 9 - F401 'properly_wrap_sync_log' imported but unused
* corehq/apps/reports/standard/deployments.py, line 25 - F401 'iter_docs' imported but unused
* corehq/apps/reports/standard/forms/reports.py, line 8 - F401 'get_number_of_forms_by_type' imported but unused
* corehq/apps/reports/standard/forms/reports.py, line 8 - F401 'get_number_of_forms_of_all_types' imported but unused
* corehq/apps/reports/standard/forms/reports.py, line 9 - F401 'get_forms_by_type' imported but unused
* corehq/apps/reports/standard/ivr.py, line 11 - F401 'json_format_datetime' imported but unused
* corehq/apps/reports/standard/ivr.py, line 28 - F401 'pytz' imported but unused
* corehq/apps/reports/standard/ivr.py, line 29 - F401 'ceil' imported but unused
* corehq/apps/reports/standard/maps.py, line 9 - F401 'DataTablesColumn' imported but unused
* corehq/apps/reports/standard/maps.py, line 9 - F401 'DataTablesHeader' imported but unused
* corehq/apps/reports/templatetags/xform_tags.py, line 7 - F401 'pytz' imported but unused
* corehq/apps/reports/templatetags/xform_tags.py, line 10 - F401 '_' imported but unused
* corehq/apps/reports/templatetags/xform_tags.py, line 22 - F401 'ServerTime' imported but unused
* corehq/apps/reports/templatetags/xform_tags.py, line 27 - F401 'CommCareCase' imported but unused
* corehq/apps/reports/tests/test_form_export.py, line 3 - F401 'os' imported but unused
* corehq/apps/reports/tests/test_readable_formdata.py, line 1 - F401 'functools' imported but unused
* corehq/apps/reports/tests/test_sql_reports.py, line 9 - F401 'json_format_date' imported but unused
* corehq/apps/reports/views.py, line 21 - F401 'cache' imported but unused
* corehq/apps/reports/views.py, line 74 - F401 'doc_types' imported but unused
* corehq/apps/reports/views.py, line 107 - F401 'submit_case_blocks' imported but unused
* corehq/apps/reports/views.py, line 143 - F401 'export' imported but unused
* corehq/apps/reports/views.py, line 161 - F401 'use_jquery_ui' imported but unused
* corehq/apps/reports/views.py, line 161 - F401 'use_jquery_ui_multiselect' imported but unused
* corehq/apps/reports/views.py, line 161 - F401 'use_select2' imported but unused
* corehq/apps/reports/views.py, line 161 - F811 redefinition of unused 'use_bootstrap3' from line 144
* corehq/apps/sms/api.py, line 8 - F401 'CouchUser' imported but unused
* corehq/apps/sms/api.py, line 9 - F401 'forms' imported but unused
* corehq/apps/sms/api.py, line 10 - F401 'format_username' imported but unused
* corehq/apps/sms/forms.py, line 13 - F401 'BootstrapMultiField' imported but unused
* corehq/apps/sms/forms.py, line 20 - F401 'RecordListField' imported but unused
* corehq/apps/sms/management/commands/check_case_verified_numbers.py, line 3 - F401 'CommCareCase' imported but unused
* corehq/apps/sms/management/commands/fix_preferred_number.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/sms/management/commands/fix_smslog_recipient_doc_type.py, line 2 - F401 'make_option' imported but unused
* corehq/apps/sms/management/commands/fix_smslog_recipient_doc_type.py, line 5 - F401 'settings' imported but unused
* corehq/apps/sms/management/commands/run_sms_queue.py, line 1 - F401 'make_option' imported but unused
* corehq/apps/sms/management/commands/run_sms_queue.py, line 2 - F401 'CommandError' imported but unused
* corehq/apps/sms/mixin.py, line 1 - F401 'defaultdict' imported but unused
* corehq/apps/sms/mixin.py, line 3 - F401 'json' imported but unused
* corehq/apps/sms/mixin.py, line 4 - F401 'parse' imported but unused
* corehq/apps/sms/mixin.py, line 5 - F401 'datetime' imported but unused
* corehq/apps/sms/mixin.py, line 5 - F401 'timedelta' imported but unused
* corehq/apps/sms/mixin.py, line 9 - F401 'release_lock' imported but unused
* corehq/apps/sms/mixin.py, line 12 - F401 'memoized' imported but unused
* corehq/apps/sms/mixin.py, line 13 - F401 'settings' imported but unused
* corehq/apps/sms/mixin.py, line 15 - F401 'try_import' imported but unused
* corehq/apps/sms/mixin.py, line 16 - F401 'json_format_datetime' imported but unused
* corehq/apps/sms/mixin.py, line 17 - F401 'transaction' imported but unused
* corehq/apps/sms/mixin.py, line 18 - F401 'Domain' imported but unused
* corehq/apps/sms/mixin.py, line 20 - F401 'ResourceNotFound' imported but unused
* corehq/apps/sms/models.py, line 4 - F401 'logging' imported but unused
* corehq/apps/sms/models.py, line 6 - F401 'uuidfield' imported but unused
* corehq/apps/sms/tasks.py, line 4 - F401 'sleep' imported but unused
* corehq/apps/sms/tasks.py, line 25 - F401 'Thread' imported but unused
* corehq/apps/sms/tests/opt_tests.py, line 1 - F401 'TestCase' imported but unused
* corehq/apps/sms/tests/opt_tests.py, line 2 - F401 'generator' imported but unused
* corehq/apps/sms/tests/util.py, line 26 - F401 'sleep' imported but unused
* corehq/apps/sms/util.py, line 1 - F401 'logging' imported but unused
* corehq/apps/sms/util.py, line 3 - F401 'urllib' imported but unused
* corehq/apps/sms/util.py, line 7 - F401 'CommCareUser' imported but unused
* corehq/apps/sms/verify.py, line 2 - F401 '_' imported but unused
* corehq/apps/sms/verify.py, line 2 - F401 'ugettext_noop' imported but unused
* corehq/apps/sms/verify.py, line 10 - F401 'util' imported but unused
* corehq/apps/sms/verify.py, line 12 - F401 'localize' imported but unused
* corehq/apps/sms/views.py, line 5 - F401 'logging' imported but unused
* corehq/apps/sms/views.py, line 10 - F401 'pytz' imported but unused
* corehq/apps/sms/views.py, line 11 - F401 'authenticate' imported but unused
* corehq/apps/sms/views.py, line 22 - F401 'can_use_survey_reminders' imported but unused
* corehq/apps/smsbillables/async_handlers.py, line 2 - F401 'ResourceNotFound' imported but unused
* corehq/apps/smsbillables/async_handlers.py, line 4 - F401 'log_accounting_error' imported but unused
* corehq/apps/smsbillables/management/commands/add_moz_zero_charge.py, line 2 - F401 'logging' imported but unused
* corehq/apps/smsbillables/management/commands/add_moz_zero_charge.py, line 3 - F401 'ResourceNotFound' imported but unused
* corehq/apps/smsbillables/management/commands/bootstrap_grapevine_gateway.py, line 2 - F401 'logging' imported but unused
* corehq/apps/smsbillables/management/commands/bootstrap_grapevine_gateway_update.py, line 2 - F401 'logging' imported but unused
* corehq/apps/smsbillables/tests/test_usage_fees.py, line 1 - F401 'settings' imported but unused
* corehq/apps/smsforms/app.py, line 18 - F401 'submit_form_locally' imported but unused
* corehq/apps/smsforms/app.py, line 19 - F401 'XFormInstance' imported but unused
* corehq/apps/smsforms/management/commands/close_deleted_sms_sessions.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/sofabed/tests/test_formdata.py, line 4 - F401 'uuid' imported but unused
* corehq/apps/style/forms/widgets.py, line 4 - F401 'HiddenInput' imported but unused
* corehq/apps/style/forms/widgets.py, line 4 - E501 line too long (135 > 115 characters)
* corehq/apps/style/tests/test_compress_command.py, line 10 - F401 'safe_repr' imported but unused
* corehq/apps/style/views.py, line 1 - F401 'method_decorator' imported but unused
* corehq/apps/styleguide/example_forms.py, line 2 - F401 'render_to_string' imported but unused
* corehq/apps/tour/management/commands/unmark_tour_as_seen.py, line 3 - F401 'sys' imported but unused
* corehq/apps/tour/models.py, line 2 - F401 'IntegrityError' imported but unused
* corehq/apps/userreports/reports/filters/specs.py, line 1 - F401 '_' imported but unused
* corehq/apps/userreports/reports/util.py, line 1 - F401 'ugettext' imported but unused
* corehq/apps/userreports/reports/view.py, line 36 - F401 'localize' imported but unused
* corehq/apps/userreports/tests/test_view.py, line 15 - F401 'V2' imported but unused
* corehq/apps/userreports/tests/test_view.py, line 18 - F401 'FormProcessorInterface' imported but unused
* corehq/apps/users/dbaccessors/all_commcare_users.py, line 2 - F401 'settings' imported but unused
* corehq/apps/users/forms.py, line 10 - F401 'HiddenInput' imported but unused
* corehq/apps/users/management/commands/delete_user.py, line 1 - F401 'CommandError' imported but unused
* corehq/apps/users/models.py, line 21 - F401 'get_case_ids_in_domain_by_owner' imported but unused
* corehq/apps/users/models.py, line 39 - F401 'CommCareCase' imported but unused
* corehq/apps/users/models.py, line 62 - F401 'XFormInstance' imported but unused
* corehq/apps/users/models.py, line 71 - F401 'json_format_datetime' imported but unused
* corehq/apps/users/tasks.py, line 8 - F401 'get_all_reverse_indices_info' imported but unused
* corehq/apps/users/tasks.py, line 10 - F401 'CommCareCase' imported but unused
* corehq/apps/users/tasks.py, line 11 - F401 'V2' imported but unused
* corehq/apps/users/tasks.py, line 17 - F401 'get_docs' imported but unused
* corehq/apps/users/tasks.py, line 18 - F401 'DELETED_SUFFIX' imported but unused
* corehq/apps/users/tasks.py, line 18 - F401 'is_deleted' imported but unused
* corehq/apps/users/tasks.py, line 23 - F401 'XFormInstance' imported but unused
* corehq/apps/users/tests/case_utils.py, line 6 - F401 'V2' imported but unused
* corehq/apps/users/views/mobile/groups.py, line 24 - F401 'CommCareUser' imported but unused
* corehq/apps/users/views/mobile/groups.py, line 24 - F401 'CouchUser' imported but unused
* corehq/form_processor/parsers/form.py, line 1 - F401 'hashlib' imported but unused
* corehq/messaging/ivrbackends/kookoo/models.py, line 5 - F401 'StringProperty' imported but unused
* corehq/messaging/ivrbackends/kookoo/tests/outbound.py, line 12 - F401 'sleep' imported but unused
* corehq/messaging/ivrbackends/kookoo/views.py, line 1 - F401 'sys' imported but unused
* corehq/messaging/ivrbackends/kookoo/views.py, line 3 - F401 'HttpResponseBadRequest' imported but unused
* corehq/messaging/smsbackends/apposit/models.py, line 5 - F401 'StringProperty' imported but unused
* corehq/messaging/smsbackends/megamobile/models.py, line 1 - F401 'logging' imported but unused
* corehq/messaging/smsbackends/megamobile/views.py, line 3 - F401 'HttpResponseBadRequest' imported but unused
* corehq/messaging/smsbackends/smsgh/models.py, line 3 - F401 'strip_plus' imported but unused
* corehq/messaging/smsbackends/smsgh/models.py, line 5 - F401 'StringProperty' imported but unused
* corehq/messaging/smsbackends/telerivet/models.py, line 1 - F401 'os' imported but unused
* corehq/messaging/smsbackends/tropo/views.py, line 4 - F401 'incoming_call' imported but unused
* corehq/messaging/smsbackends/twilio/models.py, line 1 - F401 'logging' imported but unused
* corehq/messaging/smsbackends/twilio/models.py, line 3 - F401 'clean_phone_number' imported but unused
* corehq/messaging/smsbackends/twilio/tests/test_log_call.py, line 2 - F401 'LogCallTestCase' imported but unused
* corehq/messaging/smsbackends/twilio/views.py, line 5 - F401 'HttpResponseBadRequest' imported but unused
* corehq/messaging/smsbackends/twilio/views.py, line 6 - F401 'csrf_exempt' imported but unused
* corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py, line 1 - F401 'datetime' imported but unused
* corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py, line 2 - F401 'DatabaseError' imported but unused
* corehq/messaging/smsbackends/unicel/tests/test_create_from_request.py, line 7 - F401 'CouchUser' imported but unused
* corehq/pillows/base.py, line 3 - F401 'settings' imported but unused
* corehq/pillows/domain.py, line 6 - F401 'memoized' imported but unused
* corehq/pillows/domain.py, line 7 - F401 'settings' imported but unused
* corehq/pillows/sms.py, line 12 - F401 'settings' imported but unused
* corehq/pillows/user.py, line 13 - F401 'settings' imported but unused
* corehq/preindex/management/commands/sync_prepare_couchdb_multi.py, line 3 - F401 'get_preindex_plugins' imported but unused
* corehq/util/supervisord/api.py, line 1 - F401 'os' imported but unused
* corehq/util/timezones/utils.py, line 3 - F401 'datetime' imported but unused

**Comment by benrudolph** [comment]
actually dimagimon can be super useful in this case

**Comment by nickpell** [comment]
@dannyroberts @benrudolph What happened that required reverting the cleanup?  I'd be interested in getting the unused imports removed.

**Comment by benrudolph** [comment]
from talking with @dannyroberts (he did the initial PR), he had used some code to automatically remove imports, but then it didn't work due to some python paths being off or something. once that happened the window of opportunity was missed since it caused all sorts of merge conflicts. then i think it was decided that it wasn't worth the effort

**Comment by benrudolph** [comment]
(it was a bit ago so the details are a bit fuzzy but i think that's the gist)

**Comment by nickpell** [comment]
gotcha thanks.  I might be interested in pursuing a more incremental approach like https://github.com/dimagi/commcare-hq/pull/11513

**Comment by dannyroberts** [comment]
Yeah, that's basically what happened.

FWIW, the command I was using is similar but much more manual

`pylint corehq/ --disable=all --enable=unused-import` (replace `corehq/` with whatever path you care about). Autoflakes sounds awesome and mildly scary

**Pull request merged**
