### PR TITLE
Revert "Revert "Renamed a few attributes in SMS/reminders""

### PR DESCRIPTION
**Pull request by dannyroberts**
Reverts dimagi/commcare-hq#25826

This is a PR to redo https://github.com/dimagi/commcare-hq/pull/25773 once https://sentry.io/organizations/dimagi/issues/1317786920/?project=136860&query=domain%3Avectorlink-tanzania&statsPeriod=14d is fixed and the change is revalidated.

### CODE REVIEW

**Comment by dannyroberts** [comment]
@orangejenny Assigned to you. It may not be a big fix, but I wanted to get it off production first and then let you iterate on the fix locally until we're sure it's good

**Comment by orangejenny** [comment]
Ready for review.

**Review by mkangia — APPROVED** [review]

**Comment by dannyroberts** [comment]
Looks like tests aren't running on that last commit for some reason?

Is there a test you could add that would have caught this? Even something as simple as just instantiating a `TelerivetBackendForm`? Not sure how necessary that is (I think we often don't test django form code) but thought I'd ask

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
@dannyroberts Travis might have been lagging, there's a test job now. I'm not going to add tests here, as it doesn't look straightforward even just to instantiate a `TelerivetBackendForm`, looks like the form needs to reference a real backend.

**Pull request merged**
