### PR TITLE
Mk release repeater edit pause

### PR DESCRIPTION
**Pull request by mkangia**
Release https://github.com/dimagi/commcare-hq/pull/18579#issuecomment-354989086

Removes the FF making feature to edit repeaters and pause them available for all.

best 🐟 / 🐟

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
looks fine besides the one thing i caught. assuming there are not other instances of that

**Comment by orangejenny** [comment]
Looks good once the remaining references to ENABLE_REPEATER_EDIT_AND_PAUSE are removed (one in tests and the one Cal pointed out).

**Comment by mkangia** [comment]
oh no.. thanks for catching this @calellowitz .. removed it.

**Review by calellowitz — APPROVED** [review]

**Comment by mkangia** [comment]
fyi
@sheelio @Ben-Talbot

**Pull request merged**
