### PR TITLE
[USH-4126] Multimedia question buttons' alignment

### PR DESCRIPTION
**Pull request by akashkj**
## Product Description
Misalignment of buttons in a multimedia question.

## Technical Summary
https://dimagi.atlassian.net/browse/USH-4126

Before:
image

image

After:
image

image

image

## Feature Flag
WEB_APPS_UPLOAD_QUESTIONS

### Safety story
Local testing

### Automated test coverage

NA

### QA Plan

NA

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by nospame — APPROVED** [review]
You could achieve the same thing here by wrapping the input in a div with either a `pull-left` or `visible-xs-inline-block` and not having to use rows or columns. Something like:
```html
<div class="pull-left">
  <input type="file"/>
</div>
<button class="btn btn-default btn-xs pull-right"></button>
```
I tend to favor a simpler solution and feel that rows and columns add unnecessary complexity in a lot of cases, but I don't think there's anything wrong with your approach.

**Comment by akashkj** [comment]
Hi @nospame 
Thanks for suggesting the alternative. It indeed is much simpler solution. It works fine with app preview and webapps large screen but with webapps small screen, it is not showing as intended.
image

**Comment by nospame** [comment]
> Hi @nospame Thanks for suggesting the alternative. It indeed is much simpler solution.
> 
> With `pull-left`: It works fine with app preview and webapps large screen but with webapps small screen, it is not showing as intended. Should this be ignored?
> 

Oh interesting, yeah I am seeing that it's wrapping on screens smaller than about 400px wide because the input seems to default to 245px wide. 

> With `visible-xs-inline-block`: It seems to be broken in webapps but works fine with app preview.
>

Maybe columns are the better answer here then. I'd maybe opt for something like 8/4 width columns to better represent the actual size of the input vs the "clear" button, but I don't think it makes a visual difference.

**Comment by akashkj** [comment]
> 8/4 width columns to better represent the actual size

Modified

**Review by nospame — APPROVED** [review]

**Pull request merged**
