### PR TITLE
Merge dimagi-utils and auditcare into commcare-hq repo

### PR DESCRIPTION
**Pull request by dannyroberts**
used the subtree-merge script

All the commits you see here are commits from dimagi-utils and auditcare except for the last five made by me today.

### CODE REVIEW

**Comment by orangejenny** [comment]
Hooray!

screen shot 2017-07-21 at 3 45 20 pm
...I guess even GitHub gets tired of counting eventually.

**Review by millerdev — APPROVED** [review]
😆  So happy to see this! 🎉

**Comment by gcapalbo** [comment]
@dannyroberts what's the plan for the dimagi/logistics repo? will the dimagi-utils and auditcare repos hang around to support those references?

**Comment by dannyroberts** [comment]
@gcapalbo, yeah I don't plan on deleting auditcare or dimagi-utils repos, so the plan is for dimagi/logistics to be able to keep its references to those and for that to work indefinitely, or at least have that option.

**Pull request merged**
