### PR TITLE
Allow evaluator expression variables to be None or boolean

### PR DESCRIPTION
**Pull request by kaapstorm**
This is going to allow us to evaluate coalesce-style expressions like ...

``` JavaScript
  {
    "display_name": "Selected Date", 
    "datatype": "date", 
    "type": "expression", 
    "column_id": "selected_date", 
    "expression": {
      "datatype": "date", 
      "type": "evaluator", 
      "context_variables": {
        "screening_date": {
          "datatype": "date", 
          "type": "property_path", 
          "property_path": [
            "form", 
            "date"
          ]
        }, 
        "adoption_date": {
          "datatype": "date", 
          "type": "property_path", 
          "property_path": [
            "form", 
            "selected_date"
          ]
        }
      }, 
      "statement": "screening_date if screening_date else adoption_date"
    }
  }
```

@czue cc @NoahCarnahan

### CODE REVIEW

**Comment by kaapstorm** [comment]
(Unlike previous similar PRs, it turns out I actually need this one.)

**Comment by NoahCarnahan** [comment]
Does this change existing behavior? Would `a or b` where `a="foo"` and `b="bar"` have returned `"foo"` before? If so, do you think we need to migrate these existing reports? (not sure how widespread evaluator expression usage is)

**Comment by kaapstorm** [comment]
:construction_worker: :white_check_mark: https://travis-ci.org/dimagi/commcare-hq/builds/148042835

**Comment by kaapstorm** [comment]
@NoahCarnahan, no, this doesn't change existing behaviour. `and` and `or` were undocumented and unused. I actually added them, only to discover their behaviour differed from what I expected, and then I removed my code and tested them and discovered they had always been there. This test just shows what they do (which is neither Python bitwise `&` and `|` nor Python logical `and` and `or`).

**Comment by NoahCarnahan** [comment]
Cool, thanks for the clarification

**Pull request merged**
