### PR TITLE
UCR documentation in readthedocs

### PR DESCRIPTION
**Pull request by emord**
Another thing I've wanted to do for a while. I think the final scenario would involve having the top level sections in separate pages (overview, data sources, reports, etc) as the current one would is huge, but this initial one would just be moving these docs to their respective classes.

Also its super nice that it directly points you to the source code:
image

Thoughts? Is it worth continuing as a late night-no thought task? should we just keep the huge readme file?

guessing interested parties: @czue @snopoke @calellowitz

### CODE REVIEW

**Comment by snopoke** [comment]
I think this would be great.

**Comment by czue** [comment]
:+1: :100:

**Comment by esoergel** [comment]
:+1: 
IIRC this does at least give a nice TOC on the sidebar too, is that right?

**Comment by emord** [comment]
@esoergel it does

image

**Comment by emord** [comment]
I think this is good to merge as is. I haven't moved all of the expressions to their classes yet, but I think this may be strictly better than the current unwieldy markdown file.

**Review by kaapstorm — APPROVED** [review]

**Pull request merged**
