### PR TITLE
Enclose content in correct div, so that footer layout works as expected

### PR DESCRIPTION
**Pull request by sravfeyn**
This unblocks a button that otherwise is covered by the footer. http://manage.dimagi.com/default.asp?189202 cc @esoergel

### CODE REVIEW

**Comment by czue** [comment]
cc @orangejenny @biyeun (in case any feedback)

**Comment by orangejenny** [comment]
looks okay to me, will leave for @biyeun

**Comment by benrudolph** [comment]
once this is mgd it should fixed i think: https://github.com/dimagi/commcare-hq/pull/9537

**Comment by biyeun** [comment]
should be fixed by https://github.com/dimagi/commcare-hq/pull/9537, closing for now

**Pull request closed without merging**
