### PR TITLE
Location safe

### PR DESCRIPTION
**Pull request by sravfeyn**
https://manage.dimagi.com/default.asp?251580#edit_0_251580 https://manage.dimagi.com/default.asp?251578

@esoergel

### CODE REVIEW

**Comment by sravfeyn** [comment]
On location-restriction, I think instead of a cryptic 403 to the user, we should display an error message that convey that it's a project setup organizations setup issue. @sheelio

**Comment by sravfeyn** [comment]
Closing this as these changes are required in another PR https://github.com/dimagi/commcare-hq/pull/15696

**Comment by esoergel** [comment]
@sravfeyn We currently show [this message](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/locations/middleware.py#L6-L11) if the user doesn't have a location assigned, or in other location restriction things, we show [this message](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/locations/permissions.py#L95-L99).  I'd definitely be in support of a clearer message or more precise messages in various circumstances if you wanna take a crack at it.  For example, we could distinguish between a page being unavailable because it's not location-safe and a page being unavailable because it IS location-safe, but the data requested is out of scope.

**Comment by sravfeyn** [comment]
My bad, it already is showing the message for non-location-safe page as well. Thanks for explanation!

**Pull request closed without merging**
