### PR TITLE
add a step to the README on getting offline less working

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by esoergel** [comment]
https://github.com/dimagi/commcare-hq/pull/10110

**Comment by benrudolph** [comment]
interesing. i think @biyeun and i decided to use the other compressor locally cause it was way way faster

**Comment by benrudolph** [comment]
hmm ok yeah that was never PR'd

**Comment by benrudolph** [comment]
actually @dannyroberts see this: https://github.com/dimagi/commcare-hq/blob/master/settings.py#L926

**Pull request merged**
