### PR TITLE
Remove Python 2 requirements and docker

### PR DESCRIPTION
**Pull request by millerdev**
- `requirements-python3` was intentionally left intact since https://github.com/dimagi/commcare-cloud still depends on it.
- The base docker image may take some time to build a new Python 3 version on dockerhub. Do we need to do something special for that to cut over cleanly?

### CODE REVIEW

**Comment by emord** [comment]
Looks like the test failures are on the requirements tests. You may need to update https://github.com/dimagi/commcare-hq/blob/4d45e1130fcb619f7830132dd7f6622a93a2e414/scripts/test-make-requirements.sh in some way?

**Comment by millerdev** [comment]
This may need to be rebased after https://github.com/dimagi/commcare-hq/pull/25149 is merged

**Comment by millerdev** [comment]
Canceled travis until new [dockerhub image is built](https://cloud.docker.com/repository/docker/dimagi/commcarehq_base_new/builds) (currently in progress)

**Comment by millerdev** [comment]
✅

**Pull request merged**
