### PR TITLE
reduce z-index of notice

### PR DESCRIPTION
**Pull request by sravfeyn**
http://manage.dimagi.com/default.asp?189126#edit_0_189126 @esoergel

### CODE REVIEW

**Comment by czue** [comment]
@orangejenny might also have thoughts

**Comment by orangejenny** [comment]
It's unfortunate that this is in-page CSS rather than an external LESS file that could use a z-index variable...hard-coding z-index is a mess.

That said, I was curious why these needs a z-index at all - given that it's an absolutely positioned div that appears after the elements it's trying to cover, it should already be drawn on top of them. Looks like it's necessary to cover the date range text box, which is a `.input-group .form-control` with a `z-index: 2` rule that's set by bootstrap: https://github.com/twbs/bootstrap/blob/master/less/input-groups.less#L23  So I'd suggest making this 3 instead of 50 (arbitrarily high z-indexes are a code smell) and adding a comment explaining why it's necessary.

Also, there's a `z-index: 4999` five lines that up that also needs to be changed. I'd guess you can just lower the 4999 to 3 and remove the 5000 altogether (the 5000 element is a child of the 4999 element, shouldn't need its own explicit z-index) but haven't tested that.

**Comment by sravfeyn** [comment]
Awesome! Thanks for the detailed note @orangejenny I updated the code.

**Comment by orangejenny** [comment]
sweet, looks good

**Pull request merged**
