### PR TITLE
Kill careplans

### PR DESCRIPTION
**Pull request by dannyroberts**
I've heard some excitement around the prospect of this from some of you, and I did a little final research on prod data to validate. See also: https://trello.com/c/StQ0J7Ci/21-care-plans.

I left around a `CareplanModule` stub that's just a trigger for displaying a deprecation message, and removed all the code that did anything interesting with it.

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
💓

**Comment by orangejenny** [comment]
FWIW, this 500s when accessing an app that does contain a care plan module:
screen shot 2017-07-25 at 5 12 23 pm

**Comment by dannyroberts** [comment]
Thanks, I fixed that by changing my strategy and filtering out careplan modules entirely so they never appear in the first place. Was also able to then delete a bunch more boilerplate code.

**Comment by orangejenny** [comment]
Nice, I like the new strategy.

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
