### PR TITLE
convert four more fluff pillows to kafka

### PR DESCRIPTION
**Pull request by czue**
:blowfish: still need to push this closer into the framework if possible so that there's less scaffolding around everything

wanted to get a few more running on prod first just to make sure everything is working fine.

@benrudolph @snopoke

### CODE REVIEW

**Comment by benrudolph** [comment]
onwards and upwards! :boat: will let tests run

**Comment by czue** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
I assume the update to fluff was in a previous PR that's already merged

**Comment by czue** [comment]
> I assume the update to fluff was in a previous PR that's already merged
:+1:

**Pull request merged**
