### PR TITLE
B3 ui element

### PR DESCRIPTION
**Pull request by biyeun**
- cleans up references to ui-element so that they're all using the b3 version (same JS functionality, correct CSS)
  @orangejenny cc @calellowitz

### CODE REVIEW

**Comment by orangejenny** [comment]
Hooray, this has been a bit confusing. Good to merge when tests pass.

Can you delete `bootstrap2/ui-element.js` altogether? Doesn't look like there's anything left that references it.

**Comment by biyeun** [comment]
@orangejenny removed the split of `ui-element.js` and `main.js`

**Comment by orangejenny** [comment]
awesome. bootstrap2's base_template.html is no longer used, right? looks like it still references bootstrap2/main.js

**Comment by biyeun** [comment]
@orangejennyi can pop that commit over to this PR then https://github.com/dimagi/commcare-hq/pull/11881

**Comment by biyeun** [comment]
@orangejenny tests are ✅

**Pull request merged**
