### PR TITLE
B3 tf feedback

### PR DESCRIPTION
**Pull request by benrudolph**
@biyeun @orangejenny here's some of the feedback. two things notably missing:
- didn't add the jquery textchange file to bower since i'd like to get this in first: https://github.com/dimagi/commcare-hq/pull/8917
- didn't move touchforms-inline because i wanted to get some more context on the second place that it was used (case-hierarchy.html). not sure where that's used

:blowfish: 
cc: @proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Kicked build, fail looked unrelated.

**Comment by czue** [comment]
should be fixed by https://github.com/dimagi/commcare-hq/pull/9087

**Comment by snopoke** [comment]
FYI `case-hierarchy.html` is used by the `render_case_hierarchy` template tag which is used when rendering a case in these places:
* case details view
* careplan
* pact careplan

**Comment by czue** [comment]
:boot: ed the :construction:

**Pull request merged**
