### PR TITLE
Deactivate data source

### PR DESCRIPTION
**Pull request by nickpell**
implements http://manage.dimagi.com/default.asp?189462

@czue @NoahCarnahan cc: @orangejenny @TylerSheffels

### CODE REVIEW

**Comment by orangejenny** [comment]
looks reasonable to me, will leave for @NoahCarnahan or @czue to look over

**Comment by TylerSheffels** [comment]
Same from me!

**Comment by NoahCarnahan** [comment]
Deactivated data sources will still show up in the left side navigation, right? Is there any indication when you view a data source if it's been deactivated?

**Comment by nickpell** [comment]
@NoahCarnahan The data source will still show up in the left hand navigation.  Right now, there isn't a visible cue that the data source is deactivated.  I was thinking of putting a checkbox on the data source config page.  Alternatively we could append "(deactivated)" to the data source name.

**Comment by NoahCarnahan** [comment]
I like the idea of adding "(deactivated)" to the name for now. Seems like that would solve some possibly confusing scenarios.

**Comment by orangejenny** [comment]
> I like the idea of adding "(deactivated)" to the name for now. Seems like that would solve some possibly confusing scenarios.

I also like having a way to distinguish these in the UI. If at all possible, I'd have a help popup over the "deactivated" text explaining what it means, because we use "active" elsewhere in HQ to mean different things. Or do an icon, a warning sign or flag or something, with a help popup, and don't expose the word "deactivated" at all.

**Comment by NoahCarnahan** [comment]
Another thing that crossed my mind is that a domain could potentially accumulate an ever increasing number of data sources if someone is often creating and deleting report builder reports. This got me thinking that perhaps the solution is to treat user created/edited data sources different than we treat report builder created data sources.

Perhaps instead of the deactivated flag, there should be a flag on data sources that humans touch, and when a report is deleted we do not delete the data source it referenced if that was a data source that a person had touched. I haven't thought through all the potential disadvantages though...

**Comment by nickpell** [comment]
@NoahCarnahan That sounds like a valid approach as well, but I'm not too worried about having too many data sources, since the process that would create them seems like a rare workflow, the deactivated data sources are just couch docs that don't generate much overhead other than the space they take up in the db, and if we wanted to remove deactivated data sources in the future it would be an easy task to do.  In contrast mistakenly deleting a data source is more difficult to recover from.

**Comment by nickpell** [comment]
@orangejenny I like the idea of having a warning popup, with instructions on how to activate the build as well.

**Comment by NoahCarnahan** [comment]
cool, sounds good. Do you want to add the UI changes to this PR, or should I merge it now?

**Pull request merged**
