### PR TITLE
Don't fetch cached user, we're gonna save it

### PR DESCRIPTION
**Pull request by esoergel**
https://dimagi-dev.atlassian.net/browse/HI-610
https://sentry.io/organizations/dimagi/issues/538330201/

Getting a resource conflict when adding a web user to a domain (which saves the user object).

@nickpell

### CODE REVIEW

**Review by nickpell — COMMENTED** [review]
Is the theory that the cache is stale, so fetching a user from the cache and then saving it fails?

**Comment by esoergel** [comment]
@nickpell yup, that's my guess as to what's happening.

**Comment by nickpell** [comment]
Will passing ```strict=True``` overwrite the stale cache?  (If not, seems better to clear the cache so it will be up-to-date afterwards).

**Comment by esoergel** [comment]
I don't think so - I think quickcache just skips the caching mechanism entirely.  If this does end up saving the user, then that should invalidate the cache.

**Comment by nickpell** [comment]
Hmm, seems then preferable to clear the cache prior to fetching the user.

**Comment by nickpell** [comment]
Actually I see now how the user always gets saved - so fine as is.

**Pull request merged**
