### PR TITLE
have MVP indicators deal with revisions correctly

### PR DESCRIPTION
**Pull request by dannyroberts**
and more straightforwardly

also makes MVP pillows raise their errors rather than suppressing them

### CODE REVIEW

**Comment by dannyroberts** [comment]
@biyeun @czue I want to just take notes on http://manage.dimagi.com/default.asp?160417 and get your opinions. First, I do think this is at least an important piece of the puzzle. I think I have a coherent story for why this was only happening on `IndicatorXForm`s. (If you search your email for this MVP error, it's all forms.) And that's that while IndicatorXForm.is_update is always false, IndicatorCase.is_update is pretty much always true. And if you look closely at the code, the _rev issue hinges on that.

I think I don't have a coherent story for why it was happening as often as it was—and if so then why not more often. Forms are generally only saved once, so the only way a form would be trying to save over another form is if the pillow processes the same change twice. In our normal mental model of how the changes feed works, this would only happen if the pillow was reset. But if the pillow was reset, we'd have hundreds of thousands of these errors, not just a handful here and there. The only thing I can think of, and maybe this is plausible, is that the changes feed is almost completely linear but every so often throws in a repeat (since after all, there's explicitly no guarantee that changes show up in order or show up only once—as we've seen recently!).

I'm going to hold off on this until we have a chance to discuss and agree on a good way to test/QA.

**Comment by czue** [comment]
this makes sense to me. let me know what you think we should do in terms of testing, but am happy to merge now too

**Comment by dannyroberts** [comment]
If your ok with that, I'm fine with it. It's a small diff that I thought
pretty carefully about, but we would definitely just be relying on me
having been careful, as I had no data to run this code against. Was waiting
for guidance from @biyeun, but if we want to just push and fix any
potential errors relatively I won't say no.

**Comment by biyeun** [comment]
I think it's fine to push

**Comment by czue** [comment]
:shipit:

**Pull request merged**
