### PR TITLE
Remove old intrahealth pillow & report code

### PR DESCRIPTION
**Pull request by emord**
Follow up from https://github.com/dimagi/commcare-cloud/pull/1933 We aren't running these pillows anymore, and new reports were created to replace these old reports

@dmydlo can you confirm that your work should allow removing all of this code?

### CODE REVIEW

**Comment by dmydlo** [comment]
@emord Everything looks good, removing this code won't affect new reports.

**Comment by emord** [comment]
Thanks for confirming @dmydlo 

@biyeun @Rohit25negi should be ready for review

**Comment by Rohit25negi** [comment]
@emord  is this still active?

**Comment by emord** [comment]
yes still active. looks like a non-trivial merge conflict that I need to solve. will do so this week

**Pull request closed without merging**
