### PR TITLE
Be explicit about min pycryptodome version

### PR DESCRIPTION
**Pull request by dannyroberts**
since there's an external constraint we want to assert, namely that
versions below 3.6.6 are considered to have security vulnerabilities.

@emord I had already started this in a separate branch before realizing you'd done it in parallel and beaten me to it. PRing just this piece since it's a nice extra safety check and intentionality hint.

### CODE REVIEW

**Review by emord — APPROVED** [review]
Is there a workflow where this could ever be set to < 3.6.6 other than very manually setting it in all the txt files?

Also the "security update" comment seems kind of pointless. if we did that for all security updates, we'd eventually have the same comment for many of these packages

**Comment by dannyroberts** [comment]
> Is there a workflow where this could ever be set to < 3.6.6 other than very manually setting it in all the txt files?

Yeah the scenario I had in mind is that we add a dependency, and that dependency pins to <3.6.6 for some reason. In that case, since nothing else in the .in files restricts its version, it would go with this new, lower version. If we set a min version like in this PR, then we would see it clearly as a version conflict. There are probably other similar scenarios but I think this is the most plausible.

> Also the "security update" comment seems kind of pointless. if we did that for all security updates, we'd eventually have the same comment for many of these packages

Yeah I mean it doesn't say a ton, but I still think it says something. The person who is confronted with a version conflict in the above scenario would likely come upon this line and see that it has a min version, and then also see why it was picked as a min version. They may be wondering "is this a real lower limit, or is it just what it happened to be when it was last updated so whoever it was overzealously applied that limit?" and the comment will hopefully guide them to conclude the former.

**Comment by emord** [comment]
Ah. that makes sense. Didn't think about other packages having dependencies pinned.

**Comment by emord** [comment]
> Build failure is/will be fixed by this PR: #21679

Do you want to merge master in and let tests re-run or just go ahead and merge?

**Comment by dannyroberts** [comment]
Eh, my intuitions aren't infallible, so might as well merge and run the test

**Pull request merged**
