### PR TITLE
Misc UCR documentation updates

### PR DESCRIPTION
**Pull request by esoergel**
Commit-by-commit will probably make the most sense.
@czue @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
will let @czue review as he has more context

**Comment by czue** [comment]
looks good pending updating the aggregation recommendations. thanks!

**Comment by esoergel** [comment]
:white_check_mark: The last two commits are new - I added links and made some language changes around aggregation spec

**Comment by czue** [comment]
nice - this is great thanks!

**Pull request merged**
