### PR TITLE
Intaheatlh reports

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue @fyniac 

Fixes for cases:
http://manage.dimagi.com/default.asp?166971#935427
http://manage.dimagi.com/default.asp?167312#931906
http://manage.dimagi.com/default.asp?167313#931905

### CODE REVIEW

**Comment by czue** [comment]
@TylerSheffels this needs a `RecouvrementFluff` checkpoint reset. @lwyszomi any others?

**Comment by lwyszomi** [comment]
@czue @TylerSheffels 
Can we reset ```TauxDeRuptureFluff``` too? I know, I have not changed anything in this fluff, but we have some missing docs on HQ. When I run this fluff on local machine then I have all data.

**Comment by TylerSheffels** [comment]
@lwyszomi Will do.

**Comment by lwyszomi** [comment]
@TylerSheffels Thanks

**Pull request merged**
