### PR TITLE
Minor extend_schema cleanup

### PR DESCRIPTION
**Pull request by benrudolph**
just some cleanup. changing variable names and adding a couple tests. may not be necessary, feel free to push back

@czue @esoergel

### CODE REVIEW

**Comment by czue** [comment]
just curious if this was just cleanup what is the commit that added a failing test?

**Comment by czue** [comment]
seems legit assuming you're sure these are better names in whatever ways this function is used

**Comment by esoergel** [comment]
:heart: the way these tests are written - makes it very easy to understand what the code is supposed to do.

**Comment by benrudolph** [comment]
i had originally thought the bug was in this function (turned out it wasn't and i fixed the test in the last commit. sorry bad history). better names i suppose is debatable since doc represents a schema from one document (but still of schema type) and previous_schema represents a schema from multiple docs reconciled. 

ethan, yeah feel like just having examples of how the function is used is helpful in understanding

**Pull request merged**
