### PR TITLE
Ipm senegal fix

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue 
need reset checkpoint and reidnex RecouvrementFluffPillow.

### CODE REVIEW

**Comment by lwyszomi** [comment]
@fyniac @snopoke 
Could you take a look and merge? This is important for Fio.

**Comment by czue** [comment]
@esoergel are you deploying? this needs a pillow reindex

**Comment by esoergel** [comment]
@czue I am, will preindex early then.

**Comment by czue** [comment]
cool - fyi, this is a bit more complicated than a simple preindex (have to manually stop pillow and reset the checkpoint). @dannyroberts can help if you aren't sure what to do

**Comment by dannyroberts** [comment]
Offlined with @esoergel but steps are
- log into hqpillowtop0 and stop pillows (or just this one)
- go to https://www.commcarehq.org/hq/admin/system/ and click reset (for just this pillow!)
- do a normal awesome_deploy

**Pull request merged**
