### PR TITLE
New mvp indicator

### PR DESCRIPTION
**Pull request by katembu**

### CODE REVIEW

**Comment by czue** [comment]
@biyeun assume you should review this?
@katembu assume no way around doing this without another huge reindex?

**Comment by katembu** [comment]
@czue @biyeun we've no problem waiting for the huge reindex to catch up. This should be last or second last change happening on this project.

**Comment by katembu** [comment]
@biyeun let me know when this will be deployed.

**Comment by biyeun** [comment]
@katembu sorry, we were offline this week for the dev summit. This feature should be deployed.

**Comment by czue** [comment]
@biyeun (or whoever deployer is) - I think this still requires resetting the pillows, right? also, thanks to @snopoke that should be doable from the admin page: https://www.commcarehq.org/hq/admin/system/

**Comment by biyeun** [comment]
so lovely. thanks @snopoke <3

**Comment by katembu** [comment]
@biyeun is re-indexing complete?

**Comment by biyeun** [comment]
@katembu all caught up

**Comment by czue** [comment]
@biyeun @katembu I don't think they are. The UI says they are but the sequence IDs still look way behind. that indicator might have broken with @snopoke's refactor

image

**Comment by katembu** [comment]
@czue @biyeun  can you check for me the status of this. Some indicator are yet to catch up completely but seems to be improving each day.

**Comment by czue** [comment]
@katembu that's right.

The indices are the following number of documents through: 
cases: 55349918 / 69966356
forms: 51709745 / 69966353

**Pull request merged**
