### PR TITLE
Update App Builder Icons

### PR DESCRIPTION
**Pull request by biyeun**
Also make the move icon only appear on hover ;-) @dimagi/product 

@benrudolph cc @orangejenny 

merge https://github.com/dimagi/commcare-hq/pull/12838 or close that PR after merge of this one

demo-icons

### CODE REVIEW

**Comment by benrudolph** [comment]
❤️ ❤️ ❤️

**Comment by benrudolph** [comment]
i wonder if it'd be ok to take the flag off of the form icons?

**Comment by benrudolph** [comment]
(no strong feelings but thought i'd raise it)

**Comment by orangejenny** [comment]
I'd support moving these out from behind the support toggle but would do it as part of other user-facing case management onboarding changes (which we'll hopefully be doing in the next few weeks).

**Comment by benrudolph** [comment]
Sounds right to me

**Comment by amsagoff** [comment]
:heart_eyes:

**Pull request merged**
