### PR TITLE
Add license abbreviations

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?151804#876211

abbreviations from here: http://manage.dimagi.com/default.asp?115231#BugEvent.650603

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
whoa, what are those search indices used for?

**Comment by emord** [comment]
@czue Whoa crap. I thought I was editing the js files for a couple of pages. nice catch

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by emord** [comment]
@czue 

I removed those as I don't think those are used any longer. The displays I saw look to use this anyways: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/domain/models.py#L887

**Comment by emord** [comment]
(I took out those changes)

**Comment by czue** [comment]
ok cool. I think we can actually delete those. am guessing all of our search stuff is powered by elastic

**Comment by czue** [comment]
(can address separately)

**Pull request merged**
