### PR TITLE
allow configuring additional case types for shadow modules

### PR DESCRIPTION
**Pull request by snopoke**
## Product Description
The 'additional case types' configuration is not inherited by Shadow Modules so allow users to configure it.

Jira: https://dimagi-dev.atlassian.net/browse/SUPPORT-12939

## Technical Summary
Show the "Additional Case List and Case Search Types" UI element for Shadow Modules.

There is also a small change to `Module.is_surveys` to check for any emtpy case type (None or empty string).
This impacts Shadow Modules that don't have a source menu selected makes the user do a browser refresh after selecting a source menu in order to get access to the case configuration tabs etc. I don't like having to make the user refresh the browser window but it should only be a one time thing. Also open to other suggestions.

An alternative to this approach would be to us the 'additional case types' setting from the source module.

## Feature Flag
USH_CASE_CLAIM_UPDATES

### Safety story
Small UI change tested locally.

### Automated test coverage
None

### QA Plan
I don't think this needs formal QA. The change has been tested locally.

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Code looks fine, but I'm surprised we're allowing the shadow's additional case types to be different from the source, instead of inheriting them, given that the main case type is inherited. Does the project need the additional case types to be different in the shadow?

**Comment by snopoke** [comment]
> Code looks fine, but I'm surprised we're allowing the shadow's additional case types to be different from the source, instead of inheriting them, given that the main case type is inherited. Does the project need the additional case types to be different in the shadow?

It does not. This was my initial take on unblocking the project since I wasn't sure if it made more sense to inherit vs override. If you think it makes more sense to inherit I'll go ahead and make that change instead.

**Comment by orangejenny** [comment]
Yeah, let's make it inherited.

**Comment by snopoke** [comment]
Closing to take a different approach

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/31255

**Pull request closed without merging**
