### PR TITLE
Remove child_health tableau ucr

### PR DESCRIPTION
**Pull request by emord**
can give it a couple of days before merging

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Comment by calellowitz** [comment]
Do you know why travis didnt run?

**Comment by emord** [comment]
@calellowitz it's running. possible that some comms between github and travis isn't working https://travis-ci.org/dimagi/commcare-hq/builds/435799550

**Comment by snopoke** [comment]
@emord has conflicts with master

**Comment by emord** [comment]
@calellowitz thoughts on pushing this out today?

**Comment by calellowitz** [comment]
Im for it

**Pull request merged**
