### PR TITLE
Revert "[ICDS Dashboard] Added captcha in registration page"

### PR DESCRIPTION
**Pull request by orangejenny**
Reverts dimagi/commcare-hq#28472

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Comment by orangejenny** [comment]
killed build

**Comment by orangejenny** [comment]
fyi @challabeehyv

**Comment by challabeehyv** [comment]
@orangejenny Thanks for the revert. I will check it now

**Comment by mkangia** [comment]
@challabeehyv please also test the registration without the setting enabled when you revert this back

**Comment by calellowitz** [comment]
@challabeehyv @mkangia 
Since registration is a core functionality (and one that ICDS doesn't even use) this should go through a real QA before release in addition to the self testing you mentioned.

I am a little curious how this came up in the audit though, since registration is disabled for our ICDS servers (you can't even get to this page).

**Comment by mkangia** [comment]
> I am a little curious how this came up in the audit though, since registration is disabled for our ICDS servers (you can't even get to this page)

@calellowitz the audit is being done on icds-staging where sign up is available. If that is the case I think we can consider removing sign up for icds-staging as well and then this should not be needed. Checking on that
thank you
fyi @challabeehyv

**Pull request merged**
