### PR TITLE
use is_commcare_user instead of isinstance

### PR DESCRIPTION
**Pull request by czue**
https://github.com/dimagi/commcare-hq/pull/27135#discussion_r407501194

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Comment by mkangia** [comment]
Build failure didn't look related, restarted failed job
```
custom.icds_reports.tests.agg_tests.test_aggregation_script:InactiveAWWsTest.test_submission_dates ... Exception in thread cchq-producer-network-thread:
Traceback (most recent call last):
  File "/vendor/lib/python3.6/site-packages/kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "/vendor/lib/python3.6/site-packages/kafka/producer/sender.py", line 160, in run_once
    self._client.poll(timeout_ms=poll_timeout_ms)
  File "/vendor/lib/python3.6/site-packages/kafka/client_async.py", line 598, in poll
    self._poll(timeout / 1000)
  File "/vendor/lib/python3.6/site-packages/kafka/client_async.py", line 631, in _poll
    end_select = time.time()
  File "/vendor/lib/python3.6/site-packages/freezegun/api.py", line 173, in fake_time
    if _should_use_real_time():
  File "/vendor/lib/python3.6/site-packages/freezegun/api.py", line 151, in _should_use_real_time
    if not ignore_lists[-1]:
IndexError: list index out of range
```

**Comment by czue** [comment]
feel like this PR won the code owner lottery.

**Comment by mkangia** [comment]
wait what lottery? @czue

**Comment by czue** [comment]
> wait what lottery? @czue

ha, just that i got four reviewers for free.

**Pull request merged**
