### PR TITLE
cachebust toggles.js on toggles.py and feature_previews.py changes

### PR DESCRIPTION
**Pull request by dannyroberts**
Here's my first pass at preventing situations like http://manage.dimagi.com/default.asp?240172 in the first place.

@snopoke @orangejenny cc: @czue 

touches every page and is a little clever so I'm going to test on staging first.

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
lgtm

**Comment by dannyroberts** [comment]
Update: I put it on staging, and staging is not completely broken

**Comment by dannyroberts** [comment]
And some more thorough local testing:

(all urls below start with `http://localhost:8000/a/droberts/toggles.js?username=droberts@dimagi.com&cachebuster=`)

| Run | cachebuster | observation |
|----|----|----|
| Start runserver | `0ce-897-4dc-638` |  |
| Restart runserver | `0ce-897-4dc-638` | no change |
| Change toggles.py | `85e-897-4dc-638` | first chunk changed | 
| Change feature_previews.py | `85e-fd6-4dc-638` | second chunk changed | 
| Revert toggles.py to what it was | `0ce-fd6-4dc-638` | first chunk went back to previous value |
| Revert feature_previews to what it was | `0ce-897-4dc-638` | back to original value |

In all cases it behaved as I expected.

**Comment by dannyroberts** [comment]
✅  Removing the don't merge label, I'm happy with this when you are.

**Comment by orangejenny** [comment]
Looks reasonable, happy to merge whenever you're comfortable with it, Danny.

**Pull request merged**
