### PR TITLE
record detailed timing for syncs > 5s

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
Putting this up as a potential means of getting more detailed data about sync timing. This saves the full timing context for syncs > ~1s~ 5s.

This will add more data to the synclog DB but most syncs are below ~1s~ 5s so it should not be overwhelming.

Analysis would require exporting synclog data for a time period and analysing the timing data.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
Covered by existing tests

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Seems reasonable if we expect to use it. Do you know how big the timing context data usually is, and/or do you have any estimates of what effect this might have on sync log storage?

**Comment by snopoke** [comment]
> Seems reasonable if we expect to use it. Do you know how big the timing context data usually is, and/or do you have any estimates of what effect this might have on sync log storage?

I've made a few updates to reduce the size. It's now ~850 characters of JSON data:
```
[{"name": "SyncElementProvider", "duration": 0.0001, "subs": []}, {"name": "RegistrationElementProvider", "duration": 0.0004, "subs": []}, {"name": "FixtureElementProvider", "duration": 0.0, "subs": []}, {"name": "CasePayloadProvider", "duration": 0.0265, "subs": [{"name": "get_case_ids_to_sync", "duration": 0.0223, "subs": []}, {"name": "process_case_batches", "duration": 0.0, "subs": []}, {"name": "update_index_trees", "duration": 0.0001, "subs": []}, {"name": "update_case_ids_on_phone", "duration": 0.0, "subs": []}, {"name": "move_no_longer_owned_cases_to_dependent_list_if_necessary", "duration": 0.0, "subs": []}, {"name": "purge_and_get_irrelevant_cases", "duration": 0.0, "subs": []}, {"name": "compile_response", "duration": 0.004, "subs": [{"name": "add_commtrack_elements_to_response", "duration": 0.004, "subs": []}]}]}]
```
I've also changed it to only record for syncs > 5s which is about 10% of all sync requests.

**Review by millerdev — APPROVED** [review]

**Comment by snopoke** [comment]
@dannyroberts do you think is useful enough to do?

**Comment by dannyroberts** [comment]
@snopoke I can see it being useful for a project to speed up sync timings. Sending it to datadog would be more likely to influence day to day operations, so I would see this as more useful for someone who's planning to do something specific with that data. Did you have a use in mind?

**Pull request closed without merging**
