### PR TITLE
Add new domain to asr report

### PR DESCRIPTION
**Pull request by Rohit25negi**
ticekt: https://dimagi-dev.atlassian.net/browse/ICDS-512

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Comment by mkangia** [comment]
Safe change so merging it and not waiting for the build

**Comment by lwyszomi** [comment]
Hi @Rohit25negi @mkangia I think after this merge we have failing test in ```userreports```:

```
FAIL: corehq.apps.userreports.tests.test_static_reports:TestStaticReportConfig.test_data_sources_actually_exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vendor/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/tests/test_static_reports.py", line 80, in test_data_sources_actually_exist
    self.assertEqual(0, len(configs_missing_data_source), msg)
AssertionError: There are 1 report configs which reference data sources that don't exist (or which don't exist on that domain):
static-icds-cas-sandbox-static-asr_4_6_infrastructure
```

**Comment by snopoke** [comment]
Fixed here: https://github.com/dimagi/commcare-hq/pull/24150

**Comment by mkangia** [comment]
Ah! sorry about that.
Thanks @snopoke

**Pull request merged**
