### PR TITLE
100% app preview

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride A day may come when the courage of men fails… but it is not THIS day.

cc: @snopoke @emord

### CODE REVIEW

**Comment by czue** [comment]
:muscle:

**Review by czue — APPROVED** [review]

**Comment by wpride** [comment]
💰

**Comment by benrudolph** [comment]
(will completely remove when we know we can handle the load)

**Review by snopoke — APPROVED** [review]
:1st_place_medal:

**Comment by benrudolph** [comment]
killed build

**Pull request merged**
