### PR TITLE
adding domain data to email tracking

### PR DESCRIPTION
**Pull request by calellowitz**
@sravfeyn 
wont pass tests until https://github.com/dimagi/dimagi-utils/pull/362 is merged, which it depends on.
This includes domain data for a some of our email tracking

### CODE REVIEW

**Comment by sravfeyn** [comment]
Looks good, I kicked the build again (now that submodule is merged). You can add the right submodule ref in the HQ PR, if build depends on the submodule PR, that way it doesn't matter whether the submodule PR is merged or not.

**Comment by calellowitz** [comment]
@sravfeyn rekicked build since submodules were updated and removed do not merge tag. good to know about updating refs in the pr. i will do that in the future.

**Comment by sravfeyn** [comment]
Build fail looks real https://travis-ci.org/dimagi/commcare-hq/jobs/124654502#L9846

**Comment by calellowitz** [comment]
:white_check_mark:

**Pull request merged**
