### PR TITLE
load saved select2 value in the UI

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?169035

### CODE REVIEW

**Comment by nickpell** [comment]
@czue I have this working when you choose a different saved reports in the "Favorites" dropdown.  However, it still doesn't work for the initial page load because the select2 widget isn't added to the page yet.  Do you know where in the code the widget gets added to the page?

**Comment by nickpell** [comment]
@NoahCarnahan code buddy

**Comment by nickpell** [comment]
```DynamicChoiceListFilter```

**Comment by czue** [comment]
@nickpell I had a rough time tracking down how that filter initialization happens. On the initial page load, the filters are set in javascript correctly, but not in the UI elements. Then the async call is made based off the javascript variables and the table gets properly updated. But I couldn't figure out how to get a handle to the filter elements from either when the ajax call gets made or inside the ajax callback. maybe you could just do it on page load though? I think `update_filters` was what I was looking for, so might just entail figuring out when to call it.

**Comment by nickpell** [comment]
good to go

**Comment by czue** [comment]
nice - worked out easier than I expected. these filters scare me.

**Pull request merged**
