### PR TITLE
delete cvsu custom

### PR DESCRIPTION
**Pull request by snopoke**
subscription lapsed and project no longer being funded
@sravfeyn

### CODE REVIEW

**Comment by czue** [comment]
```
Traceback (most recent call last):
  File "./manage.py", line 95, in <module>
    execute_from_command_line(sys.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/vendor/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vendor/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/vendor/lib/python2.7/site-packages/django/apps/config.py", line 119, in create
    import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named cvsu
```

**Comment by czue** [comment]
looks good on :white_check_mark: . nice :skull: / :baby: ratio

**Comment by snopoke** [comment]
todo at some point:

- [ ] delete ucr table
- [ ] delete cvsu fluff couch db

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
