### PR TITLE
Migrate ApiUser to SQL (1 of 3)

### PR DESCRIPTION
**Pull request by orangejenny**
Follows [docs](https://github.com/dimagi/commcare-hq/blob/master/docs/couch_to_sql_models.rst#practical-steps). This is a small one: simple model, only 3 documents on prod, no saving/syncing code necessary because ApiUsers only get created, not updated.

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Review by snopoke — COMMENTED** [review]
This model is used in so few places it hardly seems worth migrating - can we not kill it instead?

Uses:
* custom zipline integration
* j2me builds api

**Comment by orangejenny** [comment]
@snopoke Agree it'd be good to kill, but I don't have good domain knowledge here. Is there communication we'd need to do for the zipline project and/or j2me projects?

**Comment by snopoke** [comment]
@orangejenny yea, I'm not sure, we'd have to involve product and solutions I guess. Maybe not worth holding up the process now but probably still good to send a mail.

**Review by millerdev — APPROVED** [review]
Would be great to remove it if possible, but understandable if the coordination is more work than it's worth.

**Comment by orangejenny** [comment]
I'm going to go forward with this migration but also emailed Andrea & Dev about zipline. I found a 2018 note from Gio saying he was planning to remove it, so that's promising.

@snopoke What's the link between this and j2me builds? I only see the `api_user_basic_auth` decorator used in the zipline code. What would break if we removed ApiUser?

**Comment by snopoke** [comment]
@orangejenny there are two other decorators:
* `require_api_user` used here: https://github.com/dimagi/commcare-hq/blob/3ecf69fdc59af5e60496f0de018e3df721ae607e/corehq/apps/builds/views.py#L31-L32
* `require_api_user_permission` which is unused

**Comment by orangejenny** [comment]
@snopoke thanks, don't know how i missed those

**Pull request merged**
