### PR TITLE
DHIS2 API

### PR DESCRIPTION
**Pull request by kaapstorm**
Classes for managing DHIS2 API calls, and tests.

(Tests are going to fail without a DHIS2 test server, hence the `[ci skip]` commit message. Also, the server needs to be for testing only, because once DataValues have been added you can't completely tear down test data -- DHIS2 creates DataValueAudits that can only be deleted directly in PostgreSQL, so test organisation units, etc. can never be removed.)

@benrudolph cc @sheelio @snopoke

### CODE REVIEW

**Comment by kaapstorm** [comment]
@sheelio do we have a DHIS2 server we can use for testing? These tests create an org unit and add dummy data to it which we won't be able to delete, so maybe not great for a server we want to use for other stuff. Otherwise I can mark these tests to be skipped, and just test locally.

**Review by benrudolph — COMMENTED** [review]
is there anyway we can make this not dependent on a separate server? maybe by mocking out some of the responses?

**Comment by kaapstorm** [comment]
Good call @benrudolph I'll do that.

**Comment by kaapstorm** [comment]
To do:
 - [ ] Mock DHIS2 responses

**Comment by kaapstorm** [comment]
Closing this to PR off master

**Pull request closed without merging**
