### PR TITLE
OpenMRS Importers: Include ACE

### PR DESCRIPTION
**Pull request by kaapstorm**
Resolves RequireJS issue.

### CODE REVIEW

**Comment by emord** [comment]
should this include a revert of https://github.com/dimagi/commcare-hq/pull/24790 ?

**Comment by kaapstorm** [comment]
It was originally part of one, but its not the same cause, so I broke it out.

**Comment by orangejenny** [comment]
I'm confused as to how this is working, because in general requirejs pages don't use script tags and because `openmrs/js/openmrs_importers` already includes `hqwebapp/js/base_ace`, which already includes `ace-builds/src-min-noconflict/ace` (although it does not include the json, xml, or searchbox files, perhaps it should).

FWIW, ace is generally broken on both prod and india, but not icds, which suggests there's a py3-related problem (weird as that would be): https://dimagi-dev.atlassian.net/browse/HI-744

**Comment by kaapstorm** [comment]
Well I am confused too. By following [the steps to troubleshoot RequireJS](https://github.com/dimagi/commcare-hq/blob/master/docs/js-guide/migrating.md#troubleshooting-the-requirejs-build-process) locally, I managed to break the DHIS2 DataSet page (yay) and also the OpenMRS Importer (boo).

But I'm pretty sure I remember the OpenMRS Importer page working on prod, and the error message I am getting locally on the DHIS2 DataSet page is not the same as the error I saw on prod.

> ace is generally broken on both prod and india

I guess the silver lining is that my repro issues might have an explanation.

I'll close this.

**Comment by kaapstorm** [comment]
@orangejenny, ace seems to be working for UCRs on prod ... but the changes in this PR don't fix the OpenMRS Importers page in Py3. 

It might be related to the warning `build_requirejs` shows in Py3, but I'm not sure yet:
```
/usr/lib/python3.6/subprocess.py:786: ResourceWarning: subprocess 24261 is still running
  ResourceWarning, source=self)
/srv/share/src/dimagi/commcare-hq/corehq/ex-submodules/dimagi/utils/gitinfo.py:107: ResourceWarning: unclosed file <_io.BufferedReader name=11>
  url = sub_git_remote_url(git_dir)
```

I'll dig a little deeper, and see why the page to edit UCRs is working, but this page is not.

**Comment by orangejenny** [comment]
Huh, I didn't know `build_requirejs` was throwing an error in python 3. I wonder if it's related to this: https://github.com/dimagi/commcare-hq/pull/24875 ...I'll take a look, but probably not for a couple of days.

**Pull request closed without merging**
