### PR TITLE
IntraHealth Reports - change fields in calculations and small fixes

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue @fyniac 
need reindex a RecouvrementFluffPillow

### CODE REVIEW

**Comment by czue** [comment]
:+1: when tests pass.

**Comment by lwyszomi** [comment]
@czue tests passed

**Comment by lwyszomi** [comment]
@czue 

Do you know if anyone restarted the pillow after the deploy?

**Comment by czue** [comment]
oops I don't think so. I can do that now.

**Comment by lwyszomi** [comment]
@czue 

Thanks

**Comment by czue** [comment]
(done)

**Pull request merged**
