### PR TITLE
CDN! 

### PR DESCRIPTION
**Pull request by benrudolph**
:horse_racing: :horse_racing: @dannyroberts 

cc: @NoahCarnahan

### CODE REVIEW

**Comment by benrudolph** [comment]
we're rolling! :roller_coaster: g2m after tests

**Comment by benrudolph** [comment]
we have to make sure the cache busting works properly, but merging this won't have any affect on prod since i haven't updated the `STATIC_CDN` localsetting on prod

**Comment by benrudolph** [comment]
it should just "work" cause we append a version number to all the files

**Comment by czue** [comment]
neat

**Comment by czue** [comment]
does this mean that HQ is magically going to switch to a CDN on next deploy/

**Comment by benrudolph** [comment]
as long as i deploy localsettings and `deploy_proxy` it should :sweat_smile:

**Pull request merged**
