### PR TITLE
Restore vellum-staging in staging.yaml

### PR DESCRIPTION
**Pull request by millerdev**

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
@millerdev Have you run rebuildstaging with this?

**Comment by millerdev** [comment]
@orangejenny I have not. Does that need to be done? I'm guessing there is nothing new or interesting on vellum-staging, so it can likely be reset to master. Does that sound right to you?

**Comment by millerdev** [comment]
Killed the build.

**Comment by millerdev** [comment]
I did this just now to resolve any merge conflicts with vellum-staging:
```
$ git fetch
$ git branch -f vellum-staging origin/master
$ git push -f origin vellum-staging
```
This means the same version of vellum that is currently on master will also be deployed on staging.

**Pull request merged**
