### PR TITLE
ICDS: Update Aggregation

### PR DESCRIPTION
**Pull request by sheelio**
@emord 

Fixed this branch and merged master

### CODE REVIEW

**Comment by emord** [comment]
@sheelio This looks fine to me. I thought you were going to add some columns to the model though?

**Comment by sheelio** [comment]
@emord 
I don't think we need to extend the module (the model already has the columns needed).

**Comment by sheelio** [comment]
The dashboard team wants to start QA-ing and testing this by next Wednesday - can we deploy this and time this with the data copying changes?

**Comment by emord** [comment]
@sheelio looks like this can be merged, but still has the don't merge tag on.

**Review by emord — APPROVED** [review]

**Pull request merged**
