### PR TITLE
Profile Aggregate SQL

### PR DESCRIPTION
**Pull request by sravfeyn**
Replacing the [other PR](https://github.com/dimagi/commcare-hq/pull/20145) with this, after rebasing. (I now remember why I merge instead of rebase, I would have had to do force push which I don't like)

### CODE REVIEW

**Review by emord — APPROVED** [review]
Thanks. This looks good. A test failed, but it wasn't clear that it was related, so I kicked the build

**Comment by emord** [comment]
Looks like it's now failing on a migration conflict.

Also I'm hoping to parallelize this script and move it away from this large custom SQL script in https://github.com/dimagi/commcare-hq/pull/20143 Would it be possible to change this to work off that PR since the migration needs to be changed anyways

**Comment by sravfeyn** [comment]
Okay, this is not needed anymore since that other PR tracks timing between task using `celery_task_logger`, right? https://github.com/dimagi/commcare-hq/pull/20143/files#diff-b8c5a5e308a203bcaee8ed83e6837edfR149

**Comment by emord** [comment]
> Okay, this is not needed anymore since that other PR tracks timing between task using celery_task_logger, right?

`celery_task_logger` only outputs info to the celery log file.

I think this sort of profiling is still very useful so that we can easily view the history of the task without diving through logs.

**Comment by sravfeyn** [comment]
https://github.com/dimagi/commcare-hq/pull/20370

**Pull request closed without merging**
