### PR TITLE
case search auto_launch expression

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
HQ portion of https://dimagi-dev.atlassian.net/browse/USH-914

Convert case search `auto_launch` attribute from a string (`true`, `false`) to an expression:
* "$next_input = '' or count(instance('casedb')/casedb/case[@case_id=$next_input]) = 0"
* "false()"

## Feature Flag
USH_CASE_CLAIM_UPDATES (case_claim_autolaunch)

## Product Description
Fix for edge case interaction between case claim and end-of-form navigation

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
Existing tests

### QA Plan
QA alongside:
* https://github.com/dimagi/formplayer/pull/958
* https://github.com/dimagi/commcare-core/pull/989

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by snopoke** [comment]
@shubham1g5 let me know when the formplayer stuff is on staging and I'll deploy this to staging as well

**Comment by shubham1g5** [comment]
@snopoke Thanks, would you be able to deploy both formplayer and HQ for this. I have added to the formplayer staging.yml and resolved conflcits so it should be smooth.

**Comment by snopoke** [comment]
> @snopoke Thanks, would you be able to deploy both formplayer and HQ for this. I have added to the formplayer staging.yml and resolved conflcits so it should be smooth.

done

**Comment by shubham1g5** [comment]
@snopoke merging this as we have a pass from QA.

**Pull request merged**
