### PR TITLE
Don't trigger a reorder when changing module settings

### PR DESCRIPTION
**Pull request by esoergel**
https://dimagi-dev.atlassian.net/browse/HI-716

This happened only with a particular combination of feature flags and addons.  In particular, `BASIC_CHILD_MODULE` had to be disabled.  At any rate, the issue was that `oldRoot` was `""` and `newRoot` was `undefined`, since the the select parent widget was only available for advanced modules.  Since `"" !=== undefined`, this incorrectly triggered a reorder.

@orangejenny @biyeun @nickpell

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Seems fine to merge if it works, but it also seems a bit difficult to understand what's going on.

Just based on your description of the issue, is it possible there's some logic that's currently looking only at the flag that should also look at the module type? I glanced around and only found [this](https://github.com/dimagi/commcare-hq/blob/788cb3a98dc1b323b3012570beef9446a39c625b/corehq/apps/app_manager/views/modules.py#L203-L205) which looks like it's already always set to True for advanced modules.

**Comment by esoergel** [comment]
@orangejenny 
> is it possible there's some logic that's currently looking only at the flag that should also look at the module type?

I don't think so - `newRoot` comes from `'select[name=root_module_id]'`, which is the widget that lets you choose a parent menu:

image

It's correct that that not appear for basic modules where `BASIC_CHILD_MODULE` is disabled.  The issue is that the value of that widget is `undefined` if it's missing.  This change coerces any falsy values to `null` so the comparisons will work correctly.

I could modify this to be a bit more explicit - this whole listener is irrelevant if the widget is missing, so maybe this would explain the intent better?
```javascript
var $parentModuleSelector = $(this).find('select[name=root_module_id]');
if ($parentModuleSelector.length = 0) {
    return;
}
```

**Comment by orangejenny** [comment]
@esoergel Ah, I see, thanks for explaining. I do like your proposed change.

**Comment by orangejenny** [comment]
@esoergel sweet, thanks for updating. Can't you remove the `|| null` now?

**Comment by esoergel** [comment]
> Can't you remove the `|| null` now?

Yes, probably, though I kinda prefer it - feels safer knowing all falsy types will compare properly.  I could see one of those two things accidentally being switched to `null` or `undefined` rather than `""`, and this is a pretty subtle bug.

**Pull request merged**
