### PR TITLE
Remove Kafka specific logic from PillowCheckpoint

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

**Review by commit**

The `KafkaPillowCheckpoint` subclass of `PillowCheckpoint` exists to be used with pillows that process changes from Kafka, which makes the Kafka logic in the `PillowCheckpoint` class redundant and unnecessary (as far as I can tell). The logic in `update_to` is duplicated across the two classes at the moment. I removed the Kafka specific logic in `PillowCheckpoint`, and changed any `PillowCheckpoint` instantiations to `KafkaPillowCheckpoint` if the pillow referenced a Kafka change feed.

### Safety story

Will put this on staging for a bit to see if any issues pop up. Knowing that all uses of `PillowCheckpoint` don't interact with a KafkaChangeFeed makes me feel pretty good about this change.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
I'm tempted to just remove the `self.assertEqual(pillow.get_last_checkpoint_sequence(), {})` line in the failing test as I don't think that check is necessary and gets the test passing, but I'm noticing some state being saved across test runs and want to dig into that more tomorrow anyway so I'll hold off on pushing any new commits.

**Review by snopoke — COMMENTED** [review]
Build failing:

```
  ======================================================================
  FAIL: corehq.apps.change_feed.tests.test_kafka_change_feed:KafkaCheckpointTest.test_dont_create_checkpoint_past_current
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/mnt/commcare-hq-ro/corehq/apps/change_feed/tests/test_kafka_change_feed.py", line 111, in test_dont_create_checkpoint_past_current
      self.assertEqual(pillow.get_last_checkpoint_sequence(), {})
  AssertionError: {TopicPartition(topic='web-user', partitio[58 chars]): 0} != {}
  + {}
  - {TopicPartition(topic='commcare-user', partition=0): 0,
  -  TopicPartition(topic='web-user', partition=0): 0}
```

**Comment by calellowitz** [comment]
Is the usage in https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/change_feed/pillow.py#L77 going to be an issue

**Comment by gherceg** [comment]
@calellowitz my understanding is that Pillow reads from the couch change feed, and therefore the PillowCheckpoint is the appropriate class to use, even after the Kafka logic has been stripped out. If that understanding isn't right then this PR is likely toast.

**Review by joxl — APPROVED** [review]
This somehow disappeared from my radar (I think it was pushed while I was on PTO). I'll defer final approval to other devs who have a better understanding of checkpoints than I do, but from a high level, this looks like a valuable change (DRY, code reorg, etc).

**Comment by gherceg** [comment]
Thanks for bringing attention to this again @joxl. Fwiw this has been deployed to staging since December 26th, and there don't seem to be any issues with pillows on staging.

**Review by snopoke — COMMENTED** [review]
It seems like the `KafkaPillowCheckpoint` overrides all of the methods of the base class and doesn't ever call the super methods. This makes me think that it should be a standalone class and shouldn't inherit from `PillowCheckpoint` at all.

**Comment by gherceg** [comment]
Agreed @snopoke. See d21544ce55e84ffa2c9771c991d2b3fe65ba1200

**Review by snopoke — APPROVED** [review]

**Comment by gherceg** [comment]
I held off on merging since I am going to be offline for awhile. If someone else wants to merge this and take responsibility for monitoring pillows, please do! Otherwise I'll get back to it September 👍🏻

**Comment by gherceg** [comment]
Clearly not worth making this change so closing for now.

**Pull request closed without merging**
