### PR TITLE
support remote apps

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @NoahCarnahan prs are getting a bit backed up here, but this includes this PR: https://github.com/dimagi/commcare-hq/pull/12664

Everything after https://github.com/dimagi/commcare-hq/commit/8c2595a6d9726dca24181647d21814eb05e2b5be is new. this will finally support remote app migration. When it detects that any remote apps are being migrated, it will turn on user defined columns for exports flag. then any columns/tables that have been skipped because we couldn't find them in the schema are automatically added as a user defined column/table.

cc: @esoergel @orangejenny

### CODE REVIEW

**Comment by czue** [comment]
not reviewing closely but high level plan sounds good to me. 

> When it detects that any remote apps are being migrated, it will turn on user defined columns for exports flag. then any columns/tables that have been skipped because we couldn't find them in the schema are automatically added as a user defined column/table.

not sure if this question makes sense, but do we also want/need to do this step for any export that has questions that don't match the schema?

**Comment by benrudolph** [comment]
@czue it's very difficult to tell if something is a system property that was automatically checked or a question from a remote app if the column is not found in the schema. i'm fairly confident all questions and case properties will be properly migrated and found in the schema if they made their application on HQ. 

i'm going to try and run a few more dry runs on real HQ to see more of the types of columns we're skipping. i'd rather not expose the user defined columns if we don't have to. up for debate though

**Comment by czue** [comment]
makes sense. maybe we could store the non-migrated fields as a property on the export document and that way if we need them down the line they are there? just a thought - not sure how hard it is to retroactively build that list after the migration happens.

**Comment by benrudolph** [comment]
that's fair, we do store all of the skipped (and converted) columns in a migration meta doc. from these i think we could fairly easily create user defined columns. i'll do a pass and see if we have enough information to recreate

**Comment by benrudolph** [comment]
anyone want to offline and review this with me? would like to get this in

**Comment by orangejenny** [comment]
hey, apologies for the code review backlog. i'll aim to do it this afternoon, will grab you if needed.

**Comment by benrudolph** [comment]
no worries, this one has all the other PRs' commits. so this is really the only pending

**Pull request merged**
