### PR TITLE
fix old exports page in django 1.10

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?250116

@emord

### CODE REVIEW

**Comment by nickpell** [comment]
cc: code buddy @esoergel

**Review by emord — APPROVED** [review]

**Comment by benrudolph** [comment]
do we not have to reconcile the `choices` param in some way?

**Comment by nickpell** [comment]
@benrudolph It seems to work fine without ```choices```.  I don't think it was being used in the first place.  Compare [current docs](https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#django.forms.Widget.render) with [past docs](https://docs.djangoproject.com/en/1.9/ref/forms/widgets/#django.forms.Widget.render).

**Comment by benrudolph** [comment]
weird, ok makes sense. thanks

**Pull request merged**
