### PR TITLE
replace default case reindexer with new one

### PR DESCRIPTION
**Pull request by snopoke**
@emord

### CODE REVIEW

**Comment by snopoke** [comment]
```
======================================================================
FAIL: test_case_reindexer_v2 (testapps.test_pillowtop.tests.test_reindexer.PillowtopReindexerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/testapps/test_pillowtop/tests/test_reindexer.py", line 74, in test_case_reindexer_v2
    self._assert_case_is_in_es(case)
  File "/mnt/commcare-hq-ro/testapps/test_pillowtop/tests/test_reindexer.py", line 123, in _assert_case_is_in_es
    self.assertEqual(1, results.total)
AssertionError: 1 != 0
```

**Comment by snopoke** [comment]
needs changes from https://github.com/dimagi/commcare-hq/pull/12320

**Comment by emord** [comment]
Looks good. will wait on other pr

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
self merging

**Pull request merged**
