### PR TITLE
Update form mm export to use same filter as other export download

### PR DESCRIPTION
**Pull request by mkangia**
## Summary

https://dimagi-dev.atlassian.net/browse/INDIV-12

Review by commit.

Currently the form multimedia download only considers the date filter and user types, whereas when one filters for forms, all filters are applied. This is confusing on the UI, since its on the same page.
Looks like a pending improvement in multimedia exports. Last change was in 2016, https://github.com/dimagi/commcare-hq/pull/13477.

This PR updates form multimedia download to use the same filter setup as the usual form download in order to consider the same set of forms, to filter for ones with multimedia.

More context and details in comment https://github.com/dimagi/commcare-hq/pull/29552#issuecomment-829562388

## Product Description

When downloading form multimedia, users will now get the **correct** set of form multimedia according to the filters set.
Do we need to notify users in a certain way?

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### QA Plan

https://dimagi-dev.atlassian.net/browse/QA-2886
Majorly looking for that things are still working. The specifics of the filters need not be worried about since they are already working in form export.

### Safety story

QA was done.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
Thanks, I like how this turned out.

**Comment by mkangia** [comment]
thanks @millerdev,

QA begins next week, hopefully will be a smooth one.

**Comment by mkangia** [comment]
@dimagi/product want to run this by you once. QA is done and this is ready to go.

Adding more details to the description.

This PR changes or fixes the filters for the form multimedia download.

Context:
The source of change was from a ticket that said that users were not able to download form multimedia by a specific user because the export was so large that the download was not permitted by HQ, which was unexpected since there weren't many such submissions for the user.
Turned out that form multimedia does not allow filtering for a specific user, even though the filter is shown on the UI and works fine for form exports.
Both form export and multimedia export, are available on the same page. [Example](https://staging.commcarehq.org/a/ccqa2-2/data/export/custom/new/form/download/72cef1416973138f5b5c991a0e00349d/)

The form multimedia export just considers two things as of now
1. [User type](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/export/views/download.py#L441) with [mapping](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/export/forms.py#L1002-L1009): lets you filter for Mobile users, demo users, Supply and unknown (unknown includes unknown, system and web)
2. [Date Span](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/export/views/download.py#L440): to filter by form received_on timestamp

This PR:
changes the form multimedia export to use the same filters as form export so that same set of forms are considered.
The difference being mainly now supporting new filters like specific user, group etc just like form export. 
With respect to originally supported filters,
1. User Types are now mapped a bit differently. There is no grouping for unknown user type, instead its one to one mapping for all types as seen [here](https://github.com/dimagi/commcare-hq/blob/7317d90296c36ed04597ddc7063400a9359150a0/corehq/apps/export/forms.py#L722). There are filters for unknown users and web users if there is a need. But there is no filter for system users.
2. Date span works as before on form received_on timestamp as seen [here](https://github.com/dimagi/commcare-hq/blob/7317d90296c36ed04597ddc7063400a9359150a0/corehq/apps/export/forms.py#L754)

All of this should be okay considering, ideally, we should be sharing multimedia for the forms that are available in the form export with the same set of filters.

fyi @millerdev @esoergel feel free to weigh in or add anything

**Comment by kmishra100** [comment]
SaaS product has no issues with this change.

**Comment by biyeun** [comment]
Looks good @mkangia

**Comment by mkangia** [comment]
thanks all, merging this now!

**Pull request merged**
