### PR TITLE
Subtree merge pillowtop and fluff

### PR DESCRIPTION
**Pull request by czue**
can just look at a few commits towards the bottom to make sense of this.

opening for tests for now. @snopoke I wasn't planning on also doing ctable since it's so close to being deprecated. let me know if you disagree with that thinking though (since ctable depends on fluff and pillowtop this essentially means that development is frozen if dev on those moves here)

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 87 errors:

* corehq/ex-submodules/fluff/__init__.py, line 1 - F401 'exceptions' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 2 - F401 'EmitterValidationError' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 3 - F401 'BACKEND_COUCH' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 3 - F401 'BACKEND_SQL' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 4 - F401 'Calculator' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'custom_date_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'custom_null_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'date_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'null_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 7 - F401 'filter_by' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'AttributeGetter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'FlatField' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'IndicatorDocument' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 9 - F401 'FluffPillow' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 10 - F401 'indicator_document_updated' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 19 - F401 'fluff' imported but unused
* corehq/ex-submodules/fluff/indicators.py, line 231 - E124 closing bracket does not match visual indentation
* corehq/ex-submodules/fluff/pillow.py, line 118 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/signals.py, line 2 - F401 'pprint' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 7 - F401 'chain' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 8 - F401 'signals' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 9 - F401 'get_pillow_class' imported but unused
* corehq/ex-submodules/fluff/tests/tests.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 175 - E501 line too long (118 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 178 - E501 line too long (124 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 179 - E501 line too long (124 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 180 - E501 line too long (116 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 182 - E501 line too long (129 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 183 - E501 line too long (128 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 184 - E501 line too long (131 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 187 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/tests/tests.py, line 219 - E501 line too long (119 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 273 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 314 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 315 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 357 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 364 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 365 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 405 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 423 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 463 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/tests/tests.py, line 504 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 505 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 506 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 507 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 508 - E501 line too long (132 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 509 - E501 line too long (130 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 563 - E303 too many blank lines (2)
* corehq/ex-submodules/pillow_retry/models.py, line 13 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillow_retry/models.py, line 22 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillow_retry/models.py, line 60 - E501 line too long (140 > 115 characters)
* corehq/ex-submodules/pillow_retry/models.py, line 143 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tasks.py, line 28 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tests.py, line 99 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tests.py, line 100 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillowtop/admin.py, line 16 - W391 blank line at end of file
* corehq/ex-submodules/pillowtop/checkpoints/manager.py, line 54 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/es_utils.py, line 61 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/listener.py, line 1 - F401 'copy' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 5 - F401 'TransportError' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'create_index_for_pillow' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'initialize_mapping_if_necessary' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'pillow_index_exists' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'pillow_mapping_exists' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 48 - E303 too many blank lines (3)
* corehq/ex-submodules/pillowtop/listener.py, line 516 - E501 line too long (167 > 115 characters)
* corehq/ex-submodules/pillowtop/management/commands/ptop_es_manage.py, line 46 - E701 multiple statements on one line (colon)
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 13 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 14 - E121 continuation line under-indented for hanging indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 15 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 16 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 17 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 18 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 45 - E221 multiple spaces before operator
* corehq/ex-submodules/pillowtop/management/commands/ptop_run_docs.py, line 3 - F401 'LabelCommand' imported but unused
* corehq/ex-submodules/pillowtop/management/commands/run_ptop.py, line 6 - F401 'get_pillow_instance' imported but unused
* corehq/ex-submodules/pillowtop/management/pillowstate.py, line 1 - F401 'get_es' imported but unused
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 5 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 12 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 41 - W391 blank line at end of file
* corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py, line 1 - F401 'copy' imported but unused
* corehq/ex-submodules/pillowtop/tests/test_import_pillows.py, line 68 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 1 - Missing name in function declaration.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 17 - ['group_by'] is better written in dot notation.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 18 - ['date'] is better written in dot notation.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 18 - ['value'] is better written in dot notation.
* corehq/ex-submodules/fluff/fluff_filter/_design/filters/domain_type.js, line 1 - Missing name in function declaration.

**Comment by dimagimon** [comment]
There are 87 errors:

* corehq/ex-submodules/fluff/__init__.py, line 1 - F401 'exceptions' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 2 - F401 'EmitterValidationError' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 3 - F401 'BACKEND_COUCH' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 3 - F401 'BACKEND_SQL' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 4 - F401 'Calculator' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'custom_date_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'custom_null_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'date_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 6 - F401 'null_emitter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 7 - F401 'filter_by' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'AttributeGetter' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'FlatField' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 8 - F401 'IndicatorDocument' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 9 - F401 'FluffPillow' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 10 - F401 'indicator_document_updated' imported but unused
* corehq/ex-submodules/fluff/__init__.py, line 19 - F401 'fluff' imported but unused
* corehq/ex-submodules/fluff/indicators.py, line 231 - E124 closing bracket does not match visual indentation
* corehq/ex-submodules/fluff/pillow.py, line 118 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/signals.py, line 2 - F401 'pprint' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 7 - F401 'chain' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 8 - F401 'signals' imported but unused
* corehq/ex-submodules/fluff/signals.py, line 9 - F401 'get_pillow_class' imported but unused
* corehq/ex-submodules/fluff/tests/tests.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 175 - E501 line too long (118 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 178 - E501 line too long (124 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 179 - E501 line too long (124 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 180 - E501 line too long (116 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 182 - E501 line too long (129 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 183 - E501 line too long (128 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 184 - E501 line too long (131 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 187 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/tests/tests.py, line 219 - E501 line too long (119 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 273 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 314 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 315 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 357 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 364 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 365 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/fluff/tests/tests.py, line 405 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 423 - E126 continuation line over-indented for hanging indent
* corehq/ex-submodules/fluff/tests/tests.py, line 463 - E303 too many blank lines (2)
* corehq/ex-submodules/fluff/tests/tests.py, line 504 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 505 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 506 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 507 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 508 - E501 line too long (132 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 509 - E501 line too long (130 > 115 characters)
* corehq/ex-submodules/fluff/tests/tests.py, line 563 - E303 too many blank lines (2)
* corehq/ex-submodules/pillow_retry/models.py, line 13 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillow_retry/models.py, line 22 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillow_retry/models.py, line 60 - E501 line too long (140 > 115 characters)
* corehq/ex-submodules/pillow_retry/models.py, line 143 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tasks.py, line 28 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tests.py, line 99 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillow_retry/tests.py, line 100 - E226 missing whitespace around arithmetic operator
* corehq/ex-submodules/pillowtop/admin.py, line 16 - W391 blank line at end of file
* corehq/ex-submodules/pillowtop/checkpoints/manager.py, line 54 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/es_utils.py, line 61 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/listener.py, line 1 - F401 'copy' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 5 - F401 'TransportError' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'create_index_for_pillow' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'initialize_mapping_if_necessary' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'pillow_index_exists' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 28 - F401 'pillow_mapping_exists' imported but unused
* corehq/ex-submodules/pillowtop/listener.py, line 48 - E303 too many blank lines (3)
* corehq/ex-submodules/pillowtop/listener.py, line 516 - E501 line too long (167 > 115 characters)
* corehq/ex-submodules/pillowtop/management/commands/ptop_es_manage.py, line 46 - E701 multiple statements on one line (colon)
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 13 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 14 - E121 continuation line under-indented for hanging indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 15 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 16 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 17 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 18 - E127 continuation line over-indented for visual indent
* corehq/ex-submodules/pillowtop/management/commands/ptop_reset_checkpoint.py, line 45 - E221 multiple spaces before operator
* corehq/ex-submodules/pillowtop/management/commands/ptop_run_docs.py, line 3 - F401 'LabelCommand' imported but unused
* corehq/ex-submodules/pillowtop/management/commands/run_ptop.py, line 6 - F401 'get_pillow_instance' imported but unused
* corehq/ex-submodules/pillowtop/management/pillowstate.py, line 1 - F401 'get_es' imported but unused
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 5 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 12 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/pillowtop/run_pillowtop.py, line 41 - W391 blank line at end of file
* corehq/ex-submodules/pillowtop/tests/test_elasticsearch.py, line 1 - F401 'copy' imported but unused
* corehq/ex-submodules/pillowtop/tests/test_import_pillows.py, line 68 - E302 expected 2 blank lines, found 1
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 1 - Missing name in function declaration.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 17 - ['group_by'] is better written in dot notation.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 18 - ['date'] is better written in dot notation.
* corehq/ex-submodules/fluff/_design/views/generic/map.js, line 18 - ['value'] is better written in dot notation.
* corehq/ex-submodules/fluff/fluff_filter/_design/filters/domain_type.js, line 1 - Missing name in function declaration.

**Comment by czue** [comment]
alright just tested this on staging and looks good to go. @benrudolph @snopoke would be nice to get this in so that I can start doing prospective dev in HQ.

**Comment by czue** [comment]
easiest way to review is to just go to the [commits tab](https://github.com/dimagi/commcare-hq/pull/9585/commits) and look at changes from yesterday

**Comment by benrudolph** [comment]
ok this looks fine to me. seems like a lot of the code is just moved over (which makes sense). the commits to remove the submodule look good

**Comment by benrudolph** [comment]
this ain't gonna help your :heavy_plus_sign: / :heavy_minus_sign: ratio

**Comment by czue** [comment]
> this ain't gonna help your :heavy_plus_sign: / :heavy_minus_sign: ratio

:disappointed:

**Comment by czue** [comment]
@dimagi/team-commcare-hq pillowtop and fluff as submodules are no more! you should feel free to 

```
rm -r submodules/pillowtop-src
rm -r submodules/fluff-src
```

:boom:

**Comment by benrudolph** [comment]
:tada: :cake:

**Comment by dannyroberts** [comment]
:tada:

>> this ain't gonna help your :heavy_plus_sign: / :heavy_minus_sign: ratio
>
> :disappointed: 
Probably won't change your stats. Since you're just merging these commits into your branch, I don't think you're accountable for them stat-wise.

**Comment by snopoke** [comment]
Sorry, slow to respond here. Re the question about ctable, I don't think that should be an issue. The ctable code hasn't seen any changes in a while and as you say we're hoping to get rid of it soon.

**Pull request merged**
