### PR TITLE
Mk/update notification

### PR DESCRIPTION
**Pull request by mkangia**
Getting too many notification so reducing that.
Also dump the dict correctly.

### CODE REVIEW

**Comment by emord** [comment]
You're currently using `send_mail_async` directly https://github.com/dimagi/commcare-hq/blob/0f814368e4984a8b348e1b759916feae73ff262a/corehq/apps/receiverwrapper/util.py#L232

Why aren't you using `soft_assert`? That's the canonical way to do this and it includes an exponential back off to make sure you don't get too many emails.

Using `send_mail_async` also means you'll get emails from third party environments. Those usually have soft asserts turned off

**Comment by mkangia** [comment]
thanks for inputs @emord
Two things:
1. i would need all the emails/occurrences. I just filtered out the case that was causing noise so now I would get email only for relevant notifications which we are hoping to catch and hopefully rare.
2. this is set only for ICDS env so should not be receiving it from other envs
So this should be fine?

**Comment by emord** [comment]
That makes sense. Its not clear to me from this PR why this is set only for ICDS, but will trust you about that.

Its probably a good practice to consistently use soft_assert and turn off exponential backoff if necessary, but not required for this PR

**Review by emord — APPROVED** [review]

**Comment by mkangia** [comment]
> That makes sense. Its not clear to me from this PR why this is set only for ICDS, but will trust you about that.

@emord 
This is probably happening just for some older versions of CommCare but that can't be said with confirmation and has been raised only for ICDS that these submissions are causing issues for them, hence only set for ICDS.

**Review by snopoke — APPROVED** [review]

**Pull request merged**
