### PR TITLE
fix typo in mvp migration logging

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue @biyeun — ok if I run this by doing the following on hqdb0 as soon as this is merged?

```bash
cchq@hqdb0$ git fetch master
cchq@hqdb0$ git checkout origin/master custom/_legacy/mvp/management/commands/mvp_migrate_lesser_case_types_mar2015.py
# run command, etc
cchq@hqdb0$ git checkout --custom/_legacy/mvp/management/commands/mvp_migrate_lesser_case_types_mar2015.py
```

**Comment by czue** [comment]
i didn't quite follow the git commands above. can't you just checkout latest master in the preindex directory and not worry about doing anything else fancy?

**Comment by dannyroberts** [comment]
@czue yeah that's better, I'll do that

**Comment by dannyroberts** [comment]
Thanks!

**Pull request merged**
