### PR TITLE
Only show label if field has a value

### PR DESCRIPTION
**Pull request by emord**
Noticed this if you have a first name, but not last name

selection_056

cc: @TylerSheffels

### CODE REVIEW

**Comment by orangejenny** [comment]
aww, B2. B3 fixes `.dl-horizontal` so this doesn't happen, which is good for the couple dozen other places we use it.

**Comment by benrudolph** [comment]
what vigilance when protecting that email address

**Comment by benrudolph** [comment]
no tests, merging

**Comment by czue** [comment]
> what vigilance when protecting that email address
lol i was thinking the same thing

**Pull request merged**
