### PR TITLE
Cache repeat record send

### PR DESCRIPTION
**Pull request by benrudolph**
@gcapalbo @czue this will _drastically_ improve the performance. this makes the requests scale to the number of repeaters, not the number of repeat records. this broke when we moved to using `requests` library. https://github.com/dimagi/dimagi-utils/commit/11b17b3845910bf07064df5b5f3680bb673bd793

:fish: or :office:

### CODE REVIEW

**Comment by benrudolph** [comment]
we probably should deploy this asap so we don't send duplicate records

**Comment by czue** [comment]
:shipit:

**Comment by gcapalbo** [comment]
when we skip processing a record under these circumstances, do we still end up saving the repeat record (and thus giving it a new revision)?

because the if it doesn't get a new revision it won't try to reprocess it for another day based on the lock timeout on the process repeat record task

**Comment by benrudolph** [comment]
@gcapalbo yep essentially we catch the error and save it as the failure reason. in the `process_repeat_record` function we call `save` after `fire`

**Pull request merged**
