### PR TITLE
move remaining ICDS UITab additions to extension points

### PR DESCRIPTION
**Pull request by snopoke**
##### RISK ASSESSMENT / QA PLAN
Tested this locally. One issue is that these will now only be available on the `icds-cas` domain. That is the same as the current state but if we need to expose these on another domain it will require a code change instead of updating a toggle.

### CODE REVIEW

**Comment by mkangia** [comment]
> One issue is that these will now only be available on the icds-cas domain

Extracting the domain name as a constant would be helpful in case we need to do something in future.

**Comment by mkangia** [comment]
the links were pretty embedded in the views on HQ, are you saying they would retain their orginial spot or appear in the end or the sections/tabs?

**Comment by snopoke** [comment]
> the links were pretty embedded in the views on HQ, are you saying they would retain their orginial spot or appear in the end or the sections/tabs?

@mkangia  Do you mean the same place in the UI. I believe they will stay in the same place yes.

**Comment by mkangia** [comment]
that is great!

**Review by mkangia — APPROVED** [review]

**Pull request merged**
