### PR TITLE
Make Globe more Global

### PR DESCRIPTION
**Pull request by biyeun**
why so north america centric, yo?

http://manage.dimagi.com/default.asp?222996#1126033

cc @orangejenny @esoergel 

screen shot 2016-04-13 at 5 19 53 pm

### CODE REVIEW

**Comment by orangejenny** [comment]
beauteous

**Comment by snopoke** [comment]
Nice B! I would love to be able to do more design stuff but it's just not worth the effort on Linux.

**Comment by czue** [comment]
:earth_africa:

**Comment by biyeun** [comment]
@snopoke have you looked at [inkscape](https://inkscape.org/en/)? It's an open source vector graphics program and fairly decent. Then there's [font forge](https://fontforge.github.io/en-US/) which I haven't used but I've heard good things about it for linux

**Comment by benrudolph** [comment]
🌏 what about dem aussies!

**Comment by esoergel** [comment]
I've played with inkscape before and found it powerful.  No idea how to edit `.glyphs` files on linux though.

**Comment by snopoke** [comment]
Yea I do use inkscape. It was editing the font files that couldn't get
working.

**Pull request merged**
