### PR TITLE
Add ability to control which non-admin roles can assign a non-admin role

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/ICDS-1414

##### SUMMARY
Add ability to let a role be assigned only by specific roles

##### PRODUCT DESCRIPTION
Enhancing the ability to control if a role can be assigned by non admins.
Just like on the roles UI a user has ability to give access to all reports or few reports to a role, adding a similar UI interface for a user to define a role assignable by specific roles and not all non-admins, so that when other non-admin users who can assign a role to a mobile or web user, they only see roles marked as accessibly for all non-admins or marked accessible for their own role.

Sneak preview [here](https://recordit.co/LvvsHZRqC4)

@dimagi/product happy to put this behind a feature flag if needed.

### CODE REVIEW

**Comment by djmore9** [comment]
This is great. 👍🏽

**Comment by esoergel** [comment]
@mkangia @djmore9  What did you think of my suggestion on slack for an alternative approach?  That is:

Users should not be able to assign roles with permissions they themselves don't have.
Users _should_ be able to assign roles where the permissions are a subset of their own permissions.

The nice thing about that approach is that it doesn't require the user to configure anything, nor for us to store relationships between roles or consider edge cases around roles changing.

**Comment by mkangia** [comment]
Hey @esoergel 
That would be a nice general implementation for HQ for better security. 
However this use case is a bit different.
What we need here is that the admin controls which roles can assign a certain role. It's possible they don't want to even allow a higher level role to assign a lower role.
For example,
I have
1. Admin - access to everything
2. (non-admin) Role Handler - access to everything and manages role assignments
2. (non-admin) State - access to everything except mobile workers
3. (non-admin) District - access to everything except mobile workers and web users

Now we want that users at Role handler can assign State and District roles but don't want State to be able to assign District role to anyone. 
For example: someone at State can reassign another user with State role to District and block them, and that needs to be protected, which can't be done by current role settings.

**Comment by mkangia** [comment]
@orangejenny @esoergel 
Offlined about this with @djmore9 and confirmed that it's good to go without a feature flag, so this should be good to review now.
Ethan, 
let me know if you still have queries on the process.

**Comment by mkangia** [comment]
apologies @calellowitz @kaapstorm @millerdev @proteusvacuum @Rohit25negi @snopoke 
for the unexpected review request. Bad merge. Feel free to ignore this.

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
@esoergel this is gtg?
responded to your suggestion in https://github.com/dimagi/commcare-hq/pull/27627#issuecomment-635598672

**Pull request merged**
