### PR TITLE
[OPM] Add error messages to all InvalidRows

### PR DESCRIPTION
**Pull request by esoergel**
Just make errors more descriptive.  Anyone feel free to merge.  @czue @sravfeyn FYI

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by esoergel** [comment]
Failure looks unrelated.  The opm tests pass locally

**Comment by twymer** [comment]
Seeing the same test timeout elsewhere.

**Comment by czue** [comment]
nice, thanks

**Pull request merged**
