### PR TITLE
bulk ES pillow processor

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
ES pillow processor that uses the [bulk ES API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html). I think this is a good idea for 2 reasons:

1. It should reduce the connection load on ES and possibly other load depending on how ES handles these.
2. Having mixed batch and serial processors in a pillow makes it harder to reason about what's happening in the pillow.

Pillows using bulk:
* case-pillow
* form-pillow
* SqlSMSPillow
* user-pillow

### CODE REVIEW

**Review by emord — APPROVED** [review]
These changes look good. I particularly like moving from custom bulk operations to the ES library's implementation. The test failures do look related to the PR though

**Comment by dannyroberts** [comment]
Could this have caused https://sentry.io/organizations/dimagi/issues/1292940649/?environment=production&project=136860&query=is%3Aunresolved? This PR went out with the deploy yesterday, after which that error started happening. Just asking based on that and a rough match of keywords

```
NotImplementedError: this function not yet implemented
  File "pillowtop/pillow/interface.py", line 210, in _batch_process_with_error_handling
    retry_changes, change_exceptions = processor.process_changes_chunk(changes_chunk)
  File "pillowtop/processors/elastic.py", line 101, in process_changes_chunk
    bad_changes, docs = bulk_fetch_changes_docs(changes_chunk)
  File "pillowtop/utils.py", line 332, in bulk_fetch_changes_docs
    new_docs = list(doc_store.iter_documents(doc_ids_to_query))
  File "corehq/form_processor/document_stores.py", line 141, in iter_documents
    for doc in self.store.iter_documents(ids):
  File "pillowtop/dao/interface.py", line 27, in iter_documents
    raise NotImplementedError('this function not yet implemented')
```

**Comment by dannyroberts** [comment]
I think this also caused another error, where xforms from the sql backend aren't getting their `external_blobs` copied over to elasticsearch: https://dimagi-dev.atlassian.net/browse/SAASP-10112. I think the fix is to use `.to_json(include_attachments=True)` if it's an `XFormInstanceSQL` here https://github.com/dimagi/commcare-hq/blob/33535d3ad874053b0e14ae11bb40cd7f51c111d4/corehq/form_processor/document_stores.py#L38-L39.

**Comment by dannyroberts** [comment]
This is past the statute of limitations, but I just noticed (I think because we recently separately had a big bout of pillow errors) that this PR likely introduced this error https://sentry.io/organizations/dimagi/issues/1292223056/?project=136860&query=is%3Aunresolved, an error that happens during the handling of pillow errors. Not sure if the fix is just to use `item.get('error')`, but I'll take a look

**Pull request merged**
