### PR TITLE
Remove USE_FORMPLAYER flag

### PR DESCRIPTION
**Pull request by wpride**
@benrudolph more flag cleanup.

cross-request https://github.com/dimagi/touchforms/pull/281

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]
👍 no one is depending on this flag right

**Comment by wpride** [comment]
Just me, you, Clark, and Biyeun https://www.commcarehq.org/hq/flags/edit/use_formplayer/

**Comment by benrudolph** [comment]
solid crew

**Comment by czue** [comment]
...and icds? https://india.commcarehq.org/hq/flags/edit/use_formplayer/

not really following this, just making sure you are also checking india server if you're breaking flags...

**Comment by benrudolph** [comment]
good catch, sorry didn't actually look at the links. i think in this case it doesn't matter because use formplayer frontend is turned on for them so they get all use_formplayer features + the new frontend

**Pull request merged**
