### PR TITLE
update checkpoints after 5 mins

### PR DESCRIPTION
**Pull request by snopoke**
On envs that don't have a lot of changes the checkpoints can take a very long time to get updated. This still relies on a change coming through to trigger the update but will still reduce the time between updates.
@gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
build failure looks related to change processing, not sure if it's related to this pr

**Review by czue — APPROVED** [review]
i kicked the build but i think it was real (and looking at your last commit it looks like maybe you had intentionally added it to get more info?). 

agree with Giovanni's comment but looks good to me.

**Comment by gcapalbo** [comment]
(looks good to me, but build still failing)

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
