### PR TITLE
Removed question labels altogether when they have no content

### PR DESCRIPTION
**Pull request by orangejenny**
## Product Description
https://dimagi-dev.atlassian.net/browse/USH-3891

### Safety story
~~Quite small, although in a very visible UI. Did smoke testing locally. Relying on code review for safety assurance.~~ Decided to request QA.

### Automated test coverage

no

### QA Plan

https://dimagi-dev.atlassian.net/browse/QA-5951

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by Robert-Costello — APPROVED** [review]
This looks good to me. The only risk I could see is not displaying a Question when it should be. It looks like any cases where a Question should be displayed are covered here.

**Comment by Jtang-1** [comment]
Following Robert's thought, maybe it's safer to make an "isEmptyLabel" property and use `hidden` instead. That'll change the failure mode to showing an empty space rather than hiding a label that should be shown.

**Review by nospame — APPROVED** [review]
Makes sense to me. I don't remember, does `visible` remove it from the DOM or just hide its content? My only concern might be a question's label column disappearing and leaving the question to take an odd amount of row space.

**Comment by orangejenny** [comment]
Updated to address @nospame 's point.

**Review by stephherbers — APPROVED** [review]

**Pull request merged**
