### PR TITLE
ICDS: Fix indicators to handle the seeking_services flag

### PR DESCRIPTION
**Pull request by sheelio**
This fixes up a number of indicators so they don't count the case if the case is not seeking services at the AWC center.  

@emord for review

### CODE REVIEW

**Comment by emord** [comment]
Build failure looks real. Also it looks like you're adding a column and renaming a column. this will require a full rebuild. is that ok?

**Comment by sheelio** [comment]
@emord 

Pretty sure that I'm not adding a column (I think that's the diff being weird).   Fixed the build failure though.

**Comment by sheelio** [comment]
Ah I see that re-arranged the columns.  Will fix.

**Comment by sheelio** [comment]
After looking again, don't think the columns were re-arranged (the order is still bp3_complete, pnc_complete and postnatal).

**Review by emord — APPROVED** [review]
Yeah just a weird diff. looks good. is it important to deploy today?

**Comment by sheelio** [comment]
Nope, not important to deploy today.  Just wanted to wrap up the data source changes (this shouldn't have any impact on the existing data since the app hasn't been updated to negate the seeking_services indicator).

**Pull request merged**
