### PR TITLE
[ICDS] rename indicators in the wasting report

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi @Rohit25negi @calellowitz 

I added change for the ticket: https://dimagi-dev.atlassian.net/browse/ICDS-470, I changed the labels and calculations, so now we will have the same data as we have in the program summary report.

Need QA: Yes
Environment: ICDS
Locally Tested: Yes

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Comment by Rohit25negi** [comment]
This looks good. But This says QA, Should not this be released under FF first?

**Comment by Rohit25negi** [comment]
@lwyszomi  can you put this under FF

**Comment by Rohit25negi** [comment]
ping! @lwyszomi  This should be going under FF

**Comment by lwyszomi** [comment]
@Rohit25negi updated

**Review by Rohit25negi — APPROVED** [review]
did you tested it and checked if it is working fine and FF on/off working fine

**Comment by lwyszomi** [comment]
Yes I tested this and all working fine

**Pull request merged**
