### PR TITLE
Fixtures db prep

### PR DESCRIPTION
**Pull request by dannyroberts**
This is seeming really simple because (we knew this before, but I rechecked):
- `fixtures` views don't reference any other doc types
- no other views reference fixtures doc types

The process to complete the migration is something like
1. merge and deploy this PR
2. run initial and continuous migrations ([docs](https://github.com/dimagi/commcare-hq/blob/master/corehq/doctypemigrations/README.md#run-the-doctype-migration))
3. Make another PR flipping the db and deploy that
4. kill continuous and eventually delete docs form old db (also in the docs above)

### CODE REVIEW

**Comment by dannyroberts** [comment]
For an idea of size of the migration:

| Doc Type | Doc Count | View Count |
|---|---|---|
| FixtureDataItem | 390,899 | 2 |
| FixtureDataType | 2,058 | 1 |
| FixtureOwnership | 267,390 | 1 |

**Comment by benrudolph** [comment]
nice i was looking into this a bit. how come we don't have to change the `corehq/apps/domain/_design/views/related_to_domain/map.js`. i know you made a change for this on your previous migration but i still didn't really grok why it worked

anyways this is awesome! :star:

**Comment by dannyroberts** [comment]
@benrudolph yeah the reason is because I'm opting to sync the domain views to the new db as well. The reason I had to add those views back (if you look at the commits, they're reverts) is that I was assuming `_design/domain` wouldn't exist on the new db.

**Comment by benrudolph** [comment]
gotcha, thanks for the explanation

**Comment by czue** [comment]
:+1: to merge as soon as it's confirmed that these DBs have been created on prod and india

**Comment by czue** [comment]
and yeah - this is great!

**Comment by dannyroberts** [comment]
Looks like these dbs were already created earlier. Also, I think what I said earlier was wrong and that the way we're set up currently, these dbs can create themselves both on prod and india.

**Comment by czue** [comment]
nice, good to know about the DBs

**Pull request merged**
