### PR TITLE
Remove help text flag

### PR DESCRIPTION
**Pull request by emord**
2.19 is being released

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@emord good to merge or are we waiting for official release notice?

**Comment by emord** [comment]
@czue I was told 2.19 was being released today, so should be good to go right?

**Comment by czue** [comment]
I think so, @christineawhite @ctsims @amsagoff @orangejenny et. al. can confirm. I think occasionally releases get delayed at the last minute for unexpected reasons.

**Pull request merged**
