### PR TITLE
remove custom.openlmis and unused calling code

### PR DESCRIPTION
**Pull request by dannyroberts**
https://trello.com/c/dcfnPhR0/14-openlmis-integration-code

There were two steps to my process here (could have been two different commits but I didn't think of it until after):
1. search the code for places outside of `custom/openlmis` that the text `custom.openlmis` or `custom/openlmis` appeared. For each place, see how the import was being used and verify that I can get rid of it (they were all either in unused functions, or could be deleted after deleting unused url endpoints). Delete any templates or other things no longer used.
2. delete everything under `custom/openlmis`

In reviewing this, I'd focus mostly on everything outside the `custom/openlmis` directory, but it might be worth validating that everything in the `custom/openlmis` directory can be deleted.

### CODE REVIEW

**Comment by dannyroberts** [comment]
@gcapalbo buddy

**Comment by dannyroberts** [comment]
@czue FYI I think you were largely involved in this?

**Comment by gcapalbo** [comment]
wow, -1966.  looks ok to me

**Comment by czue** [comment]
looks good but I think the :rabbit: :black_circle: goes even further. you should go digging in `custom.requisitions`. it looks like at least `RequisitionCase` can be removed and possibly the whole module

**Comment by czue** [comment]
(this is g2g from my side either way)

**Comment by dannyroberts** [comment]
Thanks for the tip! Give me a day to look it over and I'll decide whether to roll it into this PR or do it separately.

**Comment by dannyroberts** [comment]
Nice
```
$ ag custom.requisitions --ignore locale/
custom/requisitions/utils.py
3:from custom.requisitions.const import UserRequisitionRoles

custom/requisitions/signals.py
7:from custom.requisitions.models import RequisitionCase
8:from custom.requisitions.utils import get_notification_recipients, get_notification_message
```

No code outside `custom.requisitions` imports from it. Sounds like a clean delete to me!

**Comment by gcapalbo** [comment]
:+1: from my side, will let @czue sign off

**Comment by czue** [comment]
:egg: :shell: :ant:

**Pull request merged**
