### PR TITLE
Remove b3 floating footer

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @biyeun @dimagi/product hey guys based on some feedback and my own struggles i've moved the black bar to the bottom of the screen (the way it was in b2). let me know if there's a strong reason not to do this. here are some screen shots:
screen shot 2015-12-11 at 5 39 55 pm
screen shot 2015-12-11 at 5 39 48 pm
screen shot 2015-12-11 at 5 39 30 pm

### CODE REVIEW

**Comment by orangejenny** [comment]
I don't think dropping the animation is the end of the world, but I'm curious what the struggles were - are you finding the code hard to work with, or product-wise do you think it's a bad feature?

**Comment by benrudolph** [comment]
it's not the animation, it's the fact that it floats at the bottom of the window (instead of the page) and covers up a lot of things. it's been a source of bugs and removes the ability to have anything else stick to the bottom of the window (cloudcare debugger). happy to discuss, this has just been the general sense i've gotten from people

**Comment by amsagoff** [comment]
We're still going to have to rethink this for form builder, but this seems
like an easy win for b3 pages. Thanks Ben!

**Comment by biyeun** [comment]
So, this isn't quite the same functionality as b2. Consider a screen where the content is shorter than the height of the window. And as @amsagoff hinted, this was implemented to handle full-page views like form builder.

screen shot 2015-12-11 at 1 29 41 pm

**Comment by czue** [comment]
i'm definitely pro this change if it reduces bugs related to the black bar. guessing it won't fix all of them, but just to note how common they come up: 
- http://manage.dimagi.com/default.asp?146903
- http://manage.dimagi.com/default.asp?179126
- http://manage.dimagi.com/default.asp?180562
- http://manage.dimagi.com/default.asp?185874
- http://manage.dimagi.com/default.asp?187328
- http://manage.dimagi.com/default.asp?183956
- http://manage.dimagi.com/default.asp?183566

**Comment by benrudolph** [comment]
@biyeun maybe as a halfway we can leave the functionality in and if a "full
screen" flag is enabled then the floating footer appears. Otherwise the
default is off. What do you think?

**Comment by millerdev** [comment]
Can you add screenshots of what this looks like on the form builder page (before/after)? Also, how does it work when performing various scroll/zoom operations on the form builder page:
- scroll over the left menu bar
- scroll over the footer
- fullscreen the form builder

**Comment by benrudolph** [comment]
@millerdev this doesn't affect formbuilder just pages that are currently in b3. i'm shooting to make all pages have the same functionality as the current b2 footer. currently working on fixing that issue biyeun mentioned when the screen is larger than the content

**Comment by millerdev** [comment]
@benrudolph thanks for the clarification

**Comment by biyeun** [comment]
@benrudolph The issue I have with this change is that the footer doesn't actually stick to the bottom now (see the screen shot I added).

**Comment by biyeun** [comment]
@benrudolph the screenshot I added, perhaps confusing because there is no border around the image, shows a huge chunk of white space below the footer, because the content before the footer is smaller than the height of the window.

**Comment by benrudolph** [comment]
Yep i see it, good catch. Just didn't get a chance to fix today

**Comment by biyeun** [comment]
@benrudolph cool! just wanted to clarify the issue i saw...realize it might not have been clear :+1:

**Comment by czue** [comment]
woohoo!

**Pull request merged**
