### PR TITLE
Upgrade pycryptodome to specific commit until next release

### PR DESCRIPTION
**Pull request by dannyroberts**
a small number of keys generated by pycrypto
are not readble by pycryptodome https://github.com/Legrandin/pycryptodome/issues/188

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Comment by emord** [comment]
`ImportError: No module named Crypto.Cipher`

Maybe this commit is broken in other ways/

**Comment by dannyroberts** [comment]
The error here is due to a pycryptodome (silently) not supporting `-e` install (and `pip-compile` not supporting non-editable install from URL). The commit we need, https://github.com/Legrandin/pycryptodome/commit/0df6211, is already in their master branch, and historically they've made releases pretty regularly, so I asked whether they had a timeline for the next release including this fix, so far without reply. 😞

Our options are
- abandon `pip-compile` because of this restriction
  - drawback: we'd either have to give up fully-pinning requirements or replace it with another tool like pipenv
- wait until the next release is out
  - this means leaving the bug live for maybe quite some time
- revert back to pycrypto
  - annoying to keep making people do; has known security vulnerabilities, though I'm not sure if we're exposed to them
- add a temporary manual install step after pip install that just installs this

**Comment by emord** [comment]
Is there a previous version of pycryptdome that does not have this issue we could roll out?

**Comment by dannyroberts** [comment]
I don't think there is, I think it was an obscure bug in there from there start.

**Comment by dannyroberts** [comment]
Note to myself for how to reproduce install issue:
```
$ mkvirtualenv crypto
```
This fails:
```
(crypto) $ pip uninstall pycryptodome ; pip install -e git+https://github.com/Legrandin/pycryptodome@0df6211#egg=pycryptodome==3.6.4; python -c 'import Crypto'
Uninstalling pycryptodome-3.6.4:
  Would remove:
    /Users/droberts/.virtualenvs/crypto/lib/python2.7/site-packages/Crypto/*
    /Users/droberts/.virtualenvs/crypto/lib/python2.7/site-packages/pycryptodome-3.6.4.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled pycryptodome-3.6.4
Obtaining pycryptodome==3.6.4 from git+https://github.com/Legrandin/pycryptodome@0df6211#egg=pycryptodome==3.6.4
  Updating ./.virtualenvs/crypto/src/pycryptodome clone (to revision 0df6211)
  Did not find branch or tag '0df6211', assuming revision or ref.
Installing collected packages: pycryptodome
  Running setup.py develop for pycryptodome
Successfully installed pycryptodome
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Crypto
```
This works:
```
(crypto) $ pip uninstall pycryptodome ; pip install git+https://github.com/Legrandin/pycryptodome@0df6211#egg=pycryptodome==3.6.4; python -c 'import Crypto'
Uninstalling pycryptodome-3.6.4:
  Would remove:
    /Users/droberts/.virtualenvs/crypto/lib/python2.7/site-packages/pycryptodome.egg-link
Proceed (y/n)? y
  Successfully uninstalled pycryptodome-3.6.4
Collecting pycryptodome==3.6.4 from git+https://github.com/Legrandin/pycryptodome@0df6211#egg=pycryptodome==3.6.4
  Cloning https://github.com/Legrandin/pycryptodome (to revision 0df6211) to /private/var/folders/rg/2s009hs57c1d5jtcs0ckz9wh0000gn/T/pip-install-MjCmHL/pycryptodome
  Did not find branch or tag '0df6211', assuming revision or ref.
Building wheels for collected packages: pycryptodome
  Running setup.py bdist_wheel for pycryptodome ... done
  Stored in directory: /private/var/folders/rg/2s009hs57c1d5jtcs0ckz9wh0000gn/T/pip-ephem-wheel-cache-U3i9LB/wheels/6d/a5/ad/ab1853b3b1cd5d71086166eaaf647a707a2540b680a111fd71
Successfully built pycryptodome
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.6.4
```

**Comment by dannyroberts** [comment]
I got this very helpful suggestion from Jeremy Bowman at EdX:

> Until the relevant pip-tools bug is resolved, we've been using a shell script to post-process the generated requirements files and strip off the "-e" prefix which had to be added to keep pip-compile happy: https://github.com/edx/edx-platform/blob/master/scripts/post-pip-compile.sh#L17 .  Doing this, the "-e" is only there while pip-compile downloads it to fetch its dependencies; when actually installing dependencies from the generated requirements files, it won't use an editable install.  There are some more notes about this at http://open-edx-proposals.readthedocs.io/en/latest/oep-0018-bp-python-dependencies.html , which outlines our current guidelines for Python dependency management.

My plan is to implement that. (Hopefully it will also solve the related airflow issue https://github.com/dimagi/commcare-hq/pull/21251#discussion_r206856694.)

**Review by emord — APPROVED** [review]

**Pull request merged**
