### PR TITLE
remove unused logger

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by benrudolph** [comment]
note you have to also remove it here: https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/roles/commcarehq/templates/localsettings.py.j2#L177

**Comment by nickpell** [comment]
@benrudolph is there a reason for the redundancy?  It seems like having this setting in two repos, one of which always gets ignored on production machines due to localsettings, is ripe for confusion

**Comment by benrudolph** [comment]
absolutely ripe for confusion. i think the purpose is so we can have different logging on our local machines than the production machines. though it seems like we should just have the production machines always use the `settings.py` file and not override it in the localsettings. just never got around to changing it

**Comment by nickpell** [comment]
seems like the right behavior is to default to the specifications in ```settings.py```, and use ```localsettings.py``` only if you need to override (just like it's normally used)

**Comment by benrudolph** [comment]
yep i think we're on the same page. this is just legacy

**Pull request merged**
