### PR TITLE
[ICDS] Added translations for Kannada

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi

I sent next part of translations for the 2BI, 2BII and 2CI reports in the ICDS project.

Please let me know if you have any questions.

Regards,
Łukasz

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
will it cause an error if we tail the change with "," in the new line added i.e add "," in the end already so that when we add new ones next time only those show as changed for review?

**Comment by calellowitz** [comment]
@mkangia 
I think trailing commas are not allowed in JSON

**Comment by lwyszomi** [comment]
@mkangia @calellowitz Yes, in JSON we cant add a trailing comma. This cause the wrong format in JSON.

**Comment by mkangia** [comment]
Ya, thought so. Thanks

**Pull request merged**
