### PR TITLE
Add test time limit

### PR DESCRIPTION
**Pull request by millerdev**
Fail any test that runs for longer than 29 seconds unless the limit is overridden with `corehq.util.test_utils.timelimit`. This should detect super long running tests if a change is made that causes service (e.g., elasticsearch) timeouts that do not otherwise cause tests to fail.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
How confident are you that all tests should run in under 29sec, other than the ones you've decorated in this PR?

**Comment by orangejenny** [comment]
```
ERROR: custom.inddex.tests.test_master_report:TestFixtures.test_conversion_factors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vendor/lib/python3.6/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/vendor/lib/python3.6/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/vendor/lib/python3.6/site-packages/django/test/testcases.py", line 213, in __call__
    super(SimpleTestCase, self).__call__(result)
AssertionError: run time limit (29.0) exceeded: 29.660715579986572
```

**Comment by millerdev** [comment]
@orangejenny 

> How confident are you that all tests should run in under 29sec, other than the ones you've decorated in this PR?

I'm tracking down the ones that take longer and decorating them. Hopefully this game of wack-a-mole doesn't last too long.

Some of the added timeouts are going to stick around indefinitely (database setup, for example). However, in some cases I think it's highlighting things that could be optimized (making it possible to remove the `timelimit`).

**Review by esoergel — APPROVED** [review]

**Comment by millerdev** [comment]
Pass/fail record on https://github.com/dimagi/commcare-hq/pull/27433/commits/2cab2662f5efb2949e2d6c17071e8c9a30196e96:

- First run: all passed.
- Restarted Job 1 (the most recent job to fail). Pass.
- Restarted all: (in progress)

**Comment by millerdev** [comment]
Some commits from this PR have been split out into separate PRs (https://github.com/dimagi/commcare-hq/pull/27475, https://github.com/dimagi/commcare-hq/pull/27476, https://github.com/dimagi/commcare-hq/pull/27477) so they can be merged sooner, making tests faster while I continue to work on stability on this branch.

**Comment by millerdev** [comment]
travis builds on b9d774d:
1. all pass
2. ...

**Comment by millerdev** [comment]
travis builds on https://github.com/dimagi/commcare-hq/pull/27433/commits/297b510e7e89d2da3974ab7511f5f680c9c2ef07:

1. job 4 fail - network error at 6 minutes
2. ...

**Comment by millerdev** [comment]
travis builds on https://github.com/dimagi/commcare-hq/pull/27433/commits/2d8495305cce8331c9173bd5899c863696d6b361:

1. all pass
2. ...

**Comment by millerdev** [comment]
I think this is ready for final review and merge.

**Review by dannyroberts — APPROVED** [review]

**Comment by dannyroberts** [comment]
🥳

**Comment by millerdev** [comment]
@dimagi/team-commcare-hq this PR adds a time limit of 29s to every test (as well as `setUpClass` and `tearDownClass`). The limits can be overridden and extended as needed for very long tests, and there are examples of how to do that in this PR (please use sparingly).

**Comment by mkangia** [comment]
Nice! this is great @millerdev , thanks for adding this.

**Pull request merged**
