### PR TITLE
don't crash on null entries

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?157434

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@snopoke it looks like this was a side effect of https://github.com/dimagi/commcare-hq/pull/5534. not sure if there's a cleaner fix.

**Comment by twymer** [comment]
`for thing in things or []` works too, though maybe less explicit about the possibility of `None`

**Comment by snopoke** [comment]
@czue was an issue with the decorator: https://github.com/dimagi/pillowtop/pull/107

**Comment by czue** [comment]
ah, that makes much more sense

**Pull request merged**
