### PR TITLE
run tests with ownership cleanliness actually enabled, bugfixes

### PR DESCRIPTION
**Pull request by czue**
can be read commit-by-commit. mostly just setting up a way to create ownership cleanliness flags on submission for tests.

@snopoke cc @NoahCarnahan (sorry about all the review)

wait for tests

### CODE REVIEW

**Comment by snopoke** [comment]
Nothing blocking but will wait for tests.

**Comment by czue** [comment]
thanks - responded and hopefully fixed tests

**Comment by snopoke** [comment]
looks good. Kicked build

**Comment by czue** [comment]
:white_check_mark: finally!

**Pull request merged**
