### PR TITLE
Remove supervisor_id IS NULL from ccs_record_monthly and child_health_monthly

### PR DESCRIPTION
**Pull request by emord**
Just creating draft for now since tests are effed

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]
Seems fine. it will silently lose data, which i don't love. but i think thats better than the agg failing?

**Comment by calellowitz** [comment]
can we maybe log cases that are excluded by this

**Comment by emord** [comment]
> Seems fine. it will silently lose data, which i don't love. but i think thats better than the agg failing?

records with supervior_id = NULL won't be inserted into the base table when we roll out those primary key changes to the UCR

**Comment by emord** [comment]
Been a couple of merge conflicts since last approval. @calellowitz want to give one final approval?

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
