### PR TITLE
A/B test background image on account creation

### PR DESCRIPTION
**Pull request by orangejenny**
code buddy @calellowitz 
@NoahCarnahan can you double-check the KISSmetrics code?
cc @dimagi/product & @biyeun 

"plain" version:
screen shot 2016-04-06 at 5 37 08 pm

"molly" version:
screen shot 2016-04-06 at 5 36 54 pm

### CODE REVIEW

**Comment by biyeun** [comment]
@orangejenny hmm, the whitespace around the login form could be a little better. It might be a good idea to continue the type of styling from the main hq static site, where the form is on top of a blue background. The white background on top of the image seems off-putting

**Comment by czue** [comment]
looks awesome! should be a fun test

possibly a terrible idea but maybe also make the create account popup a tiny bit transparent? (thinking of the [expensify login page](https://www.expensify.com/signin))

**Comment by orangejenny** [comment]
@biyeun Which part of prelogin do you mean? The main page is almost totally blue, with images only really visible when you scroll, whereas this page doesn't have (much) scrolling.

@czue Sounds all right to me, might make the white-on-photo less jarring. I'll play with some transparency.

**Comment by NoahCarnahan** [comment]
KISSmetrics code looks good 👍

**Comment by biyeun** [comment]
@orangejenny the workflow should look a little more seamless starting with the [email] (sign up for free) button on the first page of the prelogin site.

**Pull request merged**
