### PR TITLE
Kill most pact reports

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
See conversation [here](https://github.com/dimagi/commcare-hq/pull/28032#issuecomment-896066805).

I removed the 4 top-level reports that are broken: All Patients, DOT Patient List, PACT DOT Admin, and PACT CHW Admin. I left the single patient report alone since it still works, although I suspect that it isn't accessible with both the "All Patients" and "DOT Patient List" reports broken. I left the top-level "CHW Management" report alone since it works, but the individual CHW profile page it links to is broken, so I removed that.

Slightly annoyingly, the reason I'm looking at this is that https://github.com/dimagi/commcare-hq/pull/30232/ updated code that's only used by pact...and it turns out that code is in the single patient report, so I didn't actually remove it.

## Product Description
See above.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

There are some tests for pact reports.

### QA Plan

Not requesting QA.

### Safety story
Removed custom reports that are broken. This could possibly break related custom reports if I removed code that's still used and doesn't have test coverage, though these reports aren't used much. I'll smoke test after deploy that the remaining CHW management report still loads.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
:star2:

**Review by millerdev — APPROVED** [review]
Thank you! There is also probably more pact stuff that can be removed too. Namely, [tasks.py](https://github.com/dimagi/commcare-hq/blob/7cec77fd3d9dee29f6a1b827237eeb37dbf84a68/custom/_legacy/pact/tasks.py) and [signals.py](https://github.com/dimagi/commcare-hq/blob/7cec77fd3d9dee29f6a1b827237eeb37dbf84a68/custom/_legacy/pact/signals.py) since https://github.com/dimagi/commcare-hq/pull/30228 has been merged.

**Comment by orangejenny** [comment]
cool, added 4ef9ec57701f5a1142130f4d04274dc23daccc9d

**Comment by snopoke** [comment]
:grinning: image

**Pull request merged**
