### PR TITLE
App manager v2: reload page on rearrange forms/modules

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?256730

For once I'm unhappy to be deleting code. Rearranging forms/modules without refreshing the page is a better experience. But there are quite a few urls that use the index-based id, and missing updating one of them has rather severe consequences (overwriting a module/form's settings).

@benrudolph / @biyeun

### CODE REVIEW

**Review by benrudolph — COMMENTED** [review]
oh man that is a big bummer. code looks fine. is it easy to detect when things aren't going to work?

**Comment by orangejenny** [comment]
@benrudolph The real fix would be to update the various URLs that take `module_id` and instead pass in unique module id. It's not a huge task; I'm admittedly being kind of lazy.

**Comment by biyeun** [comment]
@orangejenny I can take that on over the weekend.

**Comment by orangejenny** [comment]
@biyeun okay, cool, will leave this open for now in case you have other stuff come up, but won't merge

**Comment by orangejenny** [comment]
Biyeun's fix has turned out to be more involved than expected, I'd like to deploy this in the interim, will revert when the more robust fix is ready.

new code buddies @kaapstorm @gcapalbo

**Comment by biyeun** [comment]
@orangejenny noted. thanks.

**Pull request merged**
