### PR TITLE
More config options for case forwarding

### PR DESCRIPTION
**Pull request by sravfeyn**
https://docs.google.com/document/d/1Xu1leevGYuAx6O-Y4hdN0ogYdjGp92fJyzEb1IAd6lU/edit#

### CODE REVIEW

**Comment by sravfeyn** [comment]
@wpride Here's the screenshot for the two extra options we are adding for MobileODT
screen shot 2016-01-11 at 10 38 17 pm

**Comment by sravfeyn** [comment]
cc @snopoke, buddy @biyeun

**Comment by wpride** [comment]
:+1:

**Comment by snopoke** [comment]
looks good @sravfeyn. PR still marked as 'don't merge'

**Comment by sravfeyn** [comment]
Yeah, waiting for product to confirm if having this on core is alright.

**Comment by snopoke** [comment]
👍

**Comment by sravfeyn** [comment]
@amsagoff Is this good to go be core product path?

**Comment by snopoke** [comment]
@sravfeyn I'm pretty sure this can just be released as is. Also not mergable.

**Comment by sravfeyn** [comment]
Cool, g2g @snopoke

**Comment by snopoke** [comment]
:+1: once tests pass

**Comment by amsagoff** [comment]
sorry for the late reply, g2g from my perspective

**Pull request merged**
