### PR TITLE
Modify blob export for multiple existing archives

### PR DESCRIPTION
**Pull request by esoergel**
##### SUMMARY
The blob exporter skips blobs already present in an existing archive (or more than one), but to do so, it must read the whole archive into memory.  I hit an OOM error trying to this for REC, so I used `split` to break it up into 8 smaller archives.  This PR is two changes to support that:

* Don't concat all existing archive names to get the new one - this hits the filename character limit.
* Add a help message and some basic logging to show progress through the filenames

##### RISK ASSESSMENT / QA PLAN
Nah, isn't used in production

### CODE REVIEW

**Comment by esoergel** [comment]
Actually it looks like this won't solve the problem fully - the split files aren't properly formatted tar archives on their own, so python's `tarfile` can't read them.  I don't think `tarfile` has the capability to ennumerate the names of the items in an archive in a memory-efficient manner.  I'm playing around with using `$ tar --list` to get that list, and may change this mgmt cmd to accept a list of known items rather than dealing with existing archives in memory.  Any ideas?

**Review by kaapstorm — APPROVED** [review]

**Comment by millerdev** [comment]
> 

Does [`tarfile.next()`](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.next) read the entire tarfile into memory? Similarly, this may work (inspired by first comment on [SO answer](https://stackoverflow.com/a/2018576/10840)):
```py
existing.update(info.name for info in tarfile)
```

**Comment by kaapstorm** [comment]
> Does tarfile.next() read the entire tarfile into memory?

Good question! The motivation for switching from zip to tar was memory efficiency. Tar files [don't have a table of contents](https://en.wikipedia.org/wiki/Tar_(computing)#Random_access). Iterating members, like Daniel suggested, sounds like the right way to do this. Uglier, but faster, would be to save the list of members separately when we dump the blobs.

**Comment by esoergel** [comment]
> Does tarfile.next() read the entire tarfile into memory? Similarly, this may work (inspired by first comment on SO answer):

I believe it does - if you jump to source for `tarfile` there's a `_loaded` attribute that about every method seems to reference.  At any rate, I tried doing that yesterday evening and still got runaway memory issues.

The approach I'm working on now is to use `$ tar --list` to get a list of the blob names in the archive, then passing that in rather than trying to process the tarfile in python.  It's still really big (31M names), so just loading them into a set takes like 6GB RAM, but that should be tolerable.  Closing the PR until I get that working.

**Pull request closed without merging**
