### PR TITLE
[ICDS Dashboard] added infantometer and stadiometer to awc infra tabular report

### PR DESCRIPTION
**Pull request by challabeehyv**
https://app.asana.com/0/1112385193248823/1153005958632441/f

##### SUMMARY
 added infantometer and stadiometer to awc infra tabular report

##### FEATURE FLAG
ICDS: Enable access to pre-release features in the ICDS Dashboard reports

### CODE REVIEW

**Comment by challabeehyv** [comment]
[AWC_Infrastructure (1).xlsx](https://github.com/dimagi/commcare-hq/files/4354744/AWC_Infrastructure.1.xlsx)
with feature flag ON

**Comment by challabeehyv** [comment]
[AWC_Infrastructure (2).xlsx](https://github.com/dimagi/commcare-hq/files/4354746/AWC_Infrastructure.2.xlsx)
with feature flag OFF

**Review by Rohit25negi — APPROVED** [review]
Looks. good. Is there any date restriction to it before which it should not be displayed. as far I remember these two are added recently to the dashboard on the card level. Do we have data for these for old dates like Dec 2017
@challabeehyv

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
Actually it would be great to have test cases for these changes

**Comment by challabeehyv** [comment]
> Actually it would be great to have test cases for these changes

added with beta flag

**Review by Rohit25negi — APPROVED** [review]
Looks good. gtg once the test cases are passed. @challabeehyv  also can you update GS team to test this as this is going under feature flag

**Review by Rohit25negi — APPROVED** [review]

**Pull request merged**
