### PR TITLE
Multi-Select: Remove selections upon form submission

### PR DESCRIPTION
**Pull request by stephherbers**
## Product Description

Flagged from [this interrupt ticket ](https://dimagi-dev.atlassian.net/browse/USH-2503)
There was an error triggered fro some dedupe workflows that contained multi-select case lists

## Technical Summary

This adds a clear upon form submission of the cases saved in `selectedValues`. This was not here previously because it's also cleared in other functions that are called the same time as onSubmit. However, my guess is this complicated workflow BHA is using does not have the other functions called. This caused the workflow to fail the second time around, but "starting over" (clicking the home button) calls the functions with the selectedValues clearing and lets it succeed again. 

## Feature Flag

MULTI_SELECT_CASE_LISTS

### Safety story

Tested locally and on staging

### QA Plan

I am not requesting QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]
Looks good to me!

**Comment by orangejenny** [comment]
Is this going to risk breaking end of form navigation for multi-select case lists? I forget exactly what we do and don't support for multi-select plus EOF nav.

**Comment by stephherbers** [comment]
@orangejenny ah interesting I do not know, but I will investigate (particularly if that's some thing we claim to support, I know that QA does test that for multi-select). Do you view this as blocking for the merge?

**Review by snopoke — APPROVED** [review]
I think this should be safe. EOF nav should only rely on the reference GUID and not the client side storage.

**Pull request merged**
