### PR TITLE
No need to bust keys that are never cached and avoid using redis KEYS command

### PR DESCRIPTION
**Pull request by sravfeyn**
On ICDS, I observed bunch of redis errors this morning IST. Per the redis slowlog, the command `keys` is run during that time, which is very slow to the order of above 10 seconds. The slowlog command was `KEYS *cas_reach_data*` which corresponds to this call. I ran the same command, and was able to reproduce the same redis error blip with that. This confirms, indeed it is the `KEYS` redis command that's the culprit. It might be that this doesn't always cause errors (apparently since the task has been running every day since Feb), but may be under special circumstances it does. And we did have bunch of redis blips over the weeks (may be not always for this reason).

The `keys` is not recommended to be used in production environments except for debugging per Redis docs. The right way is to use django-redis's `iter_keys` or `delete_pattern` which does a `SCAN` redis command which is supposed to be more performant instead of `KEYS`. Still better is `UNLINK` command that is specifically created to delete all keys matching a pattern, which is a _lot_ more performant. It's not implemented in the django-redis library but it's possible to use to run raw redis commands using that library for this special case if and when wanted.

I didn't find any other `cache.keys` call in the HQ code base.

I am removing this call instead of modifying it to use because, it looks like the underyling cache decorator [has been removed](https://github.com/dimagi/commcare-hq/commit/08f298bcdf15443cdd734b0f431bb630102ddc9c#diff-50b8c0baaef34ca763dda94410624738L15) a while ago.

@nickpell 

FYI @snopoke @Rohit25negi

### CODE REVIEW

**Comment by sravfeyn** [comment]
@snopoke 

Additionally, we should prevent further usage of this method (since it's not recommended by Redis). Something like below would work, but it needs to be in the right file to be applied on all django processes.  Or, are these best practices in preventing external library method usage for cases like these?

```
from django.core.cache import cache

def safe_keys(*args, force_use=False, **kwargs):
    if force_use:
        return cache.keys(*args, **kwargs)
    raise Exception("cache.keys is not recommended to be used in production, consider using iter_keys")

cache.keys = safe_keys
```

**Comment by sravfeyn** [comment]
Per redis docs on latency https://redis.io/topics/latency

> IMPORTANT NOTE: a VERY common source of latency generated by the execution of slow commands is the use of the KEYS command in production environments. KEYS, as documented in the Redis documentation, should only be used for debugging purposes. Since Redis 2.8 a new commands were introduced in order to iterate the key space and other large collections incrementally, please check the SCAN, SSCAN, HSCAN and ZSCAN commands for more information.

**Comment by snopoke** [comment]
@calellowitz @emord please take a look at this

**Review by calellowitz — APPROVED** [review]
I swear i switched to `iter_keys` a while ago but this looks fine

**Comment by sravfeyn** [comment]
I just kicked the build again, we should make sure to get this in before next deploy

**Comment by emord** [comment]
fwiw this was included in last nights deploy https://github.com/dimagi/commcare-hq/releases/tag/2019-07-10_21.01-icds-deploy

**Pull request merged**
