### PR TITLE
Ils report changes

### PR DESCRIPTION
**Pull request by lwyszomi**
@fyniac 

Could you assign someone to review? Mike want this because he has a meeting with client tomorrow.

### CODE REVIEW

**Comment by fyniac** [comment]
@esoergel can you please review?

**Comment by esoergel** [comment]
Looks good to me, I'll merge after tests

**Comment by czue** [comment]
@fyniac @modonnell729 doesn't look like this was merged in time for deploy. ping me if this needs to get in before the ILS meeting this morning.

**Comment by czue** [comment]
@modonnell729 i just deployed this

**Comment by esoergel** [comment]
Sorry about that guys, I didn't realize this warranted another deploy.

**Pull request merged**
