### PR TITLE
new new relic machines

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke does this just work?
@dannyroberts

### CODE REVIEW

**Comment by snopoke** [comment]
Yes, that should just work. I don't see those machines on the newrelic server dashboard yet, are they up?

**Comment by dannyroberts** [comment]
I think I've actually (somehow) never personally set up new-relic on a
machine. Is the full process (1) run ansible (2) add to the list of new
relic machines in fab environment & deploy (3) manually (?) add machines to
the new relic dashboard?

**Comment by snopoke** [comment]
Yea, just 1 and 2, no step 3

On 2 September 2015 at 16:15, Daniel Roberts <notifications@github.com>
wrote:

> I think I've actually (somehow) never personally set up new-relic on a
> machine. Is the full process (1) run ansible (2) add to the list of new
> relic machines in fab environment & deploy (3) manually (?) add machines to
> the new relic dashboard?
>
> On Wed, Sep 2, 2015 at 4:33 AM Simon Kelly <notifications@github.com>
> wrote:
>
> > Merged #8095 <https://github.com/dimagi/commcare-hq/pull/8095>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dimagi/commcare-hq/pull/8095#event-398661097>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/8095#issuecomment-137096095>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
Ok sounds like we just need to deploy (2), which we'll do in 5 or so hours
on daily deploy.

**Comment by snopoke** [comment]
I already ran the necessary command on the django workers:

   - set_supervisor_configs
   - restart_services

**Pull request merged**
