### PR TITLE
Upgrade js dev dependencies to latest versions

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

If tests pass and the deploy is successful, this is safe since all dependencies are only used in dev contexts. 

eslint: [changelog](https://github.com/eslint/eslint/blob/main/CHANGELOG.md) and [diff](https://github.com/eslint/eslint/compare/v7.32.0...v8.15.0)

grunt: [changelog](https://github.com/gruntjs/grunt/blob/main/CHANGELOG) and [diff](https://github.com/gruntjs/grunt/compare/v1.5.2...v1.5.3)

grunt-cli: [changelog](https://github.com/gruntjs/grunt-cli/blob/main/CHANGELOG.md) and [diff](https://github.com/gruntjs/grunt-cli/compare/v1.3.2...v1.4.3)

mocha: [changelog](https://github.com/mochajs/mocha/releases)
- 10.0.0 drops support for RequireJS, so I kept mocha on 9.2.2 (the latest 9.x.x version)

mocha-headless-chrome: [changelog](https://github.com/direct-adv-interfaces/mocha-headless-chrome/blob/master/CHANGELOG.md) and [diff](https://github.com/direct-adv-interfaces/mocha-headless-chrome/compare/v3.0.0...v4.0.0)

I've reviewed this as best I can including inspecting commits, looking at snyk.io for each dependency for any known issues, and googling around for potential issues. All looks good.

### Safety story

Just dev dependencies.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
Current failure is node version related, similar to https://github.com/dimagi/commcare-hq/pull/31407#issuecomment-1088871363, except this time around we have upgraded to v14. It looks like github actions aren't running with that updated version?

**Review by millerdev — APPROVED** [review]
I think it's fine to upgrade this way (single PR, multiple dependencies upgraded). Do you have a path forward for getting tests to pass?

**Comment by gherceg** [comment]
Rebased on master

**Review by joxl — APPROVED** [review]
:1st_place_medal:

**Comment by gherceg** [comment]
Will test a deploy on staging before merging to ensure things look good.

**Review by millerdev — APPROVED** [review]

**Review by biyeun — APPROVED** [review]
yayyy! fantastic

**Comment by gherceg** [comment]
Deployed to staging successfully. Merging 👍🏻

**Pull request merged**
