### PR TITLE
Fixed related locations form not displaying initial value

### PR DESCRIPTION
**Pull request by orangejenny**
https://dimagi-dev.atlassian.net/browse/REACH-111

Introduced in https://github.com/dimagi/commcare-hq/pull/23877, probably by https://github.com/dimagi/commcare-hq/commit/504b386ccc395707cce542a2c0942007895c9c14#diff-c0e86be18166b9f5d1c2ccb534fe8aa1R62

Feature flag: REACH: Enable experimental location many-to-many mappings

### CODE REVIEW

**Review by emord — APPROVED** [review]
What are the chances that other usages are broken? Found https://github.com/dimagi/commcare-hq/blob/04153252e1fe24866018a29c9f58645c77132c01/corehq/apps/domain/forms.py#L1931 as an example (that's fed to `.initial` [here](https://github.com/dimagi/commcare-hq/blob/04153252e1fe24866018a29c9f58645c77132c01/corehq/apps/domain/forms.py#L2035))

I found that pretty quickly with `ag "','.join"`. There's some noise in there, but may be worth going through those instances to find other broken selects? May also want to try `', '.join` (with a space after comma)

**Review by gbova — APPROVED** [review]

**Comment by orangejenny** [comment]
@emord It's easier to grep for usages of `LocationSelectWidget`, there aren't many: the related locations form in this PR, `CommtrackUserForm` (tested in the breaking PR), `EWSUserSettings` (tested in the breaking PR, not a multiselect), `AdminInvitesUserForm` (doesn't use initial data, tested in the breaking PR, not a multiselect), and OpenMRS repeaters (not a multiselect).

**Comment by orangejenny** [comment]
@emord The code you linked isn't related - it's indeed a noisy grep, because we genuinely do store multi-value fields as CSVs sometimes.

**Comment by emord** [comment]
@orangejenny Thanks for checking those other instances and the info on the better grep

**Pull request merged**
