### PR TITLE
update deploy submodule

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts / anyone

cc: @proteusvacuum @sravfeyn

### CODE REVIEW

**Comment by benrudolph** [comment]
yeah, i was being lazy cause there were no tests, but now i actually think there might be

**Comment by proteusvacuum** [comment]
ah, you `[ci skip]`ed it. didn't see that. Should I wait?

**Comment by benrudolph** [comment]
yes, was just looking at the commcare-hq repo and there is one dep where we import `fab.fabile import get_pillow_env_config` which i changed

**Comment by benrudolph** [comment]
crossed with https://github.com/dimagi/commcare-hq-deploy/pull/60

**Pull request merged**
