### PR TITLE
Revert "[ICDS] extend Google Analytics intregration"

### PR DESCRIPTION
**Pull request by calellowitz**
Reverts dimagi/commcare-hq#22918
FYI: @lwyszomi 
This code does not work for mobile users and i believe also fails for users assigned to multiple locations, which many dashboard users are.

### CODE REVIEW

**Comment by lwyszomi** [comment]
@calellowitz do you have more information what was failing?

**Comment by calellowitz** [comment]
The function `get_location` in https://github.com/dimagi/commcare-hq/pull/23020/files#diff-129264561592e648289c087ab1350b9bL221 only exists on webusers.
Users can also be in multiple locations and `get_location` returns all of those. The next few lines of code seemed to be assuming that it returned a single `SQLLocation` object

**Comment by lwyszomi** [comment]
@calellowitz so we can change this to ```get_sql_location``` this function we have in both user types. Regarding multiple locations I didn't found yet in GA how to store lists, now I used custom dimensions for this solution. Also, this is the first part of changes to check if these data will be enough for us.

**Comment by calellowitz** [comment]
`get_sql_location` is the right function to use, but the data it will return will not be of the right type for how `user_location` is used later in the view. it is also already called lower down, so we may be able to refactor to share that call. The reason im reverting is because this was hotfixed earlier and i plan on deploying today and wanted to make sure this would not recur.

**Comment by lwyszomi** [comment]
Okay. So merge this and I will change this inne other PR

**Comment by calellowitz** [comment]
Great!

**Pull request merged**
