### PR TITLE
UCR - Base Item Expression

### PR DESCRIPTION
**Pull request by lwyszomi**
@fyniac Could you assign someone which are familiar with UCR code, I need this to finish L10k reports.

Fixed iterator expression 
    * Allow use named expression and filters in base_item_expression
    * Add access to root doc in base_item_expression

### CODE REVIEW

**Comment by fyniac** [comment]
@benrudolph I believe is more familiar with the L10k work.  feel free to have someone else look.

**Review by benrudolph — APPROVED** [review]
seems fine to me. would a test make sense for this? also pinging @emord

**Comment by emord** [comment]
This seems fine to me. agreed a test would be good

**Comment by lwyszomi** [comment]
@benrudolph @emord Can we merge this today I will add test tomorrow. I need this to UCR reports and I have deadline to Friday.

**Pull request merged**
