### PR TITLE
Extension cases autoclose

### PR DESCRIPTION
**Pull request by proteusvacuum**
@czue @orangejenny 

I'm still a bit wary about this as it is irreversible. If you submit a close form for a host, it automatically propagates down the chain to the rest of the extensions. If you then archive the close form, that "undo" action doesn't propagate. 

[I'm not even sure what undoing the automatic close actually means, if this is even possible, since we lose data in this scenario (i.e. I have 3 or 4 closed extensions in my chain which I have closed manually, I close the host of these extensions which closes everything else. The system now can't differentiate between a manual close and a system close... unless we look at the submitter of each form.]

http://manage.dimagi.com/default.asp?217563#1092770

### CODE REVIEW

**Comment by czue** [comment]
I think this is legit. Can you merge master so tests run?

How are extension cases closed? I assume by submitting an additional form, right? In that case it should be possible to undo since it would be a system form you could archive.

**Comment by proteusvacuum** [comment]
yeah, submitting a form. I just mean that if you were to undo just the closing of the host, it wouldn't also undo the automatic close of its extensions.

**Comment by czue** [comment]
yeah, i think that's probably ok

**Comment by czue** [comment]
:boot:

**Comment by snopoke** [comment]
I have some thoughts about how to make the undo operation work if we ever come back to this:
* perform the close operation as part of the original form submission (instead of via a separate form submission)
* this would allow us to process form archives / edits in the same way we do for normal forms since the changes to the extension cases are linked to the same form.

**Comment by proteusvacuum** [comment]
That's a great idea.

**Pull request merged**
