### PR TITLE
change response code for submission errors that are not recoverable

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
Prevent mobile devices from retrying unprocessable form XML submissions.

##### PRODUCT DESCRIPTION
This changes the response code we use for form submissions that we are unable to parse. Previously we would return a 500 (Server Error) response code but now we are returning a 422 (Unprocessable Entity) code.

The main goal is to prevent mobile devices from retrying these forms.

Probably not worth announcing this change but putting details here anyway.

Docs for this already exists here: https://confluence.dimagi.com/display/commcarepublic/Submission+API

@ctsims FYI

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
Curious to what the phone will do now? The user is notified and fixes it?
@ctsims

**Comment by snopoke** [comment]
@mkangia the phone will 'quarantine' the for to prevent it from being retried automatically and will allow remaining forms to be submitted. There is an option to view these forms on the phone and retry them but it's mostly for debugging purposes and a user would not be expected to to that usually.

**Comment by ctsims** [comment]
@snopoke Can you confirm whether Sentry will still report these as errors? I think we do still want to have the logs that forms were in this state so the team can keep following up on their generation.

**Comment by snopoke** [comment]
Yes, they are still reported to sentry.

**Comment by mkangia** [comment]
Thanks @snopoke . 
Just want to confirm that there is no possibility, that a form processing would fail because of HQ and not because of the form, resulting in the response to be 422?

**Comment by snopoke** [comment]
@mkangia other errors would cause a 500

**Comment by mkangia** [comment]
@snopoke i think i meant that any error on HQ while processing the form and considering it invalid, would result in 422 even though the form was actually okay. But i guess that's not gonna happen.
thanks for confirming.

**Pull request merged**
