### PR TITLE
Post tests XFormSQL

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke :blowfish: 

cc: @proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Build fail looks related:
```
======================================================================

ERROR: test_auth_context (couchforms.tests.test_auth.AuthTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 168, in inner

    return helper(*args, **kwargs)

  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 141, in __call__

    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)

  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 156, in call_with_settings

    fn(*args, **kwargs)

  File "/home/travis/build/dimagi/commcare-hq/corehq/util/test_utils.py", line 137, in fn_with_pre_and_post

    self.fn(*args, **kwargs)

  File "corehq/ex-submodules/couchforms/tests/test_auth.py", line 14, in test_auth_context

    xml_data = open(file_path, "rb").read()

IOError: [Errno 2] No such file or directory: 'corehq/ex-submodules/couchforms/tests/data/meta.xml'
```

**Comment by benrudolph** [comment]
oops yep will fix

**Comment by benrudolph** [comment]
thanks for the cleanup simon

**Comment by benrudolph** [comment]
:white_check_mark:

**Pull request merged**
