### PR TITLE
gunicorn config tweaks

### PR DESCRIPTION
**Pull request by snopoke**
https://github.com/dimagi/commcare-hq-deploy/pull/195

### CODE REVIEW

**Comment by benrudolph** [comment]
we purposely changed this a while back: https://github.com/dimagi/commcare-hq/pull/7957. it was a long time ago, so may be irrelevant, but as i commented before we might want to make this a function of the ram available on the machine. we were previously seeing OOM errors on prod

**Review by kaapstorm — COMMENTED** [review]
fwiw, `psutil.virtual_memory()` will give you total and free RAM. We could probably use something like 
```
workers = max(multiprocessing.cpu_count() * 2, (psutil.virtual_memory().total - BASE_RAM) / WORKER_RAM)
```

**Comment by snopoke** [comment]
Ah, that's irritating. Maybe we should push some of those settings to the command line which will be easier to configure per env.

**Comment by snopoke** [comment]
Updated to make #workers configurable per env

**Review by kaapstorm — APPROVED** [review]

**Review by benrudolph — APPROVED** [review]
nice

**Pull request merged**
