### PR TITLE
Use Ace editor for UCRs

### PR DESCRIPTION
**Pull request by proteusvacuum**
Look! Inline error handling! V. Fast Rendering! This thing is `ace`. 
https://trello.com/c/L8DNGKS9/4-better-json-validation-errors-when-creating-ucrs-ismaila

screenshot from 2018-06-29 11-52-50

Product note: This is an update to the UCR UI... Not under a feature flag, but it's hidden.

### CODE REVIEW

**Review by pr33thi — APPROVED** [review]
this is awesome

**Review by orangejenny — APPROVED** [review]
This is wonderful.

**Comment by proteusvacuum** [comment]
Apparently this is actually under a feature flag.

**Comment by pr33thi** [comment]
@proteusvacuum should you add the feature flag to the description for dev's weekly deploy summary?

**Comment by proteusvacuum** [comment]
FF: https://www.commcarehq.org/hq/flags/edit/user_reports/

**Pull request merged**
