### PR TITLE
upgrade to py3 compatible ethiopian-date-converter

### PR DESCRIPTION
**Pull request by nickpell**
I had to remove the ```#egg=ethiopian-date-converter``` to get ```pip install``` to work for me locally.  @pr33thi is there any particular reason it's needed?

### CODE REVIEW

**Review by pr33thi — COMMENTED** [review]
What errors were you seeing with the #egg part? And does it properly install without it, with pip install -U?

Here's an explanation of why it's in there (you can ctrl+f for "include #egg" to go to the relevant paragraph): https://pip.readthedocs.io/en/1.1/requirements.html

**Comment by nickpell** [comment]
I ran the following commands:
```
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ pip show ethiopian-date-converter
Name: ethiopian-date-converter
Version: 0.1.2
Summary: Ethiopian date converter.
Home-page: https://github.com/dimagi/ethiopian-date-converter
Author: UNKNOWN
Author-email: UNKNOWN
License: GNU General Public License (GPL), Version 3
Location: /Users/Nick/.virtualenvs/hq_env3/lib/python2.7/site-packages
Requires: 
### UPDATE REQS TO 0.1.3
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ git diff
diff --git a/requirements/requirements.txt b/requirements/requirements.txt
index d0a7857..6655b95 100644
--- a/requirements/requirements.txt
+++ b/requirements/requirements.txt
@@ -96,7 +96,7 @@ dnspython==1.15.0
 raven==6.1.0
 quickcache==0.1.0
 zeep==1.6.0
-git+git://github.com/dimagi/ethiopian-date-converter@v0.1.2#egg=ethiopian-date-converter
+git+git://github.com/dimagi/ethiopian-date-converter@v0.1.3#egg=ethiopian-date-converter
 git+git://github.com/dimagi/architect@v0.5.7a2#egg=architect
 contextlib2==0.5.4
 hiredis==0.2.0
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ pip install --requirement requirements/requirements.txt --quiet
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ pip show ethiopian-date-converter
Name: ethiopian-date-converter
Version: 0.1.2
Summary: Ethiopian date converter.
Home-page: https://github.com/dimagi/ethiopian-date-converter
Author: UNKNOWN
Author-email: UNKNOWN
License: GNU General Public License (GPL), Version 3
Location: /Users/Nick/.virtualenvs/hq_env3/lib/python2.7/site-packages
Requires: 
### REMOVE #egg from REQS
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ git diff
diff --git a/requirements/requirements.txt b/requirements/requirements.txt
index d0a7857..0517034 100644
--- a/requirements/requirements.txt
+++ b/requirements/requirements.txt
@@ -96,7 +96,7 @@ dnspython==1.15.0
 raven==6.1.0
 quickcache==0.1.0
 zeep==1.6.0
-git+git://github.com/dimagi/ethiopian-date-converter@v0.1.2#egg=ethiopian-date-converter
+git+git://github.com/dimagi/ethiopian-date-converter@v0.1.3
 git+git://github.com/dimagi/architect@v0.5.7a2#egg=architect
 contextlib2==0.5.4
 hiredis==0.2.0
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ pip install --requirement requirements/requirements.txt --quiet
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$ pip show ethiopian-date-converter
Name: ethiopian-date-converter
Version: 0.1.3
Summary: Ethiopian date converter.
Home-page: https://github.com/dimagi/ethiopian-date-converter
Author: UNKNOWN
Author-email: UNKNOWN
License: GNU General Public License (GPL), Version 3
Location: /Users/Nick/.virtualenvs/hq_env3/lib/python2.7/site-packages
Requires: 
(hq_env3)Nicholass-MacBook-Pro-2:commcare-hq Nick$
```

The upgrade only worked after I removed the ```#egg```.

We could add the ```-U``` flag to the ```pip install``` commands that we use for deploys and tests, but that might update dependencies in an unpredictable way.

**Comment by nickpell** [comment]
^ Ran using pip 9.0.1

**Comment by nickpell** [comment]
@millerdev Let me know if you have any wisdom here

**Comment by millerdev** [comment]
@nickpell just so I'm clear, you had v0.1.2 installed and wanted it to upgrade to v0.1.3. So you ran
```
pip install --requirement requirements/requirements.txt --quiet
```
which did not upgrade the library as expected, even though requirements.txt referenced v0.1.3. Is that all correct?

### Observations assuming the above is correct:

I think the `#egg=ethiopian-date-converter` part is important and should not be removed (that's how pip determines what package is being installed).

Given the weirdness you're seeing as well as trouble @pr33thi had in the past with this, I'm wondering if pip lacks a feature or has a bug where it does not parse the URL to get the version number (the rev/tag following the `@` char). Since it does not know the target version it simply checks to see if *any version* of that package is installed and does nothing if it is. One workaround for this would be to upload the package to PyPI. This would allow us to use the normal requirements syntax rather than these flaky github URLs.

The reason it worked when you removed `#egg=...` is because pip could no longer tell what package it was going to install with that line so it force-installed it over what was already there. Thus removing `#egg=...` is non-ideal because it makes pip do extra work every time anyone runs `pip install -r requirements/requirements.txt`.

**Comment by pr33thi** [comment]
Also, I realized that the version you changed is actually the git tag!
https://coderwall.com/p/-wbo5q/pip-install-a-specific-github-repo-tag-or-branch
Did you update the git tag on the repo to v0.1.3 after changing the code?

**Comment by nickpell** [comment]
> Did you update the git tag on the repo to v0.1.3 after changing the code?

I added a git tag: https://github.com/dimagi/ethiopian-date-converter/tree/v0.1.3
And a git release: https://github.com/dimagi/ethiopian-date-converter/releases/tag/v0.1.3
Which both contain an update to the version number: https://github.com/dimagi/ethiopian-date-converter/commit/53bf2ad629844f9367d6b1e2c4c23fd2ea01eeff

@pr33thi Is there something else I should update?  If not, then I'll take @millerdev's advice and upload the package to PyPI.

**Comment by pr33thi** [comment]
Yep, those are the things you'd change to make them correspond with requirements.txt. If that didn't fix it, I think you should take @millerdev's advice

**Comment by nickpell** [comment]
@pr33thi Updated requirements to use pypi

**Review by esoergel — APPROVED** [review]

**Pull request merged**
