### PR TITLE
ICDS Tableau Report Changes

### PR DESCRIPTION
**Pull request by sheelio**
@kkrampa 
I've refactored this code a fair bit.  I don't believe the location restrictions are working correctly.

Is it possible to update the drilldown filter to support location restrictions with the following behaviour:
- If user is assigned to a location, the drilldown filter defaults to that location (but still shows the ancestors)
- In addition, if a user is in a role that is location restricted, they should not be able to choose any locations through the filter that they do not have access to.  This should support the user being assigned to multiple locations

I'm guessing this can be done by updating the API that pulls locations (for the filter) to be location restricted supported, and by defaulting the assigned location to user's primary assigned location.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 6 errors:

* custom/icds_reports/static/tableau_app.js, line 174 - Missing semicolon. (semi)
* custom/icds_reports/static/tableau_app.js, line 212 - 'newSheet' is not defined. (no-undef)
* custom/icds_reports/static/tableau_app.js, line 217 - 'newSheet' is not defined. (no-undef)
* custom/icds_reports/static/tableau_app.js, line 224 - 'newSheet' is not defined. (no-undef)
* custom/icds_reports/static/tableau_app.js, line 278 - 'dashboard' is defined but never used (no-unused-vars)
* custom/icds_reports/static/tableau_app.js, line 322 - Missing semicolon. (semi)

**Comment by kkrampa** [comment]
I think that changes that I made for m4change can be useful here. I extracted them to common module in another PR so they can be easily reused here.

**Comment by sheelio** [comment]
Thanks - can you link me to that PR?

**Comment by kkrampa** [comment]
Here is the original PR: https://github.com/dimagi/commcare-hq/pull/14889
Here is PR that I've made today: #15243

**Pull request closed without merging**
