### PR TITLE
fix multiple numeric filters

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?180169

@NoahCarnahan @dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
will let @NoahCarnahan review but :+1: from me. thought about asking for a test but decided to pick my battles...

**Comment by NoahCarnahan** [comment]
looks good, thanks nick.

**Comment by nickpell** [comment]
@czue Any suggestions on how to structure a test?  I only saw one end-to-end test of querying data from an actual data source (maybe we should have a library for that) or maybe there's a better place to unit test

**Comment by czue** [comment]
I think it would be non-trivial to write a test which was why i didn't actually ask. I agree you might have to make a data source and a report which feels like a lot of bootstrap for something that's relatively simple

**Pull request merged**
