### PR TITLE
kill angular 1.4.4

### PR DESCRIPTION
**Pull request by benrudolph**
@proteusvacuum @sravfeyn requires prelogin PR: https://github.com/dimagi/commcarehq-prelogin/pull/39

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by czue** [comment]
image
:heart_eyes:

**Comment by czue** [comment]
(build is failing)
```
======================================================================
ERROR: test_compress_offline (corehq.apps.style.tests.test_compress_command.TestDjangoCompressOffline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/style/tests/test_compress_command.py", line 8, in test_compress_offline
    call_command('compress', force=True)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 274, in handle_noargs
    self.compress(sys.stdout, **options)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 231, in compress
    "%s" % (template.template_name, e))
CommandError: An error occured during rendering /home/travis/build/dimagi/commcare-hq/corehq/apps/prelogin/templates/prelogin/services.html: 'angular-sanitize/angular-sanitize.js' could not be found in the COMPRESS_ROOT '/home/travis/build/dimagi/commcare-hq/staticfiles' or with staticfiles.
----------------------------------------------------------------------
Ran 721 tests in 36.288s
```

**Comment by czue** [comment]
these are all awesome! not merging any because they scare me but no blockers on my side if you're confident in bower+testing

**Comment by benrudolph** [comment]
brucelee

**Comment by benrudolph** [comment]
haha i suppose that isn't the best approach for software

**Comment by proteusvacuum** [comment]
@benrudolph merge conflicts

**Comment by benrudolph** [comment]
:white_check_mark:

**Pull request merged**
