### PR TITLE
Updated AWS dialer code to reflect new domain

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
https://dimagi-dev.atlassian.net/browse/SUPPORT-10182 / https://dimagi-dev.atlassian.net/browse/USH-1210

Updates the AWS dialer to use the new domain described in [March 2021 Updates here](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-release-notes.html#march21-release-notes).

This is mostly a find and replace, plus the old URL showed up in the AWS js files so I updated those (and moved them to npm).

I did a cursory glance to verify that [our initCCP call](https://github.com/dimagi/commcare-hq/blob/983c78f298e0e5d4554e730f84bf1301693afe7c/corehq/apps/integration/static/integration/js/dialer/domain_dialer_main.js#L31) still looks reasonable based on the [initCCP call in the docs](https://github.com/amazon-connect/amazon-connect-streams#connectcoreinitccp).

FYI @ctsims 

## Feature Flag
COVID: Enable usage of AWS Connect Dialer

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

None.

### QA Plan

I'll test this manually locally or on staging.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by orangejenny** [comment]
Also noting I deleted `amazon-connect-min.js` altogether, as it wasn't in the `amazon-connect-streams` repo, but I'm still digging around to see if it's in any of the other `amazon-connect` repos.

**Comment by orangejenny** [comment]
@dimagi/dependency-watchers This PR introduces a js dependency only used by USH. Are we documenting division-specific dependencies? It's really a shame we can't comment in package.json.

**Review by joxl — APPROVED** [review]

**Comment by joxl** [comment]
> Are we documenting division-specific dependencies?

I don't recall where we're at with this, I assume it will be discussed again on Monday. I've left a note for Monday so your question doesn't get missed.

**Comment by orangejenny** [comment]
This needs actual QA, though I'll do it instead of sending this through formal QA. Updated description.

**Review by snopoke — APPROVED** [review]

**Review by biyeun — APPROVED** [review]
Thanks @orangejenny. Signing off as a member of the dependency pod.

I've added instructions for division-specific dependencies [here](https://confluence.dimagi.com/display/saas/CommCareHQ+dependency+management#CommCareHQdependencymanagement-DependenciesAddedbyDivisionsOutsideofSaaS).

**Comment by orangejenny** [comment]
@biyeun lovely, thank you for documenting this one

**Comment by orangejenny** [comment]
Closing this out for now, we're delaying this change.

**Pull request closed without merging**
