### PR TITLE
Cache invalidate users

### PR DESCRIPTION
**Pull request by czue**
last interrupt :gift: before dropping off. hopefully fixes the user caching bug once more.

http://manage.dimagi.com/default.asp?215679

@snopoke @dannyroberts @esoergel cc @proteusvacuum

### CODE REVIEW

**Comment by benrudolph** [comment]
this has been a :imp: of a bug. good hunting :gun:

**Comment by czue** [comment]
updated and hopefully fixed tests. might not be around when they finish though. if still broken could be good for someone on interrupt to grab this.

**Comment by proteusvacuum** [comment]
Assigning the ticket back to interrupt now that @czue is offline

**Comment by TylerSheffels** [comment]
My update adds the main db as a default for the invalidate_document method. This is dependent on people knowing that they need to use `invalidate_cached_domain` in order to do domains. Open to hearing suggestions on other ways this could have been accomplished.

**Comment by dannyroberts** [comment]
can you make it call `invalidate_document` with `couchdb=self.get_db()` instead? Maybe I'm missing the point, but at least on the surface that seems more correct.

**Comment by TylerSheffels** [comment]
I initially thought that as well. The object that is used in a the test doesn't have a get_db() method, and that made me wonder if there were potentially other places that we were caching things that wouldn't have a get_db() method. Because I wasn't sure I opted for using the base couchdb, but I agree that using `self.get_db()` feels like the correct option.

**Comment by dannyroberts** [comment]
weird. `_InvalidateCacheMixin` is the base class for `QuickCachedDocumentMixin` and `CachedCouchDocumentMixin` which are always used in conjunction with `Document`. Perhaps the object used in the test are dummy objects created in the test file which consequently have no app_name and thus no db?

I guess I'm not sure which tests you mean. I'd be happy to take this over, as I might have more context; if that sounds good, could you let me know and point me to the test that wasn't passing with the `self.get_db()` route?

**Comment by TylerSheffels** [comment]
You were correct, the test was using a dummy object. I updated the code + added get_db() to the test. Feel free to take if you have a strong feeling on how it should work.

**Comment by dannyroberts** [comment]
```
======================================================================
FAIL: test_instantiate_all (testapps.test_pillowtop.tests.test_settings.PillowtopSettingsTest)
----------------------------------------------------------------------
...
-  u'couchdb_uri': u'http://127.0.0.1:5984/test_commcarehq__users',
?  -               -        ^^^^^^^^^
+  'couchdb_uri': 'http://couch:5984/test_commcarehq__users',
?                         ^^^^^
```

**Comment by esoergel** [comment]
I think you just need to change that line to:
```python
    "couchdb_uri": "http://{COUCH_SERVER_ROOT}/test_commcarehq__users",
```
Check the latest version of that file on master

**Comment by dannyroberts** [comment]
OK i'll take a look today

**Comment by dannyroberts** [comment]
Finally1

**Comment by czue** [comment]
yikes, what a nightmare. thanks all for getting that over the hump!

**Pull request merged**
