### PR TITLE
upgrade numpy

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Review by emord — APPROVED** [review]
any reason to upgrade this? I was hoping to remove it after python3 as our usages should be able to be replaced by the statistics library

**Comment by nickpell** [comment]
I was gonna upgrade it because my Mac defaulted to python 3.7 and numpy needed a compatibility upgrade, but I got it to use 3.6 so no longer relevant

**Comment by emord** [comment]
Oh. htat sounds important to upgrade then. if we're working on python3, we may as well use the latest right?

**Comment by nickpell** [comment]
Maybe.  I'm currently targeting 3.6 for the upgrade, so 3.7 is out of scope.  I think I will just punt on this upgrade since we might just replace numpy for statistics once we are on 3.6.

**Pull request closed without merging**
