### PR TITLE
Renamed incorrect case property in ICDS data sources

### PR DESCRIPTION
**Pull request by orangejenny**
https://dimagi-dev.atlassian.net/browse/ICDS-1174

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
oh man!

**Comment by mkangia** [comment]
would these need to be rebuilt?

**Comment by orangejenny** [comment]
> would these need to be rebuilt?

@calellowitz do you know the answer to this?

**Comment by calellowitz** [comment]
This will not fix existing data in those sources, but will apply immediately to all new data coming in. Rebuilding these is certainly the simplest way to get updated data for each record, but will be quite expensive (these are very slow UCRs and there are a LOT of child health cases). They do rebuild themselves over the course of the month. If it is fine to wait until 30 days from now to be sure all the data is right, then that would be the simplest option. Otherwise, the only real option is to use the `async_rebuild_table` (https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/userreports/management/commands/async_rebuild_table.py) management command, but it will probably take a couple days to rebuild at least, and cause a backup in the async queue.

**Review by Rohit25negi — APPROVED** [review]
Good catch it was. Looks good.

**Review by czue — APPROVED** [review]

**Pull request merged**
