### PR TITLE
Allow dev environments to function without segment api key

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Not sure why I'm just getting this now (as the segment code has been here for about a month I think), but I can't use the application deploy page because the js throws a `ReferenceError: analytics is not defined` error. I would think that other people would be having this problem to? @sravfeyn assigning to you as I think you added segment in #6067. Feel free to close without merging if there is a better solution that I missed, or if I should be changing something in my config files instead.

FYI review buddy @biyeun

### CODE REVIEW

**Comment by sravfeyn** [comment]
Ha, I tested this without the segment key and I can access the app-deploy page fine. Can you tell me the reproduction steps? One reason this might have failed is that your `localsettings.ANALYTICS_IDS` might not have the key `SEGMENT_ANALYTICS_KEY` (while the settings.ANALYTICS_IDS has that key). If that fixes, I can add that to localsettings.example.py. 

If there isn't a valid-key Segment JS API silently fails (i.e. all those functions you have added get automatically defined by the API).

**Comment by NoahCarnahan** [comment]
You're right, my `localsettings.py` `ANALYTICS_IDS` dict did not have the `SEGMENT_ANALYTICS_KEY`. If I add it with a non "falsey" value like `"dummy"`, the problem is resolved.



The reproduction steps by the way are:
1. `settings.py` contained:

    ```
    ANALYTICS_IDS = {
      'GOOGLE_ANALYTICS_ID': '',
      'PINGDOM_ID': '',
      'ANALYTICS_ID_PUBLIC_COMMCARE': '',
      'SEGMENT_ANALYTICS_KEY': '',
      'HUBSPOT_ID': '',
    }
    ```
2. `localsettings.py` contained:

      ```
     ANALYTICS_IDS = {
       'GOOGLE_ANALYTICS_ID': 'mygoogleid',
       'PINGDOM_ID': '*****'
     }
     ````

3. Load `/a/<domain>/apps/view/<app_id>/releases/` in your browser.
4. Observe the following error message in your js console:
"Uncaught ReferenceError: analytics is not defined"

**Comment by NoahCarnahan** [comment]
Come to think of it, the easiest thing to do is probably just to not wrap the analytics code in an if statement at all. (See latest commit)

**Comment by sravfeyn** [comment]
:+1:  Thanks

**Pull request merged**
