### PR TITLE
Remove leftover Couch References for Auditcare

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Product Description

There were a few references of Auditcare code referencing couch as pointed out by  @dannyroberts [comment](https://dimagi-dev.atlassian.net/browse/SAAS-13717?focusedCommentId=232792)

The PR removes those references 
## Technical Summary

https://dimagi-dev.atlassian.net/browse/SAAS-13717

## Safety Assurance
No changes affecting the running code on HQ
### Automated test coverage

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by dannyroberts** [comment]
Awesome thanks. How about removing `auditcare/_design` in this PR as well, which I think is the last (code) step?

**Review by millerdev — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by dannyroberts** [comment]
Hmm, hard to tell whether
```
  ======================================================================
  FAIL: corehq.apps.hqadmin.tests.test_raw_doc:TestRawDocLookup.test_raw_doc_with_invalid_uuid
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/mnt/commcare-hq-ro/corehq/apps/hqadmin/tests/test_raw_doc.py", line 81, in test_raw_doc_with_invalid_uuid
      self.assertEqual({r.result for r in data["db_results"]}, {"missing"})
  AssertionError: Items in the first set but not the second:
  'Database does not exist.'
```
is related but it could be. I'm going to re-run that job.

**Comment by dannyroberts** [comment]
I think this last commit I just added will fix the test. It removes auditcare from `COUCH_APPS`. Our code was inferring from that that this couch database existed, and inferring from something else (the lack of a `_design` in the app maybe) that it didn't. This I think removes the last mention of there being an auditcare couch db

**Comment by dannyroberts** [comment]
failed on codecov upload, but the tests themselves passed. I'm re-running the test job to just remove any sliver of a doubt

**Review by millerdev — APPROVED** [review]

**Comment by AmitPhulera** [comment]
Thanks @millerdev and @dannyroberts for getting this through 🎉

**Pull request merged**
