### PR TITLE
Enable sms 2fa

### PR DESCRIPTION
**Pull request by ghost**
Link to trello card: https://trello.com/c/KENNpC7j/1-2fa-re-enable-sms

SUMMARY: This allows the 2fa device to be sms

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]

**Review by dannyroberts — CHANGES_REQUESTED** [review]
Actually, sorry I should have looked a bit harder. I think the way we want to do this is in commcare-cloud instead, but letting each env specify a value for `ALLOW_PHONE_AS_DEFAULT_TWO_FACTOR_DEVICE`.

And then I think we don't need to manually override `TWO_FACTOR_SMS_GATEWAY` and `TWO_FACTOR_CALL_GATEWAY`

**Comment by preethivaid** [comment]
@dannyroberts that makes sense about enabling it in certain environments- one question though, I noticed that just setting `ALLOW_PHONE_AS_DEFAULT_TWO_FACTOR_DEVICE = True` in settings.py without also setting `TWO_FACTOR_SMS_GATEWAY` didn't make the sms option show up. Any idea what I'm missing?

Also, hi!!!!!!!!!! Hope all is well with you

**Comment by dannyroberts** [comment]
Hi!!!! 👋 

Oh, I see. Yeah to get it to show up locally, you have to add these to your localsettings: https://github.com/dimagi/commcare-hq/blob/f0bf59760517fb2f65baced09c5bf8282ffb51f9/localsettings.example.py#L309-L310.

But those will already be present on production due to this: https://github.com/dimagi/commcare-cloud/blob/02232389d906dc77160bbede5c6fb5e5e2c259f7/src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2#L717-L720.

Right now the state of things on production is that this is still an enabled 2fa method, but it's not allowed to be _added_ as a 2fa method. (The idea was to phase out the sms 2fa starting by not letting new people add it, but obviously now we're walking that back.)

**Comment by preethivaid** [comment]
Ok got it. So I should just add `ALLOW_PHONE_AS_DEFAULT_TWO_FACTOR_DEVICE` to the `public.yml` file for certain environments? Which ones should have this variable set to true?

**Comment by dannyroberts** [comment]
Yeah I think add it and make sure it's getting set in
`localsettings.py.j2`. (Currently it might not be.) I think you just want
to enable it for production!

**Comment by preethivaid** [comment]
Cool, I don't have the option to add reviewers, but I made those changes here: https://github.com/dimagi/commcare-cloud/pull/3746

**Pull request closed without merging**
