### PR TITLE
Refresh Warning After Saving Polygon (Geospatial)

### PR DESCRIPTION
**Pull request by zandre-eng**
## Product Description

An info banner is shown on the page when the user saves a new polygon, requesting a page refresh:
Screenshot from 2024-07-01 16-57-39

## Technical Summary

Link to ticket [here](https://dimagi.atlassian.net/browse/SC-3717).

After saving a new polygon in the UI, an info banner will be shown asking the user to refresh the page. Currently, when a user saves a new polygon and applies new report filters, we fetch and replace the list of saved polygons with the one given in `initialPageData`. This becomes outdated after saving a new polygon since `initialPageData` is only loaded on page load, and not when report filters are changed. Getting the user to refresh the page ensures that the latest list of saved polygons can be retrieved from the back-end.

As an alternative, I looked into using the `select2` component to fetch the latest list of saved polygons on demand. This would avoid requiring a refresh, however it will end up making the code more complex. This is because we also store and keep track of unsaved polygons drawn on the map, so that they can be added back to the map on a page refresh. Fetching saved polygons on demand using a `select2` widget would mean keeping track of two arrays, one for saved polygons and one for unsaved polygons.

## Feature Flag

`GEOSPATIAL`

### Safety story

- Local testing

This change will only affect domains that have the Geospatial feature flag enabled.

### Automated test coverage

N/A as changes are mostly limited to HTML templates.

### QA Plan

No QA planned.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by Charl1996** [comment]
@zandre-eng Would you mind explaining this part a bit more, please?

> Currently, when a user saves a new polygon and applies new report filters, we fetch and replace the list of saved polygons with the one given in initialPageData

What do you mean with "the one given in initialPageData"? I would've thought we push all the saved polygons in initialPageData?

**Comment by zandre-eng** [comment]
> What do you mean with "the one given in initialPageData"? I would've thought we push all the saved polygons in initialPageData?

@Charl1996 We send the list of saved polygons [here](https://github.com/dimagi/commcare-hq/blob/875cf7cb80caf5146cb6cc3ef6249e0f577b8b1f/corehq/apps/geospatial/reports.py#L64) which then gets loaded into the template [here](https://github.com/dimagi/commcare-hq/blob/875cf7cb80caf5146cb6cc3ef6249e0f577b8b1f/corehq/apps/geospatial/templates/geospatial/map_visualization_base.html#L17). After changing report filters or loading the page, we fetch the list of saved polygons from `initialPageData` [here](https://github.com/dimagi/commcare-hq/blob/875cf7cb80caf5146cb6cc3ef6249e0f577b8b1f/corehq/apps/geospatial/static/geospatial/js/geospatial_map.js#L238).

Since `initialPageData` gets set in the template on page load, it doesn't get updated when we apply new report filters. After saving a new polygon and reapplying case filters we clear out the existing list of saved polygons and retrieve the list again from `initialPageData` which does not contain the newly saved polygon.

But talking through this, I'm wondering if this can actually be changed slightly so that we only fetch from `initialPageData` on page loads and not when reapplying filters. For the latter, we simply keep using the existing list in memory. That way, we won't need a refresh and will have an up-to-date list of saved polygons. Let me look into this.

**Comment by Charl1996** [comment]
@zandre-eng Thanks for the explanation.

Also, your idea sounds like a good thing to explore.

**Comment by zandre-eng** [comment]
> But talking through this, I'm wondering if this can actually be changed slightly so that we only fetch from initialPageData on page loads and not when reapplying filters. For the latter, we simply keep using the existing list in memory. That way, we won't need a refresh and will have an up-to-date list of saved polygons. Let me look into this.

Unfortunately, it seems this doesn't work. When reapplying the case filters we lose the KO binding and so the existing list of saved polygons is lost as well and we have to retrieve the list again from `initialPageData`. We could perhaps try and store this list outside of the KO instance to persist it in the browser, but this smells of messy code.

**Review by Charl1996 — APPROVED** [review]
Change seems good to me

**Pull request merged**
