### PR TITLE
Change Standard Plan's User limit to 125

### PR DESCRIPTION
**Pull request by gbova**
I accidentally bumped the user limit for the publicly available Standard Edition Plan back down to 50 in my Annual Pricing PR:
https://github.com/dimagi/commcare-hq/pull/21601/files#diff-225accb0c9040d0a6a0a916674b1f5f6R24

This PR changes it back to 125

### CODE REVIEW

**Comment by mkangia** [comment]
Oops. How does this effect the user who are currently on the plan, they start getting more straight away?

**Comment by gbova** [comment]
@mkangia I'm not sure. Julie and Kai pointed this out to me, because a customer flagged this. Julie may need to do an audit of all new subscriptions and update them to the new version, which is why they want this out soon.

**Comment by mkangia** [comment]
thanks @gbova.
I would let @nickpell to share review from his experience with accounting. I don't have enough context to assure its working. Otherwise, syntax wise looks fine to me

**Comment by gbova** [comment]
Good call!

**Review by nickpell — APPROVED** [review]
Should be easy to query production and softlayer to see if there are any subscriptions on the erroneous software plan version.  Depending on how many, you can either have Julie fix manually or script a fix.

**Pull request merged**
