### PR TITLE
App manager v2: allow rearranging of registration forms

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?256712

@biyeun Could turn this into an add-on instead, but after mulling it over, I don't think making reg forms come first is likely to enhance people's understanding of case management (or that they'll understand why they can't rearrange the reg forms), I think it's enough that case lists are created with the reg form first. Let me know if you think this is an important constraint for us to have.

cc @benrudolph

### CODE REVIEW

**Comment by biyeun** [comment]
@orangejenny Doesn't allowing people to drag the reg forms also enable them to drop it into another module? Won't that confuse things?

**Comment by orangejenny** [comment]
It does allow them to drop reg forms into another module, which will strip the case management if the other module doesn't use cases. Don't think it's any more or less confusing that being able to drag followup forms into survey modules.

My guess is that it isn't going to be obvious to new users why they can drag some forms around but not others - I don't actually think I can clearly articulate what this constraint is adding.

**Review by benrudolph — APPROVED** [review]
👍 agree that it won't make much sense to the user. maybe if you wanted to go down that route you could show a user an error message for why they can't move it

**Comment by biyeun** [comment]
ok cool

**Comment by biyeun** [comment]
I do like ben's idea though of alerting the user when dragging the reg form to another module. I think reg forms should be paired with their caselists...otherwise the whole point of the case list falls apart, no?

**Comment by orangejenny** [comment]
@biyeun let's offline at the onboarding meeting tomorrow

**Comment by orangejenny** [comment]
Offlined, should be good to merge. I'll do the other reg form-related changes in another PR, would like to get this one out since it was reported as a bug.

**Pull request merged**
