### PR TITLE
Use `user_es_query` in Submit History

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke this optimizes the submit history report. given the complexity of this portion it's hard to tell if this is the _exact_ same functionality, however if we believe that `user_es_query` gets all relevant user ids (which is an assumption we make elsewhere), then this should be the same functionality. ran a little profiling as well:

```
In [7]: timeit.timeit('from corehq.apps.reports.filters.users import LocationRestrictedMobileWorkerFilter as EMWF; EMWF.pull_users_and_groups("aspace", ["t__0","t__4"])', number=100)
Out[7]: 8.12283182144165
```

```
In [9]: timeit.timeit('from corehq.apps.reports.filters.users import LocationRestrictedMobileWorkerFilter as EMWF; EMWF.user_es_query("aspace", ["t__0","t__4"]).values_list("_id")', number=100)
Out[9]: 0.4410839080810547
```

This is on my local domain which doesn't even have 100 users. `pull_users_and_groups` is a _horrible_ function that should never ever be called. it uses the dreaded `get_all_users_by_domain` not once, not twice, but 3 times (depending on what's passed in). in addition the submit history make _another_ call to `get_all_users_by_domain`. so in sum it can be called up to 4 times during a call to submit history, and the function is not cached. this PR removes all those calls

to test this i ran some basic queries on this branch vs. master branch

cc: @millerdev

### CODE REVIEW

**Comment by benrudolph** [comment]
(label because i want to do a little more testing)

**Review by snopoke — COMMENTED** [review]
:heart:

**Review by millerdev — APPROVED** [review]
Wow, nice rewrite!

**Comment by benrudolph** [comment]
Ok i'm happy with this. I've single selectors (user types, users, groups). I've tested unioning of selectors (groups + user types, groups + single users, user types + single users). From what i can tell the functionality is the same

**Comment by snopoke** [comment]
🚀

**Comment by NoahCarnahan** [comment]
🏎

**Pull request merged**
