### PR TITLE
EWS: Email reports

### PR DESCRIPTION
**Pull request by kkrampa**
http://manage.dimagi.com/default.asp?184008#1026483
Merged with master and improved #6405. 

Don't merge. It should be merged when migration will be completed (It should happen in this week)

### CODE REVIEW

**Comment by czue** [comment]
@kkrampa just ping when you want this reviewed

**Comment by kkrampa** [comment]
@czue I agreed with Mike that we run this task only once after switchover so now it can be reviewed and merged.

**Comment by kkrampa** [comment]
@czue We need to run this on friday or saturday so I hope you will find time to review this.

**Comment by czue** [comment]
:+1: looks good

**Pull request merged**
