### PR TITLE
[AWS SES] Use SNS notifications as primary source

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAASP-10242

##### SUMMARY
This makes sure we use SNS notifications (which have more reliable formatting and more complete information) as the primary source of information for handling email bounces. 

I will be making a followup PR that utilizes the extra bounce meta information when determining what emails to strip from the recipient list (for instance, if someone only has less than three `General`-typed bounces, we should still allow the email to go through as it could be a temporary thing, like a full inbox. Any `Suppressed` bounces should definitely not go through, as this means the AWS servers have already flagged this email as definitely problematic. Any `Complaints` should in the future not be as easily resolved on the end-user side and definitely warrants a support ticket to reinstate that email, as it resulted from direct action on the user's part sending email from us to their spam filter.

There will also be another followup PR regarding how we handle the Transient bounce information. Right now I just want to make sure everything is working properly getting this information from SNS into our system.

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
There is a lot of what looks like untested code in this PR (ex: 29679871c6ed868e3ed6157ac8f852a0651058de). I'm concerned that this will end up being a hard-to-maintain part of the codebase, and adding tests could help that situation. Thoughts?

**Comment by biyeun** [comment]
@millerdev I'll followup with some tests

**Comment by biyeun** [comment]
@millerdev tests added!

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Thanks for adding tests!

**Pull request merged**
