### PR TITLE
Stop phone two way sync

### PR DESCRIPTION
**Pull request by gcapalbo**
Once https://github.com/dimagi/commcare-hq/pull/11848 is merged, i'll merge this with master to reduce the diff.  Also I want to wait a day with https://github.com/dimagi/commcare-hq/pull/11848 being deployed before merging this.

@dannyroberts code buddy

### CODE REVIEW

**Comment by dannyroberts** [comment]
@gcapalbo i think this is to stop syncing between postgres and couch after your migration for sms models to postgres? Can I get a quick confirmation on that? Also, can you explain what `VerifiedNumber` versus `PhoneNumber` represent, and why this PR changes all of one to the other?

**Comment by dannyroberts** [comment]
Saw my answer to `VerifiedNumber` vs `PhoneNumber` in https://github.com/dimagi/commcare-hq/pull/11848, also seeing that most of the diff I see here is actually from that PR. Will hold off reviewing this until that one's merged in; I was just confused.

**Comment by gcapalbo** [comment]
sorry @dannyroberts for the confusion - i just merged master. this pr just removes any last references to the couch model and stops the two-way sync between VerifiedNumber and PhoneNumber. i put the hold off on merge label because i'd like to wait until tomorrow to merge this, just so that the code from #11848 runs for a day before we stop the sync.

**Comment by dannyroberts** [comment]
No worries! Awesome, this looks great. Lemme know when you're ready to merge!

**Comment by gcapalbo** [comment]
@dannyroberts i'm good to merge now

**Comment by gcapalbo** [comment]
:white_check_mark:

**Pull request merged**
