### PR TITLE
B3 Accounting Reports

### PR DESCRIPTION
**Pull request by biyeun**
@nickpell good to do a soft QA
cc: @millerdev 
review commit-by-commit

Affects these reports
screen shot 2016-02-23 at 3 51 33 pm
screen shot 2016-02-23 at 3 52 44 pm

Other screenshots
screen shot 2016-02-23 at 3 52 02 pm
screen shot 2016-02-23 at 3 53 03 pm
screen shot 2016-02-23 at 3 53 41 pm
screen shot 2016-02-23 at 3 53 56 pm
screen shot 2016-02-23 at 3 54 08 pm
screen shot 2016-02-23 at 3 54 32 pm

### CODE REVIEW

**Comment by biyeun** [comment]
Note that https://github.com/dimagi/commcare-hq/pull/10447 is part of this PR, once that's merged in i can update this pr, unless this gets merged in before I do the other accounting stuff

**Comment by nickpell** [comment]
Soft touch QA looks good.  The one thing I would was this js error:

screen shot 2016-02-23 at 4 45 57 pm

on the SMS gateway fees page.

**Comment by biyeun** [comment]
interesting...i'm not seeing that locally. Did you `bower install`?

**Comment by biyeun** [comment]
@nickpell yes, not seeing it even running less in debug mode and compressor

**Comment by nickpell** [comment]
> Did you bower install?

Looks like that was it

**Pull request merged**
