### PR TITLE
pass multimedia map into webformsession

### PR DESCRIPTION
**Pull request by wpride**
@benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
👍 on ✔️

**Comment by wpride** [comment]
@benrudolph see ticket here http://manage.dimagi.com/default.asp?233922 for a question I had - the multimedia map still appears to be empty. Looks like this comes straight from the couch doc? Have any insight on what might be happening?

**Comment by benrudolph** [comment]
(will look into it soon)

**Comment by benrudolph** [comment]
sorry just got to this. it's because we grab only brief apps in the cloudcare view: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cloudcare/views.py#L120

**Comment by benrudolph** [comment]
i think it may make sense to have `appselect:getApp` actually make a request to get the full app

**Pull request merged**
