### PR TITLE
Update scripts/ files to be more easily executable

### PR DESCRIPTION
**Pull request by orangejenny**
https://github.com/dimagi/commcare-hq/pull/28717#discussion_r514460389

Also renamed & moved the git-heat script.

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
These should not be executable:
- `scripts/cloudant/README.md`
- `scripts/cloudant/manage_cloudant.py`
- `scripts/update-code.sh` (contains three different functions, should be sourced)

`*.py` files will not work properly if they do not have a shebang line (`#! /usr/bin/env python`):

- `scripts/coudant/*.py` (except `manage_cloudant.py`)
- `scripts/yaml_static_strings.py`

Might want to announce that `hammer.sh` and `staticfiles-hammer.sh` are changing since I'm guessing most people who use them have added them to `.profile` or similar by now (and they probably do not want to run hammer every time they start a new shell).

**Comment by orangejenny** [comment]
@millerdev Thanks, I did `git add` carelessly. Updated so only the shell scripts are executable.

**Review by millerdev — APPROVED** [review]
Are you planning to announce that `hammer.sh` and `staticfiles-hammer.sh` are changing?

**Comment by orangejenny** [comment]
Yep, was just waiting to see if you had other comments.

@dimagi/team-commcare-hq FYI this PR changes `hammer` and `staticfiles-hammer` to make them plain scripts instead of functions within scripts. If you have strong objections, do speak up. I'll leave this PR open for a another day or two.

**Pull request merged**
