### PR TITLE
make StringIO imports compatible

### PR DESCRIPTION
**Pull request by nickpell**
@dimagi/py3

### CODE REVIEW

**Comment by nickpell** [comment]
test failures are real

**Comment by nickpell** [comment]
maybe we need to distinguish between
https://pythonhosted.org/six/#six.StringIO
and
https://pythonhosted.org/six/#six.BytesIO

**Comment by kaapstorm** [comment]
Yeah, [this cheat sheet](http://python-future.org/compatible_idioms.html#stringio) seems to suggest that we should be using `io.BytesIO` for handling byte strings in Python 2.

**Comment by millerdev** [comment]
This is probably going to require a case-by-case analysis to figure out which of `BytesIO` or `StringIO` should be used, and probably custom code in some situations to explicitly do the bytes/text conversion that is currently being done implicitly by Python 2.

**Comment by nickpell** [comment]
closing out of date PR

**Pull request closed without merging**
