### PR TITLE
Add Report Builder V2 Release Notifications

### PR DESCRIPTION
**Pull request by biyeun**
@orangejenny 
cc @sheelio 
buddy @mkangia 
screen shot 2017-11-02 at 12 47 45 am
screen shot 2017-11-02 at 12 52 27 am

### CODE REVIEW

**Review by orangejenny — COMMENTED** [review]
Looks good. Did y'all talk about having the alert link to the blog? https://www.dimagi.com/blog/visualize-your-data-faster-with-commcares-new-report-builder-2/

**Comment by biyeun** [comment]
@sheelio can you peep at @orangejenny's comment? thanks

**Comment by orangejenny** [comment]
realized Sheel's offline, maybe @krsdimagi has an opinion

**Comment by sheelio** [comment]
@biyeun  @orangejenny 

Sounds good to have a link to the blog if easy to show in the bubble

**Comment by sheelio** [comment]
@biyeun 

Is this good to merge?

**Comment by biyeun** [comment]
@sheelio should be g2m now

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
