### PR TITLE
Django 1.6

### PR DESCRIPTION
**Pull request by snopoke**
@emord 

Added support to uninstall specific versions of a requirement prior to upgrading to make sure that old files are removed.

### CODE REVIEW

**Comment by snopoke** [comment]
This has been on staging for a week now.

**Comment by esoergel** [comment]
:tada: :balloon: :cake:

**Comment by emord** [comment]
@orangejenny @czue Heads up for interrupt in case any weird issues pop up in deploy. (doubt it as it's been on staging for a while)

Will merge when tests pass

**Comment by czue** [comment]
:+1:

**Pull request merged**
