### PR TITLE
remove type="text/javascript" from all <script> tags

### PR DESCRIPTION
**Pull request by dannyroberts**
This routinely drives me irrationally crazy

### CODE REVIEW

**Comment by dannyroberts** [comment]
@dimagi/js-team @proteusvacuum

**Comment by dannyroberts** [comment]
This reduces our total codebase size by 6KB :)

**Comment by benrudolph** [comment]
me too!!! totally obsolete in html5

**Comment by benrudolph** [comment]
looks like you missed your window for no merge conflicts 😞

**Comment by dannyroberts** [comment]
Conflicted with my other branch which I then merged in for exactly that reason. Conflict fixed!

**Comment by benrudolph** [comment]
do you mind if i wait til tests finish so we can ensure compression works?

**Comment by dannyroberts** [comment]
not in the least

**Comment by dannyroberts** [comment]
✅  It's also on staging and poking around did not reveal any console errors. Of course that only says that there isn't something broken on the base page, but if there'd been some systematic error in my find and replace, that would likely have caught it

**Comment by benrudolph** [comment]
💰

**Comment by benrudolph** [comment]
(didn't review closely, also trusting your find and replace ninja skills)

**Pull request merged**
