### PR TITLE
Command to restore blobs in S3

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

This is an effort to codify/make more permanent [Danny's code used to restore blobs in S3](https://dimagi-dev.atlassian.net/browse/SAAS-13713?focusedCommentId=214078) in the event of accidental deletion. A similar, though not exact, version of this was used on production to restore blobs recently.
### Safety story

Just a management command useful to extreme firefighting scenarios.
### QA Plan

No QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
I think given how unusual / idiosyncratic the circumstances that call for this command are, it would make sense for the command to be named something that coveys a little more "this probably isn't the command you're looking for". A word like "emergency" or something like that might help convey.

I'd also add a little more about the circumstances in which you'd use this command in the docstring; for example that if forms and cases have been deleted then those have to be manually restored from backup before running this command.

Otherwise looks great!

**Comment by gherceg** [comment]
I can't decide if this command should also handle cleaning up the DeletedBlobMeta objects. I'm leaning towards yes, but I also don't want this command to promise too much. I think there are potential scenarios where there wouldn't be DeletedBlobMeta objects, so it makes sense to keep that responsibility on the caller as that is more tightly coupled with restoring the SQL BlobMeta objects.

**Review by millerdev — APPROVED** [review]

**Comment by gherceg** [comment]
Apologies for dropping this. @dannyroberts are you content with me merging this?

**Comment by dannyroberts** [comment]
Yep!

**Pull request merged**
