### PR TITLE
render message as html in email

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/QA-1203
Introduced in https://github.com/dimagi/commcare-hq/pull/27182/files
Picking suggestion from http://masnun.com/2014/01/09/django-sending-html-only-email.html

##### SUMMARY
Render email content as html

##### FEATURE FLAG
`LOCATION_REASSIGNMENT`

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Seems fine given that these are internal-only emails.

**Comment by mkangia** [comment]
> Seems fine given that these are internal-only emails.

@orangejenny is this not a good solution otherwise?

**Comment by orangejenny** [comment]
For external emails I don't think we can assume people are reading them in HTML.

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
@orangejenny I will confirm my understanding but what I was thinking was that the email would now render as a HTML and hence it won't have BR tags but a new line for real. Will that not be true if it's not read on browser, is what you are saying?

**Comment by orangejenny** [comment]
@mkangia My understanding is that if you read the email on a text-based client (e.g., pine), it'll display the HTML markup, as described in the ticket, and that's why we typically send both an HTML version and a text version of emails.

**Pull request merged**
