### PR TITLE
soft assert when case created without create block

### PR DESCRIPTION
**Pull request by snopoke**
RE http://manage.dimagi.com/default.asp?246559

FYI @amstone326

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Comment by emord** [comment]
This seems somewhat easily testable. Thoughts on adding one?

**Comment by amstone326** [comment]
@snopoke Awesome, this is great, thank you. Is there a way I can set myself up to get notified when this occurs? That way I'll be able to look into the logs right away. (Or if you already get notified then you could just pass it along to me when you do)

**Comment by snopoke** [comment]
@emord not sure what test I would write. This is related to a potential mobile bug.

@amstone326 these should come to the commcarehq-ops email list. My plan was to forward them to you too.

**Comment by amstone326** [comment]
👍 great

**Comment by emord** [comment]
@snopoke I initially thought a high level test where we submit a case block with update and verify that a soft assert is thrown. Not sure if that is useful though

**Comment by czue** [comment]
will be fun/interesting to see how frequently this happens.

**Comment by snopoke** [comment]
@emord we don't have a precedent for testing soft asserts and normally I don't think there is that much value in it but since this could be rare and we want to make sure we get notified it seems worth knowing that it get's fired. Test added: 2342f44

**Comment by dimagimon** [comment]
There are 6 errors:

* corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py, line 16 - F401 'softer_assert' imported but unused
* corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py, line 216 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_factory.py, line 191 - E501 line too long (128 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_factory.py, line 213 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_cleanliness.py, line 562 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_cleanliness.py, line 563 - E501 line too long (117 > 115 characters)

**Comment by dimagimon** [comment]
There are 6 errors:

* corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py, line 16 - F401 'softer_assert' imported but unused
* corehq/ex-submodules/casexml/apps/case/tests/test_bugs.py, line 216 - E501 line too long (121 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_factory.py, line 191 - E501 line too long (128 > 115 characters)
* corehq/ex-submodules/casexml/apps/case/tests/test_factory.py, line 213 - E501 line too long (136 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_cleanliness.py, line 562 - E501 line too long (127 > 115 characters)
* corehq/ex-submodules/casexml/apps/phone/tests/test_cleanliness.py, line 563 - E501 line too long (117 > 115 characters)

**Comment by snopoke** [comment]
:white_check_mark: build finally passed!

**Pull request merged**
