### PR TITLE
Fix UCR data source Session usage

### PR DESCRIPTION
**Pull request by NoahCarnahan**
There are two places where the default engine id was being used to retrieve a database session instead of getting the engine id from the data source itself. This was happening in the code that queries the data source to figure out the expanded column columns, and the code that queries the data source to get the choices for a filter. In both cases, `corehq.db.Session()` was being used (which uses the `DEFAULT_ENGINE_ID`). This PR replaces those and instead accesses the session through `IndicatorSqlAdapter`.

I'm pretty sure this will solve [Ticket #182856](http://manage.dimagi.com/default.asp?182856), [Ticket #183489](http://manage.dimagi.com/default.asp?183489), and [Ticket #182951](http://manage.dimagi.com/default.asp?182951).

@czue @nickpell 
cc @kaapstorm 
best reviewed commit-by-commit

### CODE REVIEW

**Comment by nickpell** [comment]
:+1: Looks good pending tests

**Comment by czue** [comment]
gracias amigo!

**Comment by czue** [comment]
not sure how i missed these when i first rolled out multi-db support but thanks for fixing

**Comment by NoahCarnahan** [comment]
No worries!

**Pull request merged**
