### PR TITLE
Add grid menu configuration

### PR DESCRIPTION
**Pull request by NoahCarnahan**
Adds an option (behind a feature flag) to the applications setting page for enabling grid menus.

cc @kaapstorm FYI @ctsims, @snopoke 
Best reviewed commit-by-commit.
Looking to get this deployed before weekend, so quick review would be much appreciated.

### CODE REVIEW

**Comment by snopoke** [comment]
Looks OK. Is there a spec for this?

**Comment by NoahCarnahan** [comment]
No spec that I know of. @ctsims told me that it should work like this:
```
When use_grid_menus is enabled:
    If none of the menu elements had id="root":
        add a menu item with id="root"
    For each menu where id="root":
        add style="grid" to that menu element
```

**Comment by ctsims** [comment]
Spec checks out.

-Clayton

**Comment by snopoke** [comment]
:+1: merge when build passes

**Comment by NoahCarnahan** [comment]
:white_check_mark:

**Comment by ctsims** [comment]
Woo! Thanks for the quick turnaround on these issues, Noah, and thanks for
the proactive review, Simon, you guys are crushing it!

-Clayton

**Pull request merged**
