### PR TITLE
fixing red code text

### PR DESCRIPTION
**Pull request by calellowitz**
@biyeun @benrudolph cc: @emord @czue 
http://manage.dimagi.com/default.asp?227867#1152562
screen shot 2016-05-25 at 3 43 28 pm

### CODE REVIEW

**Comment by biyeun** [comment]
@calellowitz please make the background `@cc-bg` and add a 1px border of `darken(@cc-bg, 50%)`, thanks!

**Comment by calellowitz** [comment]
@biyeun 
screen shot 2016-05-25 at 4 14 47 pm

**Comment by benrudolph** [comment]
hot! 🔥

**Comment by biyeun** [comment]
good on ✅

**Comment by snopoke** [comment]
Not so hot on the raw XML view of a form: 
image

**Comment by snopoke** [comment]
Also 
image

**Comment by snopoke** [comment]
https://github.com/dimagi/commcare-hq/pull/11948

**Pull request merged**
