### PR TITLE
Automate removing branches from staging.yml

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

Whenever a PR is merged and the branch is deleted, if the branch is not also removed from `scripts/staging.yml` file it results in an error that we need to manually resolve when rebuilding staging.

We should be able to rely on a github action to run whenever a PR is merged that will remove the branch from `scripts/staging.yml` if applicable, and don't need to worry about if the branch is deleted or not.

The one unknown I still have is if the github action will have write permission to this repository, especially directly on master. Seems like a big risk to allow that.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
More appropriately a draft PR, though in its current form, this would simply run and output the diff for the scripts/staging.yml file.

**Review by millerdev — COMMENTED** [review]
I don't think it's a good idea to have a github action that commits to master. Also, I think it will not be possible without granting extra permissions. I'm -1 on the planned outcome here.

**Comment by esoergel** [comment]
@millerdev there's been some discussion on slack and on this ticket:
https://dimagi-dev.atlassian.net/browse/CDTW-27
I believe the current plan is to move staging.yml to a standalone repo with different permissions structure, which might also let us disable push-to-master entirely in commcare-hq.  I can't comment on how far Graham's ambitions and availabilty extend, though.

**Comment by gherceg** [comment]
> I can't comment on how far Graham's ambitions and availability extend, though.

Yeah at the moment I don't have the time to pick this up, but agree this PR is a no-go so will close it out.

**Pull request closed without merging**
