### PR TITLE
actually useful error message for bad status code in repeaters

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @gcapalbo yeah don't know why i didn't do this the first time...

### CODE REVIEW

**Comment by benrudolph** [comment]
screen shot 2016-03-17 at 11 56 48 am

**Comment by czue** [comment]
not mergable and also build fail looks real:
```
======================================================================
ERROR: test_simple_post_with_cached_timeout_bad_http_response (corehq.apps.repeaters.tests.test_simple_post.SimplePostCacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/apps/repeaters/tests/test_simple_post.py", line 58, in test_simple_post_with_cached_timeout_bad_http_response
    simple_post_with_cached_timeout('abc', 'http://google.com')
  File "/mnt/corehq/apps/repeaters/models.py", line 77, in simple_post_with_cached_timeout
    message = u'{}: {}'.format(resp.status_code, resp.reason)
AttributeError: 'MockResponse' object has no attribute 'reason'
```

**Comment by benrudolph** [comment]
ty updated

**Comment by gcapalbo** [comment]
:+1: waiting on build

**Pull request merged**
