### PR TITLE
Various changes to attempt to get run_ptop working locally

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

As part of the kafka+zookeeper upgrade, I figured it would be nice to get pillows running locally as a way to test that upgrade is safe locally in addition to tests, but this PR doesn't quite get `run_ptop` all the way there. I'm not looking to merge this, but rather to get more input. 

The current blocker is an `AppRegistryNotReady` when first starting the pillow in the new process. I tried adding `import django; django.setup()` at what I believed was the entrypoint for pillows on new processes `ConstructedPillow.run`, but that seems too late in the call chain.

I'm also unsure how pillows are run on production, and if there is overlap with changes here that would impact that so I'd appreciate more input from that perspective.
### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [ ] Risk label is set correctly
- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by calellowitz** [comment]
> I'm also unsure how pillows are run on production, and if there is overlap with changes here that would impact that so I'd appreciate more input from that perspective.

Everything Joel said is correct about how we generate the commands to run pillows. The actual commands themselves all look vaguely like this (example from the pillow you modified in this PR
```
./manage.py run_ptop --pillow-name SqlSMSPillow --num-processes=1 --process-number=0
```

If the main gist of your question was whether we use `run_ptop` in production, the answer is yes, but always for specific pillows, not multiple at once. It is possible some of the issues you face come from that, although I would not be surprised if others come from the mac as you mentioned.

**Comment by gherceg** [comment]
Could have sworn I left a comment here about discoveries that led to reverting most of what was added initially. The multiprocessing default start method is an issue on macOS, since it is now spawn and not fork (a change made in python 3.8). I initially tried to get this to work with spawn, but the wall I hit made me second guess that, so I went back to explicitly specifying fork, which is still the default behavior of linux, just not macOS. So without the default start method change, even running a single pillow at a time will fail on mac, but with the change it will succeed.

**Comment by joxl** [comment]
> The multiprocessing default start method is an issue on macOS, since it is now spawn and not fork

Does this mean that as-is, executing `ptop_run` on macOS is a no-go due to platform differences in Python's `multiprocessing` library? Are you (or anyone reading this) aware of other areas in HQ that have this kind of issue where a fundamental component of HQ Python code doesn't work on "supported" Unix's (e.g. Linux and Darwin kernels)?

**Comment by calellowitz** [comment]
> 2\. Are you (or anyone reading this) aware of other areas in HQ that have this kind of issue where a fundamental component of HQ Python code doesn't work on "supported" Unix's (e.g. Linux and Darwin kernels)?

We have this page https://github.com/dimagi/commcare-hq/blob/master/DEV_SETUP_MAC.md listing a number of issues macs run into, and at least one more is described in our main dev setup docs https://github.com/dimagi/commcare-hq/blob/master/DEV_SETUP.md

That mac page, somewhat obliquely, references issues with pillows that this PR tries to address insofar as it provides pillow workarounds for mac users, and implies `run_ptop` does not work. The other big thing that we have had issues with in the past on platforms other than linux (and specifically Ubuntu 18.04, which is our supported "production" environment), is `pghashlib`, which I believe works on current M1 macs, but didn't at various times in the past.

**Comment by snopoke** [comment]
Closing old PRs, reopen if needed.

**Pull request closed without merging**
