### PR TITLE
cleanup OData tests

### PR DESCRIPTION
**Pull request by nickpell**
The first commit replaces the use of a decorator with a ```with``` statement.  That enables writing certain test cases without introducing a helper function, which was previously required when subclasses use a class-level decorator that overrides the individual function decorators.  I wasn't able to confirm if the overriding behavior is intentional or a bug, but either way the new code is cleaner.

The second commit enables the OData feature flag when testing other conditions that cause the request to fail.  This way, we test a single failing condition in isolation, rather than testing a failing condition when the feature flag will also fail.  This change also means that the API returns a 401 (expected) rather than a 404 which is returned whenever the feature flag is not enabled. 

Recommend 🐡 and ```?w=1```.

### CODE REVIEW

**Comment by esoergel** [comment]
I'm not quite following - what was the reason for the old structure?  Are you saying that there are test cases which set the flag to True at the test class, and to False in the method (or vice versa), and that that has an unclear resolution?  Or that enabling two different feature flags doesn't work?

I'd expect `@flag_enabled` at the top of each of these classes - seems odd to enable it for only a portion of some of the methods, aside from `test_missing_feature_flag`.  Have you tried putting the decorator at the top of the class, then disabling it within that method?  (there's also `flag_disabled`)

**Comment by nickpell** [comment]
> Or that enabling two different feature flags doesn't work?

This is the issue

> Have you tried putting the decorator at the top of the class, then disabling it within that method?

For some reason this approach causes ```test_request_succeeded``` to fail.

**Comment by nickpell** [comment]
@esoergel f9e410e

**Review by esoergel — APPROVED** [review]
Offlined with Nick - the chief issue as I understand it is this:
```python
class MyTests(TestCase):
    def test1(self):
        ...

    def test2(self):
        ...


@patch('myfn')
class MyAdditionalTests(TestCase):
    def test1(self):
        ...
```
When used as a class decorator, `@patch` automatically decorates all methods in that class beginning with `test_`.  However, since `MyAdditionalTests` doesn't override `test2`, that `@patch` call decorates the superclass.  This results in:
* `MyTests.test1` - not patched
* `MyTests.test2` - unexpectedly patched!
* `MyAdditionalTests.test1` - patched
* `MyAdditionalTests.test2` - patched

Sounds like bit of a nightmare to resolve, whatever works.

**Comment by nickpell** [comment]
Merging since last update is just comments

**Pull request merged**
