### PR TITLE
Fix missing logo

### PR DESCRIPTION
**Pull request by nickpell**
fixes http://manage.dimagi.com/default.asp?163595

Confirmed backwards compatibility with apps that have working logos.  If the logo does not appear in an existing app, it simply can be re-uploaded to fix it.

### CODE REVIEW

**Comment by czue** [comment]
I don't have too much context on this part of the code, but the change looks good to me. @nickpell do you know who might be more qualified to quickly sign off and merge?

**Comment by nickpell** [comment]
maybe @biyeun or @dannyroberts ?

**Comment by nickpell** [comment]
bump

**Comment by dannyroberts** [comment]
I don't have a ton of context about how this works, but the changes look like they make the code a little simpler, which is good. As long as you're confident it fixes the issue, this looks good to me!

**Comment by biyeun** [comment]
ditto what danny said

**Pull request merged**
