### PR TITLE
Catch ResourceNotFound in paginate_view

### PR DESCRIPTION
**Pull request by kaapstorm**
This resolves my "missing" error when migrating user db from a clean install (i.e. nothing to migrate).

@dannyroberts I don't know why I was getting the error though, nor whether this change is a good idea.
cc @NoahCarnahan

### CODE REVIEW

**Comment by czue** [comment]
I think the thing that isn't being found is the view, and force-syncing in a migration might be the appropriate thing to do. for example: [something like this](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/userreports/migrations/0001_initial.py#L16) @dannyroberts what do you think?

**Comment by millerdev** [comment]
@czue recommended this branch to me when I ran into this error:
```
$ ./manage.py run_doctype_migration user_db_migration --initial
Traceback (most recent call last):
  ...
couchdbkit.exceptions.ResourceNotFound: missing
```
It got me past that issue, so thanks @kaapstorm!

**Comment by kaapstorm** [comment]
:smile: So glad it wasn't just me, @millerdev

**Comment by dannyroberts** [comment]
seems like this was because all_docs/by_doc_type didn't exist yet for you, and then you ran `./manage.py migrate` to get it, and then that failed because of my choice to block the migration on this manual step, which requires all_docs/by_doc_type. Makes sense! Shouldn't happen quite like this in the future now that you have it, but it's good to keep this kind of deadlock in mind; hadn't considered it.

**Comment by dannyroberts** [comment]
Taking me a while to realize this, but this is a problem even on first-time setup of HQ. Sorry I missed that! I think the most correct solution is to do sync couchdb before migrations—then the view would exist and we wouldn't end up in this catch 22: https://github.com/dimagi/commcare-hq/pull/8530

**Pull request closed without merging**
