### PR TITLE
misc updates (see commits for details)

### PR DESCRIPTION
**Pull request by snopoke**
@czue @benrudolph 
buddy @sravfeyn 

:fish:

### CODE REVIEW

**Comment by czue** [comment]
build fail looks related:
```
======================================================================
FAIL: test_get_form_operations (corehq.form_processor.tests.test_form_dbaccessor.FormAccessorTestsSQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/form_processor/tests/test_form_dbaccessor.py", line 103, in test_get_form_operations
    self.assertEqual(XFormOperationSQL.ARCHIVE, operations[0].operation)
AssertionError: 'archive' != u''
----------------------------------------------------------------------
```

**Comment by czue** [comment]
(also why is that test running in two parts of the matrix?)

**Comment by snopoke** [comment]
It gets run once with no sharding and then once with sharding

**Comment by czue** [comment]
ah that makes sense

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/sql_accessors/tests.py, line 1 - F401 'uuid4' imported but unused
* corehq/sql_accessors/tests.py, line 3 - F401 'settings' imported but unused
* corehq/sql_accessors/tests.py, line 5 - F401 'skipUnless' imported but unused
* corehq/sql_accessors/tests.py, line 7 - F401 'CommCareCaseSQL' imported but unused
* corehq/sql_accessors/tests.py, line 7 - F401 'XFormInstanceSQL' imported but unused
* corehq/sql_accessors/tests.py, line 8 - F401 'FormProcessorTestUtils' imported but unused
* corehq/sql_accessors/tests.py, line 8 - F401 'create_form_for_test' imported but unused
* corehq/sql_accessors/tests.py, line 9 - F401 'PartitionConfig' imported but unused

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/sql_accessors/tests.py, line 1 - F401 'uuid4' imported but unused
* corehq/sql_accessors/tests.py, line 3 - F401 'settings' imported but unused
* corehq/sql_accessors/tests.py, line 5 - F401 'skipUnless' imported but unused
* corehq/sql_accessors/tests.py, line 7 - F401 'CommCareCaseSQL' imported but unused
* corehq/sql_accessors/tests.py, line 7 - F401 'XFormInstanceSQL' imported but unused
* corehq/sql_accessors/tests.py, line 8 - F401 'FormProcessorTestUtils' imported but unused
* corehq/sql_accessors/tests.py, line 8 - F401 'create_form_for_test' imported but unused
* corehq/sql_accessors/tests.py, line 9 - F401 'PartitionConfig' imported but unused

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
