### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by emord**
@proteusvacuum 

Like this https://github.com/dimagi/commcare-hq/blob/master/custom/ilsgateway/models.py#L134

### CODE REVIEW

**Comment by emord** [comment]
from slack: 

Farid Rener [11:54] 
is anyone else getting a `Your models have changes that are not yet reflected in a migration, and so won't be applied.` message? when I run `makemigrations` I get a new migration in ilsgateway that does an `AlterField` on `report_date`, but I can’t see anything that has changed recently...(edited)

​[11:55] 
on the `DeliveryGroupReport` model

**Comment by proteusvacuum** [comment]
yes, that's the one... what would have made it start showing up? `blame` doesn't show that line being edited recently...

**Comment by emord** [comment]
I think it's always been there, but I've just ignored it since we can't get rid of that error anyways.

Also running `makemigrations` locally actually makes a django migration in your django.auth folder in the virtualenv because of our userhack. I think it actually means there's a conflict locally when upgrading to django 1.8 (shouldn't affect prod because we don't run `makemigrations` there)

**Comment by proteusvacuum** [comment]
weird.

**Pull request merged**
