### PR TITLE
App Manager V2 Split updated to match changes in onboarding branch

### PR DESCRIPTION
**Pull request by biyeun**
- a continuation of https://github.com/dimagi/commcare-hq/pull/13680, this copies the relevant V1 files over to V2, and then updates the V2 templates to match what is on onboarding. No V1 (read: production) files should have been harmed in this process.
- also adds diffs and final template tests for the files added to V2

I know this is enormous, but when I picked this up the separate onboarding branch was already huge to begin with and unmerged with master due to how intermingled the templates used to be!

@orangejenny @benrudolph 
cc @dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 14 errors:

* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 62 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 138 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 208 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 210 - 'data' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 275 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 291 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 302 - Missing trailing comma. (comma-dangle)
* corehq/apps/app_manager/static/app_manager/js/app_manager_media.js, line 155 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/management/commands/build_app_manager_v2_diffs.py, line 6 - F401 'sys' imported but unused
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 373 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/templatetags/xforms_extras.py, line 46 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views/apps.py, line 129 - F841 local variable 'form' is assigned to but never used
* corehq/apps/app_manager/views/modules.py, line 865 - F812 list comprehension redefines 'module' from line 845
* corehq/apps/app_manager/views/modules.py, line 873 - F841 local variable 'form' is assigned to but never used

**Comment by biyeun** [comment]
screen shot 2016-10-24 at 1 29 34 pm

😂 😂 😂 😂 😂 😂 😂 

oh dear...

**Comment by dimagimon** [comment]
There are 14 errors:

* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 62 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 138 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 208 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 210 - 'data' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 275 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 291 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 302 - Missing trailing comma. (comma-dangle)
* corehq/apps/app_manager/static/app_manager/js/app_manager_media.js, line 155 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/management/commands/build_app_manager_v2_diffs.py, line 6 - F401 'sys' imported but unused
* corehq/apps/app_manager/suite_xml/post_process/workflow.py, line 373 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/templatetags/xforms_extras.py, line 46 - E302 expected 2 blank lines, found 1
* corehq/apps/app_manager/views/apps.py, line 129 - F841 local variable 'form' is assigned to but never used
* corehq/apps/app_manager/views/modules.py, line 865 - F812 list comprehension redefines 'module' from line 845
* corehq/apps/app_manager/views/modules.py, line 873 - F841 local variable 'form' is assigned to but never used

**Comment by biyeun** [comment]
ugh ok i'm going to split this out into a couple parts because this is a disaster to review

**Comment by orangejenny** [comment]
> ugh ok i'm going to split this out into a couple parts because this is a disaster to review

thank you <3

**Pull request closed without merging**
