### PR TITLE
support related document lookups in data sources

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@snopoke fyi @nickpell @NoahCarnahan

**Comment by snopoke** [comment]
We did this together so @nickpell or @NoahCarnahan should merge

**Comment by NoahCarnahan** [comment]
Cool. looks really useful. Are fixtures accessible with this?

**Comment by czue** [comment]
if you have a fixture ID in a form or case you could look something up. you can also always save raw data from fixtures to SQL. doing user --> fixture value lookups is harder (though you can chain joins) just because it only works if you know the couch ID of the thing you're looking up

**Pull request merged**
