### PR TITLE
Warn on unmigrated apps

### PR DESCRIPTION
**Pull request by orangejenny**
screen shot 2016-11-21 at 1 08 46 pm

fyi @amsagoff 

@emord / @czue 

Hold off on merge until swiss server is migrated (currently waiting on client response).

### CODE REVIEW

**Comment by amsagoff** [comment]
great!

**Comment by emord** [comment]
looks like the test failure is legit

**Comment by orangejenny** [comment]
forgot to run `build_app_manager_v2_diffs`, should be good now

**Review by czue — APPROVED** [review]
:+1: whenever you're ready

**Comment by orangejenny** [comment]
Added logic to remove most references to an app's `vellum_case_management` property. It's now referenced only in
- The deploy page, where there's a warning if you try to revert to a non-VCM app
- The warning added in this PR

Removed "don't merge" label since migration is complete.

**Pull request merged**
