### PR TITLE
Grid menu for app preview

### PR DESCRIPTION
**Pull request by benrudolph**
@dimagi/ux @wpride when in a portuguese meeting and you can't speak portuguese ... implement grid view!

screen shot 2017-03-09 at 12 51 53 pm
screen shot 2017-03-09 at 12 51 50 pm
screen shot 2017-03-09 at 12 51 42 pm
screen shot 2017-03-09 at 12 50 29 pm

### CODE REVIEW

**Comment by benrudolph** [comment]
not quite ready yet, it doesn't properly respect when you decide to set grid view on a per module basis

**Comment by benrudolph** [comment]
also doesn't handle audio

**Comment by wpride** [comment]
@benrudolph Very sexy! I don't know how well we handle audio on mobile for grid views currently, might not be worth worrying about

**Comment by benrudolph** [comment]
nice that's good news!

**Comment by biyeun** [comment]
@benrudolph can we add about `20px` padding to the bottom of that pls? ;)

**Comment by benrudolph** [comment]
i knew you'd notice that 😝

**Comment by benrudolph** [comment]
✅ should also merge this guy: https://github.com/dimagi/formplayer/pull/314

**Pull request merged**
