### PR TITLE
B3 reports minor update

### PR DESCRIPTION
**Pull request by biyeun**
@benrudolph didn't get these up before you merged :)

### CODE REVIEW

**Comment by benrudolph** [comment]
thanks for follow lg2m

**Comment by benrudolph** [comment]
:+1: after tests

**Comment by biyeun** [comment]
@benrudolph resolved merge conflicts

**Comment by benrudolph** [comment]
tests failed, wonder if you have to merge in master

**Comment by biyeun** [comment]
@benrudolph i did...looking into it

**Comment by benrudolph** [comment]
:boom:

**Pull request merged**
