### PR TITLE
allow non-django databases for reporting DBs

### PR DESCRIPTION
**Pull request by snopoke**
buddy @kaapstorm

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Review by emord — APPROVED** [review]
Looks like a reasonable change to me. Is there any reason that you didn't just add a readonly setting to the entry in settings.DATABASES and skip calling migrate if that was set here: https://github.com/dimagi/commcare-hq/blob/je/more-sms-ui/corehq/sql_db/management/commands/migrate_multi.py#L34-L42

**Comment by snopoke** [comment]
@emord I did have that initially but it didn't seem 'safe' enough

**Comment by snopoke** [comment]
Since this only affects ICDS I'll update the settings and deploy tomorrow

**Comment by snopoke** [comment]
Closing in favour of https://github.com/dimagi/commcare-hq/pull/17656

**Pull request closed without merging**
