### PR TITLE
Use this month instead of previous month for project performance report

### PR DESCRIPTION
**Pull request by gherceg**
## Summary

For more context see the [JIRA ticket](https://dimagi-dev.atlassian.net/browse/SAAS-11855).

This support issue pointed to a data mismatch in the project performance report between the two graph types (bar vs tables). I believe the issue is due to using the previous month as the summary to compare against rather than the current month. 

The following is a bit confusing to word, so bear with me. The wording throughout the project performance report implies we are comparing the current month (e.g., March) to the two previous months (e.g., January and February), but in reality we are comparing the previous month (e.g., February) to its previous and next month (e.g., January and March). While this sounds the same and does share _some_ of the same data (e.g., form submission counts and deltas), this causes 2 issues. 

1) Users are not classified appropriately (e.g., new performing vs low performing vs inactive). For example, say a user named "tester" submitted 10 forms in January, 20 in February, and 10 in March. When viewing the project performance page in March, the current behavior classifies "tester" as a new high performing user since this is based on the February summary, when in reality, "tester" should now be classified as a low performing user for March. 

2) Users created in the current month do not appear in the tables at all, because the previous month does not know about these users.

This change is currently on staging and so far behaves as expected.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

I am working on some tests now.
### QA Plan

Undecided on if this should go through QA.
### Safety story

Tested on staging. This change only impacts the project performance report.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by gherceg** [comment]
@czue I'm curious to hear your input on this as I may be misunderstanding something fundamental to this report.

**Comment by gherceg** [comment]
I realized I needed to pass in the stub for 2 months ago now that I was using the current month as the base for comparison, so also went ahead and removed/replaced references to next month with two months ago...not exactly thrilled about this since it is definitely not as elegant.

**Comment by czue** [comment]
@gherceg responding to just the PR description to start:

> The wording throughout the project performance report implies we are comparing the current month (e.g., March) to the two previous months (e.g., January and February)

Is this true? For example:

> **Low Performing Users**
> These are people who used CommCare *last* month but didn't submit 15 forms.

and 

> **New Inactive Users**
> These are workers who stopped using CommCare *last* month.

That said, this does seem to be a bug (or a language correction) in the third chart, which states:

> New High Performing Users
> These are workers who submitted 15 forms this month and didn't last month.

My memory is a bit fuzzy but I recall that @nicknestle and I thrashed for a long time on these charts/definitions - at least in part because the data looks terrible on the first of the month and isn't helpful if you are looking at the current month.

Happy to review the code, but just wanted to point that out in case this is a spec/language issue and not actually a bug.

**Comment by czue** [comment]
@gherceg [This thread from an old doc I dug up](https://docs.google.com/document/d/1DrXuXIXVCDfvEaDRoBX6klct7FP9EaNRcyl3Bc6qeTc/edit?disco=AAAAAwx8UC4) i think confirms my suspicion. Basically the list is determined by data from the previous month, but the table also shows data in the current month.

If you mouse over the arrows you also get a hover text ("change in forms submitted since *last* month") which

**Comment by czue** [comment]
I added a "don't merge" label for until we're able to get alignment on whether this is actually a correct change to make.

**Comment by gherceg** [comment]
@czue I agree with what you're saying. I did have the thought that this change makes these tables essentially useless at the beginning of a month like you said, which doesn't sound ideal. Happy to just make the wording change for New High Performing Users instead.

**Comment by gherceg** [comment]
Closing since this is no longer relevant.

**Pull request closed without merging**
