### PR TITLE
Cleanup dispatch for scheduled reports

### PR DESCRIPTION
**Pull request by nickpell**
get rid of some of the ugliest code I've been ashamed to write

### CODE REVIEW

**Comment by nickpell** [comment]
@dannyroberts @NoahCarnahan @czue

**Comment by czue** [comment]
this definitely looks like an improvement! i'm not super comfortable in this part of the code so will let someone else review closely and merge

**Comment by NoahCarnahan** [comment]
looks good

**Comment by czue** [comment]
@nickpell just pinged you on [a ticket](http://manage.dimagi.com/default.asp?181656) that looks like it might have been caused by this change.

**Comment by nickpell** [comment]
looking

**Pull request merged**
