### PR TITLE
add management command to calculate the disk size of a domain's forms and cases

### PR DESCRIPTION
**Pull request by biyeun**
## Summary
A client wanted to calculate the physical/disk size of their forms and cases prior to export. This is a management command to help estimate that size.

see https://dimagi-dev.atlassian.net/browse/SAAS-12052

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
none

### QA Plan
none needed

### Safety story
just a simple management command

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by biyeun** [comment]
tested in a limited release. works great ✅

**Review by millerdev — APPROVED** [review]
I think we should be careful to note that these numbers are estimates and if they are used for resource planning for, for example, setting up a data warehouse, they are probably far on the low side. The sizes returned by this script are probably near the minimum amount of space needed to store a raw dump of the data but nothing more. They do not include operational overhead like the size of indexes needed to access the data in a performant manner, etc. In the wrong hands and without proper understanding of what they represent, these numbers could be a basis for very unrealistic expectations.

**Review by gherceg — APPROVED** [review]
Nice!

**Comment by biyeun** [comment]
@millerdev yeah I considered that. I ended up taking this number and then a little more than doubled it. Do you recommend I 3x or 4x my recommendation?

**Comment by ctsims** [comment]
Hey @biyeun 

Who's the client in question here and what's their use case? This seems like a bit of an extreme exception in terms of what we're willing to provide to customers through manual backend intervention, although having the core mechanisms to estimate this does seem useful in some ways (like us being able to gauge the rough or relative cost for projects).

My experience with comprehensive domain exports has also been that even our absolute largest domains are still very much "personal laptop" sized in terms of data, so I would anticipate that we could probably run a couple domains for sizing estimates here and communicate back ranges in the future without getting into the weeds about individual spaces.

**Comment by biyeun** [comment]
@ctsims I want to maintain their privacy on this public PR, but I will ping you in the ticket. :)

**Comment by ctsims** [comment]
> @ctsims I want to maintain their privacy on this public PR, but I will ping you in the ticket. :)

Ah, good call. I should responded there first. Thanks!

**Pull request merged**
