### PR TITLE
Je/server env

### PR DESCRIPTION
**Pull request by emord**
@dimagi/scale-team 

Celery wasn't running due to:

/bin/bash: /home/cchq/www/icds/current/services/supervisor/icds_celery_bash_runner.sh: No such file or directory

### CODE REVIEW

**Comment by emord** [comment]
feels like we might be creating more work for ourselves. maybe we should just change it over to icds_new or something?

**Comment by snopoke** [comment]
What do you mean about changing it over?

**Comment by emord** [comment]
Err. I mean in some places we have icds, and some places it's icds-new/icds_new because of https://github.com/dimagi/commcarehq-ansible/blob/master/ansible/vars/icds-new/icds-new_public.yml#L4

Seems like it might have just been easier to gone with icds-new everywhere, even if it meant re-deploying stack

**Comment by emord** [comment]
deployed to cids-new and verified celery is now running

**Comment by snopoke** [comment]
Oh right, should definitely all be consistant

**Comment by calellowitz** [comment]
I think we can revert this and then just delete the line you are referring to. ENV would still be icds-new/icds_new while ansible and fab deploying but internally and all over the code it would just be icds. Then we would not have to change any of the code, or the UCRs, and it would be easy to switch the new environment to just being called icds when we decommission the old one.
@snopoke @emord Does that idea make sense to you
cc: @dimagi/scale-team

**Pull request merged**
