### PR TITLE
Create helper functions for word wrapping

### PR DESCRIPTION
**Pull request by zandre-eng**
## Product Description

Currently, when a case property description contains a very long word, this will not be properly word-wrapped in the app manager:
wrap_validation_none

The helper functions from this PR ensure that long words are properly wrapped to fit inside the description popup:
Screenshot from 2023-08-25 11-06-03

## Technical Summary

Link to ticket [here](https://dimagi-dev.atlassian.net/browse/SC-3078).

Helper functions have been created to ensure that the length of each word in a case property's description is less than a limit of 43 characters. If a word is longer than this, then it is appropriately wrapped with newlines to stay within the length constraint.

Validation is being done on each word individually since wrapping already occurs between words.

## Feature Flag

`DATA_DICTIONARY`

### Safety story

- Small UI validation change.
- Have done local testing.

### Automated test coverage

N/A

### QA Plan

No QA planned.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
Nice.

I'm not sure about the function name `validateWordLength()` because it sounds like it's going to return a boolean, or throw an error if any words are too long ... but I appreciate that it's not an easy function to find a name for. `breakAtMaxLength()`, `wrapLongWords()`, `insertBreaks()` :shrug:

**Comment by zandre-eng** [comment]
@kaapstorm Yeah it was a weird one to try and find a name for, because it does do validation (in a way) but it also handles the taking action part of any failed validation. But I have updated the name to `insertWordBreaks()` to better reflect what it is doing.

**Comment by snopoke** [comment]
FYI for future reference, changes to Vellum must be done in the Vellum repo: https://github.com/dimagi/Vellum/pull/1093

Then use `./scripts/vellum-to-hq` to update the HQ resources.

**Comment by zandre-eng** [comment]
> FYI for future reference, changes to Vellum must be done in the Vellum repo: https://github.com/dimagi/Vellum/pull/1093
Then use ./scripts/vellum-to-hq to update the HQ resources.
I've ported these changes here: https://github.com/dimagi/Vellum/pull/1093 (+ a unit test and a bug fix)

@snopoke Thanks for highlighting that here, will keep in mind for future Vellum changes :+1:

**Pull request merged**
