### PR TITLE
fix TimingTestSuite to properly manage setUpClass

### PR DESCRIPTION
**Pull request by dannyroberts**
patch class once instead of making a new subclass each time

@snopoke finally bumped into this doing something else and got around to looking at it. Not too hard a fix and I tested that a setUpClass is only called once (per class if it's a superclass of course).

### CODE REVIEW

**Comment by dannyroberts** [comment]
Also I'm pretty sure (though not 100% certain) that this only times the individual test runs, meaning that the setUpClass methods do not get timed at all. That's probably fixable, but I'm guessing isn't going to be a first order factor anyway

**Comment by snopoke** [comment]
Nice, looks good. Waiting for build.

**Comment by dannyroberts** [comment]
FYI individual tests that took longer than 15 seconds:

```
  test_prefix_fees (corehq.apps.smsbillables.tests.test_gateway_fees.TestGatewayFee) 0:03:40.303661
  testForA_B (pact.tests.dot_ordering.dotsOrderingTests) 0:01:04.568423
  testFormA (pact.tests.dot_ordering.dotsOrderingTests) 0:00:32.917544
  testFormB (pact.tests.dot_ordering.dotsOrderingTests) 0:00:32.819054
  testDOTFormatConversion (pact.tests.dot_submission.dotsSubmissionTests) 0:00:32.692044
  testPillboxCheck (pact.tests.dot_submission.dotsSubmissionTests) 0:00:32.463625
  testSignal (pact.tests.dot_submission.dotsSubmissionTests) 0:00:32.354014
  testNoPillboxCheckFirst (pact.tests.dot_submission.dotsSubmissionTests) 0:00:32.021837
  testNoPillboxCheckSecond (pact.tests.dot_submission.dotsSubmissionTests) 0:00:31.989171
  test_domain_and_direction (corehq.apps.smsbillables.tests.test_usage_fees.TestUsageFee) 0:00:18.940081
  test_migration (custom.ilsgateway.tests.test_migration_task.MigrationTaskTest) 0:00:18.747203
  test_ok (corehq.apps.reminders.tests.ReminderCallbackTestCase) 0:00:17.694263
  test_log_no_usage_fee (corehq.apps.smsbillables.tests.test_usage_fees.TestUsageFee) 0:00:17.203475
  test_backend (corehq.apps.sms.tests.BackendTestCase) 0:00:15.594462

  test_community_over_limit (corehq.apps.accounting.tests.test_invoicing.TestUserLineItem) 0:00:33.578286
  test_over_limit (corehq.apps.accounting.tests.test_invoicing.TestUserLineItem) 0:00:32.479054
  test_under_limit (corehq.apps.accounting.tests.test_invoicing.TestUserLineItem) 0:00:29.990949
  test_invoice_credit (corehq.apps.accounting.tests.test_credit_lines.TestCreditLines) 0:00:28.210726
  test_prorate (corehq.apps.accounting.tests.test_invoicing.TestProductLineItem) 0:00:28.080971
  test (corehq.apps.app_manager.tests.test_form_versioning.FormVersioningTest) 0:00:27.077135
  test_combined_credits (corehq.apps.accounting.tests.test_credit_lines.TestCreditLines) 0:00:26.748830
  test_feature_line_item_credits (corehq.apps.accounting.tests.test_credit_lines.TestCreditLines) 0:00:24.807928
  test_product_line_item_credits (corehq.apps.accounting.tests.test_credit_lines.TestCreditLines) 0:00:24.777295
  test_resubscription (corehq.apps.accounting.tests.test_subscription_changes.TestUserRoleSubscriptionChanges) 0:00:23.363514
  testRender (corehq.apps.app_manager.tests.test_success_message.SuccessMessageTest) 0:00:23.020375
  test_cancellation (corehq.apps.accounting.tests.test_subscription_changes.TestUserRoleSubscriptionChanges) 0:00:21.801226
  test_over_limit (corehq.apps.accounting.tests.test_invoicing.TestSmsLineItem) 0:00:19.441992
  test_under_limit (corehq.apps.accounting.tests.test_invoicing.TestSmsLineItem) 0:00:18.908891

test_sharing (corehq.apps.hqcase.tests.test_case_sharing.CaseSharingTest) 0:00:23.587499
```

**Comment by dannyroberts** [comment]
Here's number of tests over 15 seconds per test class:

```
   5 pact.tests.dot_submission.dotsSubmissionTests
   4 corehq.apps.accounting.tests.test_credit_lines.TestCreditLines
   3 pact.tests.dot_ordering.dotsOrderingTests
   3 corehq.apps.accounting.tests.test_invoicing.TestUserLineItem
   2 corehq.apps.smsbillables.tests.test_usage_fees.TestUsageFee
   2 corehq.apps.accounting.tests.test_subscription_changes.TestUserRoleSubscriptionChanges
   2 corehq.apps.accounting.tests.test_invoicing.TestSmsLineItem
   1 custom.ilsgateway.tests.test_migration_task.MigrationTaskTest
   1 corehq.apps.smsbillables.tests.test_gateway_fees.TestGatewayFee
   1 corehq.apps.sms.tests.BackendTestCase
   1 corehq.apps.reminders.tests.ReminderCallbackTestCase
   1 corehq.apps.hqcase.tests.test_case_sharing.CaseSharingTest
   1 corehq.apps.app_manager.tests.test_success_message.SuccessMessageTest
   1 corehq.apps.app_manager.tests.test_form_versioning.FormVersioningTest
   1 corehq.apps.accounting.tests.test_invoicing.TestProductLineItem
```

**Comment by dannyroberts** [comment]
@snopoke looks good to go!

**Comment by snopoke** [comment]
:+1:

**Comment by snopoke** [comment]
Would be great if we can get to a point where we don't have any tests over
15s!

**Comment by dannyroberts** [comment]
I have it in my list of random fun things to do to try and see if I can optimize the worst ones a bit by just moving things into `setUpClass` and `tearDownClass`, but if anyone wants to beat me to the punch, feel free!

**Pull request merged**
