### PR TITLE
Add load_from_form to AdvancedFormActions

### PR DESCRIPTION
**Pull request by benrudolph**
@emord @snopoke AdvancedForms were broken on prod I believe due to this: https://github.com/dimagi/commcare-hq/commit/c89ac7bc (here's the ticket: http://manage.dimagi.com/default.asp?225242). I really have no context on what this does, just pattern matching based on that commit. At the very least this lets you save advanced forms again

cc: @millerdev

### CODE REVIEW

**Comment by emord** [comment]
@benrudolph I updated this PR. this was for cmitfb but we haven't decided how to support that for advanced forms yet

**Comment by millerdev** [comment]
Is it possible to test this?

**Comment by emord** [comment]
@millerdev I'll do it in a different PR. it should be possible, but there's currently no testing around this view

**Comment by benrudolph** [comment]
thank @emord merging

**Pull request merged**
