### PR TITLE
Remove Angular form HQ

### PR DESCRIPTION
**Pull request by AmitPhulera**
## Summary

https://dimagi-dev.atlassian.net/browse/SAAS-12329
We are removing Angular from HQ as it is no longer used.
## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### QA Plan

Not raising a formal QA because there is no evidence of usage of these libraries on HQ. However, they are pushed to staging to observe if we see any related issues.
### Safety story

The changes have been tested on local and the branch is pushed to staging and we would keep it there till Monday to see if someone finds any issues.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
Is there no code that uses angular? If so, that is great! Will wait for @biyeun to review, but looks good to me as long as it does not break anything.

**Comment by snopoke** [comment]
If I recall correctly, one of the reasons this was kept was for ICDS dashboard. Obviously that's not required any longer.

**Review by biyeun — APPROVED** [review]
looks good to me 🎉

**Comment by AmitPhulera** [comment]
It's been on the staging env for a few days and no issues were observed. So I am merging this.

**Pull request merged**
