### PR TITLE
Flip fixtures db

### PR DESCRIPTION
**Pull request by dannyroberts**
opening for tests

### CODE REVIEW

**Comment by czue** [comment]
:+1: 

ready when you are captain!

**Comment by benrudolph** [comment]
:boat: ahoy!

**Comment by snopoke** [comment]
@dannyroberts did you run the migration on zambia as well?

**Comment by czue** [comment]
woohoo! :tada: 

(good question about zambia though)

**Comment by dannyroberts** [comment]
I haven't deployed to zambia. I was hoping to use that to test the robustness of my blocking deploy and documentation. (The running the migration will be super fast on wvz.) @snopoke since you were my original partner in crime, would you mind trying to deploy to zambia then following the instructions of the error message?

**Comment by snopoke** [comment]
Didn't work quite as documented since the server hadn't been deployed since
the initial migration was added so I had to run the commands from the
failed deploy directory (releases/2015-...)

Otherwise all good.

On 19 October 2015 at 06:58, Daniel Roberts <notifications@github.com>
wrote:

> I haven't deployed to zambia. I was hoping to use that to test the
> robustness of my blocking deploy and documentation. (The running the
> migration will be super fast on wvz.) @snopoke
> <https://github.com/snopoke> since you were my original partner in crime,
> would you mind trying to deploy to zambia then following the instructions
> of the error message?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/8610#issuecomment-149098703>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
Thanks @snopoke, great point. I'll update the message. Really trying to lower the barrier to doing more of these if we get any gains from them

**Pull request merged**
