### PR TITLE
Bulk app translation and Markdown

### PR DESCRIPTION
**Pull request by kaapstorm**
Noah did some really cool stuff with Markdown in bulk app translations, allowing one to add new Markdown, and remove old Markdown. The difference in logic between how default (plaintext) values and Markdown values are handled is causing discrepancies -- specifically dropping Markdown when that's not what the user meant, and updating the Markdown value instead of the plaintext value.

I think there are two causes of this: 
- The (cool) regex that identifies Markdown is not accurate enough; I didn't test extensively, but it doesn't recognise a string with a bullet point in it.
- Current code uses two ways of determining the plaintext value node. If the Markdown node appears before the plaintext value node in XML, the wrong node will be chosen.

Using a single way of setting the value node (see 55dde1c in a separate branch) goes a little way, but doesn't resolve bug [FB 183536](http://manage.dimagi.com/default.asp?183536). And even if I extend that regex (and I'm not sure I can), I'm not confident that we won't see a similar problem come up again in the future.

So I made translating Markdown and plaintext values behave the same way. This does resolve the bug, but to do that I had to drop some functionality. My change no longer supports removing Markdown or adding new Markdown using bulk app translation. i.e. Markdown needs to be added/removed in the app builder, and bulk app translation will simply translate the fields that exist, keeping Markdown if it was there before. 

I'm not sure my approach is the right way to go. It simplifies the code but I don't like taking things away -- @dimagi/product should probably weigh in here. 

@orangejenny @NoahCarnahan cc @dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 164 - E501 line too long (135 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 194 - E501 line too long (123 > 115 characters)
* corehq/apps/app_manager/tests/test_bulk_app_translation.py, line 243 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/translations.py, line 579 - E126 continuation line over-indented for hanging indent
* corehq/apps/app_manager/translations.py, line 585 - E126 continuation line over-indented for hanging indent

**Comment by sheelio** [comment]
Is it easier just to have two columns (one with the regular label and one with the mark down label)?

**Comment by emord** [comment]
@kaapstorm I think we explicitly didn't go with this way of doing things because we received a bug that a user couldn't add markdown to a question unless they actually went into the form and edited each question

@sheelio We didn't use two columns because in the form builder we act as if there isn't a special markdown value in the xform. And if they edited the markdown label without the regular label, the regular label would be overwritten by form builder.

**Comment by NoahCarnahan** [comment]
(I've done some app translation work, but I think @orangejenny actually did the markdown part)

**Comment by kaapstorm** [comment]
@emord that's good context to know.

What if we allow users to add Markdown from bulk app translation, but not drop Markdown if we think the new translation looks like plaintext? That would fix this bug, and still keep the functionality that was requested.

**Comment by emord** [comment]
@kaapstorm You mean that if there is already a markdown node, we would replace both default and markdown nodes with the new text even if it doesn't look like markdown? That sounds fine to me. The only difference to the user would be a slightly larger xform than necessary

**Comment by kaapstorm** [comment]
Thanks @emord, I'll go with that.

**Comment by kaapstorm** [comment]
I've kept the bits for adding and vetoing Markdown, and just dropped removing. I've also brought the plaintext and Markdown code for finding the plaintext node and deleting nodes in line.

Easier to review [ignoring whitespace](https://github.com/dimagi/commcare-hq/commit/d72ed59700283c427bdf330acdce1f60e72dc39e?w=0).

**Comment by emord** [comment]
@kaapstorm I'm not sure if this solves this case:

1. a form doesn't have markdown
2. upload a translation file
  * a question has one language that looks like markdown, the other language does not (hindi: "stars", english: "**stars**")
3. the updated form should have markdown nodes for both hindi and english

**Comment by kaapstorm** [comment]
@emord, so either all nodes have Markdown or no nodes have Markdown. That seems consistent. It does make the idea of "vetoing" Markdown problematic. Let's say we start off with no nodes with Markdown, and Hindi == "सितारों" ("stars", according to Google Translate) and English == "\*\*stars\*\*". That suggests for English, Markdown has been vetoed by the user in form builder. Next, we upload a new translation, and Hindi comes in as "\*\*सितारों\*\*". Now do we veto Markdown in Hindi because it was vetoed in English? Or do we add Markdown for English because we're adding Markdown for Hindi? Or do we add Markdown for Hindi, and veto Markdown for English, and end up with Markdown nodes for some labels but not others (current behaviour)?

I think we should go with the principle of least surprise. If one user says that it's not Markdown in English, we should probably assume that it's not Markdown in Hindi either. We could be wrong. We could also be wrong if "\*\*stars\*\*" (English) was vetoed as Markdown before, but then we got a translation like "\*\*stars\*\*:\n\* Betelgeuse\n\* Polaris\n\* Natalie Portman", because we would still be vetoing it even though that's looking **a lot** like Markdown now. 

So I'm going with all-or-nothing, vetoed for one == vetoed for all. Let me know if you think that's a bad idea.

**Comment by emord** [comment]
@kaapstorm that sounds right to me and consistent with how we handle it in vellum.

**Comment by kaapstorm** [comment]
Finally wrapping this up. Easier to review per commit, although the relevant ones at this point are "Aggregate Markdown and Markdown-vetoed nodes" (d40ec79) and "Test aggregating Markdown nodes" (6abbfb1). This should bring behaviour in line with Vellum, with tests. If I'm missing a scenario, or I've misunderstood Vellum behaviour, @emord, please shout.

**Comment by emord** [comment]
Looks good to me.

@orangejenny is this consistent with the behavior that you were originally looking for?

**Comment by orangejenny** [comment]
> So I'm going with all-or-nothing, vetoed for one == vetoed for all.

Yeah, I agree with your decisions: markdown veto covers all languages (as in Vellum), you can't use bulk translations to add or remove a veto (unnecessarily complex), and you can't switch from markdown to plain text via bulk translations (fixes bug, doesn't cause harm).

Looks good.

**Pull request merged**
