### PR TITLE
Add option to fix staging after update master

### PR DESCRIPTION
**Pull request by millerdev**
fyi @emord @orangejenny

### CODE REVIEW

**Comment by emord** [comment]
This still requires a separate `vellum-to-hq staging` right?

**Comment by millerdev** [comment]
No. But it does not update vellum-staging with a new version of vellum. It only makes vellum-staging not conflict with master. So if you do a staging deploy right after running `vellum-to-hq master --fix-staging` the version of vellum on staging would be the same as it was before you ran `vellum-to-hq`.

**Comment by millerdev** [comment]
Maybe I misunderstood your question. A better answer may be "Yes and no." If you want to push a new version of vellum to staging then you need to run `vellum-to-hq staging`

**Comment by emord** [comment]
Yeah. that's exactly what I meant. Thanks

**Pull request merged**
