### PR TITLE
hypelink when available

### PR DESCRIPTION
**Pull request by sravfeyn**
When you search in HQ by doc_id, a corresponding HQ link for that doc will be displayed if available. For e.g. if you search for an application ID, a link to view the app will be displayed.

screen shot 2017-12-04 at 4 27 24 pm

### CODE REVIEW

**Comment by sravfeyn** [comment]
@esoergel

**Comment by esoergel** [comment]
Have you seen that the [raw_doc](https://www.commcarehq.org/hq/admin/raw_doc/?id=83b7983f565c4b62978c86c983b405c8&db_name=) view has something like this already?  The commcare flower icon will use the existing search functionality to find the document, if possible.  I'd also recommend using that tool over `doc_in_es` unless you're specifically interested in the version stored in elasticsearch.

**Comment by sravfeyn** [comment]
Hey yeah, I think it's worth keeping if we are keeping `doc_in_es` around.

**Comment by esoergel** [comment]
Fair enough.  Although I'd still recommend linking instead to [`quick_find`](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqwebapp/views.py#L1081-L1081) (or whatever it uses under the hood), which knows how to handle a very broad range of doc types.

**Review by esoergel — APPROVED** [review]

**Comment by sravfeyn** [comment]
Good point Ethan! Updated

**Comment by esoergel** [comment]
Cool, thanks!

**Pull request merged**
