### PR TITLE
make breadcrumbs smaller

### PR DESCRIPTION
**Pull request by biyeun**
they are grossly gross

screen shot 2015-12-11 at 2 20 05 pm
screen shot 2015-12-11 at 2 19 47 pm
screen shot 2015-12-11 at 2 19 37 pm

### CODE REVIEW

**Comment by biyeun** [comment]
@millerdev

**Comment by czue** [comment]
:+1: @dimagi/product fyi

**Comment by benrudolph** [comment]
:eyes: neat

**Comment by millerdev** [comment]
@amsagoff @ctsims this isn't quite the outcome I thought we'd agreed to. Was it subsequently decided that the breadcrumbs are too important to remove?

**Comment by ctsims** [comment]
Agreed that we discussed removing them entirely (including possibly making
them a pop-down). Maybe this is an independent change?

**Comment by amsagoff** [comment]
Independent change - I talked to B about removing for form builder and we
got distracted by how huge they are everywhere. Still planning on removing
for form builder (and dealing with the footer somehow).

**Comment by ctsims** [comment]
Cool, agree that it's a good change either way. Looks great!

-Clayton

**Comment by millerdev** [comment]
:+1:

**Pull request merged**
