### PR TITLE
Flag priority improvement areas 

### PR DESCRIPTION
**Pull request by ctsims**
## Product Description
No code changes

## Technical Summary
Context: https://github.com/dimagi/commcare-hq/issues/31930

Adds comments to flag the 10 (ok, 12) "worst" high traffic methods in the codebase for improvement

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by akashkj** [comment]
@ctsims Where can we see the Radon static analysis reports?

**Comment by ctsims** [comment]
@akashkj You can get them from the command line 

```
$ radon cc . --min=E --exclude=node_modules/*,staticfiles/*
```

Not sure where the best place for the documentation on that process is. We run the static analysis with every PR, but it doesn't output individual files, just counts

**Review by esoergel — APPROVED** [review]

**Comment by esoergel** [comment]
@akashkj this is the exact command that is run to generate these metrics:
https://github.com/dimagi/commcare-hq/blob/70eafcfb4a0021e164bade66cf6498d4b7330400/corehq/apps/hqadmin/management/commands/static_analysis.py#L106-L106

**Comment by akashkj** [comment]
Thank you @ctsims & @esoergel, this is helpful info.

**Pull request merged**
