### PR TITLE
add flag for skipping fixtures on restore

### PR DESCRIPTION
**Pull request by calellowitz**
##### SUMMARY

This adds a flag to restores allowing the client to specify if they want to not include fixtures. If a fixture is not included in the restore the version on the phone is kept unmodified. This is mainly for projects with large fixtures that want to avoid the cost of parsing them on each sync, and only gets set during automated syncs that happen after form submission in formplayer (a feature currently only in use by USH projects and based on an app property).

### CODE REVIEW

**Comment by ctsims** [comment]
@calellowitz Quick design question - Did you think through the potential approach of excluding **lookup tables** but not all fixtures in the design? 

I think the system more or less does actually do a decent job of only including other types of fixtures when they have changed (locations in particular), or are much smaller (like groups), so it could prevent certain types of misaligned fixture problems for those fixtures to be included even if Lookup Table fixtures are not. 

I'm not sure if that's particularly easy, however, and am not sure if there are real edge cases where those fixtures would definitely need to be included in practice (groups is the only one I can create a narrative for in my head).

**Review by orangejenny — APPROVED** [review]
Code itself looks line, approving pending Clayton's question being resolved.

**Comment by calellowitz** [comment]
> Did you think through the potential approach of excluding lookup tables but not all fixtures in the design?

I looked into this briefly, based on the way the fixture generators are created (a global singleton populated from a list in the settings file), it seemed a lot trickier to do it at that level, and I also couldn't convince myself how sending cases but not those other fixtures would break things.
That being said, I don't actually think it would be that hard to filter just that one. We would just need to switch the fixture generators from a static to a dynamic list (and perhaps no longer a singleton)

**Comment by ctsims** [comment]
@calellowitz Got it. My intuition is that if it's an order of magnitude more difficult it's not worth bigger changes to support.

The only other thing I was going to suggest was that the server not respect a request to suppress fixtures on a "clean" (IE: Non-incremental) restore, because on all platforms that will brick the sandbox if there's dependent data (locations, groups, etc) in the fixtures. I don't think that should be a big risk, because the platforms generally strip headers if they do a clean sync, but it would be helpful for the server to also reinforce that.

**Pull request merged**
