### PR TITLE
change path for inspector_names

### PR DESCRIPTION
**Pull request by lwyszomi**
Hi,

next change for inspector_names path in datasource.

Regards,
Łukasz

### CODE REVIEW

**Comment by lwyszomi** [comment]
hold of merge

**Comment by lwyszomi** [comment]
ready for review and merge

**Comment by lwyszomi** [comment]
Hi @nickpell 

I added new changes to the VectorLink report:
 - I changed the path in the inspector_name indicator
 - I extended the comments function to give a possibility to get a comment by the whole path starting on the root. 

Please let me know if you have any questions.

Regards,
Łukasz

**Review by nickpell — APPROVED** [review]

**Comment by lwyszomi** [comment]
@nickpell could you kick off the build, I think to failure is not related.

**Pull request merged**
