### PR TITLE
Analytics: event for submitting form in app preview

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?259520

@benrudolph

### CODE REVIEW

**Review by benrudolph — COMMENTED** [review]
this won't distinguish between web apps, edit forms, and app preview. so `[app-preview]` prefix is kind of misleading

**Comment by orangejenny** [comment]
@benrudolph Thanks, didn't know that, and I do want this to be only for live preview. Is putting the event in preview_app.js the reasonable thing to do, then?

**Comment by benrudolph** [comment]
ok hmm i think what you can do is put the event here: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js#L143
and then use the `user.environment` to figure out if it is web apps or app preview. see possible values here: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/cloudcare/static/cloudcare/js/formplayer/constants.js

form entry code should have no knowledge of where it lives, but there is one variable that is passed in to determine if it's in phone mode. though still think it makes sense to do it in the callback

**Comment by orangejenny** [comment]
@benrudolph Cool, thanks. Updated.

**Review by benrudolph — APPROVED** [review]

**Pull request merged**
