### PR TITLE
Fix broken script path

### PR DESCRIPTION
**Pull request by biyeun**
fyi @millerdev 

@orangejenny / @benrudolph 
cc @czue

### CODE REVIEW

**Comment by czue** [comment]
:+1:  - assume no test coverage and if so feel free to merge. did this break something?

**Comment by biyeun** [comment]
@czue, apparently it was breaking a test. saw this in an interim PR from @millerdev but thought it was unrelated. closing and pulling this into the broken branch

**Comment by millerdev** [comment]
👍 it broke the staging deploy.

@biyeun did you intend to close this?

**Comment by biyeun** [comment]
@millerdev brought it into the `b3-groups-pt2` branch

**Pull request closed without merging**
