### PR TITLE
Revert "ejs/location location 2"

### PR DESCRIPTION
**Pull request by calellowitz**
@emord
FYI: @jmtroth0 
this broke the icds tableau dashboard. Specifically changes to `location_drilldown.async.js` caused a js error on that page.

### CODE REVIEW

**Comment by calellowitz** [comment]
@jmtroth0 
For what it's worth, the rest of the PR beyond that one file can likely be remerged immediately, and we are hoping to kill the tableau dashboard soon. Your call on how much time you want to sink into finding and fixing that bug

**Comment by calellowitz** [comment]
in case it wasn't clear, this reverts https://github.com/dimagi/commcare-hq/pull/19628

**Comment by snopoke** [comment]
test failure seems unrelated:
```
 1 failing
  1) Progress Report Directive tests initial state:
     AssertionError: expected true to equal false
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:2178
      at http://localhost:8000/static/icds_reports/js/spec/progress-report.directive.spec.js:36
```

**Comment by snopoke** [comment]
Also this is affecting prod so going to merge and deploy: https://manage.dimagi.com/default.asp?271529

**Comment by jmtroth0** [comment]
Ah, thanks for taking care of this @snopoke and @calellowitz. I guess there was something I didn't test @millerdev

**Pull request merged**
