### PR TITLE
fix migration when DefaultProductPlans already exist

### PR DESCRIPTION
**Pull request by nickpell**
@calellowitz

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Comment by nickpell** [comment]
self-merging now so we can deploy swiss.  Ran accounting tests locally.

**Comment by benrudolph** [comment]
is there any way to get around this by typing some command in the shell?

**Comment by nickpell** [comment]
this should work too:

```
DefaultProductPlan.objects.filter(product_type__in=[
    'CommTrack',
    'CommConnect'
]).delete()
```

**Comment by benrudolph** [comment]
thanks!

**Pull request merged**
