### PR TITLE
Force every property except locale

### PR DESCRIPTION
**Pull request by kkrampa**
@dannyroberts @snopoke 
http://manage.dimagi.com/default.asp?144634

### CODE REVIEW

**Comment by snopoke** [comment]
Looks good to me.

Seems like we could get rid of a bunch of those settings completely though. @orangejenny perhaps something for the app builder backlog?

**Comment by dannyroberts** [comment]
@ctsims can you just double check that switching to this behavior doesn't have any undesired consequences?

**Comment by ctsims** [comment]
In theory this could cause minor problems with weird edge cases (IE: I go
change a setting to 'fix' something on someone's phone), but my guess is
that we should be starting from the other direction (IE: start with the
assumption everything is forced, and work backwards), more or less my guess
would be that the properties with 'force' set is basically "the set of
properties that people actually bother using".

-Clayton

**Comment by orangejenny** [comment]
@snopoke yeah, that makes sense, will add to backlog

**Comment by dannyroberts** [comment]
@kkrampa looks like this isn't mergeable anymore

**Comment by dannyroberts** [comment]
bump

**Comment by kkrampa** [comment]
Updated

**Comment by dannyroberts** [comment]
thanks

**Pull request merged**
