### PR TITLE
Mobile select filter tweaks

### PR DESCRIPTION
**Pull request by dannyroberts**
Responding to @czue's comments on https://github.com/dimagi/commcare-hq/pull/9336

### CODE REVIEW

**Comment by dannyroberts** [comment]
Might be good for @nickpell or @NoahCarnahan cc: @proteusvacuum @orangejenny

**Comment by nickpell** [comment]
looks good to me

**Comment by dannyroberts** [comment]
Thanks!

**Comment by czue** [comment]
:+1: thanks for follow up!

**Pull request merged**
