### PR TITLE
re-work suite file for data registry search modules

### PR DESCRIPTION
**Pull request by snopoke**
## Technical Summary
This makes fundamental changes to the suite file when case search is configured to search from a data registry.

Normal case search:
1. form entry contains a datum which references the module details
2. module details contains an action which kicks off a stack operation to show case search (remote-request)
3. case search is complete (case selected, claim performed, sync complete) the stack rewinds back to the details but with the needed datum selected
  - since the case was claimed and a sync was performed the case is now in the user's casedb
4. navigation continues to the form

This workflow doesn't work for data registry search because in step 3 we don't perform the claim and sync which means that the case is not going to be in the user's casedb. This makes it impossible for navigation to continue.

Instead of having the search be launched from an action in the details what we will do is have the search performed directly as part of the form entry. This search populates a 'remote' instance which is then used by the form's datum to show the case details. 

More details in the spec and in the tests.

Spec: https://docs.google.com/document/d/1FCSxVBoBG8LnmogMwei1nb6eC74eUhs7HWuJmBg6i3k/edit#heading=h.oij9d37sohxx

## Feature Flag
DATA_REGISTRY

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
Added

### QA Plan
I'm not planning to put this through QA prior to merging. This is still being tested by USH so it will get QA'd then.

### Safety story
The changes in this PR do current work on formplayer (except for accessing the remote instance in the form). This should not impact any app builds that are not using 'registry case search'. Given the comprehensive test suite I am confident that this won't impact anything outside of the FF.

There are still further changes that need to be made to get this working nicely with other app features like "form linking", "search again".

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by shubham1g5** [comment]
Thanks @snopoke Looks good to me. Also tested this with https://github.com/dimagi/formplayer/pull/1006 and I am able to get a working prototype that loads up details from a cross domain case in the form. Although any form saves fails with the [error](https://github.com/dimagi/commcare-core/blob/master/src/main/java/org/commcare/xml/CaseXmlParser.java#L248) because the case is not present in the local DB. Probably we would want to remove any case updates on the remote case from the form as well and have a different model than `case` for eg. `remote-case` where we save these updates and process them later on HQ.

**Comment by snopoke** [comment]
> Thanks @snopoke Looks good to me. Also tested this with [dimagi/formplayer#1006](https://github.com/dimagi/formplayer/pull/1006) and I am able to get a working prototype that loads up details from a cross domain case in the form. Although any form saves fails with the [error](https://github.com/dimagi/commcare-core/blob/master/src/main/java/org/commcare/xml/CaseXmlParser.java#L248) because the case is not present in the local DB. Probably we would want to remove any case updates on the remote case from the form as well and have a different model than `case` for eg. `remote-case` where we save these updates and process them later on HQ.

The way we're going to accomplish this is to create new cases with save-to-case and then process them asynchronously on HQ to update the case in the remote domain. Details of that here: https://github.com/dimagi/commcare-hq/pull/30452

**Review by orangejenny — APPROVED** [review]

**Comment by shubham1g5** [comment]
@snopoke That makes sense, though does this mean mobile need to ignore these case updates locally and not fail on form save when it doesn't find a case locally in DB for cases with type - registry_case_update) ?

**Comment by snopoke** [comment]
> @snopoke That makes sense, though does this mean mobile need to ignore these case updates locally and not fail on form save when it doesn't find a case locally in DB for cases with type - `registry_case_update` ?

There should be no changes required for this since the form will be creating a new case which will belong to the current user's domain.

**Comment by shubham1g5** [comment]
I see, I am trying to set this up on [staging](https://staging.commcarehq.org/a/florida-covid/apps/view/668ea0db6b99e84185e52e628b71b973/form/32d05b073dd7447185f1db5500a6082c/source/#form/patient_name), though I am able to load case details in the form, the form save is failing [here](https://sentry.io/organizations/dimagi/issues/2565664263/?environment=staging&query=is%3Aunresolved) with a bad case id message. So I am basically wondering if I am setting this up incorrectly or if there is any pending work that we need to do on this front.

**Comment by snopoke** [comment]
@shubham1g5 thanks for testing this out. I'll put this PR on staging which should fix the case update issues: https://github.com/dimagi/commcare-hq/pull/30519

**Pull request merged**
