### PR TITLE
Icds cas reach change awcs launched and opened

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @calellowitz @Rohit25negi,
I have removed in the program summary page in ICDS-CAS Reach denominator for AWCs Launched and changed denominator for Number of AWCs Open yesterday from a number of AWCs to number of AWCs launched.
Need QA: Yes
Environment: n/a
Locally Tested: Yes
Regards, Dawid

### CODE REVIEW

**Comment by Rohit25negi** [comment]
Adding the label do not merge as ticket says ask before deploying

**Review by Rohit25negi — COMMENTED** [review]
These changes looks good. Only concern I have is are these the only instances of these indicators used. If these indicators are used elsewhere also. Should not all those changes be rolling out at same time? Else it will be inconsistency atleast for denominator of "awc open yesteryda"

**Comment by Rohit25negi** [comment]
And There has to be update in the documentation where ever these indicators are updated

**Review by Rohit25negi — CHANGES_REQUESTED** [review]
Code looks good. Left two comments.

**Review by Rohit25negi — APPROVED** [review]

**Review by Rohit25negi — APPROVED** [review]
Checked with the GS Team, Apart from Manual there is no inconsistency.
Heena: Where else do you expect the inconsistency?
Sarvesh: I think that's it, don't expect other inconsistencies.

**Comment by Rohit25negi** [comment]
@dmydlo can you put these changes into Feature flag?

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
