### PR TITLE
[preview] In-form navigation like mobile

### PR DESCRIPTION
**Pull request by biyeun**
@benrudolph 

cc @dimagi/product 

webforms-stylin

pls merge: https://github.com/dimagi/touchforms/pull/252

### CODE REVIEW

**Comment by benrudolph** [comment]
this is sick! does this work ok when questions get added / removed via form logic?

**Comment by biyeun** [comment]
@benrudolph lol I don't I didn't try that on a more advanced form...I think you'd need to recompute the total/progress

**Comment by snopoke** [comment]
Very nice! branch has conflicts

**Comment by amsagoff** [comment]
:sunglasses:

**Comment by benrudolph** [comment]
nice nice, do you think it makes sense to rebase this to one commit in case we want to revert when we get actual screen to screen nav?

**Comment by czue** [comment]
> nice nice, do you think it makes sense to rebase this to one commit in case we want to revert when we get actual screen to screen nav?

there's also the "squash and merge" button on github.

**Comment by benrudolph** [comment]
discussed offline, think we're gonna just go for it and refactor as necessary since we should be able to reuse a lot of the code

**Pull request merged**
