### PR TITLE
Move changes from QA to live Enikshay domain

### PR DESCRIPTION
**Pull request by kkrampa**
@NoahCarnahan @proteusvacuum

### CODE REVIEW

**Comment by kkrampa** [comment]
We need to rebuild three data sources: test, episode and voucher.

**Comment by emord** [comment]
@NoahCarnahan these rebuilds are probably going to fail if they're put in the celery queue. You'll probably need to run the async rebuild that you had to for episode cases before

**Comment by NoahCarnahan** [comment]
@emord 
Ah, interesting. Why do you think they'll fail in the celery queue? There is a task that automatically rebuilds tables when the configuration has changed, right? Do we need to do something to disable that?

**Comment by emord** [comment]
@NoahCarnahan I think they'll start, but it will take a really long time for them to complete because of hte # of cases in enikshay. that will result in only a partial rebuild. similar to what you saw before

**Pull request merged**
