### PR TITLE
Docker compose for devs with ARM64 chip

### PR DESCRIPTION
**Pull request by AddisonDunn**
## Product Description

No user-facing changes. It will only affect developers running services in docker and hopefully only developers with an ARM64 chip.

## Technical Summary

Developers with computers that have ARM64 chips cannot run the Postgres image used by the default `hq-compose.yml` file. This allows ARM64 devs to compose docker without holding a separate copy of `hq-compose.yml` on their computers, which is both a hassle and possible operational issue. See [this Slack thread](https://dimagi.slack.com/archives/C0WLJ3HRP/p1636663809146500) for the conversation that triggered this change.

`hq-compose-arm64.yml` is an exact copy of the `hq-compose.yml` file except that it includes a change to line 60, changing:

`image: dimagi/docker-postgresql`
to 
`image: arm64v8/postgres`

`arm64v8/postgres` is the name of an image built by the Postgres team specifically for ARM64 architecture. Without this line, an architecture-related error often occurs on Mac M1 computers.

The [second commit](https://github.com/dimagi/commcare-hq/commit/45e9c6b467039c125b768ce17ad397872f0b39d9) was created by Joel to automatically change which `hq-compose` file is used to compose Docker services based on a computer's architecture when we run `./scripts/docker up.` If one has an ARM64 architecture computer chip, the `hq-compose-arm64.yml` file will be used to compose Docker services.

I have verified that this works cleanly on my Mac M1 with an ARM64 chip and that the ARM64 Postgres image is used.

The conversation is open if anyone has suggestions or thoughts.

### Safety story

This should only affect developers

### Automated test coverage

No tests.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by calellowitz** [comment]
I don't know much about our internal postgres container differs from the one used here, but it would be good to note differences (either in the docker README or the dev setup one). Since this is now invisible (which is great), it will be confusing for people if it works differently than advertised.

**Review by joxl — COMMENTED** [review]
> `hq-compose-arm64.yml` is an exact copy of the `hq-compose.yml` file except that it includes a change to line 60

This is great information, thanks for clarifying this.  With that in mind I think a few more tweaks could eliminate all compose file content duplication.  Perhaps we could make multiple "arch" compose files (e.g. `hq-compose-x86.yml` and `hq-compose-arm64.yml`) where each only defines the `postgres.image` attribute.  Then `scripts/docker` could determine which "arch" file to use (and export an env var.), and the `hq-compose.yml` file could use that to extend arch-specific blocks.

**Comment by AddisonDunn** [comment]
@joxl Thanks, I added your code that removes the need to have an entirely different `hq-compose.yml`.

@calellowitz I've added some clarification to DEV_SETUP that will also remove some soon-to-be outdated comments on the manual fix.

**Review by joxl — APPROVED** [review]

**Comment by joxl** [comment]
Merge can wait for @calellowitz and/or @millerdev reviews since my review is biased by my own contributions.

**Pull request merged**
