### PR TITLE
Removed XFormServerModifiedParams

### PR DESCRIPTION
**Pull request by orangejenny**
@snopoke @sravfeyn This looks like it exists to support [this query](https://github.com/dimagi/commcare-export/blob/3b2294ceb3f6dc6d0b14615a740189fc2e01841d/commcare_export/commcare_minilinq.py#L46-L72). Would it be safe to merge this after https://github.com/dimagi/commcare-export/pull/159/ or do we need to keep it for the sake of backwards compatibility?

### CODE REVIEW

**Comment by sravfeyn** [comment]
Hey @orangejenny Yes, I remember that's mostly from DTE. But you could do a quick grep on nginx logs to be 100%sure.

**Comment by snopoke** [comment]
I expect we'd need to keep it for some time since it will take a while for all clients to be upgraded

**Comment by snopoke** [comment]
When we do remove it we should add an error message as well so that DET users know what to do to fix it.

**Comment by orangejenny** [comment]
@sravfeyn @snopoke Sounds good, thanks. I'll leave this open and revisit in a while.

**Comment by snopoke** [comment]
A quick data pull of our logs shows this query is still being used by a number of domains. I see commcare-export versions 1.8.1 (latest), 1.4.0, 1.2.1. I think removing this will require forcing upgrades and re-syncing of data which may not be tractable for some large domains.

I think we could come up with a way to seamlessly migrate to the new pagination style but we'll still need to force an upgrade of commcare-export. I've made an issue for that here: https://github.com/dimagi/commcare-export/issues/220

**Comment by orangejenny** [comment]
@snopoke Realistically I'm unlikely to take this forward. Would it make sense to go in USH's tech debt backlog?

**Comment by snopoke** [comment]
> @snopoke Realistically I'm unlikely to take this forward. Would it make sense to go in USH's tech debt backlog?

I think we can just punt it. I've created the issue in the commcare-export repo so it won't get lost.

**Pull request closed without merging**
