### PR TITLE
[ICDS Dashboard]Removed supervisor and doc from retrieving while fetching results

### PR DESCRIPTION
**Pull request by challabeehyv**
##### SUMMARY
Removed supervisor and doc from retrieving while fetching results

### CODE REVIEW

**Comment by Rohit25negi** [comment]
@challabeehyv can you test locally and esure its working

**Comment by challabeehyv** [comment]
> @challabeehyv can you test locally and esure its working

actually i a have a problem accessing awc location locally due to the worker node not attched to master citus. That is where the bug came. But now it should work fine

**Comment by Rohit25negi** [comment]
> > @challabeehyv can you test locally and esure its working
> 
> actually i a have a problem accessing awc location locally due to the worker node not attched to master citus. That is where the bug came. But now it should work fine

Cool. could you please test now? @challabeehyv

**Comment by challabeehyv** [comment]
> > > @challabeehyv can you test locally and esure its working
> > 
> > 
> > actually i a have a problem accessing awc location locally due to the worker node not attched to master citus. That is where the bug came. But now it should work fine
> 
> Cool. could you please test now? @challabeehyv

checked

**Review by Rohit25negi — APPROVED** [review]
Good to merge once the build passes

**Pull request merged**
