### PR TITLE
don't crash on mothers with edd's way in the future

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?152091

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
hold off on merge a sec, will write a quick test

**Comment by czue** [comment]
g2g

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by esoergel** [comment]
Looks good, will merge after tests.

**Pull request merged**
