### PR TITLE
Kill referrals in case processing, restore, and exports

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?152886

Referral submissions in the last 3 months (one was me testing, other is a test form):

image

@dannyroberts feels like time?

### CODE REVIEW

**Comment by czue** [comment]
going to throw this on staging for a bit. also there's still tons of referral stuff in app builder but i didn't want to touch that.

**Comment by czue** [comment]
@amsagoff fyi - no one is using referrals and this officially drops support for them.

**Comment by czue** [comment]
woot :white_check_mark:

**Comment by benrudolph** [comment]
+28 −642 :+1:

**Comment by dannyroberts** [comment]
This is so great!

**Comment by dannyroberts** [comment]
I'm signed off once you're happy with QA. I'd also be excited to remove v1 support from app builder in the near future. (This would mean no one can edit their v1 apps anymore, so we should see when the last edit to a v1 app was made first.)

**Comment by czue** [comment]
@dannyroberts two weeks on staging and so far so good. how long do you think we should wait on this?

**Comment by dannyroberts** [comment]
Do we want to test what *does* happen if someone submits with referrals? Probably no since we're pretty sure that doesn't happen anymore. Other than that, I'd be comfortable deploying this if we haven't seen any problems from it on staging.

**Comment by czue** [comment]
@dannyroberts https://staging.commcarehq.org/couchlog/view/82532d9abaa5bd17d16c426b8f9ee19c/

I'm comfortable with this if you are. :white_check_mark:

**Pull request merged**
