### PR TITLE
Remove slugs from raw_product_states

### PR DESCRIPTION
**Pull request by proteusvacuum**
:snail:

http://manage.dimagi.com/default.asp?188057

@snopoke 
cc @millerdev

### CODE REVIEW

**Comment by czue** [comment]
nice thanks. :+1: when tests pass

**Comment by snopoke** [comment]
:snail: :boom: :speedboat: :racehorse:

**Comment by proteusvacuum** [comment]
@snopoke I'm gonna need to start asking you for translations. This is what I understood:
"Attached a snail to a firework, it exploded, so I had to escape by boat. On the other side of the river, jumped on my horse to try and outrun the bandits."

**Comment by snopoke** [comment]
I think I like this better. I'll just keep posting random emoji's and you
can come up with a story. Maybe one day we'll collected them all into a
coffee table book / blog post 😁

On 27 November 2015 at 09:20, Farid Rener <notifications@github.com> wrote:

> @snopoke <https://github.com/snopoke> I'm gonna need to start asking you
> for translations. This is what I understood:
> "Attached a snail to a firework, it exploded, so I had to escape by boat.
> On the other side of the river, jumped on my horse to try and outrun the
> bandits."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/9301#issuecomment-160057791>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by proteusvacuum** [comment]
:white_check_mark:

**Pull request merged**
