### PR TITLE
Fetch new token only when expired

### PR DESCRIPTION
**Pull request by mkangia**
## Product Description

This PR updates the implementation for auth manager for OAuth 2.0 client credentials grant type, to fetch a new token only if the token is expired or is expiring in next 10 seconds.
10 seconds buffer was chosen to cater for any delays which should suffice and is minor compared to the default life cycle of 1 day for a token.
This change is only effective for repeaters for projects using CommCare Analytics which is a handful of domains. OAuth 2.0 client credentials is primarily used for repeaters used for CommCare Analytics.

## Technical Summary

https://dimagi.atlassian.net/browse/SC-3908

The approach here is inspired from how tokens are refreshed by the library as seen [here](https://github.com/oauthlib/oauthlib/blob/v3.1.0/oauthlib/oauth2/rfc6749/clients/base.py#L197)
In order to not break any existing workflows the change is only being done for CommCare Analytics which sits behind a feature flag though it seems reasonable to do it for all oauth setups.
Why so?
Client credentials grant isn't expected to have a refresh token as per the [specification of OAuth protocol](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3), so based on that, currently HQ will always request for a new token since [this condition](https://github.com/dimagi/commcare-hq/blob/7d461505b0695e457b73bca737b9a8fd3f933536/corehq/motech/auth.py#L222) will always be true even if there is a token saved in last_token since it will never have "refresh_token".

That condition was added as a part of [this PR](https://github.com/dimagi/commcare-hq/pull/33619) but we have lost the stacktrace of the error it was addressing so its not clear now why exactly that condition was added and if it is still a concern.

I can't decide here if this change should be released generally so I am keeping it behind the feature flag and will let the team decide if it should be released for all as a follow up PR because I'd like to get this rolled out asap to unblock other issues being faced with HQ and Analytics integration via repeaters.

## Feature Flag

`SUPERSET_ANALYTICS`

### Safety story

Tested on staging that
1. When not expired, same token was used successfully
2. When expired, new token was requested and used successfully

### Automated test coverage

Unfortunately the tests are missing for all auth managers here. I will try to add tests at least for the change though the change is behind a feature flag and was well tested.

### QA Plan

No QA planned

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by calellowitz** [comment]
> This change is only effective for authorization with CommCare Analytics.

This isn't quite true, right? It affects _all_ repeaters in any domain using CommCare Anlalytics, even the non analytics repeaters?

**Comment by mkangia** [comment]
> This isn't quite true, right? It affects all repeaters in any domain using CommCare Anlalytics, even the non analytics repeaters?

Sorry yes, you are right. These are handful of domains. I will update the description.

**Review by calellowitz — APPROVED** [review]

**Review by snopoke — COMMENTED** [review]
~~Why is this only applied to the toggle? Is `expires_at` not respected by any other systems?~~

Explained in the PR description.

I do think this would be a good change to rollout more broadly but would require a fallback (hopefully temporarily) so as to not break existing integrations.

**Comment by mkangia** [comment]
> would require a fallback (hopefully temporarily)

Hey @snopoke 

Just checking on what this could be? A feature flag again to revert to old system?

**Comment by snopoke** [comment]
> > would require a fallback (hopefully temporarily)
> 
> Just checking on what this could be? A feature flag again to revert to old system?

I was thinking of a reqeust to test the auth or else a fallback to fetch a new token if the request fails (and we were using an existing token)

**Comment by mkangia** [comment]
Okay :+1:

**Review by snopoke — APPROVED** [review]

**Pull request merged**
