### PR TITLE
Use web apps as different user

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @biyeun  (and fyi @czue in case you're interested), this implements the frontend restore as interface. allows people to set who they are logged in with and persists across sessions. this won't actually work until the backend portion is merged: https://github.com/dimagi/formplayer/pull/140. biyeun i know the banner is horrible, maybe we can talk about it tomorrow. best read commit by commit

still todo:
- [x]  Styling for app preview
- [x]  Javascript Tests
- [x]  Pass restoreAs value to form entry
- [x]  Throw behind a toggle
- [x]  Style icon for log in as and figure out copy
- [x] Documentation

Easily select your user and view information about
select_user

Easily clear your login user
clear login

Nice little user page that is restful and gives you the ability to copy the link to other people (not sure if that's ever going to be useful...)
filter_user

Hooray i've wanted to have this for so long! The dream is real! 😴 

cc: @nickpell

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 19 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js, line 200 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js, line 219 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/list/list_view.js, line 35 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/session_nav.js, line 46 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/util/util.js, line 30 - 'DOMPurify' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 9 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 27 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 31 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - '$' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 9 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - '$' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 30 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 4 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 21 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 31 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 32 - 'Util' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 102 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 108 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 116 - Unexpected console statement. (no-console)

**Comment by dimagimon** [comment]
There are 21 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js, line 201 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js, line 220 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/list/list_view.js, line 35 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/session_nav.js, line 46 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/apps/util/util.js, line 30 - 'DOMPurify' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 12 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 32 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/collections/user.js, line 36 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 5 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 7 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - '$' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 9 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - '$' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 54 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 4 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 27 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 44 - 'Util' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 121 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 5 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 7 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 1 - 'Util' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by dimagimon** [comment]
There are 8 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 5 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/spec/user_collection_spec.js, line 7 - Missing semicolon. (semi)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 1 - 'Util' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by benrudolph** [comment]
leaving the rest of dimagimon errors

**Comment by benrudolph** [comment]
icons are sick purple now:
screen shot 2016-10-25 at 4 18 42 pm

**Comment by czue** [comment]
this is amazing. :heart_eyes: 

what is the security model we have here? it didn't look like there was much in place besides the toggle right now. does that imply there is a vulnerability whereby any mobile worker could currently (with some JS/API hacking) gain access to any other mobile worker's data?

**Comment by wpride** [comment]
http://i.imgur.com/7drHiqr.gif

**Comment by benrudolph** [comment]
the security aspect is from the restore itself. we don't allow users to restore as other users unless they are web users and have the edit permissions flag. so even if they fiddle with the javascript, they'll just get errors

**Comment by czue** [comment]
ah nice. for TB we will need to extend this to support certain mobile users but we can ignore that for now.

**Comment by benrudolph** [comment]
ah interesting, i was going to scope it for just web users who have edit permissions. will have to think harder about who this appears for

**Comment by czue** [comment]
another question - after doing this is there any record that the form was submitted by one user on behalf of somebody else? This will also be useful/required eventually

**Comment by benrudolph** [comment]
i _think_ the auth context will be the user who submitted the form (not the restore as user). i haven't actually tried any of this end to end

**Comment by benrudolph** [comment]
though i doubt it'll be hard to just add another parameter to the submission and have the submit code save it somewhere

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by benrudolph** [comment]
👍 this is g2g

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by benrudolph** [comment]
@wpride https://github.com/dimagi/commcare-hq/pull/13711/commits/0f524a48a6b309ee52a32939e79dee765bc786ec

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/user_controller.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/utils.js, line 3 - 'Marionette' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 43 - 'e' is defined but never used (no-unused-vars)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 127 - Unexpected console statement. (no-console)
* corehq/apps/cloudcare/static/cloudcare/js/formplayer/users/views.js, line 135 - Unexpected console statement. (no-console)

**Comment by benrudolph** [comment]
🚀

**Pull request merged**
