### PR TITLE
Add editable codes in organization levels

### PR DESCRIPTION
**Pull request by proteusvacuum**
screen shot 2015-11-18 at 3 54 07 pm
http://manage.dimagi.com/default.asp?186409#1046824

Not sure if the "advanced mode" toggle (top right of table) is the best way. I could also potentially put a big red warning message if this is toggled that changing codes could break the app?
@esoergel @sheelio 

Code buddy: @millerdev

### CODE REVIEW

**Comment by czue** [comment]
looks great to me

**Comment by czue** [comment]
(will let @sheelio sign off on UI)

**Comment by sheelio** [comment]
Looks great - I assume that clicking "Advanced Mode" will show the organization level type code?

**Comment by proteusvacuum** [comment]
@sheelio, yes. Clicking advanced mode shows that extra column.

**Comment by millerdev** [comment]
:+1:

**Comment by snopoke** [comment]
Wording in the description could use a tweak. Mixed use of location vs orgaization

**Comment by proteusvacuum** [comment]
@snopoke, agreed (outside this PR though) -- 
@dimagi/product do you have some text suggestions for the description of this page? Otherwise I'll make something up.

**Comment by esoergel** [comment]
:+1:

**Pull request merged**
