### PR TITLE
skip unknown trans strings

### PR DESCRIPTION
**Pull request by sravfeyn**
@nickpell 
http://manage.dimagi.com/default.asp?222302

### CODE REVIEW

**Comment by czue** [comment]
build fail looks real:
```
======================================================================
FAIL: test_translation (corehq.apps.app_manager.tests.test_bulk_ui_translation.BulkUiTranslation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/apps/app_manager/tests/test_bulk_ui_translation.py", line 68, in test_translation
    u'unknown_string': u'Dong',
AssertionError: {u'fra': {u'entity.sort.title': u'wubble', u'home.start.demo': u'Dong', u'activi [truncated]... != {u'fra': {u'entity.sort.title': u'wubble', u'unknown_string': u'Dong', u'home.st [truncated]...
  {u'en': {u'date.tomorrow': u'wobble',
           u'entity.sort.title': u'wabble',
-          u'home.start.demo': u'Ding'},
?                                     -
+          u'home.start.demo': u'Ding',
+          u'unknown_string': u'Ding'},
   u'fra': {u'activity.locationcapture.Longitude': u'wibble',
            u'entity.sort.title': u'wubble',
-           u'home.start.demo': u'Dong'}}
?                                      ^^
+           u'home.start.demo': u'Dong',
?                                      ^
+           u'unknown_string': u'Dong'}}
----------------------------------------------------------------------
Ran 334 tests in 11.172s
FAILED (failures=1, expected failures=1)
```

**Comment by sravfeyn** [comment]
Fixed @nickpell or @czue

**Comment by czue** [comment]
@sravfeyn it looks like this basically undoes https://github.com/dimagi/commcare-hq/pull/10384 which was added to fix http://manage.dimagi.com/default.asp?217420. can you clarify what the issue here is? It seems like you @proteusvacuum and @dimagi/product should get on the same page about how this is supposed to work so we don't have to keep flip-flopping the behavior when new issues crop up.

**Comment by sravfeyn** [comment]
Thanks for pointing out that cory. Closing the ticket as this not a good change in light of that.

@dimagi/product  Here is the issue if we let any/all strings (Android UI strings + App specific strings) updated by CommCare UI translations, people are running into issues like [this](http://manage.dimagi.com/default.asp?222302#BugEvent.1115944). If we don't, they are not able to bulk update some translations. There are two possible resolution options
1. Have any/all strings updated by CommCare UI translations, but properly update corresponding strings in the app (for e.g. module.m0 update should actually update the module-name of the app). 
2. Only allow [Android UI strings](https://github.com/dimagi/commcare-translations/blob/master/messages_en-2.txt) (maintained by mobile team) in CommCare UI Translations, use Bulk App translations for all app-specific strings.
1 is little easy, but in terms of UX, we are giving 2 redundant ways to update translations for some strings. 2 is better option, but at first sight it's little more than interrupty

**Comment by amsagoff** [comment]
I've seen this modules.mo thing crop up several times and keep thinking
we've fixed it - so maybe we have been flip flopping a bit already...

Solution 2 sounds good. I'm not really tracking the problem that ICDS has,
though - is it just that they want to be able to update app translations
via UI translations?

**Comment by sravfeyn** [comment]
The problem ICDS has is (also good number of other domains) - whenever an app uses some advanced feature there are some strings that are neither part of App Translations not UI translations. To implement solution-2, we need to figure out where these strings come from and add a section to App translations xlsx file for their translation. 
I think this needs more digging on whether these strings should be added to Mobile-team managed UI translations or should they be part of App translations. Seems like not an easy_win, I am going to have to put it on my backlog or have this resourced separately. 
@amsagoff

**Comment by amsagoff** [comment]
In my memory, this issue only crops up for the module0 translation - and
over the past few years, i only remember this happening for module0.

My instinct is this is happening because the module0 is popping up in
autofill translations. You can see the problem (recently reported on another
ticket <http://manage.dimagi.com/default.asp?221576#1118552>) on this page
<https://india.commcarehq.org/a/lmrf-mch/apps/view/9b0ba401498cf29a1b05aa632db64974/languages/>
.

As a fix, I propose making sure that module0 is *not* included in autofill
translations for any language.

**Comment by sravfeyn** [comment]
Cool, implemented that here https://github.com/dimagi/commcare-hq/pull/11041
I think `modules.m0` is coming from published translations. When someone clicks autofill translations and saves them, HQ will explicitly remove `modules.m0` translation before saving them. Does that sounds good?

**Comment by amsagoff** [comment]
Sounds like it will address the core issue. will modules.m0 still appear in
the Languages UI on HQ?

**Comment by sravfeyn** [comment]
It might appear in the UI when you click auto-fill translations, but it wont be actually saved. That's why this fix is hacky/workaround and long term solution should be one of what we discussed.

**Pull request closed without merging**
