### PR TITLE
[ICDS Dashboard] Reformatted the date , added 'N/A' for empty values and fixed the sr no issue in dashboard usage report

### PR DESCRIPTION
**Pull request by challabeehyv**
https://dimagi-dev.atlassian.net/browse/QA-861
https://dimagi-dev.atlassian.net/browse/QA-860
https://dimagi-dev.atlassian.net/browse/QA-859

##### SUMMARY
Reformatted the last login date , added 'N/A' for empty values and fixed the sr no issue in dashboard usage report
##### FEATURE FLAG
No

### CODE REVIEW

**Comment by Rohit25negi** [comment]
@challabeehyv this looks good. You have also attached the ticket or crippled Sr no. I dont see its resovled in this ticket.

**Review by Rohit25negi — APPROVED** [review]
Can you test it locally?

**Comment by Rohit25negi** [comment]
> @challabeehyv this looks good. You have also attached the ticket or crippled Sr no. I dont see its resovled in this PR

I see now.

**Comment by challabeehyv** [comment]
> @challabeehyv this looks good. You have also attached the ticket or crippled Sr no. I dont see its resovled in this PR

custom/icds_reports/utils/__init__.py
This has the fix. Removed it from dashboard_usage.py  and added during report generation as we want it post sorting and this will remove the unnecessary looping

**Comment by challabeehyv** [comment]
> Can you test it locally?

tested it

**Pull request merged**
