### PR TITLE
Speed up device log

### PR DESCRIPTION
**Pull request by dannyroberts**
Should fix http://manage.dimagi.com/default.asp?217466
## Note to deployer

The reindex/migration tag is set because this adds a new relatively large sql index. This is a situation in which it would make sense to setup_release this branch on prod, and then run `./manage migrate phonelog` there and wait for it to complete before deploying. This should not cause any interruption, and it won't hang on deploy, though the pre-migration itself will likely take quite a bit of time to complete.

This will also not work on postgres < 9.4, so people will have to upgrade to 9.4; and there's been some confusion about whether staging was properly upgraded, so this may possibly cause problems on staging until we address it.
## Interesting backstory

Somewhat unintuitively, the thing that takes the longest in loading the Device Log Details report on a domain with a lot of them isn't the actual data but rather the filters, which need to get a list of all distinct values to show.

A while ago I made `fast_distinct` for this, using some code from the postgres wiki to implement a "loose index scan"—a technique for basically running distinct queries, but manually doing it in a way that's much faster than using the distinct keyword: finding the minimum value, then finding the smallest value less greater than it, and so on until you're done.

For this to be fast, the lookups have to be using an index. So when I first did this, I made an index for the 'type' column, and used `fast_distinct` to get a list of distinct types. But the code I was copying could only replace a full distinct on a column (i.e. across all domains). This worked fine for 'type' (which is a limited set regardless of the domain), but didn't work for username or device_id which are domain-specific, so those remained using bad ol' DISTINCT.

When I started working on http://manage.dimagi.com/default.asp?217466 it quickly became apparent that these `SELECT DISTINCT ... WHERE domain = 'pradan-mis'` queries were taking _long_ time. So I looked back at this `fast_distinct` hack and realized it could probably be modified pretty easily to also filter by domain. So I tested that in the psql shell on staging (on its own largest domain) and it was indeed way faster. Now, in order for it to be faster, of course, we also have to add an index for (domain, username) and (domain, device_id). (Indexing just username without domain is actually useless, which is what we were doing before.)

So that's what this PR does. It cleans up the device log sql indexes (removing useless ones and adding useful ones) and then adds this pretty huge (if gnarly) optimization.

### CODE REVIEW

**Comment by dannyroberts** [comment]
On staging, loading the filters went from 3 minutes to 1.5 seconds. :)

**Comment by benrudolph** [comment]
this is incredible :rocket: :horse_racing:

**Comment by czue** [comment]
really neat, thanks for the backstory! :clap:

**Comment by snopoke** [comment]
nice one @dannyroberts. Whoever creates the indexes should probably do a `CREATE INDEX CONCURRENTLY` to avoid locking writes from the table while the index is building. See http://www.postgresql.org/docs/9.4/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY

Unfortunately this means running the command manually via the SQL shell.

**Comment by dannyroberts** [comment]
@snopoke good point. I have some questions about that:

1. Is there a way to do this in the migration itself?
2. If we have to do it manually from the psql shell, will it be able to detect that an index exists and not create it? If so, does it only do this if we name it according to django's naming system which includes what looks like a hash of something?

**Comment by snopoke** [comment]
Unfortunately you can't do it in a django migration because migrations run
in transactions with no way around it. The index name should be consistent
across dB's so if you create it the the migration should be a noop. Should
test locally though using the sqlmigrate command to see the SQL output.

**Comment by dannyroberts** [comment]
Hmm. Looks like if I create the index beforehand, then I get

django.db.utils.ProgrammingError: relation
"phonelog_devicereportentry_domain_10959f20fea53534_idx" already exists

on migrate. Anyone ever get this to work in production before? I know
CONCURRENTLY has come up before, but I forget whether we've actually done
it successfully with a django migration.

**Comment by snopoke** [comment]
That's very irritating. It was possible to do it in a migration before we
upgraded to 1.7. I don't think we've done one since then.

I've looked for solutions before but not found any. Might have to fake the
migration.

**Comment by snopoke** [comment]
One possible option would be to write the migration SQL manually using
'create index if not exists'. I think you can use a RunSql operation and
pass it the state operation as  kwarg:
https://docs.djangoproject.com/en/1.9/ref/migration-operations/#runsql

**Comment by dannyroberts** [comment]
@snopoke OK I subclassed `AlterIndexTogether` to use concurrently in the last commit. Let me know what you think of that approach. Assuming it works, it reduces the steps down to

1. setup release
2. run migrate from that release
3. deploy

(And if you didn't mind hanging forever, you could even just skip to step 3.)

**Comment by snopoke** [comment]
Won't that still run it in a transaction?

**Comment by dannyroberts** [comment]
Oh, :hankey:

**Comment by dannyroberts** [comment]
And yeah the tests also came to the same conclusion:

```
django.db.utils.InternalError: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
```

**Comment by dannyroberts** [comment]
Ok, I guess we're back to the option you suggested of using `CREATE INDEX IF NOT EXISTS`—I can just do that along the same lines as the last commit.

**Comment by snopoke** [comment]
:+1:

**Comment by dannyroberts** [comment]
OK so to recap, my plan is the following. I look at the SQL commands my migration will produce:

```
$ ./manage.py sqlmigrate phonelog 0002
corehq.util.log.HqAdminEmailHandler logger is being changed to logging.StreamHandler
BEGIN;
CREATE INDEX IF NOT EXISTS "phonelog_devicereportentry_domain_10959f20fea53534_idx" ON "phonelog_devicereportentry" ("domain", "device_id");
CREATE INDEX IF NOT EXISTS "phonelog_devicereportentry_domain_2d9d284c035e8a57_idx" ON "phonelog_devicereportentry" ("domain", "username");

COMMIT;
```

I run the CONCURRENTLY version of them directly in the production psql shell
```
hqdb0$ psql  ...
CREATE INDEX CONCURRENTLY "phonelog_devicereportentry_domain_10959f20fea53534_idx" ON "phonelog_devicereportentry" ("domain", "device_id");
CREATE INDEX CONCURRENTLY "phonelog_devicereportentry_domain_2d9d284c035e8a57_idx" ON "phonelog_devicereportentry" ("domain", "username");
```

and when those are done, we merge this PR and deploy over it (which will work because of the IF NOT EXISTS).

Sound good @snopoke?

**Comment by snopoke** [comment]
:+1: yes that should work. Does this also remove the other unused indexes?

**Comment by dannyroberts** [comment]
It should. Your asking because `sqlmigrate` didn't print anything out to that effect? It was because I'd already run 0002 locally. If I rewind to 0001 and run it again:

```
BEGIN;
DROP INDEX "phonelog_devicereportentry_device_id_77e65ba2870e335f_uniq";
DROP INDEX "phonelog_devicereportentry_domain_24d5aaf71fe6d120_uniq";
DROP INDEX "phonelog_devicereportentry_user_id_4224977fb4192d6e_uniq";
DROP INDEX "phonelog_devicereportentry_username_5b999c89c85caf5a_uniq";
CREATE INDEX IF NOT EXISTS "phonelog_devicereportentry_domain_10959f20fea53534_idx" ON "phonelog_devicereportentry" ("domain", "device_id");
CREATE INDEX IF NOT EXISTS "phonelog_devicereportentry_domain_2d9d284c035e8a57_idx" ON "phonelog_devicereportentry" ("domain", "username");

COMMIT;
```

I just tested the above steps locally (rewind to 0001, run sqlmigrate 0002, copy the create commands with CONCURRENTLY into psql, run migrate 0002) and it all worked nicely until the last step, when I get

```
django.db.utils.ProgrammingError: syntax error at or near "NOT"
LINE 1: CREATE INDEX IF NOT EXISTS "phonelog_devicereportentry_domai...
```

http://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist/35626#35626 claims `IF NOT EXISTS` used this way is new in PostgreSQL 9.5. (Locally I'm on 9.2 and on prod according to ansible we're on 9.4.) Does that sound right?

**Comment by dannyroberts** [comment]
(Thanks for helping me with this; I think after we work out the kinks it's going to be really nice to finally have a process for this.)

**Comment by snopoke** [comment]
Ah, damn. I thought you could do IF NOT EXISTS on 9.4. Seems the only
option then is to fake the migration?

**Comment by dannyroberts** [comment]
@snopoke there's good news and bad news. The good news is I hacked around it to make it work for 9.4+. The bad news is that this is what it looks like: https://github.com/dimagi/commcare-hq/commit/c4b9f27ddd6a4ae8fa5077a55668d0320d989b91. I think the good news is better than the bad news is bad.

**Comment by snopoke** [comment]
Seems OK to me. not that much of a hack and with a known end of life plan.

On 25 February 2016 at 18:24, Daniel Roberts <notifications@github.com>
wrote:

> @snopoke <https://github.com/snopoke> there's good news and bad news. The
> good news is I hacked around it to make it work for 9.4+. The bad news is
> that this is what it looks like: c4b9f27
> <https://github.com/dimagi/commcare-hq/commit/c4b9f27ddd6a4ae8fa5077a55668d0320d989b91>.
> I think the good news is better than the bad news is bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/10374#issuecomment-188862178>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by dannyroberts** [comment]
OK I've kicked these off on prod. Once they're done, I think the migration (dropping the other indexes) should be quick enough to do during deploy

**Comment by dannyroberts** [comment]
Oh, and I've tested the whole workflow as I outlined above on staging, and it all works like a charm!

**Comment by snopoke** [comment]
🙌

**Comment by dannyroberts** [comment]
The indexes have been created on prod, g2m!

**Comment by czue** [comment]
:boom:

**Pull request merged**
