### PR TITLE
Update linux docker instructions

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

I'm pretty confused at this point, so maybe it is best for a linux user to take over this. Why do docker installation instructions differ between docker/README.md and DEV_SETUP.md? 

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Comment by kaapstorm** [comment]
> Why do docker installation instructions differ between docker/README.md and DEV_SETUP.md?

`DEV_SETUP.md` instructions are for running the development web server natively. `docker/README.md` instructions are for running the whole HQ environment using Docker, and is intended for third-parties, not HQ devs.

**Comment by kaapstorm** [comment]
:thinking: I take it back. `docker/README.rst` has a section "Running only services in Docker". I'm not sure who that section is intended for.

**Comment by gherceg** [comment]
In Cal's words, we used to use docker from the ubuntu repos and not the docker repos because it was easier. However now that we need to include docker repos, it might be easier to just point devs to the docker repos for the entire docker setup. Does that make sense to you @kaapstorm?

**Comment by kaapstorm** [comment]
Yes, it does.

**Review by millerdev — APPROVED** [review]
I didn't have a chance to try this out (and probably won't because I use podman), but it looks fine to me.

**Comment by gherceg** [comment]
Honestly given I don't use linux I don't feel in a good position to make any substantial changes to those docs related to docker setup, so just going to merge this as is. If anyone wants to take a stab at cleaning up the docker setup instructions for linux, potentially just referencing the docker instructions directly instead, that would be much appreciated!

**Pull request merged**
