### PR TITLE
cleaning up app type dropdown for exports

### PR DESCRIPTION
**Pull request by calellowitz**
@benrudolph @kaapstorm cc: @NoahCarnahan 
simplifying the app type dropdown on exports for @amsagoff and @sheelio 
http://manage.dimagi.com/default.asp?217105#1102131
screen shot 2016-03-08 at 4 34 21 pm
screen shot 2016-03-08 at 4 34 45 pm

### CODE REVIEW

**Comment by amsagoff** [comment]
noice

**Comment by kaapstorm** [comment]
:+1: by me. Definitely not blocking, and totally a subjective opinion, but I like comprehensions over `map` (and `filter`) (maybe only because comprehensions appeal to some personal aesthetic ... or something).

**Comment by benrudolph** [comment]
sweet! i'm a `map` and `filter` guy cause i don't like that you can add if statements and other stuff to comprehensions :stuck_out_tongue: (also i don't think he changed any of that if you look at this diff with `w=1`)

**Comment by calellowitz** [comment]
I tend to prefer list comprehensions but Ben is right, I just moved some code that was already written for this page so didn't want to change it too much

**Comment by kaapstorm** [comment]
:+1: :smile: (One day I will write you a poem about the poetry of comprehensions, @benrudolph -- the `if`s are crucial, although double `for`s should be replaced with generators --oh! that's the one thing more beautiful than a list comprehension -- a generator comprehension! :rainbow:) (WAT?! There's no pink unicorn emoji?!)

**Comment by benrudolph** [comment]
hahaha i like the descriptiveness of `filter` and `map` :rainbow: :rainbow:

**Pull request merged**
