### PR TITLE
Revert "Set mapbox key to one that works from previous commit"

### PR DESCRIPTION
**Pull request by snopoke**
Reverts dimagi/commcare-hq#20946

The old key is fine - just needed to update our MapBox account. This other key is from Cory's personal MapBox account.

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
Should these be in the repo?

**Comment by snopoke** [comment]
It doesn't matter since they end up in JS in the browser anyway.

**Comment by proteusvacuum** [comment]
Thanks!

**Comment by emord** [comment]
This should probably be in localsettings so that its harder to accidentally use ours

**Pull request merged**
