### PR TITLE
Minor improvements and some documentation

### PR DESCRIPTION
**Pull request by mkangia**
Walking through async processing found few improvements.

Also added some documentation from my understanding of the code, that I think would be helpful.

### CODE REVIEW

**Review by czue — APPROVED** [review]
Looks great, thanks for the cleanup!

**Comment by calellowitz** [comment]
adding @sravfeyn who is doing work on some of this stuff now

**Comment by sravfeyn** [comment]
Thanks for looking into this Manish. I think the conflicts are due to the work I did in this PR https://github.com/dimagi/commcare-hq/pull/27207

**Comment by mkangia** [comment]
Closed in favour of https://github.com/dimagi/commcare-hq/pull/27280, avoid merge conflicts which were harder to solve than to just redo the PR changes. Used the same commit messages for easier mapping

**Pull request closed without merging**
