### PR TITLE
Assign location on GPS Capture page using map

### PR DESCRIPTION
**Pull request by mkangia**
## Product Description

Building on https://github.com/dimagi/commcare-hq/pull/33467, now user can click on the map to capture location for a user/case and that populates the latitude and longitude input fields

## Technical Summary

https://dimagi-dev.atlassian.net/browse/SC-2923
Simply use the click binding on the map to populate gps coordinates on the knockout model

## Feature Flag

GEOSPATIAL

### Safety story

Tested locally

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by zandre-eng — APPROVED** [review]

**Review by SmittieC — APPROVED** [review]

**Comment by SmittieC** [comment]
Nice! Maybe we can `noqa` that mapboxgl linting issue?

**Comment by mkangia** [comment]
Looks like we do noqa differently for JS, going to give that a try

**Comment by mkangia** [comment]
Looks like that did it, https://github.com/dimagi/commcare-hq/pull/33474/commits/7756cb3f97ed78042b912614e077ec1acd449e29

**Review by SmittieC — APPROVED** [review]
:rocket:

**Pull request merged**
