### PR TITLE
Add variable fetch limit to deploys page

### PR DESCRIPTION
**Pull request by proteusvacuum**
Appending for e.g. `?limit=100` will now fetch 100 results at at time. This should allow searching of releases more easily.

@czue 
buddy @emord

### CODE REVIEW

**Comment by czue** [comment]
tests failed
```
  3 failing
  1) App Releases SavedApp should only make one request when downloading zip:
     TypeError: 'undefined' is not an object (evaluating 'app.download_application_zip')
      at http://localhost:8000/static/app_manager/spec/releases_spec.js:48
      at callFn (http://localhost:8000/static/mocha/mocha.js:4202)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at http://localhost:8000/static/mocha/mocha.js:4661
      at http://localhost:8000/static/mocha/mocha.js:4790
      at next (http://localhost:8000/static/mocha/mocha.js:4581)
      at http://localhost:8000/static/mocha/mocha.js:4591
      at next (http://localhost:8000/static/mocha/mocha.js:4523)
      at http://localhost:8000/static/mocha/mocha.js:4554
      at done (http://localhost:8000/static/mocha/mocha.js:4163)
      at callFn (http://localhost:8000/static/mocha/mocha.js:4217)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at next (http://localhost:8000/static/mocha/mocha.js:4555)
      at http://localhost:8000/static/mocha/mocha.js:4559
      at timeslice (http://localhost:8000/static/mocha/mocha.js:12326)
  2) App Releases SavedApp should use the correct URL for downloading ccz:
     TypeError: 'undefined' is not an object (evaluating 'app.download_application_zip')
      at http://localhost:8000/static/app_manager/spec/releases_spec.js:54
      at callFn (http://localhost:8000/static/mocha/mocha.js:4202)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at http://localhost:8000/static/mocha/mocha.js:4661
      at http://localhost:8000/static/mocha/mocha.js:4790
      at next (http://localhost:8000/static/mocha/mocha.js:4581)
      at http://localhost:8000/static/mocha/mocha.js:4591
      at next (http://localhost:8000/static/mocha/mocha.js:4523)
      at http://localhost:8000/static/mocha/mocha.js:4554
      at done (http://localhost:8000/static/mocha/mocha.js:4163)
      at callFn (http://localhost:8000/static/mocha/mocha.js:4217)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at next (http://localhost:8000/static/mocha/mocha.js:4555)
      at http://localhost:8000/static/mocha/mocha.js:4559
      at timeslice (http://localhost:8000/static/mocha/mocha.js:12326)
  3) App Releases SavedApp should use the correct URL for downloading multimedia:
     TypeError: 'undefined' is not an object (evaluating 'app.download_application_zip')
      at http://localhost:8000/static/app_manager/spec/releases_spec.js:61
      at callFn (http://localhost:8000/static/mocha/mocha.js:4202)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at http://localhost:8000/static/mocha/mocha.js:4661
      at http://localhost:8000/static/mocha/mocha.js:4790
      at next (http://localhost:8000/static/mocha/mocha.js:4581)
      at http://localhost:8000/static/mocha/mocha.js:4591
      at next (http://localhost:8000/static/mocha/mocha.js:4523)
      at http://localhost:8000/static/mocha/mocha.js:4554
      at done (http://localhost:8000/static/mocha/mocha.js:4163)
      at callFn (http://localhost:8000/static/mocha/mocha.js:4217)
      at http://localhost:8000/static/mocha/mocha.js:4195
      at next (http://localhost:8000/static/mocha/mocha.js:4555)
      at http://localhost:8000/static/mocha/mocha.js:4559
      at timeslice (http://localhost:8000/static/mocha/mocha.js:12326)
>> 3/23 tests failed (0.04s)
Warning: Task "mocha:app_manager" failed. Use --force to continue.
```

**Comment by czue** [comment]
i don't know if we care, but does this break if you pass in `?limit=pineapple`

**Comment by czue** [comment]
:pineapple: :smile:

**Comment by proteusvacuum** [comment]
@dimagi/product Do you think it would be useful to add a text box that does this on the deploys page? Like a thing which says "Show [xxx] results". (Alternatively, is there a reason this page isn't just paginated regularly?)

**Pull request merged**
