### PR TITLE
gevent multi migrate

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke do you see any potentially bad things that could happen if we made this command async? noticed it was taking a while during deploys

cc: @esoergel

### CODE REVIEW

**Comment by benrudolph** [comment]
seems to work async locally:
screen shot 2016-03-26 at 4 15 04 pm

added a bit of error checking if one of the migrations fails:
screen shot 2016-03-26 at 4 21 09 pm

**Comment by snopoke** [comment]
Shouldn't be any issue. Nice 🚄

**Comment by snopoke** [comment]
Probably shouldn't be async if interactive. Or disable setting interactive option

**Comment by benrudolph** [comment]
good point, updated to support interactive and noinput: https://github.com/dimagi/commcare-hq/pull/10948/commits/3006421a28170a4d53a5f5d2353aa857ba5416ad

**Comment by esoergel** [comment]
Awesome!

**Pull request merged**
