### PR TITLE
migrate gsid reports to b3

### PR DESCRIPTION
**Pull request by biyeun**
@snopoke or @sravfeyn 
cc @emord

### CODE REVIEW

**Comment by snopoke** [comment]
:+1:

**Comment by biyeun** [comment]
map report shows a JS error. other reports load fine, just the location filter looks a bit whack.
Will prioritize addressing this first thing. assuming that since no one said anything over the past week (oops) that map report is not mission critical, but should get fixed asap. @snopoke thoughts on whether that's grounds to revert this?

**Comment by biyeun** [comment]
here is location filter for my ref:
screen shot 2016-03-28 at 5 33 26 pm

**Comment by snopoke** [comment]
I don't think these get used much if at all. We could look at retiring
them. Does the domain still have custom report access?

**Comment by biyeun** [comment]
@snopoke It looks like the domain does have custom report access. 

@dimagi/product not sure if you guys are the best ones to ping re: retiring these reports?

**Comment by czue** [comment]
(probably the project team, not @dimagi/product)

**Comment by sravfeyn** [comment]
(I think Nick Nestle was PMing this project when I worked on these reports in 2013)

**Pull request merged**
