### PR TITLE
Fixed covid autodoc

### PR DESCRIPTION
**Pull request by orangejenny**
Followup for https://github.com/dimagi/commcare-hq/pull/29707

This is a little bit awful, which seems to be par for the course with docs build issues. Build was failing with

```
WARNING: autodoc: failed to import module 'custom_actions' from module 'custom.covid.rules'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/jschweers/.pyenv/versions/3.6.8/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_module
    return importlib.import_module(modname)
  File "/Users/jschweers/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
...
  File "/Users/jschweers/.pyenv/versions/3.6.8/lib/python3.6/site-packages/botocore/httpsession.py", line 17, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/Users/jschweers/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 101, in <module>
    + OpenSSL.SSL.VERIFY_FAIL_IF_NO_PEER_CERT,
TypeError: unsupported operand type(s) for +: 'VERIFY_PEER' and 'VERIFY_FAIL_IF_NO_PEER_CERT'
```

https://github.com/dimagi/commcare-hq/pull/29141 configured the docs build to mock OpenSSL because ReadTheDocs can't support it, but one of our dependencies leads to a top-level import of some constants in OpenSSL. Presumably, these get interpreted as None due to the mock, which then causes the operand error.

The simplest way to fix this is to get the erroring import out of the top-level imports.

This PR also fixes a very small number of our very many docs warnings.

### CODE REVIEW

**Review by czue — APPROVED** [review]
Thanks! I still feel like hosting our own docs might be the right long-term move. This game of cat and mouse feels like it'll lead to more effort than just biting the bullet and building everything in a full-blown HQ environment.

**Comment by orangejenny** [comment]
@czue Agreed, although I'm not sure if there's been enough pain yet for any division to be willing to resource the time to set up our own hosting.

**Comment by esoergel** [comment]
It wouldn't be too hard to have travis build docs for us, though I'm not certain what we'd do with the artifacts - maybe recommit them and host on github pages?

**Comment by orangejenny** [comment]
@esoergel That would make Travis surface warnings, but wouldn't affect the import issues, right? Committing the artifacts seems okay.

**Comment by esoergel** [comment]
Oh that's true, we could add a docs build to travis just as part of our test suite - ie, docs fail to build, that's a test failure.

What I meant is that travis has a "full-blown HQ environment", as Cory put it, so presumably it's less likely to run into build failures than readthedocs.  Travis could then generate the static files used for the docs, but we'd still have to store and host them somehow (github pages could work).

This is actually a larger infrastructural question, IMO.  We don't have a "build" step in our CI tooling, so all our generated files are handled in sub-optimal, ad-hoc ways.  A few offhand, though I know there are others:
* requirements must be built by the developer, which is enforced by a test
* docs are built on readthedocs, which can fail silently
* `.po` files are compiled during deploy on each machine individually

We could probably use a solution to any one of these as a guide for the others.

**Comment by orangejenny** [comment]
@esoergel Got it, thank you for laying out the context. I see you added this to the next cross-divisional dev owners agenda, it'll be good to talk about it.

**Pull request merged**
