### PR TITLE
Re-instate pencil icons on app manager menu

### PR DESCRIPTION
**Pull request by orangejenny**
Merged https://github.com/dimagi/commcare-hq/pull/12842 locally and realized that pencil icons aren't showing on hover.

@biyeun feel free to change, I just wanted to get a quick fix in

@NoahCarnahan this needs to be merged before today's deploy

### CODE REVIEW

**Comment by biyeun** [comment]
hmmm, that's odd. had you done a hard refresh?

**Comment by orangejenny** [comment]
I was definitely getting the new CSS and JS. But if it's a matter of code not being up to date, this PR shouldn't have been merged. Was there code in #12842 that was supposed to make the pencils visible on hover?

**Comment by biyeun** [comment]
The css should have taken care of it, but maybe i inadvertently flipped that change while working on the move icon

**Comment by biyeun** [comment]
A lot of the hide/show stuff we do with javascript is often better done with css, especially when we want to do more animated transitions---it's far easier to do all of that with css properties

**Comment by orangejenny** [comment]
Agreed - definitely feel free to update the code, I was just aiming to put on a band-aid.

**Pull request merged**
