### PR TITLE
Vary on self.field for devicelog report

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts need to vary on field as well, tricksy!

cc: @millerdev 

http://manage.dimagi.com/default.asp?225029

### CODE REVIEW

**Comment by millerdev** [comment]
Would it be hard to write a test for this?

**Comment by benrudolph** [comment]
in general we don't have any tests for reports or filters because they're so heavily coupled with the `request` object which is somewhat difficult, but definitely not impossible. i can give a crack at it tomorrow and just pass a magicmock as the request object

**Comment by millerdev** [comment]
Could you use the [django test client](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#the-test-client) to make a request?

**Comment by benrudolph** [comment]
i've traditionally used the django test client to make http requests. that would actually make testing this way harder since we'd have to make the proper http call to the report and be able to generate all the correct things which is difficult. i think just instantiating the filter and mocking the request object that we pass into the __init__ function is the simplest route

**Comment by dannyroberts** [comment]
oops. Thanks ben!

**Pull request merged**
