### PR TITLE
Register all_docs views to new db

### PR DESCRIPTION
**Pull request by esoergel**
@dannyroberts @sravfeyn
Also updated docs to explain the change.

### CODE REVIEW

**Comment by esoergel** [comment]
This has a reindex, but for an empty db, so it shouldn't be time consuming.

**Comment by dannyroberts** [comment]
Good catch—surprised the flip PR was passing without this!

**Comment by dannyroberts** [comment]
And thanks for updating the docs!

**Comment by dannyroberts** [comment]
failure real (but just need to update the test):
```
======================================================================
FAIL: test_get_all_doc_ids_for_domain_grouped_by_db (corehq.couchapps.tests.test_all_docs.AllDocsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/couchapps/tests/test_all_docs.py", line 35, in test_get_all_doc_ids_for_domain_grouped_by_db
    get_db('fixtures').uri: []}
AssertionError: {'http://127.0.0.1:5984/commcarehq__meta_test': [], 'http://127.0.0.1:5984/commc [truncated]... != {'http://127.0.0.1:5984/commcarehq__meta_test': [], 'http://127.0.0.1:5984/commc [truncated]...
- {'http://127.0.0.1:5984/commcarehq__domains_test': [],
-  'http://127.0.0.1:5984/commcarehq__fixtures_test': [],
? ^
+ {'http://127.0.0.1:5984/commcarehq__fixtures_test': [],
? ^
   'http://127.0.0.1:5984/commcarehq__meta_test': [],
   'http://127.0.0.1:5984/commcarehq__users_test': ['users_db_doc'],
   'http://127.0.0.1:5984/commcarehq_test': ['main_db_doc']}
----------------------------------------------------------------------
```

**Pull request merged**
