### PR TITLE
Don't call is_active on non-visible tabs

### PR DESCRIPTION
**Pull request by esoergel**
@snopoke This removes the `all_tabs` thing introduced in this PR https://github.com/dimagi/commcare-hq/pull/2672/files
This was causing `is_active` to be called on tabs which shouldn't be visible, and in some cases triggering http://manage.dimagi.com/default.asp?176456.  I don't think I understand what the `all_tabs` list was for - do you remember?  I'll deploy this to staging before merging in to prod, but won't get to it 'till Monday

### CODE REVIEW

**Comment by snopoke** [comment]
I have no idea what all_tabs is for. I changed this quite a long time ago and didn't give much thought to its correctness, just its optimization. Looking at it now it seems reasonable to get rid of it though there may be some weird edge cases or something. Good to QA on staging.

**Comment by esoergel** [comment]
Sounds good.  It's on staging now, and I opened a QA ticket.

**Comment by czue** [comment]
@esoergel any updates on this? these errors are getting super annoying

**Comment by esoergel** [comment]
@czue Yeah, just got QA feedback: http://manage.dimagi.com/default.asp?176760  Two issues, one is surely unrelated, the other might not be.  I'll look in to it now.

**Comment by esoergel** [comment]
The issues are unrelated to this change, so we can merge this and resolve those separately.

**Pull request merged**
