### PR TITLE
vary cache on args

### PR DESCRIPTION
**Pull request by snopoke**
@dannyroberts @benrudolph

### CODE REVIEW

**Comment by czue** [comment]
```
======================================================================
ERROR: test_vary_on_func (corehq.util.tests.test_quickcache.QuickcacheTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/tests/test_quickcache.py", line 182, in test_vary_on_func
    self.assertRegex(key, 'quickcache.cached_fn.[a-z0-9]{8}/sa1')
AttributeError: 'QuickcacheTest' object has no attribute 'assertRegex'
----------------------------------------------------------------------
```

**Comment by snopoke** [comment]
hmm, maybe a new feature in django 1.6. will update

**Comment by dannyroberts** [comment]
Crap, I'm sorry I let that slip by. That also is a pretty serious failure mode of `quickcache` that somehow hadn't occurred to me—that you can very easily by mistake make all calls to a function return something arbitrary regardless of arguments. Wonder if it should just fail hard if you pass nothing in, and to get this behavior, make you pass in `[]` explicitly—we could do this pretty easily by just removing the default value of vary_on in (right now it's `def quickcache(vary_on='', timeout=None, memoize_timeout=None, cache=None)`) and finding all usages of quickcache as a singleton cache, and changing the call to use an argument.

**Comment by snopoke** [comment]
@czue @dannyroberts build passing :white_check_mark:

**Comment by snopoke** [comment]
@dannyroberts yea I think failing hard if nothing is supplied is a good idea

**Comment by benrudolph** [comment]
nice, thanks. agree with danny on that

**Comment by dannyroberts** [comment]
OK, tracking at http://manage.dimagi.com/default.asp?161813

**Pull request merged**
