### PR TITLE
disable _all field for sms index

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
Amended @snopoke's commit from https://github.com/dimagi/commcare-hq/pull/25666 to include only SMS index and to update the index name to trigger a reindex.

On production I think the SMS index is small enough that it reindexing isn't a huge burden. Is that true on ICDS as well?

### CODE REVIEW

**Review by biyeun — APPROVED** [review]

**Review by snopoke — COMMENTED** [review]
Probably OK for ICDS (we have 20M docs). One concern is that we haven't done an ES reindex in a long time so may need to tweak it. We can try kick off the reindex in a limited release and see how it goes.

For future reindexes it would be great to figure out the process for using the ES reindex feature: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-reindex.html

**Comment by dannyroberts** [comment]
@snopoke Cool, yeah I agree that'd be nice. I took a stab at a CEP for this https://github.com/dimagi/commcare-hq/issues/26516, feel free to update the description directly if you have more fleshed out ideas and/or to comment.

**Review by dannyroberts — COMMENTED** [review]
I can't approve my own PR, but @snopoke I approve your changes. Let me know if you want me to delay, otherwise I'll probably merge this tomorrow (Jan 30)

**Comment by snopoke** [comment]
@dannyroberts please can we wait to merge this until the ICDS reindex is complete otherwise it will block deploy. I'm going to continue monitoring it today and hopefully it will be done by EOD.

**Comment by snopoke** [comment]
@dannyroberts we can go ahead and merge this now

**Comment by dannyroberts** [comment]
Awesome, thanks!

**Pull request merged**
