### PR TITLE
add build info

### PR DESCRIPTION
**Pull request by sravfeyn**
cc @gcapalbo

### CODE REVIEW

**Comment by sravfeyn** [comment]
@calellowitz

**Review by gcapalbo — APPROVED** [review]

**Comment by calellowitz** [comment]
@sravfeyn I think you need to renumber the migration (and change its dependency), but otherwise this looks good to go

**Comment by sravfeyn** [comment]
Cool. For reordering the migration, I should merge the branch `ce/auto-batches` into this branch and reorder it, yeah?

**Comment by calellowitz** [comment]
> Cool. For reordering the migration, I should merge the branch ce/auto-batches into this branch and reorder it, yeah?

yeah that sounds right

**Comment by sravfeyn** [comment]
Hey @calellowitz I manually moved it, ran tests and airflow, everything went well. So this it good to go.

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
