### PR TITLE
Track the percentage of time we have a maintenance alert up

### PR DESCRIPTION
**Pull request by dannyroberts**
This is a metric that Dev wanted

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
It's my understanding that a gauge is used to record an un-aggregated value of something like CPU usage, and it doesn't make sense to aggregate it. One of the best explanations I've found of the purpose of gauges is [this SO answer](https://stackoverflow.com/a/52049382/10840), which says

> Gauge simply reflect the status of your system, or some metric you don't want to be aggregated at all.

Maybe that's just wrong? Curious how you're planning to use gauge values in datadog to measure the percentage of time we have a maintenance alert up? Have we done anything like that before?

**Comment by dannyroberts** [comment]
Yeah so I was thinking this would create a graph that's a straight line at 0 or 1, and then we can roll up the averages to get the percent of time in a given period. This is a lot like how the `http.can_connect` metric works, and you can get uptime numbers from it, though I'm not sure how precise it is. For this I think it should be fairly good—we'll be sampling the value once a minute, and I don't think it's vulnerable to average of averages errors because of the evenness of the data. (I think if buckets of equal duration have an equal number of values contained in them, then averages of averages work out fine.)

So yeah this still seems like a fine idea to me, let me know if you see it differently

**Comment by millerdev** [comment]
I don't know of a function in datadog to answer the question _How many time units (minutes, hours, days) was this metric at a given value (`> 0`, for example)?_ Maybe there is something like that that I don't know about?

As I understand it a [gauge](https://docs.datadoghq.com/developers/dogstatsd/data_types/#gauges) metric maintains the value that was most recently recorded until a new value is recorded. I'm not exactly sure how this is handled when aggregations are applied, but in this "uptime" case it might be similar to a counter that is incremented by 1 every 10s (datadog's default aggregation interval).

I wonder if it would make more sense to use a [counter](https://docs.datadoghq.com/developers/dogstatsd/data_types/#counters) that is incremented by 1 every minute that a maintenance alert is active. Then you can aggregate over whatever period you want and divide by the number of minutes in that period to get the value. The down-side to this is that it requires precise measurement of time to record each minute that the alert is active. If a counter update is skipped for whatever reason then the data in datadog will be wrong. But I'm not sure this is a big problem.

**Comment by dannyroberts** [comment]
> As I understand it a gauge metric maintains the value that was most recently recorded until a new value is recorded
I agree with this.
> I'm not exactly sure how this is handled when aggregations are applied, but in this "uptime" case it might be similar to a counter that is incremented by 1 every 10s (datadog's default aggregation interval).
This makes it sound like if you graph avg of a 0-or-1 gauge metric over time you would get a line going up and to the right with a slope of 1, but that's not what you get. What you get is mostly a straight line at whatever the most common value is (0 for this metric, 1 for site uptime metrics) with dips/spikes when there's downtime. Check out these graphs for some examples: https://app.datadoghq.com/dashboard/s5q-92s-vrw/dannys-timeboard-12-mar-2019-1637?tile_size=m&page=0&is_auto=false&from_ts=1551981600000&to_ts=1552586400000&live=true&tpl_var_environment=production. The graph for this new metric is on there, but it's totally uninteresting at this point because it's a flat line at 0.

I'm not sure if that lands with you; if it doesn't then I'm probably misunderstanding a point you're making and maybe we should go to voice. As far as I can tell, this metric is working the way I intended it to

**Pull request merged**
