### PR TITLE
Remove hsph reports

### PR DESCRIPTION
**Pull request by dannyroberts**
[6/24/15, 2:54:50 PM] Danny Roberts: hey sheel
[6/24/15, 2:55:09 PM] Danny Roberts: does hsph use the 'hsph' domain for anything nowadays?
[6/24/15, 2:55:09 PM] Danny Roberts: https://www.commcarehq.org/a/hsph/reports/submit_history/?emw=t__0&form_unknown=&form_unknown_xmlns=&form_status=active&form_app_id=&form_module=&form_xmlns=&sub_time=&startdate=2011-10-01&enddate=2015-06-24
[6/24/15, 2:55:15 PM] Danny Roberts: no submissions since march 2014
[6/24/15, 2:56:05 PM] Danny Roberts: i ask, because at some point we (someone) rewrote hsph reports, and made a copy of all the old ones
[6/24/15, 2:56:17 PM] Danny Roberts: and 'hsph' domain is still on the old ones
[6/24/15, 2:56:20 PM] Sheel Shah: we dont use the hsph reports at all
[6/24/15, 2:56:26 PM] Sheel Shah: and hsph is not in use
[6/24/15, 2:56:34 PM] Danny Roberts: wait that's amazing
[6/24/15, 2:56:45 PM] Danny Roberts: are you saying I can go ahead and delete all hsph custom reports?

And then sheel disappeared. So I continued investigating, and he was right: by grepping proxy logs, I found that none of the three hsph domains had had their custom reports visited in the last 2 years.

I've already removed

```
"hsph-betterbirth-pilot-2": "hsph",
"hsph-dev": "hsph",
```

from `DOMAIN_MODULE_CONFIG` in the prod DB. (When I tested, a number of those custom reports were 500ing anyways.)

This PR removes the code.

### CODE REVIEW

**Comment by dannyroberts** [comment]
In addition to a bunch of code, this would remove **17** views

**Comment by dannyroberts** [comment]
@sheelio, can you confirm this is totally ok?

**Comment by benrudolph** [comment]
you took too long to respond to him!

**Comment by czue** [comment]
image
:heart_eyes:

**Comment by sheelio** [comment]
Do it.  Remove em!

**Comment by dannyroberts** [comment]
:tada: @benrudolph want to do the honors?

**Comment by benrudolph** [comment]
:bomb: ----> :boom: hsph :boom:

**Comment by czue** [comment]
:confetti_ball:

**Pull request merged**
