### PR TITLE
Revert "Merge pull request #30559 from dimagi/dependabot/pip/requirem…

### PR DESCRIPTION
**Pull request by gherceg**
…ents/openpyxl-3.0.9"

This reverts commit ddfdc07463daf4489c4e01fd94bcbc1d5cf10757, reversing
changes made to 2026a74c6aa9acd8a996de77b7cc231a4fd3095a.

Reverting [this PR](https://github.com/dimagi/commcare-hq/pull/30559)

## Technical Summary

https://dimagi-dev.atlassian.net/browse/SAAS-13134

Introduced a bug into downloading exports that I should have caught. I'm looking into stripping timezone info entirely from the couch date before sending to openpyxl, but due to local env issues is taking longer than I hoped. Reverting this PR for now to fix the bug.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
Introduced a bug into downloading exports that I should have caught. I'm looking into stripping timezone info entirely from the couch date before sending to openpyxl, but due to local env issues is taking longer than I hoped. Reverting this PR for now to fix the bug.

**Comment by gherceg** [comment]
> reversing changes made to 2026a74.

This doesn't seem true and/or related, so I'm confused. I ran `git revert -m 1 ddfdc07463daf4489c4e01fd94bcbc1d5cf10757` and fixed conflicts with the recent [ipython bump](https://github.com/dimagi/commcare-hq/pull/31026) by taking the newer version of `jedi`.

**Comment by gherceg** [comment]
^ talked with Joel and we are chalking that up to git leaving a very confusing autogenerated message since Norman's commit was the previous commit on master to this merge commit. As the PR shows, there isn't anything related to Norman's commit.

**Comment by gherceg** [comment]
I'm going to test this on staging, but would like to get this out in today's deploy.

**Review by joxl — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Pull request merged**
