### PR TITLE
Update license text formatting

### PR DESCRIPTION
**Pull request by dankohn**
This changes how the license is formatted but has no effect on the actual
licensing of the project. By using the
standard text formatting, it enables the GitHub library
licensee https://developer.github.com/v3/licenses/ to correctly identify
the license as BSD-3.

That will then show up correctly on this COVID-19 response
landscape: https://landscape.lfph.io/selected=comm-care&zoom=150

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
This looks fine but conflicts with https://github.com/dimagi/commcare-hq/pull/27872, could you pull and resolve the conflict?

**Comment by orangejenny** [comment]
fyi @ctsims

**Comment by dankohn** [comment]
@orangejenny I fixed the merge conflict.

**Comment by orangejenny** [comment]
Thanks @dankohn , merging.

**Comment by dankohn** [comment]
And that worked. GitHub now sees you as BSD-3. However, I accidentally overwrite https://github.com/dimagi/commcare-hq/pull/27872 if you could reapply that (just change the `2019` to `2020`).

**Comment by orangejenny** [comment]
thanks for flagging, I'll do that

**Pull request merged**
