### PR TITLE
don't enable apply button in UCRs until events are setup

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?220866

not thrilled with this approach, though couldn't think of anything better.

@nickpell @NoahCarnahan cc @emord

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
I'm not sure of a better solution either, but might be worth noting that I think the bug first became noticeable around the time that https://github.com/dimagi/commcare-hq/pull/10598/ was deployed. For some reason parts of the page (like the filters) started loading rather slowly at that point.

**Comment by czue** [comment]
interesting. I was playing around in a profiler trying to figure out what was getting slow but didn't make much sense of it. I was also wondering if it was related to the leaflet/maps change which also on a similar schedule and looked like may be causing some slowness (but I didn't really understand what I was looking at).

**Comment by NoahCarnahan** [comment]
I had noticed that the `toggles.js` file in particular was taking a very long time to load, and @dannyroberts fixed a cacheing issue that was apparently the culprit. Not sure if it's worth pursuing further, but thought I'd just bring it up incase someone else has some more info that brings all the pieces together.

**Comment by dannyroberts** [comment]
Meant to comment when I first saw this, but my take is it's possible for `toggles.js` to delay the initial load, but after that it's cached more or less forever for your domain + user until you change a toggle for the domain or user. In other words I wouldn't expect this to happen reproduceably as a result of `toggles.js`

**Pull request merged**
