### PR TITLE
Multimedia not downloading

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?188489

First commit fixes the bug (this has...never worked? not worked in a long time? one of those two). Remaining commits just standardize the UI a bit.

before:
screen shot 2015-12-04 at 12 24 48 pm

after:
screen shot 2015-12-04 at 12 24 00 pm

@dannyroberts / @proteusvacuum

### CODE REVIEW

**Comment by benrudolph** [comment]
someone call the fire department :fire_engine:. @orangejenny on :fire: :fire:

**Comment by orangejenny** [comment]
test failure unrelated (see https://github.com/dimagi/commcare-hq/pull/9421)

**Comment by czue** [comment]
this is great! only thought I had was whether the "show only missing references" should be like a dropdown or radio button or something since it's kind of a mode toggle and not a button or a link

**Comment by czue** [comment]
(not actionable if you disagree or don't think it's worth the effort, just a thought)

**Comment by orangejenny** [comment]
Yeah, agree that the link isn't ideal, this might be the rare good place to use a checkbox. Going to leave it alone for now - there are a couple of other medium-sized ux changes I'd like to make here, hoping to come back to it soon.

**Pull request merged**
