### PR TITLE
Handle document update conflict when builder export schema

### PR DESCRIPTION
**Pull request by NoahCarnahan**
http://manage.dimagi.com/default.asp?229677
@benrudolph cc @kaapstorm

### CODE REVIEW

**Comment by czue** [comment]
this seems fine but do we know why this is happening so often? is there anything we can do to stop saving it so frequently?

**Comment by NoahCarnahan** [comment]
For the ICDS app, this page is really slow to load, which I think causes people to try loading the page multiple times simultaneously in multiple tabs (which causes the conflict). We have a separate ticket to track "speed things up", so I'm hoping this change will just be a stopgap.

**Comment by benrudolph** [comment]
seems like we'd also have the same issue for form exports

**Comment by NoahCarnahan** [comment]
(updated for form schema)

**Comment by czue** [comment]
just to confirm, we write the schema doc on every page load and there's no easy way around that?

**Comment by czue** [comment]
(none of my comments are blocking in case not clear - just want to understand)

**Comment by benrudolph** [comment]
yes, we currently do write the schema every time though we could easily skip that if there are no new apps to iterate over

**Comment by NoahCarnahan** [comment]
It should easy to not save the schema if we didn't find any new builds on this page load, so that's probably an optimization worth making. There is still a chance of "overlapping" page loads though that would trigger the document update conflict.

As I'm thinking more about this though, it's interesting that this page takes so long to load even when there aren't any new builds to be merged into the schema. So I'm curious what's causing that...

**Comment by czue** [comment]
re: the overlapping page load issue you could use some of @gcapalbo's [locking framework](https://github.com/dimagi/dimagi-utils/blob/master/dimagi/utils/couch/__init__.py#L40) but that might be overkill

**Comment by czue** [comment]
(no blockers on this one so merged) @NoahCarnahan - possible the page load issue is because of the saved schema stuff that hasn't been implemented yet?

**Comment by gcapalbo** [comment]
re: the locking, more recently i've been favoring the `CriticalSection` for all my locking needs: https://github.com/dimagi/dimagi-utils/blob/0db2b86d2e632994cb000e742cb30dd28f993467/dimagi/utils/couch/__init__.py#L309

it's a very lightweight way to make sure two threads don't produce conflicts, just make sure you choose the timeouts appropriately

**Comment by czue** [comment]
ah nice, that's what i was looking for.

**Comment by NoahCarnahan** [comment]
Cool, I'll keep `CriticalSection` in mind

**Pull request merged**
