### PR TITLE
Downgrade Information Pop Up 

### PR DESCRIPTION
**Pull request by orangejenny**
https://manage.dimagi.com/default.asp?265868

@sheelio 

HQ
screen shot 2017-11-22 at 2 41 53 pm

Email
screen shot 2017-11-22 at 2 43 06 pm

@calellowitz / @nickpell

### CODE REVIEW

**Comment by nickpell** [comment]
"CommCare makes me sad" - lol

**Review by nickpell — APPROVED** [review]

**Comment by sheelio** [comment]
@orangejenny 
Based on the email thread, can we change the email address that receives this to growth@dimagi.com

**Comment by orangejenny** [comment]
@sheelio Updated email address. Are you happy with the copy? Couldn't tell from the email thread.

Note to self, this now depends on https://github.com/dimagi/commcare-hq/pull/18704 and https://github.com/dimagi/commcarehq-ansible/pull/1079

**Comment by sheelio** [comment]
Copy is ok - no actionable changes based on the email discussion.

**Comment by nickpell** [comment]
@orangejenny localsettings have been updated on all environments, so no longer blocking on that.

**Comment by orangejenny** [comment]
@nickpell Awesome, thanks for letting me know.

**Comment by orangejenny** [comment]
@nickpell Added a commit - wasn't working when user was *not* downgrading.

**Review by nickpell — APPROVED** [review]

**Comment by nickpell** [comment]
Last commit shouldn't have test coverage, so feel free to merge

**Comment by orangejenny** [comment]
@nickpell good point

**Pull request merged**
