### PR TITLE
Apply banner to dashboard

### PR DESCRIPTION
**Pull request by Rohit25negi**
Showing alert banner to dashboard also.
https://dimagi-dev.atlassian.net/browse/ICDS-463

### CODE REVIEW

**Comment by orangejenny** [comment]
It looks like the `alert-maintenance` class isn't available on the ICDS dashboard, which only has bootstrap stylesheets, not HQ's css. What does this look like?

**Comment by orangejenny** [comment]
I experimented with this on india. With the current code, it looks like this:
Screen Shot 2019-04-03 at 10 10 02 AM

If I manually apply the [.alert-maintenance styles](https://github.com/dimagi/commcare-hq/blob/18716540d3a20f257f0117fd042a0abb2874727e/corehq/apps/hqwebapp/static/hqwebapp/less/_hq/alerts.less#L14-L20), it looks like this:
Screen Shot 2019-04-03 at 10 12 22 AM

Which looks fine, but it doesn't work with the dashboard scrolling behavior:
Screen Shot 2019-04-03 at 10 12 34 AM

**Comment by Rohit25negi** [comment]
This code shows the banner to the icds dashboard. But It should be deployed until the style thing is fixed. With the current style  program summary and filter thing is being hidden which should not be.

**Comment by Rohit25negi** [comment]
fixed

**Pull request closed without merging**
