### PR TITLE
add jquery-ui-1.8.23-legacy to bower

### PR DESCRIPTION
**Pull request by dannyroberts**
and upgrade from 1.8.16 (patch level upgrades should be safe)

### CODE REVIEW

**Comment by biyeun** [comment]
awesome sauce :+1:

**Comment by benrudolph** [comment]
nice

**Comment by dannyroberts** [comment]
Thanks for the resolution @esoergel!

**Comment by dannyroberts** [comment]
@biyeun you incorporated this change into your recent big bootstrap update PR, right? If so can you go ahead and close this?

**Pull request closed without merging**
