### PR TITLE
Direct ccz download

### PR DESCRIPTION
**Pull request by esoergel**
Add a view to directly download the latest ccz for an application.  Also add a JSON view listing all the applications on a domain (name, version, id, and ccz download link).

Both views currently require that the user be logged in to the domain.  @ctsims let me know if that doesn't work for you and we can talk about options.

Pinging @snopoke as he did recent work on this and might have thoughts about the implementation.
@proteusvacuum @emord

### CODE REVIEW

**Comment by proteusvacuum** [comment]
:+1: will wait for others to weigh in before merging, but seems like a reasonable approach to me.

**Comment by snopoke** [comment]
Looks reasonable. Assume we don't want to include builds?

**Comment by esoergel** [comment]
Figured we could easily enough add builds later if there's a want.  Probably in the form of an optional GET param `build=117` which otherwise defaults to the latest.

**Comment by ctsims** [comment]
You're a champ!

We can see how the login stuff fares WRT the app list, but the concept
totally makes sense (Don't wanna dump domain data without it).

So excited, this is gonna kick ass.

-Clayton

**Comment by proteusvacuum** [comment]
:fireworks:

**Comment by ctsims** [comment]
Let me know when this is on staging so I can test 'er out!

**Pull request merged**
