### PR TITLE
move indirect models.py imports out of __init__.py

### PR DESCRIPTION
**Pull request by nickpell**
@proteusvacuum 

Needed for django 1.9

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Hey, this change is causing the New "Register Patient Repeater" page to complain with 
```
KeyError: <class 'custom.enikshay.integrations.ninetyninedots.repeaters.NinetyNineDotsRegisterPatientRepeater'>
```

**Comment by nickpell** [comment]
@proteusvacuum Is there another place we can put this?

**Comment by proteusvacuum** [comment]
what is the requirement? just not have anything in `__init__.py`?

**Comment by nickpell** [comment]
There can't be any imports of ```models.py``` in ```__init__.py```.  That's both direct and indirect imports.

**Comment by proteusvacuum** [comment]
@nickpell I updated this. The `enikshay` app is never loaded in settings (because there is nothing there), so that code was never getting run.

**Comment by nickpell** [comment]
Great, thanks!

**Pull request merged**
