### PR TITLE
Fix CouchDB case action reconciliation

### PR DESCRIPTION
**Pull request by emord**
https://dimagi-dev.atlassian.net/browse/HI-359

Previously the check for whether or not we needed to reconcile case actions only looked at server_date, but the reconciliation strategy is actually much more complex https://github.com/dimagi/commcare-hq/blob/a500f078e8bc061678c53ebac3d19091831d2521/corehq/form_processor/backends/couch/update_strategy.py#L394-L429

https://github.com/dimagi/commcare-hq/blob/a500f078e8bc061678c53ebac3d19091831d2521/corehq/form_processor/backends/couch/update_strategy.py#L419 sneaky indeed

### CODE REVIEW

**Review by mkangia — COMMENTED** [review]
Thank you for fixing this @emord . I dont have good context on this so i would defer to @snopoke for review on this.

**Review by snopoke — APPROVED** [review]
👍 this is the fix I suggested in the ticket

**Comment by emord** [comment]
Not 100% confident in the latest update. @snopoke let me know if that removal makes sense

**Review by millerdev — APPROVED** [review]

**Comment by snopoke** [comment]
Looks good, I agree with the test changes.

**Pull request merged**
