### PR TITLE
log errors in build_incentive_files

### PR DESCRIPTION
**Pull request by nickpell**
https://sentry.io/organizations/dimagi/issues/1108906569/?project=136860

```build_incentive_files``` failed on india, but didn't log a proper error because the celery error processing crashed due to what looks like an exception message in bytes.  I'm adding logging to figure out what's going on, and will test manually on india.

Recommend ```?w=1```

### CODE REVIEW

**Comment by nickpell** [comment]
@dimagi/py3

**Review by calellowitz — APPROVED** [review]
This runs once per month. Are you planning on running it manually to test?

**Comment by nickpell** [comment]
Yeah, I'll run ```build_incentive_report``` manually to reproduce the issue.

**Comment by nickpell** [comment]
closing in favor of https://github.com/dimagi/commcare-hq/pull/24826

**Pull request closed without merging**
