### PR TITLE
Case API v0.6: Allow creating or updating indices by external ID

### PR DESCRIPTION
**Pull request by esoergel**
## Product Description
https://dimagi-dev.atlassian.net/browse/USH-2097
Allow creating or updating indices by external ID in the v0.6 Case API

## Technical Summary
This is pretty straightforward - the client must specify one of the valid ID fields, then we must do an "enrich" step where we transform that to an actual ID if necessary.  I already did something like this for "temporary_id" in the bulk upload, so it was an easy enough extension to support external ID with the aid of a lookup.

Would love to do that lookup in bulk, but I'm not sure how.

## Feature Flag
Enable the v0.6 Case API

### Safety story
I used TDD, and the feature isn't released yet anyways

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
> Would love to do that lookup in bulk, but I'm not sure how.

You could do this in 2 ways:

1. Write a SQL function and pl_proxy function to do the query in parallel over all the DB shards e.g.
    * [get_cases_by_id (PlProxy)](https://github.com/dimagi/commcare-hq/blob/163b8074f1a54f5eb02790de4f536c2c3b5cabcd/corehq/sql_proxy_accessors/sql_templates/get_cases_by_id.sql)
        * (in your case you would use `RUN ON ALL;`)
    * [get_cases_by_id (SQL)](https://github.com/dimagi/commcare-hq/blob/b927357119edb2f92fe02cd3257434586f06f14d/corehq/sql_accessors/sql_templates/get_cases_by_id.sql)

2. Run the query iteratively

```python
for db_name in get_db_aliases_for_partitioned_query():
    yield from CommCareCase.objects.using(db_name).filter(domain=domain, external_id__in=ids)
```

**Comment by snopoke** [comment]
@esoergel it would also be useful to be able to update a case based on the external ID (not just use it for linking indices). Is that being tracked separately?

**Comment by snopoke** [comment]
> @esoergel it would also be useful to be able to update a case based on the external ID (not just use it for linking indices). Is that being tracked separately?

Covered by this task https://dimagi-dev.atlassian.net/browse/USH-2096

**Comment by esoergel** [comment]
Thanks Simon, I should've remembered that approach.  Just updated that call to be in bulk.

**Review by snopoke — APPROVED** [review]

**Pull request merged**
