### PR TITLE
refactor SubmissionPost.run

### PR DESCRIPTION
**Pull request by snopoke**
every time I look at this method I want to change it. I think this is an improvement but open to feedback.
@benrudolph 

cc @biyeun 

can review CBC (:blowfish: / :blowfish:)

### CODE REVIEW

**Comment by benrudolph** [comment]
looking solid, lgtm once tests pass

**Comment by benrudolph** [comment]
this should fix up tests. gonna work off this branch

**Comment by snopoke** [comment]
Thanks for the fixups

**Comment by czue** [comment]
:walking: :walking: :runner: :runner:

**Pull request merged**
