### PR TITLE
run tests without ICDS code

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Comment by snopoke** [comment]
Build now passes without ICDS code: https://travis-ci.org/github/dimagi/commcare-hq/builds/723763736

**Comment by millerdev** [comment]
There's still a test failing on the most recent commit in this PR. I don't see where the build you linked came from.

**Comment by snopoke** [comment]
@millerdev I forgot the ICDS JS tests are still broken. I've removed them. The build I liked came from this commit which was the last one before I added back the ICDS test to Travis. So this build ran without the ICDS code: https://github.com/dimagi/commcare-hq/pull/28379/commits/a4b62228903a1b7de0372adbd0624396c54b1bd2

**Review by millerdev — APPROVED** [review]
Yay! :tada:

**Pull request merged**
