### PR TITLE
Fix shared exports showing up when marked as private

### PR DESCRIPTION
**Pull request by SmittieC**
No ticket

## Product Description

Fix: For projects with shared exports, when an export is marked as **private**, other users are still able to see it.

## Technical Summary

In the code change, the variable `e` is an export, but of type `dict`. `hasattr(e, 'owner_id')` returned `False`, even though the `owner_id` is in the dictionary (See [this](https://stackoverflow.com/questions/10724766/pythons-hasattr-on-list-values-of-dictionaries-always-returns-false#:~:text=hasattr%20does%20not%20test%20for%20members%20of%20a%20dictionary.%20Use%20the%20in%20operator%20instead%2C%20or%20the%20.has_key%20method%3A)). It looks like the variable `e` will always be a dictionary, so my update fixes this.

## Feature Flag

None

### Safety story

- Local testing

### QA Plan

[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-5371)

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by kaapstorm — COMMENTED** [review]
Nice.

What do you think of pulling `def _can_view(export, user_id)` out from inside `get_exports_page()`, and writing a test for it?

Not only would it be a "failed before, passes now" kind of test, but it could also make it clearer that `export` is a dict.

**Comment by SmittieC** [comment]
> 

I think that is a good idea

**Comment by SmittieC** [comment]
@kaapstorm QA passed this change. There's a separate small change (not from this PR) that didn't pass yet, but that is already in master now and is being tested. It was just a name change, so not a blocker

**Review by kaapstorm — APPROVED** [review]
Nice!

**Comment by kaapstorm** [comment]
(btw, any changes that Product / Marketing would not be interested in announcing, you can add the label "product/invisible", so they know they can skip this PR.)

**Pull request merged**
