### PR TITLE
Escaped user-submitted field names on forms

### PR DESCRIPTION
**Pull request by mjriley**
## Summary
This is a fix for [QA-2867](https://dimagi-dev.atlassian.net/browse/QA-2867) and [QA-2869](https://dimagi-dev.atlassian.net/browse/QA-2869), and any other places where custom data fields are used. The label for the field is user-supplied data, and currently undergoes no modifications before being presented to the user, which allows an XSS attack. This fix simply escapes the label before it is presented.

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

I would like to add tests to this area, but currently do not have time. I will circle back later: [SAAS-12060](https://dimagi-dev.atlassian.net/browse/SAAS-12060)

### QA Plan

No QA required.

### Safety story

Local testing was done to verify that the changes were safe and fix the associated issues. As far as I can tell, the `label` property is only used as a display property -- it does not affect how the data is saved or loaded. In theory, errors would be limited to display only.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Should the `choices` get the same treatment, or are they already handled properly?

**Comment by mjriley** [comment]
Choices seem to be handled correctly -- when I put in HTML into those elements, they were escaped appropriately

**Review by AmitPhulera — APPROVED** [review]
💯

**Review by dannyroberts — APPROVED** [review]
I'm kind of curious what makes it escape choices but not label. Let's not block the PR on it, but any insight on what's going on there?

**Pull request merged**
