### PR TITLE
Move ICDS code to its own repo

### PR DESCRIPTION
**Pull request by snopoke**
(redo of https://github.com/dimagi/commcare-hq/pull/28216)

New home of ICDS code: https://github.com/dimagi/commcare-icds
Changes:

* Delete `custom/icds`
* Delete `custom/icds_reports`
* Delete `custom/__init__.py` (to make it into a namespace package)
* Update `.travis.yml`
* update `nose.py` to make tests work

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
:tada:

**Review by millerdev — APPROVED** [review]

**Comment by snopoke** [comment]
Build finally passed and ran all the ICDS tests - now just waiting on QA

**Comment by millerdev** [comment]
Unrelated to the other issue, I ran across an error while trying to run tests locallly:
```
======================================================================
ERROR: nose.failure:Failure.runTest
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
  File "custom/aaa/tests/test_aggregations.py", line 18, in <module>
    from custom.icds_reports.tests.agg_tests import CSVTestCase
ImportError: cannot import name 'CSVTestCase' from 'custom.icds_reports.tests.agg_tests' (unknown location)
```
Looks like `custom.aaa` tests have dependencies on `custom.icds_reports`. Wonder how the build passed on this PR?

**Comment by dannyroberts** [comment]
After deploying this to india and production, websockets are 500ing across the board, and I see the error message in the `websockets.log` on the proxies https://sentry.io/organizations/dimagi/issues/1821983091/?cursor=0%3A100%3A0&project=136860&statsPeriod=14d. The timing on staging matches when this was first deployed to staging. https://stackoverflow.com/questions/28205264/django-app-improperly-configured-the-app-module-has-multiple-filesystem-locati implies it can happen when you delete a `__init__.py`. My working hypothesis is that websockets issue is caused by that error, which is caused by
> * Delete custom/__init__.py (to make it into a namespace package)

**Comment by dannyroberts** [comment]
I found I could fix the error by adding `custom/ccqa/__init__.py`. I didn't want to add back `custom/__init__.py` (which I also believe would have fixed it) because that seems to be intentional and necessary for allowing `custom.icds` to be defined in another repo.

**Pull request merged**
