### PR TITLE
remove app_manager/partials/b3/supported-languages.html

### PR DESCRIPTION
**Pull request by dannyroberts**
and merge the few relevant changes into partials/supported-languages.html

@biyeun cc: @kaapstorm

### CODE REVIEW

**Comment by dannyroberts** [comment]
@orangejenny since no one's bitten yet.

**Comment by dannyroberts** [comment]
:white_check_mark:

**Comment by biyeun** [comment]
yay, THANK YOU

**Comment by dannyroberts** [comment]
:) My distinct pleasure

**Pull request merged**
