### PR TITLE
Combine multimedia feature flags

### PR DESCRIPTION
**Pull request by orangejenny**
Give the ICDS team one fewer feature flag to turn on. The BULK_UPDATE_MULTIMEDIA_PATHS flag has grown to include a couple of translations enhancements for ICDS; I think validating app translations falls into this bucket.

Verified that no one is using this flag on prod, and everyone using it on india is on ICDS.

@mkangia / @millerdev

### CODE REVIEW

**Review by mkangia — COMMENTED** [review]
Can this be clubbed with `APP_TRANSLATIONS_WITH_TRANSIFEX` instead? People managing `APP_TRANSLATIONS_WITH_TRANSIFEX` would be the ones validating. Plus `update multimedia paths` would not be intuitive with validating text app translations.

**Comment by orangejenny** [comment]
> People managing APP_TRANSLATIONS_WITH_TRANSIFEX would be the ones validating.

My long-term thought is that the validation might be useful to projects besides ICDS, who are managing a lot of multimedia/languages but not using transifex.

**Comment by mkangia** [comment]
Agree on the future but i think it's better to use the other FF for now considering the intent to reduce FFs. Plus this changes the namespace from user to domain which might not be desirable.

**Comment by orangejenny** [comment]
Hrm...I'm not quite convinced, and you & I disagreeing makes me think this PR might introduce confusion rather than reducing it. The team didn't directly ask for it, so I think it's better to just close this one out.

**Pull request closed without merging**
