### PR TITLE
Memoize new

### PR DESCRIPTION
**Pull request by snopoke**
reverts https://github.com/dimagi/commcare-hq/pull/9329 in favour of a different approach.

Dependant on https://github.com/dimagi/dimagi-utils/pull/335

@dannyroberts @benrudolph

### CODE REVIEW

**Comment by dannyroberts** [comment]
Oh, wow, this looks great! Didn't realize how much of a headache the workaround was until looking at all the code you could delete :)

**Comment by dannyroberts** [comment]
:tada: thanks for the follow up

**Comment by dannyroberts** [comment]
Does this also let you clean up https://github.com/dimagi/commcare-hq/blob/d01443156a2500e1fd5c076f03ffac780e68fcaf/corehq/form_processor/backends/sql/dbaccessors.py#L47? I remember seeing that in conversation on a PR and thinking it was related

**Comment by snopoke** [comment]
Yup, I'll revisit that again.

On 1 December 2015 at 20:21, Daniel Roberts <notifications@github.com>
wrote:

> Does this also let you clean up
> https://github.com/dimagi/commcare-hq/blob/d01443156a2500e1fd5c076f03ffac780e68fcaf/corehq/form_processor/backends/sql/dbaccessors.py#L47?
> I remember seeing that in conversation on a PR and thinking it was related
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/9341#issuecomment-161053762>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Pull request merged**
