### PR TITLE
ICDS Tests

### PR DESCRIPTION
**Pull request by kkrampa**

### CODE REVIEW

**Comment by kkrampa** [comment]
@emord

**Comment by kkrampa** [comment]
Passed locally but not on travis.

**Comment by kkrampa** [comment]
@emord I think it's ready to initial review. I will try to fix tests on travis later.

**Comment by emord** [comment]
@kkrampa can you merge master again? after that I think this is good to go

**Comment by kkrampa** [comment]
@emord Done :white_check_mark:

**Pull request merged**
