### PR TITLE
Add distinct on to reports

### PR DESCRIPTION
**Pull request by mkangia**
[Ticket](https://dimagi-dev.atlassian.net/browse/ICDS-1062)
Need to add support to provide distinct on clause to reports for some UCR fixes

##### SUMMARY
This PR makes it possible to add `DISTINCT ON` clause to a report query.
Related Change to SQL Agg is https://github.com/dimagi/sql-agg/pull/66/files

##### FEATURE FLAG
`USER_CONFIGURABLE_REPORTS`

##### PRODUCT DESCRIPTION
On UI when creating report configurations, one can add columns for distinct clause in SQL query

@AndreaMKing5 this wont change anything in the already present reports. 
It's just an additional configuration to set on a report which can be set, and then revert to old configuration if it does not work as expected.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Review by czue — APPROVED** [review]
Nice! Can you also add some basic documentation for this?

**Review by orangejenny — COMMENTED** [review]
Looks good once you re-run make requirements.

**Review by orangejenny — APPROVED** [review]

**Comment by mkangia** [comment]
✔️

**Comment by AndreaMKing5** [comment]
+1 on adding a reference to this in confluence docs, but otherwise seems great!

**Comment by mkangia** [comment]
thanks @AndreaMKing5 , added in https://github.com/dimagi/commcare-hq/pull/26984

**Comment by czue** [comment]
> added in #26984

@mkangia thanks for documenting the `SqlData` class. Though I think it'd be good to add an example of how to use it in a UCR report config, because it's not really clear at all from those docs how a report author might take advantage of it.

**Comment by mkangia** [comment]
Sure @czue ,
can you link me to where we have added examples for such configs?

**Comment by czue** [comment]
@mkangia I imagine the simplest place would be alongside the other report config properties in [this section](https://commcare-hq.readthedocs.io/ucr.html#report-configurations)

**Pull request merged**
