### PR TITLE
Revert "Merge pull request #20743 from dimagi/sr-batch-asyncindicators"

### PR DESCRIPTION
**Pull request by emord**
This reverts commit 98cefc5193bd75d1557699c7befee3702ae14c0f, reversing
changes made to 15ef187315ac14a8156765e484570bf53e3066c7.

@sravfeyn I had to revert this due to https://sentry.io/dimagi/commcarehq/issues/580399479/?referrer=slack

It looks like the queueing only groups by doc_type not by the data source's id. This means that when a ccs_record and a child_health case were in the same task, there was an exception when trying to insert because it attempted to insert rows of null values

### CODE REVIEW

**Comment by emord** [comment]
hotfixed to icds

**Comment by sravfeyn** [comment]
Thanks Emord, the reason this failed is because the task tries to have SQLalchemy save empty set of rows. I made a [fix here with a test case](https://github.com/dimagi/commcare-hq/pull/20949/files#diff-6b6321d8e680daed5179bb3e097f3ca8R102). (I did add this for ES but forgot to add this to SQL)

**Comment by emord** [comment]
merging because other PR's tests are failing

**Comment by sravfeyn** [comment]
Revert of this https://github.com/dimagi/commcare-hq/pull/20964

**Pull request merged**
