### PR TITLE
Updated TB notification report

### PR DESCRIPTION
**Pull request by kkrampa**

### CODE REVIEW

**Review by czue — APPROVED** [review]

**Comment by czue** [comment]
build fail looks real this time:
```
======================================================================
ERROR: test_production_config (corehq.apps.userreports.tests.test_static_data_sources.TestStaticDataSource)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vendor/lib/python2.7/site-packages/mock.py", line 1224, in patched
    return func(*args, **keywargs)
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/tests/test_static_data_sources.py", line 53, in test_production_config
    data_source.validate()
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/models.py", line 264, in validate
    raise BadSpecError(_('Report contains duplicate column ids: {}').format(', '.join(set(columns))))
BadSpecError: Report contains duplicate column ids: endofcp_test_requested_date, result_of_test
----------------------------------------------------------------------
```

**Comment by kkrampa** [comment]
@czue This is first part of work. I'm still blocked by #14183
Are there any updates in that PR?

**Comment by czue** [comment]
merged that PR - thanks for the ping!

**Comment by kkrampa** [comment]
@czue :white_check_mark:

**Pull request merged**
