### PR TITLE
fix intrahealth queries using the IN filter

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?185918

### CODE REVIEW

**Comment by nickpell** [comment]
using these commits for hotfix, leaving PR open for review.

**Comment by czue** [comment]
code looks good. i'm probably missing something obvious, but why do you need to use `IN` for a one-element tuple?

**Comment by kaapstorm** [comment]
I'm not familiar with this code, but I'd expect that should be
```
        if 'archived_locations' in self.config:
            filters.append(NOT(IN('location_id', self.config['archived_locations'])))
```
where `self.config['archived_locations']` is a list or a tuple.

**Comment by kaapstorm** [comment]
(e.g. [line 50][1] uses an `EQ` filter instead of `IN`, but also curiously ignores the value of `self.config['region_id']`: 
```
        if 'region_id' in self.config:
            filters.append(EQ("region_id", "region_id"))
```
@lwyszomi , I know it was a while ago, but do you remember whether this was intentional?)

  [1]: https://github.com/dimagi/commcare-hq/blob/master/custom/intrahealth/sqldata.py#L50-51

**Comment by kaapstorm** [comment]
Just thinking ... Is `self.config` being passed as SQL parameters to the query? Then this code might make sense as it was, and the bug would be that `self.config['archived_locations']` has not been assigned a list or a tuple.

**Comment by snopoke** [comment]
It does seem odd to use `IN` with single element tuples.

**Comment by kaapstorm** [comment]
It seems `self.config` *is* being passed as SQL query params, so the string should not be a tuple; It's the name of a dictionary key. It ultimately gets used in [sqlagg/base.py:183](https://github.com/dimagi/sql-agg/blob/master/sqlagg/base.py#L183)

The bug is probably a config error; `self.config['archived_locations']` needs to be a list/tuple.

**Comment by lwyszomi** [comment]
@kaapstorm If i good remember, this was intentional.

**Comment by kaapstorm** [comment]
:+1: Thanks.

**Comment by czue** [comment]
@lwyszomi if this was intentional can you clarify why it uses an `IN` query instead of just checking equality?

**Comment by lwyszomi** [comment]
@czue 
If we talking about ```archived_location``` we using ```IN``` because we want exclude all records for archived locations.

But when we talking about ```region_id```, currently we using ```EQ```  operator, because from UI we can only choose one region.

**Comment by nickpell** [comment]
if ```self.config['archived_locations']``` is a tuple, then it sounds like we need to pass bind parameters for each tuple value like so: https://github.com/dimagi/commcare-hq/pull/8839/files#diff-935c3a3c22812028e0e863ed731d8170R125

**Comment by nickpell** [comment]
going to close until all reports are fixed

**Comment by kaapstorm** [comment]
What if you tried to solve this in a more generic way? Something like ...
```diff
diff --git a/corehq/apps/reports/api.py b/corehq/apps/reports/api.py
index b9141be..e3e54c9 100644
--- a/corehq/apps/reports/api.py
+++ b/corehq/apps/reports/api.py
@@ -43,3 +43,12 @@ class ReportDataSource(object):
 
     def get_total_records(self):
         return 0
+
+    def make_param_list(self, param_name):
+        param_list = []
+        for i, param in self.config[param_name]:
+            param_name_i = '{}_{}'.format(param_name, i)
+            self.config[param_name_i] = param
+            param_list.append(param_name_i)
+        del self.config[param_name]
+        return param_list
diff --git a/custom/intrahealth/sqldata.py b/custom/intrahealth/sqldata.py
index 62f42c0..8963914 100644
--- a/custom/intrahealth/sqldata.py
+++ b/custom/intrahealth/sqldata.py
@@ -93,7 +93,8 @@ class ConventureData(BaseSqlData):
         filters = super(ConventureData, self).filters
         filters.append(AND([GTE('real_date_repeat', "strsd"), LTE('real_date_repeat', "stred")]))
         if 'archived_locations' in self.config:
-            filters.append(NOT(IN('location_id', 'archived_locations')))
+            params = self.make_param_list('archived_locations')
+            filters.append(NOT(IN('location_id', params)))
         return filters[1:]
 
     @property
```

**Comment by nickpell** [comment]
@kaapstorm I'm trying something similar (overriding ```filter_values```)

**Pull request closed without merging**
