### PR TITLE
[ICDS Dashboard] updated the migration_status in ccs_record_monthly

### PR DESCRIPTION
**Pull request by ShubhamBansal1997**
##### SUMMARY

Instead of person_cases, migration_status is now coming from the migration_form

### CODE REVIEW

**Comment by Rohit25negi** [comment]
@ShubhamBansal1997  I see two PRS with same name 
this and https://github.com/dimagi/commcare-hq/pull/26380. which one to review?

**Comment by ShubhamBansal1997** [comment]
@Rohit25negi This one is abandoned due to change in the spec

**Comment by Rohit25negi** [comment]
this has been taken further here: https://github.com/dimagi/commcare-hq/pull/26736

**Comment by Rohit25negi** [comment]
Closing this out as this is outdated.

**Pull request closed without merging**
