### PR TITLE
bump jsonobject-couchdbkit to 0.7.3.0 + nasty workaround

### PR DESCRIPTION
**Pull request by dannyroberts**
@calellowitz

### CODE REVIEW

**Comment by czue** [comment]
Looks like tests might need a --force or --noinput type of argument.
```
Uninstalling jsonobject-0.7.1:
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/DESCRIPTION.rst
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/INSTALLER
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/METADATA
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/RECORD
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/WHEEL
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/metadata.json
  /vendor/lib/python2.7/site-packages/jsonobject-0.7.1.dist-info/top_level.txt
  /vendor/lib/python2.7/site-packages/jsonobject/__init__.py
  /vendor/lib/python2.7/site-packages/jsonobject/__init__.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/api.py
  /vendor/lib/python2.7/site-packages/jsonobject/api.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/base.py
  /vendor/lib/python2.7/site-packages/jsonobject/base.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/base_properties.py
  /vendor/lib/python2.7/site-packages/jsonobject/base_properties.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/containers.py
  /vendor/lib/python2.7/site-packages/jsonobject/containers.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/exceptions.py
  /vendor/lib/python2.7/site-packages/jsonobject/exceptions.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/properties.py
  /vendor/lib/python2.7/site-packages/jsonobject/properties.pyc
  /vendor/lib/python2.7/site-packages/jsonobject/utils.py
  /vendor/lib/python2.7/site-packages/jsonobject/utils.pyc
Proceed (y/n)? Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 326, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 103, in remove
    response = ask('Proceed (y/n)? ', ('y', 'n'))
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 158, in ask
    response = input(message)
EOFError: EOF when reading a line
```

**Comment by dannyroberts** [comment]
@calellowitz just making sure you saw this. I think the fix is a simple strategically placed `--yes`

**Comment by calellowitz** [comment]
:white_check_mark:
@dannyroberts @czue

**Comment by dannyroberts** [comment]
:tada:

**Pull request merged**
