### PR TITLE
Style UCR CodeMirror some

### PR DESCRIPTION
**Pull request by esoergel**
Enable code folding, support autoresize as you type, and add a border so it looks more like a widget.  (Happy to backtrack if someone objects to any of these)
@czue @benrudolph

### CODE REVIEW

**Comment by esoergel** [comment]
One caveat with this is that it now won't go smaller than 3 lines, even when the field is only `[]`.  The demos on their website behave the same way, and I couldn't figure out a good way to make it collapse all the way down to one line without adding a handler to the `change` event, so I just left it like this.

**Comment by benrudolph** [comment]
screenshot? all sounds reasonable

**Comment by esoergel** [comment]
It doesn't look that different - only changes are the arrows for code folding, the minimum height, and the border
screenshot_2015-10-22_17-11-45

**Comment by czue** [comment]
neat

**Comment by czue** [comment]
played with this locally - looks good!

**Comment by NoahCarnahan** [comment]
This is way better, thanks @esoergel!

I've always just copy pasted from a real text editor because of the resizing issue and the lack of code folding. Hopefully I won't have to anymore :)

**Pull request merged**
