### PR TITLE
Split jQuery UI includes

### PR DESCRIPTION
**Pull request by orangejenny**
In the interest of reducing jQuery UI usage, at least reducing how often it conflicts with other libraries, include individual components instead of the entire monstrosity. It's a bunch more script requests, but I suspect we aren't actually using a lot of these (I can take a pass at figuring out which ones we aren't using).

Doesn't include jQuery effects.

@dimagi/js-team

### CODE REVIEW

**Comment by benrudolph** [comment]
what's the adv. here? more easily know what's on the page since jquery ui is kind of a black box?

**Comment by orangejenny** [comment]
Yeah, that's the main one: know what is & isn't on the page so we can be more confident about removing pieces. Removing pieces will also slim down the total amount of js on the page.

**Comment by dannyroberts** [comment]
This came up in the JS meeting today; when I first saw this PR I thought it would mean making N http requests for script files instead of one, but that's not the case because it's all in a compress block. With that in mind, after basic testing (just like that running compress works and no new JS errors on just like 1 page that uses this), this seems like a strict improvement.

**Comment by orangejenny** [comment]
As discussed, switched over to non-minified versions for the sake of source maps. Probably won't need them often, but might as well make them available.

**Comment by orangejenny** [comment]
Did some grepping & removed scripts we aren't using. This is ready to go.

**Pull request merged**
