### PR TITLE
add ability to know if advancedform needs access to parent case

### PR DESCRIPTION
**Pull request by mkangia**
## Summary

https://dimagi-dev.atlassian.net/browse/INDIV-10?focusedCommentId=138185

https://sentry.io/organizations/dimagi/issues/2257623181/?environment=production&project=136860&query=is%3Aunresolved+Error+processing+SMS&statsPeriod=14d

In order to support using `AdvancedForm`, the first blocker is to have a way for the form to know if it uses parent cases which is needed by sms workflow [here](https://github.com/dimagi/commcare-hq/blob/61df4fb439d3b969e3970b98e00a16e80716808d/corehq/apps/smsforms/app.py#L48)
This was originally added in 2015, https://github.com/dimagi/commcare-hq/pull/7638. Not sure if there will be more issues to support AdvancedForm past this point, but this was a small effort so thought of simply adding this first and then take it from there.

The change is applicable to sms workflows using keywords that initiate an AdvancedForm in the app and need a case preloaded. I believe there are no such workflows currently set on environments since its broken and this PR fixes it.

## Feature Flag

`APP_BUILDER_ADVANCED`

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Safety story

This workflow isn't in action since its not working anyway. So should be safe to rollout

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by mkangia** [comment]
also pinging @czue if you have inputs from context on the PR done earlier by Gio and would like to share thoughts.

**Review by snopoke — COMMENTED** [review]
I'm not convinced this will catch all the cases. Advanced forms also allow writing custom xpath to load cases or load cases based on fixture data. I think there are a lot of things that advanced modules can do that would break the assumptions for SMS forms.

**Comment by mkangia** [comment]
thanks @snopoke 

Based on suggestions, I updated to assume that this will always be true for advance forms. I did a force push for a cleaner history that wiped out old commit, adding here for reference, https://github.com/dimagi/commcare-hq/commit/61df4fb439d3b969e3970b98e00a16e80716808d.

**Review by snopoke — COMMENTED** [review]
@mkangia I looked for where `footprint` is referenced and I don't see any references to it. I know it's passed to formplayer in `additional_filters` but there are no usages of that in Formplayer either.

I suspect this was part of a legacy sync algorithm and was removed e.g. https://github.com/dimagi/commcare-hq/commit/92b7dfad56cc0cf64077cd2600ccbb2aece1efc6

**Comment by mkangia** [comment]
thanks @snopoke 
So we can remove it entirely! i will make a new PR for that one then.

**Comment by czue** [comment]
I don't have any extra information to assist on this, but agree with the conclusion you came to.

One higher-order concern is whether by attempting to support advanced forms we might get ourselves in a troublesome state down the line where people rely on other things that don't work and then we end up with a big unplanned support burden and/or scope creep? I.e. just wondering if the more practical solution is to explicitly fail hard and fast if you try to use an advanced module/form with SMS. (I have no perspective on how practical that is)

**Comment by mkangia** [comment]
Hey @czue 

> just wondering if the more practical solution is to explicitly fail hard and fast if you try to use an advanced module/form with SMS

So you are saying we should not support advanced module/form at all? It should be possible to find out if there are any sms workflows that are using advancedforms or not. The original request was to support(fix?) a followup (update a case) using advanced form which is not working. As of now this PR, looks like a bugfix rather than a feature change.


> One higher-order concern is whether by attempting to support advanced forms we might get ourselves in a troublesome state down the line where people rely on other things that don't work and then we end up with a big unplanned support burden and/or scope creep?

I can't say anything with full confidence here on how it would be since the overall feature is pretty old and this is the first time I am looking into it. 
Just want to add that sending details to formplayer is almost the last step in the workflow, which is failing here and I believe it was always meant to work but broke at some point. So i am positive about this working fine after this, at least from the perspective of communication from HQ to formplayer, and if it does, it will be a good value add.
Advance app building is itself behind a feature flag and is told, be to avoided if possible, so w.r.t support burden, it should be okay since 1) it wont be used much 2) it's behind a feature flag

Though, if it still looks worth taking a step back and not supporting advancedform is better, still open to that suggestion as well.

**Comment by snopoke** [comment]
Adding my 2c. I don't think there was ever any specific thought on making SMS forms work with Advanced Modules. I'm inclined to agree with @czue since I'm almost 100% sure that there are things you can do with Advanced Modules that would break sms forms. I'd be curious to know why they are using an Advanced Module there and whether a normal module wouldn't work.

In terms of this PR I would rather take the approach to remove the legacy checks from the SMS code instead of adding functions the Advanced Form.

**Comment by mkangia** [comment]
https://github.com/dimagi/commcare-hq/pull/29589

removed footprint, simply removes the redundant parameter. So should be okay to do irrespective of what we conclude here (which would be useful in decisions needed if there are still issues with advanced forms after removing footprint param)

**Comment by mkangia** [comment]
> I'd be curious to know why they are using an Advanced Module there and whether a normal module wouldn't work.

I will follow up on that.

**Comment by mkangia** [comment]
Closing to avoid confusions about this PR but still open to thoughts on previous comments.

**Comment by mkangia** [comment]
If anyone has context on that, (maybe @czue ?)
if that param is not used anymore, does that mean all cases are always loaded in casedb? I am not sure if that is even the right statement but what is the change in formplayer/HQ if that param is not used anymore or when/why the param became redundant.

**Comment by snopoke** [comment]
Formplayer used to use the normal restore endpoint but now uses the case_migrations restore endpoint for sms forms where the 'user' is a case.

**Comment by mkangia** [comment]
Happy to share that this resolved the blocker and advanced from worked well, as a follow up form to load/update case.

**Pull request closed without merging**
