### PR TITLE
Re-bucket restore case load metric

### PR DESCRIPTION
**Pull request by dannyroberts**
## Summary
I've found graphs such as https://app.datadoghq.com/dashboard/b5y-ujq-yaf?from_ts=1585585782688&fullscreen_section=overview&fullscreen_widget=7014445048885642&live=true&to_ts=1609255782688&tpl_var_baseline_domain=%2A&tpl_var_domain=%2A&fullscreen_start_ts=1585587347443&fullscreen_end_ts=1609257347443&fullscreen_paused=false to be limited in their usefulness because the range of buckets is both too granular and too short: we have too much information about whether it was 20 or 50 cases (which we don't care so much about) and not enough information about whether it was 11k, 90k or 250k cases.

This PR ~(1) switches from the 1, 2, 5, 10 exponential pattern to a 1, 3, 10 exponential pattern and (2)~ extends the range so that the largest bucket is "over_1000000"—high enough that we're quite sure we never hit it, which means if we _do_ hit it that's extremely useful information.

This PR has the annoyance that any change in metrics does, namely that we will have to adjust our graphs to match the new boundaries, and even then there will forever be a quantum change in the way the data looks. I think that's mitigated by the fact that ~the 10, 100, 1000, etc~ *most of the* boundaries remain the same which provides some continuity in the graphs.

@calellowitz I'm curious to hear your thoughts

See also https://github.com/dimagi/commcare-hq/pull/28937 which is somewhat related but not interdependent.

## Feature Flag
None

## Product Description
None

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### QA Plan

QA is not needed

### Safety story
This is a very minor change that will either not affect anyone or fail so catastrophically (i.e. syntax error) that it would be caught by tests.

### Rollback instructions

This can be safely rolled back; the only consideration is that it would switch back the way the graphs in datadog look, a very minor thing.

### CODE REVIEW

**Comment by gherceg** [comment]
>limited in their usefulness because the range of buckets is both too granular and too short

@dannyroberts I understand how this solves the length issue, but am not sold on the granularity issue. You do explain why you still want some level of granularity:
>not enough information about whether it was 11k, 90k or 250k cases

but I would appreciate hearing the thought process behind choosing the 1, 3, 10 pattern and not something more coarse like 1, 10, 100.

**Comment by dannyroberts** [comment]
I think 1, 10, 100 could be fine, but I didn't want to jump straight there. There's no like firm calculation I did to say that would be too spread out, I just started with the current granularity (exponential with two stops between 1 and 10) and took it down one notch (1 stop between 1 and 10).

In general when I want a roughly exponential pattern I tend to choose from
1. 1, 10 (10^n)
2. 1, 3, 10 (roughly 10^(n/2))
3. 1, 2, 5, 10 (roughly 10^(n/3))
4. 1, 2, 3, 6, 10 (roughly 10^(n/4), I rarely use this)

and go up or down a notch at a time. But yeah none of that is a real answer. If this still feels too granular after collecting some data it'll be easy to switch to 1, 10.

**Review by gherceg — APPROVED** [review]

**Review by calellowitz — COMMENTED** [review]
As you described in the description, I fear this not granular enough at the higher levels. How do you feel about keeping the previous spacing but cutting the ones under 100 and adding a comparable amount to the top. So `[100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]` and perhaps further if you want the granularity about 100k (although hopefully that won't be as necessary soon as USH continues dropping their case loads. I think the different blocks in the 10s of thousands is nice, but agree that we probably didnt need that granularity at the low end. 30k and 100k are pretty far apart, as are 3k and 10k. Plus this will keep it more continuous with past data which will be nice as USH looks to see how effective their casedb reductions are.

**Comment by dannyroberts** [comment]
OK sure, I can do that

**Comment by dannyroberts** [comment]
How's that?

**Review by calellowitz — APPROVED** [review]
Looks great! thanks danny

**Pull request merged**
