### PR TITLE
pass callable to url instead of string

### PR DESCRIPTION
**Pull request by nickpell**
Remove a ton of `RemovedInDjango110Warning`s

@sravfeyn @dannyroberts

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 15 errors:

* corehq/apps/app_manager/urls.py, line 24 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/urls.py, line 26 - E501 line too long (127 > 115 characters)
* corehq/apps/app_manager/urls.py, line 27 - E501 line too long (121 > 115 characters)
* corehq/apps/domain/urls.py, line 93 - E501 line too long (131 > 115 characters)
* corehq/apps/domain/urls.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/apps/fixtures/urls.py, line 20 - E501 line too long (117 > 115 characters)
* corehq/apps/receiverwrapper/urls.py, line 11 - E241 multiple spaces after ','
* corehq/apps/reports/urls.py, line 107 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 111 - E501 line too long (127 > 115 characters)
* corehq/apps/reports/urls.py, line 113 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 114 - E501 line too long (134 > 115 characters)
* corehq/apps/sms/urls.py, line 42 - E501 line too long (124 > 115 characters)
* corehq/apps/users/urls.py, line 48 - E501 line too long (121 > 115 characters)
* custom/apps/crs_reports/urls.py, line 6 - E501 line too long (128 > 115 characters)
* custom/apps/crs_reports/urls.py, line 7 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* corehq/apps/app_manager/urls.py, line 24 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/urls.py, line 26 - E501 line too long (127 > 115 characters)
* corehq/apps/app_manager/urls.py, line 27 - E501 line too long (121 > 115 characters)
* corehq/apps/domain/urls.py, line 93 - E501 line too long (131 > 115 characters)
* corehq/apps/domain/urls.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/apps/fixtures/urls.py, line 20 - E501 line too long (117 > 115 characters)
* corehq/apps/receiverwrapper/urls.py, line 11 - E241 multiple spaces after ','
* corehq/apps/reports/urls.py, line 107 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 111 - E501 line too long (127 > 115 characters)
* corehq/apps/reports/urls.py, line 113 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 114 - E501 line too long (134 > 115 characters)
* corehq/apps/sms/urls.py, line 42 - E501 line too long (124 > 115 characters)
* corehq/apps/users/urls.py, line 48 - E501 line too long (121 > 115 characters)
* custom/apps/crs_reports/urls.py, line 6 - E501 line too long (128 > 115 characters)
* custom/apps/crs_reports/urls.py, line 7 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* corehq/apps/app_manager/urls.py, line 24 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/urls.py, line 26 - E501 line too long (127 > 115 characters)
* corehq/apps/app_manager/urls.py, line 27 - E501 line too long (121 > 115 characters)
* corehq/apps/domain/urls.py, line 93 - E501 line too long (131 > 115 characters)
* corehq/apps/domain/urls.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/apps/fixtures/urls.py, line 20 - E501 line too long (117 > 115 characters)
* corehq/apps/receiverwrapper/urls.py, line 11 - E241 multiple spaces after ','
* corehq/apps/reports/urls.py, line 107 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 111 - E501 line too long (127 > 115 characters)
* corehq/apps/reports/urls.py, line 113 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 114 - E501 line too long (134 > 115 characters)
* corehq/apps/sms/urls.py, line 42 - E501 line too long (124 > 115 characters)
* corehq/apps/users/urls.py, line 48 - E501 line too long (121 > 115 characters)
* custom/apps/crs_reports/urls.py, line 6 - E501 line too long (128 > 115 characters)
* custom/apps/crs_reports/urls.py, line 7 - E501 line too long (124 > 115 characters)

**Comment by dimagimon** [comment]
There are 15 errors:

* corehq/apps/app_manager/urls.py, line 24 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/urls.py, line 26 - E501 line too long (127 > 115 characters)
* corehq/apps/app_manager/urls.py, line 27 - E501 line too long (121 > 115 characters)
* corehq/apps/domain/urls.py, line 93 - E501 line too long (131 > 115 characters)
* corehq/apps/domain/urls.py, line 174 - E501 line too long (118 > 115 characters)
* corehq/apps/fixtures/urls.py, line 20 - E501 line too long (117 > 115 characters)
* corehq/apps/receiverwrapper/urls.py, line 11 - E241 multiple spaces after ','
* corehq/apps/reports/urls.py, line 107 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 111 - E501 line too long (127 > 115 characters)
* corehq/apps/reports/urls.py, line 113 - E501 line too long (119 > 115 characters)
* corehq/apps/reports/urls.py, line 114 - E501 line too long (134 > 115 characters)
* corehq/apps/sms/urls.py, line 42 - E501 line too long (124 > 115 characters)
* corehq/apps/users/urls.py, line 48 - E501 line too long (121 > 115 characters)
* custom/apps/crs_reports/urls.py, line 6 - E501 line too long (128 > 115 characters)
* custom/apps/crs_reports/urls.py, line 7 - E501 line too long (124 > 115 characters)

**Comment by nickpell** [comment]
https://github.com/dimagi/commcare-hq/pull/13222/commits/47df1a8757700ed8271cfcd1577d31cee0ed5c2b has me thinking that the upgrade process will be pretty labor intensive.  Seems like ```name=``` needs to be added to any ```url``` that is referenced via ```reverse```.  Smoothest workflow will probably be via small PRs.

**Pull request closed without merging**
