### PR TITLE
 Registration date in the exported list of mobile user

### PR DESCRIPTION
**Pull request by Rohit25negi**
1. added the prettified(existing format used) registration date in the exported list of mobile users

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
Can you `registered_on` to the allowed headers at the top of this file. That way a user can download and reupload without deleting this column. May also want to mark it read only, like the imei one. Looks good otherwise

**Comment by orangejenny** [comment]
Hi Rohit, can you add the fogbugz ticket link to the PR description?

**Comment by Rohit25negi** [comment]
Hey Jenny, Here is the ticket link:
https://manage.dimagi.com/default.asp?275878#1513039

**Comment by orangejenny** [comment]
@Rohit25negi cool, thanks. It's good to add those links to PRs in general (makes life easier in a few months when someone is trying to figure out how and why this code change was made).

**Comment by Rohit25negi** [comment]
@calellowitz I have made the changes requested.

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
