### PR TITLE
Don't change resource id, just version number

### PR DESCRIPTION
**Pull request by esoergel**
@emord @snopoke 
http://manage.dimagi.com/default.asp?144456
I tried this out on staging, and it appears to solve the issue.

### CODE REVIEW

**Comment by benrudolph** [comment]
@snopoke :)

**Comment by snopoke** [comment]
Nice, this looks right but a comment would probably be useful for future reference. Kicked the build.

**Comment by esoergel** [comment]
commented and build passed

**Comment by snopoke** [comment]
Just thought of this now but I think its worth writing a test case for this. (see https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/tests/test_media_suite.py#L8)

**Pull request merged**
