### PR TITLE
upgrade grunt-mocha to 1.0.0 & install npm packages in base docker image

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?222547
@NoahCarnahan 

grunt-mocha@1.0.0 depends on phantomjs@2.1.1 which gets pulled from github and not bitbucket. Hopefully this will make the build more reliable.

I'm still going to look into pre-installing it in the docker image.

### CODE REVIEW

**Comment by snopoke** [comment]
@emord

**Comment by NoahCarnahan** [comment]
Looks like it failed with a different PhantomJS error:
https://travis-ci.org/dimagi/commcare-hq/jobs/119508164

```
Running "mocha:app_manager#fields" (mocha) task
Testing: http://172.17.0.14:8000/mocha/app_manager/fields

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

Aborted due to warnings.


The command ".travis/matrix-script.sh" exited with 90.

Done. Your build exited with 1.
```

**Comment by snopoke** [comment]
baah - worked locally - will keep trying

**Comment by NoahCarnahan** [comment]
How did you test locally by the way? I spent some time on this ticket yesterday but put it aside after going down a rabbit whole trying to test the travis builds locally

**Comment by snopoke** [comment]
Oh I didn't test it in docker, just on my local machine. You can test stuff
in docker using `.travis/simulate.sh javascript`

**Comment by snopoke** [comment]
Killing this for now

**Pull request closed without merging**
