### PR TITLE
fail more gracefully when we can't convert percentages to numbers

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?174635

@nickpell @NoahCarnahan

### CODE REVIEW

**Comment by NoahCarnahan** [comment]
:+1:
Might be worth adding a test?

**Comment by czue** [comment]
can do (probably won't get to it till tomorrow). might push to merge first since this is breaking someone's report and i can do that later

**Comment by NoahCarnahan** [comment]
Sounds good.

**Comment by czue** [comment]
thanks - as promised: https://github.com/dimagi/commcare-hq/pull/7315

**Pull request merged**
