### PR TITLE
Revert "Kill old edit forms"

### PR DESCRIPTION
**Pull request by orangejenny**
Reverts dimagi/commcare-hq#21907

Resurrecting old edit forms while we work on some improvements to data cleaning.

@dannyroberts 
or @calellowitz since you reviewed dimagi/commcare-hq#21907

### CODE REVIEW

**Comment by orangejenny** [comment]
@snopoke fyi, old edit forms is back :(  Probably shouldn't merge https://github.com/dimagi/commcare-hq/pull/22057 just yet.

**Comment by orangejenny** [comment]
@nickpell Can this get into today's deploy?

**Comment by orangejenny** [comment]
@nickpell That's new and weird. Thanks for flagging.

**Comment by snopoke** [comment]
> @snopoke fyi, old edit forms is back  Probably shouldn't merge #22057 just yet.

OK thanks, #22057 just adds a soft assert FYI

**Pull request merged**
