### PR TITLE
Getting Started docs for DHIS2 Tracked Entities integration

### PR DESCRIPTION
**Pull request by kaapstorm**
##### SUMMARY
The intention of these docs is to dive into configuring a simple integration with DHIS2, forwarding CommCare cases as DHIS2 tracked entity instances, and sending other form data as DHIS2 data elements.

##### FEATURE FLAG
The documentation is publicly accessible, but the feature is enabled with the "DHIS2 integration" feature flag.

##### PRODUCT DESCRIPTION
"Getting Started" documentation with a starter configuration for a DHIS2 Tracked Entities integration with DHIS2's demo server.

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Review by millerdev — APPROVED** [review]
This is getting to be a big PR, and kinda hard to review. I did not read every change thoroughly. Are you planning to merge sometime soon?

**Comment by kaapstorm** [comment]
Oh! My bad! This PR is only supposed to be changes to a README file! I merged changes to the README from another branch, and clearly it brought a whole lot more in too.

I'll rebase.

**Comment by kaapstorm** [comment]
Squished!

This branch will be merged when DHIS2 Tracked Entity integration is through QA, and the science fiction in this PR becomes fact.

**Review by millerdev — APPROVED** [review]

**Comment by kaapstorm** [comment]
Closing this PR. It is incorporated into the rebased Tracked Entity integration PR #26995

**Pull request closed without merging**
