### PR TITLE
Removed completed couch to sql migration scripts

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary
This updates `PopulateSQLCommand` to show an error message if the migration management command can't be found, allowing us to delete those commands. The error instructs users to check out a specific older commit, a workflow that already exists for when someone tries to run the migration after the couch models have been deleted.

This also deletes the commands for completed migrations and makes some minor updates to the docs.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

There are some tests that run subclasses of `PopulateSQLCommand`.

### QA Plan

No QA.

### Safety story
This is a pretty minor change to a management command used mostly internally. Smoke tested locally.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by orangejenny** [comment]
Removed the high & medium risk labels.

**Comment by orangejenny** [comment]
Ugh, I forgot that these need to exist because they're referenced in django migrations:

```
  File "/mnt/commcare-hq-ro/corehq/apps/cloudcare/migrations/0002_sqlapplicationaccess.py", line 6, in <module>
    from corehq.apps.cloudcare.management.commands.populate_application_access import Command
ModuleNotFoundError: No module named 'corehq.apps.cloudcare.management'
```

I don't know of a way around that. Closing this. I'll submit the docs changes separately.

**Comment by snopoke** [comment]
@orangejenny is it necessary to keep that code in the migration? I think we can assume by now that any existing environments have run the migration and any new environments shouldn't need to. If that statement is correct then we can just remove the operations from the migration so that it becomes a no-op.

**Comment by orangejenny** [comment]
@snopoke That's a good point. I'm never certain how long to wait before being confident that any localhosters will have run the code, but most of these migrations were done a year ago, which seems like enough time.

**Comment by esoergel** [comment]
@orangejenny there are some guidelines around this [here](https://confluence.dimagi.com/display/internal/Announcing+changes+affecting+third+parties).  The gist of it is that [we expect third parties to deploy at least every two weeks](https://dimagi.github.io/commcare-cloud/system/maintenance-expectations.html).  It's a good idea to allow a generous grace period beyond that, but we need to be able to draw the line somewhere reasonable for us to progress on things like this.

**Comment by orangejenny** [comment]
@esoergel Awesome, I didn't realize we had formalized those expectations. Thank you.

**Pull request closed without merging**
