### PR TITLE
Base branch for getting back to 4 jobs on travis

### PR DESCRIPTION
**Pull request by dannyroberts**
If you're working on getting back to 4 jobs on travis, set this to the base branch to have tests get run.

### CODE REVIEW

**Comment by dannyroberts** [comment]
oops i misnamed the branches

**Comment by millerdev** [comment]
@dannyroberts do we still need this branch?

**Comment by dannyroberts** [comment]
Oh I closed it yesterday thinking the concensus was not to use the approach. To resurrect, you'd also need to resurrect https://github.com/dimagi/commcare-hq/pull/23892, but I'm guessing you might have just not noticed I closed it.

**Comment by millerdev** [comment]
Oh, I was just asking about the branch (I know we don't need the PR). I assume it's not needed.

**Pull request closed without merging**
