### PR TITLE
dont sync couch on migrate

### PR DESCRIPTION
**Pull request by calellowitz**
## Technical Summary

https://dimagi-dev.atlassian.net/browse/SAAS-12601

As followup from a recent P1, this separates couch changes from the `migrate` management command. I added it to our `hammer` script so that the "make sure everything is up to date" still covers all the bases.

### Safety story

This does not affect running code

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

## Final self-reflection
- [x] My safety story above is convincing and gives me confidence that this PR will not introduce a regression

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]

**Review by snopoke — COMMENTED** [review]
Does this impact tests at all?

Edit: looks like the answer is yes.

**Review by millerdev — APPROVED** [review]

**Review by snopoke — APPROVED** [review]

**Review by dannyroberts — APPROVED** [review]
Forgot to approve when I reviewed last week

**Comment by snopoke** [comment]
> Tested this on staging and confirmed that our existing deploy handles preindexing without the migrate hook, so I think this is good to go.
> 
> FYI @dimagi/team-commcare-hq Once this is merged, you will have to run `sync_couch_views` whenever there are changes to couch views, much like running `migrate` now. For those that use the `hammer` script to automate a lot of the post code update tasks, I have added that command there, so just running `hammer` will continue to be enough.

Django has a way to detect if migrations are required, is there a way to do that for couch? Perhaps we could do it only if running in DEBUG mode?

**Comment by millerdev** [comment]
@snopoke wrote

> Django has a way to detect if migrations are required, is there a way to do that for couch?

https://github.com/dimagi/commcare-hq/pull/32544 adds support for that.

**Comment by millerdev** [comment]
@calellowitz I think this is good to go now that https://github.com/dimagi/commcare-hq/pull/32544 is merged.

I merged master and pushed [one new commit](https://github.com/dimagi/commcare-hq/pull/30555/commits/7b1d8df5010d3f94865d7b1d4442ba18af4ed0cf), so probably makes sense to have someone else do a final review.

**Comment by calellowitz** [comment]
Looks good to me. Thanks for pushing this over the line!

**Pull request merged**
