### PR TITLE
Add edited_by_user_id to forms API

### PR DESCRIPTION
**Pull request by esoergel**
followup from https://github.com/dimagi/commcare-hq/pull/16883
Feel free to propose alternative names or ways to present the field.
@snopoke @emord
@krsdimagi FYI

### CODE REVIEW

**Comment by snopoke** [comment]
I don't think we can call this field `edited_by_user_id` since it only represents that if the form was edited. For unedited forms it may be `null` if the form wasn't submitted with auth or else it will the ID of the submitting user.

I think calling it `last_modified_by` might be OK but still not great.

**Comment by esoergel** [comment]
@snopoke what do you think of adding a `if edited_on:` to the top, so that it will only be set if the form has been edited?  As you pointed out, the meaning can be confusing otherwise.

**Comment by snopoke** [comment]
Yea, that seems like a good idea.

**Comment by esoergel** [comment]
I made that change, so I think this should be g2m.

**Review by emord — APPROVED** [review]

**Pull request merged**
