### PR TITLE
make upgrade-requirements

### PR DESCRIPTION
**Pull request by emord**

### CODE REVIEW

**Review by nickpell — APPROVED** [review]
Loving these requirements upgrades

**Comment by emord** [comment]
Very close to having the output of `pip list --outdated` fit in one screen on my laptop

**Review by kaapstorm — APPROVED** [review]

**Comment by emord** [comment]
Had to revert `python-dateutil` because it looks like they changed exception formats in the new version. My guess is that it would only affect tests, but not including it here to reduce any possibilities of encountering errors.

@kaapstorm This was in motech.openmrs, so I think that may be your area of ownership (no need to actually look into this/upgrade it. nothing requires that it be upgraded at this point except for my own urges to make upgrade-requirements be an easier job):

```

======================================================================
FAIL: corehq.motech.openmrs.tests.test_atom_feed:GetTimestampTests.test_bad_date
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/motech/openmrs/tests/test_atom_feed.py", line 62, in test_bad_date
    get_timestamp(feed_elem)
AssertionError: "^Unknown string format$" does not match "(u'Unknown string format:', 'Nevermore')"
```

**Review by millerdev — APPROVED** [review]

**Comment by kaapstorm** [comment]
No problem @emord, the change is tiny: https://github.com/dimagi/commcare-hq/pull/23246

**Pull request merged**
