### PR TITLE
Update credit adjustment interface

### PR DESCRIPTION
**Pull request by nickpell**
Handles a few requests from Ops.  Would be good to get into today's deploy.

:blowfish: @benrudolph cc: @dannyroberts

### CODE REVIEW

**Comment by dannyroberts** [comment]
if deploy's at 3 that's 20 minutes which isn't enough to run tests. If you run the accounting tests locally maybe that'll speed things up

**Comment by nickpell** [comment]
there's no test coverage for that file, but running accounting tests locally anyway

**Comment by nickpell** [comment]
accounting tests pass locally

**Comment by dannyroberts** [comment]
hmm looks like this just missed deploy

**Pull request merged**
