### PR TITLE
Ze/bulk export all case types

### PR DESCRIPTION
**Pull request by zandre-eng**
## Technical Summary

Link to ticket [here](https://dimagi-dev.atlassian.net/browse/SC-2553).

This allows users to be able to do a bulk case export, creating a config to export every case type in a project space.

A new dropdown option called "Any Application" is available when creating a case export, which lists all the case types in the project space. Furthermore, this new option includes a "Select All" which allows the user to do a bulk case export.
Screenshot from 2023-04-14 10-46-26

When creating a bulk case export config, users will be able to edit properties such as the file name and type, but will be unable to generate a Data Export config file. The user will also be unable to choose what to name the Excel sheets, choose which case properties to export, or mark sensitive data.
Screenshot from 2023-03-27 12-07-53

The case type given to a bulk case export is `commcare-all-case-types`, which is used to identify an export as being a bulk case export. After saving a bulk case export config, the backend will start a task to populate the config with tables for all case types in the project.

There is a sanity check put in for when the user wants to do a bulk case export. If the project has more than 30 case types or 20 applications, then the user will be unable to create a bulk case export config, and will be met with the following error message:
Screenshot from 2023-04-13 10-13-13

If the user has a pre-existing bulk case export config, and tries to download it with the above-mentioned limits exceeded, then the following error message will be shown:
Screenshot from 2023-04-13 10-13-25

The reason for implementing this limit is that the Celery task responsible for populating the `ExportInstance` tables will silently fail if there are too many case types/applications in the project.

## Feature Flag

None.

### Safety story

- Local testing.
- Unit tests were added to check functions doing bulk case export.
- QA passed.

### Automated test coverage

Unit tests have been created to check both the `generate_instance_from_schema` and `generate_schema_from_builds` functions when doing a bulk case export.

### QA Plan

Link to QA ticket [here](https://dimagi-dev.atlassian.net/browse/QA-4930).

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by orangejenny** [comment]
UI feedback: Something about having "select all" as an option in a dropdown seems odd. Usually select all is a separate interaction in HQ. How about calling that option "Any Case Type" instead of "Select All" and putting it at the top? That would be more like the applications dropdown.

@biyeun

**Comment by zandre-eng** [comment]
@orangejenny It sounds like a good idea to rename it to something like "All Case Types" instead, to help keep things consistent. The wording I used was from this PR's ticket and spec doc, but I do agree it should then probably be changed. I am curious to hear what @biyeun thinks before going ahead with the change.

**Comment by zandre-eng** [comment]
Apologies to all the extra people that got tagged for review. This was a mistake on my end where a merge wasn't pushed correctly . The issue has been resolved now and the extra people that got tagged may ignore this PR.

**Review by kaapstorm — APPROVED** [review]

**Review by kaapstorm — COMMENTED** [review]
:+1:

**Review by SmittieC — APPROVED** [review]
Overall looks good :+1:

**Pull request merged**
