### PR TITLE
fix subscription form

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?189054

@calellowitz cc: @kaapstorm

### CODE REVIEW

**Comment by calellowitz** [comment]
:+1: pending tests

**Comment by nickpell** [comment]
:white_check_mark:

**Comment by nickpell** [comment]
gonna self merge and deploy

**Comment by kaapstorm** [comment]
:+1: Sorry I've been so slack with reviews, @nickpell. I took PTO on Tues, and yesterday was packed with personal admin.

**Pull request merged**
