### PR TITLE
Yeksi naa reports various changes

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @czue,
In these changes, I have named loops, extended tests data, fixed dashboard 3 as well as changed used columns to match new specification.

### CODE REVIEW

**Review by czue — APPROVED** [review]
Looks great - thanks for the thorough work!

**Comment by dannyroberts** [comment]
Hi @dmydlo, failure looks related (?):
https://travis-ci.org/dimagi/commcare-hq/jobs/365672653

```
FAIL: custom.yeksi_naa_reports.tests.reports.test_dashboard_2:TestDashboard2.test_rupture_rate_by_pps_report
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/yeksi_naa_reports/tests/reports/test_dashboard_2.py", line 269, in test_rupture_rate_by_pps_report
    ], key=lambda x: x[0])
AssertionError: Lists differ: [[u'District Test 2', u'no dat... != [[u'District Test 2', u'no dat...
First differing element 10:
[u'PPS 1', u'no data entered', u'no data entered', u'no data entered', u'no data entered', u'46.15%', u'no data entered']
[u'PPS 1', u'no data entered', u'no data entered', u'no data entered', u'no data entered', u'no data entered', u'no data entered']
Diff is 5577 characters long. Set self.maxDiff to None to see it.
```

**Review by czue — APPROVED** [review]
thanks again for follow ups

**Comment by dannyroberts** [comment]
Thanks @dmydlo

**Pull request merged**
