### PR TITLE
Module filtering instance

### PR DESCRIPTION
**Pull request by benrudolph**
See this for context: http://manage.dimagi.com/default.asp?162644

@snopoke @orangejenny 

enchantress: @biyeun

### CODE REVIEW

**Comment by benrudolph** [comment]
also, @snopoke, it's always a pleasure working in the app_manager code

**Comment by snopoke** [comment]
@benrudolph thanks but most credit goes to @dannyroberts

**Comment by dannyroberts** [comment]
:bowtie:

**Comment by benrudolph** [comment]
:+1:

**Pull request merged**
