### PR TITLE
Removed corehq/apps/api/data/

### PR DESCRIPTION
**Pull request by orangejenny**
## Summary

Added back in https://github.com/dimagi/commcare-hq/pull/1540

I think it's dead now. Opening for tests.

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

Let's find out.

### QA Plan

Not QAing. This was added years ago for the sake of profiling, so I don't think it's likely to cause any user-facing issues.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by stephherbers — APPROVED** [review]

**Review by millerdev — APPROVED** [review]
Tests passed, which is a good sign (although there might not be many tests from that era). Maybe ask @ctsims, @dannyroberts or @snopoke  if they know anything about it yet?

**Review by snopoke — APPROVED** [review]
I don't have any context on this but I don't see any other references to these files in code.

**Comment by snopoke** [comment]
The API that used this was removed here: https://github.com/dimagi/commcare-hq/pull/10602

**Comment by orangejenny** [comment]
@snopoke Sweet, thank you for looking that up.

**Pull request merged**
