### PR TITLE
actually refresh export views

### PR DESCRIPTION
**Pull request by nickpell**
Actually execute the query, so the couch views update

@dannyroberts @gcapalbo

### CODE REVIEW

**Comment by nickpell** [comment]
Am I correct in thinking that the view won't be updated unless ```.all()``` is called? @dannyroberts @czue

**Comment by czue** [comment]
good call. forgot that couch view calls return a lazily evaluated generator

**Comment by czue** [comment]
it looks like `.fetch()` might be the most appropriate thing to call: https://github.com/benoitc/couchdbkit/blob/master/couchdbkit/client.py#L1021

**Comment by czue** [comment]
(will amount to the same thing - just a tiny bit more readable)

**Comment by snopoke** [comment]
Also it won't do any wrapping

**Pull request merged**
