### PR TITLE
Ews report changes

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 8 errors:

* custom/ewsghana/filters.py, line 151 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/filters.py, line 152 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/filters.py, line 180 - W292 no newline at end of file
* custom/ewsghana/reports/specific_reports/reporting_rates.py, line 10 - F401 'DatespanMixin' imported but unused
* custom/ewsghana/reports/specific_reports/reporting_rates.py, line 18 - F401 'calculate_last_period' imported but unused
* custom/ewsghana/reports/stock_transaction.py, line 3 - F401 'StockState' imported but unused
* custom/ewsghana/reports/stock_transaction.py, line 69 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/reports/stock_transaction.py, line 79 - W391 blank line at end of file

**Comment by dimagimon** [comment]
There are 8 errors:

* custom/ewsghana/filters.py, line 151 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/filters.py, line 152 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/filters.py, line 180 - W292 no newline at end of file
* custom/ewsghana/reports/specific_reports/reporting_rates.py, line 10 - F401 'DatespanMixin' imported but unused
* custom/ewsghana/reports/specific_reports/reporting_rates.py, line 18 - F401 'calculate_last_period' imported but unused
* custom/ewsghana/reports/stock_transaction.py, line 3 - F401 'StockState' imported but unused
* custom/ewsghana/reports/stock_transaction.py, line 69 - E226 missing whitespace around arithmetic operator
* custom/ewsghana/reports/stock_transaction.py, line 79 - W391 blank line at end of file

**Comment by czue** [comment]
@lwyszomi this is a pretty big set of changes - do you have tickets or specs you can point at? Or maybe you can put some comments in the PR?

**Comment by lwyszomi** [comment]
@czue 
http://manage.dimagi.com/default.asp?169052#951720
http://manage.dimagi.com/default.asp?169917#950655
http://manage.dimagi.com/default.asp?169268#952661

**Comment by czue** [comment]
wow that datespan requirement is annoying. :+1: to merge, but not mergeable anymore

**Comment by lwyszomi** [comment]
@czue updated

**Comment by czue** [comment]
(still not mergeable)

**Comment by lwyszomi** [comment]
@czue updated

**Pull request merged**
