### PR TITLE
B3 Bihar Reports

### PR DESCRIPTION
**Pull request by biyeun**
Migrates bihar reports to B3. 
Builds on https://github.com/dimagi/commcare-hq/pull/10619

QA'd locally as much as I could. 
@millerdev / cc @czue 
commit-by-commit

screen shot 2016-03-04 at 4 03 34 pm
screen shot 2016-03-04 at 4 15 08 pm
screen shot 2016-03-04 at 4 15 15 pm
screen shot 2016-03-04 at 4 15 51 pm
screen shot 2016-03-04 at 4 08 38 pm

### CODE REVIEW

**Comment by biyeun** [comment]
@dimagi/product for QA suggestions

**Comment by czue** [comment]
Like the other one - only thing that matters is how this looks on a C2

**Comment by biyeun** [comment]
got this on staging to test but something on staging is overriding the mobile template being sent to the login view...

**Comment by biyeun** [comment]
suspect this interference might be coming from two-factor? @calellowitz any thoughts? (see comment above)

**Comment by biyeun** [comment]
(reports view looks ok)

**Comment by calellowitz** [comment]
I looked at the mobile login view / template and from my quick check the two-factor branch does not appear to modify any of the places mobile login is referenced. @emord would know more about this than me but I believe he is offline.

**Comment by biyeun** [comment]
@calellowitz the mobile login view calls the main login view with a new template as the argument, but looks like the passed argument is never used now and the mobile template is never loaded

**Comment by biyeun** [comment]
@millerdev this is ready to merge since two factor currently affecting this on staging but not on a branch without it.

**Comment by calellowitz** [comment]
@biyeun I have found where two factor breaks it, and am working to fix that as well

**Pull request merged**
