### PR TITLE
Update Pillow to 5.2.0

### PR DESCRIPTION
**Pull request by emord**
Went through the change logs https://pillow.readthedocs.io/en/5.2.x/releasenotes/5.2.0.html and couldn't find anything that we use.

Removals noted were:

https://pillow.readthedocs.io/en/5.2.x/releasenotes/3.0.0.html#deprecated-methods
https://pillow.readthedocs.io/en/5.2.x/releasenotes/4.0.0.html#image-core-stretch-removed
https://pillow.readthedocs.io/en/5.2.x/releasenotes/4.1.0.html#removed-deprecated-items

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
This looks like a large jump - does it make sense to put it on staging or test in some other fashion?

**Comment by emord** [comment]
> This looks like a large jump - does it make sense to put it on staging or test in some other fashion?

Deployed this to staging. Our use of this library is very basic from what I can tell. I did a few things to hit such as uploading and deleting a domain's custom logo and uploading images.

**Comment by orangejenny** [comment]
@emord thanks, sounds good

**Comment by emord** [comment]
will deploy monday

**Pull request merged**
