### PR TITLE
Test or not

### PR DESCRIPTION
**Pull request by sravfeyn**
I have added these tests for https://github.com/dimagi/commcare-hq/pull/7164 But I am not sure 
- if it's necessary to add tests to such a small custom feature 
- if these tests are good tests

so, I didn't add them.
But I would like to get feedback, if you have some time, on what makes these tests bad and what could be made better.
@snopoke @esoergel @czue only the third commit

### CODE REVIEW

**Comment by snopoke** [comment]
Seems reasonable to have the tests especially since you've already written them. I would probably refactor slightly so that you can just pass the tab into a generic test method.

**Comment by czue** [comment]
yeah my quick feedback (sorry if this isn't what you were looking for)

1. Probably not good ROI in terms of time spent writing these tests to how important it is that we have test coverage for this feature
2. Now that the tests exist, not a major downside in keeping them around
3. The minor downside is that it slows down all tests
4. That would be largely addressed if you made the tests not depend on the database (which I think would be pretty easy - though you're making small assumptions about how the user permissions map to the underlying function calls, or harder if you go with a mock approach)

**Comment by sravfeyn** [comment]
Thanks for the insights! I have to figure out 4th point.

**Comment by czue** [comment]
Yeah sorry that was a bit confusing. I was basically saying you can just make the `WebUser`/`Domain` setup without saving it to the database. I think no mocks necessary.

**Pull request closed without merging**
