### PR TITLE
Avoid line break before long report names

### PR DESCRIPTION
**Pull request by solleks**
[Feature request ](https://docs.google.com/document/d/1bmo7swOiXyUTW6IcWn9HFCNcdUS8m6KzMcSK2biN7zg/edit?ts=5ef3962a)(see Spec no. 4).

##### SUMMARY
The edit_role_modal dialog box shows a list of custom reports with check boxes (when "Allow role to access all reports" is not selected). A very long report name can cause ugly formatting of the list by placing a line break before the check box and outdenting the line:
OldEditRoleModalLayout

This PR changes the wrapping behavior to avoid the line break:
NewEditRoleModalLayout

Why does the bad formatting happen? Bootstrap defines a form-check as a div containing an invisible check box and a label, where the label has a label::before defined as an empty string outlined by a box. The label::before is forced left where it normally lies over the invisible check box. A very long report name causes a very long label, which wraps with a line break between the invisible check box and the label, at which point, the label::before placement ends up being too far left.

The fix is to disable wrapping between the invisible check box and the label, but then re-enable it within the label so that the report name isn't clipped by the dialog box margin. To reduce unintended consequences, I just did this within the list of custom report names.

##### FEATURE FLAG
Not specific to a feature flag.

##### RISK ASSESSMENT / QA PLAN
I don't think this change requires QA as it is only a cosmetic change.

##### PRODUCT DESCRIPTION
Users will no longer see an unexpected line break in the form if they create a very long report name.

### CODE REVIEW

**Comment by orangejenny** [comment]
This looks good, thank you for the thorough explanation. Two requests for additional improvements:

1) Can you add a new class or two instead of using inline styles? We're pretty dogmatic about avoiding inline styles. New classes would go in [this folder](https://github.com/dimagi/commcare-hq/tree/master/corehq/apps/hqwebapp/static/hqwebapp/less/_hq/), either in `lists.less` (since it's a list of checkboxes) or in `forms.less` (since that's where our `.form-check` additions are defined).

2) Can you apply this to the similar places in this file (everything that uses a `foreach: foo.specific` binding)? I agree with your point about unintended consequences, but I'm confident that these sections are basically the same and that the other sections have the same problem. (This file needs to be DRYed up very badly, but that's out of scope for this PR.)

**Comment by solleks** [comment]
I'm learning CSS as I go here, so every line that I write makes me nervous.

What do you think about this version, where every form-check has the white-space style change? I can't find any form-checks used in HTML files aside from edit_report_modal.html. This change does affect form-checks that are not in lists, but those can still suffer from bad formatting if we wanted to give them a long label:
LongLabel

If you prefer that we only change the style for form-checks in lists, is there any way to define a new class in LESS that is exactly like .form-check except for the new white-space style? Something like:

```
.form-check-in-list extends .form-check {
    white-space: nowrap;
}
```

**Comment by orangejenny** [comment]
Ha, I have felt that nervousness before, but I think what you have now is good.

This UI got a facelift relatively recently, about a year ago in https://github.com/dimagi/commcare-hq/pull/23343, so it makes sense to me that the new UI isn't widely used yet. It's likely that any new usages will want to use the same behavior you implemented here.

I'm going to go ahead and merge this, and then it'll get deployed early next week.

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
Hmm, there's a build failure, which I can't imagine is related, but to be very conservative, I'll restart it and wait to merge until it passes.

**Pull request merged**
