### PR TITLE
Adding 'Web Apps' as an option in Roles so that we can restrict access

### PR DESCRIPTION
**Pull request by kkrampa**
@emord

### CODE REVIEW

**Comment by kkrampa** [comment]
https://manage.dimagi.com/default.asp?262722

**Comment by emord** [comment]
There's no code handling the following case:

>    b) If user does not belong to any of the above mentioned roles (in 2a), then when they click on "report an issue" on ICDS-CAS Dashboard, it should navigate to a page that says "Please contact the nearest Helpdesk to report the issue"

**Comment by kkrampa** [comment]
Handled here: https://github.com/lwyszomi/commcare-hq/blob/a42dc4725dd945c4e79567747a2bf6192566b333/custom/icds_reports/static/js/icds_app.js#L9L18

**Comment by kkrampa** [comment]
Could you restart the build?

**Review by emord — APPROVED** [review]

**Comment by kkrampa** [comment]
✅

**Pull request merged**
