### PR TITLE
Add app summary link for each version

### PR DESCRIPTION
**Pull request by proteusvacuum**
Did you know that you can see the app summary for every single version of the app you ever made? You can! This PR exposes that functionality so you can see what your app looked like in the past without you needing to know some magic URL. 

screenshot from 2018-11-27 16-06-28

I changed the summary page titles so you know what version you are looking at: 
screenshot from 2018-11-27 16-10-08

Pinging @dimagi/product in case you want me to hide this or put the button elsewhere.

### CODE REVIEW

**Review by orangejenny — COMMENTED** [review]
Sweet.

> Pinging @dimagi/product in case you want me to hide this or put the button elsewhere.

How about making it an option in the publish modal? The releases page is already a carnival of buttons/widgets, and I think one click away is the right level of visibility for this.

**Comment by djmore9** [comment]
@proteusvacuum This is great. Understanding previous apps will be useful to teams who have multiple app builders. We have had a few customers provide feedback on how our Release Management could be better. Improvements in this area will bring CommCare closer to being an Enterprise-grade offering. 

@orangejenny I don't think Publish modal would be a useful. I would be mostly interested in the App Summary for troubleshooting issues with the current app, to confirm before reverting to a previous version, or to simply understand how the old app was built. Since these tasks are not related to Publishing, I think putting this button on the Publish modal would be a bit out of place. However, I do agree about the carnival of buttons on the Releases page.  How about something like this:

**Version 386** | Jul 31, 2017 17:05 EDT by Dev with CommCare v. 2.36.1 | App Summary

App Summary being link.

**Comment by orangejenny** [comment]
@djmore9 Fair point about this not being a publishing action. I was thinking this is similar to "View Source Files" which is in the deploy modal but only visible to superusers. Making that modal a junk drawer isn't a good idea.

To tweak your suggestion slightly, what if we just linkified the "Version 386" text or did the link as an next to the version? Just wanted to shorten it a bit - app error counts also show up on that line, it's starting to get cluttered.

**Comment by djmore9** [comment]
Yeah, either of the 2 options sound good. I thought of proposing making Version 386 a link, but thought that may not be optimum from a discoverability standpoint.

**Comment by czue** [comment]
I'll throw one more idea in the hat:

Make the "Revert" button a "More..." dropdown with the revert, app summary and view source files in it. I suspect if we had analytics on that button (do we?) we'd discover that revert is also probably given more real estate than it deserves.

**Comment by orangejenny** [comment]
> Make the "Revert" button a "More..." dropdown

That's not bad; I agree reversions very likely aren't common enough to warrant the visual attention that button gets.

Yet another possibility would be to change "Publish" to "Actions" and put both the revert action and the app summary link in the popup. It'd clean up the page a bit, but it would also make that popup less cohesive.

@djmore9 / @ohmegasquared your call

**Comment by djmore9** [comment]
Publish is the primary action here so I wouldn't put it under More/Actions, but everything else can go there, I think. @ohmegasquared Thoughts?

**Comment by djmore9** [comment]
Thanks all. 🙏🏽

I really like @czue's idea. 

@ohmegasquared Here's an example of what App Summary looks like:
https://www.commcarehq.org/a/dev-more/apps/view/b919e23f138840248559f7fc463c3ca3/summary/form/
Running options via users is fine. There will be a bunch of such requests from devs that require minor design feedback, so it will be super helpful if you can have a process for tracking and executing on such requests so that we more forward effectively. But ultimately, our focus should be more on creating 'design capacity or framework' so that devs can makes such decisions relatively independently. For example, I think, the UX pattern of a Primary Action, and a bunch of associated Secondary Actions is pretty common, so it will be helpful to define such standards for CommCare. 
Happy to discuss this further offline. Cheers.

**Comment by proteusvacuum** [comment]
@ohmegasquared and I discussed this offline, and she had the following suggestion:

> Meghan Canale [14:50]
> maybe left align in the contrainer as to not distract from the publish button
> 
> Farid Rener [14:51]
> I think that's going to interfere with the "comments" box
> 
> Meghan Canale [14:51]
> It could go below the comments box if that whole row was dedicated to buttons
> 
> Farid Rener [14:52]
> ok
> should I also move the publish button into that row?
> 
> Meghan Canale [14:53]
> yea, I'm suggesting publish, revert, and app summary are all horizontally aligned
> and app summary is left aligned with the chat bubble icon
> 
> Farid Rener [14:54]
> cool beanz

I'm going to do that for now so that this PR isn't held up on building out a request framework.

**Comment by ohmegasquared** [comment]
> For example, I think, the UX pattern of a Primary Action, and a bunch of associated Secondary Actions is pretty common, so it will be helpful to define such standards for CommCare.

Definitely agree, but this is a navigation element, taking you to a different page. It doesn't have the same types of functions as other buttons on this page, like publish or revert, which is why I think it would be something good to put in front of users. Putting a navigational element in an button can be surprising and jarring to a user who didn't realize they were leaving that page. 

Farid and I chatted offline about the lowest level of effort to get this on the page, which was copied and pasted above. 

Thanks!

**Comment by djmore9** [comment]
Sweet. Thank you, both. Cheers.

**Comment by proteusvacuum** [comment]
Here it is:

screenshot from 2018-12-03 10-43-50

**Review by orangejenny — APPROVED** [review]

**Comment by czue** [comment]
looks great!

**Pull request merged**
