### PR TITLE
link to domain that triggered the autopay change

### PR DESCRIPTION
**Pull request by nickpell**
If I'm on domain X and I add my card as the autopayer, and the billing account was created by domain Y, then both me and the owner of the old autopay card receive an email with a link to Billing Info of domain Y.  This changes the link to domain X.

@proteusvacuum @benrudolph cc: @esoergel

### CODE REVIEW

**Comment by proteusvacuum** [comment]
The autopay card gets set for every domain in the billing account, right? Does it make sense to also send links to the other domains that are part of that account?
I think this is actually a bit confusing -- the autopay card is for the whole account, but you have to set it at the domain level. Or have I misremembered how these accounting models work?

**Comment by nickpell** [comment]
@proteusvacuum You're remembering correctly.  I think the goal should be to enable both email recipients (person who just added card and person whose card is being removed from autopay) to go to a page where they can see the account's card setup.  Before this PR, both recipients receive a link to a domain to which they might not belong; with this PR, at least one of the recipients will belong to the domain.

A slightly better change might be to query for a domain which belongs to this account and to which the recipient is a domain admin; but that's for an edge case so extreme I don't think it's worth considering at the moment (but feel free to push back or fix if you're inclined).

**Comment by nickpell** [comment]
(also note that this is only an issue for the recipient whose card is being removed from autopay)

**Comment by proteusvacuum** [comment]
I see. So the issue is that even if they are an account admin, they might not be a domain admin. Didn't realize that distinction. This makes more sense now.

**Comment by nickpell** [comment]
:white_check_mark:

**Pull request merged**
