### PR TITLE
Rebuild Form Command Synchronously

### PR DESCRIPTION
**Pull request by sheelio**
@dannyroberts 

This is synchronous (and also uses couch to pull list of forms).

### CODE REVIEW

**Comment by dannyroberts** [comment]
if it's pulling form ids from couch it won't work for SQL domains, right?

**Comment by sheelio** [comment]
Yup it won't - I do just need this for a couch domain (I could modify the
formaccessors but didn't want to make more risky changes).

**Review by dannyroberts — CHANGES_REQUESTED** [review]
Ah okay. Sorry to be a bummer, but someone's inevitably going to want to use this later and be super confused/disappointed when it doesn't work on SQL. Can you change the name to `rebuild_form_table_couch`?

**Comment by sheelio** [comment]
Made changes.

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
