### PR TITLE
Uneditable export columns

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @NoahCarnahan this implement "uneditable" user defined columns. Thought here is that when we do a migration we can now just force add the columns for the existing exports. this'll hopefully get us closer to 0 domains on old exports. open for review, still need to write tests and hook it up to the migrate_exports command

cc: @gcapalbo

### CODE REVIEW

**Comment by czue** [comment]
sorry, can you remind me what the rationale for this was (as opposed to user defined)?

in terms of behavior - these will show up in the UI and export but you can't change them? can you delete them? assume if you can then they would be gone forever at that point?

i think we probably talked about this I just can't remember

**Comment by benrudolph** [comment]
correct, this will show up in the UI and you can't change them or delete them, it will look exactly like your previous export. i thought it'd be confusing if all of a sudden after the migration a bunch columns had text field inputs instead of the normal looking `form.question` in the column definition

**Comment by czue** [comment]
> this will show up in the UI and you can't change them or delete them, it will look exactly like your previous export

ok, have you confirmed this with anyone on product? i don't know how bad/disruptive that would be but sounds like something we should at least flag

**Comment by benrudolph** [comment]
no i haven't, but the alternative would be to just have those columns disappear. i thought the goal was to make the migration be as transparent as possible. what part do you think would be disruptive?

**Comment by czue** [comment]
not disruptive so much as getting support tickets from people asking why they can't edit their exports.

is the alternative not to create an editable, manual column? i think I just don't understand this well enough to be useful, but if you feel good that you've thought it though and talked to any relevant stakeholders I think feel free to just ignore me

**Comment by benrudolph** [comment]
ah i see where we're missing each other. the part that would be uneditable would be the path to the column not the label. there are 3 columns in the export, selected, question, and label. on a normal column selected and label are editable. on a user defined column, question is editable so that a user can specify where the data exists. a non -editable user defined column functions that exact same as a regular column except that we've already determined the path to the question and thus do not let users modify that (like normal columns)

**Comment by czue** [comment]
gotcha, that seems totally fine then. sorry about causing churn.

**Comment by benrudolph** [comment]
ok tests written, sorry for the delay. we're almost there. got a few more items to tick off before going big and converting everyone

**Comment by czue** [comment]
:+1: from me. haven't looked at code closely so would prefer if @NoahCarnahan or @gcapalbo reviewed and merged

**Comment by NoahCarnahan** [comment]
Looks good. One step closer!

**Pull request merged**
