### PR TITLE
preindex couch periodically

### PR DESCRIPTION
**Pull request by emord**
@dimagi/scale-team preindexing couch takes quite a while when we don't deploy often (sometimes hours), so this will make sure it's up to date every hour. I think this will have little to none effect on prod or softlayer or swiss, but big gains on nic and maybe l10k/enikshay in the future

buddy @orangejenny

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]

**Comment by snopoke** [comment]
I don't think this will trigger an index. I think you just need this portion: https://github.com/dimagi/dimagi-utils/blob/dbc52f6ef32f376524c17bb65c41d5a26c6de4e0/dimagi/utils/couch/sync_docs.py#L26-L37

**Comment by emord** [comment]
Thanow dependent on https://github.com/dimagi/dimagi-utils/pull/410

**Review by snopoke — COMMENTED** [review]
Do we actually want to push the design docs to couch at all? That doesn't seem useful and may incur some penalty.

**Comment by emord** [comment]
I don't think that pushing will have much of an effect, but I changed it to pull out index_design_doc

(cancelled tests until the dimagi-utils pr is merged)

**Comment by snopoke** [comment]
merged dimagi/dimagi-utils#410 and updated the submodule ref in this branch

**Pull request merged**
