### PR TITLE
Shorter initial wait, more chances

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: [HI-534](https://dimagi-dev.atlassian.net/browse/HI-534)

I agree with @millerdev 's concerns he gave in the [first PR](https://github.com/dimagi/commcare-hq/pull/24233/). I don't love the idea of a thread-local global variable for this one situation. I also considered prefixing the domain name with a constant, like "PENDINGSIGNUP-<real-domain-name-here>" that can be dropped, but I imagine the footprint of that kind of change would be big, and could cause awful and hard-to-find side-effects. Maybe `sleep()` is the least of the evils.

cc @dannyroberts @nickpell @gbova

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
So we're possibly waiting even longer now?

I do not agree that `sleep()` is the least of evils. Also, might need to find someone else to approve this. I can't do it with a clear conscience.

**Comment by nickpell** [comment]
As much as I don't like a global variable it's probably the only reliable way to address this issue until we get off Couch :/ I'm happy to be proven otherwise though.

**Comment by kaapstorm** [comment]
I'm OK with reviewers having the right to veto.

Is a thread-local global variable the other lesser evil? Or are their other evils to consider? :smiling_imp:

**Comment by kaapstorm** [comment]
With 2 votes for global variable, I'll go with that. I'll be picking this up after a couple of other tickets, so if anyone wants to make more Nominations Of Evil, there is some time.

**Comment by kaapstorm** [comment]
I will explore how feasible it would be to pass `domain`. If it seems a worse option than using a thread-local variable, I'll go with the variable.

**Comment by millerdev** [comment]
Before I proposed the thread-local solution Sravan originally said:

> The code path is too deep to pass domain (it could be doable but it's a long chain of passing)...

Which is what prompted me to think of other solutions than than passing the original domain object through to here. I still think that (passing it through) would be the best solution.

**Pull request closed without merging**
