### PR TITLE
Tell dependabot to use a specific Python version when resolving pip dependencies

### PR DESCRIPTION
**Pull request by joxl**
## Technical Summary

A `runtime.txt` file can be used to tell dependabot how to configure its runtime environment.  Specifying `python-3.9` causes dependabot to use Python 3.9 (instead of 3.10, which has been causing it to generate broken requirements files for some time now).

**WARNING**: the fact that `runtime.txt` works for this purpose is a hack. This file is likely dependant on how dependabot works under the hood, and has been reported to have [caveats of its own](https://github.com/dependabot/dependabot-core/issues/4758).

----

I discovered the core problem when investigating the `markdown` library's [Change Log](https://python-markdown.github.io/change_log/), which is where I learned that its sub-dependency `importlib-metadata` (with further sub-dependency `zipp`) is only required for Python < 3.10. Those are the two libraries that dependabot keeps removing from our dependency files, so it seems dependabot is rendering its dependency changes using Python 3.10.

After a _lengthy_ browse of dependabot-core's issues, I found dependabot/dependabot-core#4606, which lead to the discovery of the [undocumented `.python-version` or `runtime.txt` hacks](https://github.com/dependabot/dependabot-core/issues/1455), where I settled on using `runtime.txt` to avoid interfering with [`pyenv` configurations](https://github.com/dependabot/dependabot-core/issues/4062) ([this comment](https://github.com/dependabot/dependabot-core/issues/4062#issuecomment-995684728) was particularly helpful).

During my investigation, I realized that HQ dependencies did have a `.python-version` file in the past, added in PR #28607 for the exact reason that this PR is adding `runtime.txt`. Unfortunately, that file is troublesome to maintain (it requires the full exact version including patch, which changes frequently; and it must match a version of python listed in a dependabot-core source file). It also causes environment problems for developers who use `pyenv`, which seems to be the reason it eventually got removed in PR #30966.

This change was tested on a simple custom repository which confirmed it works ([dependabot commit prior to](https://github.com/joxl/dependabot-python3.9/commit/250b4799ef57257b526e6999608816afe0651a4e) `runtime.txt`, and the [recreated commit after](https://github.com/joxl/dependabot-python3.9/commit/e2e935fb24cf950fd4c4f93d809754d8f3e8d144)).

Ticket: [SAAS-13963](https://dimagi-dev.atlassian.net/browse/SAAS-13963)

### Safety story

Only affects dependabot (as far as I know). This option is safer than using a `.python-version` file, which also apparently affects developers who are using `pyenv` (among other things, see **Technical Summary** above).

### QA Plan

No QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by AmitPhulera — APPROVED** [review]
Great find 🎉

**Review by millerdev — COMMENTED** [review]
How did you decide on the path of this file (`deployment/runtime.txt`)? Is that an arbitrary path that dependabot uses? It looks like the conventions around this file [may be related to Heroku, although it apparently is not always in a `deployment` directory](https://stackoverflow.com/q/61492883/10840)?

It concerns me a little bit to have this file in the `deployment` directory, where it seems out of place and not related to the other files in that directory. Does it support comments? If yes, what do you think of adding a comment that explains what it is and why it is in that location?

**Comment by joxl** [comment]
> How did you decide on the path of this file (`deployment/runtime.txt`)?

🤦‍♂️ That was a typo, thank you for catching this. Fixing now (it should be `requirements/runtime.txt`).

**Comment by joxl** [comment]
> Does it support comments?

I don't actually know, perhaps. With more testing I could probably find out. I agree it would be nice (even now that it's in the correct location, it could still save a dev from needing `git blame` to figure out what it's for).

**Comment by joxl** [comment]
@millerdev, `runtime.txt` now has comments. I tested a few different comment variations and not all of them work. The existing one does work. Here's the [repo](https://github.com/joxl/dependabot-python3.9/commits/main) where I tested this (the last 4 commits are the syntax tests).

**Review by millerdev — APPROVED** [review]

**Pull request merged**
