### PR TITLE
Remove by date modified owner

### PR DESCRIPTION
**Pull request by dannyroberts**
Continues off of https://github.com/dimagi/commcare-hq/pull/7218, split off because of reindex.

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts i put a don't merge tag on. I think that's right but feel free to remove if not

**Comment by dannyroberts** [comment]
:+1: thanks

**Comment by czue** [comment]
+4 −1,966 #statpadding

**Comment by snopoke** [comment]
vote @dannyroberts gets the rock for deleting the most code!

**Comment by benrudolph** [comment]
+1 to the rock vote

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Pull request merged**
