### PR TITLE
log when there is a matching case that is not migrated

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
@sravfeyn

**Review by sravfeyn — APPROVED** [review]

**Comment by sravfeyn** [comment]
Failure looks related
```
======================================================================
FAIL: custom.enikshay.nikshay_datamigration.tests.test_create_enikshay_cases:TestCreateEnikshayCases.test_matching_case_not_migrated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py", line 217, in test_matching_case_not_migrated
    call_command('create_enikshay_cases', self.domain)
AssertionError: MatchingNikshayIdCaseNotMigrated not raised
```

**Review by sravfeyn — APPROVED** [review]

**Comment by sravfeyn** [comment]
Build is still failing

**Comment by nickpell** [comment]
finally ✅

**Pull request merged**
