### PR TITLE
Remove old UserPillow

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

I was poking around in this code, noticed we have quite a few old pillows hanging around that claim they could be removed after https://github.com/dimagi/commcare-hq/pull/21329 was rolled out, but they have remained.

I figure there might be a good reason for this, but after viewing datadog and confirming the old `UserPillow` is not in use, but the new `user-pillow` is, it felt a bit safer to at least start with removing the old user pillow. Additionally, the user pillow tests were still using the old pillow which didn't seem right. I added some test cases there and made it look more like tests we write these days while I was at it.

If it turns out we can't yet remove this, I'd at least want the test changes to go out.
### Safety story

From what I can tell, the old UserPillow is not in use and safe to remove, which is all this PR does.
### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by gherceg** [comment]
Based on that test failure and looking at the `test_checkpoint_creation` and `test_no_checkpoint_creation`, I'm assuming there is more going on here than I am currently aware of with the old pillows and likely why they haven't been removed yet.

**Comment by joxl** [comment]
> I'm assuming there is more going on here than I am currently aware of

Might be worth looking into how checkpoint names are generated.  I'm wondering if this error is literally just because the pillow name changed (no longer contains "old"?).

```python
testapps.test_pillowtop.tests.test_reindexer:CheckpointCreationTest.test_checkpoint_creation(<class 'corehq.pillows.user.UserReindexerFactory'>, 'UserPillow') ... ERROR

======================================================================
ERROR: testapps.test_pillowtop.tests.test_reindexer:CheckpointCreationTest.test_checkpoint_creation(<class 'corehq.pillows.user.UserReindexerFactory'>, 'UserPillow')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 433, in test
    return test_func(self, *args)
  File "/mnt/commcare-hq-ro/testapps/test_pillowtop/tests/test_reindexer.py", line 158, in test_checkpoint_creation
    pillow = get_pillow_by_name(pillow_name)
  File "/mnt/commcare-hq-ro/corehq/ex-submodules/pillowtop/utils.py", line 112, in get_pillow_by_name
    config = get_pillow_config_by_name(pillow_class_name)
  File "/mnt/commcare-hq-ro/corehq/ex-submodules/pillowtop/utils.py", line 121, in get_pillow_config_by_name
    raise PillowNotFoundError('No pillow found with name {}'.format(pillow_name))
pillowtop.exceptions.PillowNotFoundError: No pillow found with name UserPillow

----------------------------------------------------------------------
Ran 4673 tests in 697.078s

FAILED (SKIP=1427, errors=1)
```

**Comment by calellowitz** [comment]
> Based on that test failure and looking at the `test_checkpoint_creation` and `test_no_checkpoint_creation`, I'm assuming there is more going on here than I am currently aware of with the old pillows and likely why they haven't been removed yet.

I think we may need to do more work before this is safe to go through with. The test failures themselves look easy to fix. In the stacktrace Joel linked, it is complaining that it cannot find the pillow with id `UserPillow`, which makes sense since you just deleted that pillow. You could probably replace it with `user-pillow` (the id of the pillow you replaced the old one with in the reindexer) and the test would pass, but I am not sure that set of changes is ideal.

Currently, the old, single use, pillows that are hanging around are used in the `ptop_reindexer_v2` commands (in the reindexer factories it uses to backfill es data). That command relies on pillows to do the heavy liftying, and it is really nice for us to have the single use pillows because it means we can reindex all the data the data in ES, without all the other processors used in the combined pillows. In the user example, that means we can reindex users, without reprocessing all of the user docs for UCRs as well. That becomes an even bigger deal for something like the case reindexer, where we save on the UCR processing, but also the messaging processing, and the case search index.

This brings us to the tests in question. These reindexers update the pillow checkpoint for the pillows they use to reindex data. That way, when you start the pillow up after a reindex, it does not attempt to reprocess all data, but instead only new data that came in after the reindex. However, we only want to set those checkpoints for the pillow that we used to reindex. Those tests are verifying that the correct pillow checkpoint is set. We only want to update the checkpoint for the specific pillow used in the reindexer, since we skipped part of the processing for the other pillows. In this case, you can see the tests confirm that the `UserReindexer` updates the `UserPillow` checkpoint, but not the `user-pillow`, the id of the new combined pillow.

Given all that, in order to safely make this change we need a way to only process the documents for the ES index we care about, and not mess with the checkpoint of the combined pillow. I don't think either of those are insurmountable problems. We can likely use arguments in the pillow constructor to select the processor we want (like the `skip_ucr` flag in the user pillow), and an argument in the reindexer to tell it not to overwrite the checkpoints for combined pillows. Alternatively, it is not obvious to me that these reindexers need to use "real" pillows, and it is possible we can dynamically create the ones we need, but the constructor for that will look a lot like the old pillow we just ripped out.

**Comment by snopoke** [comment]
Since @joxl is current working on changes to the reindexing process it may be worth holding off on removing these pillows until after that work is done.

**Comment by snopoke** [comment]
Closing old PRs, reopen if needed.

**Pull request closed without merging**
