### PR TITLE
wrap ReportAppFilter with correct subclass

### PR DESCRIPTION
**Pull request by dannyroberts**
Opening for tests for now

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue @nickpell This seems to work fine for the very limited thing I was testing, and the tests pass. Does anyone see any potential issue with it? Main thing to look out for is if any place specifically required a `ReportAppFilter` and not one of its subclasses that could break, but that seemed unlikely/unintuitive and I also couldn't find any.

**Comment by nickpell** [comment]
looks fine to me (fyi I don't think this code has any test coverage)

**Comment by czue** [comment]
:+1: by me (this is all @nickpell's domain though)

**Comment by dannyroberts** [comment]
Thanks! (and good to know)

**Pull request merged**
