### PR TITLE
Add automated test framework for AAA dashboard

### PR DESCRIPTION
**Pull request by emord**
Big surprise here: writing tests finds bugs and are super useful.

This is going to be very similar to the ICDS tests, except the csv data is only setup for a single class of tests instead of the module. I'm doing this to relieve some of the pain we've had when updating the CSV files there as its often caused many test failures in reports that are hard to change. This means that any reports being tested will insert their own data in their `setupclass` or `setUpTestData`. @lwyszomi FYI on this point.

Currently I've only added a single test case for a pregnant woman who was pregnant between 2018-08-01 -> 2019-05-01 (expected). Will be adding more test cases as I move forward, but wanted to get this out before it was too large

review commit by commit

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Looks fine though quite a bit of common code with the ICDS tests which could be pulled out into UCR testing utils.

**Comment by emord** [comment]
Getting a super weird failure on travis's partitioned setup that I can't reproduce:

```
ERROR: corehq.apps.commtrack.tests.test_xml:BugSubmissionsTestSQL.test_archived_form_gets_removed_from_case_xform_ids
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 221, in setUp
    super(CommTrackSubmissionTest, self).setUp()
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 60, in setUp
    self.domain = util.bootstrap_domain(util.TEST_DOMAIN)
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/util.py", line 54, in bootstrap_domain
    domain_obj = create_domain(domain_name)
  File "/mnt/commcare-hq-ro/corehq/apps/domain/shortcuts.py", line 11, in create_domain
    secure_submissions=False)
  File "/mnt/commcare-hq-ro/corehq/apps/domain/models.py", line 619, in get_or_create_with_name
    result = cls.view("domain/domains", key=name, reduce=False, include_docs=True).first()
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 914, in first
    return list(self)[0]
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 1022, in __len__
    return self.count()
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 945, in count
    self._fetch_if_needed()
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 979, in _fetch_if_needed
    self.fetch()
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 958, in fetch
    self._result_cache = self.fetch_raw()
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 975, in fetch_raw
    return self._fetch(self._arg, self.params)
  File "/vendor/lib/python2.7/site-packages/couchdbkit/client.py", line 757, in raw_view
    ddoc.fetch()
  File "/vendor/lib/python2.7/site-packages/cloudant/design_document.py", line 464, in fetch
    super(DesignDocument, self).fetch()
  File "/vendor/lib/python2.7/site-packages/cloudant/document.py", line 169, in fetch
    resp.raise_for_status()
  File "/vendor/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Object Not Found not_found missing for url: http://couch:5984/test_commcarehq__domains/_design/domain
```

I have no idea how my changes would have affected a couch view missing, but I merged master in an effort to fix it. If that does not get rid of the error, I may extract the code changes I made to merge until I can figure this one out

**Comment by emord** [comment]
I removed all the test code here. Going to open a separate PR tomorrow to see if I can figure out why one of the travis jobs fails. at a bit of a loss for now

**Comment by emord** [comment]
I pulled out all of the tests to retry them in a separate PR and attempt to track down the introduced failure in partitioned database test

**Pull request merged**
