### PR TITLE
Product id sql export

### PR DESCRIPTION
**Pull request by dannyroberts**
Fixes http://manage.dimagi.com/default.asp?225790

### CODE REVIEW

**Comment by dannyroberts** [comment]
@benrudolph fyi, @kaapstorm buddy

**Comment by snopoke** [comment]
Build failed

**Comment by dannyroberts** [comment]
@snopoke as far as you know, calling it "product_id" was just an oversight in the export code and the test code, right? E.g. this code isn't supposed to be able to run off both a LedgerValue (new ledger, which calls it `entry_id`) and StockState (old ledger, which did call it `product_id`), right?

**Comment by snopoke** [comment]
As far as I know that's correct. I'm pretty sure i added a `product_id` alias to `LedgerValue` in a PR that got merged today so if in doubt you could just leave it.

**Comment by dannyroberts** [comment]
@snopoke oh, well cool! I'll close this for now and revisit if your change somehow doesn't fix it.

**Pull request closed without merging**
