### PR TITLE
Remove couchdb from the staging/prod inventories

### PR DESCRIPTION
**Pull request by esoergel**
With it in there, a full stack ansible deploy attempts to compile couchdb on those machines.  We don't appear to be using it on a fab deploy anyways.

@dannyroberts we spoke about this on Friday, just want to double check that this is what we had in mind.

### CODE REVIEW

**Comment by czue** [comment]
I think we can also remove it from softlayer

**Comment by esoergel** [comment]
Sounds good.  Do you know what the [`_test1` thing](https://github.com/dimagi/commcare-hq/blob/master/fab/inventory/softlayer) is all about?
```
[_test1]
#10.162.36.196
localhost ansible_connection=local

[couchdb:children]
_test1
```
I can't tell what that's used for other than as a target for couchdb.

**Comment by czue** [comment]
@kaapstorm set that up but I think that's just a very poorly named ansible control machine, and a relic of initial setup/testing

**Comment by dannyroberts** [comment]
:+1: looks great, glad to have that confusing bit of config gone. @esoergel FF to self-merge when you're ready

**Pull request merged**
