### PR TITLE
keep yarn.lock frozen during tests

### PR DESCRIPTION
**Pull request by biyeun**
##### SUMMARY
`yarn install` creates a diff on tests in an unpredictable way if `yarn.lock` is not freshly created. this causes the `make requirements` test to fail. `yarn install --frozen-lockfile` ensures that `yarn.lock` doesn't get randomly regenerated during travis builds or when there are no changes to `package.json` on a fresh `yarn install`

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Review by esoergel — APPROVED** [review]
Guessing this supersedes https://github.com/dimagi/commcare-hq/pull/28167?

OOC, what does `yarn.lock` provide?  Is it more than just an artifact of `package.json`?

**Comment by biyeun** [comment]
@esoergel it's the replacement of `package.lock` for `yarn installs`. It locks in dependencies of dependencies versions as well.

**Review by dannyroberts — APPROVED** [review]

**Comment by biyeun** [comment]
I'm going to make one more change to this so that all versions are fixed to the ones currently on production. I don't want yarn automatically upgrading packages on install on all versions specified with `^`...who knows what kind of havoc that might wreak...

**Comment by snopoke** [comment]
build still failing at the same point

**Comment by biyeun** [comment]
@snopoke yeah i think the changes need to get pushed up to docker cloud. going to merge this in so that image can be rebuilt

**Comment by snopoke** [comment]
@biyeun since yarn.lock is in the repo I don't think it has anything to do with docker, the test is just checking that there are no git diffs.

**Comment by biyeun** [comment]
@snopoke it actually DOES matter. the `yarn install` command for docker was updated here https://github.com/dimagi/commcare-hq/pull/28168/files#diff-662906842d60defbe33d53b27fd9cc39R22

**Pull request merged**
