### PR TITLE
update django-websocket-redis

### PR DESCRIPTION
**Pull request by nickpell**
https://github.com/jrief/django-websocket-redis/blob/master/docs/changelog.rst

### CODE REVIEW

**Comment by nickpell** [comment]
@emord Do you have any suggestions for how to QA this?

**Comment by emord** [comment]
I think the only things that use web sockets are the someone else is editing this form warning in app manager and the dimagisphere

**Comment by nickpell** [comment]
tested on staging, looks good

**Review by emord — APPROVED** [review]
still has don't merge tag

**Pull request merged**
