### PR TITLE
Add app summary button to form builder

### PR DESCRIPTION
**Pull request by proteusvacuum**
The missing piece of the app building puzzle. How do you know what your app does? Look at the summary!

screenshot from 2019-02-06 22-53-16

### CODE REVIEW

**Review by gbova — APPROVED** [review]
This is awesome!

**Review by orangejenny — APPROVED** [review]
Was this a specific request from GS? Are you adding analytics? We went back & forth on whether or not to include the Manage Case button itself and don't really know if people use it. (And I see now that we didn't add analytics to it.)

**Comment by proteusvacuum** [comment]
@orangejenny yes, this was a specific request. The app summary is a useful tool during app building and currently requires more than one click to find (releases -> app summary). Having to go to releases first means it seems like looking at the app summary should only happen right before you make a build, which we'd like to move away from. 

(some people requested to have an automatically reloading app summary in a sidebar like app preview is... but this seems like a good first step)

Also, added analytics, thanks for the push to do that.

**Comment by orangejenny** [comment]
> some people requested to have an automatically reloading app summary in a sidebar like app preview is

oh my. thanks for the background.

**Pull request merged**
