### PR TITLE
Remove v1 ICDS UCRs

### PR DESCRIPTION
**Pull request by emord**
@sheelio you said that maybe we can do this soon/now?

@proteusvacuum

### CODE REVIEW

**Comment by sheelio** [comment]
I think we need a confirmation from Lilianna that we can trigger this .  I'll email her about it again.  Cal / Saket / Srikant have okayed it.

**Comment by emord** [comment]
@sheelio just added a couple more commits for more cleanup. Lilianna just approved this, so I think we can merge/deploy today?

@czue FYI that this should help out with lag/fewer db queries

**Comment by sheelio** [comment]
Yup, I think good to merge / deploy today.

**Comment by czue** [comment]
nice!! do async indicators just ignore references to deleted data sources?

**Comment by emord** [comment]
@czue yeah. they catch it and move on https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/userreports/tasks.py#L338-L341

**Comment by emord** [comment]
@czue fwiw i think that exception was causing those jobs to take longer. I've since run some manual commands to remove these. so there's a huge dropoff on the async ucr dashboard

**Pull request merged**
