### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by emord**
I think this broke tests last time, so opening pr

@amstone326 @wpride this should be updated since 2.36 is released right?

### CODE REVIEW

**Comment by orangejenny** [comment]
https://github.com/dimagi/commcare-translations/pull/41 should have fixed the tests that broke last release, permanently. Don't think there should be anything the HQ team has to do for each mobile release anymore. But mobile team can confirm.

**Comment by amstone326** [comment]
Hey @emord, so on each release mobile creates a PR [like this one](https://github.com/dimagi/commcare-translations/pull/42) in the commcare-translations repo. So that did get done and merged for 2.36. I think that, after @dannyroberts and I made our semi-recent changes to this process, there is now also something that needs to happen in this repo, but had forgotten / it has not been added into the mobile release checklist yet, which is why it hasn't been done. Are you clear on what the exact steps I should be adding are? If so I can do that now so it doesn't get missed on further releases.

**Comment by amstone326** [comment]
Also I'm curious what made you think to do this! (glad that you did)

**Comment by emord** [comment]
@amstone326 I was updating a different submodule and noticed this one needed to be updated too. @dannyroberts does anything else need to happen?

**Comment by amstone326** [comment]
@dannyroberts Can you let me know what steps I should add to the release checklist so that this will get taken care of in future releases?

**Comment by orangejenny** [comment]
Do the mobile scripts commit the submodule ref to the main hq repo? That could have slipped through the cracks (deployer used to take care of it, now it's on the developer).

**Comment by amstone326** [comment]
@orangejenny No that isn't currently being done. So that's all that needs to be added?

**Comment by orangejenny** [comment]
@amstone326 yeah, that should be all

**Comment by amstone326** [comment]
@orangejenny Correct me if I'm wrong, but because this step will involve creating a new branch in the commcare-hq repo, I think it will be much more complicated to automate the creation of that branch from within the mobile-deploy scripts than it was to do the automation for the PR in the commcare-translations repo. Does it seem reasonable to you for the step that gets added to the release checklist for this to just be "Create a ticket for interrupt to commit the commcare-translations submodule ref to the main hq repo"?

**Comment by orangejenny** [comment]
@amstone326 I'm curious why it's complicated to automate (maybe easier to offline about that?) but yeah, an interrupt ticket is fine.

**Comment by amstone326** [comment]
Hey, yea, would you mind offlining about this briefly whenever you have a
chance?

**Pull request merged**
