### PR TITLE
CVSU: ucr reports

### PR DESCRIPTION
**Pull request by kkrampa**

### CODE REVIEW

**Comment by kkrampa** [comment]
PR doesn't touch existing reports. Ported reports are hidden behind feature flag.

**Comment by kkrampa** [comment]
@czue Could you kick build?

**Comment by czue** [comment]
done

**Comment by czue** [comment]
@kkrampa who usually reviews these reports?

**Comment by kkrampa** [comment]
@czue I have no idea because original reports weren't done by Soldevelo devs.

**Comment by czue** [comment]
@snopoke is this you?

**Comment by kkrampa** [comment]
@czue By new reports I mean old reports ported to UCR so maybe you can just merge and then we can verify on domain that results are the same?

**Comment by czue** [comment]
I'll take a look sometime soon (but not today)

**Comment by snopoke** [comment]
Yea, I did the original. I can take a look next week.

**Comment by snopoke** [comment]
I didn't do any actual report QA but the code looks fine.

**Pull request merged**
