### PR TITLE
update phonenumberslite to latest version

### PR DESCRIPTION
**Pull request by nickpell**
Removes some incompatibilities with python 3.6.  See https://hub.docker.com/r/dimagi/commcarehq_py3/builds/b8mibreulkaarryn8ssphua/

@dimagi/py3

### CODE REVIEW

**Comment by millerdev** [comment]
Test failure possibly related?
```
FAIL: custom.enikshay.integrations.ninetyninedots.tests.test_repeaters:TestUpdatePatientPayloadGenerator.test_get_payload
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/enikshay/integrations/ninetyninedots/tests/test_repeaters.py", line 456, in test_get_payload
    payload = self._assert_payload_contains_subset(cases, expected_numbers)
  File "/mnt/commcare-hq-ro/custom/enikshay/integrations/ninetyninedots/tests/test_repeaters.py", line 346, in _assert_payload_contains_subset
    self.assertDictContainsSubset(expected_payload, actual_payload)
AssertionError: Mismatched values: u'treatment_supporter_phone_number', expected: u'+9166000666', actual: u'+91066000666'
-------------------- >> begin captured logging << --------------------
debug_user_save: INFO: single,a471ffe99a85425698fd382f675e4ea5,None,/mnt/commcare-hq-ro/corehq/apps/users/models.py:96:log_user_save,/a/enikshay-bets-updates/bets/payment_confirmation
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'fake-domain-from-mixin', u'', None, u'')
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'fake-domain-from-mixin', u'', None, None)
root: DEBUG: Saving new form: XFormInstance(form_id='2055e26c974d4707b19ba739c2e78506', domain='fake-domain-from-mixin')
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'fake-domain-from-mixin', u'', None, u'')
casexml.apps.phone.restore_caching: DEBUG: invalidating ('RestorePayloadPathCache', 'fake-domain-from-mixin', u'', None, None)
root: DEBUG: Saving new form: XFormInstance(form_id='9f33839c02ce484bacf851a7a1e2318f', domain='fake-domain-from-mixin')
```

**Comment by emord** [comment]
What are the incompatibilites that are fixed? This looks like a pretty big version jump at once. Would it be sufficient to use the last 7.x release?

**Comment by nickpell** [comment]
@emord This is the fix needed for py3.6:
https://github.com/daviddrysdale/python-phonenumbers/commit/3f3ee9a2b27da63138bdf72fa884c9c7a0bfc3e0

It is included in the 7.x series, but the updates here should also work.

**Review by millerdev — APPROVED** [review]
Looks good from here. Do we feel like this is well tested and not too risky?

**Comment by nickpell** [comment]
>  Do we feel like this is well tested and not too risky?

The other use cases of the library are much simpler, so I feel like this is good to release

**Pull request merged**
