### PR TITLE
Process repeat records concurrently

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: https://dimagi-dev.atlassian.net/browse/HI-451 and PR #23579

Use concurrent.futures to process repeat records without blocking on API calls.

(`futures` is backported to Python 2.7 from Python 3. It is already a requirement via s3transfer & tinys3. I should make it an explicit requirement, right?)

@czue @orangejenny @millerdev

### CODE REVIEW

**Comment by czue** [comment]
Nice, this is a great idea. 

I've seen us use `gevent` for similar use cases in the past. For my own education how is `concurrent.futures` different  / why'd you pick it?

**Review by czue — COMMENTED** [review]
Code looks good. Thinking about this, is it definitely true that this is more parallel / superior to how the celery concurrency stuff works today? I don't really have my head wrapped around how that works, but I know is also attempting to do parallelization in a similar fashion...

**Comment by kaapstorm** [comment]
This is slightly different from how Celery workers work. (Please forgive me if I'm about to explain stuff you already know.) In fact it's best to use the two together: parallelism (multi-processing, where code is running on multiple cores) + concurrency (multi-threading, where one core is switching between different blocks of code).

gevent, [asyncio](https://docs.python.org/3/library/asyncio.html) in Py3, and futures (the way I'm using it here) are concurrent but not parallel -- they switch between blocks of code like generators or coroutines. The idea is, rather than waiting for I/O, instead to switch away and do something else, and then come back when the I/O is finished. So each parallel Celery worker could get more done if it didn't have to wait for API responses, etc..

The problem I found was that I couldn't get gevent to pass control to another thread after it had sent an API request without waiting for the response. In Py3, the [aiohttp](https://aiohttp.readthedocs.io/en/stable/) library makes this easy. I also looked at [trollius](https://github.com/vstinner/trollius) which is a port of Py3's asyncio to Py2, but it's deprecated, and I'd prefer to avoid it.

Then I found that concurrent.futures can do exactly what we need. There is a [great blog post here](http://elliothallmark.com/2016/12/23/requests-with-concurrent-futures-in-python-2-7/) explaining what it's doing, and quantifying the speed difference.

**Comment by czue** [comment]
Sorry, I was referring to celery's built-in concurrency on gevent, which we already use: http://docs.celeryproject.org/en/latest/userguide/workers.html#concurrency

Does that change your answer or am I confused?

**Comment by kaapstorm** [comment]
Whoa! I didn't know Celery could use concurrency! Thank you for clarifying!

[Celery's examples](https://github.com/celery/celery/tree/master/examples/eventlet#tasks) look really promising! I'm trying to figure out how to use a Celery gevent pool for repeat records. Would the CELERY_REPEAT_RECORD_QUEUE just use a gevent pool instead of a prefork pool? Or would that mean that we get concurrency without parallelism? Maybe our own example(s?) would help ...

Do you know where we use this already? I didn't find anything with a quick grep, but I might have been looking for the wrong thing.

**Comment by czue** [comment]
I think we just use it by calling `-P gevent --concurrency {some_number}` [from the command line](https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/commcarehq/templates/supervisor_celery_workers.conf.j2#L8).

It looks like at least on prod it should already be doing this: https://github.com/dimagi/commcare-cloud/blob/master/environments/production/app-processes.yml#L18-L21

**Review by snopoke — COMMENTED** [review]
This is confusing to me. We're already using celery which does parallel processing. If we need to increase the throughput of the queue why wouldn't we just increase the number of celery workers? 

Also just to point out that they queue is using gevent so I'm not sure this will work well from inside a greenlet.

**Comment by snopoke** [comment]
Sorry, didn't read the existing comments, looks like you're already heading towards using celery's concurrency already.

**Comment by kaapstorm** [comment]
Thanks guys. Closing this PR in favour of adding workers.

**Pull request closed without merging**
