### PR TITLE
Cs/sc 2922 implement geocoder

### PR DESCRIPTION
**Pull request by Charl1996**
**Note: I'm not basing this PR off of master until https://github.com/dimagi/commcare-hq/pull/33494 has been merged.**

## Product Description
The GPS capture map now has an address bar where the user can type in the address of the specific mobile worker/case. A marker is placed on the selected address location and the input fields are updated accordingly. Only addresses are supported, so the user won't be able to select countries, regions, postal codes etc...only specific addresses.

What the map looks like with the marker at the selected address location:

image

## Technical Summary
A simple `MapboxGeocoder` object is added to the map controls for geocoding support.

## Feature Flag
Geospatial FF

### Safety story
Tested locally.

### Automated test coverage
No automated tests.

### QA Plan
No formal QA planned at this stage.

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by zandre-eng** [comment]
Great to see this supported out-the-box by MapBox! :rocket:

**Comment by mkangia** [comment]
Amazing!

**Review by SmittieC — COMMENTED** [review]
Nice

**Comment by Charl1996** [comment]
Closing this to clean up the commit history.

**Pull request closed without merging**
