### PR TITLE
move defaults before localsettings

### PR DESCRIPTION
**Pull request by sravfeyn**
@mkangia

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
Not sure but i guess this build failure was fixed in master. Merging master might resolve this.

**Comment by sravfeyn** [comment]
Thanks for the tip, merged!

**Comment by sravfeyn** [comment]
Thanks for the tip, merged!

**Comment by mkangia** [comment]
@sravfeyn Do we need this PR'ed against NIC deploy branch as well?

**Comment by sravfeyn** [comment]
I have patched this already

**Pull request merged**
