### PR TITLE
Add location.metadata to location fixture restore

### PR DESCRIPTION
**Pull request by esoergel**
this adds a block to each location like:

``` xml
<location_data>
    <best_swordsman>Sylvio Forel</best_swordsman>
    <in_westeros>false</in_westeros>
</location_data>
```

for a dict of the form:

``` json
{"best_swordsman": "Sylvio Forel",
 "in_westeros": false}
```

### CODE REVIEW

**Comment by czue** [comment]
@esoergel who did you talk to about how this is going to be used? seems an important design decision since once people start building apps off of this we're going to be locked in.

**Comment by esoergel** [comment]
I'll send out an email to commcare.supply.

**Comment by czue** [comment]
@esoergel please ping when spec is finalized and you want this reviewed again

**Comment by esoergel** [comment]
@czue go ahead.  I was hesitant about releasing it when it might not work in the form builder, but it won't break any existing functionality, and I'm pretty sure it will work for at least most use cases anyways.

**Pull request merged**
