### PR TITLE
make assert soft

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?223584

@snopoke cc @nickpell

### CODE REVIEW

**Comment by snopoke** [comment]
Any idea if this caused by something similar to this: http://manage.dimagi.com/default.asp?216573? If so we should ping cloudant

**Comment by czue** [comment]
I'm not sure. I can't seem to reproduce it locally. There are two Location documents that have been deleted but are somehow tripping the assertion. I'll know more after this is merged and deployed and pops up again.

**Comment by snopoke** [comment]
:+1: on :white_check_mark:

**Comment by czue** [comment]
:white_check_mark:

**Pull request merged**
