### PR TITLE
optimize exports

### PR DESCRIPTION
**Pull request by benrudolph**
@NoahCarnahan @dimagi/scale-team getting ready for the flip once the reindex is finished on prod

### CODE REVIEW

**Comment by benrudolph** [comment]
...and as of now:
```
Processed 5077000/27919391 of 5077000 documents in 3:14:13.886193 (14:33:43.287345 remaining)
```

**Comment by benrudolph** [comment]
gotta fix up tests but the reindex has finished:
```
Processed 27928391/27919391 of 27928391 documents (0 previously processed, 0 filtered out).
```
i'm now kind of interested in integrating `has_submissions` property in the deploy page...

**Comment by benrudolph** [comment]
✅

**Comment by czue** [comment]
sweet

**Comment by NoahCarnahan** [comment]
👍

**Pull request merged**
