### PR TITLE
regiser form change the hubspot info dictionary for the appcues test

### PR DESCRIPTION
**Pull request by mkaczmarczyksoldevelo**
@calellowitz could you please look at this?

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Comment by calellowitz** [comment]
looks good! thanks

**Comment by orangejenny** [comment]
@calellowitz Shouldn't this have showed up in sentry because of the `raise_for_status` in `_hubspot_post`? The only hubspot-related issue I see is https://sentry.io/dimagi/commcarehq/issues/231576701 which is a 502.

(Not that I was monitoring hubspot, more wondering if I should be and also if sentry is a good place to look for info about hubspot problems.)

**Comment by calellowitz** [comment]
It probably should show up in sentry, although I think we have had issues in the past with celery task exceptions not showing up there, so I do not know if it ever actually would. I believe I checked sentry after this issue was reported but did not look very hard, so it is possible I missed it.

**Comment by orangejenny** [comment]
It was in my head that this all happens immediately on the webworker, because it's during signup, but yeah, it's still an async task. Thanks, makes sense.

**Pull request merged**
