### PR TITLE
Reorganize fab-related files

### PR DESCRIPTION
**Pull request by dannyroberts**
The large commit is 100% moving files into fab/ (plus adding a fabfile.py that imports everything from fab.fabfile)

The other commit changes the way we specify which pillows should run on which setup.

I've been using this to deploy while testing ansible, and tested it yesterday on staging.

You can also run e.g. `python fabfile.py test_pillows production` to see which pillows will show up on a given environment (for debugging when you change the config).

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 25 errors:

* fab/fabfile.py, line 34 - E501 line too long (116 > 115 characters)
* fab/fabfile.py, line 62 - E123 closing bracket does not match indentation of opening bracket's line
* fab/fabfile.py, line 73 - E501 line too long (133 > 115 characters)
* fab/fabfile.py, line 187 - E303 too many blank lines (3)
* fab/fabfile.py, line 227 - E303 too many blank lines (3)
* fab/fabfile.py, line 359 - E231 missing whitespace after ','
* fab/fabfile.py, line 484 - F841 local variable 'redis' is assigned to but never used
* fab/fabfile.py, line 485 - F841 local variable 'memcached' is assigned to but never used
* fab/fabfile.py, line 492 - E303 too many blank lines (2)
* fab/fabfile.py, line 565 - E231 missing whitespace after ','
* fab/fabfile.py, line 790 - E501 line too long (119 > 115 characters)
* fab/fabfile.py, line 952 - E501 line too long (127 > 115 characters)
* fab/fabfile.py, line 990 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1105 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1129 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1154 - F821 undefined name 'loc'
* fab/fabfile.py, line 1155 - F821 undefined name 'remote'
* fab/fabfile.py, line 1221 - E261 at least two spaces before inline comment
* fab/fabfile.py, line 1221 - E262 inline comment should start with '# '
* fab/fabfile.py, line 1246 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1251 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1256 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1261 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1289 - E127 continuation line over-indented for visual indent
* fab/fabfile.py, line 1300 - E302 expected 2 blank lines, found 1

**Comment by dannyroberts** [comment]
Do people prefer leaving the fabfile content in the original fabfile.py rather than also going inside `fab/`? The point was just to get everything fab related into one place.

**Comment by dannyroberts** [comment]
(this is real; have to edit tests for pillow config code)

**Comment by dimagimon** [comment]
There are 27 errors:

* corehq/apps/hqadmin/tests.py, line 12 - F401 'get_pillow_actions_for_env' imported but unused
* fab/fabfile.py, line 34 - E501 line too long (116 > 115 characters)
* fab/fabfile.py, line 62 - E123 closing bracket does not match indentation of opening bracket's line
* fab/fabfile.py, line 73 - E501 line too long (133 > 115 characters)
* fab/fabfile.py, line 187 - E303 too many blank lines (3)
* fab/fabfile.py, line 227 - E303 too many blank lines (3)
* fab/fabfile.py, line 359 - E231 missing whitespace after ','
* fab/fabfile.py, line 484 - F841 local variable 'redis' is assigned to but never used
* fab/fabfile.py, line 485 - F841 local variable 'memcached' is assigned to but never used
* fab/fabfile.py, line 492 - E303 too many blank lines (2)
* fab/fabfile.py, line 565 - E231 missing whitespace after ','
* fab/fabfile.py, line 790 - E501 line too long (119 > 115 characters)
* fab/fabfile.py, line 952 - E501 line too long (127 > 115 characters)
* fab/fabfile.py, line 990 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1105 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1129 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1154 - F821 undefined name 'loc'
* fab/fabfile.py, line 1155 - F821 undefined name 'remote'
* fab/fabfile.py, line 1221 - E261 at least two spaces before inline comment
* fab/fabfile.py, line 1221 - E262 inline comment should start with '# '
* fab/fabfile.py, line 1246 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1251 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1256 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1261 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1289 - E127 continuation line over-indented for visual indent
* fab/fabfile.py, line 1300 - E302 expected 2 blank lines, found 1
* fab/pillow_settings.py, line 56 - F841 local variable 'pillow_actions' is assigned to but never used

**Comment by dimagimon** [comment]
There are 25 errors:

* fab/fabfile.py, line 34 - E501 line too long (116 > 115 characters)
* fab/fabfile.py, line 62 - E123 closing bracket does not match indentation of opening bracket's line
* fab/fabfile.py, line 73 - E501 line too long (133 > 115 characters)
* fab/fabfile.py, line 187 - E303 too many blank lines (3)
* fab/fabfile.py, line 227 - E303 too many blank lines (3)
* fab/fabfile.py, line 359 - E231 missing whitespace after ','
* fab/fabfile.py, line 484 - F841 local variable 'redis' is assigned to but never used
* fab/fabfile.py, line 485 - F841 local variable 'memcached' is assigned to but never used
* fab/fabfile.py, line 492 - E303 too many blank lines (2)
* fab/fabfile.py, line 565 - E231 missing whitespace after ','
* fab/fabfile.py, line 790 - E501 line too long (119 > 115 characters)
* fab/fabfile.py, line 952 - E501 line too long (127 > 115 characters)
* fab/fabfile.py, line 990 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1105 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1129 - E124 closing bracket does not match visual indentation
* fab/fabfile.py, line 1154 - F821 undefined name 'loc'
* fab/fabfile.py, line 1155 - F821 undefined name 'remote'
* fab/fabfile.py, line 1221 - E261 at least two spaces before inline comment
* fab/fabfile.py, line 1221 - E262 inline comment should start with '# '
* fab/fabfile.py, line 1246 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1251 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1256 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1261 - E302 expected 2 blank lines, found 1
* fab/fabfile.py, line 1289 - E127 continuation line over-indented for visual indent
* fab/fabfile.py, line 1300 - E302 expected 2 blank lines, found 1

**Pull request merged**
