### PR TITLE
run both sharded and js tests on same runner

### PR DESCRIPTION
**Pull request by benrudolph**
@dimagi/test-team maybe a bad idea, but we can certainly fit both these test suites on one runner. it's not as clean though

### CODE REVIEW

**Comment by snopoke** [comment]
Makes sense to me

**Review by emord — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by benrudolph** [comment]
TEST=python-sharded-and-javascript JS_SETUP=yes
 23 min 36 sec

👷 🔫

**Comment by snopoke** [comment]
Nice, although this doesn't reduce the total build time it does mean less concurrent VM's required per PR which should improve our throughput.

**Comment by benrudolph** [comment]
1 less VM and 1 less pull down of docker, so i think it shaves 5 or so minutes

**Pull request merged**
