### PR TITLE
Update inventories for elasticsearch node host_name

### PR DESCRIPTION
**Pull request by TylerSheffels**
Will be required with upcoming ansible PR

### CODE REVIEW

**Comment by TylerSheffels** [comment]
India doesn't have an ES host, which seems odd

**Comment by dannyroberts** [comment]
not mergeable

**Comment by dannyroberts** [comment]
(fixed)

**Comment by TylerSheffels** [comment]
@dannyroberts Thanks for rebasing, should be good to go now.

**Pull request merged**
