### PR TITLE
Remove xform user registration handling

### PR DESCRIPTION
**Pull request by dannyroberts**
https://trello.com/c/mrl9gPPC/3-user-registration-j2me

### CODE REVIEW

**Comment by czue** [comment]
man this code is a blast from the past.

we should also get rid of https://bitbucket.org/javarosa/javarosa/wiki/UserRegistrationAPI and the pointer on https://confluence.dimagi.com/display/commcarepublic/CommCare+HQ+APIs. have you done any due diligence to make sure no one is relying on this in an API-like fashion?

**Comment by czue** [comment]
:+1: once confirmed this is safe

**Comment by dannyroberts** [comment]
That's a good point. I was relying on work Product did to make sure no J2ME projects were relying on this, but we probably never checked direct API/scripting usage. I would be quite surprised if anyone were, but we can check whether it's in active use by adding a soft_assert. To me if no one uses it for a couple weeks, I'd say I'm not concerned if someone uses it occasionally and we didn't pick it up in the 2-week period; in that case they'll almost certainly notice that it fails next time they use it, and they can use excel upload or the supported User Creation API instead. Sound good?

**Comment by czue** [comment]
yeah that sounds fine to me. we can probably update the docs now.

**Comment by dannyroberts** [comment]
@czue https://github.com/dimagi/commcare-hq/pull/12469

**Comment by dannyroberts** [comment]
The [someone actually called CommCareUser.create_or_update_from_xform](https://github.com/dimagi/commcare-hq/pull/12469/files#diff-16ce9f2eb3be0695a91eca75714bb3b7R1442) soft assert hasn't been triggered in the ~3 weeks it's been live.

**Comment by dannyroberts** [comment]
After this is merged (or at the same time), https://github.com/dimagi/dimagi-utils/pull/380 can be too

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
