### PR TITLE
Remove site

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 5 errors:

* corehq/apps/users/exceptions.py, line 7 - E302 expected 2 blank lines, found 1
* corehq/apps/users/views/__init__.py, line 193 - E501 line too long (176 > 115 characters)
* corehq/util/context_processors.py, line 1 - F401 'datetime' imported but unused
* corehq/util/context_processors.py, line 129 - E124 closing bracket does not match visual indentation
* corehq/apps/locations/_design/views/users_by_location_id/map.js, line 1 - Missing name in function declaration.

**Comment by dannyroberts** [comment]
oops wrong base branch

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
build fail looks unrelated

**Pull request merged**
