### PR TITLE
add unique constraint to prevent race conditions with partner analytics

### PR DESCRIPTION
**Pull request by biyeun**
## Technical Summary
This should prevent the race condition that caused this issue from happening again
https://dimagi-dev.atlassian.net/browse/SAAS-13243

### Safety story
improves safety

### Automated test coverage
this area of the codebase has tests

### QA Plan
No

### Migrations

- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
I don't see the migration. Did you forget to add it?

It's probably a good idea to apply this migration in a private release rather than as part of deploy since it may not apply cleanly if there are any records that block creation of a unique constraint. If such records exist, then the migration will need to be updated with a script to merge and clean up duplicates.

Third party environments will not have a clear path forward if that script is absent and they hit that scenario.

Would it be reasonable to develop that script so that all environments have a clear upgrade path?

**Comment by biyeun** [comment]
@millerdev yep, i seemed to have missed that one. sorry!

**Review by millerdev — APPROVED** [review]
Offlined with @biyeun. She said this feature is unlikely to be used anywhere except on production. She will setup a private release on production and apply the migration there to ensure it does not block deploy.

**Comment by biyeun** [comment]
tested and cleaned up! ✅

**Pull request merged**
