### PR TITLE
Minor repeater cleanup

### PR DESCRIPTION
**Pull request by benrudolph**
This does a bit of cleanup around the UI and starts recording the failure reason for a repeat record. Making that failure reason available in the UI is going to take a bit more work

Here are some screenshots:

Failure when link fails:
screen shot 2015-12-05 at 11 45 51 am
When link succeeds:
screen shot 2015-12-05 at 11 45 36 am
When HQ chokes:
screen shot 2015-12-05 at 11 52 21 am

cc: @czue :blowfish: if you want

### CODE REVIEW

**Comment by czue** [comment]
build fail likely real
```
======================================================================
FAIL: test_repeater (corehq.apps.repeaters.tests.test_repeater.RepeaterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/repeaters/tests/test_repeater.py", line 143, in test_repeater
    self.assertEqual(len(repeat_records), 2)
AssertionError: 3 != 2
----------------------------------------------------------------------
```

**Comment by czue** [comment]
looks good. :+1: to merge from my side once tests are fixed. Will give @biyeun a chance to comment on the crispy/html question too

**Comment by benrudolph** [comment]
thanks, should be fixed this go around

**Comment by biyeun** [comment]
@benrudolph @czue Didn't get a chance to review this as I was offline. My recommendation is that https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/style/crispy.py#L155 is used here as the nested `crispy.Div` thing is a little weird and difficult to parse on first glance. note, an empty label shouldn't be necessary. I also would put the error AFTER the button, as adding it before will cause the button to jump down after it's clicked, which is never good for a ui element. 

Sorry these weekend PRs carrying over to offline time don't give me a good chance to comment on things. This is OK merged as is, but this cleanup would be optimal.

Use a template like:
```
<div class="form-group">
  <div class="col-sm-9 col-md-8 col-lg-6">
    <button /> 
    <p class="help-block">error text</p>
  </div>
</div>
```

**Comment by benrudolph** [comment]
good suggestions. will update when i get a few spare cycles. put it on my
todo list

**Comment by benrudolph** [comment]
(currently pushing on scale, but won't forget about it)

**Comment by biyeun** [comment]
coolio sounds good :+1:

**Pull request merged**
