### PR TITLE
turn set to list before passing to celery task using JSON serializer

### PR DESCRIPTION
**Pull request by nickpell**
https://sentry.io/organizations/dimagi/issues/1065393976/

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
"Don't pass sets to celery" seems like a non-intuitive rule to remember. Do you think there's any way to catch this in code?

**Comment by nickpell** [comment]
If this code has test coverage, we could patch ```.delay``` to run the serializer even when celery is set to always eager.  We'd want to apply that across all of our tests.

**Comment by dannyroberts** [comment]
@nickpell is the serializer used set per task? Where is it set for this task? Is pickle still the default serializer?

**Comment by nickpell** [comment]
@dannyroberts JSON is the default.  Pickle is used only when it is specific in the task decorator.

**Comment by esoergel** [comment]
> If this code has test coverage, we could patch .delay to run the serializer even when celery is set to always eager. We'd want to apply that across all of our tests.

That's a great idea.  I'd even go so far as to say we should extend `@task` to _always_ run the serializer, so it doesn't perform differently in different contexts.

In theory, we could also use that as a place to soft check for bad-practice things like passing really large objects as params.

**Pull request merged**
