### PR TITLE
Remove css-grid-polyfill-binaries and references

### PR DESCRIPTION
**Pull request by dannyroberts**
## Technical Summary
The `css-grid-polyfill-binaries` library was first added in 2016 while some css features had insufficient browser support. What's nice about removing it is it'll take about 125ms off the user-facing response time of hitting the Search button on case search screens where grids are used, because that was previously causing it to refetch this polyfill library. We could have tried to fix that redundant fetching, but since there's broad browser support now for the style that this polyfill was originally added for, it seems better to just remove.

## Feature Flag
None

### Safety story
This change should only affect web apps case tiles, and there should be no user-facing effect. All browsers since about 2017 support [CSS grid layout](https://en.wikipedia.org/wiki/CSS_grid_layout) (thanks for the reference, @orangejenny!).

I'll also do QA to validate this.

### Automated test coverage

None

### QA Plan

I'm going to put this on staging and ask QA to go through a representative workflow on a number of browsers.

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Thanks, @dannyroberts , this is a nice bit of tech debt to clean up - and every little performance boost helps.

**Comment by dannyroberts** [comment]
I plopped this on staging and navigated to the same app on staging that I originally noticed this on in production and everything looks fine, and the script isn't loaded. Will flag for QA team

**Review by biyeun — APPROVED** [review]
great! thank you!

**Review by nospame — APPROVED** [review]
Nice.

**Comment by orangejenny** [comment]
Please do not merge this today - if you need it to go out soon, let's talk.

**Review by AmitPhulera — APPROVED** [review]

**Pull request merged**
