### PR TITLE
use hqDefine for users/js/roles.js

### PR DESCRIPTION
**Pull request by dannyroberts**
you'll want to use w=1

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/apps/users/static/users/js/roles.js, line 20 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 18 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 126 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 141 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 139 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 45 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 124 - Missing trailing comma. (comma-dangle)

**Comment by dimagimon** [comment]
There are 7 errors:

* corehq/apps/users/static/users/js/roles.js, line 20 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 18 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 126 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 141 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 139 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 45 - Missing trailing comma. (comma-dangle)
* corehq/apps/users/static/users/js/roles.js, line 124 - Missing trailing comma. (comma-dangle)

**Comment by dannyroberts** [comment]
Deployed to staging and the one page potentially affected looks fine

**Comment by dannyroberts** [comment]
@gcapalbo buddy

**Pull request merged**
