### PR TITLE
Add notes to reporting diff models

### PR DESCRIPTION
**Pull request by emord**
This might be helpful to keep track of and better document any differences and exceptions. because the differences aren't always obvious. Also considered a boolean 'resolved' or an assignee field, but wasn't sure if that would also be useful. let me know what you think

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]
I'm not sure whether you need `from __future__ import absolute_import` in migrations like Stickler says, but @nickpell will know.

**Comment by kaapstorm** [comment]
Hmmm. I think `assignee` and `resolved` could be a good idea. ... Or we could set conventions where assignee and "[resolved]" are given in the notes, kinda like old-style [forum topics](https://ubuntuforums.org/showthread.php?t=2130640). 

Separate fields might be neater, and useful if we want to display / filter by them in Django Admin. Yeah, I'm leaning to extra fields.

**Review by snopoke — APPROVED** [review]

**Comment by snopoke** [comment]
I was thinking we'd just delete them once they were resolved.

**Comment by emord** [comment]
fine if we delete them later. this is only going to be used for the citus migration at the moment. we can always add more columns if we find we don't like this workflow

**Pull request merged**
