### PR TITLE
Add indian financial year date filter

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi-dev.atlassian.net/browse/ICDS-1393?focusedCommentId=52567

##### SUMMARY
Add an options to use Current Indian Financial Year as a date filter for reports.

##### FEATURE FLAG
`Mobile UCR` but this is also available in Report Builder

##### RISK ASSESSMENT / QA PLAN
These date filters are shown at two places
1. [for mobile UCRs](https://github.com/dimagi/commcare-hq/blob/2c8cce2ecf180e3b2c7d645a7d0c88dd4bd41f97/corehq/apps/app_manager/views/modules.py#L319) which is needed here and confirmed it in UI.
Screenshot 2020-05-27 at 3 52 03 PM

2. But it also appears in [Report Builder](https://github.com/dimagi/commcare-hq/blob/83e0d70603902364fb6ac062117cddd1e4397aac/corehq/apps/userreports/views.py#L614)
Screenshot 2020-05-27 at 3 53 03 PM

Considering the effected environments I assume this should be okay to appear in all usages of these date filters since they are either staging or in India. Before considering restricting this to just mobile UCRs, want to check about it before I go about passing domain everywhere to check for feature flag which would be some lift.

##### PRODUCT DESCRIPTION
Adds an option for filter by Indian financial year for date filters in Mobile UCRs and also in Report Builder

##### ENVIRONMENTS
India, ICDS, ICDS-Staging

### CODE REVIEW

**Comment by orangejenny** [comment]
> before I go about passing domain everywhere to check for feature flag which would be some lift

Can you say more about this? This is a small feature that I'd expect to be flagged, not to involve a new environment-level setting. I don't see that many calls of `get_all_daterange_choices` - though I didn't follow the entire tree, so I believe that it becomes messy somewhere.

Would it be easier if you didn't send a domain into `get_all_daterange_choices` but instead filtered at the UI level? It looks like report builder calls `get_simple_dateranges` directly in a `page_context` function. Mobile UCR might be trickier.

**Comment by orangejenny** [comment]
Have you chatted with product about this? I wonder if they'd be okay with this date range being available globally or might have another creative suggestion for how to limit it (projects that use IST?).

**Comment by mkangia** [comment]
hey @orangejenny 
> Can you say more about this? This is a small feature that I'd expect to be flagged, not to involve a new environment-level setting

Few things,
1. Didn't add a new environment level setting, just used the set server environment
2. these date filters are mostly set globally. If you see `get_all_daterange_slugs` and `get_simple_dateranges` that call and then other places where these are used are also during code initialisation like
https://github.com/dimagi/commcare-hq/blob/1b4a2a6c08ca3b50a4e6e86e2c57220a64f32b5c/corehq/apps/userreports/reports/filters/values.py#L194
https://github.com/dimagi/commcare-hq/blob/3380d02e3cb8d22abff78b0f9697582066cd1c19/corehq/apps/saved_reports/models.py#L87
where these would need to be dynamically fetched for a domain which will get really messy.

> Would it be easier if you didn't send a domain into get_all_daterange_choices but instead filtered at the UI level?

There is an additional lift of even having domain available where these are called. They are called at places other than UI as well.

> Have you chatted with product about this? I wonder if they'd be okay with this date range being available globally or might have another creative suggestion for how to limit it (projects that use IST?).

Sure I can do that. To add, projects using IST again brings the limitation of passing domain which is a challenge.

**Comment by djmore9** [comment]
india and icds environments only please. Offlined with Manish.

**Comment by mkangia** [comment]
thanks @djmore9 , updated to exclude staging.

@orangejenny @esoergel this should be good to review though let me know if you think we should still reconsider the implementation.

**Review by esoergel — APPROVED** [review]
So long as SaaS is okay with this being on India, this change seems fine to me

**Pull request merged**
