### PR TITLE
Changed build comment search to ES

### PR DESCRIPTION
**Pull request by emord**
@orangejenny as we talked about. will do a bit more testing tomorrow with this, but this should work as a performance improvement.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
Noting this is largely a revert/followup for https://github.com/dimagi/commcare-hq/pull/21952

**Comment by emord** [comment]
I've changed this to a "search string query" because that will do case insensitive, partial matching and falls more in line with what I would expect from this box. For example with ICDS there are three recent builds:

1. Reverted to version 15372 - LATEST IN DEVELOPMENT STREAM
2. File ready to be sent for English -LATEST IN V1 TRANSLATION STREAM
3. Reverted to version 15362-Translation stream 

|query | filter in python | query ES | search string query ES |
|----|----|----|---|
| trans | 2 & 3 | 2 | 2 & 3 |
| TRANSLATION | 2 & 3 | 2 | 2 & 3 |
| ation | 2 & 3 | None | 2 & 3 | 
| ranslation | 2 & 3 | 2 | 2 & 3 | 
| anslation | 2 & 3 | 2 | 2 & 3 | 
| nslation | 2 & 3 | None | 2 & 3 | 
| slation | 2 & 3 | None | 2 & 3 | 
| ation | 2 & 3 | None | 2 & 3 | 
| 15362-Translation | 2 & 3 | 2 & 3 | 2 & 3 |

I was surprised the initial two queries missed build 3, but I think it may be due to some tokenizer not 
properly splitting out. I was also surprised it did not handle 'ation', or other sub strings correctly

I don't see anything from the [original PR](https://github.com/dimagi/commcare-hq/pull/21761) that would have suggested this was intended, so I think going iwth search_string_query is better

**Review by orangejenny — APPROVED** [review]
Agree with the search string query change, and thank you for laying out the examples clearly. @proteusvacuum might find them interesting.

**Comment by proteusvacuum** [comment]
Maybe I missed this, but did we do anything to ensure that new builds are picked up by ES immediately?

**Comment by emord** [comment]
@proteusvacuum we did not, but Jenny and I had talked about that a bit, and the compromise that this takes, is its still pulling hte latest builds from Couch, but when you search ES will be used. The likelihood of someone searching for a build that's in the past 5 builds and that those aren't picked up by ES seems pretty small

**Comment by proteusvacuum** [comment]
got it, didn't look closely enough at the if statement that was just outside the diff. Seems like a good compromise for now.

**Pull request merged**
