### PR TITLE
Case attachment drops

### PR DESCRIPTION
**Pull request by millerdev**
Follow-up for https://github.com/dimagi/commcare-hq/pull/21106. The only changes here are in 070b951 and e8a9520, all other commits are in the other PR.

@snopoke @jmtroth0

### CODE REVIEW

**Comment by dannyroberts** [comment]
Looks like we're seeing issues with this on prod (only env deployed so far): https://sentry.io/dimagi/commcarehq/issues/617775498/

**Comment by snopoke** [comment]
It's possible it was transient since the SQL functions use the table as the data type

**Comment by millerdev** [comment]
@snopoke Is there a better way to structure these migrations to prevent errors on deploy?

**Comment by snopoke** [comment]
I can't think of a better way. Even if we don't use the tables and just use
Records for the data types we'd still have the issue that one DB get's
updated before the other. Maybe we could create temp functions and then
rename them but that still seems like it could suffer from the same issue.
I suppose we could do this (assuming we aren't using tables as the data
types):

* create new function on shard DB (get_case_v2) (leaving old function
intact)
* update plroxy to use new function
* drop old function

**Comment by millerdev** [comment]
Alright, just wanted to make sure I wasn't doing something obviously wrong. I'm going to allow this to roll out as is unless you think it's too disruptive and should be changed.

**Comment by snopoke** [comment]
I'm happy to roll this out as is

**Pull request merged**
