### PR TITLE
Add halting migration to block if sms / ivr backend migration scripts haven't run

### PR DESCRIPTION
**Pull request by gcapalbo**

### CODE REVIEW

**Comment by gcapalbo** [comment]
This is tested and good to go, but going to close it since I want to run the scripts manually first to avoid deploy interruption.

**Comment by gcapalbo** [comment]
@NoahCarnahan @snopoke code review buddies

**Comment by snopoke** [comment]
LGTM. Just checking that its good to merge now. If so feel free to self merge.

**Comment by gcapalbo** [comment]
yup, good to merge

**Pull request merged**
