### PR TITLE
Remove load test report

### PR DESCRIPTION
**Pull request by gcapalbo**
http://manage.dimagi.com/default.asp?230039
@esoergel / @dannyroberts 
@czue

### CODE REVIEW

**Comment by gcapalbo** [comment]
it also seems like we can remove the entire loadtest directory and the corehq.apps.hqadmin.multimech module. @dannyroberts / @esoergel is that right?

**Comment by czue** [comment]
yep, i think that's right

**Comment by czue** [comment]
:skull: on :white_check_mark:

**Comment by dannyroberts** [comment]
Yeah, that would be awesome

**Comment by gcapalbo** [comment]
ok, updated to also remove the loadtest directory and multimech module. i did a search and couldn't find any references to either

**Comment by dannyroberts** [comment]
Build fail looks real
```
======================================================================
ERROR: test_authenticate_as (corehq.apps.hqadmin.tests.test_authenticate_as.AuthenticateAsIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/hqadmin/tests/test_authenticate_as.py", line 91, in test_authenticate_as
    resp = self.client.get(reverse(AuthenticateAs.urlname))
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 470, in get
    **extra)
  File "/vendor/lib/python2.7/site-packages/django/test/client.py", line 286, in get
    return self.generic('GET', path, secure=secure, **r)
...
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/vendor/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/vendor/lib/python2.7/site-packages/django/template/base.py", line 1136, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/mnt/commcare-hq-ro/corehq/tabs/templatetags/menu_tags.py", line 106, in format_sidebar
    sections = active_tab.sidebar_items if active_tab else None
  File "/mnt/commcare-hq-ro/corehq/tabs/tabclasses.py", line 1506, in sidebar_items
    'url': reverse('loadtest_report')},
  File "/vendor/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/vendor/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'loadtest_report' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
-------------------- >> begin captured logging << --------------------
auditcare.middleware: DEBUG: Middleware is running in a test context, disabling monkeypatch
--------------------- >> end captured logging << ---------------------
```

**Comment by gcapalbo** [comment]
@dannyroberts yep, that should be fixed with the last commit

**Comment by dannyroberts** [comment]
Nice, beat me to it. Looks good on ✅

**Pull request merged**
