### PR TITLE
Catch when the user's location has been deleted

### PR DESCRIPTION
**Pull request by kaapstorm**
Context: http://manage.dimagi.com/default.asp?243286

Opening for review. I'll add more commits to address the other items in the ticket, and tests.

@esoergel @mkangia cc @biyeun @sravfeyn

### CODE REVIEW

**Comment by esoergel** [comment]
Thanks for the follow-up, Norman.  I'd also be happy to merge these fixes in piecemeal if you don't think they all need to come in together.

**Comment by kaapstorm** [comment]
Good call @esoergel. They don't need to come in together, and piecemeal is a much better idea. Dropping "hold off".

**Comment by mkangia** [comment]
@kaapstorm To understand this better, we are ignoring a case where a location that does not exist is assigned in bulk upload by assigning no location instead?
If thats the case i see this can be misleading since a user would end up having no location even when expected to have some location after a successful import. Would be better to skip the import and notify user via email if this is done async.

**Comment by kaapstorm** [comment]
Hey @mkangia , this change only applies to downloading mobile workers. e.g. A user wants to download a list of mobile workers but at least one of them is currently assigned to a location that no longer exists. As the codebase stands at the moment, HQ will 500 when it tries to get that location. This change will set the mobile worker's location to None in the downloaded document, but won't modify the mobile worker's record.

**Comment by mkangia** [comment]
@kaapstorm i thought this was upload since the file name was 'users/bulkupload`. Sorry!

**Pull request merged**
