### PR TITLE
Upgrade gevent and greenlet

### PR DESCRIPTION
**Pull request by millerdev**
I think the only thing holding these back was `gipc`, which [has been removed](https://github.com/dimagi/commcare-hq/pull/30354).

A newer version of gevent is required before we can upgrade to Python 3.9 because v1.4.0, which is no longer supported, cannot be installed there.

### Safety story

This seems like a big upgrade, but on the other hand might just work? Should probably deploy to staging and do some QA.

### Automated test coverage

Dependency upgrade. No new tests added.

### QA Plan

https://dimagi-dev.atlassian.net/browse/QA-3632

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by joxl — APPROVED** [review]
Looks "simple" enough. I'm curious how we would expect an upgrade failure to manifest itself. Did you do any research on why the new version brings the additional zope dependencies?

**Review by calellowitz — CHANGES_REQUESTED** [review]
gevent and greenlet have a lot of issues with certain versions of those libraries only working with certain versions of python (as underlying c library changes, I believe), so I think we will want to more carefully pin the version and make sure the exact gevent and greenlet versions play nicely with the python version we plan to migrate to, rather than `>`, and I think we definitely want to do careful testing on staging, even if the python api hasn't changed

An example gevent ticket showing multiple of the times it has happened:
https://github.com/gevent/gevent/issues/1260

And the last time it bit dimagi:
https://github.com/dimagi/commcare-hq/pull/28869

**Comment by calellowitz** [comment]
@millerdev That all makes a lot of sense to me, and agree that the issues I am concerned about are resolved by setting a lower bound known to work with our version of python. I do have one question that may be as much about my lack of understanding of `pip-compile` as anything else.

> All libraries are pinned to a specific version in requirements.txt files, which are built with pip-compile. requirements.txt controls what is installed, and is the gold standard of what is tested and known to work with any given version of HQ.

It is my understanding that pip compile is run every time a dependency is upgraded, added, or removed. That is not an infrequent occurrence. Does not pinning the top version mean that unrelated libraries may get updated each time you make a requirements change, or do upgrades only happen explicitly even without pinning?

**Comment by millerdev** [comment]
@calellowitz no. Quoting the [`pip-compile` docs](https://github.com/jazzband/pip-tools/)
> **Note**: If ``pip-compile`` finds an existing ``requirements.txt`` file that fulfils the dependencies then no changes will be made, even if updates are available. To compile from scratch, first delete the existing ``requirements.txt`` file, or see [Updating requirements](https://github.com/jazzband/pip-tools/#updating-requirements) for alternative approaches.

**Review by calellowitz — APPROVED** [review]

**Pull request merged**
