### PR TITLE
fix app_label for DomainRequest

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?217936

introduced in https://github.com/dimagi/commcare-hq/pull/10380

### CODE REVIEW

**Comment by nickpell** [comment]
@benrudolph looks like this is it, waiting on tests

**Comment by nickpell** [comment]
confirmed on staging that this fixes the issue

**Comment by czue** [comment]
@esoergel fyi

**Comment by benrudolph** [comment]
thanks @nickpell

**Comment by esoergel** [comment]
crap, thanks!

**Pull request merged**
