### PR TITLE
Removed deprecated export models

### PR DESCRIPTION
**Pull request by orangejenny**
I was looking at rarely-used couch views, found `form_question_schema` and then couldn't find any references to the related models, `FormQuestionSchema` and `QuestionMeta`.

@esoergel @dannyroberts do either of you know the history here or if there's a reason to keep these around?

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
Looks good to me, but Danny and/or Ethan should probably give final approval.

**Comment by dannyroberts** [comment]
I remembered doing a big cleanup of related stuff which I think I found here: https://github.com/dimagi/commcare-hq/pull/23669. That's the last time `FormQuestionSchema` was mentioned in our git history. It looks like during that clean up I became focussed on testing whether one remaining entrypoint that used all that stuff was being used, and I imagine I just missed some of these things that really could have been deleted

**Review by dannyroberts — APPROVED** [review]

**Review by esoergel — APPROVED** [review]
Yeah, seems reasonable to me - don't recall any context on these models.

**Comment by orangejenny** [comment]
Great, thanks all for the thoughts.

This doesn't need a reindex after all since it deletes the only view in `corehq/couchapps/form_question_schema/views`. I'll merge it tomorrow and then run `prune_couch_views` to remove the view.

**Comment by orangejenny** [comment]
Deployed to prod and india, leaving decision about whether or not to run `prune_couch_views` to @dannyroberts as discussed on slack.

**Comment by dannyroberts** [comment]
I ran prune_couch_views on india. Thanks @orangejenny!

**Pull request merged**
