### PR TITLE
delete all types of SQL forms when deleting a domain

### PR DESCRIPTION
**Pull request by nickpell**
Previously, we were only deleting XFormInstance.

@ctsims

### CODE REVIEW

**Comment by ctsims** [comment]
Hi Nick,

Does this also address the cases that we're still on the system?

**Comment by nickpell** [comment]
@ctsims The "cases" were deleted, but the data still existed in elasticsearch.  I'm adding this assertion to check that this doesn't happen again: https://github.com/dimagi/commcare-hq/pull/21922

**Comment by nickpell** [comment]
✅

**Comment by nickpell** [comment]
bump

**Review by proteusvacuum — APPROVED** [review]

**Pull request merged**
