### PR TITLE
drop debug statement

### PR DESCRIPTION
**Pull request by orangejenny**
@dannyroberts is it cool to remove this? console's getting crowded.

### CODE REVIEW

**Comment by benrudolph** [comment]
i vote yes!

**Comment by czue** [comment]
same, don't see any reason this should be necessary

**Comment by orangejenny** [comment]
build fail is the unrelated DomainPillow error. restarted.

**Comment by proteusvacuum** [comment]
:+1:

**Comment by dannyroberts** [comment]
Yes, thanks!

**Pull request merged**
