### PR TITLE
Populate Appcues id to Enable Appcues for Web Apps

### PR DESCRIPTION
**Pull request by Jtang-1**
## Product Description

Enables Appcues to be configured for web apps

## Technical Summary

Adds the appcue ID to web Apps by checking the path contains `/cloudcare/apps/v2/` 
Related [AppCue Doc](https://studio.appcues.com/settings/installation/guide/script)
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/USH-3551?focusedCommentId=293588&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-293588)
## Feature Flag

None
### Safety story

Locally tested, change expands app cues availability which doesn't pose a safety risk.

### Automated test coverage

no automated test

### QA Plan

no QA

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by mjriley** [comment]
Are we sure this is safe? The reason we felt comfortable adding an exception for ERM was because ERM was hidden behind our higher-end plans and the number of people able to access the administration pages was minimal. Enabling this for WebApps seems to essentially enable AppCues for our entire customer base, which would defeat the purpose of the check. If we have doubts around this, I would recommend reverting this and determining how many new users this is going to expose us to. My concern is that this puts over our account's user cap

**Comment by Jtang-1** [comment]
Thanks for flagging Matt. Including here the additional context you provided me over slack + the email conversation you had with appcues:
Our current plan has a MAU (Monthly Active User) cap of 10k with the current usage being ~2k/month (in particular from new users). It's unique per user and it occurs on page load even if the user doesn't trigger any flow. If we exceed the limit, there won't be a disruption to our account, but someone from appcue will contact us to coordinate either upgrading our plan or reducing our usage. 

I ran this script to get a count of unique users that navigated into web apps and from Jan-Sep 2023, and it's ~4.5k/month, so with this usage, we should still be within the account's user cap.

I'll note in the ticket this usage concern and if can implement a way to restrict to only web apps that use flow. Otherwise, I think we can proceed and revert if we do exceed the user cap (although I don't expect to based on the query count). Are we comfortable with that approach? And would you recommend I pull in anyone else from SaaS for their input?

[Web App Usage script.txt](https://github.com/dimagi/commcare-hq/files/13127222/Web.App.Usage.script.txt)

**Comment by mjriley** [comment]
Appreciate the followup @Jtang-1 . The script looks good, and I'd say with those usage levels, we can likely go live with this. I think we should rope in @kcowger on this, though. I'm not sure which division owns AppCues, but with this expected usage, and assuming this flow is specific to USH, that would mean USH is responsible for the bulk of AppCues traffic.

**Comment by orangejenny** [comment]
Thanks @Jtang-1 and @mjriley for working through this. I agree we may get to a place where most Appcues users are USH users, though I also expect we'll stay well below the 10k limit. @kcowger let me know if you want to discuss further.

**Comment by kcowger** [comment]
@orangejenny happy to chat about it. For the purposes of this PR it sounds like it's safe to proceed.

**Pull request merged**
