### PR TITLE
Fix subscription page pricing table

### PR DESCRIPTION
**Pull request by dannyroberts**
Template now shared with prelogin

Merge https://github.com/dimagi/commcarehq-prelogin/pull/94 with this

### CODE REVIEW

**Comment by dannyroberts** [comment]
@benrudolph @biyeun cc: @gjavetski

**Comment by dannyroberts** [comment]
Suggestion: Look at the two PRs commits/diffs as if they were one PR. I committed changes that went together together

**Comment by dannyroberts** [comment]
Due to new comments on http://manage.dimagi.com/default.asp?236188 might go a different route with this

**Comment by dannyroberts** [comment]
Just offlined with @gjavetski, it'll be a more minor change than I thought; I'll reopen when I've done it.

**Comment by dannyroberts** [comment]
@gjavetski @amsagoff 

screen shot 2016-08-30 at 5 24 44 pm

**Comment by benrudolph** [comment]
looks good ddawg 👍 is this ready to go?

**Comment by dannyroberts** [comment]
Yeah this is good to go!

**Comment by dannyroberts** [comment]
(And the other PR linked)

**Comment by dannyroberts** [comment]
Thanks ben!

**Pull request merged**
