### PR TITLE
Use provider not pillow

### PR DESCRIPTION
**Pull request by benrudolph**
@czue

### CODE REVIEW

**Comment by benrudolph** [comment]
i'm unsure how to test this locally, seems like there's a lot of moving parts and kafka is giving me trouble. i'm pretty sure this is what caused this: http://manage.dimagi.com/default.asp?220782. i'm gonna revert your PR and redeploy because i think that's what noah needs

**Comment by czue** [comment]
whoops, thanks. that was definitely just a bad typo.

**Comment by czue** [comment]
(will rebase onto https://github.com/dimagi/commcare-hq/pull/10680 and test)

**Comment by czue** [comment]
huh, though I still have no idea how this affected anything since it shouldn't have been using that pillow to do the reindex.

**Comment by czue** [comment]
ah, i see, this pillow was initiating the table adapter that was getting a lock on the table and preventing the real pillow from being able to operate on it.

**Pull request closed without merging**
