### PR TITLE
add modification date to MessagingSubEvent that updates with related models

### PR DESCRIPTION
**Pull request by snopoke**
## Summary
The new 'messaging-event' API provides access to MessagingSubEvent data and associated messages. Currently the 'date' used in filtering is `MessagingSubEvent.date`. This date get's set when the event is first created but does not change after that which presents a problem to users of the API. If you are querying the API by date range you will potentially miss data in the instance where new messages are associated with events after you have passed the event's date.

To counter this there are a number of changes:
1. Add a modification date to MessagingSubEvent
2. Update this message data is updated
3. Update the API to allow filtering on this date (which falls back to `event.date` if the modification date is null). (separate PR)

### Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
Code will be executed by existing tests.

### QA Plan
None

### Safety story
Adding a nullable DB column should not be an issue. The saves in the SMS and Email classes should not add significant load to the DB.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by millerdev** [comment]
It seems not quite right to update the MessagingSubEvent if that model has not actually changed, and it has some disadvantages:

- update logic that does not go through the Django save method will not update the modified date, and it may not be obvious that any updates to `Log` or `Email` should also be paired with updating the modified date on `MessagingSubEvent`.
- two database queries on every `<Log|Email>.save()`

Another approach would be to add a modified date column to each of `Log` and `Email` and then filter on `<Log|Email>.modified_date` with fallback to `MessagingSubEvent.date` if that is null. Maybe you already considered this?

**Comment by mkangia** [comment]
Agree with Daniel on "if that model has not actually changed".  Or can it be named such that the intention is clear, `parent_event_modified`?
I am not well aware of the way events are connected, so can't suggest a better alternate.

**Comment by snopoke** [comment]
> It seems not quite right to update the MessagingSubEvent if that model has not actually changed, and it has some disadvantages:
> 
> * update logic that does not go through the Django save method will not update the modified date, and it may not be obvious that any updates to `Log` or `Email` should also be paired with updating the modified date on `MessagingSubEvent`.
> * two database queries on every `<Log|Email>.save()`
> 
> Another approach would be to add a modified date column to each of `Log` and `Email` and then filter on `<Log|Email>.modified_date` with fallback to `MessagingSubEvent.date` if that is null. Maybe you already considered this?

Agreed this isn't ideal. What do you think of the following:

1. Add modification date columns to both SMS and Email models
2. Update the API query to use subqueries to filter on the SMS / Email / SQLXFormSession dates:

```python
query = MessagingSubEvent.objects.select_related("parent").filter(parent__domain=domain)
newest_sms = SMS.objects.filter(messaging_subevent=OuterRef('pk')).order_by('-modified_time').values('modified_time')[:1]
newest_email = Email.objects.filter(messaging_subevent=OuterRef('pk')).order_by('-modified_time').values('modified_time')[:1]
query = query.annotate(last_activity=Greatest(
    'date', 'xforms_session__modified_time', Subquery(newest_sms), Subquery(newest_email)
))
query = query.filter(last_activity__gt=X)
query = query.order_by('-last_activity')
```

Equivalent SQL:
```sql
SELECT sms_messagingsubevent.*, GREATEST(
      "sms_messagingsubevent"."date", 
      "smsforms_sqlxformssession"."modified_time", 
      (SELECT U0."date" FROM "sms_sms" U0 WHERE U0."messaging_subevent_id" = ("sms_messagingsubevent"."id") ORDER BY U0."date" DESC  LIMIT 1),
      SELECT U0."date" FROM "sms_email" U0 WHERE U0."messaging_subevent_id" = ("sms_messagingsubevent"."id") ORDER BY U0."date" DESC  LIMIT 1)
  ) AS "last_activity"
  FROM "sms_messagingsubevent"
  INNER JOIN "sms_messagingevent" ON ("sms_messagingsubevent"."parent_id" = "sms_messagingevent"."id") 
  LEFT OUTER JOIN "smsforms_sqlxformssession" ON ("sms_messagingsubevent"."xforms_session_id" = "smsforms_sqlxformssession"."id")
  WHERE
    "sms_messagingevent"."domain" = %s 
    AND GREATEST(
        "sms_messagingsubevent"."date", "smsforms_sqlxformssession"."modified_time", 
        (SELECT U0."date" FROM "sms_sms" U0 WHERE U0."messaging_subevent_id" = ("sms_messagingsubevent"."id") ORDER BY U0."date" DESC  LIMIT 1),
        (SELECT U0."date" FROM "sms_email" U0 WHERE U0."messaging_subevent_id" = ("sms_messagingsubevent"."id") ORDER BY U0."date" DESC  LIMIT 1)
    ) > %s
  ORDER BY "last_activity" DESC
```

**Comment by millerdev** [comment]
I like that proposal. It seems difficult to do know implementing it, but I wonder what an `EXPLAIN` of that query will look like on a domain with a lot of SMS or Email records? Hopefully we can make it perform well.

**Comment by snopoke** [comment]
Running the query with `date` gives the following plan:
```
 Sort  (cost=1075987.35..1076009.00 rows=8661 width=668) (actual time=37.570..37.616 rows=194 loops=1)
   Sort Key: (GREATEST(sms_messagingsubevent.date, smsforms_sqlxformssession.modified_time, (SubPlan 1), (SubPlan 2))) DESC
   Sort Method: quicksort  Memory: 217kB
   ->  Nested Loop Left Join  (cost=1.56..1072844.91 rows=8661 width=668) (actual time=0.082..37.320 rows=194 loops=1)
         Filter: (GREATEST(sms_messagingsubevent.date, smsforms_sqlxformssession.modified_time, (SubPlan 3), (SubPlan 4)) > '2021-05-01 00:00:00+00'::timestamp with time zone)
         Rows Removed by Filter: 1532
         ->  Nested Loop  (cost=1.13..364072.33 rows=25984 width=660) (actual time=0.030..10.631 rows=1726 loops=1)
               ->  Index Scan using sms_messagingevent_domain on sms_messagingevent  (cost=0.56..75672.14 rows=23479 width=347) (actual time=0.021..1.759 rows=1494 loops=1)
                     Index Cond: ((domain)::text = 'alaska-covid-19-project'::text)
               ->  Index Scan using sms_messagingsubevent_parent_id on sms_messagingsubevent  (cost=0.56..11.97 rows=31 width=313) (actual time=0.004..0.005 rows=1 loops=1494)
                     Index Cond: (parent_id = sms_messagingevent.id)
         ->  Index Scan using smsforms_sqlxformssession_pkey on smsforms_sqlxformssession  (cost=0.43..0.55 rows=1 width=12) (actual time=0.002..0.002 rows=1 loops=1726)
               Index Cond: (sms_messagingsubevent.xforms_session_id = id)
         SubPlan 1
           ->  Limit  (cost=11.57..11.57 rows=1 width=8) (actual time=0.007..0.007 rows=1 loops=194)
                 ->  Sort  (cost=11.57..11.62 rows=18 width=8) (actual time=0.006..0.006 rows=1 loops=194)
                       Sort Key: u0.date DESC
                       Sort Method: top-N heapsort  Memory: 25kB
                       ->  Index Scan using sms_sms_messaging_subevent_id on sms_sms u0  (cost=0.56..11.48 rows=18 width=8) (actual time=0.003..0.004 rows=4 loops=194)
                             Index Cond: (messaging_subevent_id = sms_messagingsubevent.id)
         SubPlan 2
           ->  Limit  (cost=8.46..8.46 rows=1 width=8) (actual time=0.003..0.003 rows=0 loops=194)
                 ->  Sort  (cost=8.46..8.46 rows=1 width=8) (actual time=0.003..0.003 rows=0 loops=194)
                       Sort Key: u0_1.date DESC
                       Sort Method: quicksort  Memory: 25kB
                       ->  Index Scan using sms_email_messaging_subevent_id_e06043f9 on sms_email u0_1  (cost=0.43..8.45 rows=1 width=8) (actual time=0.002..0.002 rows=0 loops=194)
                             Index Cond: (messaging_subevent_id = sms_messagingsubevent.id)
         SubPlan 3
           ->  Limit  (cost=11.57..11.57 rows=1 width=8) (actual time=0.006..0.006 rows=0 loops=1726)
                 ->  Sort  (cost=11.57..11.62 rows=18 width=8) (actual time=0.006..0.006 rows=0 loops=1726)
                       Sort Key: u0_2.date DESC
                       Sort Method: quicksort  Memory: 25kB
                       ->  Index Scan using sms_sms_messaging_subevent_id on sms_sms u0_2  (cost=0.56..11.48 rows=18 width=8) (actual time=0.004..0.004 rows=1 loops=1726)
                             Index Cond: (messaging_subevent_id = sms_messagingsubevent.id)
         SubPlan 4
           ->  Limit  (cost=8.46..8.46 rows=1 width=8) (actual time=0.004..0.004 rows=0 loops=1726)
                 ->  Sort  (cost=8.46..8.46 rows=1 width=8) (actual time=0.004..0.004 rows=0 loops=1726)
                       Sort Key: u0_3.date DESC
                       Sort Method: quicksort  Memory: 25kB
                       ->  Index Scan using sms_email_messaging_subevent_id_e06043f9 on sms_email u0_3  (cost=0.43..8.45 rows=1 width=8) (actual time=0.003..0.003 rows=0 loops=1726)
                             Index Cond: (messaging_subevent_id = sms_messagingsubevent.id)
 Planning time: 1.889 ms
 Execution time: 37.743 ms
```

First execution took 4s. I think the planned implementation would be the same execution plan since the columns would be indexed in the same way.

**Pull request closed without merging**
