### PR TITLE
Custom logo privilege

### PR DESCRIPTION
**Pull request by nickpell**
Restrict custom logo uploader to Advanced plans and higher.

http://manage.dimagi.com/default.asp?111183#885505

@biyeun

### CODE REVIEW

**Comment by czue** [comment]
looks good to me. what's the management command that has to run?

**Comment by nickpell** [comment]
```cchq_prbac_bootstrap```, which adds the privilege to Advanced plans and higher

**Comment by czue** [comment]
i see. we should probably figure out a way to automate that into the deploy process.

**Comment by nickpell** [comment]
it's included in an earlier accounting datamigration.  A second datamigration could be added to ensure that existing CCHQ instances get the updated privileges

**Comment by czue** [comment]
build fail real?
```
======================================================================
ERROR: testBuildApp (corehq.apps.app_manager.tests.test_app_manager.AppManagerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_app_manager.py", line 145, in testBuildApp
    copy = app.make_build()
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/models.py", line 3162, in make_build
    copy.create_jadjar(save=True)
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/models.py", line 3057, in create_jadjar
    all_files = self.create_all_files()
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/models.py", line 3527, in create_all_files
    'profile.xml': self.create_profile(is_odk=False),
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/models.py", line 3471, in create_profile
    if domain_has_privilege(self.domain, privileges.COMMCARE_LOGO_UPLOADER):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/accounting/utils.py", line 101, in domain_has_privilege
    plan_version = Subscription.get_subscribed_plan_by_domain(domain)[0]
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/accounting/models.py", line 1241, in get_subscribed_plan_by_domain
    product_type=SoftwareProductType.COMMCARE).plan.get_version()
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: DefaultProductPlan matching query does not exist.
```

**Comment by nickpell** [comment]
yep, fixing the test

**Comment by nickpell** [comment]
@czue tests passing, added datamigration

**Comment by czue** [comment]
thanks!

**Pull request merged**
