### PR TITLE
Standardize @dimagi.com email checks

### PR DESCRIPTION
**Pull request by minhaminha**
## Technical Summary

Based on a comment left by @mjriley on [this PR](https://github.com/dimagi/commcare-hq/pull/31465#discussion_r866885545).

As Matt explains in his comment, there's a lot of places that check whether a given email ends with `@dimagi.com` so standardizing it would be best, for readability and if there's ever a need to tweak this check a little. 

Matt mentions ~9 or so places where this check occurs but I was only able to find 6 so if you know of a place that has this please let me know!

### Safety story

Tested locally. Most of these places were something along the lines of `email.endwith('@dimagi.com')` so it's just replacing that with a call to a method that does the same thing. 

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]
Great improvement!

**Review by biyeun — APPROVED** [review]
Fantastic! Thank you! 🎉

**Review by mjriley — COMMENTED** [review]
I don't remember where I saw the nine instances, but this looks like it catches most of them.

The only instance I could find that probably should be added is the bug report view: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/hqwebapp/views.py#L832-L835.

Also, I think I may have been confused at the time. I'm not sure it's a great idea to make this a static method on `CouchUser`, rather than some User helper util class. The issue here is that it forces modules which have no use for user code (and especially no need to know about couch code) to import CouchUser, when all they want to do is verify an email.

**Comment by minhaminha** [comment]
Thanks Matt for that additional instance! I've also moved the method to its own function in util.py for clarity.

**Review by mjriley — APPROVED** [review]

**Pull request merged**
