### PR TITLE
Hide shadow forms from app summary

### PR DESCRIPTION
**Pull request by sheelio**

### CODE REVIEW

**Comment by sheelio** [comment]
@NoahCarnahan 

We'd like to hide shadow forms from the app summary (this change makes that possible I think)

**Review by NoahCarnahan — APPROVED** [review]
Looks good, thanks

**Comment by sheelio** [comment]
For some reason the import failed at the top level, so I included it in the function (similar to other functions inside the same file).

**Comment by NoahCarnahan** [comment]
Great, looks good. That error was probably because there was a circular import. `corehq.apps.app_manager.models` imported this file. But putting it in the function like you did breaks the cycle.

**Pull request merged**
