### PR TITLE
Gevent doesn't guarantee ordering when calculating ES adapter doc counts

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

~It doesn't seem necessary to use gevent here anyway, and based on the output of this command, it looks like the order of results returned isn't guaranteed (which makes sense).~

It is useful to use gevent so that the counts for both indices are calculated at roughly the same time. Otherwise writes can result in surprisingly different counts between the two indices.
### QA Plan

No QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by AmitPhulera** [comment]
> it looks like the order of results returned isn't guaranteed

Is it true? I thought the results will be placed in array in the order they have been called, the results may come before and after but when you access them in array the position would be deterministic 🤔

**Comment by gherceg** [comment]
@AmitPhulera after your comment I believe we confirmed together that it is the case that gevent doesn't guarantee ordering. I know you were still opposed to this change from a performance perspective, but I can't imagine it slows things down _that_ much since it is limited to a primary and secondary index. I'd rather merge this and avoid those running this command from being confused by output rather than a slightly faster execution time.

**Review by AmitPhulera — APPROVED** [review]
Thank you ❤️

**Review by AmitPhulera — APPROVED** [review]

**Comment by AmitPhulera** [comment]
@gherceg Is there any remaining work in this one?

**Pull request merged**
