### PR TITLE
python-modernize . -w

### PR DESCRIPTION
**Pull request by nickpell**
@dimagi/py3

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
Curious why this PR is necessary? The code is Python 2/3 compatible as is, so really not necessary to change. If it's a matter of `python-modernize` tripping on code it can't tell is 2/3 compatible then we should find a way to mark code like this so it's either ignored by the tool or easy to ignore manually.

**Comment by nickpell** [comment]
I don't think ```modernize``` supports skipping over marked code.  We could add a comment to skip committing a line manually, but it's about the same amount of work as just letting the fixer be applied.

**Comment by nickpell** [comment]
Thoughts?

**Review by emord — APPROVED** [review]
Pro this change even if it's not necessary. It keeps noise down when running the script. I imagine once python 3 is real it will be easy to run something that changes all these back to `.items`

**Comment by millerdev** [comment]
Sorry for letting this slide for so long.

> once python 3 is real it will be easy to run something that changes all these back to `.items`

This is true, although it makes it harder to follow changes with tools like `git blame`. Ideally I'd like to see the modernizer tool get smarter, but that doesn't seem likely to happen anytime soon. I'd rather be on Python 3 sooner than take more time to make the tools better if that would delay getting there.

**Pull request merged**
