### PR TITLE
Remove now-unused languages/list view

### PR DESCRIPTION
**Pull request by esoergel**
To be merged after https://github.com/dimagi/commcare-hq/pull/9957 has been deployed safely
@dannyroberts

### CODE REVIEW

**Comment by orangejenny** [comment]
hooray!

**Comment by dannyroberts** [comment]
Nice! Looks good to merge once you're happy with how you tested it. Might be worth adding a test that uses fake es / possibly mocked couch as well.

**Comment by dannyroberts** [comment]
(also looks like there are conflicts with master)

**Comment by dannyroberts** [comment]
@esoergel looks like this is the only view in this design doc so you can just merge this into https://github.com/dimagi/commcare-hq/pull/9957 and close this PR (or we can merge it whenever we merge that one).

**Comment by dannyroberts** [comment]
(basically same comment as https://github.com/dimagi/commcare-hq/pull/9955#issuecomment-173626293)

**Comment by esoergel** [comment]
Same here, gtm on my end.

**Pull request merged**
