### PR TITLE
split couch across multiple machines

### PR DESCRIPTION
**Pull request by snopoke**
ansible changes to follow

@dimagi/scale-team 

## requires localsettings change timed with deploy: https://github.com/dimagi/commcarehq-ansible/pull/715

### CODE REVIEW

**Comment by emord** [comment]
@dimagi/scale-team aded some commits to fix tests and note commands that are now broken

**Comment by emord** [comment]
I've been unable to reproduce the test failures here

**Comment by snopoke** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
@dimagi/team-commcare-hq FYI once this is merged you'll need to update your couch settings in localsettings.py as follows: https://github.com/dimagi/commcare-hq/pull/15896/files#diff-61fb5d4bf7e411768579934d90561e5fL73

**Review by dannyroberts — APPROVED** [review]

**Comment by snopoke** [comment]
merging this since it's compatible with current settings

**Pull request merged**
