### PR TITLE
Fix cloudant attachments

### PR DESCRIPTION
**Pull request by dannyroberts**
w/ @esoergel cc: @orangejenny @proteusvacuum

### CODE REVIEW

**Comment by dannyroberts** [comment]
doctypemigration tests pass, so no need to wait for tests

**Comment by esoergel** [comment]
build looks like it failed, but it actually passed: https://travis-ci.org/dimagi/commcare-hq/builds/94509099

**Comment by benrudolph** [comment]
haha that's odd

**Comment by esoergel** [comment]
@benrudolph The failure was 'cause I merged and deleted the branch before travis got a chance to fetch it, so it failed on that step.  The build I linked was the one run on the merge commit.

**Pull request merged**
