### PR TITLE
Use location tree order

### PR DESCRIPTION
**Pull request by esoergel**
Builds off of https://github.com/dimagi/commcare-hq/pull/14308 and https://github.com/dimagi/commcare-hq/pull/14309
To be merged after those two.
@czue @proteusvacuum I see you two on the git blame for this area, so pinging in case you have strong feelings.
This PR makes the UCR location filter order results by the tree order.  Even without the path display, it's currently difficult to get top-level locations, as searching "Mass" includes results for all children of "Massachusetts".  The path display puts higher-level locations first, then buckets things under that, ordered by name when at the same level.

### CODE REVIEW

**Comment by esoergel** [comment]
@dannyroberts buddy ping

**Comment by dimagimon** [comment]
There are 14 errors:

* corehq/apps/locations/tests/test_location_queries.py, line 145 - F841 local variable 'dorcester' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 146 - F841 local variable 'boston' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 148 - F841 local variable 'somerville' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 149 - F841 local variable 'cambridge' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 150 - F841 local variable 'arlington' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 157 - E131 continuation line unaligned for hanging indent
* corehq/apps/locations/tests/test_location_queries.py, line 158 - E131 continuation line unaligned for hanging indent
* corehq/apps/locations/tests/test_location_queries.py, line 173 - F841 local variable 'arlington' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 174 - F841 local variable 'boston' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 175 - F841 local variable 'dorcester' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 176 - F841 local variable 'somerville' is assigned to but never used
* corehq/apps/locations/tests/test_location_queries.py, line 187 - E131 continuation line unaligned for hanging indent
* corehq/apps/locations/tests/test_location_queries.py, line 188 - E131 continuation line unaligned for hanging indent
* corehq/apps/userreports/tests/test_choice_provider.py, line 200 - E126 continuation line over-indented for hanging indent

**Comment by czue** [comment]
makes sense to me, thanks!

**Comment by proteusvacuum** [comment]
That's awesome.

**Comment by proteusvacuum** [comment]
I've actually noticed the same thing with case properties in app manager, and was going to complain about it but then bit my tongue. Would be cool if we could do something similar there too. (e.g. /parent/name comes before 'name' when you type 'name').
Way out of scope for this PR, and is actually probably a different issue.

**Comment by dannyroberts** [comment]
Failure looks related
```
======================================================================
ERROR: test_edit_names (corehq.apps.locations.tests.test_bulk_management.TestBulkManagement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/locations/tests/test_bulk_management.py", line 801, in test_edit_names
    change_names,
  File "/mnt/commcare-hq-ro/corehq/apps/locations/tests/test_bulk_management.py", line 430, in bulk_update_locations
    result = importer.run()
  File "/mnt/commcare-hq-ro/corehq/apps/locations/bulk_management.py", line 408, in run
    self.bulk_commit(self.type_rows, self.location_rows)
  File "/mnt/commcare-hq-ro/corehq/apps/locations/bulk_management.py", line 421, in bulk_commit
    save_locations(location_stubs, type_objects)
  File "/mnt/commcare-hq-ro/corehq/apps/locations/bulk_management.py", line 830, in save_locations
    update_children(ROOT_LOCATION_TYPE)
  File "/mnt/commcare-hq-ro/corehq/apps/locations/bulk_management.py", line 827, in update_children
    child.save()
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/locations/models.py", line 428, in save
    super(SQLLocation, self).save(*args, **kwargs)
  File "submodules/dimagi-utils-src/dimagi/utils/couch/migration.py", line 174, in save
    super(SyncSQLToCouchMixin, self).save(*args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/mptt/models.py", line 924, in save
    refresh_target=False)
  File "/vendor/lib/python2.7/site-packages/mptt/managers.py", line 71, in wrapped
    return method(self, *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/mptt/managers.py", line 587, in _move_node
    self._make_sibling_of_root_node(node, target, position)
  File "/vendor/lib/python2.7/site-packages/mptt/managers.py", line 944, in _make_sibling_of_root_node
    new_tree_id = getattr(right_sibling, self.tree_id_attr)
AttributeError: 'NoneType' object has no attribute 'tree_id'
```

**Pull request closed without merging**
