### PR TITLE
Bump memoized to 1.1.3

### PR DESCRIPTION
**Pull request by millerdev**
See https://github.com/dimagi/memoized/pull/7

Wait for tests.

### CODE REVIEW

**Comment by czue** [comment]
did we get to the bottom of the thing with python libraries not properly updating on deploy?

**Comment by millerdev** [comment]
Great question, and thanks for raising. I do not know because I haven't been following that issue very closely—it hasn't bitten me yet. I will check into it.

It might not matter here since this is a fully backward-compatible update.

**Comment by millerdev** [comment]
I talked with @dannyroberts  and we agreed that "the old or new version of the library will always be in place" after deploy, so it should be safe to merge this since it is completely backward compatible.

**Review by dannyroberts — APPROVED** [review]
Yeah we're tracking the issue here https://dimagi-dev.atlassian.net/browse/SAASP-10161, but I agree with @millerdev that in this particular case we're safe because it will work the same regardless of the version of memoized installed (1.1.2 vs 1.1.3)

**Pull request merged**
