### PR TITLE
Pull saved reports and scheduled reports into their own app (saved_reports)

### PR DESCRIPTION
**Pull request by dannyroberts**
When I was looking into this yesterday, I did a prefactor where I pulled out all the saved reports and scheduled reports code into its own app (`corehq.apps.saved_reports`). Unless anyone objects, I think this will just make any changes we make to this system a little easier to reason with. One thing I intentionally left in `corehq.apps.reports` is anything to do with URLs, views, and django forms, reasoning that it's tightly coupled with the rest of the reports UI, and moving it out would be more confusing than helpful. All of the backend code for saved reports and scheduled though would now live in `corehq.apps.saved_reports`.

### CODE REVIEW

**Comment by czue** [comment]
didn't review changes closely but i'm in favor of the move.

were there really no couch views for these or you just didn't want to bother with the overhead of moving them?

**Comment by dannyroberts** [comment]
All the couch views are in the separate `corehq/couchapps` dir, so there was nothing for me to move from `reports` and leaving them where they were seemed fine to me.

**Comment by czue** [comment]
ah that makes sense, thanks.

**Comment by orangejenny** [comment]
Haven't reviewed, but I like this decision.

**Comment by dannyroberts** [comment]
I've confirmed (locally) that the tasks are discoverable in their new location, which I think is the only thing tests might not have caught. Otherwise it's a pretty simple code move with no code changes, so the only other errors I can think of would be import errors, which would likely be caught by tests. It's also been on staging for a few days and I've clicked around the scheduled reports interface, which I think would have caught any import errors. (Staging doesn't do celery beat, so I couldn't test scheduled reports directly on staging, though as I alluded to before, I did this locally.)

**Review by kaapstorm — APPROVED** [review]

**Comment by emord** [comment]
> Staging doesn't do celery beat, so I couldn't test scheduled reports directly on staging

@dannyroberts I think a close approximation is opening a shell on staging and running the periodic task that schedules the report using `.delay()`? Not sure if you think that will be more trustworthy than local testing

**Review by millerdev — APPROVED** [review]
Overall, this looks like a nice separation. Some thoughts:

What is the difference between a normal "report" and a "saved report"? Also is "saved" synonymous with "scheduled"? If not what is the difference? (answers to these questions would ideally go into a docstring or readme file)

Conceptually it seems like the ability to save a report is something orthogonal to the concept of generating a report. Hypothetical: if "saved" reports and normal reports both implemented some common interface then maybe any report could be saved? My initial thought was the things in `saved_reports` should be added to a new package `corehq.apps.reports.saved` rather than a new app. The fact that we have `reports` and `saved_reports` apps beside each other may be confusing if the things in those apps are not clearly distinguished and defined. Maybe it makes sense to add readme files or docstrings so it's clear what belongs in each app and where to put new reports in the future?

There is some shared logic between the apps. Some modules in `corehq.apps.reports` import things from `from corehq.apps.saved_reports`, and the opposite is also true. Maybe the apps are tightly coupled or maybe there are just a few common bits of logic that could be extracted to a common place so the apps are not interdependent?

**Comment by dannyroberts** [comment]
Saved and Scheduled reports are a small bundle of features that build on each other (specifically Scheduled reports depends entirely on Saved reports), and Saved reports depends on `reports` but apart from the UI, where they're integrated, reports doesn't really depend saved reports at all. For more on the feature set which this PR is moving to `saved_reports`, see https://confluence.dimagi.com/display/commcarepublic/Managing+Saved+and+Scheduled+Email+Reports.

I did think of moving it to `corehq.apps.reports.saved`, but it since it has its own tasks, its own models, its own management commands, its own tests, it seemed more straightforward to hook into the auto bootstrapping we get from putting it at the app level than to separate those all out into `saved/tasks.py`, etc. and then in `reports/tasks.py` doing `from .saved.tasks import *`, (and doing that for models, and then also somehow for management commands (?)). It seems like I'd have to do more rolling my own conventions to go that route so I stuck with something established.

I think for now since I have some actually-quite-useful changes pipelined on top of this (https://github.com/dimagi/commcare-hq/pull/23737), I'm going to leave it this way. FWIW, I think my ideal organization, if the rest of our codebase was organized like this would be to have something like 

```
cchq/
  reporting/  # not an app
    reports/  # app
    saved_reports/  # app
  ...
```
or something like that, where it was established that everything at a certain level was an app, but we could still have a level of organization between them for grouping. (This is a total aside, just something related I've thought about before.)

**Comment by dannyroberts** [comment]
@emord thanks for the suggestion. Just ran that as well on staging and it works just the way I'd expect. I'm going to add a small readme to the saved_reports app with some context an the link to confluence, and then I'll merge this

**Pull request merged**
