### PR TITLE
Hq define accounting

### PR DESCRIPTION
**Pull request by dannyroberts**
you'll want to use w=1

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 36 errors:

* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 7 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 117 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 23 - 'can_purchase_credits' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 10 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 20 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 193 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 297 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 123 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 408 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 54 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 37 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 6 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 62 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 463 - Expected indentation of 12 space characters but found 11. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 418 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 241 - 'initData' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 84 - 'django' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 426 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 18 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 231 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 245 - 'response' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/ko/accounting.pricing_table.js, line 114 - Expected indentation of 4 space characters but found 0. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 77 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 505 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 59 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 364 - 'paginatedListModel' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 175 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 501 - 'Stripe' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 422 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 109 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 217 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 363 - 'response' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 28 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 36 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 55 - Expected indentation of 12 space characters but found 14. (indent)

**Comment by gcapalbo** [comment]
some of the lint feedback looks like it might be an issue:

- corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 84 - 'django' is not defined. (no-undef)
- corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 364 - 'paginatedListModel' is not defined. (no-undef)
- corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 501 - 'Stripe' is not defined. (no-undef)

**Comment by gcapalbo** [comment]
looks ok to me, also pinging @nickpell in case he wants to take a pass

**Comment by nickpell** [comment]
👍

**Comment by dimagimon** [comment]
There are 36 errors:

* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 7 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 117 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 10 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.pricing_table.js, line 114 - Expected indentation of 4 space characters but found 0. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 193 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 297 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 123 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 408 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 54 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 37 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 6 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 62 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 463 - Expected indentation of 12 space characters but found 11. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 78 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 418 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 241 - 'initData' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 84 - 'django' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 426 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 18 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 231 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 245 - 'response' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 175 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 505 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 59 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 364 - 'paginatedListModel' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 501 - 'Stripe' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 24 - 'can_purchase_credits' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 422 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 109 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 21 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 217 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 363 - 'response' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 28 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 36 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 55 - Expected indentation of 12 space characters but found 14. (indent)

**Comment by dimagimon** [comment]
There are 26 errors:

* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 7 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 117 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 10 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.pricing_table.js, line 114 - Expected indentation of 4 space characters but found 0. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 54 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 507 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 37 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 6 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 410 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 62 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 232 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 176 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 84 - 'django' is not defined. (no-undef)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 78 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 18 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 218 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 59 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 465 - Expected indentation of 12 space characters but found 11. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 37 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 56 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 24 - 'can_purchase_credits' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 109 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 21 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 194 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 28 - Missing semicolon. (semi)

**Comment by dannyroberts** [comment]
@gcapalbo thanks `paginatedListModel` was actually a bug; the other two were just referencing (existing) globals.

**Comment by dimagimon** [comment]
There are 24 errors:

* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 7 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 118 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.pricing_table.js, line 114 - Expected indentation of 4 space characters but found 0. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 507 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 37 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/js/adjust-balance-modal.js, line 6 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 410 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 11 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 232 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 176 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 55 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 63 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 18 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 60 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 218 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 465 - Expected indentation of 12 space characters but found 11. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 37 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 56 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 24 - 'can_purchase_credits' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 21 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 194 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 78 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 28 - Missing semicolon. (semi)

**Comment by dimagimon** [comment]
There are 13 errors:

* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 56 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 410 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 24 - 'can_purchase_credits' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 176 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 232 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 21 - Missing semicolon. (semi)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 194 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.credits.js, line 78 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.pricing_table.js, line 114 - Expected indentation of 4 space characters but found 0. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 218 - Expected indentation of 12 space characters but found 14. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 507 - Missing trailing comma. (comma-dangle)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 465 - Expected indentation of 12 space characters but found 11. (indent)
* corehq/apps/accounting/static/accounting/ko/accounting.payment_method_handler.js, line 37 - Missing trailing comma. (comma-dangle)

**Comment by dannyroberts** [comment]
I got this set up on local and fixed the few js errors I found, so I think it's clean. @nickpell I know you're a lot more familiar with the area; do you want to do a click-through with your console open and just double-check I didn't miss anything obvious?

**Comment by nickpell** [comment]
I found a js error: Uncaught Error: Syntax error, unrecognized expression: /hq/accounting/accounts/new/
by
1) navigate to http://localhost:8000/hq/accounting/accounts/
2) click on "Add New Billing Account"

The error is displayed and the page immediately redirects.  The page seems to work, but flagging anyway.  fwiw I observed the same type of error for adding a new subscription or software plan.

Otherwise looks good to merge.

**Comment by dannyroberts** [comment]
I couldn't recreate your exact problem, though I found another small thing that I fixed. I followed these steps.

- run `./manage.py add_operations_user droberts@dimagi.com` locally
- go to http://localhost:8000/hq/accounting/accounts/new/
- fill out the required fields and click Add New Billing Account.

Nothing shows up in the console either before redirect or on the new page.

**Comment by nickpell** [comment]
@dannyroberts One last question - did you have "Preserve log" checked?  The error appeared really fast then disappeared when the page redirected.
If you still don't see it, then I'm good to merge.

**Comment by dannyroberts** [comment]
I was just able to reproduce it on staging but still haven't locally; my guess is it's non-deterministic. For what it's worth, I had a hunch, and that's the error message that jQuery displays if you pass a url-looking string like that to `$`. In my browser console:

```javascript
> $('/hq/accounting/accounts/new/')
jquery.js:1472 Uncaught Error: Syntax error, unrecognized expression: /hq/accounting/accounts/new/
```

**Comment by dannyroberts** [comment]
Oops, silly me. I've managed to reproduce it locally now; I think I was on the wrong page

**Comment by dannyroberts** [comment]
@nickpell I just checked and the same thing happens on master locally for me. Want to double check that yourself in case I'm getting confused by some stale js or something locally?

**Comment by nickpell** [comment]
@dannyroberts Confirmed that the error appears on master

**Comment by nickpell** [comment]
oops just saw the awaiting QA tag.  I think this is all the QA intended, right?

**Comment by dannyroberts** [comment]
Yup, I meant to remove. 👍 thanks!

**Pull request merged**
