### PR TITLE
Add disclaimer on program summary tab

### PR DESCRIPTION
**Pull request by dmydlo**
Hi @calellowitz,
I have added the requested disclaimer to the program summary tab.
Regards, Dawid

### CODE REVIEW

**Comment by calellowitz** [comment]
@dmydlo do you have a screenshot of what this looks like?

**Comment by dmydlo** [comment]
Here you go.
disclaimer

**Comment by dmydlo** [comment]
Also mobile view.
disclaimer2

**Comment by calellowitz** [comment]
@dmydlo 
This appears on all 4 tabs of the program summary?

**Comment by dmydlo** [comment]
Yes, it does appear on all 4 tabs.

**Pull request merged**
