### PR TITLE
fix  immunization

### PR DESCRIPTION
**Pull request by katembu**
Fix immunisation as per new suggestions.

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 9 errors:

* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 22 - 'visit_diff' used out of scope.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 26 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 28 - ['moderate_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 31 - ['severe_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 41 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 43 - ['muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 50 - ['routine_muac'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 56 - 'visit_diff' used out of scope.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 60 - ['active_gam'] is better written in dot notation.

**Comment by dimagimon** [comment]
There are 7 errors:

* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 27 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 29 - ['moderate_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 32 - ['severe_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 42 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 44 - ['muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 51 - ['routine_muac'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 61 - ['active_gam'] is better written in dot notation.

**Comment by dimagimon** [comment]
There are 7 errors:

* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 27 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 29 - ['moderate_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 32 - ['severe_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 42 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 44 - ['muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 51 - ['routine_muac'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 61 - ['active_gam'] is better written in dot notation.

**Comment by katembu** [comment]
@biyeun Is it necessary to change the variable objects to dot notation?

**Pull request closed without merging**
