### PR TITLE
forcing new timezone behavior in sql domains

### PR DESCRIPTION
**Pull request by calellowitz**
http://manage.dimagi.com/default.asp?227964#1154414
@dannyroberts @czue @emord cc: @biyeun

### CODE REVIEW

**Comment by snopoke** [comment]
@calellowitz  pretty sure this isn't necessary and won't fix the issue. Did you see this: https://github.com/dimagi/commcare-hq/compare/dates?expand=1

**Comment by calellowitz** [comment]
@snopoke that function modifies the data in place (so returning shouldnt be necessary. a comment in there indicates tahts for test convenience), but was incorrectly stripping timezone information from sql domains. according to @dannyroberts this is because we determine whether a doc belongs to a a new timezone domain from the request, but there isnt a request when putting sql forms into es so its defaulting to old timezone behavior (treating the phone times as utc instead of converting to utc). this didnt surface for couch domains because we store the form json in couch while recalculating it each time as a property for sql ones.

**Comment by snopoke** [comment]
OK thanks for the explanation. That makes sense.

**Comment by snopoke** [comment]
Could be good to add a comment to `adjust_datetimes`

**Comment by calellowitz** [comment]
@snopoke no worries, I probably should have led with that in the PR description. adding a comment now.

**Comment by dannyroberts** [comment]
This looks correct to me based on our conversation/digging. Agree about comment on `adjust_datetimes`—the fact that it relies a request object being stored in a thread local by middleware in order to determine the domain is pretty crucial and non-obvious aspect of that function's behavior! (It was a confusing sentence to even write!)

**Comment by czue** [comment]
:+1: thanks for the fix!

**Pull request merged**
