### PR TITLE
Split up reports_forms views, remove name_by_xmlns

### PR DESCRIPTION
**Pull request by esoergel**
@emord @dannyroberts
Commits are granular.  There's nothing urgent about this - it can be merged whenever is convenient.

### CODE REVIEW

**Comment by dannyroberts** [comment]
Is this related?
```
======================================================================
FAIL: test_get_filtered_data_by_app_id (corehq.apps.reports.tests.test_filters.FormsByApplicationFilterDbTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/reports/tests/test_filters.py", line 78, in test_get_filtered_data_by_app_id
    self.assertEqual(2, len(results))
AssertionError: 2 != 0
----------------------------------------------------------------------
```

**Comment by esoergel** [comment]
it certainly *seems* related.  I'll look into it.

**Comment by dannyroberts** [comment]
@esoergel i removed the don't merge label and merged. Let me know if that wasn't your intention! (But I feel like we talked about this and it's well understood, so I'm assuming that label was just a holdover from before you were finished.)

**Comment by czue** [comment]
:tada:

**Comment by esoergel** [comment]
@dannyroberts yup, this was g2g, thanks for kicking it off!

**Pull request merged**
