### PR TITLE
Revert "remove unused tags"

### PR DESCRIPTION
**Pull request by dannyroberts**
This reverts commit 15a4611e1433a32af14566ec3980f07af66efafa.

See https://github.com/dimagi/commcare-hq/pull/27251/files#r418658370

##### SUMMARY
Turns out these particular metrics are in use (by me, even!) and I'd missed that in review

### CODE REVIEW

**Comment by dannyroberts** [comment]
Build failure real:
```
AssertionError: ('Prometheus metric error', {'metric_name': 'commcare_load_sms', 'tags': ['src', 'domain'], 'expected_tags': ('status', 'backend', 'src', 'domain')})
```
@snopoke Should I read that as saying that now all calls to `commcare_load_sms` MUST have `status` and `backend` tags on them (as well as `src` and `domain`)? I think I recall that was the thrust of a recent PR you made, that a given metric must now always be emitted with the same tags every time.

**Comment by snopoke** [comment]
@dannyroberts that's correct, one option I had considered was to change the `load_counter` interface to include kwargs with defaults set:
```python
def sms_load_counter(source, domain, status='', backend=''):
    return load_counter("sms", source, domain, extra_kwargs={'status': status, 'backend': backend})
```

**Review by millerdev — APPROVED** [review]

**Comment by dannyroberts** [comment]
Thanks @snopoke, I took that suggestion. Just another thing I want to confirm: are both `''` and `None` valid values for the purposes of prometheus and/or the shared metrics validator layer? Just want to make sure we're not going to get some runtime errors if it passes in backend=None (a possible output of `_get_backend_tag`, though not sure in what situation that would come up)

**Comment by snopoke** [comment]
@dannyroberts I think `None` get's translated to the string `'None'`

**Comment by dannyroberts** [comment]
```
AssertionError: ('Prometheus metric error', {'metric_name': 'commcare_load_sms', 'tags': ['status', 'backend', 'src', 'domain'], 'expected_tags': ('src', 'domain')})
```
Is there a declaration somewhere of tags for a given metic that I need to be matching @snopoke

**Comment by dannyroberts** [comment]
Couldn't reproduce the test failure locally for some reason. (I did change my localsettings to have both `METRICS_PROVIDERS`, and that still didn't reveal the issue locally.)

**Comment by dannyroberts** [comment]
OK replacing this with https://github.com/dimagi/commcare-hq/pull/27451

**Pull request closed without merging**
