### PR TITLE
update alembic

### PR DESCRIPTION
**Pull request by emord**
open for tests

### CODE REVIEW

**Comment by snopoke** [comment]
:+1:

**Comment by snopoke** [comment]
not sure if I should merge this so leaving it to you

**Comment by emord** [comment]
@snopoke I think this is safe to merge unless there's a reason @nickpell didn't upgrade when upgrading sqlalchemy (https://github.com/dimagi/commcare-hq/commit/8a696e94bf6d91d25fe2695c3d71714138795335), but I didn't notice anything of concern in the changelog

**Comment by nickpell** [comment]
@emord no reason I didn't upgrade

**Pull request merged**
