### PR TITLE
report builder perms take 2

### PR DESCRIPTION
**Pull request by emord**
Fixing and testing my error from here https://github.com/dimagi/commcare-hq/pull/14655

Made some changes to the test and shaved off a few seconds while adding 2 tests.

@NoahCarnahan @kaapstorm 

cc @benrudolph @snopoke

### CODE REVIEW

**Comment by kaapstorm** [comment]
:boot: :construction_worker_man:

**Review by NoahCarnahan — APPROVED** [review]

**Review by kaapstorm — APPROVED** [review]

**Comment by NoahCarnahan** [comment]
This build keeps timing out. I've tried restarting it like 3 times... :( Might be ok to merge without build?

**Comment by snopoke** [comment]
Have you tried merging in master (we added another build to the matrix)

**Comment by emord** [comment]
just merged master. I thought restarting the whole build would have picked up the build changes

**Pull request merged**
