### PR TITLE
Added clear button for single-select questions in web apps & app preview

### PR DESCRIPTION
**Pull request by orangejenny**
The clear button shows up for single select questions only. It fades in once an answer is selected and fades out if the answer is cleared.

Screen Shot 2020-05-25 at 9 21 10 PM

Screen Shot 2020-05-25 at 9 26 06 PM

### CODE REVIEW

**Comment by orangejenny** [comment]
@dimagi/product

**Review by dannyroberts — APPROVED** [review]

**Comment by shubham1g5** [comment]
Nice @orangejenny , Wondering if a similar change should be made on mobile for consistency ?

**Comment by orangejenny** [comment]
@shubham1g5 A similar change for mobile would be great. Didn't seem urgent because you can clear on mobile already, but it'd be nice if they matched, and I think the button is good for discoverability (unless the long press is a common standard on mobile apps).

**Comment by shubham1g5** [comment]
ohh wow, I didn't know we can clear on mobile already using a long press. Long press is definitely CommCare and I haven't seen it anywhere else. So if we are using this pattern on web, it does make sense for us to mimic it on phone. Added a [ticket](https://dimagi-dev.atlassian.net/browse/SAAS-10936) here for SAAS to prioritize.

**Comment by orangejenny** [comment]
@shubham1g5 thank you!

**Comment by ShivamPokhriyal** [comment]
>ohh wow, I didn't know we can clear on mobile already using a long press. Long press is definitely CommCare and I haven't seen it anywhere else. 

Same, I didn't know anything like that existed. Amazing!

**Pull request merged**
