### PR TITLE
Fix icds reports test

### PR DESCRIPTION
**Pull request by millerdev**
The most important commit is https://github.com/dimagi/commcare-hq/commit/cef4ed1bc5db0a0f8858a68fd6f177257c209f55. If the tests pass I'll revert https://github.com/dimagi/commcare-hq/pull/23897/commits/8a924bc76d7d24335d5ff29b2c5ae151859d2270 before merging.

@calellowitz @emord @nickpell @dannyroberts

### CODE REVIEW

**Review by emord — APPROVED** [review]

**Comment by dannyroberts** [comment]
In this build that test is still being skipped:

```
@skip("This test is breaking the build on master and should be debugged on a branch.")
```

**Review by calellowitz — APPROVED** [review]
This looks good. Surprised it was necessary, but happy to see the fix was straightforward.

**Review by nickpell — APPROVED** [review]
I'd support killing all currently running jobs

**Comment by dannyroberts** [comment]
Looks like there's a new but related failure:

```
======================================================================
ERROR: custom.icds_reports.tests.test_cas_data_export:TestLocationView.test_agg_awc_cas_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_cas_data_export.py", line 74, in test_agg_awc_cas_data
    csv_data = self._get_data_from_blobdb(indicator, state_id, month)
  File "/mnt/commcare-hq-ro/custom/icds_reports/tests/test_cas_data_export.py", line 24, in _get_data_from_blobdb
    csv_file = io.TextIOWrapper(sync.get_file_from_blobdb(), encoding='utf-8')
  File "/mnt/commcare-hq-ro/corehq/blobs/util.py", line 52, in __getattr__
    return getattr(self._obj, name)
AttributeError: 'StreamingBody' object has no attribute 'readable'
```

**Comment by millerdev** [comment]
> Surprised it was necessary

The csv module is better at dealing with text than bytes. And `TextIOWrapper` does universal line mode, which is what resolved the issue in this case.

```py
>>> import io
>>> import csv342 as csv

>>> csv_file = io.BytesIO(b"abc,def,ghi\n,\r,\n")
>>> list(csv.reader(csv_file))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmiller/code/virtualenvs/hq/lib/python2.7/site-packages/csv342.py", line 162, in next
    return self.__next__()
  File "/Users/dmiller/code/virtualenvs/hq/lib/python2.7/site-packages/csv342.py", line 157, in __next__
    row = self.reader.next()
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

>>> csv_file = io.TextIOWrapper(io.BytesIO(b"abc,def,ghi\n,\r,\n"), encoding='utf-8')
>>> list(csv.reader(csv_file))
[[u'abc', u'def', u'ghi'], [u'', u''], [u'', u'']]
```

**Pull request merged**
