### PR TITLE
B3 tweak to reports/async/default.html

### PR DESCRIPTION
**Pull request by orangejenny**
@biyeun does this look right to you? I don't know how to test it locally.

### CODE REVIEW

**Comment by biyeun** [comment]
@orangejenny I think we can actually delete this line. with the new styling this isn't necessary. I would leave it for now until Sol Develo gets to the last few custom reports

**Comment by biyeun** [comment]
@orangejenny seeing that this is actually in a b3 only template, this line can just disappear

**Comment by orangejenny** [comment]
@biyeun cool, updated

**Comment by biyeun** [comment]
not part of tests so g2merge

**Pull request merged**
