### PR TITLE
waiting for document ready

### PR DESCRIPTION
**Pull request by calellowitz**
@millerdev 
missing document ready was stopping the jquery from binding to the dom elements, which had not always loaded in time.
mocha tests in the suite pass locally but they complain about a missing reference, likely because our analytics code is not loaded into the test file but im not sure

### CODE REVIEW

**Comment by calellowitz** [comment]
✅ except for the issue i pointed out in the pr description.

**Comment by benrudolph** [comment]
seems like the test failure is actually real though i'm not sure how

**Comment by benrudolph** [comment]
```

Running "mocha:notifications" (mocha) task
Testing: http://localhost:8000/mocha/notifications/
  1) Uncaught error outside test suite
  NotificationsService Unit Tests
  ✓ Initialization 
  ✓ Model 
fakeError
  ✓ Error 
  3 passing (4ms)
  1 failing
  1)  Uncaught error outside test suite:
     Uncaught TypeError: 'undefined' is not an object (evaluating 'window.analytics.trackUsageLink') (http://localhost:8000/mocha/notifications/:67)
```

**Comment by proteusvacuum** [comment]
js tests passed

**Pull request merged**
