### PR TITLE
Don't let footer cover last forms

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?187059#1045520

@gcapalbo

### CODE REVIEW

**Comment by orangejenny** [comment]
Cloudcare pages shouldn't need to know about the footer. Maybe one of the ids that layout.js expects isn't being set correctly? https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/style/static/style/js/layout.js#L3-L9

Happy to pair on this if it isn't obvious to @benrudolph or @biyeun what's wrong.

**Comment by biyeun** [comment]
second @orangejenny remarks. probably just need to add padding that's the height of the footer to the sidebar and main content area in the js

**Comment by emord** [comment]
Thanks @biyeun and @orangejenny

**Comment by benrudolph** [comment]
nice fix, will this mean that black bar won't be an issue for all pages?

**Comment by emord** [comment]
Yeah that should be the case. A much better fix

**Comment by benrudolph** [comment]
javascript tests passed (there are none for this, gonna go ahead and merge)

**Pull request merged**
