### PR TITLE
remove bootstrap_ledgers view

### PR DESCRIPTION
**Pull request by snopoke**
@sravfeyn 
cc @czue

Original PR: https://github.com/dimagi/commcare-hq/pull/7934

### CODE REVIEW

**Comment by czue** [comment]
good idea: https://github.com/dimagi/commcare-hq/pull/7934#issuecomment-133056027

**Comment by czue** [comment]
:+1: on :white_check_mark:

**Comment by czue** [comment]
:boot: :construction: 

it didn't look related, but it did look like an intermittent error i've seen before that we should likely fix:
```
======================================================================
FAIL: test_get_forms_with_attachments_meta (corehq.form_processor.tests.test_form_dbaccessor.FormAccessorTestsSQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/corehq/form_processor/tests/test_form_dbaccessor.py", line 124, in test_get_forms_with_attachments_meta
    self.assertEqual(form_with_pic.form_id, forms[0].form_id)
AssertionError: '1b3e4fc1465f48a6b7d9229eaaaccc8e' != u'1754ba79dfb1405f9b6a6b79d812e627'
----------------------------------------------------------------------
```

**Comment by snopoke** [comment]
test fix here: https://github.com/dimagi/commcare-hq/pull/10652

**Pull request merged**
