### PR TITLE
Subscription object - added standard manager and new property in API

### PR DESCRIPTION
**Pull request by lwyszomi**
@czue 

http://manage.dimagi.com/default.asp?227258

### CODE REVIEW

**Comment by czue** [comment]
kicked build. :+1: on :white_check_mark:

**Comment by lwyszomi** [comment]
@czue 
Could you kick off the build again?

**Comment by czue** [comment]
done

**Comment by czue** [comment]
still failing though it really doesn't look related. could you try merging master?

**Comment by lwyszomi** [comment]
@czue 
I merged master but still failing (The job exceeded the maximum time limit for jobs, and has been terminated.)

**Pull request merged**
