### PR TITLE
weasy returns

### PR DESCRIPTION
**Pull request by calellowitz**
@emord @gbova 
As per the conversation in the email thread, removing the inline import and updating the documentation.

@dannyroberts 
Is there a mechanism by which we notify external users that requirements have changed. The README is updated and commcare-cloud already installs these packages but that is pretty opaque to non dimagi users.

### CODE REVIEW

**Comment by dannyroberts** [comment]
Yeah what would someone have to run to update their environment? Any operations we require people to do to upgrade, we usually follow this process for: https://confluence.dimagi.com/display/internal/Announcing+commcare-cloud+changes. It might seem weird in this case because it's not a commcare-cloud change, but from the outside perspective it looks the same ("before you upgrade you have to run these commands"), so I think it makes sense to use the same process.

**Comment by calellowitz** [comment]
> what would someone have to run to update their environment?
They would just have to deploy stack again, specifically just run the common_installs playbook, although I think the only way to do that now includes running all of `deploy_common.yml` which does a bunch more. Alternatively for those that do not use commcare-cloud they may need to do a single `apt-get install`. A lot of machines come with these packages by default so it will not necessarily be needed although it may.

**Comment by dannyroberts** [comment]
Ah okay. For a more specific command, I think `cchq <env> ansible-playbook deploy_common.yml --tags=common_installs` should work.

> Alternatively for those that do not use commcare-cloud they may need to do a single apt-get install.

Other than dev environments, commcare-cloud is the only supported way to deploy commcare-hq, so we should not worry about trying to keep anyone else in the loop about how to upgrade.

So yeah I think this confirms what I suggested earlier, which is that the best route is to follow https://confluence.dimagi.com/display/internal/Announcing+commcare-cloud+changes. Feel free to ping me on the commcare-cloud PR that comes out of that and I can take a look

**Comment by dannyroberts** [comment]
Looks like this is just waiting for an approval? I'll let someone who was more involved in the thread do that, but just wanted to make sure we hadn't forgotten

**Review by millerdev — APPROVED** [review]

**Comment by calellowitz** [comment]
Thanks for following up danny. I had held off for a week after sending out the message on commcare-developers to give other groups time to make the necessary changes, but agree it looks good to merge now.

@dimagi/team-commcare-hq 
This makes pango a requirement of commcarehq. It should be installed by default on linux machines with any graphical environment. For those who do not use those, it is installable on apt based machines with `apt-get install libpango1.0-0` and with homebrew on mac with `brew install pango`. Other package managers on mac or linux will likely have similar commands to install it.

**Pull request merged**
