### PR TITLE
remove staging_replicate mgmt cmd

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@TylerSheffels buddy

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
@czue confirmed we don't use this

**Comment by dannyroberts** [comment]
:white_check_mark: (not that there were relevant tests)

**Comment by dannyroberts** [comment]
@esoergel

**Comment by czue** [comment]
we should also clean up https://confluence.dimagi.com/display/commcarehq/Copying+entire+domains+of+data

**Comment by dannyroberts** [comment]
Good catch. I just removed the two parts that had to do with `staging_replicate` (marked "[temporarily deprecated]")

**Comment by czue** [comment]
thanks!

**Comment by esoergel** [comment]
:boom:

**Pull request merged**
