### PR TITLE
Update translations submodule

### PR DESCRIPTION
**Pull request by ShivamPokhriyal**

### CODE REVIEW

**Comment by orangejenny** [comment]
Oddly, the test failure looks real:

```
FAIL: corehq.apps.app_manager.tests.test_bulk_ui_translation:BulkUiTranslation.test_no_change
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/test_bulk_ui_translation.py", line 40, in test_no_change
    self.assertEqual(dict(translations), {})
AssertionError: {'en': {'notification.restore.cancelled.title': 'Sync cancelled'}} != {}
- {'en': {'notification.restore.cancelled.title': 'Sync cancelled'}}
+ {}
```

`notification.restore.cancelled.title` is in 2.49 but missing in 2.48. Did something change with that translation?

**Comment by ShivamPokhriyal** [comment]
> notification.restore.cancelled.title is in 2.49 but missing in 2.48. Did something change with that translation?

Yeah seems like that string is added in [2.49 only](https://github.com/dimagi/commcare-android/commit/e5d6ca967d843a32b9f342c51689f62c644fe91d#diff-f696e3d980bd7e74df0672d9ec57997eR536)

**Comment by orangejenny** [comment]
Hi @ShivamPokhriyal turns out the test failure is because there's a leading space in the new translation: https://github.com/dimagi/commcare-translations/blob/master/historical-translations-by-version/2.49-messages_en-2.txt#L538

Could you update that?

**Comment by ShivamPokhriyal** [comment]
> Hi @ShivamPokhriyal turns out the test failure is because there's a leading space in the new translation: https://github.com/dimagi/commcare-translations/blob/master/historical-translations-by-version/2.49-messages_en-2.txt#L538
> 
> Could you update that?

Thanks for pointing it out! Updated that string.

**Comment by orangejenny** [comment]
@ShivamPokhriyal cool, thank you

**Review by orangejenny — APPROVED** [review]

**Pull request merged**
