### PR TITLE
pass query data to Formplayer debugger endpoints

### PR DESCRIPTION
**Pull request by snopoke**
## Product Description
Improvement to the web apps / app preview debugger when used in conjunction with case search.

## Technical Summary
Pass the query data to the debugger endpoints to allow correct session replay.

### Safety story
Only impacts the web apps / app preview debugger. Formplayer endpoints already accept the param but don't do anything with it (yet)

### Automated test coverage
None

### QA Plan
I've tested this locally and found no issues.

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by snopoke** [comment]
@bot retrigger wip review

**Comment by snopoke** [comment]
@label-bot trigger wip

**Comment by snopoke** [comment]
@label-bot retrigger wip

**Comment by snopoke** [comment]
All checks passed prior to the lint change [22909a8](https://github.com/dimagi/commcare-hq/pull/31687/commits/22909a8277012a5cb17f23e127e8dc6dc0d9bede) so I'm going to merge.

**Pull request merged**
