### PR TITLE
remove ES check task

### PR DESCRIPTION
**Pull request by snopoke**
@czue 
buddy @dannyroberts 

I've left the check functions since they are still used on the dashboard.

### CODE REVIEW

**Comment by czue** [comment]
nice

**Comment by czue** [comment]
do we need the functionality on the dashboard? i can't remember the last time i used it...

**Comment by snopoke** [comment]
probably not but it's harder to remove - will do it in a separate PR

**Comment by czue** [comment]
:+1: on :white_check_mark:

**Pull request merged**
