### PR TITLE
Remove annoying are_es_filters_formatted paramater

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

There's no reason this method can't just handle both types of filter types (`ExportFilter` and json dicts) automatically instead of needing a parameter to specify. The first commit was really just to show that I wrote and ran those tests on the previous code to ensure there isn't a regression.
### Automated test coverage

Added automated test to ensure there was not a regression with this change.
### QA Plan

No QA.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by gherceg** [comment]
There are some other export related changes going out this week, and I'm in no rush to get this out so I'm going to wait to merge.

**Comment by millerdev** [comment]
Are you expecting this to change? If not, I'd encourage you to get it merged sooner rather than later. Benefits are
- Avoid merge conflicts.
- Going live separately from other similar/nearby work makes it easier to tell if this or other related work introduces an issue. If multiple changes go live concurrently then it can be harder to tell what caused the issue if one arises.

**Comment by gherceg** [comment]
> Going live separately from other similar/nearby work makes it easier to tell if this or other related work introduces an issue. If multiple changes go live concurrently then it can be harder to tell what caused the issue if one arises.

@millerdev I'm confused. This is my main reason for holding off on merging this. There is more pressing similar work that will go out today. Does that change your understanding at all or do you still feel this should go out sooner rather than later?

**Comment by millerdev** [comment]
I misread "going out this week" as going out _later_ this week, which I thought meant that you were waiting to merge this with the other things (later). Not sure why I put that extra word, which you clearly did not say, in there. Sorry for the confusion and no further objections to your original plan.

**Comment by gherceg** [comment]
Merged master and resolved conflicts, but also did some reformatting of a method definition which could have waited 😬

**Review by millerdev — APPROVED** [review]

**Comment by gherceg** [comment]
Closing and re-opening to trigger docs build test

**Comment by gherceg** [comment]
Finally re-tested on staging and exports look good to me 👍🏻

**Pull request merged**
