### PR TITLE
 end_date should be earliest date_start of future subscriptions

### PR DESCRIPTION
**Pull request by nickpell**
Fixes a bug, and removes some obsolete query constraints (now enforced by a table constraint).

### CODE REVIEW

**Comment by nickpell** [comment]
@dannyroberts

**Review by dannyroberts — APPROVED** [review]
@nickpell can you give me a quick description of what makes this check obsolete? Also, is it a _change to something better_ or are you removing it because it's currently a no-op?

**Comment by nickpell** [comment]
@dannyroberts 

This migration adds a table constraint to ensure that the subscription's end date is always greater than or equal to the start date: https://github.com/dimagi/commcare-hq/blob/3e368f969a2f1f1c623bf9c1425b70d8acb533ce/corehq/apps/accounting/migrations/0013_subscription_dates_check.py#L19

**Comment by nickpell** [comment]
(Which makes it a no-op)

**Comment by dannyroberts** [comment]
Aha! Thanks, makes sense!

**Pull request merged**
