### PR TITLE
Upgrade to select2 4.1.0 release candidate

### PR DESCRIPTION
**Pull request by solleks**
## Summary
Upgrade the select2 package from 4.0.0 to [4.1.0 release candidate](https://github.com/select2/select2/releases/tag/4.1.0-rc.0). The main reason to upgrade now is to make Web Apps comboboxes more accessible (i.e. screen readers will read them).

## Product Description
Users of screen readers should now hear the options in a dropdown menu.

Multiple lines of text can be pasted when searching. Otherwise, behavior is expected to be the same as the previous version.

## Safety Assurance

- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### QA Plan

[QA ticket](https://dimagi-dev.atlassian.net/browse/QA-2745)

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Comment by solleks** [comment]
Hi @orangejenny and @stephherbers. Here is the latest approach to making comboboxes more accessible.

**Review by orangejenny — APPROVED** [review]

**Comment by solleks** [comment]
Hi @orangejenny and @stephherbers. It's probably time to push this PR to staging since we have a testing plan for it ([QA issue](https://dimagi-dev.atlassian.net/browse/QA-2745)).

**Comment by orangejenny** [comment]
@solleks @stephherbers Added to staging 👍

**Comment by solleks** [comment]
I made a change to fix [this issue](https://dimagi-dev.atlassian.net/browse/QA-2893). Calling .select2 with first argument 'val' has been deprecated even before this change and on upgrading, the behavior has also changed, so that it no longer clears the combobox. Switching to the preferred method restores our desired behavior.

**Comment by orangejenny** [comment]
@solleks cool, and it looks like there was a staging deploy about an hour after the most recent commit, so the fix should be on staging already and ready for QA to verify.

**Comment by solleks** [comment]
QA testing noted that the clear location button remained on screen after clicking it. That is fixed by triggering a change event after modifying Select2's value. In short, we directly perform [this action](https://github.com/select2/select2/blob/80eb44bec78568b152dc5547269c164cb7b5363c/src/js/select2/core.js#L470), which we used to perform indirectly by calling the deprecated method.

**Comment by solleks** [comment]
QA testing has finished successfully for this PR ([ticket](https://dimagi-dev.atlassian.net/browse/QA-2745)).

**Comment by solleks** [comment]
This PR passed its evaluation by our screen reader expert.

**Comment by orangejenny** [comment]
Awesome. Merging, and it'll go live on prod in a few hours.

**Comment by orangejenny** [comment]
Slight correction: next prod deploy probably will not be tonight, but it'll be sometime in the next week.

**Pull request merged**
