### PR TITLE
a few improvements to the system dashboard

### PR DESCRIPTION
**Pull request by snopoke**
- support showing couch tasks on dashboard for bigcouch
- enable toggling autorefresh
- hide celery tasks args by default
- remove pillow checkpoint reset option

best reviewed per commit

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
these look great!

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
:+1: thanks!

**Pull request merged**
