### PR TITLE
add localsettings hook to post-merge

### PR DESCRIPTION
**Pull request by sravfeyn**
Adding a hook to get notifications when new settings are available. I spent 10 minutes looking how to get prelogin site working and I discovered the new setting `ENABLE_PRELOGIN_SITE` in `localsettings.example.py`. 
@esoergel

### CODE REVIEW

**Comment by czue** [comment]
i'm not sure that the trouble you ran into with the prelogin site necessarily should be solved by this exact mechanism. it seems like better documentation might help more than this commit hook.

can you think of other scenarios where this notification is useful? i'm having a hard time imaging them, and if not, i'm wondering if we should not bother with this change.

**Comment by sravfeyn** [comment]
Yeah, +1 for better docs. This is to just get environment changes like below to get registered in my head, so that I don't need to hunt when needed and I am aware that these things are changed/added in the environment.
- At some point VELLUM_DEBUG was added, if I had seen that change when I updated my code, I wouldn't be hunting how to test vellum locally
- Same with prelogin
- [default_cache setting change](https://github.com/dimagi/commcare-hq/commit/2286700d4bd8ca54d87bd4ab8e5f5d6939e6bf12#diff-75c03275bdad3fd077a71ee5dfd90065)

_Notification_ is just a message containing the diff. And we can turn them off by setting them false in this file (or by default I can make them false). 

Feel free to close the PR though. Something that works for me doesn't mean works for everyone!

**Comment by czue** [comment]
so I would say the `VELLUM_DEBUG` should also be a docs thing, and the `default_cache` change would be better served by proactive notifications to @dimagi/team-commcare-hq when making the PR(and those feel like better channels for this type of thing anyways). 

I don't use these git hooks, so my opinion doesn't matter too much. I'll let you/others decide what to do with this if you aren't yet convinced by me.

**Comment by sravfeyn** [comment]
(Will wait a day more and close if no other comments come in)

**Comment by benrudolph** [comment]
I actually think this a pretty cool change. We don't yet do a good job of notifying the team when localsettings changes happen. This seems like a low overhead and not too spammy way to sanity check whether any localsettings have been modified. How does this exactly manifest itself when a change occurs? After a merge, we all get an email notifying that a localsettings change has taken place?

**Comment by benrudolph** [comment]
I looked more closely, so this will echo that message when we pull from master?

**Comment by sravfeyn** [comment]
(Yeah, just an echo of what changed, notify is a heavy word)

**Comment by esoergel** [comment]
The `dev_settings.py` file is intended to alleviate some of that pain (although it's not much in use yet).  Whenever a setting like this is added, a reasonable default should be added to `dev_settings.py`, so it'll Just Work (for everyone who uses it anyways).

I'd like to build out that file until the only things you need in `localsettings.py` for dev work are settings that are actually local to you - maybe you want a special db name, or fancy logging settings, or `CELERY_ALWAYS_EAGER`.

**Pull request closed without merging**
