### PR TITLE
Drop usercase toggle

### PR DESCRIPTION
**Pull request by kaapstorm**
@snopoke, cc @millerdev

### CODE REVIEW

**Comment by snopoke** [comment]
@amsagoff just confirming you're OK with releasing usercase into the wild.

**Comment by millerdev** [comment]
What's the primary use case (pun not intended) for user-as-a-case?

Reason I ask is the new case management feature we're working on in the form builder could pretty easily provide access to user properties in the session. However, it would likely not allow updating user properties, as I'm guessing user-as-a-case does (since cases are read/write). However, if it's not possible or has undefined or no effect to write to a user's case, then maybe providing access to user properties through some read-only structure makes more sense?

**Comment by czue** [comment]
@millerdev my understanding is that the primary point of user-as-a-case is so the properties can be writeable from the phone (though we also hope that it can eventually replace custom user data as well - but that's more so we don't have two ways to do the same thing)

**Comment by millerdev** [comment]
Cool, that sounds useful. Thanks for the explanation.

**Comment by snopoke** [comment]
@amsagoff ping

**Comment by amsagoff** [comment]
it's passed UAT and QA - let's do it!

**Pull request merged**
