### PR TITLE
Tweaks in domain delete method

### PR DESCRIPTION
**Pull request by kkrampa**
@czue When subscription is leaved in database after domain deletion then creating new domain with the same name raises exception. (Also now inactive web users are included in deletion)

### CODE REVIEW

**Comment by kkrampa** [comment]
@czue Could you merge this and ask someone to delete domain ews-ghana (./manage.py delete_domain ews-ghana)?

**Comment by czue** [comment]
looks reasonable to me. :+1: to merge when tests pass.

@kkrampa is this time sensitive? i likely won't be able to do it today, but can tomorrow. otherwise maybe @calellowitz can take care of it

**Comment by kkrampa** [comment]
On my local machine it's very quick max. 5 minutes.

**Comment by kkrampa** [comment]
@czue Oh I misunderstood you. It's better for me to have this run today but tomorrow should be also ok

**Comment by kkrampa** [comment]
:white_check_mark: @czue 
@calellowitz I guess that Cory is offline now, could you merge this?

**Comment by calellowitz** [comment]
@kkrampa this is to merge before deploy? then run the command after?

**Comment by kkrampa** [comment]
@calellowitz Yes. Thanks!

**Comment by czue** [comment]
@calellowitz @kkrampa do you know if the command got run? if not I can take care of that today

**Comment by kkrampa** [comment]
@czue Domain is still listed on HQ so I guess that @calellowitz didn't run it.

**Comment by czue** [comment]
@kkrampa just ran and looks good

**Comment by calellowitz** [comment]
@czue thats my bad. sorry about that

**Pull request merged**
