### PR TITLE
fix last modified view

### PR DESCRIPTION
**Pull request by snopoke**
'base_doc' is only used by the user model

### CODE REVIEW

**Comment by sravfeyn** [comment]
Is reindex on ICDS not a problem for this view? I was considering to add a new app specific view, since this needs a reindex

**Comment by snopoke** [comment]
On ICDS the DBs sizes are:

DB | Size | Docs
-----|---|---
apps | 0.6GB | 1244
domains | 446KB | 60
users | 6.3G | 600911

It should be fine to reindex that provided we do it during non-peak.

**Comment by sravfeyn** [comment]
Ok, great. So, this means, for the app status warehouse, we just need to do a backfill once this gets deployed on ICDS.

**Comment by snopoke** [comment]
@sravan :white_check_mark: The rollout process will be to initiate a preindex on at least ICDS, india and prod before this get's merged

**Comment by sravfeyn** [comment]
Yeah, I can do that. Just set a private release and then run `./manage.py preindex_everything`?

I can kick it around 7PM IST.

**Comment by snopoke** [comment]
👍

**Comment by sravfeyn** [comment]
The couch preindex finished, but the ES one failed due to timeouts. I think that's good enough for this PR.

**Comment by sravfeyn** [comment]
It seems to have taken only ~10mins for the record.

**Comment by snopoke** [comment]
@sravfeyn please also do the preindex on prod and india before merging this

**Comment by sravfeyn** [comment]
Ok, kicked the reindex on both prod/india

**Comment by sravfeyn** [comment]
This finished fine on Prod, but India, I had been getting this error

```
2019-08-14 06:02:37,289 INFO Triggering view rebuild
2019-08-14 06:02:37,291 INFO Triggering view rebuild
2019-08-14 06:02:37,293 INFO Triggering view rebuild
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/cchq/www/india/releases/2019-08-14_05.07/corehq/preindex/accessors.py", line 63, in sync_design_doc
    temp=temp,                                                                                               [27/408]
  File "/home/cchq/www/india/releases/2019-08-14_05.07/corehq/ex-submodules/dimagi/utils/couch/sync_docs.py", line 32
, in sync_design_docs
    index_design_docs(db, docid, design_name_)
  File "/home/cchq/www/india/releases/2019-08-14_05.07/corehq/ex-submodules/dimagi/utils/couch/sync_docs.py", line 44
, in index_design_docs
    list(db.view(view, limit=0))
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 1022, in
__len__
    return self.count()
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 945, in c
ount
    self._fetch_if_needed()
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 979, in _
fetch_if_needed
    self.fetch()
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 958, in f
etch
    self._result_cache = self.fetch_raw()
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 97[8/408$
etch_raw
    return self._fetch(self._arg, self.params)
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/couchdbkit/client.py", line 759, in r
aw_view
    return view(**params)
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/cloudant/view.py", line 239, in __cal
l__
    **kwargs)
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/cloudant/_common_util.py", line 258,
in get_docs
    resp.raise_for_status()
  File "/home/cchq/www/india/current/python_env-3.6/lib/python3.6/site-packages/requests/models.py", line 940, in ra$se_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://10.203.40.178:25984/commcarehq__apps/_d$sign/last_modified-tmp/_view/by_last_modified?limit=0
2019-08-14T06:04:39Z <Greenlet at 0x7f2cea74b348: sync_design_doc(DesignInfo(db=<Database commcarehq__apps>, app_lab$ temp='tmp')> failed with HTTPError
```

**Comment by sravfeyn** [comment]
@snopoke Any idea why this is failing, I have setup a another release with latest master merged in and I am still getting the same error as above on India.

**Comment by snopoke** [comment]
Got this to work by deleting the view and re-creating it.

**Pull request merged**
