### PR TITLE
App Translations

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts @emord http://manage.dimagi.com/default.asp?252305
is this what you're thinking?

cc: @mkangia

### CODE REVIEW

**Comment by dannyroberts** [comment]
```
ERROR: corehq.apps.app_manager.tests.test_commcare_settings:CommCareSettingsTest.test_translated_strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/test_commcare_settings.py", line 133, in test_translated_strings
    'You need to add {} to static_strings.py'.format(v)
UnboundLocalError: local variable 'v' referenced before assignment
```

**Review by dannyroberts — APPROVED** [review]
Wow, nailed it! Incredibly thorough approach to a pretty annoying problem!

**Comment by dimagimon** [comment]
There are 34 errors:

* corehq/apps/app_manager/commcare_settings.py, line 7 - F401 'static_strings' imported but unused
* corehq/apps/app_manager/static_strings.py, line 9 - E501 line too long (270 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 11 - E501 line too long (232 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 26 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 28 - E501 line too long (200 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 30 - E501 line too long (202 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 47 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 50 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 54 - E501 line too long (302 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 67 - E501 line too long (291 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 98 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 103 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 111 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 116 - E501 line too long (191 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 124 - E501 line too long (308 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 125 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 134 - E501 line too long (185 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 135 - E501 line too long (224 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 151 - E501 line too long (243 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 152 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 157 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 162 - E501 line too long (231 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 167 - E501 line too long (421 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 172 - E501 line too long (317 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 176 - E501 line too long (133 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 177 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 195 - E501 line too long (164 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 200 - E501 line too long (161 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 205 - E501 line too long (169 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 210 - E501 line too long (394 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 216 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 224 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 242 - E501 line too long (399 > 115 characters)
* scripts/yaml_static_strings.py, line 9 - E501 line too long (184 > 115 characters)

**Comment by dannyroberts** [comment]
✅

**Comment by benrudolph** [comment]
aded one more commit to sort and make strings unique

**Comment by dimagimon** [comment]
There are 34 errors:

* corehq/apps/app_manager/commcare_settings.py, line 7 - F401 'static_strings' imported but unused
* corehq/apps/app_manager/static_strings.py, line 26 - E501 line too long (291 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 27 - E501 line too long (200 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 28 - E501 line too long (202 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 43 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 56 - E501 line too long (302 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 65 - E501 line too long (308 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 66 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 68 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 87 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 88 - E501 line too long (317 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 90 - E501 line too long (243 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 97 - E501 line too long (231 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 112 - E501 line too long (224 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 123 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 134 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 146 - E501 line too long (191 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 153 - E501 line too long (164 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 154 - E501 line too long (394 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 155 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 156 - E501 line too long (169 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 157 - E501 line too long (161 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 167 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 172 - E501 line too long (270 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 176 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 177 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 180 - E501 line too long (399 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 181 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 182 - E501 line too long (421 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 183 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 185 - E501 line too long (232 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 188 - E501 line too long (133 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 189 - E501 line too long (185 > 115 characters)
* scripts/yaml_static_strings.py, line 9 - E501 line too long (184 > 115 characters)

**Comment by dannyroberts** [comment]
```
FAIL: corehq.apps.app_manager.tests.test_commcare_settings:CommCareSettingsTest.test_translated_strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/test_commcare_settings.py", line 127, in test_translated_strings
    'You need to add {} to static_strings.py'.format(v)
AssertionError: You need to add Never to static_strings.py
```

**Comment by dimagimon** [comment]
There are 34 errors:

* corehq/apps/app_manager/commcare_settings.py, line 7 - F401 'static_strings' imported but unused
* corehq/apps/app_manager/static_strings.py, line 9 - E501 line too long (270 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 11 - E501 line too long (232 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 26 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 28 - E501 line too long (200 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 30 - E501 line too long (202 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 47 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 50 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 54 - E501 line too long (302 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 67 - E501 line too long (291 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 98 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 103 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 111 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 116 - E501 line too long (191 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 124 - E501 line too long (308 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 125 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 134 - E501 line too long (185 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 135 - E501 line too long (224 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 151 - E501 line too long (243 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 152 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 157 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 162 - E501 line too long (231 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 167 - E501 line too long (421 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 172 - E501 line too long (317 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 176 - E501 line too long (133 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 177 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 195 - E501 line too long (164 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 200 - E501 line too long (161 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 205 - E501 line too long (169 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 210 - E501 line too long (394 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 216 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 224 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 242 - E501 line too long (399 > 115 characters)
* scripts/yaml_static_strings.py, line 9 - E501 line too long (184 > 115 characters)

**Review by emord — APPROVED** [review]
looks good to me. will let danny approve first though

**Comment by dimagimon** [comment]
There are 34 errors:

* corehq/apps/app_manager/commcare_settings.py, line 7 - F401 'static_strings' imported but unused
* corehq/apps/app_manager/static_strings.py, line 26 - E501 line too long (291 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 27 - E501 line too long (200 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 28 - E501 line too long (202 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 44 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 58 - E501 line too long (302 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 68 - E501 line too long (308 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 69 - E501 line too long (126 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 73 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 95 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 96 - E501 line too long (317 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 98 - E501 line too long (243 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 105 - E501 line too long (231 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 121 - E501 line too long (224 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 135 - E501 line too long (226 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 148 - E501 line too long (166 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 160 - E501 line too long (191 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 168 - E501 line too long (164 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 169 - E501 line too long (394 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 170 - E501 line too long (119 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 171 - E501 line too long (169 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 172 - E501 line too long (161 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 182 - E501 line too long (205 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 187 - E501 line too long (270 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 192 - E501 line too long (116 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 193 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 196 - E501 line too long (399 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 197 - E501 line too long (162 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 198 - E501 line too long (421 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 199 - E501 line too long (117 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 201 - E501 line too long (232 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 204 - E501 line too long (133 > 115 characters)
* corehq/apps/app_manager/static_strings.py, line 205 - E501 line too long (185 > 115 characters)
* scripts/yaml_static_strings.py, line 9 - E501 line too long (184 > 115 characters)

**Comment by emord** [comment]
may want to merge master since https://github.com/dimagi/commcare-hq/pull/16436/ got merged

**Comment by benrudolph** [comment]
@emord since danny is offline do you mind approving if it looks ok to you?

**Pull request merged**
