### PR TITLE
Update calls to simple_post to expect a requests.response

### PR DESCRIPTION
**Pull request by TylerSheffels**
Accompanies https://github.com/dimagi/dimagi-utils/pull/344 @benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
@calellowitz we can't deploy if this is not merged. or we need to revert https://github.com/dimagi/dimagi-utils/pull/344 or don't commit the submodule. just a heads up

**Comment by czue** [comment]
@TylerSheffels build fail looks real.

```
======================================================================
ERROR: test_case_close_format (corehq.apps.repeaters.tests.test_repeater.CaseRepeaterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/repeaters/tests/test_repeater.py", line 234, in test_case_close_format
    payload = self.repeat_records(self.domain_name).all()[0].get_payload()
IndexError: list index out of range
----------------------------------------------------------------------
```

**Comment by TylerSheffels** [comment]
@benrudolph See https://github.com/dimagi/commcare-hq/commit/bfdc9ac0a41c574acaec3cc7fd7989178efe2061 for the test fix, but this really confuses me. That import is unused as far as I can see (and also not imported poorly from this module), but this fixes the tests.

**Comment by czue** [comment]
could always beef up the comment so the next person doesn't make this mistake

**Pull request merged**
