### PR TITLE
remove reports_forms/all_submitted_users

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dimagimon** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by dannyroberts** [comment]
Net change: -1 view
Indexing load: 3 views in `_design/reports_forms` (2 of them over forms)

**Comment by dannyroberts** [comment]
:racehorse: :tada:

**Comment by czue** [comment]
:bomb: :boom:

**Comment by czue** [comment]
@dannyroberts for the rest of these should we break up the remainder of the doc whenever we update it? I think we've unofficially been trying to make that the policy moving forwards

**Comment by dannyroberts** [comment]
That seems smart; do we have a preferred convention for naming? Seems like to drive home that design docs are 1-to-1 with views, the naming should be shifted entirely to design doc and the views themselfs should all be named some dummy word like 'view', so we'd change `reports_forms/all_forms` to something like `reports_all_forms/view`. Sound good?

**Comment by czue** [comment]
:+1: by me

**Pull request merged**
