### PR TITLE
set couch auth for docker

### PR DESCRIPTION
**Pull request by snopoke**
@dimagi/team-commcare-hq FYI adding default admin user to CouchDB docker container.

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Comment by proteusvacuum** [comment]
yay!

**Comment by millerdev** [comment]
Awesome!

Do we need to rebuild our containers or is there any other action necessary for pre-existing containers? I'm being lazy and not just trying it on my dev setup, so feel free to just ignore me if it will be obvious when I get around to that.

**Comment by snopoke** [comment]
No rebuild required:
```
$ docker rm -f hqservice_couch_1
$ ./scripts/docker up -d
```

**Comment by emord** [comment]
This might be causing tests to fail intermittently. Seeing a lot of errors in travis tests "Waiting for link to COUCH" example: https://travis-ci.org/dimagi/commcare-hq/jobs/251186023

**Comment by snopoke** [comment]
@emord it does seem that way. I looked at the startup script and running with auth definitely does more work that with admin part: https://gitbox.apache.org/repos/asf?p=couchdb.git;a=blob;f=dev/run;h=2f25071a150142cc703cc4a89de0a7a7015a7b9a;hb=refs/heads/master (see `cluster_setup` vs `cluster_setup_with_admin_party`)

I'll look into making it use admin part in travis only.

**Comment by emord** [comment]
@snopoke @dannyroberts @proteusvacuum Do you guys remember why we added this in the first place?

asking because @sheelio had some issues with running docker locally due to the difference between travis having admin party, but locally needing a password.

**Comment by proteusvacuum** [comment]
My comment "yay!" was because at one point formplayer required you to have a couch user to run, and that user was blown away every time I restarted my computer / docker. However, formplayer no longer uses couch so it doesn't matter any more. Not sure if that was the original reason for this though.

**Comment by emord** [comment]
@proteusvacuum Awesome, that's what I remembered. @sheelio looks like you're good to change both of those docker scripts

**Pull request merged**
