### PR TITLE
Add transforms to UCR data sources

### PR DESCRIPTION
**Pull request by NoahCarnahan**
@czue another one from the backlog (which will be useful for the report builder I think)

Adds the ability to specify a transform on `expression` data source indicators. Uses the same transforms as report columns. [ticket](http://manage.dimagi.com/default.asp?164112).

When I was writing this, I started to wonder if it makes more sense to instead add a "transform" type expression that can be nested like the boolean expressions. Transforms are also functionally similar to the datatype feature. I wonder if it makes sense to combine those concepts. Thoughts?

FYI @dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
nice!

**Comment by czue** [comment]
cool how easy this was.

**Comment by NoahCarnahan** [comment]
Yeah, it was nice how it all sorta just fell into place without me writing practically anything :)

**Comment by czue** [comment]
It does seem useful to be able to chain transforms at a minimum.

**Comment by czue** [comment]
not totally sure what you're envisioning but i think I like the concept and feel free to take a crack at it!

**Pull request merged**
