### PR TITLE
Zero should not be considered an empty value

### PR DESCRIPTION
**Pull request by esoergel**
https://dimagi-dev.atlassian.net/browse/HI-143

There's a bug where default values of 0 don't show up in web apps and live preview.  This is because 0 was being misinterpreted as a missing value.

I'm not 100% sure which falsy values might appear at this place, so I took a conservative approach of whitelisting `0` and leaving the existing behavior for the rest (the current behavior seems appropriate for `''`, `null`, and `undefined`)

### CODE REVIEW

**Review by mkangia — APPROVED** [review]
looks fine from code perspective.
Can't weigh in on the decision to do so.

**Review by jmtroth0 — APPROVED** [review]
lgtm. i agree with the decision to whitelist

**Comment by jmtroth0** [comment]
Test failure looks real though. It seems like hoisting didn't save the ordering here. https://travis-ci.org/dimagi/commcare-hq/jobs/466762863

**Comment by esoergel** [comment]
Odd, must've hit a cache or something locally when I moved it there.

**Review by jmtroth0 — APPROVED** [review]

**Pull request merged**
