### PR TITLE
add test tasklist datasource with nullable tu_id and dto_id columns

### PR DESCRIPTION
**Pull request by nickpell**
https://sentry.io/dimagi/commcarehq/issues/311047779/

Same as test_tasklist_v3.json except tu_id and dto_id are marked as nullable.

code buddy @kaapstorm

### CODE REVIEW

**Review by calellowitz — CHANGES_REQUESTED** [review]
I think you will want to talk to the project team about this. They may be purposefully excluding null values, in which case we should be changing the filters to properly exclude them, not making the column more permissive.

**Comment by kaapstorm** [comment]
Pending product team feedback, seems fine to me otherwise. 

:recycle: :construction_worker_man: Travis got stuck.

**Comment by nickpell** [comment]
@calellowitz I wrote this data source, and wasn't intentional about setting is_nullable to true or false.  This is only used by the task list reports, which always filter by location, so none of the cases that error will ever appear to an end user.  So this change should fix the error and speed up rebuild times without affecting the end user.

**Comment by emord** [comment]
fwiw it's usually easier to view these changes if you have one commit that copies an existing report to a new file and then make changes in a second commit.

Generally agree about adding better filters, but I also think it would just be good to have these data sources not erroring.

If you don't want to do a rebuild, once this is deployed I think you could just do a `insert into <new_table> select *  from <old_table>)` or something similar. 

Also you need to add this to settings.py

**Comment by nickpell** [comment]
@emord Thanks for flagging settings.py, updated

**Comment by nickpell** [comment]
> fwiw it's usually easier to view these changes if you have one commit that copies an existing report to a new file and then make changes in a second commit.

good to know, thanks

**Review by calellowitz — APPROVED** [review]

**Review by emord — APPROVED** [review]

**Pull request merged**
