### PR TITLE
include all xforms doc types in v2 fast reindex

### PR DESCRIPTION
**Pull request by dannyroberts**
@snopoke I wasn't sure how to run this, but does it look right to you?

### CODE REVIEW

**Comment by snopoke** [comment]
Yes that looks right, thanks. You can run it as follows:
```
    $ ./manage.py ptop_reindexer_v2 form
```

**Comment by dannyroberts** [comment]
@snopoke FYI, the following stacktrace appears both on my branch and on master when i run 

```
 $ ./manage.py ptop_reindexer_v2 form
```
after about 13 line-pairs like this:
```
2016-07-06 14:52:51,987 INFO reindexer xforms_2016-06-09_CouchXFormToElasticsearchPillow_reindex,sending payload,1000
Processed 13000/14000 of 75472 documents in 0:02:41.616566 (0:11:49.632768 remaining)
```
Stacktrace:
```
Traceback (most recent call last):
  File "./manage.py", line 96, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/droberts/.virtualenvs/cchq/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/droberts/.virtualenvs/cchq/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/droberts/.virtualenvs/cchq/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/droberts/.virtualenvs/cchq/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/droberts/dimagi/commcare-hq/corehq/apps/hqcase/management/commands/ptop_reindexer_v2.py", line 94, in handle
    reindexer.reindex()
  File "./corehq/ex-submodules/pillowtop/reindexer/reindexer.py", line 179, in reindex
    processor.run()
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_doc_processor.py", line 357, in run
    for doc in self.docs_by_type:
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_doc_processor.py", line 94, in __iter__
    for result in paginate_view(self.db, **args):
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_helpers.py", line 181, in paginate_view
    datetime.datetime.utcnow() - start_time)
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_helpers.py", line 133, in view_ending
    handler.view_ending(db, view_name, kwargs, total_emitted, time)
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_doc_processor.py", line 415, in view_ending
    processor.process_chunk()
  File "/Users/droberts/dimagi/commcare-hq/corehq/util/couch_doc_processor.py", line 455, in process_chunk
    ok = self.doc_processor.process_bulk_docs(self.changes, self.couchdb)
  File "./corehq/ex-submodules/pillowtop/reindexer/reindexer.py", line 125, in process_bulk_docs
    payloads = prepare_bulk_payloads(bulk_changes, max_payload_size)
  File "./corehq/ex-submodules/pillowtop/utils.py", line 178, in prepare_bulk_payloads
    for bulk_chunk in chunked(bulk_changes, chunk_size):
  File "./submodules/dimagi-utils-src/dimagi/utils/chunked.py", line 15, in chunked
    buffer.append(it.next())
  File "./corehq/ex-submodules/pillowtop/utils.py", line 170, in build_bulk_payload
    "_id": doc['_id']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by snopoke** [comment]
Thanks. I'll look into it tomorrow.

**Comment by dannyroberts** [comment]
Build failed with

```
======================================================================
FAIL: test_get_all_cases_modified_since (corehq.form_processor.tests.test_case_dbaccessor.CaseAccessorTestsSQL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/form_processor/tests/test_case_dbaccessor.py", line 602, in test_get_all_cases_modified_since
    self.assertEqual(8, len(cases_back))
AssertionError: 8 != 7
```

but that seems unlikely to be caused by this. @snopoke any idea. I'll merge master in case this was fixed on another branch.

**Comment by snopoke** [comment]
I played around with the reindexer locally but couldn't reproduce the error you got `TypeError: 'NoneType' object has no attribute '__getitem__'`. I could add a check that the doc is not None but I'd like to understand why it's None. Could you do a bit more digging locally to see what's happening?

If you run the same command again it should resume the reindex from the begging of the last batch.

Initially I thought this might be the issue but I don't really see how since none of the changes passed in would have `deleted=True`: https://github.com/dimagi/commcare-hq/pull/12351

**Comment by snopoke** [comment]
Think I found the issue: https://github.com/dimagi/commcare-hq/pull/12351/commits/0dbc45c6e64e80ab0387f57383eafe9f22db5824

**Pull request merged**
