### PR TITLE
new build update policy

### PR DESCRIPTION
**Pull request by wpride**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by NoahCarnahan** [comment]
Hey @wpride ,
I'm having a little trouble following these instructions. I'm looking at the latest 2.19 build, [#345998](http://jenkins.dimagi.com/view/CommCare%20Mobile/job/commcare-mobile-2.19/345998/), but I don't see the "posttmp" directory. Looks like the structure is `"Build Artifacts" -> "application" -> "dist"`. [This](http://jenkins.dimagi.com/view/CommCare%20Mobile/job/commcare-mobile-2.19/345998/artifact/application/) is the page I'm looking at. Am I on the wrong page or something?

**Comment by wpride** [comment]
Hmm no you're right, never made the build changes to the 2.19 release
branch just the trunk. I'll get this change PRed to the release branch
today and ping this thread when its ready. Thanks Noah.

**Comment by NoahCarnahan** [comment]
great, thanks!

**Comment by wpride** [comment]
should be good to go:

http://jenkins.dimagi.com/job/commcare-mobile-2.19/346000/artifact/application/posttmp/

**Comment by NoahCarnahan** [comment]
:+1:

**Pull request merged**
