### PR TITLE
JS guide updates

### PR DESCRIPTION
**Pull request by orangejenny**
Docs only, review by commit.

### CODE REVIEW

**Comment by orangejenny** [comment]
(killing build)

**Comment by orangejenny** [comment]
@millerdev I'm merging because we just advertised these docs to some external devs, but still happy to hear feedback.

**Comment by czue** [comment]
thank you for this!! :fire:

**Comment by czue** [comment]
read the docs hasn't updated yet. last update is [this commit](https://github.com/dimagi/commcare-hq/commit/f3835983db381fa869ce1572b022981357725814). is that a manual process?

**Comment by orangejenny** [comment]
Hmm, looks like it's supposed to update every time we push but also like
the last build was back in August and failed:
https://readthedocs.org/projects/commcarehq/builds/11596547/

I'll see what I can figure out.

**Comment by czue** [comment]
also happy to poke around the docs issue if you've got your hands full, @orangejenny

**Comment by orangejenny** [comment]
If you have time, that would be lovely. The last docs-related code I saw
was back in https://github.com/dimagi/commcare-hq/pull/25855, which was
well before the build started failing.

**Comment by czue** [comment]
Sure. Got a more promising lead. Looks like you got bit by the ol' "commcarehq.readthedocs" versus "commcare-hq.readthedocs". Real build error is here: https://readthedocs.org/projects/commcare-hq/builds/12871406/ introduced in https://github.com/dimagi/commcare-hq/commit/f7d4496e6e2005c87eed9b3c8d35c71b860bc884

```
  error: xmlsec1 is not installed or not in path.
```
Guessing we just need to maybe add a mock or something similar to how we do with PIL. Can poke around.

**Comment by orangejenny** [comment]
argh, I did get bitten. At least that new build error has a clear cause.

**Pull request merged**
