### PR TITLE
upgrade django compressor

### PR DESCRIPTION
**Pull request by nickpell**
https://django-compressor.readthedocs.io/en/latest/changelog/

### CODE REVIEW

**Comment by nickpell** [comment]
@biyeun This is on staging.  Any recommended steps for QA?

**Comment by nickpell** [comment]
Just wanted to see if you had any additional recommendations for QA. @biyeun

**Comment by biyeun** [comment]
if there hasn't been any 500ing on css + javascript then we're probably good if it's been up there for a week and people have been testing stuff on staging @nickpell

**Comment by nickpell** [comment]
cool, so good to merge?

**Comment by biyeun** [comment]
:+1:

**Pull request merged**
