### PR TITLE
Revert "temporarily remove troublesome migration and dependent test"

### PR DESCRIPTION
**Pull request by czue**
Just opening what is hopefully the last in a long line of reversions so I have something to work from. Will ping when ready.

- [x] figure out why it's failing to deploy to certain envs
- [x] fix issues
- [x] Run [ansible migration](https://github.com/dimagi/commcarehq-ansible/pull/1055) (`commcare-cloud <env> ansible-playbook deploy_db.yml --tags=pghashlib`)
   - [x] staging
   - [x] prod
   - [x] india
   - [x] icds
   - [x] enikshay
   - [x] swiss
   - [x] pna
   - [x] l10k
- [x] resolve migration conflicts if necessary

### CODE REVIEW

**Comment by czue** [comment]
ok this has been run on the envs listed above. do I need to do the others like swiss before it can be merged? i think for any monolith it should already be installed?

**Comment by snopoke** [comment]
Also not 100% sure about monoliths but since this is created per DB I think they would have the same issue.

**Comment by czue** [comment]
yeah do all monoliths have shard setups now?

**Comment by snopoke** [comment]
Yes

**Comment by emord** [comment]
@snopoke @czue I don't think that's true for swiss. It was created before sharding right?

**Comment by emord** [comment]
@czue you'll also need to deploy to PNA

**Comment by czue** [comment]
Ok, have deployed to all environments. Swiss and L10k didn't seem to have sharding setup so they were noops. I _think_ this should finally be good to go once tests pass.

**Comment by czue** [comment]
:white_check_mark:

**Comment by snopoke** [comment]
:clap:

**Pull request merged**
