### PR TITLE
enikshay: V2 tasklist data sources

### PR DESCRIPTION
**Pull request by sheelio**
@nickpell 

These are the V2 versions of the task list data sources.  Once this is deployed, we'll need to rebuild them asynchronously.  Once that's done, we can repoint all the existing reports to these and remove the v1 data source.

### CODE REVIEW

**Review by nickpell — APPROVED** [review]
looks good pending tests

**Comment by sheelio** [comment]
@nickpell 

Can you run the async rebuild command for these tables once deployed?

**Comment by nickpell** [comment]
will do

**Comment by nickpell** [comment]
I kicked off the async rebuild.

@sheelio The table id for these static data sources is identical as the dynamic reports, which means that the static and dynamic data sources point to the same tables.  This has the unfortunate affect that deploying the static data sources kicked off a synchronous rebuild of those tables.  I killed the rebuild for tests before it executed, but the episode table got wiped.

When the dynamic data sources get deleted, we should be careful to make sure that we don't accidentally delete the tables.

**Pull request merged**
