### PR TITLE
Linked docs to location safe report builder flag

### PR DESCRIPTION
**Pull request by orangejenny**
Very minor.

### CODE REVIEW

**Review by mkangia — APPROVED** [review]

**Review by czue — APPROVED** [review]
oops, sorry this slipped past my filters

**Review by czue — CHANGES_REQUESTED** [review]
oops, actually you need to fix kwargs before args issue:
```
  File "corehq/toggles.py", line 1241
    [NAMESPACE_DOMAIN],
    ^
SyntaxError: positional argument follows keyword argument
```

**Comment by czue** [comment]
(feel free to merge when done)

**Comment by orangejenny** [comment]
@czue Gah, thanks for flagging - I hadn't even looked at the test failures, figured they were unrelated and hadn't gotten around to kicking the build.

**Pull request merged**
