### PR TITLE
Revert "Revert "Make search button sticky""

### PR DESCRIPTION
**Pull request by esoergel**
## Technical Summary
Reverts https://github.com/dimagi/commcare-hq/pull/35059, reintroducing https://github.com/dimagi/commcare-hq/pull/34975
I added a couple commits on top of that to resolve the problem.  The issue was that especially-wide elements (a table) overflowed the container.  This happened because the flex element was the container, and apparently making a flexbox removes width constraints?  I found minimum reproduction steps that demonstrated that.  At any rate, shuffling things around and making the main content live inside a container inside the flexbox fixed the width so that too-wide elements scroll horizontally, as before.

### QA Plan
Forthcoming

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by AddisonDunn — APPROVED** [review]
These changes look good to me and I have been building off of them--look out for a PR from me that uses these changes and modifies them some.

**Review by Jtang-1 — APPROVED** [review]
Changes make sense. Is there a ticket we can link in the PR that references the problem that caused the initial revert? 

Also, the PR mentions this will be QA'ed. That would also make me more comfortable if this goes through QA

**Comment by esoergel** [comment]
@Jtang-1 
I can't find a ticket - don't remember if there was one, but here's a screenshot of what the problem looked like:
image

And I explain the issue with an example here:
https://dimagi.slack.com/archives/C02QG63MU/p1725298244300919

**Review by AddisonDunn — APPROVED** [review]

**Review by Jtang-1 — APPROVED** [review]
original branch was approved and the branch that was just merged in was separately approved. So approving as a whole.

**Review by Jtang-1 — APPROVED** [review]

**Pull request merged**
