### PR TITLE
add dialog encouraging upgrade

### PR DESCRIPTION
**Pull request by dannyroberts**
when a project cannot add more mobile workers

~~Screenshot:~~
screen shot 2015-12-17 at 1 47 19 pm

(The “-1” and “USD 0” are an artifact of how I was triggering this screen to show up locally without jumping through the hoops of actually setting up a community project with 50 users; those numbers will show something sensical in any real production situation.)

~~Update Subscription button takes you to Current Subscription.~~

Screenshot:
screen shot 2015-12-17 at 4 21 09 pm

When you are an admin, you won't see the “Note: ...” at the bottom, and the “Confirm Billing Information” button will be enabled and lead to the “Confirm Billing Information” page (/a/<domain>/settings/users/commcare/confirm_charges/).

### CODE REVIEW

**Comment by millerdev** [comment]
GTM on test pass (are there any tests for this?)

**Comment by dannyroberts** [comment]
@amsagoff Can you review the copy? It's exactly what used to be there, except I added the “Update Subscription” button

**Comment by dannyroberts** [comment]
@millerdev no there aren't any relevant tests for this part of the UI

**Comment by amsagoff** [comment]
Billing admin's no longer exist, so we should say "admin web user" instead.

Where does the "Update Subscription" button take you? Assume it should take
you to the Billing Information page and the button should be named "Confirm
Billing Information"

Thanks!

**Comment by dannyroberts** [comment]
Update Subscription button takes you to Current Subscription page. @biyeun said this is the most appropriate place to take someone, since you can unlock it by adding cache as well. If you disagree you and @biyeun should come to an agreement

**Comment by amsagoff** [comment]
Will take offline with Biyeun

**Comment by biyeun** [comment]
@dannyroberts i guess it was confirm billing information, so let's stick with the original

**Comment by amsagoff** [comment]
B and I offlined, and we're on the same page now. Confirm billing info it
is!

**Comment by millerdev** [comment]
I'm not following closely enough to know the status of this. Let me know when it's good to merge.

**Comment by millerdev** [comment]
Correction: when it's ready for another review pass+possible merge.

**Comment by dannyroberts** [comment]
@amsagoff updated w/ screenshot

**Comment by amsagoff** [comment]
:+1: from product

**Comment by dannyroberts** [comment]
Thanks. Ok @millerdev g2g

**Pull request merged**
