### PR TITLE
Fix packages that are affected by setuptools upgrade that breaks use_…

### PR DESCRIPTION
**Pull request by sravfeyn**
Switch simpleeval package to Dimagi's fork https://github.com/dimagi/simpleeval to address a bug in the upstream project. Replace suds-jurko with suds-py3 

### Automated test coverage

NA

### QA Plan

NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

## Final self-reflection
- [x] My safety story above is convincing and gives me confidence that this PR will not introduce a regression

### CODE REVIEW

**Comment by proteusvacuum** [comment]
Test failure looks related? 
```
Requirements are inconsistent.  Did you run 'make requirements'?
```

**Review by kaapstorm — APPROVED** [review]

**Comment by sravfeyn** [comment]
Thanks Simon. I think they haven't still made a release, so it will still be a github package, so I am merging in this for now. Will update it back once a release is made.

**Comment by AmitPhulera** [comment]
I came across this while updating a dependency. I see that a new version of simpleeval is released, would it be safe to move back to the original package?
@sravfeyn

**Comment by sravfeyn** [comment]
Sure, I think it should be safe if the underlying bug is addressed.

**Pull request merged**
