### PR TITLE
App code instead of bitly

### PR DESCRIPTION
**Pull request by kaapstorm**
Spec: https://docs.google.com/document/d/1GHLayNW9xHWWyj_sEeRGh5T7oepGsvldLLg6uyJZYH4/edit#heading=h.blt0fbwgkgt2

With app code:
app_code

Without app code:
app_code_falsey

I'm not 100% happy with the appearance here, so I tried using a `<ul>` for the installation options. I'll PR it separately, and you can choose which one looks better. Labelling "hold off" for now.

Nitpicky, I know, but I ummmed and aaahed a bit about the "Android device" in one sentence and then "Android" in the next. I think calling it "an Android" is OK (like "a Blackberry", as opposed to, say, "an iOS" or "a Windows"), but I think it would sound better if we chose to use "Android" either as an adjective or a noun throughout. OK, that does sound super nitpicky. But I'll leave it in here so it can jump out at you too now. :smiling_imp: 

@amsagoff @biyeun cc @wpride

### CODE REVIEW

**Comment by kaapstorm** [comment]
I think that's a very reasonable compromise @amsagoff .

Screenshot with "Or":
app_code_with_or

**Comment by amsagoff** [comment]
Looks good, thanks Norman!

**Comment by kaapstorm** [comment]
I accidentally left "Hold off" on this after the discussion ended. Flipping to "up for grabs".

**Comment by kaapstorm** [comment]
... aaactually, let's stage this first. :neutral_face:

**Comment by kaapstorm** [comment]
Hmmm. Tested on staging. The "bit.ly" + \<app code> results in the right URL. And CommCare on the device connects to the URL as expected ... **but** bit.ly URLs for builds on staging result in 404s. bit.ly URLs for builds on prod are fine, of course.

The change in this PR doesn't affect the bit.ly URL, so I'm sure this change isn't what's broken staging. It doesn't fill me with confidence though, not to see it working smoothly. I'm also reluctant to try and figure out what exactly on staging is causing the 404, when it's not the URL, and it's not the UI, and its cause is probably temporary. so I'm going to get on with something else on my to-do list, and come back to this, and see whether it magically fixes itself and I have no reason not to remove the "hold off" label.

**Comment by amsagoff** [comment]
Not sure if you're already factoring this in but we want to release this at
the same time as mobile 2.26. I can loop back around on this PR when that
happens.

**Comment by orangejenny** [comment]
Hi Norman, fyi I merged master and had some conflicts in releases_deploy_modal.html, you might want to take a look at this and make sure it's still the way you want it.

**Comment by wpride** [comment]
@kaapstorm just tested this out (bit.ly install on staging) and its working fine now that the lazy-jar branch was removed.

**Comment by kaapstorm** [comment]
@amsagoff I think this is actually good to go right now. The weirdness on staging is *most probably* totally unrelated, because all the independent bits seem to be working either on staging or on my local dev environment. But I want to be convinced that the bits are going to work together on prod before I'm happy to take off the "hold off" label.

I'll get a bit.ly API key, and use it to generate an app code locally, and just ignore staging.

What's the timeframe on 2.26? If this gets merged today, would that be OK?

**Comment by kaapstorm** [comment]
(Damn. When I wrote that last comment I hadn't refreshed, and missed @wspride and @orangejenny's comments. That's great, Will. Jenny, I saw the same conflict when I staged this. I'll take a look.)

**Comment by kaapstorm** [comment]
@orangejenny your merge was spot on. 

I missed a translate tag. I think we're good to go now.

**Comment by amsagoff** [comment]
Ideally we would release this with 2.26 - so either hold off merge or merge under a flag for now. Let me know if that sounds like undue overhead.
@wpride estimate on 2.26 release?

**Comment by wpride** [comment]
Estimate mid to late next week. Don't think holding off merge is any issue

**Comment by kaapstorm** [comment]
OK, cool. Thanks guys. Holding off til Wed 10th.

**Comment by kaapstorm** [comment]
Dropping "Hold off". Labelling "Up for grabs". 

This PR was held back to coincide with Mobile 2.26 ... which is round about now. So go on, just before you get stuck into the Hackathon, merge this puppy. You know you want to.

**Comment by wpride** [comment]
Please continue to hold off. Due to J2ME bugs and summit 2.26 won't be released until early next week at earliest

**Comment by amsagoff** [comment]
2.26 released, you can remove the hold and merge!

**Pull request merged**
