### PR TITLE
Add command to force zone-aware replication

### PR DESCRIPTION
**Pull request by esoergel**
As described here https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html
@dannyroberts @millerdev @nickpell

With https://github.com/dimagi/commcarehq-ansible/pull/433

### CODE REVIEW

**Comment by millerdev** [comment]
looks good to me, but I don't have much context.

**Comment by snopoke** [comment]
Just FYI we're using 1.7 so the docs page is https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-cluster.html 

In this case it's basically the same but good to make sure.

**Comment by snopoke** [comment]
Is there a corresponding PR to set the zone's of the nodes or are you going to do that manually?

**Comment by dannyroberts** [comment]
@snopoke I believe that's https://github.com/dimagi/commcarehq-ansible/pull/433

**Comment by dannyroberts** [comment]
(zone value per node will be set in inventory file)

**Comment by esoergel** [comment]
Yup, and that shouldn't be merged until after it's been deployed, so I hadn't PR'd it, but I just created one so all the cards will be on the table: https://github.com/dimagi/commcare-hq-deploy/pull/43

**Pull request merged**
