### PR TITLE
ES auto-create-index to False again

### PR DESCRIPTION
**Pull request by sravfeyn**
Just opening for tests (and tests duration), not for merging.

### CODE REVIEW

**Comment by sravfeyn** [comment]
Hey @millerdev  tests are now passing and this is good to go pending a review. I made two changes to make sure tests don't keep waiting for ES.

1. Don't retry on ES error (during tests)
2. Keep ES timeout to 5 seconds int tests instead of 30 seconds default otherwise.

**Review by millerdev — APPROVED** [review]
Nice! Is it possible to make ES index errors bubble up as hard errors in tests (rather than waiting for timeout, but then ignoring the error)?

Suggestion: what do you think of squashing the commits in this PR down to a single commit?

**Comment by sravfeyn** [comment]
> Nice! Is it possible to make ES index errors bubble up as hard errors in tests (rather than waiting for timeout, but then ignoring the error)?

I haven't actually found why sometimes the request is timing out when the index doesn't exist. The errors are coming from the background django signals that send data to ES on user save, I am afraid there isn't a straightforward way to hardfail. Since it's a background signal I wonder if it's adding to the extra run time at all. (Though I am not super sure). 

> Suggestion: what do you think of squashing the commits in this PR down to a single commit?

Yeah, good idea. I can use github 'Squash and merge' feature, if this is good to go.

**Comment by sravfeyn** [comment]
@millerdev

**Comment by millerdev** [comment]
Yep, good to go.

> Since it's a background signal I wonder if it's adding to the extra run time at all. (Though I am not super sure).

It definitely adds to the run time since it's happening in the same process. I believe signals run on the main thread.

**Comment by sravfeyn** [comment]
Also opening a PR to see if we can just skip sending users to es in tests altogether. https://github.com/dimagi/commcare-hq/pull/27849

**Pull request merged**
