### PR TITLE
add widget to choose whether j2me should use http

### PR DESCRIPTION
**Pull request by nickpell**
Putting behind a feature flag until I've been able to test everything end-to-end on prod and india.

Recommend 🐡

### CODE REVIEW

**Comment by nickpell** [comment]
Would like to merge to master so I can test that j2me is working end-to-end on india

@esoergel @emord

**Comment by emord** [comment]
Looks fine to me but merge conflicts

**Comment by nickpell** [comment]
✅

**Comment by esoergel** [comment]
Woohoo! awesome

**Pull request merged**
