### PR TITLE
Proper includes for touchforms-inline

### PR DESCRIPTION
**Pull request by benrudolph**
enchantress: @millerdev 
@czue 
This updates touchforms-inline so that it works with the new file paths. Without it, edit submissions will break

### CODE REVIEW

**Comment by benrudolph** [comment]
@czue i believe this also fixes this bug: http://manage.dimagi.com/default.asp?167165

my hunch is that `markdown` can't be found in that file and stops execution of that script. when it stops, `inElementSet` becomes undefined.

**Comment by millerdev** [comment]
:+1:

**Comment by czue** [comment]
:+1: from me. not merging due to label

**Comment by benrudolph** [comment]
Want to wait for a successful touchforms deploy before merging this (should be today, god willing)

**Comment by benrudolph** [comment]
touchforms deploy went through so this is now good to go. @czue @millerdev

**Pull request merged**
