### PR TITLE
webapps remove prevalidate

### PR DESCRIPTION
**Pull request by knguyen142**
https://dimagi-dev.atlassian.net/browse/SAAS-11161

##### SUMMARY

Currently when we submit we send up only answers that are [valid](https://github.com/dimagi/commcare-hq/blob/fd3e7ac68c78e08851f7773c2ff5adae2b0e1c61/corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js#L487) (do not have any errors) and if there are any invalid answers, we send up a `prevalidated=false` flag. 

When formplayer receives the submission, it rejects if [one of the 2](https://github.com/dimagi/formplayer/blob/130b830764e9307e78ba8283e760fe410fafd6a4/src/main/java/org/commcare/formplayer/application/FormController.java#L166-L167):
1. it's own validation check based on the answers submitted fail
2. `prevalidated=false` is sent up

It seems like this has logic has been there since the beginning. This change does the following:
1. Sends up all answers (including invalid/errored ones)
2. sends up `prevalidated=true` (cannot remove this var yet, must remove from formplayer first)

##### PRODUCT DESCRIPTION

This is deployed to staging and can be seen in this [app](https://staging.commcarehq.org/a/test-42/apps/view/0d5d20962b58c3f9ccca6b577de376bc/).

required-conditions

Also ccing @ctsims in case he knows something about `prevalidated`.

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]
Code looks fine. What do you think is the risk level of this PR?

**Comment by knguyen142** [comment]
@orangejenny The only thing I can think of is if there is a UX/product case where the browser marks the question as invalid, but formplayer would accept it. The original implementation would fail while this change would make it pass. 
Can you think of anything with that use case? 
When I look at code, there's 2 types of error functions (`error()` and `serverError()`). I'll do a test later, but [this](https://github.com/dimagi/commcare-hq/blob/c0564c662fab472045fdb1b57e4610c1c8da811b/corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js#L697) is an example. I believe if the selection is not an option in the combobox entry it will have a browser error and send up `prevalidate=false` and it will fail. However, if we make `prevalidate=true` we have to make sure formplayer also knows that the selection is not valid. 
I did a quick search of `.error(` and it occurs in some places for type validation, etc. I'm hoping that this is just a optimization that we do on the front end, and that we also do these same validations on server.

**Comment by orangejenny** [comment]
@knguyen142 Cool, that all sounds good and logical to me, thanks for writing it out. My understanding is also that any client-side validation is just a convenience and is also done by formplayer.

**Comment by orangejenny** [comment]
@knguyen142 I just realized https://github.com/dimagi/commcare-hq/pull/28701 should make that specific combobox error no longer an issue. The old widget allowed you to enter free text, but the new one does not.

**Comment by knguyen142** [comment]
I'm going to close this for now to not add complexity to the system, but will reopen if it's needed in the future.

**Pull request closed without merging**
