### PR TITLE
delete ilsgateway and ewsghana tests

### PR DESCRIPTION
**Pull request by snopoke**
These projects are no longer active. As a first step to removing the code
I'm deleting the tests to shorten our build times.

### CODE REVIEW

**Comment by snopoke** [comment]
@czue FYI

**Review by czue — CHANGES_REQUESTED** [review]
@snopoke ewsghana is still active so sadly I think we need to / should keep those tests around (and we can't delete its code either)

**Comment by snopoke** [comment]
@czue updated

**Review by czue — APPROVED** [review]
image not bad...

**Comment by emord** [comment]
I'm not sure we'll be able to delete these:

```
  File "/mnt/commcare-hq-ro/custom/ewsghana/tests/handlers/utils.py", line 23, in <module>
    from custom.ilsgateway.tests.test_script import TestScript
ImportError: No module named tests.test_script
```

from my understanding ewsghaha builds off of ilsgateway? I wouldn't be surprised if there are some things tested in ilsgateway that are also applicable for ewsghana (but not explicitly tested)? we may just want to begin by moving ilsgateway parts over to ewsghana until there are no more imports, and then delete whatever remains

**Comment by snopoke** [comment]
I thought this would be a quick win but doesn't look like it. I'll come back to it when I have more time.

**Pull request closed without merging**
