### PR TITLE
hotfix to make j&k unclickable

### PR DESCRIPTION
**Pull request by calellowitz**
##### SUMMARY

The districts are all messed up for J&K so this makes sure you can't click into the state outline.

Explanation: The js matches state name to our locations via the id field. I changed it so it was still clear but no longer matched. I incremented the version so the new version would be served, and tried to fix tests so this would be mergeable if necessary.

### CODE REVIEW

**Comment by czue** [comment]
Oops sorry about that. I actually knew this was the behavior and thought it was better than not making it clickable which I guess was poor judgment.

Did you just manually edit the topojson file and change the ID and name? I think we can just change the v4 file and serve that. I also am not sure, but I think maybe we can just change the "map_name" custom property on the J&K state location in the DB and that might have done the same thing?

**Review by czue — APPROVED** [review]
This seems fine, though also proposed an alternate approach now that the demo is over: https://github.com/dimagi/commcare-hq/pull/26595. 

It also might be nice to document the name change that was used by reworking `split_j_and_k_state` to generate this file.

**Comment by calellowitz** [comment]
closing this in favor of Cory's solution

**Comment by Rohit25negi** [comment]
Not reviewing this based on the last comment of PR closing

**Comment by czue** [comment]
oops, yeah this should be closed now.

**Pull request closed without merging**
