### PR TITLE
cache app meta

### PR DESCRIPTION
**Pull request by snopoke**

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
build fail looks real:

```
.....................................................E
======================================================================
ERROR: test_hierarchy (corehq.apps.app_manager.tests.test_case_meta.CaseMetaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/app_manager/tests/test_case_meta.py", line 46, in test_hierarchy
    meta = app.get_case_metadata()
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/quickcache.py", line 183, in inner
    return helper(*args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/quickcache.py", line 70, in __call__
    key = self.get_cache_key(*args, **kwargs)
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/quickcache.py", line 118, in get_cache_key
    for value in values)
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/quickcache.py", line 117, in <genexpr>
    args_string = ','.join(self._serialize_for_key(value)
  File "/home/travis/build/dimagi/commcare-hq/corehq/util/quickcache.py", line 107, in _serialize_for_key
    raise ValueError('Bad type "{}": {}'.format(type(value), value))
ValueError: Bad type "<type 'NoneType'>": None
```

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by snopoke** [comment]
@czue :white_check_mark:

**Pull request merged**
