### PR TITLE
Catch null app ids so they dont bork reports

### PR DESCRIPTION
**Pull request by proteusvacuum**
http://manage.dimagi.com/default.asp?227500#1150490
http://manage.dimagi.com/default.asp?227504#1150500
@benrudolph @nickpell 
cc @dannyroberts

### CODE REVIEW

**Comment by benrudolph** [comment]
👍 ✔️

**Comment by emord** [comment]
Will this return all forms if you are looking for "Unknown forms" in the reports?

**Comment by benrudolph** [comment]
ah right totally forgot about that case. would it be possible to use the missing filter instead? https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/es/filters.py#L89

**Comment by benrudolph** [comment]
maybe a test to ensure it works?

**Comment by emord** [comment]
I'm not sure that'll work either. What happens when you submit a form for an app that no longer exists? I think it would still have an app id, but I don't think unknown forms would supply the correct one. (could be wrong on that one, just off the top of my head)

**Comment by benrudolph** [comment]
interesting, that's true. would have to dig in to see how we currently handle that case

**Comment by benrudolph** [comment]
this is gross but we could construct an OR filter to be either missing app_id OR not in the list of app_ids that we know

**Comment by emord** [comment]
Actually now that I'm looking a little harder, I don't think this should block merging. The query it also filters on xmlns. I think we only explicitly unique-ify xmlns based on app, but it shouldn't be common that multiple apps in the same domain have forms with the same xmlns (except for copying apps).

I think if we copy an app 2 times and delete the original and one copy, there wouldn't be a way to specify which deleted app you wanted, only xmlns. I think this should be a sufficient fix.

**Comment by emord** [comment]
> this is gross but we could construct an OR filter to be either missing app_id OR not in the list of app_ids that we know

I'm not sure we could do that either, because if you submit an unknown xmlns to an app that is known, there would be no way to get to that form without going through all of that app's forms.

**Comment by benrudolph** [comment]
haha we're just all around f'd! but i do think the xmlns being a specifier as you mentioned is probably fine

**Comment by emord** [comment]
:+1: on :white_check_mark:

**Pull request merged**
