### PR TITLE
add homepage icons to hq and formplayer

### PR DESCRIPTION
**Pull request by jmtroth0**
adds icons for ios to use as homepage icons following [this guide](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

There are 2 issues with this current setup: (1) ios turns the transparent bits of the icons black, which looks very not ideal. (2) having more sizes would be nice for larger/newer devices. 

For both of these I could just imagemagick and upload more images, but I'm not sure how our staticfiles setup works. Is there a guide to that somewhere?

@orangejenny buddy:@snopoke

### CODE REVIEW

**Comment by orangejenny** [comment]
> having more sizes would be nice for larger/newer devices

I don't think we do this anywhere on HQ but I'm sure we do it on dimagi.com. @biyeun can you advise?

**Comment by biyeun** [comment]
@jmtroth0 since this works off of the `{{ CUSTOM_LOGO_URL }}` these logos are likely to also only be transparent `.png`s. My suggestion is to use `PIL` to add a light gray background to the `png`, and serve those file urls as the icon urls. 

see `Pasting an Image onto Another Image` where it talks about how to remove the black background. I would suggest having a nice gray gradient square for the destination image to paste the logo over...
https://auth0.com/blog/image-processing-in-python-with-pillow/

**Comment by jmtroth0** [comment]
Ooh that package looks cool. Thanks

A couple things to confirm @biyeun: 

1) I was considering not using `CUSTOM_LOGO_URL` at all since we don't know the shapes of those images. Thoughts?
2) Would I need to save a that `light gray gradient` as a thing or could something like `Image.new('RGBA', (<icon_dimens>), 'grey')` work?
3) Do we have a normal place of saving that kind of file? Would it just go into the blobdb?

**Comment by jmtroth0** [comment]
Make sense.

@biyeun The other thing is that I don't want it to happen every time, since this will be on every single request right now. That's fine for the custom icons, I can just add it to the creation flow. Where are the current static assets kept so that I can add backgrounded ones to those? They seem to be in another repo or something? Also are the already made ones that I can just add?

**Comment by biyeun** [comment]
@jmtroth0 there isn't a readymade one, but i'll see if i can fit this in over the next day.

**Comment by biyeun** [comment]
@jmtroth0 added icons! sorry for the delay

**Comment by jmtroth0** [comment]
Thanks @biyeun. They look great! (Icon at top left)

**Review by biyeun — APPROVED** [review]

**Comment by biyeun** [comment]
@jmtroth0 yayy!

**Pull request merged**
