### PR TITLE
quickcache Repeater.by_domain

### PR DESCRIPTION
**Pull request by dannyroberts**
to reduce repeated queries to couch

### CODE REVIEW

**Comment by czue** [comment]
nice. i think we can also make this a stale query

**Comment by czue** [comment]
these things change very very rarely and i can't imagine it would be a problem if they were behind by a few seconds

**Comment by snopoke** [comment]
:+1: nice

**Comment by snopoke** [comment]
Could likely do the same with the `reminders/handlers_by_reminder_type` views

**Comment by czue** [comment]
builds failing:
```
======================================================================
ERROR: test_case_close_format (corehq.apps.receiverwrapper.tests.test_repeater.CaseRepeaterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/receiverwrapper/tests/test_repeater.py", line 234, in test_case_close_format
    payload = self.repeat_records(self.domain_name).all()[0].get_payload()
IndexError: list index out of range
----------------------------------------------------------------------
```
======================================================================
FAIL: test_add_repeater (corehq.apps.domain.tests.test_views.TestDomainViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/commcare-hq/corehq/apps/domain/tests/test_views.py", line 72, in test_add_repeater
    self.assertEqual(len(app_structure_repeaters), 1)
AssertionError: 0 != 1
----------------------------------------------------------------------
```

could probably add `vary_on=settings.UNIT_TESTING` (not sure exact syntax)

**Comment by czue** [comment]
@dannyroberts assume you'll work through test failures and ping when you're good

**Comment by dannyroberts** [comment]
Yup, but thanks for the bump. I think this last commit was the root cause—my invalidation wasn't working because the superclass list was in the wrong order.

**Comment by dannyroberts** [comment]
:white_check_mark:

**Comment by czue** [comment]
any thoughts on adding stale? seemed not worth it?

**Comment by dannyroberts** [comment]
That's a good idea, just not what I was looking at. I'll pull out that call and add stale ok.

**Comment by dannyroberts** [comment]
Hmm, it makes tests fail, and will probably make the user experience of creating a repeater confusing (when it reloads, the new one most likely won't be there. Both of those are solvable, but I think that's no longer worth the effort. (The nice thing about caching is that the invalidation is super neat, so it's actually airtight as long as you're going through the models.)

**Comment by czue** [comment]
sounds reasonable for now

**Pull request merged**
