### PR TITLE
soft assert no user registration api use

### PR DESCRIPTION
**Pull request by dannyroberts**
sanity check before we merge https://github.com/dimagi/commcare-hq/pull/12419

### CODE REVIEW

**Comment by gcapalbo** [comment]
:+1: just waiting on build to be safe

**Comment by czue** [comment]
tests are failing. think you have to remove them or use `softer_assert`.
```
======================================================================
FAIL: test_submit_user_registration (corehq.apps.receiverwrapper.tests.test_submissions.SubmissionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/receiverwrapper/tests/test_submissions.py", line 97, in test_submit_user_registration
    xmlns='http://openrosa.org/user/registration',
  File "/mnt/commcare-hq-ro/corehq/apps/receiverwrapper/tests/test_submissions.py", line 68, in _test
    self.assertEqual(n_times_saved, 1)
AssertionError: 2 != 1
-------------------- >> begin captured stdout << ---------------------
<function test_submit_user_registration at 0x7f89a38d6230> failed with the following settings:
settings.TESTS_SHOULD_USE_SQL_BACKEND = False
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
auditcare.middleware: DEBUG: Middleware is running in a test context, disabling monkeypatch
root: ERROR: someone actually called CommCareUser.create_or_update_from_xform
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/users/signals.py", line 61, in create_user_from_commcare_registration
    CommCareUser.create_or_update_from_xform(xform)
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1442, in create_or_update_from_xform
    _assert(False, 'someone actually called CommCareUser.create_or_update_from_xform')
  File "/mnt/commcare-hq-ro/corehq/util/soft_assert/core.py", line 33, in __call__
    return self._call(assertion, msg, obj)
  File "/mnt/commcare-hq-ro/corehq/util/soft_assert/core.py", line 47, in _call
    raise AssertionError(msg)
AssertionError: someone actually called CommCareUser.create_or_update_from_xform
root: ERROR: Receiver app: problem sending post-save signal <function create_user_from_commcare_registration at 0x7f89b00b1140> for xform d8d7ebf232cb7bce926e11e214f06024: AssertionError: someone actually called CommCareUser.create_or_update_from_xform
--------------------- >> end captured logging << ---------------------
```

**Comment by czue** [comment]
(still failing, will just let you ping when :white_check_mark: )
```
======================================================================
FAIL: use case: chw on phone registers a username/password/domain triple somewhere
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/users/tests/create.py", line 109, in testCreateDuplicateUsersFromRegistration
    first_user, created = CommCareUser.create_or_update_from_xform(self.xform)
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1447, in create_or_update_from_xform
    _assert(False, 'someone actually called CommCareUser.create_or_update_from_xform')
  File "/mnt/commcare-hq-ro/corehq/util/soft_assert/core.py", line 33, in __call__
    return self._call(assertion, msg, obj)
  File "/mnt/commcare-hq-ro/corehq/util/soft_assert/core.py", line 47, in _call
    raise AssertionError(msg)
AssertionError: someone actually called CommCareUser.create_or_update_from_xform
```

**Comment by dannyroberts** [comment]
✅

**Comment by czue** [comment]
thanks for the persistence

**Comment by dannyroberts** [comment]
haha 👍 you bet

**Pull request merged**
