### PR TITLE
Rate limit by the number of users "allocated"

### PR DESCRIPTION
**Pull request by dannyroberts**
##### SUMMARY
That means the number of users included in the subscription if the project is below that limit.

If a project is on a Pro plan and has 60 users, they'll now be rate limited as if they have 250 users (conceptually the number of users they're "paying for") instead of 60. This mostly makes it so projects that have a small number of users aren't disproportionally affected by rate limiting, and so there isn't this incentive to create a bunch of fake users to get more resources without paying extra, which seems silly to make people do.

##### FEATURE FLAG
Affects behavior of RATE_LIMIT_SUBMISSIONS and RATE_LIMIT_RESTORES, as well as datadog metrics for would-be rate limited submissions and restores.

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
This code looks pretty easy to test. Would be nice if those were added.

**Comment by dannyroberts** [comment]
Yeah I wanted to but I'm wrestling with the subscription setup and teardown. I'll take another pass later

**Review by biyeun — APPROVED** [review]

**Comment by millerdev** [comment]
In that case I apologize for my designation of "easy to test" because it sounds like it's not ...but tests still would be nice to have.

**Comment by dannyroberts** [comment]
Whew! Bit of a slog but managed to get some tests that cover all main branches `get_n_users_for_rate_limiting`.

**Review by millerdev — APPROVED** [review]

**Comment by millerdev** [comment]
Thanks!

**Pull request merged**
