### PR TITLE
Remove 'SMS Keyword' from UI

### PR DESCRIPTION
**Pull request by dannyroberts**
http://manage.dimagi.com/default.asp?186751
https://trello.com/c/shjqm7wP/15-sms-keyword-ui-in-supply

I think this is all that was being asked.

@gcapalbo @czue

### CODE REVIEW

**Comment by gcapalbo** [comment]
do we also need to remove the functionality that was tied to this configuration we're removing?

also the ticket suggests we should check that this functionality is not in use before removing it. has that been done?

**Comment by czue** [comment]
funny this sat around this long. i think this is safe to merge since it's just the config option.

> do we also need to remove the functionality that was tied to this configuration we're removing?
> 
> also the ticket suggests we should check that this functionality is not in use before removing it. has that been done?

yeah we should probably do both of these things. I would recommend putting a soft assert where this is used (which I think can be [here](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/commtrack/sms.py#L142)) and then if it doesn't fire for a month or something we can use that as an entrypoint to delete everything (which I think is everything to do with multiple action transactions).

**Comment by czue** [comment]
hooray for :skull:

**Comment by dannyroberts** [comment]
Oh initially I thought you were saying `config.multiaction_keyword` is never set to anything other than `'report'`, but after looking at the code you referenced, you're saying that no one ever uses `multiaction_keyword`, period, even though `multiaction_enabled=True` [by default](https://github.com/dimagi/commcare-hq/blob/d5550377a31a50b0b2c8216ce3c709dea040f409/corehq/apps/commtrack/util.py#L82-82). So your guess (or the thing you want to test with a soft assert) is that the code never actually makes it to [https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/commtrack/sms.py#L142](the line you linked to).

**Comment by czue** [comment]
that is correct. funny that it defaults to `True`

**Comment by dannyroberts** [comment]
soft assert: https://github.com/dimagi/commcare-hq/pull/12891

**Pull request merged**
