### PR TITLE
rabbitmq to es2

### PR DESCRIPTION
**Pull request by benrudolph**

### CODE REVIEW

**Comment by gcapalbo** [comment]
@benrudolph was this temporary just for tonight's deploy or is this a permanent change we want to make?

**Comment by benrudolph** [comment]
probably temporary. unclear what the plan is, just wanted to be transparent about what i was doing. added label

**Comment by benrudolph** [comment]
ok i think we're just going to keep this the way it is for now so we can go ahead and merge

**Comment by czue** [comment]
:mag: :rabbit2: <-------------------- :rabbit2: :elephant:

**Pull request merged**
