### PR TITLE
Allow end of form navigation from multi to single-select forms

### PR DESCRIPTION
**Pull request by nospame**
## Product Description
Allows end of form linking from multi-select to single-select forms.

## Technical Summary
[USH-3123](https://dimagi-dev.atlassian.net/browse/USH-3123)
Essentially a follow-up to https://github.com/dimagi/commcare-hq/pull/32468, removes build validation that disallowed a new app build with multi-select => single-select form links. These links should be possible but require manual linking.

## Feature Flag
ush_case_list_multi_select

### Safety story
Code added [here](https://github.com/dimagi/commcare-hq/commit/17a916f173c49ccf0f579a47b26f9191a08782a0) already ensures all links from multi-select forms must be linked manually. The validation being removed would only have applied to this particular circumstance: where an app builder wishes to link from a multi-select to a single-select form.

### Automated test coverage
Tests exist for [linking multi-select to single-select forms](https://github.com/dimagi/commcare-hq/blob/0399c4cfc3d81ce08f90874ee0e3fdb1bf3f5ef9/corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py#L591-L619) and [manual linking required from multi-select forms](https://github.com/dimagi/commcare-hq/blob/0399c4cfc3d81ce08f90874ee0e3fdb1bf3f5ef9/corehq/apps/app_manager/tests/test_views.py#L345-L380).

### QA Plan
[QA-5018](https://dimagi-dev.atlassian.net/browse/QA-5018?atlOrigin=eyJpIjoiYjA5NjcxODJjODMwNDdjMmE4MDlhMzBhNmZjNWZhYjgiLCJwIjoiaiJ9)

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

[USH-3123]: https://dimagi-dev.atlassian.net/browse/USH-3123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[QA-5018]: https://dimagi-dev.atlassian.net/browse/QA-5018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by stephherbers** [comment]
change makes sense based on our convo earlier today. I think this is a great thing to add to the multi-select case lists docs on confluence.
Also any luck on finding a way to test this? I dug in briefly and didn't see anything too close that's already being tested, but I think it would be worth adding if possible

**Comment by nospame** [comment]
> change makes sense based on our convo earlier today. I think this is a great thing to add to the multi-select case lists docs on confluence. Also any luck on finding a way to test this? I dug in briefly and didn't see anything too close that's already being tested, but I think it would be worth adding if possible

I interpreted [this test](https://github.com/dimagi/commcare-hq/blob/0399c4cfc3d81ce08f90874ee0e3fdb1bf3f5ef9/corehq/apps/app_manager/tests/test_suite_multi_select_case_list.py#L591-L619) as checking that the basic workflow is possible and adds to the suite correctly. I also didn't find examples of testing manual linking (which _sort of_ makes sense for something necessarily user-defined). I guess I'm not sure what exactly needs to be tested that's getting missed with what exists.

**Review by snopoke — COMMENTED** [review]
~~It would be useful to have a test case that shows how this linking is supposed to work (app config and suite XML test).~~

The test you linked is what I was expecting to see.

**Comment by nospame** [comment]
The app configuration around this workflow can get pretty complex, but after a bit of a dive on how it could/should work, QA is considering this passed ([QA-5018](https://dimagi-dev.atlassian.net/browse/QA-5018)). @snopoke Do you have any other concerns about this change that would keep you from approving?

Also noting the actual workflow delivery wants to use is currently blocked ([USH-3134](https://dimagi-dev.atlassian.net/browse/USH-3134)) but that does not appear related to lifting the restriction on multi-select -> single-select form nav.

**Review by snopoke — APPROVED** [review]

**Pull request merged**
