### PR TITLE
Allow session auth for user-domains API, and clean up decorators

### PR DESCRIPTION
**Pull request by czue**
## Summary

Ran into this while working on https://github.com/dimagi/commcare-hq/pull/29001 and decided to fix it in the meantime. Then in the process realized I could clean up some copy/paste redundancy in our API auth code.

## Product Description

Enables the [User Domains API](https://confluence.dimagi.com/display/commcarepublic/User+Domain+List) to load in a browser if you're already logged in.

## Safety Assurance

I'm not sure I agree this is high risk though am not sure I understand how those terms should be used in today's HQ climate.

- [ ] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [ ] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

There is good test coverage for the functions and classes that changed in [test_auth.py](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/api/tests/test_auth.py)

### Safety story

It is a relatively mechanical refactor, plus a tiny change in functionality and the code is well-tested.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Comment by czue** [comment]
The tests cover API key auth and basic auth. I attempted to manually test digest auth locally with curl, and it didn't work. Then I tried on master and it didn't work. Then I tried against production HQ and it also didn't work. Is it possible digest auth is just broken on all our APIs? Or is something wrong with this command (this is a user account without 2FA enabled, that was another whole can of worms...)

```
curl -v --digest -u 'cory.zue@gmail.com:****'  'https://www.commcarehq.org/a/sabbatical/api/v0.5/application/'
```

**Comment by snopoke** [comment]
CURL command looks fine to me. When I run it I do see the digest auth workflow happening via the CURL log output.

**Comment by czue** [comment]
> CURL command looks fine to me. When I run it I do see the digest auth workflow happening via the CURL log output.

Yeah, same. Did you successfully auth, or you agree it's not working with HQ?

**Comment by snopoke** [comment]
> > CURL command looks fine to me. When I run it I do see the digest auth workflow happening via the CURL log output.
> 
> Yeah, same. Did you successfully auth, or you agree it's not working with HQ?

No it did not. Changing to `--basic` worked but not with `--digest`

**Comment by czue** [comment]
Ok, cool good to know. Interestingly, I figured out (after realizing DET uses digest) that it still works for the Case API. Will look into it.

Do you agree this PR is safe to merge?

**Comment by snopoke** [comment]
@czue I think it's safe to merge

**Comment by czue** [comment]
Great thanks. Also got to the bottom of the digest auth issue: https://github.com/dimagi/commcare-hq/pull/29008

**Pull request merged**
