### PR TITLE
log error before creating PillowError

### PR DESCRIPTION
**Pull request by nickpell**
https://manage.dimagi.com/default.asp?260368#BugEvent.1390660

@proteusvacuum @emord

### CODE REVIEW

**Review by emord — COMMENTED** [review]
I think that this sort of error should crash the pillow, and we shouldn't make any progress on the kafka queue until the main db is in a good state again.

**Review by proteusvacuum — COMMENTED** [review]
Won't this log the same error twice? What if you just caught the exception, and set `error_id` to "error creating PillowError" or something.

**Comment by nickpell** [comment]
> What if you just caught the exception, and set error_id to "error creating PillowError" or something.

updated

**Comment by nickpell** [comment]
> I think that this sort of error should crash the pillow, and we shouldn't make any progress on the kafka queue until the main db is in a good state again.

I think so too.  I'd like to log the doc id just to help understand if the bug referenced above is somehow related to these failures or not.

**Review by kaapstorm — APPROVED** [review]

**Pull request merged**
