### PR TITLE
enterprise domain user filter for user history report

### PR DESCRIPTION
**Pull request by snopoke**
## Product Description
New user filter for the user history report which shows all users in the enterprise.

## Technical Summary
New approach to https://github.com/dimagi/commcare-hq/pull/30777 and https://github.com/dimagi/commcare-hq/pull/30831 that doesn't change the functionality of the base filters.

Jira: https://dimagi-dev.atlassian.net/browse/USH-1316

The approach here is to create a new filter that is used solely for this report (though could be used for other reports in the future).

Notes:
- I removed the options to filter by group and location since they don't make sense in a cross domain context and also because they are mostly designed for filtering data. This report is for user auditing so filtering my group / location doesn't seem as useful.
- The filter / options endpoint are safe for use on non-enterprise domains, they will give the same results as a single domain filter.

## Feature Flag
USER_HISTORY_REPORT

### Safety story
This is a change to an unreleased report (still behind a FF). This PR does also expose a new endpoint for the filter but tests for the data source that powers the view have been added to verify that it safe even on non-enterprise domains.

### Automated test coverage
Added tests for the filter and for the options controller

### QA Plan
I plan to put this on staging and test it there.

### Migrations
NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by stephherbers** [comment]
@snopoke I have a PR out for this: https://github.com/dimagi/commcare-hq/pull/30831 I took a different approach thinking about how we are going to want to transition to have all user filters use the enterprise domain filter soon, so then the only modification we would need for that is to add `get_enterprise_controlled_domains` in two places within the `ExpandedMobileWorkerFilter`

**Review by esoergel — APPROVED** [review]

**Comment by orangejenny** [comment]
@snopoke This seems to remove the ability to search for locations in the filter: https://dimagi-dev.atlassian.net/browse/USH-370?focusedCommentId=183522

**Comment by esoergel** [comment]
@orangejenny that was deliberate, as per [this comment](https://github.com/dimagi/commcare-hq/pull/30831#issuecomment-994554240)

**Review by stephherbers — APPROVED** [review]

**Comment by snopoke** [comment]
I've updated the user display to include the domain name for mobile users:
image

**Pull request merged**
