### PR TITLE
Show Left Nav bar on case importer pade

### PR DESCRIPTION
**Pull request by Rohit25negi**
http://manage.dimagi.com/default.asp?283411

### CODE REVIEW

**Comment by orangejenny** [comment]
So the nav is showing, which is good and is the only thing the ticket explicitly asked for, but could you also take a look at making the appropriate page highlight? You could either highlight the "Import Cases from Excel" item for the entire workflow, or add another item below it that matches the breadcrumb for the individual page ("Case Options" for the second step and "Match Excel Columns to Case Properties" for the third). Whichever is simpler to do is fine, it's just so there's something highlighted to give the user a better idea of where they are.

The second option, adding a new item, is done in places like the setup tab when adding a new product:
screen shot 2018-10-02 at 11 56 20 am

**Comment by Rohit25negi** [comment]
> So the nav is showing, which is good and is the only thing the ticket explicitly asked for, but could you also take a look at making the appropriate page highlight? You could either highlight the "Import Cases from Excel" item for the entire workflow, or add another item below it that matches the breadcrumb for the individual page ("Case Options" for the second step and "Match Excel Columns to Case Properties" for the third). Whichever is simpler to do is fine, it's just so there's something highlighted to give the user a better idea of where they are.
> 
> The second option, adding a new item, is done in places like the setup tab when adding a new product:
> screen shot 2018-10-02 at 11 56 20 am

Cool, got it. I will go for the second one 💯

**Comment by Rohit25negi** [comment]
Changes in this are done. Added the subpages for entire flow. ready for final review

**Review by orangejenny — APPROVED** [review]

**Review by dannyroberts — APPROVED** [review]
@Rohit25negi looks good to me! Glad the final code to do this ended up being pretty clean!

@orangejenny any last points?

**Comment by orangejenny** [comment]
@dannyroberts nope, looks good to me

**Pull request merged**
