### PR TITLE
Eliminate trailing whitespace in bootstrap diffs

### PR DESCRIPTION
**Pull request by orangejenny**
## Technical Summary
The diffs produced by `difflib` have a lot of trailing whitespace, which means PRs that update diffs inevitably fail the flake8 check. This isn't strictly a problem - we can still merge - but it makes that check noisy/untrustworthy.

We don't expect trailing whitespace in any of the files that get diffed.

### Safety story
Changes to an internal management command

### Automated test coverage

kind of: this command builds diff files that are used in a test

### QA Plan

no

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by millerdev — APPROVED** [review]
> PRs that update diffs inevitably fail the flake8 check

I'm slightly surprised that flake8 produces lint warnings for `.txt` files. Is that expected/do we know why it's doing that?

~Looks like diffs will need to be rebuilt before this can be merged.~

**Comment by orangejenny** [comment]
I'm also surprised. I've poked around the [flake8 options](https://flake8.pycqa.org/en/latest/user/options.html) a bit but haven't yet found info on either what file types are checked by default or how to entirely ignore files by extension/pattern. Although I suppose I could add a rule to just ignore the trailing whitespace rule for these diff files.

**Comment by millerdev** [comment]
Interesting. [`--filename`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-filename) defaults to `*.py` and I don't think we are overriding that. Maybe try using [`--extend-exclude`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-exclude) to ignore `*.txt`?

**Comment by orangejenny** [comment]
@millerdev That's a much better idea. Thank you for reading docs for me. I don't know why I got stuck on editing the diff files themselves. Opened https://github.com/dimagi/commcare-hq/pull/34307

**Pull request closed without merging**
