### PR TITLE
celery hotfix

### PR DESCRIPTION
**Pull request by czue**

### CODE REVIEW

**Comment by nickpell** [comment]
@czue Is this still needed?

**Comment by czue** [comment]
@nickpell do you mean the change? I have no idea and unfortunately not a lot of context in this PR.

**Comment by czue** [comment]
I can try to go digging for what this fixed if you really need to know though.

**Comment by nickpell** [comment]
I'm wondering if we can remove djcelery since it's only used here and http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html says it's not needed anymore.  The project doesn't look well-maintained and doesn't officially support django 1.9.

**Comment by czue** [comment]
if this is literally the only usage i think we can get rid of it. not sure how to validate/QA that though, but we could just try and pay close attention (?)

**Comment by nickpell** [comment]
that's my favorite way to program :)

**Pull request merged**
