### PR TITLE
fix - switch cash bonus conditions for atri, wazirganj

### PR DESCRIPTION
**Pull request by sravfeyn**
@esoergel

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by esoergel** [comment]
The tests need to be updated to correspond to this change.  They're database-free though, so it's very quick.  `./manage.py test opm`

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Pull request merged**
