### PR TITLE
avoid AttributeError

### PR DESCRIPTION
**Pull request by sravfeyn**
Fixes https://sentry.io/organizations/dimagi/issues/879362573/

@calellowitz

### CODE REVIEW

**Review by kaapstorm — APPROVED** [review]

**Comment by calellowitz** [comment]
Is it weird that we are trying to do stats calculations on a domain that doesn't exist? That doesn't seem like it should happen.

**Comment by kaapstorm** [comment]
I should have checked the Sentry error. :grimacing: You're right, @calellowitz. This function is called by [`calced_props()`](https://github.com/dimagi/commcare-hq/blob/de4db717a7d35b2f142ed57a8f46f210de2219f7/corehq/apps/domain/calculations.py#L353) and it is called by [`update_calculated_properties()`](https://github.com/dimagi/commcare-hq/blob/77f468de100a12dd49d3cfe0cbedd370828366ea/corehq/apps/reports/tasks.py#L147). If the domain doesn't exist, we should deal with that there before we try to get its calculated properties.

**Comment by sravfeyn** [comment]
I think I tested this for a domain that actually had this issue so I missed the domain not existing issue. I added a check to see if the domain exists and delete from ES if not. Though, i am not sure why a domain that's deleted from Couch exists in ES at all (the domain pillow should have deleted it)

**Comment by sravfeyn** [comment]
I have also made a slight refactor passing domain object to avoid fetching it in multiple places in various calculation functions.

**Review by kaapstorm — APPROVED** [review]

**Comment by kaapstorm** [comment]
Thanks @sravfeyn 

Yeah, how deleted domains are in ES is ... weird.

**Pull request merged**
