### PR TITLE
Fix JSON syntax in template app

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?216939

introduced by https://github.com/dimagi/commcare-hq/commit/01f967861a69bae8bd6a8d6dd73b723c7dc373a4

@esoergel / @dannyroberts

### CODE REVIEW

**Comment by czue** [comment]
bonus points for adding a test! I'd be keen to merge and deploy now so we can get back to the two new users who got hit by this today

**Comment by czue** [comment]
(assume you ran the test you added)

**Comment by orangejenny** [comment]
yeah, ran the test

**Comment by orangejenny** [comment]
will deploy

**Pull request merged**
