### PR TITLE
add a hidden url that just renders the base template

### PR DESCRIPTION
**Pull request by dannyroberts**
this could be useful for profiling, as well as monitoring the load time of this page over time
my hypothesis is that it slowly increases over time as we add more stuff to it

### CODE REVIEW

**Comment by benrudolph** [comment]
might be useful to set up some sort of pingdom or service that hits it so we have records of it over time

**Comment by czue** [comment]
agreed. this feels like the type of thing that we should be able to setup a report for with the data we have. not saying that's in scope but just supporting the idea

**Comment by dannyroberts** [comment]
Thanks, guys. That was the general type of thing I was considering, so good to see independent corroboration :) I think I'm going to go with pingdom + a dashboard graphing base template load times alongside average site-wide load times. (Pingdom's only purpose in this setup would be to get an nginx.timings entry into datadog every minute like a cron job.)

**Comment by dannyroberts** [comment]
Silly me, when I tried to set it up I remembered it's a login-required url. Will have to enable basic auth probably.

**Comment by benrudolph** [comment]
fyi, we may need a new pingdom account if we go that way. i believe we've used all our pings in our current version

**Pull request merged**
