### PR TITLE
Static SIte updates

### PR DESCRIPTION
**Pull request by biyeun**
pls merge for comms. not user facing yet

### CODE REVIEW

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Comment by czue** [comment]
@biyeun just out of curiosity, is there a reason comms can't use staging?

**Comment by czue** [comment]
are there any alternatives to keeping the images in the repo? I can see the argument in terms of making this self-contained and not having to worry about keeping things in sync, however it seems like if we did something like a CDN that would a) be faster and b) keep the repository from getting too huge. not sure if @biyeun or others have thoughts.

**Comment by czue** [comment]
didn't review super closely but this looks good to me overall, pending any other possibilities to the images-in-the-repo question.

**Comment by biyeun** [comment]
self-containment would be nice...

**Comment by biyeun** [comment]
also, i was mainly trying to get this on prod over staging simply because it's not public...and staging merge conflicts...seems annoying to have to deal with when i'm just touching the static site. :|

**Comment by dimagimon** [comment]
:+1: No lint errors found.

**Pull request closed without merging**
