### PR TITLE
[Release Branch] Community / Trial Revamp & Feature Reallocation 

### PR DESCRIPTION
**Pull request by biyeun**
##### SUMMARY
This is the final release branch for the community / trial revamp work and feature reallocation. All code in here has been previously reviewed in separate sub-PRs.

Here's my [secret gist](https://gist.github.com/biyeun/d1d48c6ff4138810e02bbd407e0ab43d) where I kept track of the different PRs (which as of this moment have all been merged)

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Comment by biyeun** [comment]
i hate repeaters

**Comment by biyeun** [comment]
github...why u assign ppl to review when i did no such thing. hrmph

**Comment by biyeun** [comment]
FINALLY THE TESTS ALL PASSED!!!!! AAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
✅ 

...i'm going to bed.

**Comment by kaapstorm** [comment]
:tada:

**Pull request merged**
