### PR TITLE
Pause pingdom alerts on restart

### PR DESCRIPTION
**Pull request by benrudolph**
@dimagi/watchmen this adds a pause to services restart so we can stop getting those notifications. pretty straightforward, but gonna give it a go on staging first anyways

cc: @gcapalbo

### CODE REVIEW

**Comment by kaapstorm** [comment]
Nice.

**Comment by czue** [comment]
looks good. 

for the :watch: !

**Comment by czue** [comment]
also build fail looks real:
```
Traceback (most recent call last):
  File "manage.py", line 73, in <module>
    execute_from_command_line(sys.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/vendor/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vendor/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/vendor/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/mnt/custom/ilsgateway/__init__.py", line 1, in <module>
    from custom.ilsgateway.comparison_reports import ProductsCompareReport, LocationsCompareReport, \
  File "/mnt/custom/ilsgateway/comparison_reports.py", line 13, in <module>
    from custom.ilsgateway.api import ILSGatewayEndpoint
  File "/mnt/custom/ilsgateway/api.py", line 17, in <module>
    from custom.ilsgateway.models import SupplyPointStatus, DeliveryGroupReport, HistoricalLocationGroup, \
  File "/mnt/custom/ilsgateway/models.py", line 8, in <module>
    from corehq.apps.users.views import EditWebUserView
  File "/mnt/corehq/apps/users/views/__init__.py", line 41, in <module>
    from corehq.apps.domain.views import BaseDomainView
  File "/mnt/corehq/apps/domain/views.py", line 98, in <module>
    from corehq.apps.hqwebapp.views import BaseSectionPageView, BasePageView, CRUDPaginatedViewMixin
  File "/mnt/corehq/apps/hqwebapp/views.py", line 62, in <module>
    from corehq.apps.hqadmin.management.commands.celery_deploy_in_progress import DEPLOY_IN_PROGRESS_FLAG
ImportError: No module named celery_deploy_in_progress
```

**Comment by benrudolph** [comment]
oops yep thanks

**Comment by benrudolph** [comment]
:white_check_mark: ran fine on staging deploy

**Pull request merged**
