### PR TITLE
add expression to add days to a date

### PR DESCRIPTION
**Pull request by czue**
:fish: if you like

@nickpell @NoahCarnahan cc @benrudolph @esoergel @sheelio

### CODE REVIEW

**Comment by benrudolph** [comment]
:basketball: slamdunk

**Comment by nickpell** [comment]
I'm very interested in the etymology of :fish:

**Comment by czue** [comment]
it's quite simple:

commit-by-commit --> blow-by-blow --> :blowfish: / :blowfish: --> :blowfish: --> :fish: (or :tropical_fish: / :dolphin: :whale: )

surprised you didn't obviously pick that up.

**Comment by nickpell** [comment]
:open_mouth:

**Comment by benrudolph** [comment]
i'm a fan of reserving :whale: for giant :fish: PRs. also i like the new sea creature repertoire. they're much more visually appealing than the :blowfish:

**Comment by esoergel** [comment]
Lot's of :fish: :blowfish: :tropical_fish: :whale: :whale2: :dolphin: :swimmer:  in the :ocean:

**Pull request merged**
