### PR TITLE
don't try to serialize NoneType

### PR DESCRIPTION
**Pull request by nickpell**
http://manage.dimagi.com/default.asp?227246

@emord cc: @kaapstorm

### CODE REVIEW

**Comment by emord** [comment]
Does this only happen on new apps/forms that haven't been edited?

**Comment by nickpell** [comment]
I haven't looked into reproing the bug from scratch, just noting that it's reproducible at the URL in the ticket

**Comment by emord** [comment]
:+1: on :white_check_mark:

**Comment by nickpell** [comment]
✅

**Pull request merged**
