### PR TITLE
attempt to use a different Redis DB for tests

### PR DESCRIPTION
**Pull request by snopoke**
## Technical Summary
Attempt to use a different Redis DB for tests to avoid polluting the main cache.

Also a change to `dev_settings.py` to match the production Redis client settings.

### Safety story
Only affects tests.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by millerdev** [comment]
Working on a review, but have not had time to finish yet. Please do not merge this.

**Comment by snopoke** [comment]
> Working on a review, but have not had time to finish yet. Please do not merge this.

Thanks @millerdev, no need to rush.

**Review by millerdev — CHANGES_REQUESTED** [review]
What about a solution where it looks for a test setting rather than guessing for an unused database number? Something like

`settings.py`
```py
TEST_CACHE_LOCATIONS = {}
```

`docker/localsettings.py` and `dev_settings.py` would be similar
```py
redis_cache = {
    'BACKEND': 'django_redis.cache.RedisCache',
    'LOCATION': f'redis://{redis_host}:6379/0',
}
CACHES = {
    'default': redis_cache,
    'redis': redis_cache
}
TEST_CACHE_LOCATIONS = {
    'default': f'redis://{redis_host}:6379/1',
    'redis': f'redis://{redis_host}:6379/1',
}
```

`testsettings.py`
```py
helper.update_redis_location_for_tests(CACHES, TEST_CACHE_LOCATIONS)  # noqa: F405
```

`settingshelper.py`
```py
def update_redis_location_for_tests(settings_caches, test_locations):
    non_test_locations = {c.get("LOCATION") for c in settings_caches.values()}
    for name, config in settings_caches.items():
        if not config.get("BACKEND", "").startswith("django_redis"):
            continue
        try:
            if test_locations[name] in non_test_locations:
                raise RuntimeError(
                    f"TEST_CACHE_LOCATIONS[{name!r}] has the same value "
                    "as a non-test redis DB. Please update "
                    "TEST_CACHE_LOCATIONS so the values do not collide "
                    "with CACHES[*]['LOCATION']."
                )
            config["LOCATION"] = test_locations[name]
        except KeyError:
            raise RuntimeError(
                f"TEST_CACHE_LOCATIONS[{name!r}] is not set. "
                "This setting is required to run tests. "
                "See dev_settings.py for an example."
            )
```

Update: Could add this to testsettings.py if it's unpalatable to have`TEST_CACHE_LOCATIONS` in settings.py:
```py
if 'TEST_CACHE_LOCATIONS' not in globals():
    TEST_CACHE_LOCATIONS = {}
```

**Comment by millerdev** [comment]
We still need a way of clearing the test cache after the test run (or maybe before) to prevent the earlier test runs from polluting the cache of later runs, right?

**Comment by millerdev** [comment]
Updated code above to error on collisions with non-test caches.

**Comment by snopoke** [comment]
> We still need a way of clearing the test cache after the test run (or maybe before) to prevent the earlier test runs from polluting the cache of later runs, right?

That would be good but isn't part of this PR

**Comment by snopoke** [comment]
@millerdev I think your suggestion of making a `TEST_CACHE_LOCATIONS` setting is great. I'll submit a new PR with that approach.

**Comment by snopoke** [comment]
Replaced by https://github.com/dimagi/commcare-hq/pull/31427

**Pull request closed without merging**
