### PR TITLE
Make current language available for suite file calculations

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?188421

Adds `lang.current` locale id to each app_strings file (value "en", "fra", etc.) and makes this available as variable `$lang` to calculation properties in case list/detail.

@dannyroberts / @proteusvacuum

### CODE REVIEW

**Comment by proteusvacuum** [comment]
The code looks good. 
Not sure I totally understand how this works on mobile... does returning a `<locale />` always return the current locale?
According to [Suite20](https://github.com/dimagi/commcare/wiki/Suite20#text), I thought that `<locale/>` blocks returned the text they reference?

**Comment by proteusvacuum** [comment]
Ah, nvm. I think I figured it out. You add `locale.current` into app_strings:
https://github.com/dimagi/commcare-hq/pull/9573/files#diff-329ee688b2c4355e88a4fe7abb4237acR38 
which I think gets used as the locale resource on the phone.

**Comment by orangejenny** [comment]
@proteusvacuum yep yep

**Comment by proteusvacuum** [comment]
Thanks!

**Comment by dannyroberts** [comment]
It occurs to me that it could be confusing to be able to type $lang in this one place, but not in Form Display Conditions or inside forms. I think this is fine for now, but at some point we'll likely want to standardize the syntax of what goes in those boxes. Nothing actionable just a thought.

**Comment by orangejenny** [comment]
good thought

**Comment by proteusvacuum** [comment]
was there a reason this wasn't `#lang` which is how we reference other things that we replace magically (e.g. #case, #form)?

**Comment by proteusvacuum** [comment]
@dannyroberts made me realize that this is an anachronistic comment since #form and #case may not have even been around when we made this change. 

however, I think namespacing things like this in the future is a good idea! like `$commcare_lang` or somesuch.

**Comment by orangejenny** [comment]
Yeah, I don't think they existed at the time. Agree that `$commcare_lang` would have been a better choice, I wasn't thinking about users putting custom variables in apps at the time this was written.

**Pull request merged**
