### PR TITLE
Make Volatility Warnings Persistent

### PR DESCRIPTION
**Pull request by ctsims**
Changes Volatility warnings from transient (expire after 30 seconds) to persistent, and moves color to red

image

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by orangejenny** [comment]
How are users supposed to interpret that message? Is there anything they should do when they see it?

**Comment by ctsims** [comment]
@orangejenny In theory it's an indication that a case was assigned to two people and you should move to the next case in your queue rather than proceeding.

**Comment by orangejenny** [comment]
@ctsims Thanks. I'd like to show more specific instructions but can see how "move to the next case in your queue" won't necessarily make sense for all projects.

**Comment by ctsims** [comment]
@orangejenny Yeah, I think one tricky thing is that different projects expect users to do something different when they get these, so it'll be hard to have a one-size-fits-all approach to the messages. I was waiting to iterate based on user feedback, but the feedback cycle i'm seeing (which has just been "make the message harder to ignore" twice, with escalating metrics for "harder") leads me to believe that if this isn't more useful after this cycle we should just kill it.

**Pull request merged**
