### PR TITLE
increase domain column length

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?236053

@gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
looks good to me - @nickpell is this ok, and can you think of anywhere else the billable code might have trouble with a long domain name?

**Comment by nickpell** [comment]
https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/accounting/models.py#L1761 should be updated.

https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/accounting/models.py#L889 and https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/accounting/models.py#L334 are all set.

**Comment by snopoke** [comment]
updated

**Comment by nickpell** [comment]
looks good

**Pull request merged**
