### PR TITLE
Fiximmunization

### PR DESCRIPTION
**Pull request by katembu**

### CODE REVIEW

**Comment by dimagimon** [comment]
There are 7 errors:

* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 27 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 29 - ['moderate_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 32 - ['severe_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 42 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 44 - ['muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 51 - ['routine_muac'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 61 - ['active_gam'] is better written in dot notation.

**Comment by dimagimon** [comment]
There are 7 errors:

* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 27 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 29 - ['moderate_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 32 - ['severe_muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 42 - ['muac_reading'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 44 - ['muac_wasting'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 51 - ['routine_muac'] is better written in dot notation.
* custom/_legacy/mvp_indicators/mvp_child_health_indicators/views/child_muac/map.js, line 61 - ['active_gam'] is better written in dot notation.

**Comment by katembu** [comment]
@biyeun is it necessary to convert the variable object to dot notation?

**Comment by czue** [comment]
@katembu I think not necessary though also not hard :)

**Comment by czue** [comment]
@biyeun if this looks good let's try to get it in today so we can run one big reindex for the other stuff

**Pull request merged**
