### PR TITLE
Upgrade SQLAlchemy

### PR DESCRIPTION
**Pull request by emord**
I think we're about to get a github vulnerability alert. Last time I tried this there were some test errors (though that was on 1.3.0 and not the latest versions). just openeing for tests at the moment

### CODE REVIEW

**Comment by emord** [comment]
```
======================================================================
ERROR: corehq.apps.userreports.tests.test_report_data:ReportDataTest.test_basic_query
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/tests/test_report_data.py", line 176, in test_basic_query
    report_data = report_data_source.get_data()
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/reports/data_source.py", line 129, in get_data
    data = self.data_source.get_data(start, limit)
  File "/vendor/lib/python2.7/site-packages/memoized.py", line 13, in _inner
    return m(*args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/memoized.py", line 133, in __call__
    value = self.func( *args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/decorators.py", line 31, in _inner
    return func(*args, **kwargs)
  File "/vendor/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/sql/data_source.py", line 71, in get_data
    ret = super(ConfigurableReportSqlDataSource, self).get_data(start=start, limit=limit)
  File "/mnt/commcare-hq-ro/corehq/apps/reports/sqlreport.py", line 268, in get_data
    data = self._get_data(start=start, limit=limit)
  File "/mnt/commcare-hq-ro/corehq/apps/reports/sqlreport.py", line 306, in _get_data
    return qc.resolve(session.connection(), self.filter_values)
  File "/vendor/lib/python2.7/site-packages/sqlagg/base.py", line 261, in resolve
    result = qm.execute(self.connection, filter_values or {})
  File "/vendor/lib/python2.7/site-packages/sqlagg/base.py", line 100, in execute
    return connection.execute(query, **filter_values).fetchall()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1098, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 468, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 562, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2115, in visit_select
    text, select, inner_columns, froms, byfrom, kwargs
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2227, in _compose_select_body
    text += self.order_by_clause(select, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2286, in order_by_clause
    order_by = select._order_by_clause._compiler_dispatch(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 104, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 970, in visit_clauselist
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 968, in <genexpr>
    s
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 970, in <genexpr>
    c._compiler_dispatch(self, **kw) for c in clauselist.clauses
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 104, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 1200, in visit_unary
    unary, OPERATORS[unary.modifier], **kw
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 1343, in _generate_generic_unary_modifier
    return unary.element._compiler_dispatch(self, **kw) + opstring
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 104, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 772, in visit_textual_label_reference
    "Can't resolve label reference for ORDER BY / GROUP BY.",
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression u'just_for_sorting' should be explicitly declared as text(u'just_for_sorting')
---------------------------------------------------------------------
```

**Comment by emord** [comment]
I think https://github.com/dimagi/sql-agg/blob/master/sqlagg/sorting.py#L14 needs to be escaped in some way

**Comment by snopoke** [comment]
odd, sql-agg is tested with sqlalchemy 1.3.3 and all tests pass.

**Comment by emord** [comment]
> odd, sql-agg is tested with sqlalchemy 1.3.3 and all tests pass.

@snopoke That's because there's a sqlinjection in UCR https://github.com/dimagi/sql-agg/pull/57

**Comment by emord** [comment]
:white_check_mark:

**Review by kaapstorm — APPROVED** [review]

**Review by snopoke — APPROVED** [review]

**Pull request merged**
