### PR TITLE
[SSO-ish] change iFrame domain login template to inherit from main login template

### PR DESCRIPTION
**Pull request by biyeun**
## Summary
This PR ensures that `iframe_domain_login.html` inherits from the main login template, including all that crucial javascript that is necessary to assist with logging in SSO users. 

Will do a formal QA of this on staging, but have already tested it locally and it works wonderfully.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage
No test coverage here.

### QA Plan
QA will be scheduled for this next week.

### Safety story
Will undergo QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
This couples elements of these templates in a way that might make it hard for someone editing the login template to know they may need to also edit the iframe template, which is scary. It's questionable in my mind whether the inheritance is worth it, especially given that the interdependencies are not covered by tests.

Would it be possible to refactor the common part of the login template into a separate template that would be inherited by both of these templates? Alternately, maybe have the inheritance go in the opposite direction since it seems the iframe template only hides/removes things from the login template?

**Comment by biyeun** [comment]
@millerdev I think if someone IS making an edit to the login template, they should also be aware of the iframe login capability. This seems necessary, tbh, and can be solved by adding a comment in the login template to ensure their changes are compatible with iframe logins as well.

**Comment by orangejenny** [comment]
> I think if someone IS making an edit to the login template, they should also be aware of the iframe login capability.

I would not assume this, as I don't think the iframe login is used by that many clients. At the same time, issues with it are highly visible for those clients who do use it. It's a risky combination.

I'm more worried that someone will make a change to `base.html` and it'll show up on the iframe login page.

**Review by orangejenny — CHANGES_REQUESTED** [review]
Marking this "request changes" as a reminder to remove the ES6 syntax. See https://github.com/dimagi/commcare-hq/pull/29834

**Comment by biyeun** [comment]
@orangejenny @millerdev ok I made sure iframe login inherited from a different base template. I think this should address all the outstanding feedback :)

**Review by millerdev — COMMENTED** [review]
It looks like `base_no_navigation.html` is a new template that is only used by `iframe_domain_login.html`. Do I have that right?

- Since this new base template is only used by the iframe login template, why not just merge the two into the iframe template? The down-side to that being that there is duplication between the base template and the iframe login template, but it seems like you are already creating that duplication with the new base template.
- It seems like this new base template (or the iframe template) will need to be kept in sync with the other/main base template. Is that right? I had imagined that the existing base template would inherit from a new template like `base_no_navigation.html` so the common parts could be shared between the base template and this iframe login page. Is there a reason you didn't do that?

**Comment by biyeun** [comment]
@millerdev so I kept it as a separate base template so that it would be in the same place as all the other `base_` base templates (there are a number of them). I'm reluctant to share hierarchy here as I'm purposely only supporting requirejs to keep readability easier...and it's weird to have `base.html` inherit from yet another base template. Better would be a rename but that is majorly out of scope for this work.

I would rather not merge this template with `iframe_domain_login.html` purely for ease of discoverability in case a) a non-navigation base template was needed by another view and b) that all of the base templates (any template including the `<html>` tag) are in the same place

**Comment by orangejenny** [comment]
I do like the thought of merging the new template with the iframe template. There are already pages that use `<html>` scattered in random places, like the SMS chat page (finding them all has been necessary a few times for the various js modernizations). For the rename issue, are there really that many references to `base.html`? I thought most of our templates inherit from `base_section.html` so they get the left-hand nav. Even if you didn't do the rename now, having a temporarily poorly-named template seems easier to address in the future than de-duplicating code.

**Comment by biyeun** [comment]
@orangejenny @millerdev how about this now?

**Review by millerdev — APPROVED** [review]
Thanks.

**Comment by biyeun** [comment]
Thank you @millerdev! Submitted for QA now. ^_^

**Review by orangejenny — APPROVED** [review]
It's great to see the duplication gone - thank you for working through this @biyeun !

**Pull request merged**
