### PR TITLE
Move sync settings to General section

### PR DESCRIPTION
**Pull request by orangejenny**
http://manage.dimagi.com/default.asp?243119

@kaapstorm / @sravfeyn

### CODE REVIEW

**Comment by sravfeyn** [comment]
Thanks Jenny!

**Comment by czue** [comment]
nice. have we looked for any doc updates that need to happen?

**Comment by orangejenny** [comment]
@czue Good point. Just did a confluence search and found, curiously, all the references to these settings either specify "General Settings" or don't mention a section.

**Comment by czue** [comment]
nice, thanks for checking!

**Pull request merged**
