### PR TITLE
Fix non keyword agg for ES7

### PR DESCRIPTION
**Pull request by sravfeyn**
Aggregating on non-keyword fields in Elasticsearch 7 is not supported (returns this kind of error https://sentry.io/organizations/dimagi/issues/1912906733/?environment=staging&project=136860&query=is%3Aunresolved). Since most of aggs are done on keywords, I have updated the code to use keyword fields where available and update mapping to keywords where we don't have keywords. A reindex for existing envs is not required (except for staging, which I will do in a separate branch), so I am not updating the mapping names.

There are various such use-cases that didn't have tests. So, they haven't popped up in build (and also QA for some reason). To find them, I grepped through the code base for ES aggregations, reviewed and fixed them. For where tests are easy to add, I have added them.

@snopoke

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
It's quite critical that we find all of these before doing the upgrade. How confident are you that your search was exhaustive? Do we have any logging from a prod environment that we could interrogate?

**Comment by sravfeyn** [comment]
> It's quite critical that we find all of these before doing the upgrade. How confident are you that your search was exhaustive? Do we have any logging from a prod environment that we could interrogate?

Agreed, it's critical to find all of these. I reviewed each of the usages of `TermsAggregation` and `ESQuery.terms_aggregation` for which this is the issue, I am fairly confident but it will be good to get another set of eyes. 

Also, I have now added a soft-assert that can validate queries on production.  https://github.com/dimagi/commcare-hq/pull/28648/commits/8710ef4bef532e04d9d4b06acf2cd931a616be1c

**Comment by snopoke** [comment]
Test failures seem possibly related

**Comment by dannyroberts** [comment]
We had to roll this back because it breaks user lists and other queries to the user es index. (https://github.com/dimagi/commcare-hq/pull/28695). I'm sending a retro. Could I ask that for ES7 upgrade related changes you always ping someone from SaaS, by default @millerdev?

Who knows how it would have turned out, but I there's a good chance we would have flagged this for smoke testing on staging if we'd seen it.

**Comment by esoergel** [comment]
I'm guessing the issue here was that the mapping change wasn't rolled out.  User queries exclude deleted users by default by checking the `base_doc` field.  Since this field is currently analyzed, it's set in ES to `couchuser`, and `filters.term` will only do a case sensitive match on that.  This PR sets that default filter to check against `CouchUser`, which will be the value only after the index is migrated.

**Comment by orangejenny** [comment]
@esoergel So there's a mapping change required other than the changes to case_mapping and user_mapping that are in this PR?

**Comment by esoergel** [comment]
Those are the correct changes, but since the index name wasn't updated, the deploy tools didn't automatically run a reindex to apply the new mappings.  I think the oversight was that this change was misread as backwards-compatible:  

> A reindex for existing envs is not required (except for staging, which I will do in a separate branch), so I am not updating the mapping names.

**Comment by millerdev** [comment]
Would it be possible to add an automated test that fails if index code changes, but the index name is not updated (without causing too many false-negatives)?

**Comment by sravfeyn** [comment]
Sorry about the hiccup here. I will put this under a QA before trying to fix this this time.

> Could I ask that for ES7 upgrade related changes you always ping someone from SaaS, by default @millerdev?

Sure Danny, will do it in future.

>  I think the oversight was that this change was misread as backwards-compatible:

Yes, that's the oversight. Thanks for explaining here. I was trying to avoid what I thought an unnecessary reindex. Since it doesn't work, I will create a separate PR that also triggers a reindex.

**Comment by esoergel** [comment]
@millerdev that would be pretty straightforward, IMO.  You could write a test iterating over the `ElasticsearchIndexInfo` instances, checking the index name and the hash of the `json.dumps` of the mapping against a hardcoded constant.  Then any mapping update would cause a test failure, and we could put a reminder in there (you could still change only the hash and not the name, it'd just be harder).

FWIW at one point, the index name was of the format `{index_alias}_{mapping_hash}`, which if tested, would guarantee the name is updated.

**Pull request merged**
