### PR TITLE
Faster code pull

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @esoergel gonna give this a spin on staging. i'm thinking this'll shave a few mins off of deploy

### CODE REVIEW

**Comment by czue** [comment]
:+1: from me when you're happy with testing.

**Comment by benrudolph** [comment]
(played around with this on staging and it doesn't work as expected, gonna have to read some more)

**Comment by esoergel** [comment]
That's odd, I would've expected this to work.  Any idea what happens?  Does it complain about not recognizing the refs?

**Comment by benrudolph** [comment]
ok i think we chased it down to a bug in git. we'll be updating the git version (currently we're using 1.7.9.5) and that should allow us to do this faster pull

**Comment by benrudolph** [comment]
tested this out twice and it's working fine

**Pull request merged**
