### PR TITLE
[B5] Migrate case search page

### PR DESCRIPTION
**Pull request by jingcheng16**
## Technical Summary

Applied all suggestions I got from #34430 

**Form for search parameters**
Before:
image
After:
image

**Results Tab**
Before:
image
After:
image

**Query Tab**
Before:
image
After:
image

**Profile Tab**
Before:
image
After:
image

## Feature Flag

(required) Turn on the "[Enable extension sync](https://www.commcarehq.org/hq/flags/edit/extension_sync/?__hstc=240960668.2195ac63c0056c39905e6882865ae8e3.1597171287126.1616447050240.1616526330286.228&__hssc=240960668.8.1616526330286&__hsfp=1126783430)" feature flag

(required) Turn on the "[Enable synchronous mobile searching and case claiming](https://www.commcarehq.org/hq/flags/edit/search_claim/)" feature flag

### Safety story

Internal page. Tested locally and on staging

### QA Plan

No QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by orangejenny — COMMENTED** [review]
Just one comment: since your last commit updated the diff config, can you run `build_bootstrap5_diffs` once more? That'll delete the case_search diff files.

(In general, whenever you update that file, you should rebuild diffs.)

**Comment by jingcheng16** [comment]
@orangejenny Hi Jenny, I didn't run `build_bootstrap5_diffs` yet because in migration guide:
> Please refrain from including commits from build_bootstrap5_diffs in the branch you push to staging

Maybe I take my branch off staging and run `build_bootstrap5_diffs` since I have take the screenshots?

**Comment by orangejenny** [comment]
@jingcheng16 Ah, I see. That makes sense. Now that you're at the point where you're about to merge - you've tested on staging, I've reviewed everything in the PR except for the diff files - I'd go ahead and run it. You can pull the branch off staging if you're done testing, sure, that'll guarantee no merge conflicts.

**Comment by jingcheng16** [comment]
@orangejenny Thanks Jenny! I pushed the commit for rebuild b5 diffs: d569ffea230243a54d1d684bb3873fff8cf488fe

**Review by orangejenny — APPROVED** [review]
Looks good

**Pull request merged**
