### PR TITLE
Rename New CloudCare toggle, make product path

### PR DESCRIPTION
**Pull request by wpride**

### CODE REVIEW

**Comment by czue** [comment]
thanks boss. no test coverage.

**Comment by benrudolph** [comment]
at some point we should make it so that if you turn this flag on it automatically uses the correct backend (not sure if that's the case now)

**Comment by benrudolph** [comment]
(just read your email, seems like that's the case already)

**Comment by wpride** [comment]
Yeah there's no configuration possible where you use the new frontend
without the new backend (which is made unclear by the separate flags - we
should probably kill the "use formplayer backend" flag soonish).

**Pull request merged**
