### PR TITLE
add index on blobmeta table for efficient attachment deletion

### PR DESCRIPTION
**Pull request by snopoke**
##### SUMMARY
This should speed up the [delete_old_images](https://github.com/dimagi/commcare-hq/blob/cc93bc6ab718bde08e8d16e374d5cc25eff94958/custom/icds/tasks/__init__.py#L15) tasks dramatically. The current query does a sequence scan on the table.

Only adding this for ICDS since the task is ICDS specific.

### CODE REVIEW

**Review by millerdev — APPROVED** [review]

**Comment by mkangia** [comment]
Is there a benefit to other environments by keeping it just on ICDS?

just thinking in future if this is released/used more on other environments, it would be confusing that one environment had the index and others don't. Having different schemas can be hard to notice.

**Review by sravfeyn — APPROVED** [review]

**Comment by snopoke** [comment]
> Is there a benefit to other environments by keeping it just on ICDS?

Indexes to consume memory and IO so having less indexes is better.

**Comment by mkangia** [comment]
@snopoke build failure looks related.

**Comment by mkangia** [comment]
> Indexes to consume memory and IO so having less indexes is better.

Agreed. Just not sure how its still better to just keep it to one env. But since two people already thinks its okay, fine to drop it.

**Comment by snopoke** [comment]
> Just not sure how its still better to just keep it to one env.

If this were a change to the table itself I would certainly not do it for just one env but an index is a somewhat invisible thing in terms of the code so it's unlikely to cause issues or incompatibility between environments which is why I think it's OK to have it only on one env.

**Comment by snopoke** [comment]
closing in favour of https://github.com/dimagi/commcare-hq/pull/25709

**Pull request closed without merging**
