### PR TITLE
Kill anonymous web apps

### PR DESCRIPTION
**Pull request by orangejenny**
Cleared with @wpride / @ctsims 

@gcapalbo

### CODE REVIEW

**Comment by wpride** [comment]
:tada: This is awesome Jenny!

**Comment by wpride** [comment]
Getting in on the action https://github.com/dimagi/formplayer/pull/665

**Comment by orangejenny** [comment]
@wpride excellent

**Review by gcapalbo — APPROVED** [review]
@snopoke fyi i think there will be conflicts with this and https://github.com/dimagi/commcare-hq/pull/20953

**Comment by snopoke** [comment]
@gcapalbo :+1:

**Comment by emord** [comment]
I don't think this needs the "reindex/migration" flag. Deleting views shouldn't cause a reindex. In a week when we're sure we won't revert/this is deployed everywhere, we'll want to run a management command `prune_couch_views`  to delete the view from couch .

**Comment by orangejenny** [comment]
@emord thanks for the explanation, will merge when tests pass

**Comment by emord** [comment]
May want to get some verification from @dannyroberts first. I'd feel pretty silly if i was mistaken (copying for him)

> Deleting views shouldn't cause a reindex. In a week when we're sure we won't revert/this is deployed everywhere, we'll want to run a management command prune_couch_views to delete the view from couch .

**Comment by orangejenny** [comment]
@emord @dannyroberts Looked through my slack history and found Danny & I having this same conversation the last time I deleted a couch view. The conclusion was that deleting a view should also include kicking off a preindex.

**Comment by dannyroberts** [comment]
@orangejenny @emord deleting a single view from a design doc that has multiple views _does_ require a reindex, deleting an entire design doc (for us == deleting a view that's the only view in its design doc) _doesn't_. The view being deleted here is named `hash_to_anonymous_app/view` and is the only only view in the `hash_to_anonymous_app` design doc, so deleting it happily doesn't require a reindex; if this view was the only thing keeping the reindex label on there, I think you can remove it.

**Comment by orangejenny** [comment]
@dannyroberts Re-removing label, thanks for the thorough explanation :)

**Pull request merged**
