### PR TITLE
Minor requirements updates

### PR DESCRIPTION
**Pull request by gherceg**
## Technical Summary

Commits are sorted in order of my confidence that they should be merged, from most to least.

#### More confident commits

I noticed that I couldn't build documentation with dev-requirements, which was annoying and due to the lack of myst-parser. I resolved this in 9125f8298d9aee2dcf84f2b14b2ba781ca4bf5be.

I then just sorted requirements in dev-requirements alphabetically in 7a5c33650878bdb135bc994eb4ffd49e6cd0437a. 

#### Less confident commits

From there, I was eyeing the `docutils` dependency wondering if we actually need to explicitly include that for docs builds. As far as I could tell, we didn't directly reference it anywhere, but am unsure if I'm missing something? Anyway I removed the explicit dependency in 357aa3ca67fad06a240d1f8311e3558f4182a16e

After that, I was trying to grapple with why we specify doc requirements in dev-requirements.in, rather than including them from the actual docs-requirements.in file. I didn't have a good answer, so I made that change in 6ca95b2ae0972f05c6fad4f4c4dd85f8c77f4577.

That's my thought process in a nutshell. The docs build continued to work as I made these changes, so seems safe.

### Safety story

At most, only impacting docs and dev requirements. Adding to that that we have a workflow check to ensure the docs build succeeds, this seems like a very safe change.
### Automated test coverage

No.
### QA Plan

No QA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by joxl — APPROVED** [review]
This is really nice. It should also make the docs requirements more "robust" in that they can't deviate into a conflicting state with dev/test requirements. I'm a fan of this change.

**Comment by gherceg** [comment]
Pinging @kaapstorm since I've seen you worked in this area a couple of years ago, which I suppose is "recent". No worries if you don't have any context to add.

**Review by snopoke — APPROVED** [review]
Nice cleanup

**Review by kaapstorm — APPROVED** [review]
This is great. Thanks @gherceg

**Review by millerdev — APPROVED** [review]

**Pull request merged**
