### PR TITLE
Fabfile updates

### PR DESCRIPTION
**Pull request by esoergel**
Nothing to see here.  Just merge and move along.  Feel free to add to it if you're so inclined ;)

### CODE REVIEW

**Comment by snopoke** [comment]
Ha ha April fools

**Comment by czue** [comment]
I give this an over/under shelf life of about 4 days. I hope it works today though.

**Comment by snopoke** [comment]
Yes, we agreed that it would be reverted tomorrow.

On 1 April 2015 at 14:34, Cory Zue <notifications@github.com> wrote:

> I give this an over/under shelf life of about 4 days. I hope it works
> today though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/6132#issuecomment-88462444>.
>



-- 
Simon Kelly
Senior Engineer | Dimagi South Africa

**Comment by benrudolph** [comment]
:see_no_evil:

**Pull request merged**
