### PR TITLE
use UUID for location map case ID on SQL domains

### PR DESCRIPTION
**Pull request by snopoke**
@nickpell 

FYI @dimagi/scale-team

### CODE REVIEW

**Comment by nickpell** [comment]
:+1: when :white_check_mark:

**Comment by nickpell** [comment]
failure looks real:
```
ERROR: test_force_consumption (corehq.apps.commtrack.tests.test_xml.CommTrackOTATest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 200, in fn_with_pre_and_post
    run_config.pre_run(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/form_processor/tests/utils.py", line 127, in <lambda>
    pre_run=lambda *args, **kwargs: args[0].setUp(),
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 50, in setUp
    super(CommTrackOTATest, self).setUp()
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/util.py", line 173, in setUp
    self.users = [bootstrap_user(self, **user_def) for user_def in self.user_definitions]
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/util.py", line 84, in bootstrap_user
    user.set_location(setup.loc)
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1659, in set_location
    self.create_location_delegates([location])
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1800, in create_location_delegates
    self.clear_location_delegates()
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1781, in clear_location_delegates
    mapping = self.get_location_map_case()
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1831, in get_location_map_case
    return CaseAccessors(self.domain).get_case(location_map_case_id(self))
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/util.py", line 224, in location_map_case_id
    return uuid.uuid5(const.MOBILE_WORKER_UUID_NS, user.user_id)
  File "/usr/local/lib/python2.7/uuid.py", line 589, in uuid5
    hash = sha1(namespace.bytes + name).digest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 1: ordinal not in range(128)
```

**Comment by nickpell** [comment]
```
ERROR: test_force_consumption (corehq.apps.commtrack.tests.test_xml.CommTrackOTATest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 200, in fn_with_pre_and_post
    run_config.pre_run(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/form_processor/tests/utils.py", line 127, in <lambda>
    pre_run=lambda *args, **kwargs: args[0].setUp(),
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/test_xml.py", line 50, in setUp
    super(CommTrackOTATest, self).setUp()
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/util.py", line 173, in setUp
    self.users = [bootstrap_user(self, **user_def) for user_def in self.user_definitions]
  File "/mnt/commcare-hq-ro/corehq/apps/commtrack/tests/util.py", line 84, in bootstrap_user
    user.set_location(setup.loc)
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1659, in set_location
    self.create_location_delegates([location])
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1800, in create_location_delegates
    self.clear_location_delegates()
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1781, in clear_location_delegates
    mapping = self.get_location_map_case()
  File "/mnt/commcare-hq-ro/corehq/apps/users/models.py", line 1831, in get_location_map_case
    return CaseAccessors(self.domain).get_case(location_map_case_id(self))
  File "/mnt/commcare-hq-ro/corehq/form_processor/interfaces/dbaccessors.py", line 256, in get_case
    return self.db_accessor.get_case(case_id)
  File "/mnt/commcare-hq-ro/corehq/form_processor/backends/sql/dbaccessors.py", line 332, in get_case
    return CommCareCaseSQL.objects.raw('SELECT * from get_case_by_id(%s)', [case_id])[0]
  File "/vendor/lib/python2.7/site-packages/django/db/models/query.py", line 1598, in __getitem__
    return list(self)[k]
  File "/vendor/lib/python2.7/site-packages/django/db/models/query.py", line 1535, in __iter__
    query = iter(self.query)
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/query.py", line 78, in __iter__
    self._execute_query()
  File "/vendor/lib/python2.7/site-packages/django/db/models/sql/query.py", line 92, in _execute_query
    self.cursor.execute(self.sql, self.params)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/vendor/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/vendor/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: function get_case_by_id(uuid) does not exist
LINE 1: SELECT * from get_case_by_id('f4f1f1cd-d9cc-5393-90c4-8c220a...
```

**Comment by millerdev** [comment]
Tests for `location_map_case_id` would be nice

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
