### PR TITLE
don't verify nimbus SSL

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?246037

This is to get around the issue on NIC where we have two certs for
the nginx site and requests is using the wrong one (the first
in the list).

@benrudolph @calellowitz

### CODE REVIEW

**Review by benrudolph — APPROVED** [review]

**Comment by czue** [comment]
thanks for super quick turnaround!

**Comment by millerdev** [comment]
Would it make sense to only skip verification if some flag that says it's OK to skip verification is set (and only set that flag on NIC)? In general it's best practice to always verify SSL.

**Comment by millerdev** [comment]
Curious if people care about the comment I made above, or if we think it's not an issue to always be skipping SSL verification here?

**Comment by snopoke** [comment]
I was thinking that it wasn't enough of an issue for a short term workaround. Since we now have working SSL for ICDS we can revert this: #14716

**Pull request merged**
