### PR TITLE
Tweak atwho autocomplete

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @wpride a little 🎁 this cleans up the usability of the autocomplete a bit. making strides
autocomplete

- No space after insert
- Ensure that we only attempt to match when there are at least 2 characters
- Move the cursor inbetween parens for functions

cc: @snopoke @emord

### CODE REVIEW

**Comment by czue** [comment]
> only match when we've typed 2 characters

yes! this will be so much nicer.

**Review by snopoke — APPROVED** [review]
makes me want to fire up app preview to play with it

**Comment by benrudolph** [comment]
🔥 do it!

**Review by emord — APPROVED** [review]
We should port htis to formbuilder :)

**Comment by snopoke** [comment]
https://trello.com/c/6ptcOmY8/18-autocomplete-of-commcare-functions-in-vellum

**Comment by czue** [comment]
js tests failed :(

```
  1 failing
  1) Debugger EvaluateXPath should correctly match xpath input:
     AssertionError: expected null to equal ''
      at http://localhost:8000/static/chai/chai.js:210
      at http://localhost:8000/static/chai/chai.js:2178
      at http://localhost:8000/static/cloudcare/js/form_entry/spec/debugger_spec.js:12
>> 1/44 tests failed (0.31s)
Warning: Task "mocha:cloudcare#form_entry" failed. Use --force to continue.
```

**Comment by benrudolph** [comment]
classic. thanks, updating

**Comment by benrudolph** [comment]
✅ JS tests passed

**Pull request merged**
