### PR TITLE
Truncate tab name from middle

### PR DESCRIPTION
**Pull request by michelleliang1**
https://dimagi-dev.atlassian.net/browse/SAAS-10911

##### SUMMARY

Follow up to PR#28298. 

Truncate the middle part of the excel tab name to retain the most relevant information.
If there's an uneven split of characters between beginning and end part of the name, favor the beginning.

##### FEATURE FLAG

N/A

##### RISK ASSESSMENT / QA PLAN

N/A

### CODE REVIEW

**Review by orangejenny — COMMENTED** [review]
Could you add a couple of tests for `UniqueHeaderGenerator` to `test_writer.py`? It's gotten just complex enough that it'd be really helpful to have proof that there aren't any finicky little bugs: off-by-one errors, or issues with odd vs even number of characters, etc.

**Review by orangejenny — APPROVED** [review]
what beautiful tests, thank you for adding them!

**Comment by michelleliang1** [comment]
Yay! of course, no problem!

**Comment by michelleliang1** [comment]
Test failure looks unrelated/timeout error. Will merge

**Pull request merged**
