### PR TITLE
vellum:b8e74d2c3ce5de0961042844f1827a325e5370c3 updates CKEditor to 4.21.0

### PR DESCRIPTION
**Pull request by ajeety4**
updates CkEditor to 4.21.0
[ci skip]

## Product Description

See Upstream Vellum PR: https://github.com/dimagi/Vellum/pull/1081

## Technical Summary

https://dimagi-dev.atlassian.net/browse/INDIV-88

### QA Plan

QA was passed on staging.
https://dimagi-dev.atlassian.net/browse/QA-4973

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Comment by millerdev** [comment]
Closing and opening to run tests.

**Review by millerdev — APPROVED** [review]
There's more churn in [manifest.txt](https://github.com/dimagi/commcare-hq/pull/32861/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=#diff-d3ef152508dc75e66ed298ad1da2a4717afad0f27872d765804957f79ee492da) than I would expect. Maybe that's a side-effect of upgrading CKEditor or maybe a bunch of other dependencies were updated in addition? In any case since this passed QA it's probably not a problem.

Edit: I don't understand why github is not running tests.

**Comment by ajeety4** [comment]
> There's more churn in [manifest.txt](https://github.com/dimagi/commcare-hq/pull/32861/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=#diff-d3ef152508dc75e66ed298ad1da2a4717afad0f27872d765804957f79ee492da) than I would expect. Maybe that's a side-effect of upgrading CKEditor or maybe a bunch of other dependencies were updated in addition? In any case since this passed QA it's probably not a problem.
> 
> Edit: I don't understand why github is not running tests.

For manifest.text churn, not anything specific to CKEditor, however this does include some dependency updates on Vellum since last merge.
https://github.com/dimagi/Vellum/commit/a68c0b7b5cb85bcab8f8074c944494a40fec5faf and https://github.com/dimagi/Vellum/commit/52333e9a0abf2b53152952ebfbf6294762b38d28 contains most of them.

**Comment by ajeety4** [comment]
Closing and reopening again to run tests.

**Pull request merged**
