### PR TITLE
fix for bulk export only repeats

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?232720
@emord 

cc @NoahCarnahan @gcapalbo

### CODE REVIEW

**Comment by benrudolph** [comment]
nice, i'm sure this was fun 😄

**Comment by snopoke** [comment]
Not as bad as I thought it might be

**Comment by emord** [comment]
```
======================================================================
FAIL: test_update_adherence_confidence (custom.enikshay.integrations.ninetyninedots.tests.test_integration.NinetyNineDotsCaseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 232, in inner
    return helper(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 205, in __call__
    call_with_settings(fn_with_pre_and_post, run_config.settings, args, kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 220, in call_with_settings
    fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/corehq/util/test_utils.py", line 201, in fn_with_pre_and_post
    self.fn(*args, **kwargs)
  File "/mnt/commcare-hq-ro/custom/enikshay/integrations/ninetyninedots/tests/test_integration.py", line 236, in test_update_adherence_confidence
    'medium',
AssertionError: u'new_confidence_level' != 'medium'

```

I don't think this is related @proteusvacuum might know?

**Comment by proteusvacuum** [comment]
kicked build, but I think I see why this is intermittently failing. Will fix.

**Pull request merged**
