### PR TITLE
Kill facilities

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@czue something like this? :smiling_imp:

@proteusvacuum @orangejenny

**Comment by orangejenny** [comment]
looks beautiful

**Comment by dannyroberts** [comment]
:white_check_mark: @czue should I test this somehow? I was relatively careful (though not completely paranoid) about checking references both to corehq.apps.facilities in python and references to urls etc throughout the repo, so logically this shouldn't break anything.

**Comment by czue** [comment]
:skull: :factory: :boom:

**Comment by dannyroberts** [comment]
:goberserk:

**Pull request merged**
