### PR TITLE
Allow explicit disable with `!` for random toggles 

### PR DESCRIPTION
**Pull request by dannyroberts**
## Product Description
No change for end users.

## Technical Summary
https://dimagi.atlassian.net/browse/SAAS-15765
This change allows us (administrators) to explicit disable random toggles using `!`, e.g. `!mydomain` or `user:!myuser`. This will allow us to, with a single toggle, specify a set of (say) domains to enable for, a set of domains to _disable_ for, and the ability to dynamically change the default for all other domains not specified to disabled (0), enabled (1), or predictably-randomly enabled or disabled at any percentage. Previously everything there was possible except for the ability to explicitly disable specific domains when the randomness was set to anything other than 0.

## Feature Flag
Not specific to a particular feature flag, but does add possible functionality to every `DynamicallyPredictablyRandomToggle` and `FeatureRelease` feature flag.

### Safety story
This is a pretty straightforward tack-on that shouldn't interrupt any existing behavior, unless someone has been using the prefix `!` with some other intended meaning, which I don't believe is the case. This also only affects random toggles (`DynamicallyPredictablyRandomToggle` and `FeatureRelease`), and only those that do not have `NAMESPACE_OTHER` (or technically any namespace not in `ALL_NAMESPACES`) in their namespaces list. That narrows it down to:
- WEB_APPS_UPLOAD_QUESTIONS / web_apps_upload_questions
- SAVE_ONLY_EDITED_FORM_FIELDS / save-only-edited-form-fields
- SMS_USE_LATEST_DEV_APP / sms_use_latest_dev_app
- FORMPLAYER_INCLUDE_STATE_HASH / formplayer_include_state_hash
- SORT_OUT_OF_ORDER_FORM_SUBMISSIONS_SQL / sort_out_of_order_form_submissions_sql
- RATE_LIMIT_RESTORES / rate_limit_restores
- LIVEQUERY_READ_FROM_STANDBYS / livequery_read_from_standbys

None of these toggles have any items containing `!`.

### Automated test coverage

I extended existing tests to cover this change, and there are fairly good tests for this area in general. I made sure new test additions failed before any related code changes, and that the code changes made them pass.
### QA Plan
None

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Nice. Would be great to highlight it in the UI to make it clearer.

**Review by gherceg — APPROVED** [review]
Thanks for adding tests!

**Comment by dannyroberts** [comment]
> Nice. Would be great to highlight it in the UI to make it clearer.

Just noting that my local dev environment got messed up as I was trying to quickly develop and test a simple UI addition prompted by this suggestion, so I might not be able to get to it today.

**Comment by dannyroberts** [comment]
@snopoke I went ahead and addressed the UI feedback in a separate PR here https://github.com/dimagi/commcare-hq/pull/34902.

**Pull request merged**
